### ISSUE TITLE
[Figgy/production] ActionView::Template::Error: undefined method `sort_by' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1007]
## Backtrace

    line 2 of [PROJECT_ROOT]/app/views/records/edit_fields/_member_of_collection_ids.html.erb: _app_views_records_edit_fields__member_of_collection_ids_html_erb__4331512781171642807_70275432141820
    line 2 of [PROJECT_ROOT]/valhalla/app/views/valhalla/base/_form_metadata.html.erb: block in _valhalla_app_views_valhalla_base__form_metadata_html_erb__61801908037148982_70275457573980
    line 1 of [PROJECT_ROOT]/valhalla/app/views/valhalla/base/_form_metadata.html.erb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/35862747)

**Comment by hackmastera** [comment]
This error occurs after hitting "save and ingest".  I can replicate the error on staging with id `6981507`. regardless of whether / how many collections I select. Why would the edit_field be rendering at that time? And how can I replicate on dev to debug?

**Comment by hackmastera** [comment]
The change set created at https://github.com/pulibrary/figgy/blob/master/valhalla/app/controllers/concerns/valhalla/resource_controller.rb#L24 is not valid due to `{:source_metadata_identifier=>[{:error=>"Error retrieving metadata"}]}`

**Comment by hackmastera** [comment]
They erroneously received the call number for the item instead of the bib number, hence the metadata error. Closing.
