### ISSUE TITLE
Migrate Milberg plates to SimpleResource objects

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1032]
There are a set of JPEGs in an Omeka exhibit for Milberg located at http://libphp-dev.princeton.edu/milberg. We'd like to migrate these plates to Figgy so we can stop maintaining that old Omeka site. These plates should show up in DPUL.

Write a migration script against the Omeka-xml API to create SimpleResource objects.

**Comment by escowles** [comment]
@kevinreiss will have info for accessing the metadata and files, possibly via an Omeka API or JSON dump

**Comment by kevinreiss** [comment]
The current Omeka (running v 2.6) is at http://libphp-dev.princeton.edu/milberg. Each "book" is an Omeka Collection Type with the individual plates represented as Items. The REST API gives you basic information on each type, https://omeka.readthedocs.io/en/latest/Reference/api/index.html. API root endpoint is http://libphp-dev.princeton.edu/milberg/api/. The API is a bit basic if you are an authenticated user Omeka will dump out a lot more information about the collection (including ordered Items attached to that collection) or item with these JSON views.

http://libphp-dev.princeton.edu/milberg/admin/collections/show/158?output=omeka-json
http://libphp-dev.princeton.edu/milberg/admin/items/show/1588?output=omeka-json

You might also want to look at the Omeka-S new release that includes an Omeka 2 importer module that might have some useful pointers at an easy way to migrate data. High Quality JPEGs just reside in the "original" directory in the Omeka install's files directory. The JSON views above provide URLs for the each item's associated files.

**Comment by hackmastera** [comment]
@kevinreiss I get errors when I try to reach those JSON views.

**Comment by kevinreiss** [comment]
Sorry, apparently the later version of Omeka the site is running (2.6) provides only an "omeka-xml" version of the detailed object dump. The 2.0 version the site was running until yesterday would send back json. I guess it was deprecated at some point.

**Comment by escowles** [comment]
Need metadata

**Comment by escowles** [comment]
I spoke to @kelea99 about this project this morning, and these items will be used in the next exhibit.  She is working with Kevin to get metadata exported from Omeka, and hopefully we can match the metadata with the TIFFs.  If not, ingesting the highest-quality JPEGs we have is a reasonable alternative given the tight timeline.

**Comment by kelea99** [comment]
@escowles , @kevinreiss  and I will be working on this next week

**Comment by tpendragon** [comment]
@kelea99 @escowles What's the story here? Do we close this?

**Comment by kelea99** [comment]
I think we should hold of on migrating anything until it is decided what we want to do with all of them. those that were needed for the milberg show were ingested as title only by me and metadata was added directly in DPUL for the exhibition.
