### ISSUE TITLE
Match Milberg TIFFs with metadata/JPEGs

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1033]
JPEGs were ingested into Omeka, but there were TIFF images, and it would be nice to ingest these.

**Comment by tpendragon** [comment]
@kevinreiss Did anybody ever find TIFFs? If not, can we close this?

**Comment by escowles** [comment]
Closing this issue since we haven't heard back about TIFFs — we can track the ingest of these items in #1032
