### ISSUE TITLE
Add BookPlate (SimpleResource) indexer that ensures workflow state is "published"

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1040]
see, e.g., https://github.com/pulibrary/figgy/blob/master/app/indexers/ephemera_folder_indexer.rb#L19

Use this as an opportunity to investigate the functionality of `suppressed?` workflow states. Are they used? If so, how? If not, should they be used? Maybe by an `Ability` rule that is then used by indexers more broadly?

**Comment by escowles** [comment]
AFAICT, the `suppressed?` workflow method is not being used anywhere.  But IMHO, it would be good to explore whether we can handle suppression-by-workflow-state in a general way instead of having custom indexers.

**Comment by hackmastera** [comment]
Yeah, I've started sifting through code to get a sense of where these tentacles are.

so far it seems like there's not access to the workflow's `suppressed?` method at indexing time or in the ability class. maybe that's why the method is never used?
