### ISSUE TITLE
Refactor fixity job specs to use `expect...to_have_been_enqueued`

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1042]
this looks pretty great we should do it too https://github.com/samvera/hyrax/pull/2911

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/commit/80488e8d8b0b54a063e4a98b9d509a1516c0f440 We did it a few months ago.

**Comment by hackmastera** [comment]
It's crept in again since then; I'll rename the issue.

https://github.com/pulibrary/figgy/blob/master/spec/jobs/check_fixity_recursive_job_spec.rb#L36

**Comment by tpendragon** [comment]
:+1: Nice catch.
