### ISSUE TITLE
Inconsistent permissions in Cicognara items

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1060]
There are several hundred Cicognara items that are public/complete, but attempting to retrieve the manifest while not logged in results in a 403 Forbidden or 500 Internal Server Error.  A list of the impacted records is here:

https://docs.google.com/spreadsheets/d/1dF-ByK7D2S1Kz7Ia1VyW2JUBfQmK-FDJUBSfWqmrDAw/edit

**Comment by tpendragon** [comment]
Weird. I looked at this and got https://app.honeybadger.io/projects/53391/faults/36808346#notice-comments. It looks like the object isn't in the database?

**Comment by tpendragon** [comment]
This is weird! https://figgy.princeton.edu/concern/scanned_resources/57cf9a5f-3c1c-465a-987d-92084152600a/edit loads fine, but the manifest throws an object not found error.

**Comment by tpendragon** [comment]
Got it!

https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder.rb#L427 is being thrown, and then rescued, and then it tries to find it by local identifier.

**Comment by tpendragon** [comment]
I think there's a FileSet set as the thumbnail which exists but has no derivatives generated.

**Comment by tpendragon** [comment]
I think this is fixed. @escowles have you confirmed this, given that you generated the spreadsheet?

**Comment by escowles** [comment]
Yes, the permissions on those items have been fixed.
