### ISSUE TITLE
add preview screen to archival media collection import form

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1097]
The preview screen should have a hierarchical display of what the item would look like after ingest, generated by parsing the EAD and matching components within the bag.

Wireframe:
![Screen Shot 2018-07-25 at 12.18.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56214b84e38e6c1200c6a5a3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f66b7191a379ed0c2a59415e4abc21254d58eeb9cb74fce36f34985619e8806a0e74c46c15aeeed61cba52ba208f1a80b4bb824896fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f348e34851a210366ae075306e0a.png)

**Comment by tpendragon** [comment]
The preview screen should have a hierarchical display of what the item would look like after ingest, generated by parsing the EAD and matching components within the bag.

**Comment by hackmastera** [comment]
If #3021 works well then this is less important.

We can assume a valid bag at this stage (an invalid bag would fail later on actual ingest)
