### ISSUE TITLE
When an imported bibdata record already has an identifier, it overrides the resource identifier

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1106]
This is pretty severe bug in regards to imported scanned maps from the backlog. It prevents a valid geoblacklight document from being generated, and is just really confusing, in general.
![screenshot 2018-04-20 16 35 36](https://user-images.githubusercontent.com/784196/39074929-018d870c-44b9-11e8-8808-b82beda09799.png)

**Comment by jrgriffiniii** [comment]
Somewhat related to https://github.com/pulibrary/figgy/pull/1067#discussion_r182800316.  When implementing the functionality in #1067, I also found `identifier` values will be overridden during the ARK minting process:
https://github.com/pulibrary/figgy/blob/master/app/services/identifier_service.rb#L17

Please note that the `identifier` values are never appended (I suspect that the ARK is modified here instead):
https://github.com/pulibrary/figgy/blob/master/app/services/identifier_service.rb#L13
