### ISSUE TITLE
Enhance usability on the location field of archival media collection form

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1108]
maybe a file picker? maybe there can be a default location drawn from config, based on what we know about the isilon share?

depends on #1006 and depends on #2289 

Relevant set of wireframes:
https://drive.google.com/open?id=1zHEX778ezbIFGDGgjEsj9IMbN2KUk35A

**Comment by hackmastera** [comment]
Recent changes to browse everything to handle directories may mean it will work for this now.

**Comment by jrgriffiniii** [comment]
I've been approaching this by integrating File Manager support and BrowseEverything directory uploads to trigger `IngestArchivalMediaBagJobs` to be enqueued with directory paths selected by the JavaScript components.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-1108-jrgriffiniii-arch-coll-uploads#diff-65fb1c18a403ae5f2fb48e089f284357R28 keeps failing, and I'm not able to reproduce this in my local environment.  The appropriate partial override *is* rendered when I visit an `ArchivalMediaCollection` in my browser: https://github.com/pulibrary/figgy/compare/issues-1108-jrgriffiniii-arch-coll-uploads#diff-e15bf57c3b8a944b63f7aa921eab4b7d

**Comment by jrgriffiniii** [comment]
When testing using `/mnt/hydra_sources/archives_bd/bcadmin/univarchives/AC468` on staging, recursing through child directories does not seem to be supported by the `ArchivalMediaCollection`.
