### ISSUE TITLE
Ephemera: selected vocabulary terms

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1132]
Ephemera projects often include items from many countries, languages, etc., but typically a handful of languages/countries account for the vast majority of items.  Allow designating a small number of language/country/etc. items and showing those at the top of the select menu, but still allow access to the full vocab.

E.g., for LAE, the vast majority of items are in Spanish, English or Portuguese.  The Language menu could be:

* Spanish
* English
* Portuguese
* Other Languages -> shows full list

**Comment by tpendragon** [comment]
#1548 recommended a "recently used" rather than "curated list of favorites." Given how little our users edit the project properties, I'm inclined to close this in favor of that. Assigning this to you @escowles for a decision.

**Comment by escowles** [comment]
Yes, I agree that a "recently used" list would be a good way to handle this, without requiring a lot of fiddly customization (which we would probably wind up doing instead of the users).  So I'm closing this in favor of #1548
