### ISSUE TITLE
Browse Everything: Google Team Drive support?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1133]
Does the Google Drive API allow us to access team drives?

**Comment by jrgriffiniii** [comment]
It does, but the Ruby client was only recently updated in order to support this.  I've created an upstream issue in order to integrate this: https://github.com/samvera/browse-everything/issues/207

**Comment by escowles** [comment]
@jrgriffiniii Thanks for the quick research — so it looks like updating the client library and pushing that update down into Figgy would allow access to Team Drives?
