### ISSUE TITLE
Multi-select checkbox placement

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1134]
In the Ephemera multi-select menus, the checkboxes are at the far right of a very wide menu making it hard to match them with the selected items.  Can the checkboxes be on the left?

**Comment by tpendragon** [comment]
They look like this now:
![Screen Shot 2018-07-24 at 4.09.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56214b84e38e6c1200c6a5a3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f76b7191a37cf112224f5f585ecc3c4a4356bcbbd671f3e57862804e0ebcd63c5f76973913faec811aec01ba24de4a87b1b48e1ad2f42f67b6d5db1063474f4dcbed5727a29941c95df549e54a56a3153663ee7e2431.png)

Closing.
