### ISSUE TITLE
Ephemera: Allow moving boxless folders into boxes

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1143]
This is to support recording the boxes for the ~4K posters migrated into Figgy as boxless.  Important to make this as efficient as possible, given the volume of manual work.

Ideal workflow:
1. Search on poster title
2. Edit poster
3. Select box on edit form

**Comment by hackmastera** [comment]
I wonder if this would be faster: add a checkbox column to folders on a project view page. Then have a bulk action "move to box" with a dropdown for all the boxes in that project.

**Comment by hackmastera** [comment]
Where do the users want this field on the form?

**Comment by escowles** [comment]
I don't think they said where — I'll ask.
