### ISSUE TITLE
Figgy can't handle complete reindex from LAE/DPUL/Pulmap

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1147]

**Comment by tpendragon** [comment]
To be clear, Figgy's internal response times never slowed down, they backed up at the load balancer.

**Comment by escowles** [comment]
Yes, resolution of this ticket may be entirely within the load balancer, or may involve rate-limiting the reindexing, or something else.

**Comment by tpendragon** [comment]
We fixed some load balancer issues - there's a good chance this is fixed now.

**Comment by tpendragon** [comment]
We've reindexed all of DPUL since this, and everything was fine.
