### ISSUE TITLE
Add OrderManager to MediaResources

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1178]
Depends on #1709

**Comment by hackmastera** [comment]
until we do this we can't really see what's been ingested

**Comment by eliotjordan** [comment]
OrderManager requires that the resource generate a manifest. FileManger no longer orders items.

**Comment by jrgriffiniii** [comment]
Non-media files attached to `MediaResources` will not need to be ordered

**Comment by jrgriffiniii** [comment]
https://github.com/IIIF-Commons/manifesto also informs how Manifests are consumed by the client

**Comment by sdellis** [comment]
What happens when members get sent back to the API without a non-ordered member?

**Comment by jrgriffiniii** [comment]
Also, should we be using IIIF as a serialization mechanism for non-visual resources?

**Comment by tpendragon** [comment]
Obviated by #3080
