### ISSUE TITLE
ScannedResource with both imported ARK and newly-minted ARK

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1180]
Some records with imported metadata have both an ARK imported from Voyager, and also have a newly-minted ARK from EZID.  Example record: https://figgy.princeton.edu/catalog/5cb25d6a-4bf3-4b29-9e60-0482f946afa3

These items do not display a viewer in the Catalog because they are not retrieved by a query for the imported ARK.

**Comment by tpendragon** [comment]
It's not surprising that they have an ARK in both places (One is from the MARC record and one was generated by Figgy) - but it's weird that the query doesn't resolve.

**Comment by tpendragon** [comment]
Oh, they're different! That's weird.

**Comment by escowles** [comment]
Yes, I should have said that the main issue is that they ARKs are different.  I think the logic that mints a new ARK shouldn't mint one if there is an existing ARK in the imported metadata, to prevent that from happening.

**Comment by tpendragon** [comment]
Did these ARKs come from outside PUDL/Plum/Figgy?

**Comment by escowles** [comment]
The ARK in the Voyager record is a pre-existing ARK, which points to PUDL.

**Comment by tpendragon** [comment]
Weird, I thought the METS import handled that. Do we want imported metadata to override the local identifier if it exists maybe?
