### ISSUE TITLE
Change display of Cicognara-related identifiers

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1200]
* Original Cicognara numbers should be: "cico:1234" (not currently imported)
* Digital Cicognara numbers should be: "dcl:xyz" (currently "cico:xyz")

**Comment by tpendragon** [comment]
@escowles Can you add info about which fields and a possible form of implementation for this?

**Comment by escowles** [comment]
I believe the Digital Cicognara numbers will be fixed by re-importing metadata (not sure why this hasn't happened, since i thought we were doing that regularly now).  I just reimported the metadata for [one record](https://figgy.princeton.edu/catalog/ba0ba378-dc21-425e-ab15-2400b1b56b3e), and I'm seeing the Digital Cicognara number as `dcl:tc5` in the `local_identifier` field now.

The Original Cicognara number is now imported as `Cicognara, 979` in the `references` field.

So I think this ticket is fixed, but the automatic refreshing of metadata may not be working.  I'll open a ticket for that.
