### ISSUE TITLE
Remove derivative file update buttons?

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1260]
These don't work currently. Should they be removed?

![screenshot 2018-05-15 12 46 04](https://user-images.githubusercontent.com/784196/40074147-7616b5e2-583e-11e8-96f7-4a572b7022e9.png)

**Comment by escowles** [comment]
Yes, it would be better to remove these (though it would be nice to be able to upload a custom-generated JP2)

**Comment by hackmastera** [comment]
dup of #1091

**Comment by eliotjordan** [comment]
Yep. It's a dupe. Closing.
