### ISSUE TITLE
Remove file upload from edit page

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1261]
The edit page file upload button works, but there is a very small maximum file size due to settings in NGINX. This might also be confusing for users. Do we want to keep this?

![screenshot 2018-05-15 12 50 20](https://user-images.githubusercontent.com/784196/40074241-bc11381a-583e-11e8-99bb-db2e74f03797.png)

- [x] Remove the button.
- [ ] Update README to document how to upload files in dev using browse everything and the  `staged_files` directory.

**Comment by escowles** [comment]
👍 to removing that — it causes more trouble than it's worth (and we know from migration from Plum that it's never used)

**Comment by tpendragon** [comment]
It's come in handy for demos when Browse Everything is broken, but that's it

**Comment by hackmastera** [comment]
related to #1091?

**Comment by eliotjordan** [comment]
Don't think it's related. The file uploading functionality here actually works, whereas in 1091, it does not.
