### ISSUE TITLE
Implement a migration for `EphemeraFolders` which should be `complete`

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#1279]
Identified while discussing #1276, as `IngestEphemeraJob` does not address cases where `EphemeraBoxes` which were marked as prepared for production after they were ingested

**Comment by hackmastera** [comment]
After this migration is done, we should have another ticket to update logic which checks the parent workflow state. there's definitely some indexer logic like this and possibly search_builder or ability as well.
