### ISSUE TITLE
Should be able to download audio files

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1285]
Users need to download while in reading room. Currently we can't download audio because http range requests.

downloading is slow. currently goes through rails infrastructure. speed it up by piping it through nginx.

xxl redirect.

reasonable name when it's been downloaded. (ask PO what this should be: title? componentID? barcode? original filename?)

**Comment by tpendragon** [comment]
This SHOULD be done, but we should wait until we can ingest a full-sized audio bag until we close this.

**Comment by hackmastera** [comment]
depends on #1287
