### ISSUE TITLE
Preservation profiles

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1286]
We need some metadata field which will tell us what level of preservation to provide for a resource.

Requires discussion and feedback from people with expertise in this area.

Default should start with "no preservation", then move to "normal preservation", with "highest preservation" as an option

**Comment by hackmastera** [comment]
@escowles Should this look like a dropdown on a form with label "Preservation profile" and options "No preservation", "Normal preservation" and "Highest preservation"

**Comment by escowles** [comment]
@hackmastera Yes, that sounds good to me.

**Comment by hackmastera** [comment]
Hm. Okay I'd like to talk about this a bit more before doing it. I guess on next week's checkin.
