### ISSUE TITLE
Tag deploys with version/commit/etc.?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#129]
Recently got a question about whether a certain (merged) Plum PR had been deployed to production or not, and that led to a question about whether it would make sense to tag deploys with some way to know what was deployed (could be the commit, a version number, etc.)

UCSD did this: https://github.com/ucsdlib/damspas/blob/develop/config/deploy.rb#L48-L55

Do we want to do this for Figgy?

**Comment by tpendragon** [comment]
Oh, sure. I'm not sure we want to version yet, but putting the git SHA there would probably be useful.
