### ISSUE TITLE
Order Manager button is not visible

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/figgy#1294]
In the Order Manager, when foliating an object, the "apply changes" button gets moved down so far it isn't visible.  I can't find a way to scroll to it.  I have to zoom my browser to less than 100% size in order to access the button.  This happens in IE on my desktop, and in Safari on my laptop.

**Comment by tpendragon** [comment]
@joycebcat Can you share the record you were trying to foliate so we can get an idea of how many pages there were?

**Comment by joycebcat** [comment]
It doesn't have anything to do with the number of images (as far as I can tell).  When you select foliation, there are additional boxes which appear on the right-hand pane to choose labels for recto and verso, etc.  These extra boxes push the Apply button further down the screen.  It happens with EVERY object I try to foliate.  I was working on most of the Ethiopic manuscripts.

**Comment by tpendragon** [comment]
:+1: Thanks!

**Comment by sdellis** [comment]
I can help with this, but probably not today. The simplest fix is to tweak the css to either allow scrolling of that box, or to simply tighten up the form so it doesn't get pushed down.
