### ISSUE TITLE
Improve thumbnail display CSS for search results

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#131]

**Comment by tpendragon** [comment]
Plum: 
![screen shot 2018-02-05 at 10 47 33 am](https://user-images.githubusercontent.com/2806645/35822736-0a9dd4c8-0a62-11e8-9fa2-c7272d2672b4.png)

Figgy:
![screen shot 2018-02-05 at 10 47 40 am](https://user-images.githubusercontent.com/2806645/35822741-0f19a4f0-0a62-11e8-8198-4fe3aecf6967.png)


I think Plum looks better and we should have a layout like that.

**Comment by tpendragon** [comment]
Specifically, I think the thumbnail should be on the left with fields on the right.

**Comment by christinach** [comment]
Yes I agree thumbnail on the left and fields on the right
