### ISSUE TITLE
[Figgy/production] OpenURI::HTTPError: 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1316]
## Backtrace

    line 12 of [PROJECT_ROOT]/app/services/pdf_generator/canvas_downloader.rb: download
    line 15 of [PROJECT_ROOT]/app/services/pdf_generator.rb: block in render
    line 11 of [PROJECT_ROOT]/app/services/pdf_generator.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/36427640)

**Comment by hackmastera** [comment]
might just be a loris blip. but should handle better for users; tell them to try again later.

**Comment by hackmastera** [comment]
I considered redirecting back to the show page with a flash message error. However, @tpendragon  reminded me that we would be bringing orangelight users over to figgy that way. It seems like the 500 is actually the correct behavior here. closing as wontfix

**Comment by jrgriffiniii** [comment]
Discovered as necessary to resolve by logging failed attempts to download PDFs from the IIIF image server
