### ISSUE TITLE
[Figgy/production] PG::Error: invalid encoding name: utf8

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1318]
## Backtrace

    line 68 of [PROJECT_ROOT]/app/models/ability.rb: auth_token
    line 64 of [PROJECT_ROOT]/app/models/ability.rb: current_user
    line 7 of [PROJECT_ROOT]/app/controllers/concerns/token_auth.rb: new

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/37919728)

**Comment by tpendragon** [comment]
Upgrade the pg gem.

**Comment by hackmastera** [comment]
(we are on the last pre-1.0 version of pg)

**Comment by hackmastera** [comment]
Valkyrie requires pg `<1.0`
