### ISSUE TITLE
[Figgy/production] URI::InvalidURIError: bad URI(is not URI?): vol. 33-35.xml

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1321]
## Backtrace

    line 35 of [PROJECT_ROOT]/app/models/remote_record.rb: client_result
    line 31 of [PROJECT_ROOT]/app/models/remote_record.rb: success?
    line 5 of [PROJECT_ROOT]/app/validators/source_metadata_identifier_validator.rb: validate

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/36581577)

**Comment by hackmastera** [comment]
In this case a title was placed in the source metadata identifier field. Catch this in the source metadata validator, and fail the validation.
