### ISSUE TITLE
Extremely large/wide JPEG downloads not working

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1325]
Trying to download the full resolution JPEG of this object in staging does not work:

https://figgy-staging.princeton.edu/catalog/5a1522d9-aaf7-45ca-89cc-f10c2fce2f54

I get the error "The requested image pixel area exceeds the threshold set in the configuration.", but if I manually change the long dimension from the original 116,061 to 50,000, the download works:

https://figgy-staging.princeton.edu/cantaloupe/iiif/2/56%2F34%2F6c%2F56346cc8107b4b8386ad9f0d11590d99%2Fintermediate_file.jp2/full/50000,/0/default.jpg

The same is true in production Loris:

https://libimages1.princeton.edu/loris/figgy_prod%2F80%2F54%2Ffb%2F8054fbd63f97410aa909122efc54eacc%2Fintermediate_file.jp2/full/50000,/0/default.jpg

Do we need to configure a maximum image width in the image servers to prevent requesting an overlarge image?

**Comment by jrgriffiniii** [comment]
This can be adjusted in Cantaloupe: https://github.com/medusa-project/cantaloupe/blob/master/src/main/java/edu/illinois/library/cantaloupe/resource/PublicResource.java#L66

https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.cantaloupe/defaults/main.yml#L63 seems to be where this is set

**Comment by jrgriffiniii** [comment]
Trying to resolve this by adjusting the NGINX `limit_conn` Directive (http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html#limit_conn) for the Cantaloupe deployment is one approach which would prevent any overloading of the server

**Comment by escowles** [comment]
The info.json for the image includes the full resolution: `{"width": 116061, "height": 3600}`

https://libimages1.princeton.edu/loris/figgy_prod%2F80%2F54%2Ffb%2F8054fbd63f97410aa909122efc54eacc%2Fintermediate_file.jp2/info.json

But when a client requests that size, it doesn't work.  I'm open to updating Loris or nginx to allow serving the larger image.  But I also think it would also be fine if Loris could not list the full resolution, or set the max width to 50k or whatever the largest working value is.

**Comment by jrgriffiniii** [comment]
> But I also think it would also be fine if Loris could not list the full resolution, or set the max width to 50k or whatever the largest working value is.

The latter is certainly supported by Cantaloupe.  I could not find an alternative for this within:
- https://github.com/medusa-project/cantaloupe/blob/master/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/ImageInfoFactory.java#L199
- https://github.com/medusa-project/cantaloupe/blob/master/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/ImageInfo.java#L24
