### ISSUE TITLE
Get rid of PULMetadataServices?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1328]
It's only used in Figgy and hardly does anything - seems easier to track if we just merge it in?

**Comment by jpstroop** [comment]
There was definitely a time when we thought it would be used more/elsewhere--maybe in DPUL or GetIt or something? Can't really think of where else.

**Comment by tpendragon** [comment]
@jpstroop The gem predates the "let's have bibdata and figgy output jsonld" discussion and implementation. So that's probably why.

**Comment by hackmastera** [comment]
this happened
