### ISSUE TITLE
Collection owners should get a weekly email about items that need attention

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1331]
Requires #1330 

Each week, collection owners should get an email about any items in their collection that are in need of attention (e.g., state = "pending", "metadata_review" or "final_review").

**Comment by tpendragon** [comment]
What's a "collection owner"?

**Comment by escowles** [comment]
@tpendragon See #1330 — but so far it's basically the person who should get these emails.

**Comment by hackmastera** [comment]
depends on https://github.com/pulibrary/princeton_ansible/issues/286

**Comment by hackmastera** [comment]
address https://github.com/pulibrary/pul-the-hard-way/issues/30 as part of this ticket. orangelight settings at https://github.com/pulibrary/orangelight/blob/master/config/environments/production.rb#L82.

**Comment by hackmastera** [comment]
We've agreed to use this as an opportunity to try out the whenever gem

**Comment by hackmastera** [comment]
This is mostly done in #1489. Final steps needed:

- [ ] figgy box/es need to be whitelisted to use the smtp server. John K. has a ticket for this.
- [ ] John K. has created a ticket to see if helpdesk can whitelist the emails for proofpoint.
-  [ ] The task can be run manually if desired. Testing was successful on staging (except for the proofpoint issue)
- [ ] PR needed for adding this task to cron via whenever.
