### ISSUE TITLE
Collection show page should link to members

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1332]
The current member list on collection show pages lacks many of the features of the search results.  We shouldn't duplicate that functionality on the collection member list.  Instead, we should remove the member list and replace it with a link to the search results limited to collection members.

**Comment by tpendragon** [comment]
This feels really similar to collection landing pages. OD would basically have a secondary catalog controller that limited to a specific collection - is that what we're talking about here?

**Comment by escowles** [comment]
Yes, I think that basically people would like all the search/facet features, but limited to the collection.

**Comment by hackmastera** [comment]
@tpendragon Could you say more about what you are thinking? I've just looked into building what is there, which was added in this PR: https://github.com/pulibrary/figgy/pull/608. I tried to stick in the facet partial but, alas, it links back to the main search. Before I start trying to pass local params or override views / helpers, I wondered if whatever you're thinking might be cleaner. Would it be a totally different approach than is there currently for the members list, or very similar?

**Comment by tpendragon** [comment]
@hackmastera It would be a totally different approach, and not super easy. It's like having a second catalog controller which accepts an argument for which collection to restrict itself to. It was a long time ago I worked on this, but it looked like this:

https://github.com/OregonDigital/oregondigital/blob/master/app/controllers/sets_controller.rb

https://github.com/OregonDigital/oregondigital/blob/master/config/routes.rb#L21-L29

**Comment by hackmastera** [comment]
After examining the OD approach, it doesn't seem entirely analagous to our scenario.

@escowles We looked at this for a while this afternoon and it seems like this use case is covered by faceting in the main search results: first to collection, then to whatever other facet you want to use. I wonder if we could ask the stakeholders more about their use case and why they prefer to be on the collections page. I'm hesitant to add more UI if we don't need it, to avoid getting too cluttered and segmenting users into people who do things one way and people who do things another way (I think this can make communication difficult).

**Comment by escowles** [comment]
Since the use case here essentially boils down to wanting all the normal search results functionality on the member list, I think we should replace the member list with a link to the search results facet.  I'll update the description of the ticket to reflect that instead of improving the display of the existing member list.
