### ISSUE TITLE
update to valkyrie 1.1.0

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1337]
blocks #1318

Will necessitate adding `find_by_alternate_identifier` to `InstrumentedQueryService` and `BagitQueryService`

**Comment by hackmastera** [comment]
@tpendragon I'm really not sure what this method should look like for the bagit query service. Please let me know if you have any idea.

**Comment by escowles** [comment]
I assume it would involve iterating through all the bags and looking at the bag metadata for an `alternate_identifier` value?

**Comment by hackmastera** [comment]
So similar to https://github.com/pulibrary/figgy/blob/master/app/adapters/bagit/query_service.rb#L50-L55
