### ISSUE TITLE
[Figgy/production] ActionView::Template::Error: undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1343]
## Backtrace

    line 13 of [PROJECT_ROOT]/app/views/catalog/index.html.erb: _app_views_catalog_index_html_erb__459372612833869178_54233100

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/35095579)

**Comment by hackmastera** [comment]
possibly happens when you "hit a facet in the wrong place" so it doesn't go to the catalog subpath
