### ISSUE TITLE
[Figgy/production] TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1345]
## Backtrace

    line 48 of [PROJECT_ROOT]/app/services/ingest_folder_locator.rb: initialize
    line 48 of [PROJECT_ROOT]/app/services/ingest_folder_locator.rb: new
    line 48 of [PROJECT_ROOT]/app/services/ingest_folder_locator.rb: folder_pathname

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/37793717)

**Comment by hackmastera** [comment]
someone submitted the form without a path? shouldn't be possible but we can also make sure it doesn't error.
