### ISSUE TITLE
Use MediaInfo to characterize a/v resources

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1349]
The following tech. metadata properties should be added to a FileSet:
"Encoded Date" as property "Date of Digitization"
"Producer"
"Original Source Form" as property "Source Media Type"
"Duration"

these fields come from https://docs.google.com/spreadsheets/d/12k7GejCnc35Af1b-rJ7YOvpGGB8Lt-P1EL_ot7yV1aQ/edit#gid=0

**Comment by jrgriffiniii** [comment]
Referencing the MediaInfo list of tags, I am able to locate all but the `Original Source Form`:
https://mediaarea.net/en/MediaInfo/Support/Tags

Does this map to `Encoded_Original`?  Should I be referencing some source other than the MediaInfo Tags?

**Comment by hackmastera** [comment]
Hm, the example given is `Cassette`; I can't imagine how media info would be able to discover that. @kellybolding perhaps this was a typo on the spreadsheet?

**Comment by kellybolding** [comment]
@hackmastera -- "Cassette" showed up in the field "Original source form" in my test output file when I ran Media Info over one of the sample files from the LA project. (https://drive.google.com/drive/folders/1UBS8j_gdsd1538x2lcpdDp1UfdQT6KBF) We asked the vendor to embed this information in the files, so I imagine Media Info is pulling from the embedded metadata. However, if it makes more sense to take this info from PBCore in case it's not embedded in the future, I would be fine with that.

**Comment by hackmastera** [comment]
Ah, got it. Okay thanks @kellybolding! I've made #1377 for this

**Comment by jrgriffiniii** [comment]
Also, @hackmastera I've discovered that this is a valid XML tag:
https://github.com/MediaArea/MediaAreaXml/blob/master/mediainfo.xsd#L287

This wasn't featured in the documentation maintained by MediaArea (https://mediaarea.net/en/MediaInfo/Support/Tags), my apologies for that.

**Comment by hackmastera** [comment]
Hm. Well I have no preference as to where we pull it. @kellybolding either place we get it will depend on project managers / vendors following documented practices. If you think one is better than the other, we can do it either way. Do you prefer getting it from media info?

**Comment by kellybolding** [comment]
@hackmastera in that case, let's go with media info. The digitization working group will be working on documenting best practices for AV soon, and I anticipate we will recommend having this information always embedded for future projects.

**Comment by hackmastera** [comment]
sounds good thanks @kellybolding!
