### ISSUE TITLE
Update ARK metadata

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1362]
A recent report on bad links from EZID shows that 90%+ of our broken ARK links are Figgy or Plum.  The Figgy links look like they just need to point to `/catalog/[id]` instead of `/concern/scanned_resources/[id]`, and the Figgy object for the Plum ones can probably be found now that we've added the Plum local_identifier values.

[bad_links_pudiglib.zip](https://github.com/pulibrary/figgy/files/2065879/bad_links_pudiglib.zip)

**Comment by escowles** [comment]
@eliotjordan I looked at some of the Figgy items, and they were all VectorResources (see URLs):

[figgy_urls.txt](https://github.com/pulibrary/figgy/files/2098903/figgy_urls.txt)

Can you make sure these are setting the correct URLs now, and bulk-update the EZID metadata for them?

**Comment by eliotjordan** [comment]
A spot check reveals that the arks in the list above are now correct. There were a handful of non-Vector resources at the bottom of the list, and those were corrected as well.
