### ISSUE TITLE
Staff users can't delete FileSets they have created

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1367]
The `Ability` class is checking whether the FileSet's `depositor` matches the user's id, but the FileSet's `depositor` property is `nil`.

**Comment by hackmastera** [comment]
What should it check? `depositor` on the FileSet's parent?

**Comment by escowles** [comment]
Checking the parent's `depositor` sounds good — it means there is only one definition of who deposited an item for purposes of checking who can delete things.

**Comment by hackmastera** [comment]
permissions
