### ISSUE TITLE
mime_types aren't getting saved on wav files

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1369]

**Comment by hackmastera** [comment]
The problem is that file_set is looking for mime_type on the file with pcdm:use `OriginalFile` and these file_sets only have files with pcdm:use `PreservationMasterFile`, `IntermediateFile`, and `ServiceFile`. Which one should be used? @escowles?

**Comment by escowles** [comment]
@hackmastera I think we should use the `PreservationMasterFile` one, since that's the file the others are ultimately derived from.
