### ISSUE TITLE
[Figgy/staging] RuntimeError: Unable to execute command "zip -j -qq -r "/tmp/sufia20180605-8719-1qc7o05.zip" "/tmp/sufia20180605-8719-1qc7o05_1528238816040"". Exit code: pid 884 exit 141
Error message:

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1374]
## Backtrace

    line 110 of [PROJECT_ROOT]/app/derivative-services/vector_resource_derivative_service.rb: run_derivatives
    line 63 of [PROJECT_ROOT]/app/derivative-services/vector_resource_derivative_service.rb: create_derivatives
    line 8 of [PROJECT_ROOT]/app/jobs/create_derivatives_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38110502)

**Comment by eliotjordan** [comment]
More complete response here: https://github.com/pulibrary/figgy/issues/1411
