### ISSUE TITLE
Can't view fixity dashboard

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1376]
## Backtrace

    line 14 of [PROJECT_ROOT]/app/views/fixity_dashboard/_fixity_table.html.erb: block in _app_views_fixity_dashboard__fixity_table_html_erb__2308990155303852702_70271537844160
    line 12 of [PROJECT_ROOT]/app/views/fixity_dashboard/_fixity_table.html.erb: yield
    line 12 of [PROJECT_ROOT]/app/views/fixity_dashboard/_fixity_table.html.erb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38117697)

**Comment by hackmastera** [comment]
The resource referenced here is a `FileSet`. this error indicates that we still have orphaned file sets.

```
ActionView::Template::Error: undefined method `id' for nil:NilClass

    [PROJECT_ROOT]/app/views/fixity_dashboard/_fixity_table.html.erb:14 :in `block in _app_views_fixity_dashboard__fixity_table_html_erb`

    12     <% resources.each do |resource| %>
    13       <tr>
    14         <td><%= link_to resource.title.first, ContextualPath.new(child: resource, parent_id: resource.parent.id).show %></td>
    15         <td><%= link_to resource.parent.title.first, ContextualPath.new(child: resource.parent).show %></td>
    16         <td><%= format_fixity_success(resource.original_file.fixity_success) %></td>
```
