### ISSUE TITLE
When a single Component ID contains multiple barcodes, their files should ingest to the same media resource

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1387]
currently one is getting ingested to a different media resource which doesn't have the component ID.

**Comment by sdellis** [comment]
Do you have an example EAD? I wonder if this is using the dsc2?

**Comment by hackmastera** [comment]
The code is correct. There's a typo in the finding aid https://findingaids.princeton.edu/collections/C0652.xml; `32101047382492_2` should be `32101047382492_1` @kellybolding

I'm correcting it in the fixture and I'll push up the new spec to close this PR.
