### ISSUE TITLE
Rethink OCR

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#139]
* Have option to enable/disable OCR?

**Comment by rlskoeser** [comment]
If you do disable it for some content (which seems reasonable), you might think about some way of indicating to consumers whether OCR is not yet available or intentionally not included.  (Although maybe that won't be a problem once OCR is included and properly running on everything where it's desired/useful?)

**Comment by tpendragon** [comment]
1. If they decide to run OCR does the full-text attach to the manifest?
2. Default OCR off?
3. Do we just give them a language selector for the OCR?

**Comment by escowles** [comment]
Decision: one-time OCR processing is fine to satisfy a researcher's request (see https://github.com/pulibrary/figgy/issues/892), defer setting up OCR and bulk processing for now.

**Comment by escowles** [comment]
@rlskoeser reports that the Office of Communication thinks we need OCR for accessibility reasons.  Given that, I'm going to prioritize #62.
