### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1391]
## Backtrace

    line 115 of [PROJECT_ROOT]/app/models/archival_media_bag_parser.rb: get_barcode_with_part
    line 88 of [PROJECT_ROOT]/app/models/archival_media_bag_parser.rb: block in parse_dict!
    line 87 of [PROJECT_ROOT]/app/models/archival_media_bag_parser.rb: parse_dict!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38158553)

**Comment by tpendragon** [comment]
This happened trying to create the AV collection at `/mnt/hydra_sources/archives_bd/bcadmin/mss/av_backlog/la_c0977_2017_05_bag` with the identifier `C0977`

**Comment by hackmastera** [comment]
The finding aid has a section of  `altformavail` which contains a bunch of non-barcode stuff, I guess for some part of the resource that's not a/v. `https://findingaids.princeton.edu/collections/C0977.xml`. Will add error handling.
