### ISSUE TITLE
Now that state propagates to members, remove extra logic

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1405]
Given https://github.com/pulibrary/figgy/pull/1339 we should be able to remove some logic around checking parent workflow states from indexing and maybe also the search builder and maybe also `Ability`

Pending confirmation that the migration was run on prod

**Comment by hackmastera** [comment]
e.g. I think this spec should be deleted, and the behavior of reindexing children, since they will save/reindex themselves on state change. https://github.com/pulibrary/figgy/blob/master/spec/change_set_persisters/change_set_persister_spec.rb#L896
