### ISSUE TITLE
References to non-existent IDs should not break manifest generation.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1410]
## Backtrace

    line 431 of [PROJECT_ROOT]/app/services/manifest_builder.rb: base_url
    line 410 of [PROJECT_ROOT]/app/services/manifest_builder.rb: manifest_image_path
    line 52 of [PROJECT_ROOT]/app/services/geo_discovery/document_builder/iiif_builder.rb: iiif_path

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38242668)

**Comment by eliotjordan** [comment]
The scanned map record that triggered this exception is fixed now, but should we doing something other than raising an `ObjectNotFoundError` error here?

https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder.rb#L431

**Comment by escowles** [comment]
Resolved with https://github.com/pulibrary/figgy/pull/1972
