### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `map!' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1412]
## Backtrace

    line 75 of [PROJECT_ROOT]/app/services/geo_metadata_extractor/fgdc.rb: keywords
    line 27 of [PROJECT_ROOT]/app/services/geo_metadata_extractor/fgdc.rb: metadata_optional
    line 10 of [PROJECT_ROOT]/app/services/geo_metadata_extractor/fgdc.rb: extract

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/37315228)

**Comment by eliotjordan** [comment]
Test if keywords are empty before calling map.

https://github.com/pulibrary/figgy/blob/master/app/services/geo_metadata_extractor/fgdc.rb#L75

**Comment by eliotjordan** [comment]
Closing for now. Can't replicate with real data.
