### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `text' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1414]
## Backtrace

    line 27 of [PROJECT_ROOT]/app/models/remote_record.rb: attributes
    line 85 of [PROJECT_ROOT]/app/models/archival_media_bag_parser.rb: xml
    line 91 of [PROJECT_ROOT]/app/models/archival_media_bag_parser.rb: barcode_nodes

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38031816)

**Comment by hackmastera** [comment]
When ingesting la_c0799_2017_05_bag

**Comment by hackmastera** [comment]
This bag is working now
