### ISSUE TITLE
Improve PDF download speed

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1418]
PDFs are slow, particularly large ones.  Profile the download process to figure out why and/or pre-generate.

**Comment by escowles** [comment]
Might be worth checking out SHI's PDF code (see #1397)

**Comment by tpendragon** [comment]
We're going to have to pre-generate these if they want them to download fast. Otherwise, we need some sort of "email them when they're done" functionality. We're going to push this issue back to the backlog until we talk to fulfillers.
