### ISSUE TITLE
Background fixity checking of files in Figgy

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#142]
We should have a background job to do fixity checking, so we could devote a worker to auditing checksums

**Comment by hackmastera** [comment]
maybe create a 'super-low' priority queue instead of assigning a whole worker

**Comment by hackmastera** [comment]
Question: What should happen if a fixity check fails? Should it email someone? If so is there a generic / alias email address that could be used? And/or should there be some kind of fixity event dashboard?

**Comment by escowles** [comment]
👍 to a super-low priority queue for background fixity checking

I like the idea of a fixity dashboard, where you could go and see all failures, and check the status of any item.  Can we do that first, and then figure out if email or some other notification is needed?

**Comment by hackmastera** [comment]
- a job that runs a single fixity check
  - how is this job triggered?
  - a job that loops through all files
    - then starts over again
    - then stops; is started again by cron
      - what happens if/when the repo gets large enough that the first job is still running when the next one starts?
    - How often does any given file need to be checked? what is our backup schedule like?
- a job that runs a fixity check and then kicks off a new instance of itself on the next object
  - how does it know where to start its fixity check?
    - run through an enumerator and check against fixity object table for either
      - this object has never been run
      - this object has not been run in X days
  - how does it know what the next object is?
    - probably just does the above again
  - this design is simple and idempotent. If the job dies it can just be started up again. Could we even have the fixity dashboard look for the job and if it's not found, provide a button to start it?
- fixity object
  - file id
  - first run
  - last run
  - expected checksum (is there a way to store multiple checksums in one field or do we need a field per checksum?)

**Comment by hackmastera** [comment]
Jobs required:

- [ ] Create a new fixity check (to be invoked by changeset persister on resource creation)
- [ ] Update least-recently-updated fixity check, then run self (to be invoked from a rake task)

Other stuff required:

- [ ] FixityCheck object
- [ ] Delete fixity check object when file is deleted
- [ ] Fixity dashboard (show failures, most / least recent checks)

**Comment by hackmastera** [comment]
The only problem is that if you have two copies of the job running they will likely hit a race condition on checking the same item. maybe if we decide we need to do that we can add some kind of odds/evens switch on file IDs or something.

**Comment by escowles** [comment]
@hackmastera Maybe it makes more sense to have one job that selects objects to check, and then a separate job for actually doing the fixity check?

**Comment by hackmastera** [comment]
@escowles are you suggesting a long-running 'spawning' type job? would mean we wouldn't have race conditions down the line but would also be less flexible to scale. Both of these concerns are pretty hypothetical at this point.

**Comment by escowles** [comment]
Once the initial backlog is worked through, we could have a couple of different strategies.  I'm sure there are more, but here's two:

1. every day, find all the files that haven't been checked in N days and spawn jobs for all of those, or
1. have N workers continually finding the least-recently-checked object and checking it

If we go with the second option, then making sure we don't have all the workers processing the same object will be key.  We could approach that with locking, or segmenting, or randomly picking from the last X objects, etc.

**Comment by hackmastera** [comment]
Yes, the 2nd is where we've been heading so far here. I still like it as having the least moving parts. I agree there are ways to deal with multiple workers; shall we just choose one later when the time comes? It may be as part of this issue or it may be a year from now.

**Comment by escowles** [comment]
@hackmastera 👍 doing the simple thing now and addressing the concurrency issues when we want to do multiple workers sounds good.

**Comment by hackmastera** [comment]
moving dashboard to its own ticket, since this one is getting long and other work is nearly done.
