### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1421]
## Backtrace

    line 86 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: create_image_file
    line 94 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: block in add_images
    line 93 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38293445)

**Comment by hackmastera** [comment]
error when ingesting a/v bag for C1502

**Comment by hackmastera** [comment]
close in favor of #1899; this honeybadger trace is no longer available (retention expired)
