### ISSUE TITLE
Intermittent viewer load failure in FF/Windows

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1431]
Reported in Orangelight but since this seems to coincide with the new figgy viewer I'm putting the ticket here.

@sdellis any thoughts?

**Comment by hackmastera** [comment]
On a given resource, the viewer will sometimes load and sometimes not load.

**Comment by sdellis** [comment]
I haven't been able to reproduce this, so I have nothing to go on other than the hunch that if sometimes it works and sometimes it doesn't, it seems like a figgy performance issue. What happens? Does the UV just remain black? Any errors in the console? 

It would probably make sense for us to cache that uv page with Varnish or something.

**Comment by hackmastera** [comment]
I wasn't able to reproduce it either. I've asked for a screenshot.

**Comment by tpendragon** [comment]
I can not reproduce this. I'm assuming this maybe happened when there was a lot of traffic to Figgy, causing Manifest timeouts? It was around this time the load balancer was getting hammered.
