### ISSUE TITLE
Handle date ranges when importing normalized dates from PULFA

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1442]
For example, the normalized date in https://findingaids.princeton.edu/collections/C0652.xml is 1941/1985, but it shows up in the UI as if it's `January 1, 1941`.

**Comment by hackmastera** [comment]
problem appears to be in the decorator. in the imported metadata it looks like `["1941-01-01T00:00:00Z/1985-12-31T23:59:59Z"]` but once you decorate it:
```[17] pry(main)> d.imported_created
=> ["January 1, 1941"]```

**Comment by hackmastera** [comment]
The field in question is the `created` attribute on a nested imported_metadata object. While there are no guarantees in the system regarding the contents of that field, data is only imported from bibdata or pulfa. bibdata doesn't appear to populate that field. Pulfa EADs specify `dateencoding="iso8601"`. So I think the decorator can assume iso8601 for this field.

There's no built-in parsing in rails for an iso8601 time interval, the value in question here. So we can either use a gem for iso8601 parsing or just check for a `/` and parse manually. I lean toward the latter.
