### ISSUE TITLE
Should some ScannedResources be converted to ScannedMaps?

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1449]
So they can be indexed and searched in Pulmap?

Example: https://figgy.princeton.edu/catalog/8de30736-c455-4e4b-b3be-ffac78618e03

**Comment by eliotjordan** [comment]
Mostly to remind us to talk about it. If we decide to, we might want to make a list of items to convert in Figgy.

**Comment by eliotjordan** [comment]
The scanned resources bib record will need a bounding box if we do this.

**Comment by tpendragon** [comment]
@eliotjordan Review this please.

**Comment by tpendragon** [comment]
Another example: https://figgy.princeton.edu/catalog/1621a8c2-caa3-44a3-a45e-21c0006fcdbd

This came up at the maps meeting. The question from the maps stakeholders is "how do we get this into the maps portal?"

**Comment by eliotjordan** [comment]
Yes.

**Comment by eliotjordan** [comment]
Closed in favor of #5883 and #5882
