### ISSUE TITLE
Save and ingest does not find directory  “RBD1.1_c1”

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1451]
trying to ingest some FA items (Derrida, RBD1.1). I have a dir full of items named such as “RBD1.1_c1”. Save and ingest won’t find the directory, so I have to go the long way around. I have 71 of these to do with another 400 pending. (report from @roelmoon)

**Comment by hackmastera** [comment]
the dot is causing the issue. I can rename the dirs “RBD1_1_c1”, S&I sees the item to ingest, but errors because the FA uses the dot.

**Comment by hackmastera** [comment]
Here's the finding aid https://findingaids.princeton.edu/collections/RBD1.1/c1

**Comment by hackmastera** [comment]
@roelmoon is seeing this bug again: "save/ingest with “.” in the dir name isn’t working. Had to do longhand ingest for C0744.03_c0452. Most of the Ethiopic manuscripts we’re working on have this type of ID."

**Comment by hackmastera** [comment]
I got started with a bit of js error handling in the first commit on this branch: https://github.com/pulibrary/figgy/tree/issue/1451-chrome-fix

Otherwise, it looks like the original fix for this (url-encoding the first period) simply doesn't work on Chrome.

The current workaround until this bug is resolved is to ingest these on Firefox.

**Comment by hackmastera** [comment]
The code works fine on chrome, it's encoded as intended at https://github.com/pulibrary/figgy/blob/master/app/assets/javascripts/save_and_ingest_handler.es6#L10. It's just that firefox and chrome handle the encoded urls differently. It seems like chrome "helpfully" decodes it before sending the request.

So I guess for this to work universally we would need to replace dots with some other character and then transform them back I guess in the `IngestFolderLocator` https://github.com/pulibrary/figgy/blob/7979549ec6948be70aa0d04225ad471ff4cfb398/app/services/ingest_folder_locator.rb#L8

I'm not sure what this character should be.

**Comment by sdellis** [comment]
I think replacing the dots and transforming back is the best solution. Obviously choosing a character that might affect the file system is not an option here. I would go with a series of characters that are unlikely to be strung together in a filename. Something like '_-_' or 'QQQ' would work.

**Comment by tpendragon** [comment]
Alternatively, is it just that a route isn't found? I know there's a special way to tell a route to ignore slashes and dots and include that as a parameter. Would have to check the routing documentation.

**Comment by hackmastera** [comment]
posting the id sounds great.

**Comment by tpendragon** [comment]
See https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match

I think you can avoid converting the period at all if you just do:

```ruby
        get "save_and_ingest/:id", action: :save_and_ingest, :constraints => { :id => /[^\/]+/ }
```

**Comment by hackmastera** [comment]
@tpendragon the constraints option passes the `.json` through along with the id like `C0744.03_c0452.json` so perhaps the post option would be better.

**Comment by tpendragon** [comment]
Maybe just set the default format to json and don't append .json? POST is fine, but it's odd for a query.
