### ISSUE TITLE
Bulk ingest not pulling data from PULFA

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1452]
Currently does not pull data from finding aids site.

**Comment by escowles** [comment]
Looking at the code, I don't see why this wouldn't work with a PULFA component ID — should this be "Save & Ingest doesn't work with archival materials", or is there some part that errors?

**Comment by hackmastera** [comment]
This was a report about the bulk ingest page (https://figgy-staging.princeton.edu/bulk_ingest/scanned_resource). Save & Ingest works with PULFA IDs.

**Comment by hackmastera** [comment]
I should note I haven't tried to replicate; just created the ticket based on slack discussion.

**Comment by escowles** [comment]
Sorry, I was confusing that with the `bulk:ingest` rake task.

**Comment by tpendragon** [comment]
We fixed this when we rewrote all the bulk ingest logic.
