### ISSUE TITLE
Ephemera Folders are duplicated when "Add to Box" is used

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1456]
Duplication mistakes occur when you

1. Use "Add to Box" feature to add folder to specific box (in this case 71);
2. Add barcode, which saves folder information and immediately puts you into view mode;
3. Go into edit mode and use "Add to Box" feature (which was not saved) again, and proceed with metadata processing and saving, - which duplicates or triplicates the folder.

**Comment by tpendragon** [comment]
What's likely going on here is the same record is getting added to member_ids multiple times.

**Comment by escowles** [comment]
That would explain one delete action deleting all of them.

**Comment by hackmastera** [comment]
This is 2 bugs. the one @tpendragon mentioned already and also that the edit form is not populating the box it's already a member of.

**Comment by hackmastera** [comment]
The problem is that when it's added to the box it's not removed from the project. Then the wayfinder returns the first `parent` found which is still the project.
