### ISSUE TITLE
Ephemera: Recover or reingest deleted items

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1458]
Related to #1456

>Yesterday we created the next box (71) and, while processing the first folders/items, our summer student María noticed the duplication and triplication of folders. They have the same barcode, so when you delete one of them, you consequently delete all and, thus, the entire record (which only exists in PUDL).

http://pudl.princeton.edu/objects/tb09j701m
http://pudl.princeton.edu/objects/z029p651s

**Comment by tpendragon** [comment]
Reingested: https://figgy.princeton.edu/catalog/c4678ed7-406f-4a57-868c-3d34611a57bf and https://figgy.princeton.edu/catalog/acc7b9de-d89a-43c2-9d17-3efa4de21dd8
