### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1460]
## Backtrace

    line 87 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: create_image_file
    line 99 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: block in add_images
    line 98 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38328399)

**Comment by hackmastera** [comment]
here's the job info 
```
  | {"collection_component"=>"C1502",  "bag_path"=>"/mnt/hydra_sources/archives_bd/bcadmin/mss/av_backlog/la_c1502_2017_05_bag",  "user"=>{"_aj_globalid"=>"gid://figgy/User/16"},  "_aj_symbol_keys"=>["collection_component", "bag_path", "user"]}
-- | --

```

**Comment by escowles** [comment]
The HoneyBadger error is resolved and hasn't happened recently, so I think this has been fixed.
