### ISSUE TITLE
Viewer does not show volume 1 once you've navigated to another volume

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1465]
https://figgy.princeton.edu/catalog/6a51f38d-893b-471d-9a65-886f569432cf

If you navigate to vols 2, 3, 4, you cannot then navigate back to vol. 1

**Comment by sdellis** [comment]
This is a UV glitch. It seems to happen with any MVW's that have table of contents. Here's another example: https://figgy.princeton.edu/catalog/4b0402e7-d227-4f76-aee0-2f6f127cfb39

**Comment by tpendragon** [comment]
Created https://github.com/UniversalViewer/universalviewer/issues/600

**Comment by escowles** [comment]
This is fixed in Figgy and OL now.  Do we want to close the UV issue?
