### ISSUE TITLE
LUX breaks geo show pages / interferes with Leaflet viewer

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1467]

**Comment by eliotjordan** [comment]
Only on geo resource show pages with Leaflet bbox viewer.

```
Vue warn]: Error compiling template:

<div data-behavior="vue" id="main" role="main" class="container ">
    <div id="content" class="col-xs-12 show-document">
  <div id="previousNextDocument" class="pagination-search-widgets">
    <div class="pull-right search-widgets">
      <a class="btn" href="/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Vector+Resource">Back to Search</a>

      <a id="startOverLink" class="btn" href="/">Start Over</a>
    </div>
</div>
...
```

**Comment by eliotjordan** [comment]
Yes. Definitely an issue with Vue + LUX. I checkout a commit just before Lux was added, updated the uv partial and stylesheet to target UV3, and everything works as it's supposed to.

![screenshot 2018-06-25 17 41 06](https://user-images.githubusercontent.com/784196/41879463-5ca086ca-789f-11e8-85c0-12f2827b06fe.png)

**Comment by sdellis** [comment]
So, just to be clear, it's not Leaflet, but the gem that is causing the problem here. What does the gem do for us that Leaflet can't do on its own?

**Comment by eliotjordan** [comment]
That's good news. leaflet-rails isn't doing much besides providing a tidy wrapper around the javascript and stylesheet assets. However, this will certainly be an issue for Pulmap as GeoBlacklight has dependency on that gem. It's possible, but I don't think that's going to change in the near-term.
