### ISSUE TITLE
Location information in DPUL (and figgy)

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/figgy#1488]
Holding location information isn't displaying properly in figgy, and isn't displaying at all in DPUL.  Example from one object (Sketches for Sonata, Opus 106)

DPUL display:
MICROFILM 2035
MICROFILM 2563
30.15
Electronic Resource

figgy display:
RCPQK MICROFILM 2035
 RCPQK MICROFILM 2563
 RCPQK 30.15
 RCPQK Electronic Resource
 SVL MICROFILM 2035
 SVL MICROFILM 2563
 SVL 30.15
 SVL Electronic Resource
 WHS MICROFILM 2035
 WHS MICROFILM 2563
 WHS 30.15
 WHS Electronic Resource
 ELF1 MICROFILM 2035
 ELF1 MICROFILM 2563
 ELF1 30.15
 ELF1 Electronic Resource

We should not be displaying ELF* locations at all, since this is the reference to the digital object we are already looking at.  What happened with this object is that we have the digital object (which we don't want to display holdings for), 2 microfilmed copies, and the original manuscript.  The locations have been disconnected from the specific call number to which they refer and each call number gets replicated with each location.

**Comment by tpendragon** [comment]
@escowles This seems like it should be fixed but we're not sure how important it is.

**Comment by tpendragon** [comment]
No ELF locations anymore.
