### ISSUE TITLE
Add remaining Resource/Fileset fields to GraphQL response

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#1492]
I think the only remaining pieces are bibid (if it exists), startPage, thumbnail, viewingDirection.

**Comment by sdellis** [comment]
We also will need the URL to the info.json of each member thumbnail.

**Comment by hackmastera** [comment]
bibids are stored in source_metadata_identifier, as are pulfa ids. do they need to be distinguished?

**Comment by hackmastera** [comment]
@sdellis does this look right

on resource:
- bibid
- startpage
- thumbnail
- viewingdirection
- info_url

on fileset:
- thumbnail
- info_url

**Comment by sdellis** [comment]
Sorry for the delayed response, I missed the email notification from @hackmastera's questions. The fileset should have info_url, no thumbnail needed. The thumbnail for the resource should simply be the id of the resource, as well as the thumbnail info_url.

However, @tpendragon's suggestion sounds good. But that means I need to construct that syntax on the client side if thumbnails get mutated? I suppose if all members had images in that format, it would just be moving those around and not reconstructing, so 👍 if that's what you're suggesting @tpendragon .
