### ISSUE TITLE
Request review for the Figgy App. by Google

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#1500]
Derived from https://github.com/pulibrary/figgy/issues/1497

**Comment by jrgriffiniii** [comment]
The request for Figgy to be reviewed by Google was successfully submitted at 11:19AM EDT on 07/03/18 (this morning).

**Comment by jrgriffiniii** [comment]
The service configuration for Figgy has been migrated to the Organization for library.princeton.edu, and in response to requests regarding the improvement of the OAuth consent screen, a second review request has been submitted at 12:30 EDT on 07/09/18.

**Comment by jrgriffiniii** [comment]
Google has requested that a separate OAuth client for development and testing be created (for callback URLs such as `http://localhost:3000/browse/connect`).  This has been addressed, and I have requested that the verification of Figgy please proceed at 14:25 EDT on 07/10/18.

**Comment by jrgriffiniii** [comment]
Google has requested that a test account for Google Drive be created and provided for them to use in the OAuth Verification process.  This user was created, tested using Figgy in a local development environment, and provided to continue the Verification at 16:57EDT on 07/11/18.

**Comment by jrgriffiniii** [comment]
Google has now requested that a video be created in order to demonstrate how users interact with Figgy and Google Drive integration at 15:30 EDT on 07/12/18.

**Comment by tpendragon** [comment]
Do we get a plaque after all this?

**Comment by jrgriffiniii** [comment]
Google has granted Figgy verification for integration with Google Drive at 16:16EDT on 07/13/18.
