### ISSUE TITLE
Add GraphQL Support for Geo

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1505]
- [x] ScannedMap
- [ ] VectorResource
- [ ] RasterResource

**Comment by escowles** [comment]
See #2411

**Comment by eliotjordan** [comment]
Neither resource type has IIIF manifests and the thumbnails are locally stored derivative images.

**Comment by hackmastera** [comment]
Options for dealing with the thumbnail problem:

thumbnail could be removed as a resource field, i.e. it would be added as a field to downstream resources.

Or vector / rastor resources could be changed to store their thumbnails on the image server.

Or thumbnail could provide thumbnail url and not iiif service url

or these resources could just provide thumbnail: null

**Comment by tpendragon** [comment]
Providing a url seems easy enough

**Comment by hackmastera** [comment]
yeah iiif service type already can be null. so as long as we don't mind serving thumbnails from figgy to orangelight that would be fine.

**Comment by hackmastera** [comment]
we'll probably start with just making thumbnail null altogether, since the objects in question are being filtered out on the orangelight side anyway right now.
