### ISSUE TITLE
Plum ingests should do checksums.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#151]

**Comment by escowles** [comment]
Bulk ingest doesn't do checksums when migrating from Plum

**Comment by tpendragon** [comment]
Success condition: When you import a resource from Plum, the FileSets' FileNodes should have technical metadata with the checksum, much as if it was manually ingested.

**Comment by tpendragon** [comment]
Can use this: https://github.com/samvera-labs/valkyrie/wiki/Storage-&-Files#calculate-and-verify-checksums
