### ISSUE TITLE
`Collection` creation should issue a RabbitMQ "CREATED" event

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#1515]
Currently "UPDATED" is issued (and, for new Collections, the slug is *not* included [perhaps it is not yet persisted before the event is generated?])

**Comment by tpendragon** [comment]
I don't think the slug should be included in the event for creating a collection - that field is more like, "these are the slugs of the collections this thing is a member of."

**Comment by tpendragon** [comment]
Nothing is listening for this so we're not worried about it.
