### ISSUE TITLE
Order manager - selection broken

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1521]

**Comment by jrgriffiniii** [comment]
I also reproduced this using https://figgy-staging.princeton.edu/concern/scanned_maps/6e87c9bb-5fb1-4481-b1da-5fdb600d0e6f/order_manager.  I failed to select members other than the initial member using Chrome 67.0.3396.99

**Comment by tpendragon** [comment]
This was broken by https://github.com/pulibrary/figgy/pull/1513
