### ISSUE TITLE
Hide URI for holding location & fix Rendered Holding Location label to say Holding Location

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1528]
<img width="1109" alt="screen shot 2018-07-18 at 9 11 45 am" src="https://user-images.githubusercontent.com/2806645/42883810-a3ad6682-8a6a-11e8-8cb7-4ad30d4da07c.png">

We only need to show the rendered version.

**Comment by hackmastera** [comment]
it seems like the correct way to do this is override `holding_location` in the decorator. do we know why we have `rendered_holding_location` instead?

**Comment by tpendragon** [comment]
I think because at the time the decorator was used for more than the show page?

**Comment by hackmastera** [comment]
right i guess it's used in the indexer. okay thanks.
