### ISSUE TITLE
Notify users when/what we deploy

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1537]
How can/should this be automated? How can we ensure appropriate language in changelogs?

discussed at digital studio users meeting 7/19/2018

**Comment by tpendragon** [comment]
@hackmastera @escowles Can we just call this done by the weekly updates in Slack?

**Comment by escowles** [comment]
Yes, I think I'd rather keep doing deploy reports manually than having an automated deploy mechanism.
