### ISSUE TITLE
Create user FAQ / documentation

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1538]
"What hapens if I’m ingesting and you deploy?"

Also discussed with RBSC curators; check those notes for more examples of things to include in this documentation.

**Comment by hackmastera** [comment]
"If there is a corrupt tiff can you catch that?"

**Comment by escowles** [comment]
Curators asked for a "cheat sheet" with info such as:

    What is a "slug"?
    How to report bugs/problems?
    How does Figgy relate to other systems?
    How ARKs work, and how various URLs are related (e.g. ARK shoulder in DPUL URL)
    Terminology — what things are called

**Comment by sdellis** [comment]
These should [ultimately be addressed in the interface rather than a FAQ](https://alistapart.com/article/no-more-faqs-create-purposeful-information-for-a-more-effective-user-experi) or "cheat sheet" as they are really shortcomings of the UI. If FAQs are needed, terms should not be defined in an FAQ but rather in a Glossary.

**Comment by escowles** [comment]
@sdellis I think we have a grab-bag now, and different items will require different solutions:
* Some of these items should be addressed in the UI (e.g., the `slug` field should describe how we use it, and probably have a live-updating link saying your collection URL will be `https://dpul.princeton.edu/[slug]`)
* Other items can definitely go in a glossary
* Some items (e.g., "How do I report a problem?") probably need a user guide.

**Comment by tpendragon** [comment]
@kelea99 Should we close this? There's a training program and a bunch of documentation now, yeah?

**Comment by kelea99** [comment]
there is, indeed. I can add the following, bu I did not know about these requests and I do not have at least one of them documented. do you have more information on "terminology" and what was meant by that? 

KEL should address: How ARKs work, and how various URLs are related (e.g. ARK shoulder in DPUL URL)

**Comment by tpendragon** [comment]
I assume things like when we say "Record Page", "Source metadata identifier", "Ephemera Folder", "Scanned Resource", "MapSet" maybe?

**Comment by kelea99** [comment]
ok. May we leave this open until i create that as well? I want to make sure we cover everything that was asked. Ill make sure we can close by weeks end

**Comment by tpendragon** [comment]
Sounds good.

**Comment by kelea99** [comment]
@tpendragon i have started a rough[ glossary of terms](https://docs.google.com/document/d/1jrbpSXEk3CqGoVVajtbDA84pqwAF7uzMF5FgHlIAN3s/edit) and will include the above in it. i am not sure if there are other sources that already define some things. anyone is welcome to review, add to, comment...

**Comment by tpendragon** [comment]
Kim will create a link in Confluence. Close this ticket when that happens.

**Comment by kelea99** [comment]
done! all in confluence
[Figgy main page](https://pul-confluence.atlassian.net/wiki/spaces/IT/pages/1933580/Figgy+PUL+s+Digital+Repository)
f[aqs](https://pul-confluence.atlassian.net/wiki/spaces/IT/pages/1933598/FAQs+Issues+in+Figgy+and+DigitalPUL+DPUL)
[glossaries](https://pul-confluence.atlassian.net/wiki/spaces/IT/pages/1933608/Glossaries)
