### ISSUE TITLE
Do we need lossless jp2s?

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1540]
Lossless jp2s? Upcoming are some materials that require finer resolution

PSNR -> can we calculate? If below 40 re-generate with less compression. If still below, regenerate as lossless. Make sure you’re comparing same color profiles (studio uses sRGB)

They’re noticing a difference between TIFF/Figgy jp2 much greater than difference between TIFF/local jp2s. Roel can show some examples. Problem may be in Loris during conversion to PNGs. Studio can try on staging to see if cantaloupe does better. Compare the loris jp2 to the local jp2.

discussed at digital studio users meeting 7/19/2018

**Comment by tpendragon** [comment]
See #860 for the recipe and further notes.

**Comment by tpendragon** [comment]
Copied from #860:

Should we add the ability to select a lossless JP2 recipe, similar to how we allow different PDF quality settings?

@roelmoon says these changes to our existing recipe would be needed for lossless:

```
For lossless JP2, change rate to:
-rate -,2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171

And add:
Creversible=yes
```

**Comment by tpendragon** [comment]
@roelmoon says There are a couple of engraving projects from Julie's collection in PUDL that had to be processed in lossless. Even with very mild compression the engraving details got crushed.

@roelmoon Do you know which engravings these were?

**Comment by tpendragon** [comment]
We don't even need JP2s!
