### ISSUE TITLE
Adding bib number to a resource created a new resource

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1541]
When adding a bib record to the resource, started creating a new resource instead. Need to replicate.

discussed at digital studio users meeting 7/19/2018

**Comment by tpendragon** [comment]
@hackmastera is going to ask if this is still a problem. If it isn't, we're going to close it.

**Comment by hackmastera** [comment]
This is resolved, closing.

Mary said:
If I remember correctly...it may have been fixed with the multiple volume ingest change.
in a nutshell.... when I would enter in the new bib ID...it would autofill to a previously ingested item. And I was receiving an error "This ID is already in use". It has since been fixed. Hope that helps. Thank you.
