### ISSUE TITLE
Make save box stay on the side (instead of scrolling up)

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1544]
discussed at digital studio users meeting 7/19/2018

**Comment by tpendragon** [comment]
<img width="1169" alt="screen shot 2018-07-23 at 10 17 39 am" src="https://user-images.githubusercontent.com/2806645/43092323-a94bc82c-8e61-11e8-91cf-c9f7edadab5c.png">

The box referenced is on the right of this screen shot. Consider bootstrap-affix https://getbootstrap.com/docs/3.3/javascript/#affix or new CSS option `position: sticky;`
