### ISSUE TITLE
Test the rest of the LA a/v bags on staging

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1559]
the bags are in `/mnt/hydra_sources/archives_bd/bcadmin/mss/av_backlog/`
- [x] la_c0652_2017_05_bag (Emir Rodriguez Monegal)
- [x] la_c0799_2017_05_bag (Anne Tashi Slater)
- [x] la_c0977_2017_05_bag (Juan García Ponce)
- [x] la_c0984_2017_05_bag (Dolores Koch)
- [x] la_c0994_2017_05_bag (Gabriela Mora)
- [x] la_c1450_2017_05_bag (Thomas Colchie)
- [x] la_c1470_2017_05_bag (François Wahl)
- [ ] la_c1502_2017_05_bag (Rita Guibert; error see below)
- [x] la_c1511_2017_05_bag (Juan Gelman)
- [x] la_c1513_2017_05_bag (Ricardo Piglia)

the one remaining
depends on #1899
depends on #1907

**Comment by hackmastera** [comment]
the bags are in `/mnt/hydra_sources/archives_bd/bcadmin/mss/av_backlog/`
- [ ] la_c0652_2017_05_bag 
- [ ] la_c0799_2017_05_bag
- [ ] la_c0977_2017_05_bag
- [ ] la_c0984_2017_05_bag  
- [ ] la_c0994_2017_05_bag
- [ ] la_c1450_2017_05_bag 
- [ ] la_c1470_2017_05_bag 
- [ ] la_c1502_2017_05_bag 
- [ ] la_c1511_2017_05_bag
- [ ] la_c1513_2017_05_bag

**Comment by jrgriffiniii** [comment]
The case specified in https://github.com/pulibrary/figgy/issues/1907 appears to have been resolved, as all parts for a given side are ingested when testing in my local development environment:

<img width="830" alt="figgy_issues_1559_0" src="https://user-images.githubusercontent.com/1443986/46220193-615dc700-c317-11e8-99cd-91d920fbc1eb.png">

**Comment by hackmastera** [comment]
Awesome thank you for fixing those @jrgriffiniii! I just started an ingest on staging.

**Comment by hackmastera** [comment]
Done; other tickets are tracking issues that came up.
