### ISSUE TITLE
ScannedMap not showing up in DPUL

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1561]
Tom Ventimiglia reported that one East Asian item isn't showing up in DPUL, a ScannedMap:

https://figgy.princeton.edu/catalog/b13a220e-a478-40c2-bcba-7751e3456de4

I don't see any errors in the log, and updating the object or reindexing doesn't fix it either.

**Comment by tpendragon** [comment]
It might be that creating these items don't fire events on the figgy queue, just the one for the maps site.

**Comment by tpendragon** [comment]
Yeah: https://github.com/pulibrary/figgy/blob/0d48fd38e14fbced210a2c2e7f75f152b7012ead/app/services/event_generator/manifest_event_generator.rb#L46

**Comment by escowles** [comment]
OK, so the question is whether we want Geo resources to show up in DPUL.  In this case, the user expected it to — but I'd want to ask @eliotjordan whether there's any specific reason to keep Geo resources out of DPUL.

**Comment by eliotjordan** [comment]
I don't think there are any objections for scanned maps.
