### ISSUE TITLE
Ingest Latin American A/V in production

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1569]

**Comment by hackmastera** [comment]
Dup of #1559?

**Comment by escowles** [comment]
@hackmastera I intended this ticket to be for production ingest — I'll rename it.

**Comment by tpendragon** [comment]
@kelynch @kelea99 Do you know where we're at here? I've lost track, and it's funny because we built AV functionality specifically for this ingest.

**Comment by tpendragon** [comment]
Kelly's ingesting these.
