### ISSUE TITLE
Derivatives generation for Audio

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1572]
If I ingest a WAV file, Figgy should be able to generate an MP3 access file

**Comment by hackmastera** [comment]
There should be a way to turn this off, e.g. if a vendor has provided the derivatives.

**Comment by tpendragon** [comment]
@escowles @hackmastera Is this still a thing we want to keep around?

**Comment by escowles** [comment]
I'm fine closing this ticket because we've got a much clearer conversation with our stakeholders, and if we want to allow users to download MP3 versions of audio files we ingest without pre-generated derivatives, I'm sure Dan would tell us about it.
