### ISSUE TITLE
Automate adding DAO links to finding aids

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1573]
* At the very least, we can generate a report of component IDs and manifest URLs
* Can we script or otherwise automate adding them to the EAD?
* Ultimately want to use ASpace which has an API we could use to add links to digital content

**Comment by tpendragon** [comment]
See #1236

@escowles Could you decide on a way to combine #1236 and this issue?

**Comment by escowles** [comment]
Closing in favor of #1236
