### ISSUE TITLE
Automatic metadata refresh not working?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1574]
See https://github.com/pulibrary/figgy/issues/1200 — there is stale metadata in some Figgy records, so I think the metadata is not being automatically refreshed.

**Comment by tpendragon** [comment]
@escowles Remember we only process changes, we don't do full refreshes - maybe that's the issue?

**Comment by escowles** [comment]
Oh, that's the issue.  These records were all updated shortly before the automatic updates were started.  I'll run a script to update them.
