### ISSUE TITLE
Ingest Trustees/Charter (pudl0004)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1579]
Finding aid
Depends on #1675

**Comment by tpendragon** [comment]
Files: https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by tpendragon** [comment]
PUDL collection: http://pudl.princeton.edu/collections/pudl0004

**Comment by tpendragon** [comment]
This collection is only two items. Neither have MARC identifiers, both have MODS metadata and links to ARKs which resolve to the relevant finding aid and the ARK to PUDL collection. The metadata in the MODS does not match the metadata for the linked finding aid.

For example, for the minutes:

Title: "Board of Trustees Minutes. Volumes I-XII"
Related Finding Aid: https://findingaids.princeton.edu/collections/AC120
Metadata in MODS includes such things as:

Creator (Princeton University Trustees, split into two nameParts)
AAT subject headings: Minutes, Records, Meeting, Bylaws
Origin Info
Date Created (1748-1796)
Language code
physicalDetails
originInfo (Princeton, NJ)
Note
Custom license note:

"With the exception of bylaws, all Trustee minutes and records are closed for 50 years from the date of their
      creation. Exceptions may be made only with the prior approval of University General Counsel and the University Secretary. Access to the original Volume I is restricted; researchers may"
"Single photocopies may be made for research purposes. Permission to publish material from the collection must be
      requested from the University Archivist. Copyright is held by the Trustees of Princeton University."

LCSH subject headings (Princeton University Trustees, Education Higher)
Physical Location (Princeton University Library. Department of Rare Books and Special Collections. Seeley G. Mudd Manuscript Library. Princeton University Archives)

**Comment by tpendragon** [comment]
I think we're going to have to ingest these as SimpleResources, and decide if we need controlled vocabularies for them. Given that, I'm moving on to another collection for the moment.

**Comment by tpendragon** [comment]
| Field               | Example         |
| ------------- | ------------- |
| title                 | "Board of Trustees Minutes. Volumes I-XII" |
| relatedItem    | nested item with title and url to finding aid/PUDL collection |
| genre             | AAT terms, "Minutes", "Records", "Meeting", "Bylaws" |
| originInfo       | placeTerm with Princeton, N.J and a dateCreated with start of 1748 and end of 1796 |
| physicalDetails | Vol. 1: A l., 459 p.; 38 cm. |
| note                | Vol. 1, 1748-1796; v. 2 1797-1823 |
| accessCondition - restrictionOnAccess | With the exception of bylaws, all Trustee minutes and records are closed for 50 years from the date of their creation. Exceptions may be made only with the prior approval of University General Counsel and the University Secretary. Access to the original Volume I is restricted; researchers may access a typed transcript of Volume I in the library. |
| accessCondition - useAndReproduction | Single photocopies may be made for research purposes. Permission to publish material from the collection must be requested from the University Archivist. Copyright is held by the Trustees of Princeton University. |
| subject/lcsh | Corporate name with two nameParts, "Princeton University" and "Trustees" |
| subject/lcsh | Education, Higher |
| abstract        |  Consists of Volume I-XII of the minutes of the Trustees of the College New Jersey, which document Trustees decisions regarding overall policy and administration of the College from 1748-1915. The minutes in Volume I trace the development of the College during its infancy, including its early relocation from Newark, New Jersey to Princeton, New Jersey. |
| location | physicalLocation tags representing "Princeton University Library. Department of Rare Books and Special Collections. Seeley G. Mudd Manuscript Library. Princeton University Archives", an ARK, and a `holdingSimple` tag with MUDD AC120. |
| recordInfo | Record creation date in ISO8601, an origin, and a contentSource which is NjP (code referenced in location above). Also has a languageOfCataloging which is `eng` |

**Comment by escowles** [comment]
I think it's fine to convert names with muliple nameParts to single strings for ingest.  We can do name reconciliation and create or link to controlled vocab records for them, and deal with the metadata needed for the entity there.

**Comment by cwulfman** [comment]
Reach out to Dan Linke and ask him what he would like to do.

**Comment by kelea99** [comment]
Ingested to figgy. closing ticket, @cwulfman 

https://figgy.princeton.edu/catalog/474c056f-24fe-4f60-a30c-019268447a64
