### ISSUE TITLE
Ingest "Postcards" (pudl0009)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1580]
Note: MODS

@jpstroop I assume "MODS" means there's no bib records?
Depends on #1674
Depends on #1675

**Comment by tpendragon** [comment]
Files: https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by tpendragon** [comment]
http://pudl.princeton.edu/collections/pudl0009

**Comment by tpendragon** [comment]
The METS is separated into 5 directories. Each directory is a "series", which is referenced by the MODS. Each series is described in a finding aid: https://findingaids.princeton.edu/collections/AC045.xml

There's no item-level descriptions in the finding aid - there's "parts" of boxes.

| Field | Example |
| --- | --- |
| title (non-Sort) | The |
| title | Chapel, Princeton University |
| relatedItem | Princeton University Historical postcard collection Series 1 Buildings, circa 1900-1960 (separated into a title and two sub-titles |
| publisher | Published by H. M. Hinkson, Stationer, Princeton, N. J. & The Albertype Co., Brooklyn, N.Y. |
| publisher date | 1941 |
| language | eng |
| abstract | Exterior view of the chapel in black and white. Divided back postcard. |
| genre (aat) | Picture postcards |
| subject (aat) | Eye-level views, Exterior views |
| subject (lcsh) | Princeton University, Buildings, Princeton University. Chapel |
| location | Princeton University Library. Department of Rare Books and Special Collections. Seeley G. Mudd Manuscript Library. |

**Comment by tpendragon** [comment]
When migrating sort title, migrate into two fields: "Sort Title" and "Title." Title would be "The Chapel, Princeton University" and sort title would be "Chapel, Princeton University."

**Comment by tpendragon** [comment]
May be more complicated because there are sometimes more than one publisher and the published date is associated with the publisher.

**Comment by jpstroop** [comment]
Are we controlling publisher? I could imagine a single publication statement that's just a string (could include both publishers, dates and locations in whatever format, all in one field) and then separate controlled fields for publisher (just another name with a role of publisher), date(s), and location.

**Comment by christinach** [comment]
Some files include more than one <originInfo>: 
```
<originInfo>
      <publisher>Published by H. M. Hinkson, Stationer, Princeton, N. J.</publisher>
 </originInfo>
 <originInfo>
      <publisher>The Albertype Co., Brooklyn, N. Y.</publisher>
</originInfo>
```
In this case do we want to pull publication information from the first node or from all?

**Comment by jpstroop** [comment]
Definitely need both. Is publisher (or what ever it is) a repeatable field?

**Comment by christinach** [comment]
@jpstroop based on your previous comment my understanding was to add a publication field and pull the publisher, dates and locations information from the originInfo node. 
I'm not sure I understand '..Is publisher a repeatable field..'

**Comment by christinach** [comment]
I can add only the publisher information. The date is stored separately.

**Comment by tpendragon** [comment]
@christinach For now I'd just make two fields "publisher" and "published date." Extract the publisher name part to publisher and the date part of the publication to published date. (There's also a dateCreated, but that should be handled already right?)

**Comment by christinach** [comment]
yes, dateCreated is stored already. I'm assuming dateOther is the published Date.

**Comment by tpendragon** [comment]
@christinach I think that's accurate. There's also a `<copyrightDate>` it looks like.

**Comment by tpendragon** [comment]
`1/0196.mets` also has a `dateIssued`

**Comment by christinach** [comment]
yes there is a copyrightDate

**Comment by christinach** [comment]
@tpendragon thank you, I will add all the dates

**Comment by christinach** [comment]
The folder pudl0009 includes a folder 'uncat' with tif, img and png files. @roelmoon said that the png and jpg can be ignored (or deleted).
