### ISSUE TITLE
Ingest "Ivan Susanin" (pudl0018)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1582]
Notes: (From UPenn; limited use case. Offer them Images?)

@jpstroop Can you expand on what "limited use case" means?

**Comment by escowles** [comment]
Who would be talk to about these at UPenn?

**Comment by jpstroop** [comment]
> Can you expand on what "limited use case" means?

We did this volume in ~2006 for a Princeton Grad student, and it's just one volume of the complete works. I wrote a note to @egmowens over the summer to see if Penn would like a copy, but I don't think I ever heard back.
