### ISSUE TITLE
Ingest "19th c. sheet music" (pudl0020)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1583]
Note: 3 or 4 vols in PUDL; many more images available. Migrate manually?

Details: https://docs.google.com/spreadsheets/d/1f-c3goE0CC2QJ0Cbk_-JN67nk3fpI9J2Dl37AhGIzos/edit#gid=17

**Comment by tpendragon** [comment]
http://pudl.princeton.edu/collections/pudl0020

**Comment by jrgriffiniii** [comment]
I suspect that the items in this collection which have been published to PUDL do have Voyager records, but they are not linked by ARK from the MARC record (please see http://pudl.princeton.edu/objects/xd07gt10f and https://catalog.princeton.edu/catalog/10738958)

**Comment by jrgriffiniii** [comment]
Without proper Bib. IDs, `BulkIngestService` fails to create new resources during ingestion (as the attributes provided for the `ScannedResourceChangeSet` are invalid)

**Comment by jrgriffiniii** [comment]
Directory names for these are not valid bib. IDs (e. g. `smb://diglibdata1.princeton.edu/pudl/pudl0020/vol02/001/`), hence I have introduced the following: https://github.com/pulibrary/figgy/compare/issues-1583-jrgriffiniii-pudl0020.

I can proceed by issuing this as a pull request, and then looking to ingest these into staging using a local ID containing `pudl0020/vol02/001`

**Comment by hackmastera** [comment]
@jrgriffiniii do we want to expand the script for use with pulfa objects? Or should we keep the `bibdata?` check in, as well?

**Comment by jrgriffiniii** [comment]
I'm sorry, I misunderstood, where are these referenced from within PULFA?  I cannot find metadata for these.  For example using "Alpine songs" from http://pudl.princeton.edu/objects/xg94hq91z, I cannot retrieve any records: https://findingaids.princeton.edu/?v1=Alpine+songs&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0

**Comment by hackmastera** [comment]
@jrgriffiniii it might be helpful if you create the PR and i can comment there

**Comment by jrgriffiniii** [comment]
@hackmastera please see https://github.com/pulibrary/figgy/pull/1668

**Comment by jrgriffiniii** [comment]
@tpendragon unfortunately, what I found was just anomalous.  Sample 10 items from the vol. 2 only yielded one _possible_ bib. ID:

PUDL File ID | PUDL URL | Bib. ID
-- | -- | --
vol02/001 | http://pudl.princeton.edu/objects/xg94hq91z | Could not be found
vol02/002 | http://pudl.princeton.edu/objects/cf95jc83x | Could not be found
vol02/003 | http://pudl.princeton.edu/objects/qr46r2201 | Could not be found
vol02/004 | http://pudl.princeton.edu/objects/9p290b725 | Could not be found
vol02/005 | http://pudl.princeton.edu/objects/vh53wx12q | Could not be found
vol02/006 | http://pudl.princeton.edu/objects/4x51hk40b | Could not be found
vol02/007 | http://pudl.princeton.edu/objects/rr171z595 | Could not be found
vol02/008 | http://pudl.princeton.edu/objects/pz50gx48r | Could not be found
vol02/009 | http://pudl.princeton.edu/objects/sq87bv998 | Could not be found
vol02/010 | http://pudl.princeton.edu/objects/bn999811q | https://catalog.princeton.edu/catalog/8974323

**Comment by jrgriffiniii** [comment]
Invoking the Rake task using the following arguments ingests the item as a Work `bundle exec rake bulk:ingest DIR=[...]/pudl/pudl0020/vol02/001 REPLACES=pudl0020/vol01/001 LOCAL_ID=pudl0020/vol01/001`

**Comment by jrgriffiniii** [comment]
It consumes a significant amount of time (over 30 minutes), but the ingestion was successful within the staging environment: https://figgy-staging.princeton.edu/catalog/3ce08e8f-0eba-4a6c-8fa9-4eb109613761

**Comment by jrgriffiniii** [comment]
After reviewing this issue with tpendragon, it does not appear to be the case that there are MARC records for all of the items in PUDL collection:
> @tpendragon unfortunately, what I found was just anomalous. Sample 10 items from the vol. 2 only yielded one possible bib. ID:
https://github.com/pulibrary/figgy/issues/1583#issuecomment-414366783

@joycebcat is this expected for http://pudl.princeton.edu/collection.php?c=pudl0020?  If so, I can look to further prioritize ingesting these items with the understanding that MARC records shall be linked (or provided) at a later date

**Comment by joycebcat** [comment]
@jrgriffiniii These were originally done in MODS.  I converted the records to MARC and gave them to Brittany at the Music Library in March to review and import into Voyager (there were a few things which had to be reviewed post-conversion).  They will eventually have Voyager records.  I will nudge her now about them.  I guess it can be up to her to search for them in figgy and put in the Voyager ID when she creates the Voyager record if they are ingested now.

**Comment by escowles** [comment]
Ingest without metadata and add to a collection for retrieval and adding bib numbers later.

**Comment by escowles** [comment]
Here is the mapping for items in vols. 1-6:
[19th_sheetmusic.xlsx](https://github.com/pulibrary/figgy/files/3497974/19th_sheetmusic.xlsx)

Items in subsequent vols should be ingested without bib records, and the vol/issue numbers as the title, and left in pending state for future cleanup after the Bib records are created.

**Comment by escowles** [comment]
The items with Voyager records were ingested using them, the ones without were ingested with just the directory as the title, and Brittany will add the Bib IDs as they are cataloged.  All of them have the `replaces` attribute set to make it easier to identify them.
