### ISSUE TITLE
Ingest "Jackson Prints" (pudl0031)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1584]
Note: VRA/GA, but records don't all map to Voyager - Triptychs, etc.

**Comment by tpendragon** [comment]
http://pudl.princeton.edu/collections/pudl0031

**Comment by jrgriffiniii** [comment]
No METS metadata were found within https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by escowles** [comment]
Needs metadata
