### ISSUE TITLE
Ingest "Mandelʹshtam" (pudl0037)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1587]
Notes: Finding aid

**Comment by escowles** [comment]
https://findingaids.princeton.edu/collections/C0539

**Comment by tpendragon** [comment]
Not only are some of these ingested, they're even linked in finding aids: https://figgy.princeton.edu/catalog/06c536c9-f999-4b53-be56-144500491f45

**Comment by tpendragon** [comment]
https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Osip+Mandel%CA%B9shtam+Papers+C0539
