### ISSUE TITLE
Ingest "Berthier" (pudl0042)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1591]
May become ScannedMaps?

Ping @eliotjordan These look like maps?

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by escowles** [comment]
Ingest as ScannedMaps

**Comment by eliotjordan** [comment]
This is a case where the majority of the images are text with some, admittedly nice, maps interspersed. I'm not really sure what to do in these cases. Ingest as a ScannedResource and just forgo ingesting the maps into GeoBlacklight? Ingest as ScannedMaps and have many non-image records in Pulmap? Some kind of mixed approach?

**Comment by escowles** [comment]
A mixed approach seems like it is worth exploring.  Maybe we could ingest the whole collection as ScannedResources, and then ingest a subset as ScannedMaps?  Who would select the maps to ingest?

**Comment by tpendragon** [comment]
`pudl0042` on the isilon PUDL directory is empty now? Also: https://figgy.princeton.edu/catalog/1d244d71-2a5e-4b7a-ade5-4fee32821ce2

**Comment by cwulfman** [comment]
Ingested as ScannedResources to be converted to maps later.
