### ISSUE TITLE
Ingest "Common Place Books" (pudl0056)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1595]

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by escowles** [comment]
@tpendragon I see only one item in the `pudl0056` directory: 1202490 — and the two bibs in the description are Islamic manuscripts, so maybe that was intended for a different collection?

I think the decision is the same, though: ingest from Isilon.

**Comment by escowles** [comment]
Nevermind, found the collection that was a reference to —moving over to #1596

**Comment by cwulfman** [comment]
Graham Burnett approached Ben Primer in the summer of 2009 with a request for digital photos of the opening pages of PN6245.C65, Common place book / formed generally upon the principles recommended and practised by John Locke.  

Ingest as regular ScannedResource

**Comment by kelea99** [comment]
ingesting 1202490 as scanned resource and linking it to bib id

**Comment by kelea99** [comment]
This needs to be done at the command line to only ingest the tiffs (1202490).

**Comment by cwulfman** [comment]
bundle exec rake bulk:ingest COLL=b3b2415b-1ae6-4fba-ac26-3bdb4858cc08 BIB=1202490 DIR=/mnt/diglibdata/pudl/pudl0056/1202490 FILTER=.tif

https://figgy.princeton.edu/catalog/ce521bb2-e77a-4b77-b5f1-6de80c6764a2
