### ISSUE TITLE
Migrate "Afghanistan" (pudl0054)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1596]

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by escowles** [comment]
Ingest from Isilon.

**Comment by cwulfman** [comment]
These are two books digitized for NYU's Digital Library Project.  They should be ingested as regular scanned resources

**Comment by kelea99** [comment]
ingesting 29054002 and 3043062 as scanned resources and linking to bibs

**Comment by cwulfman** [comment]
https://figgy.princeton.edu/catalog/5a739503-fe5c-402c-b5e8-316ca7fd6925
