### ISSUE TITLE
Migrate "Jamaica Rebellion" (pudl0060)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1597]
Migration for this was started, but it's a photo album where every page has close-up shots of the individual pictures. We need to figure out the best way to make these display.

**Comment by tpendragon** [comment]
In the "digital library bookshelf" - http://pudl.princeton.edu/collection.php?c=og&sort=title&rpp=14&start=14

**Comment by tpendragon** [comment]
Julie says this one's her most popular item, and would really like it up.

**Comment by tpendragon** [comment]
This is odd: https://figgy.princeton.edu/catalog/4f951479-915d-481a-b157-33250e73ba3d

Someone migrated this late July. Maybe it was me? I thought I deleted it though.

**Comment by cwulfman** [comment]
https://figgy.princeton.edu/catalog/4f951479-915d-481a-b157-33250e73ba3d is sufficient; the deep zoom reproduces the PUDL behavior adequately.
