### ISSUE TITLE
Migrate "Periodicals" (pudl0061)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1598]
These aren't currently displayed anywhere. Migrate?

Ping @jpstroop @joycebcat 

Details: https://docs.google.com/spreadsheets/d/1f-c3goE0CC2QJ0Cbk_-JN67nk3fpI9J2Dl37AhGIzos/edit#gid=28

**Comment by escowles** [comment]
@cwulfman Should these go in Veridian?

**Comment by cwulfman** [comment]
They're already in Veridian: Pan & Ver Sacrum are in Blue Mountain; Vozrozhdenie are in historic periodicals.

**Comment by escowles** [comment]
Closing since these are all ingested into Veridian instances.
