### ISSUE TITLE
Ingest "Vandermaelen Atlas" (pudl0064)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1600]
Will ingest as a ScannedMap probably?

Ping @eliotjordan - do we have necessary functionality for Atlases?

Depends on #1786

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by eliotjordan** [comment]
Depends on #1786

**Comment by escowles** [comment]
I see this item ingested in pending state: https://figgy.princeton.edu/catalog/4bed7be5-518e-4879-b485-403c9f09a1f7

@eliotjordan @kelea99 who should review this item?

**Comment by kelea99** [comment]
@escowles I would say Vicki Principi would be the person to ask about this/complete it. She works with historic maps in RBSC as well.  I can email her for you.

**Comment by kelea99** [comment]
@escowles and @eliotjordan - Vicki P. will review and complete these items today (08/01). Thanks!

**Comment by eliotjordan** [comment]
@esme @kelea99 I just this. The Vandermaelen Atlas is in Figgy in a pending state because I was working on it awhile back. It is quite complex for a variety of reasons and wasn't completed. It's been on in on the backlog for awhile now.

**Comment by eliotjordan** [comment]
Outstanding work:

- Images need to be converted to individual scanned map children while maintaining structure.
- Many of the pages in the Atlas were cataloged separately in Voyager have already been ingested into Figgy as individual sheets. These need to be moved into the atlas or deleted.
  - https://figgy.princeton.edu/catalog/79e865c5-1abc-4978-a10b-6528b75066bd
  - https://catalog.princeton.edu/catalog/5740218
- Bound boxes need to assigned to images not cataloged individually.

**Comment by cwulfman** [comment]
@kelea99 discovered this: https://lib-dbserver.princeton.edu/visual_materials/maps/websites/vandermaelen/home.htm

**Comment by cwulfman** [comment]
The tif images in /mnt/diglibdata/pudl/pudl0064/2397415/ have been ingested into Figgy as a MVW.  The issues @eliotjordan raises above are out of the scope of the PUDL migration. I don't think the PUDL shut-down should be blocked by this.
