### ISSUE TITLE
Ingest "GNIB" (pudl0066)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1601]

**Comment by escowles** [comment]
Migrate as ephemera.

**Comment by escowles** [comment]
MODS metadata records: 
[GNIB.zip](https://github.com/pulibrary/figgy/files/2353164/GNIB.zip)

**Comment by cwulfman** [comment]
https://docs.google.com/spreadsheets/d/1UFrvkj_B9IhlFX9SS9H_lKYzN2SawAC2OfAEIkrUZ7A/edit?usp=sharing contains separate SIPs for each section of the GNIB, derived from the METS and, through them, the MODS.  These should be used to re-ingest the GNIB collection using `rake ingest_ephemera`

**Comment by cwulfman** [comment]
The above strategy was abandoned.

**Comment by cwulfman** [comment]
@kelea99 notes:
>The genre doesnt read in the required field (I know it is there on the main sheet, but it is not in edit mode, which is odd. ), making it impossible to save and complete, there is not a subject for all items which also makes it impossible to save and complete and there is no collection associated with them. 

- [ ] Genre is not correct
- [ ] Add "Guatemala" as subject for everything
- [ ] Add everything to https://figgy.princeton.edu/catalog/e9709523-ec23-4eb0-9dd3-002746b91d13

**Comment by tpendragon** [comment]
@cwulfman Close?

**Comment by kelea99** [comment]
@cwulfman can we please get these all batch completed? thanks.

**Comment by cwulfman** [comment]
To clarify: you'd like me to programmatically mark all the items in the GNIB collection as completed, correct?  The updated data is correct?

**Comment by kelea99** [comment]
Im leaving it to you to decide if it is correct, as you know it better than i.  if it is, then  programmatically mark all the items in the GNIB ephemera project complete. thanks!

**Comment by cwulfman** [comment]
The job ran part-way but was interrupted.  I'll finish the rest of these when I return on Tuesday

**Comment by kelea99** [comment]
Checking figgy - all items complete. Closing ticket
