### ISSUE TITLE
Ingest "A Japanese sugoroku" (pudl0082)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1605]
Notes: Almost certainly 10636676, just needs to be ingested manually

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by kelea99** [comment]
items ingested into bib id noted above: https://catalog.princeton.edu/catalog/10636676

Figgy: https://figgy.princeton.edu/catalog/9e1a9979-78fa-4c8d-b65a-d2288c5f7d83
