### ISSUE TITLE
Ingest "Japanese maps" (pudl0092)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1610]
These don't seem to be displayed anywhere. Migrate?

Ping @jpstroop @joycebcat

**Comment by escowles** [comment]
I think these are mostly migrated:

https://catalog.princeton.edu/catalog/6773431
https://catalog.princeton.edu/catalog/6773457
https://catalog.princeton.edu/catalog/6773474

@eliotjordan I'm only seeing 1 of the 8 on the middle one (6773457) — are the rest ingested but not linked to the right ARK, or do they need to be ingested?

**Comment by kelea99** [comment]
https://catalog.princeton.edu/catalog/6773431 : VIewing in Figgy and Online Catalog

https://catalog.princeton.edu/catalog/6773457 : wow, this one is messy.  we do have [one complete mapset ](https://figgy.princeton.edu/catalog/77c7d8cf-6753-456a-94d5-c7f2349ad02f)that I am completing, @eliotjordan . If you approve, I will delete all other ingests that seem to be duplicate bad ingests that are not mapsets ([search results link](https://figgy.princeton.edu/?page=2&q=6773457))

https://catalog.princeton.edu/catalog/6773474: viewing in figgy and online

**Comment by kelea99** [comment]
this is related: https://github.com/pulibrary/figgy/issues/3191. Closed this ticket and leaving 3191 open.
