### ISSUE TITLE
Ingest "Cedid atlas tercümesi, the first Turkish atlas" (pudl0115)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1616]
Notes: SHOULD WORK

@eliotjordan Should we be ingesting Atlases as ScannedMaps?

**Comment by tpendragon** [comment]
Files: https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by kelea99** [comment]
@eliotjordan does this have the same/similar problem as the Vandermaelen? Not in figgy at all.

**Comment by eliotjordan** [comment]
Looks like this is done.

https://figgy.princeton.edu/catalog/27152fc8-e70d-4fbd-8d2f-250405b4548f
