### ISSUE TITLE
Ingest "Watermark specimens" (pudl0120)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1619]
Notes: SHOULD WORK - could be a map set, but ingest as a SR for now

@eliotjordan Should we ingest these as an SR or a ScannedMap?

**Comment by tpendragon** [comment]
Files: https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by kelea99** [comment]
ingested in figgy. @tpendragon and @cwulfman I am closing this ticket. if the ingest is not correct, please do reopen:

https://figgy.princeton.edu/catalog/bb133ab0-bd26-41a4-87df-970e3e5260a6
