### ISSUE TITLE
Ingest "Atlas of NJ" (pudl0124)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1622]
Notes: SHOULD WORK - could be a map set, but ingest as a SR for now

@eliotjordan Ingest as a SR still? Or SM?

**Comment by tpendragon** [comment]
Files: Files: https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by tpendragon** [comment]
http://pudl.princeton.edu/collections/pudl0124

**Comment by eliotjordan** [comment]
Done.

https://catalog.princeton.edu/catalog/1943935
https://maps.princeton.edu/catalog/princeton-p2676w91q
