### ISSUE TITLE
Ingest "Moscow mayoral election ephemera" (pudl0125)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1623]
Notes: MODS / Collection level MARC
What does collection level MARC even mean?
Depends on #1674 
Depends on #1716
Depends on #1738
Depends on #1748

**Comment by tpendragon** [comment]
Files: https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by tpendragon** [comment]
http://pudl.princeton.edu/collections/pudl0125

**Comment by tpendragon** [comment]
http://pudl.princeton.edu/collections/pudl0125

**Comment by tpendragon** [comment]
Okay. The collection as a whole has a bib #: https://catalog.princeton.edu/catalog/7867489

Each item inside is described at the item level.

| Field | Example |
| title(latin) | Programma kandidata v mėry Moskvy Aleksei︠a︡ Navalʹnogo; 2013 god |
| subTitle(latin) | izmeni Rossii︠u︡, nachni s Moskvy |
| title(Cyrillic) | Программа кандидата в мэры Москвы Алексея Навального; 2013 год |
| subtitle(Cyrillic) | измени Россию, начни с Москвы |
| typeOfResource | text |
| genre (aat) | Ephemera |
| dateCreated | 2013 |
| language | rus |
| extent | 20 pages ; 21 cm |
| note(latin) | "Izgotovleno OOO ’Poligraficheskiĭ kompleks’. 143300, g. Naro-Fominsk, M.O., ul. Kalinina, d. 8/1, INN 50300045907. Zakazchik- kandidat na dolzhnostʹ Mėra Moskvy Navalʹnyĭ Alekseĭ Anatolʹevich. Data vypuska 23.07.2013, tirazh 30 000 ėkz. Oplacheno iz sredstv izbiratelʹnogo fonda kandidata na dolzhnostʹ Mėra Moskvy Navalʹnogo Aleksei︠a︡ Anatolʹevicha." |
| note(Cyrillic) | Same as above, but in cyrillic script. |
| note | Additional AAT genre: pamphlets. (weird) |
| subject lcsh (naf) | Navalʹnyĭ, Alekseĭ |
| subject lcsh (naf) | Respublikanskai︠a︡ partii︠a︡ Rossiĭskoĭ Federat︠s︡ii |
| subject (topic) | Mayors |
| subject (geographic) | Russia (Federation), Moscow |
| subject (topic) | Elections |
| subject (temporal) | 21st century |
| subject(genre) | Sources |
| physicalLocation | Rare Books Off-Site Storage (rcpxr) |
| physicalLocation code | NjP |
| accessCondition - useAndReproduction | http://www.princeton.edu/~rbsc/research/rights.html |
| accessCondition - restrictionOnAccess | http://www.princeton.edu/~rbsc/research/rules.html |
| recordInfo - languageOfCataloging | eng |

The most unique things here seem to be subject headings from a name authority file and the requirement for multiple scripts in a title. We handle the multiple scripts for our islamic manuscripts, but they've always been imported - and I don't think we do anything with sub titles?

A lot of these are handled in Ephemera - I wonder if we should migrate that way? We'd just have to figure out how to move over extent, type (although I think LAE has this modeled as "genre"), and handle multiple scripts.

**Comment by tpendragon** [comment]
@joycebcat Was the "collection of ephemera has a MARC record" just a practice from the past?

**Comment by joycebcat** [comment]
@tpendragon No.  We still do cross-over records in the catalog at the collection-level for a number of things whose detailed access is provided elsewhere.

**Comment by tpendragon** [comment]
@joycebcat Alright. We shouldn't need to hook that marc record to anything in Figgy though yeah?

**Comment by joycebcat** [comment]
@tpendragon Correct.  In figgy each bit of ephemera is going to have its own data.

**Comment by tpendragon** [comment]
This adds the requirement that sometimes a title will have a subtitle associated with it, meaning at times a title will be a nested object and we'll need some UI for like "+ subtitle"

**Comment by hackmastera** [comment]
Discussion of the title / subtitle wireframes led to discussion of linking titles with their transliterations. The titles in the mets different scripts are linked via `altRepGroup`. This means that data exists linking a given title and its transliteration. We need to know whether that link must be preserved. If so, we need to do additional modeling and wireframe work here. See slack discussion in #digital_library from this day for more background / info.

**Comment by cwulfman** [comment]
Done https://figgy.princeton.edu/catalog/1e2ae9ae-1381-4f5e-9453-25cc2ec5c1be
