### ISSUE TITLE
Ingest "German Modernism" (pudl0131)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1626]
Notes: Ask Cliff

@cwulfman I'm not sure what the story here is entirely, but it says to ask you about this collection - are we migrating "German Modernism" into Figgy? And can you give a background on what the collection is?

**Comment by cwulfman** [comment]
Let me apologize in advance for a long-winded answer, which also applies to issue #1632.

"German Modernism" is/was a project to digitize/rescue an important collection of avant-garde German magazines that the Library bought in the 50s(?) and then dispersed into the general collection, where many titles, printed on cheap paper, have crumbled into confetti. Blue Mountain collaborated with Rex Hatfield to identify the collection and start the project.

At the moment, it is a set of four or five early twentieth-century German arts magazines we processed in the Blue Mountain vein: item-level descriptive metadata, METS/ALTO representation via docWorks (via a vendor) that included preservation-grade tiffs, generative and delivery-grade jp2s, and PDFs. All these titles have been (or should have been) ingested into Blue Mountain's Veridian instance.

Now: those deliverables are derivatives of what the DPS shot: we've had numerous discussions over the years about the differences between capture and processing/presentation. The studio shoots everything: if the magazine issues were bound into volumes by the library, the Studio shoots the bindings, any front and back matter, etc. For the magazine projects, the subject of digitization was not the library's holdings but the issues of the magazine, so the Blue Mountain (and German Modernism) editions don't include that matter.


Why does that matter? Well, the plan, as I understand it, is to migrate Blue Mountain (and German Modernism), along with the METS/ALTO newspapers, into Figgy, eventually. But those issues aren't *exactly* what the Studio shot -- they are not faithful remediated copies of PUL's holdings. At the same time, those derivatives have received the most attention and the highest level of processing, and it would be odd to throw them away. I doubt you want to manage both. So I think there's a philosophical issue disguised as a policy issue lurking in this, and I'd be happy -- eager, even -- to talk more about this.

**Comment by cwulfman** [comment]
keep the source tiffs but hold off migrating to Figgy until a METS/ALTO strategy is developed.
