### ISSUE TITLE
Ingest "Persian periodicals" (pudl0136)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1628]
Notes: (In Progress)

@escowles Who is this in progress by?

**Comment by tpendragon** [comment]
No PUDL collection page.

**Comment by escowles** [comment]
I don't know about anybody working on this.  Given that it's a periodical, maybe @cwulfman ?

**Comment by escowles** [comment]
@cwulfman Sorry for the shorthand Github messages — I was doing a second round of triage on the roughly 60 PUDL collections that still need to be migrated.  This collection, and several other periodical collections, might be good candidates for migrating to Veridian.  Do you have time to talk about how we should handle these?  I'm mostly free this week if you have time.

**Comment by roelmoon** [comment]
The Persian Periodicals are something we've been pecking away at when Muhanad isn't working on ACO. Kim Leaman has been de facto project manager on this. They require some post-imaging processing requiring language proficiency, so the Isilon has just been a holding place for these.

**Comment by cwulfman** [comment]
@escowles I'm free all day today; we could talk this afternoon, or before/after the IT Suite meeting tomorrow at 1:30.  What works for you?

**Comment by kelea99** [comment]
@roelmoon , Wafa or I can confirm these are ready to go and is there any reason why we can't just bulk ingest them ourselves as a MVW from the isilon now that bulk ingest is working?

**Comment by kelea99** [comment]
@roelmoon can we ingest these?

**Comment by kelea99** [comment]
@roelmoon where are we with this?

**Comment by kelea99** [comment]
Ingested to figgy. available in online catalog (one title total).  closing ticket.
