### ISSUE TITLE
Ingest "WA--part 2" (pudl0137)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1629]
Notes: SHOULD WORK

**Comment by tpendragon** [comment]
Tarball: https://drive.google.com/drive/u/0/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by tpendragon** [comment]
Files in "PUDL Tarballs"

**Comment by tpendragon** [comment]
http://pudl.princeton.edu/collections/pudl0137

**Comment by hackmastera** [comment]
requested access to the files; not sure who owns them.

**Comment by hackmastera** [comment]
(update: I'm in!)

**Comment by hackmastera** [comment]
I ingested these on staging. there are the right number of items but they don't appear to match the items on pudl.
https://figgy-staging.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=pudl0017
vs
http://pudl.princeton.edu/collections/pudl0137

**Comment by tpendragon** [comment]
Yeah, that's interesting. The items you ingested appear to be part of PUDL0017 (like the METS said I guess) - I wonder if there's something weird with the .tar files?

**Comment by tpendragon** [comment]
@hackmastera It looks like they didn't all get added to the collection too? For instance: https://figgy-staging.princeton.edu/catalog/7abacc88-2e95-4e22-ae71-4fd72a22cebe

**Comment by hackmastera** [comment]
oh good find. there were twice as many mets in that file as there were items in the pudl collection. maybe some of them just never made it into pudl. will check to see if the ones that actually were in pudl somehow escaped being added to the collection.

**Comment by hackmastera** [comment]
okay all of them are there. That file of mets contained 6 from pudl0017 and 6 from pudl0137. I did the staging ingest before https://github.com/pulibrary/figgy/pull/1680 was merged. when ingested for real, both collections should be auto-created at point of need so this shouldn't be an issue.

Not sure why these 0017 ones ended up in the same directory. but I don't see them in figgy prod so I guess it makes sense to bring them in.

**Comment by hackmastera** [comment]
@joycebcat there are 12 objects in the scanned folder for this pudl collection that do not have mets records. Should they be ingested? If so I will move them to a new location on disk and create a new ticket for them.

**Comment by hackmastera** [comment]
6 new items were added to the "Western Americana" collection: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Western+Americana+Collection&f%5Bstate_ssim%5D%5B%5D=pending

6 new items were added to a collection called "pudl0137": https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=pudl0137

12 objects were moved on disk into `pudl0137-no-mets`, and ticketed as #1690
