### ISSUE TITLE
Ingest "Zelda Fitzgerald" (pudl0140)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1631]
Notes: This part of 831946. Could manually ingest w/ a part note

By "part of 831946" it means it's not a full digital scan of the book with the bib id 831946.

**Comment by tpendragon** [comment]
No PUDL collection page

**Comment by cwulfman** [comment]
Ingested and linked to finding aid: https://findingaids.princeton.edu/collections/C0183/c0280
