### ISSUE TITLE
Ingest "Ukrainian election ephemera" (pudl0144)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1633]
These don't seem to be displayed anywhere. Migrate?

Ping @jpstroop @joycebcat

**Comment by escowles** [comment]
The metadata for this collection is in `\\lib-tsserver\GNIB\Ukraine\Collection` — these should be migrated as ephemera

**Comment by escowles** [comment]
MODS metadata records:
[ukrainian.zip](https://github.com/pulibrary/figgy/files/2353158/ukrainian.zip)

**Comment by cwulfman** [comment]
https://catalog.princeton.edu/catalog/10076487
