### ISSUE TITLE
Ingest "Carvajal manuscript" (pudl0146)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1634]
Notes: Photography outsourced, non-PUL item. Finding aid?

@jpstroop @joycebcat What's the implication of the photography being outsourced? Are there special access restrictions or something?

**Comment by escowles** [comment]
This has a bib number and can be ingested.

**Comment by joycebcat** [comment]
No special access restrictions just because something has been outsourced.  This does NOT have to be private, and it should be ingested.

**Comment by escowles** [comment]
I received an email about this item from Steve Ferguson, who had received an inquiry from a user interested in this item.  I ingested the images and created the structure, and send the item to Steve for review.
