### ISSUE TITLE
[Figgy/production] MiniMagick::Invalid: `identify /tmp/mini_magick20180731-32439-gsbo7s.zip` failed with error:
identify: no decode delegate for this image format `ZIP' @ error/constitute.c/ReadImage/512.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1637]
## Backtrace

    line 81 of [PROJECT_ROOT]/app/derivative-services/jp2_derivative_service.rb: create_tiff_derivative
    line 75 of [PROJECT_ROOT]/app/derivative-services/jp2_derivative_service.rb: run_tiff_derivatives
    line 68 of [PROJECT_ROOT]/app/derivative-services/jp2_derivative_service.rb: run_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38903399)

**Comment by tampakis** [comment]
Looks like the derivatives were expecting tiffs but got zip files instead.

**Comment by tpendragon** [comment]
@eliotjordan This was a previously known characterization bug for geo resources yeah?

**Comment by eliotjordan** [comment]
Yep. See https://github.com/pulibrary/figgy/issues/1639
