### ISSUE TITLE
[Figgy/production] RubyTikaApp::CommandFailedError: execution failed with status WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Font not found: Verdana
WARN  Fo...

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1638]
## Backtrace

    line 29 of [PROJECT_ROOT]/app/characterization_services/tika_file_characterization_service.rb: json_output
    line 33 of [PROJECT_ROOT]/app/characterization_services/tika_file_characterization_service.rb: file_characterization_attributes
    line 22 of [PROJECT_ROOT]/app/characterization_services/tika_file_characterization_service.rb: characterize

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38688155)

**Comment by tampakis** [comment]
Would adding `sudo apt-get install msttcorefonts` to the ansible script resolve the issue?

**Comment by tpendragon** [comment]
I can't find any of the FileSets this happened to on Figgy - looks like they've all been deleted?

**Comment by eliotjordan** [comment]
This is an issue, again, with PDFs inside of shapefiles. Installing `msttcorefonts` doesn't help; I tried on staging.

I suggest closing this ticket as I opened up an issue for this: https://github.com/pulibrary/figgy/issues/1639
