### ISSUE TITLE
PDFs and XML files in shapefiles cause errors during characterization

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1639]
Tika is overzealous in it's duties and dives inside a zip archive causing it to raise an exception or assign an incorrect mime type. There is (hopefully) a Tika config setting  that will prevent this behavior.

**Comment by escowles** [comment]
I believe adding this to the tika config file will prevent inspecting the contents of the zip files:

```
<detector-exclude class="org.apache.tika.parser.pkg.ZipContainerDetector"/>
```

**Comment by eliotjordan** [comment]
Nice. Thanks @escowles!
