### ISSUE TITLE
Why does `IndexingAdapter` behave like a Valkyrie::Persister?

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1649]
https://github.com/pulibrary/figgy/blob/master/spec/adapters/indexing_adapter_spec.rb

but it's registered as a MetadataAdapter. I am confused about the use of adapter / persister vocabulary.

**Comment by escowles** [comment]
@hackmastera I believe the main purpose of splitting out the persister from the query service is to separate the concerns: persister does create/update/delete, query service does reads.  For example, in a traditional ActiveFedora setup, your persister would only need to use Fedora, but your query service would mostly be implemented with Solr.

**Comment by hackmastera** [comment]
related to https://github.com/samvera-labs/valkyrie/issues/577

**Comment by hackmastera** [comment]
@escowles Yes I totally understand and support all that. and I get that an "adapter" is just a persister and a query service. I just feel like the language is overloaded somewhere, or is being used in a sloppy way? I don't understand why you can register something as an adapter (which presumably would provide a query service) if it behaves like a persister.

**Comment by tpendragon** [comment]
Oh. I just didn't want to make two spec files at the time. The shared spec relies on the let(:persister) being set, so it's using that. Could be in a context or a separate file if it's causing confusion?
