### ISSUE TITLE
Wireframe for Bulk Complete

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1651]

**Comment by tpendragon** [comment]
We're going to create an interface on search results for "Bulk Edit" where you click a button and go to another page, which will store the search you had done and allow you to pick a rights statement to apply (or not) and a radio button for "Mark Complete" or what have you.

**Comment by hackmastera** [comment]
proposal for bulk edit button: https://docs.google.com/drawings/d/1gwE9F5ADWJfW06bd7Nx88ayWkl3qTqcxRcc9V6i1xIo/edit

**Comment by hackmastera** [comment]
form proposal 1: https://docs.google.com/drawings/d/15XEY_fFe6g23ObS2cDscJK7MGyBffrwLZ-TSSCt7BTQ/edit

form proposal 2: https://docs.google.com/drawings/d/1Bc02nYEKm4tjE0MhtTclkG6xxpAOobdg7l3MNrbWinQ/edit

**Comment by hackmastera** [comment]
Here are some final wireframes.

Button at top of search results form:
![1651 bulk edit button](https://user-images.githubusercontent.com/845363/44470530-fb836e80-a5f7-11e8-8c12-ad820ae23cec.png)

Bulk edit form:
![1651 bulk edit form 1](https://user-images.githubusercontent.com/845363/44470667-50bf8000-a5f8-11e8-881a-d26f76e68297.png)
