### ISSUE TITLE
[Figgy/production] ActionView::Template::Error: undefined method `sort_by' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1655]
## Backtrace

    line 3 of [PROJECT_ROOT]/app/views/records/edit_fields/_member_of_collection_ids.html.erb: _app_views_records_edit_fields__member_of_collection_ids_html_erb__3375520154541407247_53312860
    line 2 of [PROJECT_ROOT]/app/views/base/_form_metadata.html.erb: block in _app_views_base__form_metadata_html_erb__1979807181509500994_65237500
    line 1 of [PROJECT_ROOT]/app/views/base/_form_metadata.html.erb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38852456)

**Comment by eliotjordan** [comment]
This is still an issue. Re-opening ticket.

**Comment by escowles** [comment]
Looks like this is fixed.
