### ISSUE TITLE
Add metadata fields necessary for ingest of MODS files to SimpleResource

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1674]
Individual tickets should have a table of the fields which exist in the MODS as well as examples of the kind of metadata that's in each of those fields. Bring special note to "weird" examples of metadata in those fields.

**Comment by tpendragon** [comment]
The next step here is to pick a collection to ingest first and see what tickets spawn from that.

**Comment by tpendragon** [comment]
When migrating related objects, migrate the link to the finding aid but NOT the link to the PUDL collection.

**Comment by tpendragon** [comment]
Some controlled vocabs have broken up parts and we may not be able to migrate those as strings at first. See #1579 for a reference.

**Comment by hackmastera** [comment]
we decided this is actually just part of the work for each of the ingest tickets; no need to have a separate issue.
