### ISSUE TITLE
Implement a Rake task for ingesting files as SimpleResources

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#1681]
Currently `IngestFolderJob` and `IngestFoldersJob` are invoked from within Rake tasks using just `ScannedResource` as the model:

- https://github.com/pulibrary/figgy/blob/master/app/jobs/ingest_folder_job.rb#L3
- https://github.com/pulibrary/figgy/blob/master/app/jobs/ingest_folders_job.rb#L3
- https://github.com/pulibrary/figgy/blob/master/lib/tasks/bulk.rake#L22
- https://github.com/pulibrary/figgy/blob/master/lib/tasks/bulk.rake#L123

**Comment by hackmastera** [comment]
We need this functionality on the ingest_mets job.
