### ISSUE TITLE
Viewing a PDF shouldn't update EZID metadata

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1683]
## Backtrace

    line 13 of [PROJECT_ROOT]/app/services/identifier_service.rb: update_metadata
    line 5 of [PROJECT_ROOT]/app/services/identifier_service.rb: mint_or_update
    line 20 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister/mint_identifier.rb: mint_identifier

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38703159)

**Comment by escowles** [comment]
Related to #1750
