### ISSUE TITLE
 Valkyrie::StorageAdapter::FileNotFound in downloads # show 

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1687]
This needs to be investigated further, as it's still happening. As a first step, try to get some more useful info into the error message.

Initially we thought:
```This came up in Honeybadger - deleting a FileSet failed because of an error in one of the hooks, but the files are gone now so downloads don't work. It's essentially just an orphan metadata record.```

## Backtrace

    line 27 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in trace
    line 43 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39116880)

**Comment by hackmastera** [comment]
@tpendragon @eliotjordan is this related https://app.honeybadger.io/projects/53391/faults/39147191#notice-summary? just trying to figure out replication so i can narrow in on a test.

**Comment by hackmastera** [comment]
I think we want to move `CleanupFiles` out of `before_delete` after `DeleteMembers` in `after_delete_commit`
https://github.com/pulibrary/figgy/blob/e9bcd691a7f27ba768716ceb1391bc6d99ec6ca7/app/change_set_persisters/change_set_persister.rb#L37

**Comment by hackmastera** [comment]
I wrote what i thought would be a failing test based on the 2 honeybadger errors. but it passes. I need more info about what caused this scenario.

https://github.com/pulibrary/figgy/compare/issue/1588-later-file-cleanup?expand=1

@tpendragon @eliotjordan

**Comment by hackmastera** [comment]
The error this issue was created from first occurred 8/16. The error I thought had caused it (linked above, an object not found in the message generator, a.k.a. the geo resources fileset deletion issue) first occurred 8/18. so that couldn't have been the cause.

there were a lot of errors like https://app.honeybadger.io/projects/53391/faults/39115947 around the same time as this one. Perhaps it was related? If so, i'm not sure how to replicate, or whether we should. i'll bring this up for discussion on our daily call.

**Comment by tpendragon** [comment]
@eliotjordan I'm getting this error now for this link https://figgy.princeton.edu/downloads/ba8c8a97-aa56-40d9-8168-1de94946a035/file/c444458e-8ac5-4876-978b-95392faf75fd

The record is https://figgy.princeton.edu/catalog/ba8c8a97-aa56-40d9-8168-1de94946a035

That file isn't a child of that record - maybe because it's a ScannedMap and all the children are other maps? Can you think of a reason this would happen?

**Comment by eliotjordan** [comment]
No idea why that request is being made.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/pull/1998 should have resolved this

**Comment by hackmastera** [comment]
This has happened twice since october 25th. The referrer listed is honeybadger itself. Perhaps this is only still alive because we've clicked on the link? Perhaps we should close / resolve and let it come up again via the solution to #2018?

**Comment by tpendragon** [comment]
Works for me
