### ISSUE TITLE
Ingest western americana / pudl0137 images that did not have mets

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1690]
Should these go through standard process via the studio? They've been moved to a directory called `pudl0137-no-mets`.

**Comment by cwulfman** [comment]
These were not in the original PUDL. Some of these have proper bib records; some do not.

- [ ] 2458038
- [ ] 2481459
- [ ] 2638905
- [ ] 2640217
- [ ] 2750784
- [ ] 2907434
- [ ] 2923198
- [ ] 2989088
- [ ] 2992424
- [ ] 2997681
- [ ] 3000749
- [ ] 3002674
- [ ] 3005487
- [ ] 3007002
- [ ] 3010131
- [ ] 3011680
- [ ] 3011685
- [ ] 3014700
- [ ] 3018918
- [ ] 3022589
- [ ] 3022894
- [ ] 3032301
- [ ] 3054619
- [ ] 3054783
- [ ] 3055066
- [ ] 4509066
- [ ] 4572584
- [ ] 5498010
- [ ] 5498167
- [ ] 5498216
- [ ] 6258921
- [ ] 8958848

**Comment by escowles** [comment]
These 32 items have been ingested into Figgy and added to the pudl0137 and Western Americana collections: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=pudl0137
