### ISSUE TITLE
Add/use graphql-powered order manager

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#1709]
Using GraphQL will enable us to support Sammelband use cases as well as any other cases where our structural metadata differs from what can be represented by IIIF accurately. It will also allow us to send one HTTP request for all changes rather than N+1.

Depends on #1492
Depends on #1505 
Depends on #1504

**Comment by escowles** [comment]
We are using the graphql order manager — will track adding order manager support to new object types in other tickets.
