### ISSUE TITLE
Add the ability to have RDF literals with language tags from a form for SimpleResource

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1713]
This is how we store them in ScannedResources, but for those we don't render the language tag in the form because they're read-only and just from the MARC.

Final wireframe:
![issue 1717 language tag for string in form 1](https://user-images.githubusercontent.com/845363/44603185-ebae8a80-a7af-11e8-80ab-d5bb85986496.png)

**Comment by escowles** [comment]
See wireframe in #1716

**Comment by tpendragon** [comment]
We're not really doing SimpleResources
