### ISSUE TITLE
Wireframe for adding a "subtitle"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1715]

**Comment by hackmastera** [comment]
Here's an idea. I tried to avoid the confusion of where the "required" label would go.

![20180822_164855](https://user-images.githubusercontent.com/845363/44490182-9e091500-a62b-11e8-83e3-c119c5918057.jpg)

**Comment by tpendragon** [comment]
This looks good and intuitive to me.

**Comment by tpendragon** [comment]
Alexis confirmed this looked good, but wants to make sure if there are language tags associated that it copies the language tag selection from title to subtitle.

**Comment by tpendragon** [comment]
Alexi: "the labels are a little unclear.  the first one says title and the second one say title, then main title and subtitle.  i get what you're going for her, but it took a while.  perhaps start the first screen with a label that indicates it's the main title as well."

**Comment by hackmastera** [comment]
Options 2 and 3:
![2018-08-24 10 17 02](https://user-images.githubusercontent.com/845363/44599963-e5b3ac00-a7a5-11e8-9557-d11204b7d615.jpg)

**Comment by tpendragon** [comment]
We're going with option #2.
