### ISSUE TITLE
String fields in SimpleResource should be able to have a language tag associated with them.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1716]
Depends on #1717

Final wireframe:
![issue 1717 language tag for string in form 1](https://user-images.githubusercontent.com/845363/44603185-ebae8a80-a7af-11e8-80ab-d5bb85986496.png)

**Comment by hackmastera** [comment]
Discussion of which standards to use for language and script, and how this should be modeled started over on #1717 but should be decided here.

**Comment by escowles** [comment]
:+1: to using RDF 5656 language+script tags.  This fits in with how we're handling language tags already and supports including script subtags as needed (e.g., to differentiate native script and transliterated versions).  Implementation can be handled in #1713
