### ISSUE TITLE
Wireframe for associating a language with a string field in a form

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1717]

**Comment by hackmastera** [comment]
Here's an idea https://docs.google.com/drawings/d/1KFRJNjQp6iobAU2uac6o-79vjxXnLBPiYhUSw9JJ8RY/edit

**Comment by tpendragon** [comment]
This looks good to me. Looking for a product owner to give an opinion.

**Comment by jrgriffiniii** [comment]
This is excellent, my only (pedantic?) question is whether or not there should be a distinction drawn between language and character set.

**Comment by hackmastera** [comment]
I have the same question. The ticket is for language. There was discussion on slack of a script use case (presumably https://github.com/pulibrary/figgy/issues/1623) but we definitely also have the use case for language (https://github.com/pulibrary/figgy/issues/1612).

Is script something we can store as part of the RDF literal? If not do we need to store it separately somehow?

If both language and script can be included in the literal, I would propose accounting for them in the dropdown with options like "Russian (Latin)" and "Russian (Cyrillic)"

**Comment by jrgriffiniii** [comment]
I agree with the approach, but I am uncertain as to how this is typically managed in RDF literals for less common cases.  For example, https://catalog.princeton.edu/catalog/3924025 contains Nahuatl in Latin script. My understanding of https://www.ietf.org/rfc/rfc3066.txt is that it permits dialect or variant information, such as en-scouse, and this is referenced in the W3C recommendation: https://www.w3.org/TR/rdf-concepts/#section-Graph-Literal

Perhaps that's enough to support this?

**Comment by escowles** [comment]
I believe we can also use [ISO 15924 script codes](https://en.wikipedia.org/wiki/ISO_15924) to differentiate different scripts.  e.g., you could use `ru` or `ru-Cyrl` for Russian in Cyrillic script, and `ru-Latn` for Russian transliterated to Latin script.

**Comment by tpendragon** [comment]
As a reminder, we don't actually have to store these as literals either. We could just have a ScriptString or what have you `Valkyrie::Resource` and figure out what to render the JSON-LD as when appropriate.

**Comment by hackmastera** [comment]
![issue 1717 language tag for string in form](https://user-images.githubusercontent.com/845363/44603004-527f7400-a7af-11e8-82bd-b3cb8b2ea313.png)
