### ISSUE TITLE
Ingest "Engineering in the Modern World" (pudl0090) object that didn't have METS

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1718]
Should this go through standard process via the studio? It's been moved to a directory called pudl0090-no-mets.

It appears to volumes 8-43 of the journal "Engineering News"

```
$ ls /mnt/hydra_sources/pudl/pudl0090/428041/
008  010  012  014  016  018  020  022  024  026  028  030  032  034  036  038  040  042  044
009  011  013  015  017  019  021  023  025  027  029  031  033  035  037  039  041  043
deploy@figgy-staging1:/opt/figgy/current$ ls /mnt/hydra_sources/pudl/pudl0090/428041/008/
000000002.tif  000000039.tif  000000076.tif ...
```

The volumes are associated with various bib records. Here is some analysis from @joycebcat copied from https://github.com/pulibrary/figgy/issues/1609#issuecomment-415032711:
The first volume "belongs to record 2051096. The other volumes probably do not belong to that record. It appears that this thing changed its name a lot. Volume 8 is from 1881, the record cover until 1882 and then it turns into record 2049799 until 1887 (up to probably issue 18) and then it turns into record 2045531 for volumes 19-49, so this should be the last record involved in this grouping."

**Comment by escowles** [comment]
Ingest as three MVWs:
* 2051096: 008
* 2049799: 009 - 018
* 2045531: 019 - 041

**Comment by kelea99** [comment]
reconfirm. we will ingest these as MVWs:
    2051096: 008
    2049799: 009 - 018
    2045531: 019 - 041

@roelmoon and I can take this one on.

**Comment by kelea99** [comment]
What do we do with volumes/issues 42, 43, 44, @escowles and @cwulfman ? looking at documentation above, it would still fall under 2045531, but wanted to confirm (also looking at cat records)

**Comment by escowles** [comment]
@kelea99 They should go in 2045531 with 19-41 — looks like Joyce actually said "19-49" so all the ones we have should go there.

**Comment by kelea99** [comment]
Ill just do this manually.
