### ISSUE TITLE
Ingest bayonne but keep them private with a note

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1719]
It wasn't ingested initially due to confusion. It's in the ingest staging directory on the server, in the file for `pudl0090` and it's called `bayonne.mets`

**Comment by hackmastera** [comment]
I guess we should keep this private via a "takedown" workflow status, and a workflow note. Not sure exactly what the note should say except that takedown was required.

**Comment by tpendragon** [comment]
Isn't it "complete" and "private" and the fact that it was taken down is just a fluke of history on us accidentally not making it private?

**Comment by hackmastera** [comment]
That makes sense! Is the note still a workflow note? Do we have any other kind of note?
