### ISSUE TITLE
[Figgy/production] Prawn::Errors::UnsupportedImageType: image file is an unrecognised format

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1721]
## Backtrace

    line 25 of [PROJECT_ROOT]/app/services/pdf_generator.rb: block in render
    line 18 of [PROJECT_ROOT]/app/services/pdf_generator.rb: each
    line 18 of [PROJECT_ROOT]/app/services/pdf_generator.rb: each_with_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39200516)

**Comment by tpendragon** [comment]
https://figgy.princeton.edu/concern/scanned_resources/159ba3f9-feab-49dd-bc71-ca08995006d9/pdf caused this error, but when I click that link now it seems to work fine.

**Comment by eliotjordan** [comment]
This is still an issue. https://figgy.princeton.edu/concern/scanned_resources/e56c4573-e8ca-4224-9cbe-2cb48766ff6d/pdf raises an exception after processing for a long time.

**Comment by jrgriffiniii** [comment]
This is still affecting the generation of certain PDFs.

**Comment by jrgriffiniii** [comment]
This seems to raise an `Prawn::Errors::UnsupportedImageType` intermittently; I managed to generate the PDF derivative for a file affected by this error 4 hour ago more than once.

**Comment by tpendragon** [comment]
it's been a long time and we have no history. Resolving and closing.
