### ISSUE TITLE
Structure manager thumbnails are missing for map sets

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1724]
Thumbnails in the structure manager are not displaying for map sets (ScannedResources with child ScannedResources).

![screenshot 2018-08-23 10 52 09](https://user-images.githubusercontent.com/784196/44536767-cc85ff00-a6c2-11e8-8675-c38571f05b43.png)

**Comment by eliotjordan** [comment]
I can't replicate this locally. Exploring the issue on figgy-staging with rails console didn't yield any information either. I'm kind of stuck here.

**Comment by tpendragon** [comment]
@eliotjordan Review?

**Comment by tpendragon** [comment]
Replacing the structure manager.
