### ISSUE TITLE
thumbnail display inconsistent

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1732]
The thumbnails in figgy aren’t all displaying right now.  See for example Ethiopic where only the new or newly-updated objects in the list view have a thumbnail showing.

**Comment by jrgriffiniii** [comment]
https://figgy.princeton.edu/catalog.json?utf8=%E2%9C%93&q=ethiopic renders differently structured URLs: `id-29%2Fac%2F9f%2F29ac9f6fa71343ca90c10cfb9fb772e6%2Fintermediate_file.jp2` vs. `id-3fed6db0-f5b0-4867-9f14-a6ae326f11e5`

I'm uncertain as to where this was introduced.

**Comment by jrgriffiniii** [comment]
Following the guidance from @eliotjordan, the thumbnails were set using the Order Manager.  Of those FileSets chosen, the first human-readable (either with text or an icon) was selected for each resource.

**Comment by jrgriffiniii** [comment]
Treasures of the Graphic Arts Collection members also seem to have been affected by this:
https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Treasures+of+the+Graphic+Arts+Collection

Regarding one of these (https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=Photography+album+documenting+the+Morant+Bay+Rebellion+in+Jamaica), it appears that this was last updated only on 08/21: https://figgy.princeton.edu/catalog/4f951479-915d-481a-b157-33250e73ba3d

**Comment by tpendragon** [comment]
Those IDs make it look like somehow the thumbnail IDs got set to the IDs of the files instead of the FileSets? Did we break this at some point?

**Comment by jrgriffiniii** [comment]
https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=thumbnail_id_ssim:*intermediate_file* retrieves those resources with corrupt thumbnails.  They appear to be exclusively `ScannedResources`.
