### ISSUE TITLE
browse-everything fails to preserve Google Drive folder structure (e. g. hierarchy)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#1733]
Users can access folders within Google Drive accounts, but they cannot access child folders (the tree-like hierarchy is not preserved).  Some of the child folders are listed at the "root" level of the hierarchy (e. g. parent and child folders are rendered as siblings), and file contents are inconsistently listed.

This was discovered when attempting to use Figgy to upload files from a shared Google Drive Folder.  This does not affect the file-system provider.  I am not certain at this point as to whether or not this may be resolved by updating Gem dependencies for browse-everything.

**Comment by tpendragon** [comment]
What does this mean? What was the expected behavior?

**Comment by jrgriffiniii** [comment]
23 days ago the Google auth. URIs were updated in the `googleauth` Gem, leading me to believe that updating the Gem is necessary regardless of its relationship to this issue:
https://github.com/google/google-auth-library-ruby/pull/147/files

**Comment by jrgriffiniii** [comment]
Updating this Gem did not resolve the issue.  Also, there still exists a hard limit on the number of file entries which may be retrieved from the API:
```
Error - #<Google::Apis::ClientError: invalidParameter: Invalid value '1000000'. Values must be within the range: [1, 1000]>
```

Attempting to surpass more than 1000 items triggers this error.  Hence, pagination of some kind is needed (presumably, with a new request being generated once the user scrolls downwards on the UI beyond a certain point).

**Comment by jrgriffiniii** [comment]
Folder recursion now properly functions, along with listing file contents:

<img width="606" alt="figgy_issues_1733_screenshot_0" src="https://user-images.githubusercontent.com/1443986/44607042-194e0080-a7bd-11e8-86fd-e05411aabce0.png">

**Comment by jrgriffiniii** [comment]
Folder recursion now properly functions, along with listing file contents

**Comment by jrgriffiniii** [comment]
Pagination is now supported with scrolling, please see https://youtu.be/3pk8750AjRI

**Comment by hackmastera** [comment]
🎉 looks great!

**Comment by tpendragon** [comment]
:+1: Looks awesome

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/browse-everything/pull/235 is needed in order to resolve this by pulling from the `samvera` repository.  Otherwise, I can open a pull request for https://github.com/pulibrary/figgy/compare/issues-1733-jrgriffiniii-gdrive-folders
