### ISSUE TITLE
[Figgy/production] Errno::ENOTDIR: Not a directory @ rb_sysopen - /opt/repository/geo_derivatives/9c/f7/00/9cf70087d05741f1b808e4a1280c6521/display_vector.zip

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1735]
## Backtrace

    line 27 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in trace
    line 43 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38793803)

**Comment by eliotjordan** [comment]
I think this an anomaly. I'll resolve.
