### ISSUE TITLE
For items which were bulk imported in the past, attach the MODS/METS file they came from to the resource

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1737]
We've ingested a ton of items that don't have any back-reference to these files.

Depends on #1736

**Comment by tpendragon** [comment]
@cwulfman I don't know if we should close this or not. Is this something you're doing? I'm leaving this issue up to you to do with what you will.

**Comment by cwulfman** [comment]
We're keeping all the METS/MODS in case we need them again.
