### ISSUE TITLE
Ingest WA items with files but no METS

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1740]
These are in the pudl directory, but have no METS files generated:

```
2469031
2523360
2987897
2501344
2525638
6566163
```

**Comment by roelmoon** [comment]
These were scholar requests photographed in the twilight of PUDL but pre-Figgy. They were never added to PUDL, should be ingested.

**Comment by tpendragon** [comment]
@roelmoon Can the studio handle ingesting these?

**Comment by escowles** [comment]
2523360 has been ingested:
* https://figgy.princeton.edu/catalog/d9e011ed-fcf4-4493-8d40-3174125cb1c4
* https://figgy.princeton.edu/catalog/6cf46e80-0572-4440-b544-40a36d5dd024

**Comment by escowles** [comment]
I noticed that all but one of the items in this ticket had been ingested, so I went ahead and ingested the final item:

2469031:
* https://figgy.princeton.edu/catalog/fb346dce-d135-4efc-922b-cbf91cd40e03

2987897:
* https://figgy.princeton.edu/catalog/f473767d-7d3f-440c-9f97-49bd93c6ee86
* https://figgy.princeton.edu/catalog/854e5a86-2798-4ac1-a6c9-3f820c6e5b4a

2501344:
* https://figgy.princeton.edu/catalog/3a59bf07-f5ec-433d-bef1-223f226e9717

2525638:
* https://figgy.princeton.edu/catalog/a2337059-6eab-4af4-8598-cfc6897bcb29
* https://figgy.princeton.edu/catalog/e880cc32-3613-49fe-9ccd-a6de0e2934d6

6566163:
* https://figgy.princeton.edu/catalog/99dd7346-8876-4fcd-84da-acd56e164591
