### ISSUE TITLE
Slow FileSet Destroy

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1745]
https://app.datadoghq.com/apm/resource/figgy/rack.request/d991fe761dc59ede?start=1535385962262&end=1535389562262&env=none&paused=false&traceID=1398851591428808907&spanID=7117668802239554862&graphType=span_list

Maybe this is because of the new geo behavior for figuring out what messages to fire?

**Comment by escowles** [comment]
Deleting individual FileSets is fast now — was this ticket about deleting lots of FileSets?

**Comment by tpendragon** [comment]
This may have been before we sped up deletes

**Comment by escowles** [comment]
👍 I'm going to close this ticket, since we've done work that probably fixed this problem.
