### ISSUE TITLE
Searching for the name of a collection should return the collection and all its members

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1782]
Were members indexing their collection name at some point? @roelmoon is reporting a possible regression here.

At one point we discussed adding the collection to a search result faceted to that collection; this seems related but I can't find that issue.

depends on #2150

**Comment by tpendragon** [comment]
It's still indexing the collection name, I guess it's just not a searchable field anymore? (If it weren't indexing the collection name, the collection facet wouldn't work.)

**Comment by hackmastera** [comment]
this can be closed once we have a successful full index on production
