### ISSUE TITLE
Wiki page describing our use of ChangeSets, especially in relation to SimpleResource

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1785]
Original comment from #1778:

> This seems to work very well. I think we should write up something brief for the wiki, an "Our use of change sets" page akin to our "use of decorators" page. It can just say something brief about the how/why we're using change sets where someone else might have used models. See inline comments, as well.

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/wiki/ChangeSets-in-Figgy

**Comment by tpendragon** [comment]
@hackmastera Can you take a look at the above?

**Comment by hackmastera** [comment]
👍
