### ISSUE TITLE
Reconsider holding locations for PDF cover sheet contact info

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1795]
We currently use Bibdata's digital locations (i.e., delivery locations where digital=true) for the location in Figgy.  But we haven't consistently added holding locations when we've entered or migrated content, so many objects don't have a location.

A related issue is that we ingest items with holding location specified, but there's no clear way to map those to delivery locations using the Bibdata data.  Should there be?  Should we do the mapping in Bibdata or in Figgy?

The location is currently only used to get contact info for the PDF cover sheet.  Do we want another mechanism to specify this information?

**Comment by tpendragon** [comment]
@escowles Was this a user request? Can you either icebox or close this as appropriate?

**Comment by escowles** [comment]
I think this was prompted by Engineering wanting to mark items as ReCAP, because they were scanning tables of contents of journals that were moving there.  And there are several kinds of locations in Bibdata, but only the delivery/digital locations have address info needed for the PDF cover page.

Ultimately, I think some change in the way we handle locations would be good, but I'll icebox this for now because the Alma implementation might change how all that works anyway.

**Comment by tpendragon** [comment]
It did! @escowles is a seer.
