### ISSUE TITLE
Improve density of structure editor

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#180]
It would be nice to see more pages at once when organizing hierarchy

**Comment by sdellis** [comment]
@escowles I'm not sure why @cwulfman closed this, but we are starting to look at a Structure Manager redesign in DLS and I'm documenting use cases. This issue you created looks like a use case, but it's missing the "why?". I have yet to form an opinion on this and am just exploring the Struct Map issues at the moment. Can you provide more reasoning behind why you think it would be nice to see more density (i.e., more pages at once) in the Structure Manager?

**Comment by escowles** [comment]
@sdellis I don't remember why Cliff closed this, either. I'm pretty sure that he didn't work on this. Though this ticket is somewhat similar to a feature we discussed for the Geniza collection, so maybe this was closed in error?

**Comment by escowles** [comment]
But to address the question of why, I think my reasoning was that the typical content managed in the structure editor is paged material with sometimes dozens of pages in each chapter/section/division. The current full-width display means that you can usually only see a small number of pages at a time, which makes it difficult to select all of the pages you want to move into a section.

**Comment by cwulfman** [comment]
Don't remember closing it; definitely an error
