### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1803]
## Backtrace

    line 116 of [PROJECT_ROOT]/app/models/mets_document/mods_document.rb: block in series
    line 114 of [PROJECT_ROOT]/app/models/mets_document/mods_document.rb: map
    line 114 of [PROJECT_ROOT]/app/models/mets_document/mods_document.rb: series

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39382377)

**Comment by hackmastera** [comment]
Lots of failed ingests from pudl0017 due to this error last night.
