### ISSUE TITLE
Update mediainfo char service to use float for duration

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1805]
`Valkyrie::Types` now supports float.

https://github.com/pulibrary/figgy/blob/ae53812ec937a48dbc499bf65f982fc17c6a5250/app/characterization_services/mediainfo_characterization_service.rb#L31

**Comment by hackmastera** [comment]
There may be other places that use this value that we should look at? Or maybe due to other places this value is used it wouldn't make sense to use float, after all.
