### ISSUE TITLE
Address RuboCop exclusions

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1809]
There are a number of RuboCop cops that have a large number of exclusions, e.g.:
* Metrics/BlockLength
* Metrics/ClassLength
* Metrics/MethodLength

And a few cops with fewer exclusions, but the cops are indicators of complexity that should be addressed, e.g.:
* Metrics/AbcSize
* Metrics/CyclomaticComplexity

We should either refactor the code to satisfy RuboCop, or decide that we don't care about the metric and disable it (or configure a higher threshold if appropriate)

**Comment by hackmastera** [comment]
I think there are times when length is bad and times when it's fine, like your method is a long array definition or similar. it would be good to look through them but I'd vote for keeping it as an exclusion even if the list is long.

I agree it would be good to look at the complexity ones.
