### ISSUE TITLE
Document browser compatibility

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1811]
Since the incorporation of the graphql order manager, Figgy is not longer compatible with IE 11 or below.

**Comment by sdellis** [comment]
We plan to expand browser compatibility for LUX. It's described here and simply requires updating the browserlist that babel uses when transpiling: https://github.com/pulibrary/lux/issues/122

**Comment by jrgriffiniii** [comment]
This is actually impacted by #3892

**Comment by tpendragon** [comment]
Users know to switch browsers and we haven't received any complaints. Closing this.
