### ISSUE TITLE
GraphQL sending many queries for order manager

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1812]
Takes up an extra second-ish of run time for 200 pages, makes it way slower than it was when powered by a manifest: https://app.datadoghq.com/apm/resource/figgy/rack.request/6d4651fbd3f9820d?start=1536337753027&end=1536341353027&paused=false&env=none&traceID=1006188503020981409&spanID=5417570406141938655&graphType=span_list

**Comment by jrgriffiniii** [comment]
After reviewing the Vue components and Lux, I understood there to be only two actions which actually transmit requests to the GraphQL endpoint:
- `loadImageCollectionGql`
- `saveStateGql`

(https://github.com/pulibrary/figgy/blob/master/app/javascript/store/vuex/actions.js)

These are not dispatched from within the Vuex store manager in Figgy, but instead are from within Lux:
- https://github.com/pulibrary/lux/blob/master/src/patterns/OrderManager.vue#L120
- https://github.com/pulibrary/lux/blob/master/src/patterns/_OrderManagerControls.vue#L160

**Comment by tpendragon** [comment]
This ticket was in reference to loading the order manager, not doing updates to items (which I actually expect to be faster)
