### ISSUE TITLE
Order manager puts images at the end if...

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/figgy#1814]
* you're moving to the next line
 * you move too quickly

https://vimeo.com/288954704

**Comment by tpendragon** [comment]
This looks like you might be dropping it between pages, which puts it at the end? Will have to look into it - @sdellis maybe you can take a look at some point?

**Comment by sdellis** [comment]
I can't reproduce this behavior, even on the same browser with the same collection. If I try to drop it between pages, the move doesn't happen. Are you the only one who has reported this, @jpstroop ? Might have to check it out in person...

**Comment by jpstroop** [comment]
Yup, just me.

**Comment by tpendragon** [comment]
Unable to reproduce and no further reports. Closing.
