### ISSUE TITLE
Dropdown menu does not display full, if not in fullScreen

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#1864]
Should we consider opening the drop down to the left? This way it will fully display no matter if you are in FullScreen on not.
currently opens to the right:
<img width="580" alt="screen shot 2018-09-14 at 10 31 23 am" src="https://user-images.githubusercontent.com/9905193/45556706-ec17cf80-b809-11e8-8a14-828c1584af66.png">

**Comment by tpendragon** [comment]
Closed pending user complaint.
