### ISSUE TITLE
Updating an EphemeraBox is slow (30+s)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1868]
https://app.datadoghq.com/apm/resource/figgy/rack.request/3abea14c833e1fb2?start=1536874185951&end=1536960585951&paused=false&env=none&traceID=3039257740064774324&spanID=8134445562637930788

**Comment by escowles** [comment]
I edited an EphemeraBox on Figgy staging, and saving was < 2 sec.
