### ISSUE TITLE
[Figgy/production] RSolr::Error::Http: RSolr::Error::Http - 503 Service Unavailable
Error: {
  "responseHeader":{
    "status":503,
    "QTime":1726},
  "adds":[
    "d75c7161-728a-4369-a51a-e8faf3c4d599",1611868290173370368],
  "error":{
    "metadata":[
      "cause","LeaderChanged",
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException",

URI: http://lib-solr.princeton.edu:8983/solr/figgy/update?wt=json&softCommit=true&versions=true
...

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1872]
## Backtrace

    line 94 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save_all
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39543223)

**Comment by christinach** [comment]
probably random
