### ISSUE TITLE
Test Amazon Glacier

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1875]
- [x] Store 1 bag in Glacier
- [x] Retrieve it to S3
- [x] Perform fixity check in EC2 instance

Consult preservation notes to make sure this is the plan.

**Comment by eliotjordan** [comment]
All notes and code are stored in https://github.com/pulibrary/aws-playground

- 121.1 GB of test bags uploaded to Glacier
- Bags were downloaded to an EC2 instance and through a simple checksum comparison.
- Took ~ 1.5 hours to complete.

![Screenshot 2018-10-02 13.53.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552523c5f5521c770085d65b/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417773e7956e37a23cbb67bf1122343434d0eee1e020a17b8eb8339a3e73b218a5e5ae9d33b0b77c36e11acbcd71abd06b224dd5d99a4fedb1294b7607caddecd5d340c041f83fe5836a89c4bc15cf648e74b57b65e.png)

Ticket to report on costs was created: https://github.com/pulibrary/figgy/issues/1946
