### ISSUE TITLE
Research caption support

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1877]
What caption formats are supported?

**Comment by escowles** [comment]
@tpendragon says if we have WebVTT captions and add them to the HLS playlist, then they'll just work.  We can convert SRT to WebVTT with ffmpeg: https://ffmpeg.org/pipermail/ffmpeg-user/2016-October/034006.html

**Comment by tpendragon** [comment]
@kelynch There's a working group doing this right? Maybe close this?

**Comment by tpendragon** [comment]
Closing because there's a working group. Also a IIIF working group. Also we use HLS there's only one way.
