### ISSUE TITLE
Update the checksum in FgdcUpdateService

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1887]
FgdcUpdateService modifies a file, but does not update it's checksum. This means it will fail fixity checks.

**Comment by hackmastera** [comment]
We've discussed the idea that files should be immutable; perhaps we should delete the file_metadata resource and replace it instead of updating the checksum?

**Comment by hackmastera** [comment]
re: my comment above, we discussed on checkin. reasoning for considering files immutable was because of, e.g. this checksum issue, and invalidating a cached pdf. the pdf isn't an issue here. in general people seemed okay with just updating a checksum in this case.
