### ISSUE TITLE
An archival a/v object with no image should still load

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1899]
## Backtrace

    line 89 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: create_image_file
    line 101 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: block in add_images
    line 100 of [PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39602499)

**Comment by christinach** [comment]
ingest_archival_media_bag_job.rb  89 create_image_file(...)
[PROJECT_ROOT]/app/jobs/ingest_archival_media_bag_job.rb:89:in `create_image_file'
```ruby
87           image = bag.image_file(barcode: barcode)
88           IngestableFile.new(
89             file_path: image.path,
90             mime_type: image.mime_type,
91             original_filename: image.original_filename,
```
Maybe it didn't find a barcode in the specific bag?

**Comment by hackmastera** [comment]
I think the bag parser is tripping over an unexpected filename convention involving one side broken up into two parts:

```
32101047381569_1_p1_a.mp3
32101047381569_1_p1_a.mp3.sha256
32101047381569_1_p1_i.wav
32101047381569_1_p1_i.wav.sha256
32101047381569_1_p1_pm.wav
32101047381569_1_p1_pm.wav.sha256
32101047381569_1_p2_a.mp3
32101047381569_1_p2_a.mp3.sha256
32101047381569_1_p2_i.wav
32101047381569_1_p2_i.wav.sha256
32101047381569_1_p2_pm.wav
32101047381569_1_p2_pm.wav.sha256
32101047381569_2_a.mp3
32101047381569_2_a.mp3.sha256
32101047381569_2_i.wav
32101047381569_2_i.wav.sha256
32101047381569_2_pm.wav
32101047381569_2_pm.wav.sha256
32101047381569_AssetFront.jpg
32101047381569.xml
```

i'll try to put these in their own bag and test it on dev. If it reproduces I'll ask the PO about this convention and whether it needs to be accommodating.

**Comment by hackmastera** [comment]
This error is caused by an item which did not have an image:
```
32101047381585_1_a.mp3
32101047381585_1_a.mp3.sha256
32101047381585_1_i.wav
32101047381585_1_i.wav.sha256
32101047381585_1_pm.wav
32101047381585_1_pm.wav.sha256
32101047381585.xml
```
