### ISSUE TITLE
[Figgy/production] RSolr::Error::Http: RSolr::Error::Http - 503 Service UnavailableError:

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1901]
## Backtrace

    line 94 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save_all
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39602708)

**Comment by christinach** [comment]
see also: https://app.honeybadger.io/projects/53391/faults/39561049#notice-summary

**Comment by christinach** [comment]
https://app.honeybadger.io/projects/53391/faults/39606169#notice-summary

**Comment by christinach** [comment]
NoMethodError in ephemera_folders # update
https://app.honeybadger.io/projects/53391/faults/39561049#notice-comments

`instrumented_adapter.rb  94 block in save_all(...)`
