### ISSUE TITLE
Ingest Princeton Performance Archive (Orchestra collection)

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1902]
Same dataset as audio reserves?

Ingest these into its own collection to look at, since there's another ppa collection.

Existing Site: https://library.princeton.edu/music/performance-ensemble-music-archive
https://library.princeton.edu/scripts/ereserves.php?id=92

**Comment by hackmastera** [comment]
Look at current functionality, especially with respect to track-level access. Are performances split into tracks as individual files? We may want to be able to open individual works within a performance if future copyright research takes places.

**Comment by hackmastera** [comment]
I believe the course we want to ingest is called `puo`.

Here are the courses without numbers in their titles, and the count of recordings in each:

```
select C.CourseNo, Count(R.idRecording) from Recordings R
  left join Selections S on S.idRecording=R.idRecording 
  left join jSelections jS on S.idSelection=jS.idSelection 
  left join Courses C on jS.idCourse=C.idCourse 
  where CourseNo not like '%[0-9]%'
  group by CourseNo;
```

```
katz,4
tigertones,24
puje,414
organ,69
nassoons,15
cone,1
chapel,70
wuorinen,81
puo,343
emp,1
sessions,21
pucomp,6
sinfonia,164
faculty,403
students,13
lansky,28
trego,1
mendel,4
puperf,10
babbitt,40
boretz,16
westergaard,6
compgen,5
opera,9
perle,7
wildcats,2
glee,311
student,30
compgens,1
chamber,29
tigeressions,2
randall,10
tigerlilies,7
plork,29
footnotes,7
compgrad,1165
tiger,36
musica,15
reunions,60
puwe,29
dembski,4
Mackey,28
```

**Comment by hackmastera** [comment]
11 puo recordings have already been ingested into figgy manually: https://figgy.princeton.edu/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Recording&f%5Bpart_of_ssim%5D%5B%5D=PUO&q=
