### ISSUE TITLE
[Figgy/production] Errno::ENOSPC: No space left on device - sendfile

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1905]
## Backtrace

    line 92 of [PROJECT_ROOT]/app/derivative-services/jp2_derivative_service.rb: create_tiff_derivative
    line 86 of [PROJECT_ROOT]/app/derivative-services/jp2_derivative_service.rb: run_tiff_derivatives
    line 79 of [PROJECT_ROOT]/app/derivative-services/jp2_derivative_service.rb: run_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39613747)

**Comment by hackmastera** [comment]
What device is this referencing?

**Comment by tpendragon** [comment]
This may be the tmp directory of lib-proc6. Datadog's not tracking the disk space for that host - investigate the space on lib-proc6/5/4 and figure out why datadog's not reporting.
