### ISSUE TITLE
Allow search by photographer

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#1955]
Requested during grounds and buildings ingest

**Comment by tpendragon** [comment]
@kelea99 Still needed? If not can you close it?

**Comment by kelea99** [comment]
@cwulfman and @escowles do you know about this? this was before my time. can you give me more specifics what this is asking for and why?

**Comment by hackartisan** [comment]
@kelea99 maybe check in with ADAPT on this one. It was requested for the grounds and buildings collection. It would be good to know exactly what kind of search they're wanting to do that's not working.

**Comment by kelea99** [comment]
@cwulfman and @escowles and I went through this one. Photographer is now mapped to figgy for this collection. closing the ticket.
