### ISSUE TITLE
Ingest origin field on pudl0038

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1956]
required by #1588 
requires #2473

**Comment by hackmastera** [comment]
Origin appears to be a date field. examples:
http://pudl.princeton.edu/results.php?v1=Menzies%2C+Elizabeth&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&sort=score&rpp=10&view=pudlUI
http://arks.princeton.edu/ark:/88435/nz806032w

**Comment by hackmastera** [comment]
[originInfo](https://www.loc.gov/standards/mods/userguide/origininfo.html) can be used for all kinds of stuff, but in this collection it's only used for the date created.

A simple use case:
```
<originInfo>
   <dateCreated encoding="w3cdtf" keyDate="yes" qualifier="approximate">1891</dateCreated>
</originInfo>
```

A date range use case:
```
./mp028/0655.mets:   <originInfo>
./mp028/0655.mets-      <dateCreated encoding="w3cdtf" keyDate="yes" point="start" qualifier="approximate">1860</dateCreated>                                                                                                  
./mp028/0655.mets-      <dateCreated encoding="w3cdtf" point="end" qualifier="approximate">1880</dateCreated>
./mp028/0655.mets:   </originInfo>
```

Note the "approximate" qualifier in both of the above cases.

There's also unknown, which I think we could ignore; it's not even dateCreated just dateOther.
```
./mp043/1330.mets:   <originInfo>
./mp043/1330.mets-      <dateOther>Unknown</dateOther>
./mp043/1330.mets:   </originInfo>
```

**Comment by hackmastera** [comment]
Need feedback on how to import approximate dates. and approximate date ranges.

**Comment by hackmastera** [comment]
Alexis confirmed that we need to retain this qualifier. 

Anna [1:59 PM]
We don't currently have a way to encode that in figgy so I'll need to implement something. We are thinking free text when it's just a single date like "approximately 2019" and an "approximate" toggle for date ranges. 

Alexis A. [2:00 PM]
that seems fine to me.  we often use approximate or circa for dates when we know it's say, from the 1880s, but don't know the exact year

**Comment by kelea99** [comment]
https://figgy.princeton.edu/catalog/a3d75c94-2eee-47b7-b193-3b09eb9b13e7
ingest of approx. dates/date ranges still needed.

**Comment by tpendragon** [comment]
All of these grounds and buildings should be converted to ScannedResources with EAD Component IDs, yeah?

**Comment by kelea99** [comment]
Yea, since its finding aid material, but I'm looking at the records in figgy and cannot find a component id in the metadata. I find the location (Mudd, Box MP45, Item 1474). how can this information be mapped to the component ids in the FA/vice versa? Assuming this will be similar to the WA collection Cliff Just migrated? Please forgive my ignorance on this.

**Comment by tpendragon** [comment]
We'll have to find some sort of piece of correlating metadata between the MODS and EAD. I haven't looked super close.

**Comment by kelea99** [comment]
I can do that.

**Comment by escowles** [comment]
Closing this ticket since the dates will be handled as part of #2021.
