### ISSUE TITLE
Delete Duplicates from "Selections from the Near East Collections"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1967]
Reported by @roelmoon 
> Seeing a bit of Figgy weirdness with a group of Hebrew items within the near east collections. An example is 10355530. There are now two instances, one that was deposited by Mary and is completed, and another that somehow was redeposited but note that no depositor is listed. This is the case with about 140 of the items from this sub-collection we worked on.

**Comment by tpendragon** [comment]
@roelmoon Do you know if this is still a problem?

**Comment by kelea99** [comment]
It is.

**Comment by tpendragon** [comment]
Done
