### ISSUE TITLE
Ingest Granville Wilcox

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1974]
See https://github.com/pulibrary/pulfa/issues/123

**Comment by kelea99** [comment]
@escowles the link has a 404 error. do you have any more information on this collection? I looked in figgy and found these ingests:  https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Granville+Wilcox+Correspondence+C1261

**Comment by escowles** [comment]
That ticket's in a private repository (and closed), and since the content is in figgy and linked to the finding aid, I'm closing this.
