### ISSUE TITLE
Enable ark report view to load when a resource is missing an identifier

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1977]
## Backtrace

    line 16 of [PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb: block in _app_views_archival_media_collections_ark_report_html_erb___4379890785205312006_58641980
    line 14 of [PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb: each
    line 14 of [PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb: _app_views_archival_media_collections_ark_report_html_erb___4379890785205312006_58641980

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38125355)

```
ActionView::Template::Error: undefined method `first' for nil:NilClass
 ark_report.html.erb  16 block in _app_views_archival_media_collections_ark_report_html_erb(...)
[PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb:16:in `block in _app_views_archival_media_collections_ark_report_html_erb'
14     <% @resources.each do |r| %>
15       <tr>
16         <td><%= r.identifier.first %></td>
17         <td><%= r.source_metadata_identifier.first %></td>
18       </tr>
```

**Comment by hackmastera** [comment]
Note this honeybadger error is essentially the same but for the source_metadata_identifier https://app.honeybadger.io/projects/53391/faults/44737188#notice-summary
