### ISSUE TITLE
adjust "location" field for collections migrated from pudl (grounds & buildings)

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1978]
In the Location field we currently have “Mudd, Box MP82, Item 3349” Instead of “Mudd” the call no. would be more helpful (e.g. AC111, Box MP82, Item 3349). There is already a field for “Rendered Holding Location” listed as “Mudd Manuscript Library”

**Comment by hackmastera** [comment]
you can get the collection number by resolving the `ArkWithTitle.identifier` to its finding aid path

**Comment by hackmastera** [comment]
When I take just the `shelfLocator` without the `subLocation` from the mods I get the desired result. In another case this gives us "Cabinet 11/06" instead of "Curator's office, Cabinet 11/06". Should we keep the `subLocation` or will everyone know what `Cabinet 11/06` is?

**Comment by alexisantracoli** [comment]
For Mudd, this shouldn't be an issue and Cabinet 11/06 would suffice.  Although, there might be some weird case where this isn't true, but I think it should be fine.

**Comment by hackmastera** [comment]
@alexisantracoli I can also leave the `sublocation` in but still add the collection code.

**Comment by hackmastera** [comment]
Some of these have the collection number in the shelfLocator already. e.g. in one case I get `MC085, Mudd, MC085. Box 135`.

I think I will leave the shelfLocator as-is and add the collection number in the new `archival_collection_code` cfield.
