### ISSUE TITLE
MVWs show a link instead of an image in the members thumbnail column

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1980]
In the members list for MVWs, the thumbnail column should include an image, but it currently displays the link instead:

![screen shot 2018-10-16 at 10 40 38 am](https://user-images.githubusercontent.com/856924/47024984-bcbdf080-d130-11e8-9d61-4cf070ebc9fe.png)

See https://figgy.princeton.edu/catalog/8baa95b7-0c17-4c41-9466-401cc7e81b63

**Comment by eliotjordan** [comment]
They show links because the thumbnails have not been set for the child works. If you look at the example above, I set a thumbnail in the order manager for the first child and it displays as it should.

**Comment by escowles** [comment]
@eliotjordan I thought we were defaulting to the first page if there wasn't a thumbnail set.  Are we not doing that?

**Comment by eliotjordan** [comment]
I'm guessing we're not, or that logic is no longer working. I've noticed this for a long time with scanned maps. I've also seen this happen recently with the "East Asian Library Tables of Contents" collection. Perhaps there were some problems when these items were ingested?
