### ISSUE TITLE
Auth Token should not query db when auth_token is null

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1983]
When I run Figgy in development mode, I see many lines out output like this:

```
  CACHE AuthToken Load (0.2ms)  SELECT  "auth_tokens".* FROM "auth_tokens" WHERE "auth_tokens"."token" IS NULL LIMIT $1  [["LIMIT", 1]]
```

Figgy should only try to load auth tokens from the db when an auth_token parameter is provided by the client.

**Comment by tpendragon** [comment]
:+1: Priority's pretty low here though. Datadog says it takes 32 microseconds to check.
