### ISSUE TITLE
Determine modeling for audio reserve objects

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1987]
So far we're assuming that a course is a collection and a selection is a type of work/resource. One challenge is that selections have sort fields, which are collection-specific. For example, if a selection belongs to two courses it could be sorted into week one in course A but week 4 in course B. Need to figure out how to accommodate this.

child of #1986

**Comment by christinach** [comment]
```
SELECT TOP 100 
j.idCourse as collections,
a.idSelection as Works,
s.idRecording,
s.AudioFiles,
r.CallNo,
a.FilePath,
a.FileName,
a.entryid,
s.idRecording,
s.idComposer,
s.Title,
t.ram,
t.linked,
t.wav,
t.note,
t.rm,
jt.idStaff,
sta.name
FROM (AudioFiles a
left join dbo.Selections s on s.idSelection = a.idSelection
left join dbo.trackSelections t on a.idSelection = t.idSelection
left join dbo.jSelections j on t.idSelection = j.idselection)
left join dbo.jTeachers jt on j.idCourse = jt.idCourse
left join dbo.Staff sta on jt.idStaff = sta.idStaff
left join dbo.Recordings r on s.idRecording = r.idRecording
order by a.idSelection, j.idCourse, a.FileName, s.AudioFiles;
```
some more joins to display the staff member.
@tpendragon what is an ```entryid``` in AudioFiles? Why for some AudioFiles is null ? How is it generated?

**Comment by hackmastera** [comment]
What about Selections are collections of AudioFiles, and have an ordered member list

**Comment by tpendragon** [comment]
@christinach `entryId` is the ID of the Kaltura object. It's generated when they upload the file to Kaltura - they don't upload everything.

**Comment by christinach** [comment]
ok, Thanks.

**Comment by tpendragon** [comment]
> What about Selections are collections of AudioFiles, and have an ordered member list

Isn't this the same thing as a Work?

**Comment by christinach** [comment]
Is 'Work' a specific workflow in Figgy? Where in the code base you look for 'Work'?

**Comment by christinach** [comment]
I can see 'Geo - work'

**Comment by tpendragon** [comment]
> Is 'Work' a specific workflow in Figgy? Where in the code base you look for 'Work'?

Sorry, it's older terminology in the Samvera space. Work is shorthand for "ScannedResource/GeoWork/RasterResource/XResource" - those types of objects.

**Comment by christinach** [comment]
excellent! Thanks

**Comment by christinach** [comment]
```
collections	Works	idRecording	AudioFiles	CallNo	FilePath	FileName	entryid	idRecording	idComposer	Title	ram	linked	wav	note	rm	idStaff	name
NULL	15	NULL	NULL	NULL	m-z	stravApollon.ram	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL
```
There is one .ram file with a file_path: 'm-z', id_selection: 15  and everything else 'null'. 
What is this about?

**Comment by tpendragon** [comment]
I'm guessing it's what happens when they don't hit the "create a playlist" button.

**Comment by christinach** [comment]
I looked for .ram
```
1> SELECT * FROM dbo.AudioFiles where FileNote ='complete' and FilePath is not null and FileName LIKE '%.ram%';
2> GO
idFile	idSelection	FilePath	FileName	FileNote	Time	entryid
2568	15	m-z	stravApollon.ram	Complete	NULL	NULL
3145	2137	m-z	RosenSuite.ram	COMPLETE	NULL	NULL
4198	1521	m-z	Ockeghem_MissaPro.ram	COMPLETE	NULL	NULL
4711	2754	a-l	l'arlesienne1.ram	COMPLETE	NULL	NULL
```

**Comment by christinach** [comment]
Will the 'Create playlist' button create the .ram file ?

**Comment by tpendragon** [comment]
@christinach That's my understanding

**Comment by tpendragon** [comment]
This makes bulk ingest harder, but my current proposal:

1. Recordings have a Call#, and we can fetch the bib record metadata using it.
2. Recordings have Selections
3. Selections have AudioFiles (FileSets)
4. Selections are members of Courses (Collections)
5. Courses generate a playlist either through Kaltura or IIIF.

**Comment by hackmastera** [comment]
> > What about Selections are collections of AudioFiles, and have an ordered member list
> 
> Isn't this the same thing as a Work?

In figgy a file cannot be contained by more than one resource. So the difference is in adding functionality to a collection class vs. allowing a file to have multiple parents.

**Comment by tpendragon** [comment]
> In figgy a file cannot be contained by more than one resource. So the difference is in adding functionality to a collection class vs. allowing a file to have multiple parents.

If an object in Figgy has ordered children, isn't it a parent? The query will return it as such, at least.

**Comment by hackmastera** [comment]
I think we should keep selections separate, more like:
Recording < Resource, with FileSets (tracks)
Course < Collection
Selection aka Playlist < Collection, with ordered FileSet (track) members

Even if functionally a collection with ordered members is the same as a resource with ordered members, I think it maps semantically to a collection better than to a resource.

**Comment by tpendragon** [comment]
Real-Flat Proposal:

No Courses (The use case for courses was to generate an HTML page of reserves - now they enter player links into Ares which shows up right in Blackboard)
Recording < Resource, with FileSets (tracks)
Convert Selections to Logical Orders (the database enforces that a selection can only be in one recording right now)
Provide player links for each Selection + Track + Recording.

**Comment by hackmastera** [comment]
Real-Flat Proposal is compelling. Can you say more about a Logical Order? Is that a iiif range or something? I'm not sure I fully understand the implications. it sounds from the edit as though a given track could only be in one of these?

**Comment by escowles** [comment]
Two questions:
* Does "No Courses" mean that Course isn't a model, but is still a metadata field?  That seems reasonable to me.
* We might not need to support tracks being in multiple selections right away, but it sounds like this is something that comes up occasionally.  How do we support that eventually?

**Comment by tpendragon** [comment]
1. It means no course Metadata at all. It exists in the DB it appears to build a page which isn't used anymore. Instead they just put viewer links in Ares. 

2. It sounded like Dan was just putting track links directly into Ares instead of the exact correct Playlist when that comes up. We just need to enable that. If we want to enable Playlist generation one day we can either build a UI or even an external manifest builder.

**Comment by tpendragon** [comment]
@hackmastera Yes, it's a IIIF range. A given track could only be in one of them (well...with the current UI at least.)

**Comment by christinach** [comment]
@tpendragon What is a IIIF range. Is this specific in the figgy code base?

**Comment by sdellis** [comment]
@christinach https://iiif.io/api/presentation/3.0/#54-range

**Comment by christinach** [comment]
Thanks @sdellis
