### ISSUE TITLE
Get access to the audio reserve database

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1988]
Get a sense of the tables, columns, relations between them.

child of #1986

**Comment by tpendragon** [comment]
We have access to the Access files, but need the ODBC connection info for the SQL Server database.

**Comment by christinach** [comment]
- brew install FreeTDS
- gem install tiny_tds
Use the username/password for the Sql server. 
This is a connection from the microsoft webpage:
```
require 'tiny_tds'
@client = TinyTds::Client.new username: 'mus_ro', password: 'c@n_$elect',
    host: 'ereserves.princeton.edu', port: 1433
puts 'Connecting to SQL Server'

if @client.active? == true then puts 'Done' end

@client.close
```
