### ISSUE TITLE
Investigate authorization for media reserves

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1989]
child of #1986

**Comment by jrgriffiniii** [comment]
https://libweb10.princeton.edu/MusicReserves/MusicReserves.aspx?semester=1 is accessible by unauthenticated users:

<img width="1041" alt="figgy_issues_1989_screenshot_0" src="https://user-images.githubusercontent.com/1443986/47364432-4a588d80-d6a7-11e8-9bbc-9a2e211db5da.png">

However, attempting to access these links produces the following errors:

<img width="861" alt="figgy_issues_1989_screenshot_1" src="https://user-images.githubusercontent.com/1443986/47364531-8ee42900-d6a7-11e8-965d-6664ad5eec82.png">

**Comment by jrgriffiniii** [comment]
The Kaltura media player is also available to unauthenticated users (although broken without the `entryid` parameter):

<img width="638" alt="figgy_issues_1989_screenshot_2" src="https://user-images.githubusercontent.com/1443986/47365063-bedffc00-d6a8-11e8-9ba3-d52f59c8487f.png">

**Comment by jrgriffiniii** [comment]
These resources should be properly accessed using any of the links on http://library.princeton.edu/music/performance-ensemble-music-archive

**Comment by jrgriffiniii** [comment]
My understanding of the existing access workflow is:
• Desired “Class” (including non-courses such as the archival collections for concerts offered by groups like Princeton University Jazz Ensemble) is selected in a POST parameter for the `<form>`
• User authenticates to access `/MusicReserves`
• User then has access to a set of links to MusicReserve links to pages with the Kaltura media player embedded

The MusicReserves interface and Kaltura media player should not be publicly accessible

**Comment by jrgriffiniii** [comment]
After discussing this with @kevinreiss, it was confirmed that the Kaltura player offered by the current Music Reserves interface does not integrate with Kaltura for any form of authorization of access.
