### ISSUE TITLE
Investigate how much data we could rely on Ares for

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1992]
Can we reduce duplication of effort in some way by integrating more tightly with areas?

child of #1986

**Comment by jrgriffiniii** [comment]
My desire for this may have been misguided...it doesn't appear as if much can be gained from interacting with the API without using ASP/C# and interfacing with DLL service endpoint:
```
<div class="header">Search by Department</div>
			<div class="row">
				<form name="CourseSearch" action="ares.dll" method="post">
			      <input type="hidden" name="Action" value="11"/>
	                  <input type="hidden" name="Form" value="63"/>							
 	                  <input type="hidden" name="SessionID" value="<#PARAM name="SessionID">"> 
			      <#OPTION name="Custom" GroupName="Department" SelectedValue="<#USER field=Department>" Size="1">
				<input type="submit" name="DepartmentSearch" value="Go"/></form>
			</div>
```
(https://github.com/pulibrary/ares/blob/master/Ares/USearchCourse.html#L24)

**Comment by jrgriffiniii** [comment]
Additionally, access privileges for documentation for the web APIs seem to be limited to persons of contact at client institutions (i. e. https://prometheus.atlas-sys.com/display/ARE/Web+Interface)

**Comment by jrgriffiniii** [comment]
This should be fully resolved once we have confirmed with kevinreiss that there are no additional codebases or documentation for Ares which should be referenced.

**Comment by escowles** [comment]
We're not going to pursue further integration with ARES right now.
