### ISSUE TITLE
Can't download PDFs for items in the Soviet Era Books for Children and Youth collection

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#1994]
For example: https://figgy.princeton.edu/catalog/7271c39a-2686-4b20-9273-d794ffd9848a

Reported by Thomas Keenan.

**Comment by eliotjordan** [comment]
Maybe need to just clean out the old pdf file sets for these records.

**Comment by jrgriffiniii** [comment]
Datadog logs show that this is generating an error logged in Honeybadger: https://app.honeybadger.io/projects/53391/faults/39116880/249b1fd0-d6df-11e8-93d8-ba5c35982ec1

**Comment by jrgriffiniii** [comment]
Blocked by https://github.com/pulibrary/figgy/issues/1687

**Comment by jrgriffiniii** [comment]
The PDF for this particular ScannedResource appears to have been deleted, while the FileMetadata remains persisted within the database:

```
> res = Valkyrie.config.metadata_adapter.query_service.find_by(id: Valkyrie::ID.new('7271c39a-2686-4b20-9273-d794ffd9848a'))
> cs = ScannedResourceChangeSet.new(res).prepopulate!
> cs.resource.pdf_file
=> #<FileMetadata id=#<Valkyrie::ID:0x00000000089a90e0 @id="707a47d9-fa3a-4b66-8be6-497271271e3c"> [...]
> cs.resource.pdf_file.file_identifiers
=> [#<Valkyrie::ID:0x0000000008a46020 @id="disk:///opt/repository/derivatives/70/7a/47/707a47d9fa3a4b668be6497271271e3c/derivative_pdf.pdf">]
```

When checking for this file however, it does not exist:
```
$ ls /opt/repository/derivatives/70/7a/47/707a47d9fa3a4b668be6497271271e3c/derivative_pdf.pdf
ls: cannot access '/opt/repository/derivatives/70/7a/47/707a47d9fa3a4b668be6497271271e3c/derivative_pdf.pdf': No such file or directory
```

**Comment by jrgriffiniii** [comment]
Manually regenerating this required that the FileMetadata be replaced within the production environment:
```
> pdf_file = PDFGenerator.new(resource: res, storage_adapter: Valkyrie::StorageAdapter.find(:derivatives)).render
> change_set_persister.buffer_into_index do |buffered_changeset_persister|
irb(main):011:1*   cs.validate(file_metadata: [pdf_file])
irb(main):012:1>   buffered_changeset_persister.save(change_set: cs)
irb(main):013:1> end
```

https://figgy.princeton.edu/downloads/7271c39a-2686-4b20-9273-d794ffd9848a/file/966321c3-7cbe-4c99-9d25-65c63c957516

**Comment by eliotjordan** [comment]
Thanks @jrgriffiniii. I did a spot check of a few items in the collection, and they all had working PDF downloads. 💯

**Comment by jrgriffiniii** [comment]
This has been reported as unresolved for certain ScannedResources.
