### ISSUE TITLE
Investigate Kaltura Integration

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1995]

**Comment by tpendragon** [comment]
https://knowledge.kaltura.com/uploading-media-using-kaltura-api-console Kaltura API

**Comment by jrgriffiniii** [comment]
Discussing this briefly with @kevinreiss, it was made clear that Kaltura IDs for media assets will need to be preserved in the models in order to ensure proper synchronization with ARES.  These will be used to map the audio links in ARES to their new location in Figgy.
