### ISSUE TITLE
Per-Resource Auth Tokens

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2010]
Every resource should have an access token that provides access to its manifest and the file downloads of its derivative filesets.  The access token should not be in the record's JSON-LD etc.

Child of #1986

**Comment by escowles** [comment]
Generate when the record is complete

**Comment by escowles** [comment]
The implementation may be the same as the current access token implementation — but instead of granting a role, would only allow the access needed for a specific resource.

**Comment by escowles** [comment]
In the case of Playlists, the auth token should be propagated through the manifest to the member tracks, so the auth token allows playing the tracks.

**Comment by jrgriffiniii** [comment]
Blocked by #2081
