### ISSUE TITLE
Publish a manifest for a FileSet

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2013]
Allows linking to a single track or a logical grouping of tracks from ARES, not just the whole recording.

Child of #1986

**Comment by hackmastera** [comment]
The way to achieve this is to create manifests for portions of a resource.

For files, we can have a file set manifest route, and generate a manifest for that file set, e.g. `http://localhost:3000/concern/file_sets/bcfb47d3-c952-4244-8f87-6e4abbb7a4a7/manifest`? or `localhost:3000/catalog/parent/315f1149-213e-46bd-853e-8794a97231d3/bcfb47d3-c952-4244-8f87-6e4abbb7a4a7/manifest` might be preferred.

For ranges we'll either need a new route or we'll use a query string param, e.g.
`http://localhost:3000/concern/scanned_resources/d16b2265-2f28-4b79-b323-157546df0f9d/manifest?range=123456`

Note we need to check on persistence of range ids. Currently we believe they are not persistent, i.e. all the range IDs for a given resource might change if the structure is edited at all.

**Comment by tpendragon** [comment]
I prefer `http://localhost:3000/concern/file_sets/bcfb47d3-c952-4244-8f87-6e4abbb7a4a7/manifest` so that behavior can be different within the controller. The catalog paths all have one controller.

**Comment by hackmastera** [comment]
Does the manifest need resource-level metadata?

**Comment by hackmastera** [comment]
No longer needed due to playlist model
