### ISSUE TITLE
New Report: Figgy manifests and Component IDs for recently-ingested items

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2016]
Allow users to select a date, and provide a CSV report mapping PULFA component IDs to Figgy manifest URLs for items ingested since that date.

**Comment by escowles** [comment]
@chloepfendler In the next couple of weeks, we plan to bulk-ingest the finding aids content recently pulled out of webspace, implement bulk approval, and also add a report to get the component ID/Figgy manifest URL mapping.

There are two ways we've talked about doing that reporting:
1. Report for all items in a collection (which seems better for bulk-approving collections)
2. Report for all items since a given date (which seems better for routine maintenance)

Assuming that both ways of reporting are needed because of the different use cases, we'll go ahead and implement both reports.

**Comment by chloepfendler** [comment]
Great, and yes, I think both functions would be useful to have, because as you said, there will be different use cases that are better suited by one or the other. Thanks!
