### ISSUE TITLE
Error when trying to parse updated bib records

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2017]
## Backtrace

    line 30 of [PROJECT_ROOT]/app/services/voyager_updater/event_stream.rb: parsed_json
    line 15 of [PROJECT_ROOT]/app/services/voyager_updater/event_stream.rb: events
    line 22 of [PROJECT_ROOT]/app/services/voyager_updater/event_stream.rb: process!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/40463314)

**Comment by escowles** [comment]
@tampakis probably fixed this, and there is only 1 occurrence in HoneyBadger, so closing for now.
