### ISSUE TITLE
Audio Reserve Resources need to synchronize with ARES

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2020]
Currently ARES links to external content for course reserve resources.  As existing audio reserves are migrated and new are ingested into Figgy, links to the Figgy resource viewer will need to be persisted in ARES.  Synchronizing these updates might be supported using RabbitMQ message publishing, or something simpler.

Additionally, ARES also offers an intake workflow for instructors who request that items be placed on reserve.  How should this workflow affect Figgy users creating new audio reserves for courses?

**Comment by kevinreiss** [comment]
Also worth noting. ARES (or ILLiad or AEON for that matter) doesn't have a
proper CRUD api at the moment. Atlas systems has promised this in the next
major release. This is probably best examined when that may actually be
available.

**Comment by tpendragon** [comment]
We closed this because it's impossible.
