### ISSUE TITLE
Make sure corrections are integrated for historical postcards (pudl0009 / AC045)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2021]
We received the following report in SN@P that these items were mislabeled:

![image](https://user-images.githubusercontent.com/2806645/47585262-a3c3f500-d911-11e8-9ecf-2a6a51aad3e8.png)

```
Not Cottage but Cuyler Hall
http://arks.princeton.edu/ark:/88435/tb09j576b   AC045

Not Colonial but Cottage
http://arks.princeton.edu/ark:/88435/pn89d670b  AC045

Not Charter Club but Chemical Laboratory
http://arks.princeton.edu/ark:/88435/4b29b6083   AC045

Not Ivy But Cottage
http://arks.princeton.edu/ark:/88435/0c483j986   AD02 7810
http://arks.princeton.edu/ark:/88435/8w32r621f   AD02 7811

Not Ivy But Holder Hall
http://arks.princeton.edu/ark:/88435/5999n408t   MP52 1836

Not Ivy Maybe Stafford Little Hall
http://arks.princeton.edu/ark:/88435/n296wz73j   AD02 7813

Not Tower But Ivy
http://arks.princeton.edu/ark:/88435/sj1392585   SP07 1632

```

Once we let Christa know what the spreadsheet should look like she will send us updates to run.

**Comment by hackmastera** [comment]
Christa and Lynn will work on getting corrections made where they have been reported. This is not a blocker to migrating this collection or making it public, as the data is wrong in pudl already.

I think we should close this ticket; is it possible to assign the sn@p ticket to their team?

**Comment by hackmastera** [comment]
On second thought, this will require some action on our part to enable data correction imports. I will re-title it to reflect that.

**Comment by escowles** [comment]
Here is the Word doc with the corrections (67 pages of them!). 
[HPC GB Corrections via Maynard May 2 2014 FINAL.docx](https://github.com/pulibrary/figgy/files/4574903/HPC.GB.Corrections.via.Maynard.May.2.2014.FINAL.docx)

Develop a spreadsheet:
* Use ARK as the identifier
* Include a code for deleting a value (e.g., there are notes like "Omit date as obviously wrong")
* If we can parse the title updates out of the text, that would be great. If not, at least include the text in a column to make it easier to copy-and-paste.

**Comment by escowles** [comment]
I created a spreadsheet combining the data from Figgy, the Barksdale corrections, and the dates from the MODS records, and have handed off to Mudd staff who will edit and provide us with corrections that should be ingested: https://docs.google.com/spreadsheets/d/1B5PjqUssciL_mq8QuBWJSouGi71AzCQGxEH3A8Hk0fw/edit#gid=640016204

**Comment by cwulfman** [comment]
Review the import of pudl0009 and perhaps re-perform

**Comment by escowles** [comment]
Another mismatch I noticed recently: https://figgy.princeton.edu/catalog/ccf5ab1b-ed95-4268-9644-ff25e153b58a (metadata says Chemical Laboratory (i.e., Burr Hall), but image is Clio)
