### ISSUE TITLE
"Full Size" JPEGs should not have dimensions greater than 64k pixels

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2029]
JPEG image dimensions are limited to 65536 x 65536, so very wide images (e.g., scrolls like https://figgy.princeton.edu/catalog/7f761a3b-5d00-4e24-9bee-3c865f51285d) are invalid when the user tries to download the full-size image as a JPEG.

We should limit the size of JPEGs to 65536 pixels square

**Comment by tpendragon** [comment]
The new IIIF setup fixed this kinda.
