### ISSUE TITLE
Invalid link to download 1000-pixel JPEGs of very wide images

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2030]
Some very wide images (e.g., scrolls like https://figgy.princeton.edu/catalog/7f761a3b-5d00-4e24-9bee-3c865f51285d) are generating 1000-pixel download images that include `figgy_prod/figgy_prod/` when there should only be one `figgy_prod`.  The duplication does not appear in the manifest, so this may be in the UV code that builds the link.

**Comment by tpendragon** [comment]
Closed as a duplicate #3168.
