### ISSUE TITLE
Migrate numismatics data

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2031]
Child of #2242
Requires #2089

**Comment by christinach** [comment]
`coinids/ accessionids /accession numbers / firm_note = firms.firmname+' '+ firms.firmcity+' ,'+ coins.finddate`
[join-coin-accession-firm.xlsx](https://github.com/pulibrary/figgy/files/2966255/join-coin-accession-firm.xlsx)

**Comment by eliotjordan** [comment]
All Issues and Coins migrated to Figgy.
