### ISSUE TITLE
Analyze Numismatics data for fields and types

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2033]
Child of #2025

**Comment by eliotjordan** [comment]
Conversion to SQLite database: [numismatics.sqlite3.zip](https://github.com/pulibrary/figgy/files/2528088/numismatics.sqlite3.zip)

**Comment by escowles** [comment]
Thanks for that @eliotjordan — i started poking around this morning and found some interesting things, like the IssueArtist and IssueAttribute tables look like annotated link tables.

**Comment by eliotjordan** [comment]
Working on flattening out the data so we can import some test records.

**Comment by eliotjordan** [comment]
Initial sqlite queries to flatten coins table. Except for accessions. Will work on issues table.

https://gist.github.com/eliotjordan/c847ade0b8202ded1e49a64d5e46d37d
