### ISSUE TITLE
Removing pages shouldn't cause errors in the structure editor

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#204]
I received an error report for Plum that editing the structure of an item, then deleting a FileSet, and then editing the structure again produces an error.  We should be able to remove FileSets and have them remove the FileSet from the structure without any problems.

**Comment by tpendragon** [comment]
It looks like this doesn't break in Figgy, but it does leave an empty structure node around (with the label of the old FileSet)

**Comment by hackmastera** [comment]
how do i delete a fileset?

**Comment by hackmastera** [comment]
ah, found it
