### ISSUE TITLE
ChangeSet for MediaReserves

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2044]
Child of #1986

Should have very little metadata, no IIIF hints, and should have the draft/publish workflow

**Comment by christinach** [comment]
@tpendragon what metadata do we want ? Have we specified this somewhere?

**Comment by christinach** [comment]
@tpendragon sth else that I don't know and don't understand the usage. Why do we need a media_reserve_change_set when we will have a scanned_resource_change_set? What is the difference?
