### ISSUE TITLE
scannedresource says `image_resource?` true

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2046]
How is this used? It won't really be accurate once we start putting audio files in scanned_resource

**Comment by escowles** [comment]
WAV -> MP3 derivative generation is working now, so this is probably fine, but sloppy.  It would be good to clean this up to make future derivative processing logic simpler.

**Comment by tpendragon** [comment]
We're doing this now via ChangeSets and it has a logic branch in it.
