### ISSUE TITLE
Publish a manifest for a Range

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2047]
The way to achieve this is to create manifests for portions of a resource.

For ranges we'll either need a new route or we'll use a query string param, e.g.
`http://localhost:3000/concern/scanned_resources/d16b2265-2f28-4b79-b323-157546df0f9d/manifest?range=123456`

Note we need to check on persistence of range ids. Currently we believe they are not persistent, i.e. all the range IDs for a given resource might change if the structure is edited at all.

**Comment by hackmastera** [comment]
@sdellis also mentioned that manifests don't have to embed ranges, they can reference them instead.

**Comment by jrgriffiniii** [comment]
These also change for every request to the resource `Controller`, hence no request for a Manifest generated for any given `Resource` will generate the same Range URIs.

**Comment by escowles** [comment]
Not needed with new Playlist feature.
