### ISSUE TITLE
Improve the structure for authorized link URLs

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2052]
Currently, these https://github.com/pulibrary/figgy/pull/2039 structured these as simply URLs with `auth_token` as an additional querystring parameter.  For example:

Attribute Name | Values
-- | --
Authorized Link | http://localhost:3000/catalog/c46ff572-d514-433e-b9ff-1a36063ee194?auth_token=7bd89dc079f1aa37f0b3d54dec86b6df

This should be restructured in order to be more friendly to browsers and humans.

Child of #1986

**Comment by hackmastera** [comment]
What do you mean "should be restructured"? Do you mean change the display? Change the link itself? What should it be / look like instead?

**Comment by jrgriffiniii** [comment]
This was created in response to feedback captured while showcasing my progress on #2039.  I believe that @tpendragon made this comment, but I don't recall what needed to be improved upon in the URL structure (perhaps the length needed to be shortened?)

**Comment by jrgriffiniii** [comment]
Please disregard https://github.com/pulibrary/figgy/issues/2052#issuecomment-435896345, it was a misunderstanding of https://github.com/pulibrary/figgy/issues/2010#issuecomment-436015991
