### ISSUE TITLE
Ensure that users can regenerate authorization tokens

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2053]
Currently, https://github.com/pulibrary/figgy/pull/2039 does not provide a mechanism for generating new authorization tokens; it simply deletes them permanently when a resource has been deleted, or renders them temporarily invalid when a resource is taken down.

There should be such a mechanism (perhaps simply a button) which could be used to regenerate a new token (should the old token be compromised or the user wish to invalidate the current token).

Child of #1986 
Depends on #2010

**Comment by jrgriffiniii** [comment]
Currently, the most straightforward approach to integrating a button into the catalog show view would be the following:

<img width="1205" alt="figgy_issues_2053_screenshot_0" src="https://user-images.githubusercontent.com/1443986/48805216-c95fd680-ece4-11e8-9e47-d6d56293651b.png">

**Comment by jrgriffiniii** [comment]
Another design I've implemented is the following:

<img width="1128" alt="figgy_issues_2053_screenshot_1" src="https://user-images.githubusercontent.com/1443986/48807897-029c4480-eced-11e8-8b9c-bbd761c96b8f.png">

**Comment by tpendragon** [comment]
I like the second one, but I think we need some sort of text to explain what the implications of regenerating a token are.
