### ISSUE TITLE
Wireframe for playlist feature

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2067]
Child of #2066

**Comment by escowles** [comment]
Wireframes in Google Drive:
* Make playlist active: https://docs.google.com/drawings/d/1WPL8tXEmlf_C0tzdz4L13HH6sLMTUsvkWJHQhSfdXnI/edit
* Show active playlist in header: https://docs.google.com/drawings/d/1CHbZ9NybNGOXRqcmSO0xdu0OxJSUBliJhijCvndpM3s/edit
* Add tracks to active playlist: https://docs.google.com/drawings/d/1Dd0DlzqmvZl78OK6vJZC_OqCzAWPQrxGvu61bC3Llbg/edit

**Comment by escowles** [comment]
The basic workflow is:
1. Create a playlist object (with only title and visibility properties)
2. Click a button on the playlist show page to make it the active playlist
3. The active playlist is shown in the header as you navigate the site, finding tracks
4. On File Manager, each track would have a "add to active playlist" button
5. You would gather the tracks you wanted, and then go back to the playlist and use the order manager and structure manager to manage member order, grouping, etc.

**Comment by hackmastera** [comment]
I like this design. I guess the button to make the playlist active becomes a button to make it inactive?

**Comment by escowles** [comment]
Yes, that button would be a toggle, to make the current active playlist inactive.

**Comment by tpendragon** [comment]
This looks reasonable to me.
