### ISSUE TITLE
Generate HathiTrust ingestibles

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#2068]
See [HathiTrust Ingest Checklist](https://www.hathitrust.org/ingest_checklist) for requirements and specifications. There are three parts:

1. Administrative Coversheet
2. Bibliographic Metadata
3. Content

See also:

- [Guidelines for Digital Object Deposit](https://www.hathitrust.org/deposit_guidelines)
- [SUBMITTING METADATA TO ZEPHIR](https://docs.google.com/document/d/1ILpVfk5y3auLpBicflpGIJbf9bnNZ9qeJwkW48CZ1Xo/edit)
- [HathiTrust Cloud Validation and Packaging Service](https://docs.google.com/document/d/1OQ0SKAiOH8Xi0HVVxg4TryBrPUPtdv4qA70d8ghRltU/edit)
- [Ingest Checklist](https://www.hathitrust.org/ingest_checklist)
-  [Hathi's SIP validator](https://github.com/hathitrust/ht_sip_validator)

Can probably model this feature on the BagIt feature. Should be implemented using Figgy's background workers.

There should probably be a checkbox in admin interface for objects: should this be sent to Hathi?

Questions to answer:

1. Should this (also) be a Rake task?
2. Should we try using Google's new cloud tool to generate hocr?

**Comment by cwulfman** [comment]
How general should this be? This is just another kind of SIP; should we model OAIS?

**Comment by cwulfman** [comment]
A meta.yml file is required. [Hathi provides a template to be used as a model](https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view) The following are required fields:

- capture_date
- scanner_make
- scanner_model
- scanner_user
- scanning_order
- reading_order

The following are required if the data cannot be extracted from the TIFFs:

- bitonal_resolution_dpi (if bitonal TIFF)
- contone_resolution_dpi (if contone TIFFs or JPEG2000 images)
- image_compression_date
- image_compression_agent
- image_compression_tool

A **pagedata** field containing page numbers and page tags (labels) is optional.

**Comment by escowles** [comment]
Some of that seems pretty easy to get from the TIFF:
* capture_date
* scanner_make
* scanner_model
* bitonal/contone resolution_dpi

Some of that is typically not applicable for us: image_compression_date/agent/tool

reading_order we can get from the `viewing_direction` property

These seem harder to me:
* scanning_order: I guess we could infer this from the TIFF timestamps?
* scanner_user: This would typically be the `depositor` user for stuff scanned by the studio, but for vendor-digitized items, I don't think we know this.

**Comment by cwulfman** [comment]
Since we don't compress the images, that metadata shouldn't be relevant, I'd think.
Is there any info about whether or not an item was scanned by the studio or by a vendor? Is that what the `depositor` is?

And what about the logical structure, if it exists? I see there is a logical_structure property, but I don't know what an actual value looks like.

**Comment by tpendragon** [comment]
Branch for ongoing work is here: https://github.com/pulibrary/figgy/tree/issue-2068

**Comment by tpendragon** [comment]
@cwulfman What's the story? Do we close this?

**Comment by cwulfman** [comment]
This project seems to have petered out.  I'm closing this ticket.
