### ISSUE TITLE
Allow creating a playlist from some or all of a MediaReserve's tracks

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2078]
When viewing a list of tracks in a MediaReserve, I should be able to select one or more tracks, and then create a new playlist from them.

Child of #2066

**Comment by escowles** [comment]
Given input from Dan that playlists combining tracks from multiple recordings is not the new norm, this is an important feature to make a common scenario more efficient.

**Comment by tpendragon** [comment]
Proposal in #2098 would mean that they just add all the tracks from a MediaReserve via one button and delete the ones they end up not needing.

**Comment by tpendragon** [comment]
Closing this in favor of #2098
