### ISSUE TITLE
Playlist model

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2079]
Metadata:
* Label
* Visibility (default private)
* Access Token

Child of #2066

**Comment by hackmastera** [comment]
should they have a workflow?

**Comment by escowles** [comment]
@hackmastera I have not heard any scenarios described for playlist workflow, so I think it's fine to not have a workflow for now.  But I'll add it to the agenda for the next time we talk to Dan.

**Comment by hackmastera** [comment]
Access token will be done as part of #2010 / #2039
