### ISSUE TITLE
Figure out titles for NumismaticIssue and Coin resources

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2090]
How do we generate titles for these resource types?

Child of #2025

**Comment by escowles** [comment]
Alan didn't give any guidance when asked about this today.  But I believe @tampakis said that Alan previously said the short reference would be a good label.

**Comment by escowles** [comment]
I think "Coin 123" is fine for Figgy, and we can worry about titles for end-users as part of #2004.
