### ISSUE TITLE
NumismaticIssue and Coin search visibility

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2100]
Alan mentioned wanting to have the Coin resources visible to the end user while hiding the Numismatic issue.

Child of #2025

**Comment by eliotjordan** [comment]
This is the inverse of how we typically handle parent-child relationships.

I'm not 100% convinced about this. For example, from what I can tell, the issue has richer metadata. Also, grouping different copies of the same coin together seems like a nice feature.

**Comment by escowles** [comment]
I have mixed feelings on this, but I'm leaning towards trusting the user to know the data better than us.

I think we can address the grouping and issue metadata issues:
* Have a facet or other link to find all the coins in a given issue
* Pull the issue metadata into the coin record for display and discovery
