### ISSUE TITLE
Show Page redesign

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2125]
The buttons are at the bottom, and you have to scroll past the metadata and viewer.  Maybe we should make the buttons sticky at the bottom of the screen? Or move the viewer to the bottom of the page?

**Comment by escowles** [comment]
Making the buttons sticky at the bottom of the screen is one option we discussed — but there were a few other options, like moving the button and/or viewer to different places so they are not so far away.  So I think we should talk to some users before we make any big changes.

**Comment by hackmastera** [comment]
Here's a plan for user testing https://docs.google.com/document/d/1IU6ZAzHLCqcYJz1_6FfM7LkES-avBE6hXpbGia9gH_8/edit#

**Comment by tpendragon** [comment]
These are great. L+1:

**Comment by escowles** [comment]
👍 thanks for wireframing the ideas we've discussed — these look great for getting feedback on these options!

**Comment by hackmastera** [comment]
jpegs showing user votes are in this google dir https://drive.google.com/drive/folders/1OI4PpCwClXNK99HJARvzyuiQq2q0ZSJZ

**Comment by tpendragon** [comment]
Looks like we should pin the action buttons and do a full width layout. Moving the viewer in some form seems contentious.

**Comment by escowles** [comment]
I'm trying to reconcile the split opinion on moving the viewer, with the almost-universally positive vote for the full-width layout.  Do people want a full-width layout, but want to be able to switch back to the single-column layout?

**Comment by tpendragon** [comment]
I think the issue is Option B of the viewer page was much more than just a "thumbnail" change - it was basically a full-width layout too. I think we should ignore that test for now and just do the full-width layout.

**Comment by hackmastera** [comment]
It's interesting that the "move the viewer" option that did get votes in some ways resembles the full-width layout. I agree with @tpendragon the left column on that option was sort of too wide and made it look full-width-y.

A full-with layout implies a full-width screen; less than a certain size should revert to single column.

I agree we should do the 2 with clear results and re-assess after that.

**Comment by hackmastera** [comment]
We still need to integrate feedback about the workflow form; Joyce suggested it should also be pinned.

**Comment by tpendragon** [comment]
Joyce also said she never looks at the metadata - if in full-width the workflow is just at the top, with the buttons pinned, it may not be an issue?

**Comment by hackmastera** [comment]
I was going to make this an epic but then i realized the user testing process resulted in wireframes that users endorsed. So it seems like the design portion is more or less done. Creating implementation tickets:
#3009 - sticky action buttons
#3010 - full-width layout
