### ISSUE TITLE
Try to resolve call numbers to Bib-IDs for MusicReserves

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2139]
Child of #2043 

See if we can find bib-ids for all call numbers in course numbers that have numbers in them (this means it's a course, and not like the Princeton University Orchestra.)

If you can't resolve the call number, check to see if there are audio files attached to that recording which are attached to another recording and DOES have a valid call number. That means it's a playlist.

You can search for call numbers like this: https://catalog.princeton.edu/browse/call_numbers.json?search_field=browse_cn&q=cd-+2016-03-05. Know that the third one is the match.

An alternative to try might be https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&f[call_number_browse_s][]=CD-%202016-10-23, but it's case sensitive. CD -should- always be capitalized, I'd just try capitalizing everything.

Acceptance Criteria:

1. How many call numbers in all of the Recordings table can be converted to bib-ids
2. How many call numbers recordings which are in numbered courses can be resolved vs un-numbered courses.
3. How many "fake" call numbers are duplicate recordings with the same audio files that we can convert to Playlists.

Include examples of failures for all three above.

**Comment by hackmastera** [comment]
here are a bunch of varieties of call numbers
      cd-10994
      cd-24583v1
      ls-14032
      cd-10580 discs 5-8
      cd-39858disc32
      cd-16961q
      CASS-129 pt.1
      VCASS-46
      cd-6375 vol.2
      A-302 N 255
      A-302 N 539 LP
      cd-WNN-1
      lc call numbers like M1010.M87 B62q
      R003084CD
      VDISC-34
      DVD-32
      dat-2003-05-20
      dat-1998.10.12
      cd-2008-05-01
      cd-2010-05-06_WIND
      prince-05
      Tape3-1
      AlexSt_7C381415
      x-frs105-cdh
      T-97
      sessions 11
      R001170LP
      SeniorComp
      mus316_IntoIndia
      cd-4666qv11
      mus550 F'08 list
      3F-50 B22 LP
      CDX 5107
      AMSO-1168494
      SMCD 5161
      Naxos_OBCCD-510-2
      Youtube_AQUVLz99bqY
      null
      x-mus218 Milhaud

**Comment by hackmastera** [comment]
Here's my final report.
[music_report_final.log](https://github.com/pulibrary/figgy/files/2605728/music_report_final.log)

Changes to ansible will be required to merge a deployable PR. but the branch is otherwise ready; https://github.com/pulibrary/figgy/compare/issue/2139-resolve-bibids?expand=1

**Comment by tpendragon** [comment]
Added some caching so I could run the numbers quicker, and adjusted it so it would count things like `mus103sm`. My result:

```
I, [2018-11-26T15:40:32.262000 #19369]  INFO -- : Report Summary
I, [2018-11-26T15:40:32.262014 #19369]  INFO -- : --------------
I, [2018-11-26T15:40:32.262142 #19369]  INFO -- : Bib ids found in 0 of 281 recordings (suspected playlists) where call number starts with 'x-' (0%)
I, [2018-11-26T15:40:32.262158 #19369]  INFO -- : Removed suspected playlists from remaining stats
I, [2018-11-26T15:40:32.262172 #19369]  INFO -- : --------------
I, [2018-11-26T15:40:32.264954 #19369]  INFO -- : Bib ids found in 6586 of 7973 recordings (82%)
I, [2018-11-26T15:40:32.264999 #19369]  INFO -- : --------------
I, [2018-11-26T15:40:32.265941 #19369]  INFO -- : Bib ids found in 4089 of 4781 recordings with numbered course names (85%)
I, [2018-11-26T15:40:32.266189 #19369]  INFO -- : Bib ids found in 826 of 1029 recordings with other course names (80%)
I, [2018-11-26T15:40:32.266208 #19369]  INFO -- : 2163 recordings not in any course
```

The call numbers with multiple bib numbers is unfortunate - it looks like if there's multiple songs on a disk there might be one call number but multiple bib ids (appropriately).

I'm going to pull the labels and see if that'll be a useful metric. It might be that recordings shouldn't be mapping to bib-ids though.
