### ISSUE TITLE
Support ingesting PDFs

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2140]
- [x] Ingest PDF as a master file
- [x] Display PDF in the browser
- [ ] Text extraction for fulltext search

**Comment by tpendragon** [comment]
Questions:

1. Use case? What project is this for?
2. Should we extract pages and ingest them as individual files so we can use IIIF?
3. If not, do we use UV's PDF functionality, or just let them download the PDF?

**Comment by escowles** [comment]
This has come up a couple of times recently.  The case I'm thinking of today is a newspaper project (Princeton Area Cooperative Online Newspaper Project (PACON)), which has a combination of scanning microfilm and born-digital PDFs.

I think it would be a better experience to give users the original PDF than ripping to page images.  We might do that using the UV PDF functionality, or it might be through some other frontend like Veridian.

**Comment by escowles** [comment]
Closing this ticket because ingest works now — I've created https://github.com/pulibrary/figgy/issues/3152 for text extraction for fulltext search.
