### ISSUE TITLE
Add support for HLS

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2149]
* What advantages does it have over just handing off to Nginx?
* How hard is it to support?

Child of #1986

**Comment by tpendragon** [comment]
https://benwilber.github.io/streamboat.tv/nginx/rtmp/streaming/2016/10/22/implementing-stream-keys-with-nginx-rtmp-and-django.html
https://trac.ffmpeg.org/wiki/StreamingGuide
https://isrv.pw/html5-live-streaming-with-mpeg-dash

**Comment by tpendragon** [comment]
Initial hurdle is I think we're going to have to compile nginx from source, with passenger and rtmp included.

**Comment by tpendragon** [comment]
Looks like with nginx+ we wouldn't have to, but I assume that's a bit away.
