### ISSUE TITLE
[Figgy/production] PDFGenerator::Error: PDFGenerator::Error

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2153]
## Backtrace

    line 30 of [PROJECT_ROOT]/app/services/pdf_generator.rb: rescue in block in render
    line 24 of [PROJECT_ROOT]/app/services/pdf_generator.rb: block in render
    line 18 of [PROJECT_ROOT]/app/services/pdf_generator.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39221773)

**Comment by hackmastera** [comment]
the pdf generator logs before it errors: https://github.com/pulibrary/figgy/blob/f857a694b2012cb0b56534dd28e5914ff6b79552/app/services/pdf_generator.rb#L27

Here is a link to live logs of that type in the past week: https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&event&from_ts=1541516408855&index=main&live=true&query=%22failed+to+download+a+PDF%22&stream_sort=desc&to_ts=1542121208855

**Comment by hackmastera** [comment]
the pdf in question was still failing to download for me: https://figgy.princeton.edu/catalog/9e2b842c-46c2-485d-872d-20fbf0ec7c92

**Comment by jrgriffiniii** [comment]
The URL being used by `prawn` might be somehow malformed, as I'm getting valid responses for some of these requests:

https://libimages1.princeton.edu/loris/figgy_prod%2Fcd%2F41%2Ff3%2Fcd41f3ed7f474ee59127282273f9cd93%2Fintermediate_file.jp2/full/1000,/0/bitonal.jpg
derived from https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&context_event=AAAAAWcedsXa1OXz1gAAAABBV2NlZHNoVXZLVWF5YzlsX01GLQ&event=&from_ts=1541798192592&index=main&live=false&messageDisplay=inline&query=host%3Afiggy2+service%3Afiggy+filename%3Aproduction.log&stream_sort=desc&to_event=AAAAAWcedyOd1OXz4AAAAABBV2NlZHpCenZLVWF5YzlsQXlHNg&to_ts=1542404383645

**Comment by jrgriffiniii** [comment]
Malformed URLs are being used in some cases to request data from the image server during PDF generation:
```
PDFGenerator: Failed to download a PDF using the following URI as a base: https://libimages1.princeton.edu/loris/figgy_prod/63%2Ff3%2F5d%2F63f35ddc68b04febb00cf4f4267372f2%2Fintermediate_file.jp2: 400 BAD REQUEST
```
https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&context_event=AAAAAWdQg6XL0IcerwAAAABBV2RRZzZfelJHM0poWjhxZy04bQ&event=&from_ts=1543243196443&index=main&live=false&messageDisplay=inline&query=host%3Afiggy1+service%3Afiggy+filename%3Aproduction.log&stream_sort=desc&to_event=AAAAAWdQg7C40IceuwAAAABBV2RRZzhGUlJHM0poWjhxaFpmVw&to_ts=1543244067000

**Comment by tpendragon** [comment]
https://figgy.princeton.edu/concern/scanned_resources/8b01ee9b-d156-4d5a-8cb5-a8066750bd6d/pdf This is one that seems to error reliably.

**Comment by christinach** [comment]
https://figgy.princeton.edu/catalog/ddf9afb7-8de4-4ccf-bfa7-9c3137f52427/ this one fails to download as well

**Comment by jrgriffiniii** [comment]
I have just reproduced this, hence it is still a valid bug.

**Comment by tpendragon** [comment]
We haven't seen this error in a long time, closing.
