### ISSUE TITLE
Coin/Issue numbers should be multiple in the database

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2162]
They are currently singular:
```
{
  "visibility":["open"],
  "denomination":[],
  "issue_number": 6,
  "rights_statement": [{"@id": "http://rightsstatements.org/vocab/NKC/1.0/"}]
}
```

Instead they should be multiple in the db (`"issue_number":[6]`) but singular in the app.

**Comment by tpendragon** [comment]
Sure enough, this is broken in `valkyrie-sequel`. And maybe the postgres adapter too.

**Comment by tpendragon** [comment]
https://github.com/samvera-labs/valkyrie-sequel/pull/14 fixes it. We'd normally have to run a migration when we do this, but we have no coins or proxy files in production (which I think are the only things that have single values)
