### ISSUE TITLE
Order manager - lux-button.dropdown 

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#2171]
Is it considered a good UX when you click on a dropdown button and the menu stays open, even when you move your mouse away or when you click outside of the menu? 

Should this button have a mouseleave or a hide when you click somewhere else on the webpage?

![order_manager](https://user-images.githubusercontent.com/9905193/48559275-4b9d6480-e8b9-11e8-900f-4af9b83c3be5.png)

**Comment by tpendragon** [comment]
This needs a companion lux ticket.

**Comment by sdellis** [comment]
@christinach this has been fixed for a while. You just need to update the lux version. Current is 2.16.3: https://pulibrary.github.io/lux/docs/#/Patterns/DropdownMenu

**Comment by christinach** [comment]
Thank you @sdellis! I will check again when we update lux the version.

**Comment by christinach** [comment]
closing: we updated lux and this is no longer an issue.
