### ISSUE TITLE
Accession form reorg

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2175]
Reorganize the Numismatic Accession form to match the order of the existing application:
* accession number
* number in accession
* accession date
* number of items
* accession type
* cost
* account
* acquired from person
* acquired from firm
* info
* private info
* references

Child of #2025

**Comment by christinach** [comment]
where is the 'number of items' coming from?

**Comment by escowles** [comment]
For now, let's assume they are going to enter the number of items in the gift/purchase manually.  We may want to calculate this based on the number of coins that are created.

**Comment by christinach** [comment]
ok then I will add it in the PR.

**Comment by christinach** [comment]
Does it make sense the number (in the accession) and the items_number to be Valkyrie::Types::Int ?

**Comment by escowles** [comment]
I think so, but I would look at the data to see if they have any other kinds of data in there.  It sounds like just a simple count, but maybe they have "about 500" or other estimates, too?

**Comment by christinach** [comment]
I thought it was just a number but will check again. thanks
