### ISSUE TITLE
Karachi map has 2 intermediate_files

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2193]
Maybe as a result of addressing this error?

## Backtrace

    line 74 of [PROJECT_ROOT]/app/derivative-services/image_derivative_service.rb: run_derivatives
    line 64 of [PROJECT_ROOT]/app/derivative-services/image_derivative_service.rb: create_derivatives
    line 39 of [PROJECT_ROOT]/app/derivative-services/scanned_map_derivative_service.rb: create_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/41645347)

**Comment by eliotjordan** [comment]
Not sure why this occurred, but the original tiff was deleted and re-ingested. Seems to be working now.
