### ISSUE TITLE
Refactoring for Valhalla Decorators and Controllers

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#223]
As identified during a discussion on 09/20/17, @eliotjordan identified elements of functionality which could be refactored between the decorators and controllers.  Concerns blocking this refactoring were possibly some mixins which are more appropriately structured for the Valhalla Gem.

**Comment by tpendragon** [comment]
Cold we expand on this ticket into specifics?

**Comment by jrgriffiniii** [comment]
Certainly, I would imagine that the following methods _may_ be generic to any Valkyrie-based repository application to warrant their relocation to the `Valhalla` Gem.  However, I welcome input from @escowles, @tpendragon, @eliotjordan, and all others should these remain specific to `figgy`:

# Decorators
## `metadata_adapter`
- ScannedResourceDecorator#metadata_adapter
- EphemeraProjectDecorator#metadata_adapter
- EphemeraBoxDecorator#metadata_adapter
- EphemeraFolderDecorator#metadata_adapter
- EphemeraTemplateDecorator#metadata_adapter
- EphemeraFieldDecorator#metadata_adapter
- EphemeraVocabularyDecorator#metadata_adapter
- EphemeraTermDecorator#metadata_adapter

## `members`
- ScannedResourceDecorator#members
- EphemeraProjectDecorator#members
- EphemeraBoxDecorator#members
- EphemeraFolderDecorator#members

## `member_of_collections`
- ScannedResourceDecorator#member_of_collections
- EphemeraBoxDecorator#member_of_collections
- EphemeraFolderDecorator#member_of_collections

## `rendered_rights_statement`
- ScannedResourceDecorator#rendered_rights_statement
- EphemeraFolderDecorator#rendered_rights_statement

# Controllers
## `manifests`
- CollectionsController#manifests
- ScannedResourcesController#manifests
- EphemeraFoldersController#manifests

## `load_collections`
- ScannedResourcesController#load_collections
- EphemeraBoxesController#load_collections
- EphemeraTemplatesController#load_collections
- EphemeraFoldersController#load_collections

## `load_vocabularies`
- EphemeraFieldsController#load_vocabularies
- EphemeraFoldersController#load_vocabularies
- EphemeraTermsController#load_vocabularies

**Comment by hackmastera** [comment]
Revisit after #641

**Comment by tpendragon** [comment]
There are no longer Valhalla controllers, Wayfinders closed a bunch of these, and in general for the next set of refactoring we need to do a review of the code with individual tickets. Closing this.
