### ISSUE TITLE
Extract title of track from wav file on characterization

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2230]
We can make the lives of the ingesters easier this way, I think.

**Comment by hackmastera** [comment]
Used this tool to create a fixture: https://github.com/jangler/taffy

**Comment by hackmastera** [comment]
It looks like we currently use `original_filename` as the label for a file. but it also has its own field. so we should be able to override label with the extracted value without issue.

And then we would overwrite the fileset title, also?
