### ISSUE TITLE
Coin auto ingest is triggered on every page load

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2235]
## Backtrace

    line 118 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/41827486)

**Comment by eliotjordan** [comment]
https://github.com/pulibrary/figgy/blob/master/app/assets/javascripts/auto_ingest_handler.es6#L5
