### ISSUE TITLE
Support IIIF search-within

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#225]
We should have a search endpoint that does a full text search, scoped to a ScannedResource, that returns at least a list of pages that match.

Ideally, it would return coordinates of hits for hit-highlighting, but that could be on a second pass after a user had selected a page to view.

Use case: As a researcher I want to quickly find mentions of a specific author within a book.

**Comment by escowles** [comment]
See http://iiif.io/api/search/1.0/

**Comment by tpendragon** [comment]
How important is phrase searching and fuzzy matching/stemming?

**Comment by escowles** [comment]
See if we can just use https://github.com/boston-library/blacklight_iiif_search
