### ISSUE TITLE
[Figgy/production] ActionView::Template::Error: Current page was incalculable. Perhaps you called .per(0)?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2257]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/40929409)

**Comment by escowles** [comment]
This happens if you call `catalog?rows=0`

**Comment by tpendragon** [comment]
@escowles needs to not break the catalog.
