### ISSUE TITLE
Common tasks user test

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2258]
This is an idea to support https://github.com/pulibrary/figgy/issues/894

At all-hands, start off each user meeting with a small user test. Ask each user to tell us the top 1-3 things they go to Figgy to do (maybe write these down). Then for each user log them in to figgy and ask them to show us how they get to where they need to go to do that thing. This would give us some insight into how many clicks it takes users to get to the starting point for beginning their actual work.

**Comment by hackmastera** [comment]
Here's a handout we could distribute at the start or end of upcoming meetings: https://docs.google.com/document/d/1J3K7_v31KTGnc7laFlO69igehaccI7qKf8iJMo4o0Uw/edit

If we give a few to each person we should get a good sense of how they use the current home page, revealing the most important elements.

**Comment by escowles** [comment]
👍 This looks like a great way to get feedback on what people are actually using in the very cluttered home page.

**Comment by hackmastera** [comment]
all the forms from this exercise were scanned and are on google drive: https://drive.google.com/open?id=1qYzBOIHGYUSDPcdukQ_axk5L4OD_HlUF
