### ISSUE TITLE
BulkIngestService should handle Folders from cloud storage providers (e. g. Google Drive)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2274]
## Backtrace

    line 44 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: attach_dir
    line 13 of [PROJECT_ROOT]/app/jobs/ingest_folder_job.rb: block in perform
    line 113 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: block (2 levels) in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/42330874)

**Comment by tpendragon** [comment]
I wonder if this is what happens if you bulk ingest and select a google drive folder?

**Comment by jrgriffiniii** [comment]
This is not triggered by users who bulk upload Google Drive Folders, as I was able to successfully upload these from my own personal account.
