### ISSUE TITLE
[Figgy/production] URI::InvalidURIError: bad URI(is not URI?): June 30.xml

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2288]
## Backtrace

    line 35 of [PROJECT_ROOT]/app/services/pul_metadata_services/client.rb: retrieve_from_pulfa
    line 14 of [PROJECT_ROOT]/app/services/pul_metadata_services/client.rb: retrieve
    line 44 of [PROJECT_ROOT]/app/models/remote_record.rb: client_result

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/42583431)

**Comment by eliotjordan** [comment]
This is about folder names for bulk ingest of vector resources.

**Comment by eliotjordan** [comment]
Maybe add a switch to the bulk ingest form to indicate whether or not to extract remote metadata.
