### ISSUE TITLE
Use case to create a figgy record for an object with suppressed bib record

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#2291]
Sometimes the studio is asked to photograph something brand new. When they're ready to add it to figgy, the marc record isn't done / published yet for the catalog. So figgy can't pull it from bibdata. Use case came via Beth.

**Comment by tpendragon** [comment]
This is why title is optional instead of bibid. What do they need?

**Comment by tpendragon** [comment]
Oh, do they want to save and ingest? That makes sense.
