### ISSUE TITLE
Map folders contain Thumbs.db files which MIME::Type.type_for does not recognize

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2297]
[Figgy/production] NoMethodError: undefined method `content_type' for nil:NilClass

## Backtrace

    line 166 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: block in files
    line 160 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: each
    line 160 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: each_with_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/42895734)

**Comment by hackmastera** [comment]
contents of the file being ingested:
```
.
├── 08031
│   ├── denver_2013.xml
│   ├── Parcels_08031_2013.zip
│   └── Thumbs.db
├── 08045
│   ├── c522734b-9097-491a-8f50-04c848ddd54a.xml
│   ├── Parcels_08045_2013.zip
│   └── Thumbs.db
├── 08049
│   ├── Parcels_08049_2013.xml
│   ├── Parcels_08049_2013.zip
│   └── Thumbs.db
├── 08049_r
│   ├── roads_08049_2013.xml
│   └── roads_08049_2013.zip
├── 08051
│   ├── 98aa6b2b-d598-4a54-91ac-e949eacdb938.xml
│   ├── Parcels_08051_2013.zip
│   └── Thumbs.db
└── 08085
    ├── c6db7421-3462-4894-b5bf-2b1ea2ca201d.xml
    ├── Parcels_08085_2013.zip
    └── Thumbs.db
```

These `Thumbs.db` files are returning a `mime_type` of `[]` so when `first.content_type` is called you get this `NoMethodError` on `NilClass`.

I suspect these are OS-created files. Are these files that we want in the repository? If so, we should update the code to allow them. If not, do we want to write in a way to ignore them? or scan for them up from and warn users about them? Or something else?
