### ISSUE TITLE
Auto-refresh imported metadata from finding aids

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2324]
Finding aids change frequently. Manually refreshing this data is not do-able for archives staff.

depends on #2339

**Comment by hackmastera** [comment]
VoyagerUpdater::Event processes a voyager dump, pulling ids of updated bib records and queuing update jobs from them. I don't know if anything like this is possible from the finding aids site.

Does it make sense to just update all finding aids metadata nightly, at least for now? Unfortunately I think the only way to know whether a resource pulls from finding aids or from voyager is by inspecting the `source_metadata_identifier`. Is there a way to do this that makes any sense?

**Comment by hackmastera** [comment]
(update Faith on progress here)

**Comment by escowles** [comment]
It seems like we could use the change history in SVN to figure out which finding aids had been updated and needed to be reindexed.  For example, I think this should output a list of files changed since a given date: `svn diff --summarize -r {2018-12-17}:HEAD eads`

**Comment by hackmastera** [comment]
Is everything we want in the eads directory?

**Comment by hackmastera** [comment]
example output:
```
$ svn diff --summarize -r {2018-12-19}:HEAD --username XXX --password XXX http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/publicpolicy/MC008.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/publicpolicy/MC007.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC120.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC126.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC133.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC139.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC162.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC168.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC188.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC123.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC152.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC154.EAD.xml
M       http://diglibsvn.princeton.edu/svn/pulfa/trunk/eads/mudd/univarchives/AC248.EAD.xml
```

**Comment by hackmastera** [comment]
EADS are collection-level description, and components within collections are described in the same EAD. e.g. there is an EAD at `eads/mudd/univarchives/AC044.EAD.xml` which contains the description for https://findingaids.princeton.edu/collections/AC044/c0003. So we'll need to update any resource with a source_metadata_identifier that starts with the ID taken from the basepath.

**Comment by escowles** [comment]
I believe everything we want is in the `eads` directory, but I've asked if we should also check the `ead_inprogress` or `ead_restricted` since I'm not sure how those are used.

**Comment by hackmastera** [comment]
I haven't found a way to query postgres for a jsonb key that contains a string that starts with a certain value (this would be something like `metadata @>'source_metadata_identifier' LIKE 'AC044%'`) However, the archives folks are asking for functionality to search for objects in figgy by finding aid collection ID, so perhaps we need to add a new field to support both that and this. I'll update this comment with the issue number once it's created.

**Comment by escowles** [comment]
👍 adding a field for the finding aid seems like a good way to solve this query problem.

**Comment by escowles** [comment]
Those appended svn revisions are curious.  I only see two of them:

* eads/mudd/publicpolicy/MC197.EAD.xml.r16845
* eads/mudd/univarchives/AC129.EAD.xml.r16131

I wonder if they are an artifact of svn?  They were created months apart by two different users, so it seems unlikely to be a user-created backup or alternate version.

**Comment by hackmastera** [comment]
I definitely remember them from my svn days although I'm struggling to recall their meaning. Are they some artifact of merge conflicts?

**Comment by escowles** [comment]
That seems likely — maybe svn creates them when there's a merge conflict, and then users committed them accidentally after resolving the conflict in the main file?

**Comment by hackmastera** [comment]
Yes that sounds right to me.
