### ISSUE TITLE
Soviet Posters Ephemera: multiple creators

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2326]
Thomas Keenan has asked for the ability to have multiple creators for the Soviet Posters ephemera project:
> Some of our posters have multiple artists, and we would like to list the names of each in both Cyrillic and Roman script.

depends on #1139

**Comment by tpendragon** [comment]
@kelea99 Can we close this?

**Comment by kelea99** [comment]
This is similar to/same as  #2452. should the two be connected? we do not have multiple creators in ephemera yet, so it should be either be buddies with 2452 or addressed separately.

**Comment by tpendragon** [comment]
Closing this and leaving it for 2452.
