### ISSUE TITLE
Rake task to import vocabs from CSV

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#233]

**Comment by hackmastera** [comment]
Does such a CSV exist already? Or just create a fixture based on the data model?

**Comment by tpendragon** [comment]
Yeah, the CSVs already exist:

CSVs: https://github.com/pulibrary/pul-store/tree/development/db/fixtures
Rake task in Plum: https://github.com/pulibrary/plum/blob/master/lib/tasks/vocab.rake
Commands Which Should Work: https://github.com/pulibrary/plum/issues/1274
