### ISSUE TITLE
Add ESLint for the OrderManager and other Vue Components

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2332]
Currently Jest is used to provide the testing of components, mutators, and actions, but none this code is linted.  @sdellis has recommended that we follow the [Standard styleguide](https://github.com/standard/standard), but notes that there is an alternative offered by [AirBnB](https://github.com/airbnb/javascript).

**Comment by tpendragon** [comment]
Plum had this once, https://github.com/pulibrary/plum/pull/169/commits/a55f473e51740bbf4c038f4843a67ece0679246e
