### ISSUE TITLE
Handle Valkyrie::Persistence::ObjectNotFoundError within GraphQL queries by returning a custom response code

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2356]
## Backtrace

    line 118 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/43810943)

**Comment by tpendragon** [comment]
I don't think a 404 is quite right. I think it should just not return the resource? What's standard for GraphQL here?

**Comment by jrgriffiniii** [comment]
From what I could determine, the spec. doesn't recommend any particular code: https://facebook.github.io/graphql/June2018/#sec-Response-Format.  Some have used the `extensions` field to provide some additional information which could be parsed by the client, but I haven't found anything more specific than this (please see a case in https://github.com/graphql/express-graphql/issues/111 and https://github.com/graphql/express-graphql/pull/152).

I don't at all object to returning the resource with a status code of 200.

**Comment by tpendragon** [comment]
I think if you ask for a resource and it doesn't have a resource you probably just return null?
