### ISSUE TITLE
Logical structure does not work for MapSets

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2377]
Because of the way in which ScannedMaps are modeled, the structure manager saves the logical structure for MapSets in way that generates broken manifests. Specifically, the canvas id for a range with a ScannedMap does not match the id of the corresponding canvas.

**Comment by tpendragon** [comment]
OH. Yes. We never fixed logical structure for sammelbands.

**Comment by tpendragon** [comment]
Duplicate of #1554?

**Comment by eliotjordan** [comment]
Maybe a dupe. I was working on fixing this at the wayfinder/controller level, which does not fix it for all sammelbands:

https://github.com/pulibrary/figgy/compare/2377-map-set-structure

Which mirrors logic in the manifest builder:

https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder.rb#L275
