### ISSUE TITLE
Send (delayed) collection reports for new collections

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2387]
When I create a new collection and ingest content, I would like to send the collection report to the collection owner(s) to alert them of new content to review.  But, since ingest and derivative generation can take several hours to complete, I would like to wait before sending the email (e.g., wait until the next morning, or until derivative processing is done).

**Comment by tpendragon** [comment]
@escowles Is someone asking for this is or is it just you asking?

**Comment by escowles** [comment]
I think @kelea99 asked for this?  Is that true? Is this needed?

**Comment by tpendragon** [comment]
@kelea99 Still necessary?

**Comment by kelea99** [comment]
Nope. closing.
