### ISSUE TITLE
Viewer.html needs style resets to allow content to be delivered via UV iframe

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#2407]
[viewer.html](https://github.com/pulibrary/figgy/blob/master/public/viewer.html) should have the same style resets as the [uv.html](https://github.com/pulibrary/figgy/blob/master/public/uv/uv.html)

**Comment by tpendragon** [comment]
We fixed this as part of enabling user controls in the catalog. The catalog's now using `viewer` and nobody knows.
