### ISSUE TITLE
Track titles are sometimes in JSON-LD.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2409]
![screen shot 2019-01-10 at 10 39 15 am](https://user-images.githubusercontent.com/2806645/50989372-05810d80-14c4-11e9-8a5e-2e2ab1c0d4f2.png)

You can see it here: 
https://figgy-staging.princeton.edu/catalog/a6c51760-79e0-4334-8e56-d41212d84b1c

**Comment by hackmastera** [comment]
Ah. I think this is just an issue because it's rendered by javascript, which won't do ruby string interpolation. So mapping to `to_s` should resolve it. trying it now.
