### ISSUE TITLE
Raster and Vector resources with bibids are raising errors in GraphQL queries

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2411]
## Backtrace

    line 24 of [PROJECT_ROOT]/app/graphql/types/resource.rb: resolve_type
    line 20 of [PROJECT_ROOT]/app/controllers/graphql_controller.rb: block in execute
    line 114 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: block (2 levels) in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/44056447)

```
[Figgy/production] NameError: uninitialized constant Types::RasterResourceType
```

Some raster resources and vector resources have bibids, and it appears orangelight is making queries to the Figgy GraphQL endpoint that are raising exceptions.

**Comment by eliotjordan** [comment]
Someone in the maplab created a GeoTIFF from an existing scanned map and made a corresponding raster resource with the same bibid.  We don't have the use case, yet, for discovering raster and vector resources separately in the catalog, so we should filter these out for now.
