### ISSUE TITLE
A service is trying to access a non-existent ephemera folder manifest

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2413]
## Backtrace

    line 118 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/41764590)

https://figgy.princeton.edu/concern/ephemera_folders/05023681-b68b-4186-b94f-ba9aba7688c0/manifest

**Comment by tpendragon** [comment]
Someone deleted it today about 20 minutes ago, according to the logs.

**Comment by tpendragon** [comment]
Really I think asking for the manifest of a missing resource just shouldn't return a 500, right?

**Comment by escowles** [comment]
That sounds like a 404 to me.

**Comment by tpendragon** [comment]
It was DPUL trying to get the manifest. There's a log for it: https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&event=AAAAAWg-QV8OrL2ZtAAAAABBV2ctUVdtYmF6RUxoVnVjcFROSQ&from_ts=1544642190300&index=main&live=true&query=05023681-b68b-4186-b94f-ba9aba7688c0+source%3A%28ruby+OR+nginx%29&stream_sort=desc&to_ts=1547234190300

**Comment by escowles** [comment]
It's returning 404 now
