### ISSUE TITLE
Intermittent Postgres errors with GraphQL queries

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2416]
## Backtrace

    line 23 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: block in log_connection_yield
    line 17 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: log_connection_yield
    line 76 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: block in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/44236672)

```
[Figgy/production] Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() SSL error: decryption failed or bad record mac
```

**Comment by escowles** [comment]
I found this issue for Sequel, and they recommended using the extension validator extension to validate connections from the pool: http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/connection_validator_rb.html

**Comment by tpendragon** [comment]
I think it's using that already

**Comment by tpendragon** [comment]
https://github.com/samvera-labs/valkyrie-sequel/blob/master/lib/valkyrie/sequel/metadata_adapter.rb#L12

**Comment by escowles** [comment]
The next line sets the validation timeout (i.e., how long ago a connection needs to have been validated before it's re-validated) to 1800s.  That doc says you can set it to `-1` to validate the connection every time.

**Comment by tpendragon** [comment]
Yeah, the documentation says that it's expensive to try every time, but we can give it a shot

**Comment by escowles** [comment]
Yeah, I'm not sure it'll be worth the performance hit, since we're not seeing a ton of these errors.  But I think it's worth seeing what it looks like.
