### ISSUE TITLE
Order manager: shrinking the resources doesn't work well when there are no thumbnails

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2422]
@tpendragon took a screenshot

**Comment by jrgriffiniii** [comment]
<img width="983" alt="figgy_issues_2422_screenshot_0" src="https://user-images.githubusercontent.com/1443986/51412420-87fb7400-1b39-11e9-81f6-d65ddf0744e8.png">

**Comment by tpendragon** [comment]
Pending https://github.com/pulibrary/lux/pull/155
