### ISSUE TITLE
BrowseEverythingIngestJob and PreserveChildrenJob should rescue ObjectNotFound and not retry

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2438]
## Backtrace

    line 118 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38033419)

**Comment by eliotjordan** [comment]
Re-opened because this is also happening in PreserveChildrenJobs.

**Comment by hectorcorrea** [comment]
Looks like this is still an issue, it happened 700+ times on 5/14.

**Comment by bess** [comment]
This error is still appearing in honeybadger as of 17 May 2021
