### ISSUE TITLE
Thumbnails for private ScannedMaps (and other spatial resources) should be rendered in the catalog

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2439]
Thumbnails for private ScannedMaps are currently rendered for pulmap, and this behavior should be consistent across platforms.

**Comment by escowles** [comment]
This would also let users know that an item was digitized and needed approval for the viewer to display.

**Comment by tpendragon** [comment]
@eliotjordan Do with this what you will.
