### ISSUE TITLE
Logged in users can't download restricted vector files from Figgy when in Pulmap

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2442]
All authorized users should be able to download restricted content vector and raster resources.

**Comment by tpendragon** [comment]
@eliotjordan Is this still broken?

**Comment by eliotjordan** [comment]
@tpendragon It is. I should specify, that these are Princeton users logged into Pulmap, but without an account of Figgy.

**Comment by escowles** [comment]
Maybe Pulmap could use the access token like audio reserves?

**Comment by tpendragon** [comment]
Fixing #2395 means we can just give them the download link in the maps portal and CAS will take care of it.
