### ISSUE TITLE
Update ARK metadata for maps so their ARKs point to Pulmap instead of the Catalog

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2443]

**Comment by escowles** [comment]
https://github.com/pulibrary/figgy/blob/master/app/services/identifier_service.rb#L47

**Comment by hackmastera** [comment]
may be closed by #2441

Here's one that is incorrect as of right now: https://figgy.princeton.edu/catalog/5ec95d7a-0df7-4997-9ec3-28a20e9f377d

**Comment by eliotjordan** [comment]
Sorry. Just refreshed the metadata on that example ^ and now the ARK points to the correct URL. Here's another example: https://figgy.princeton.edu/catalog/92bd05c8-0dca-40d5-95ff-1509d242ee7f

Refreshing the Voyager metadata does fix the problem, BTW.

**Comment by tpendragon** [comment]
Closing #2441 didn't close this because it only updates the ARK metadata if the state, source metadata identifier, or title changes. We'll have to do this as a separate process.

**Comment by eliotjordan** [comment]
Update ARK metadata for all scanned maps and vector resources. URLs should be pointing the Pulmap now.
