### ISSUE TITLE
Improve User Feedback on Ingest Status

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2447]
Lots of questions on All-Hands 1/19 about when things are done, if they're done, and background processing that might be happening.

**Comment by hackmastera** [comment]
potentially related to or duplicate of #638

**Comment by tpendragon** [comment]
I think this is solved if FileSets know if they're done or not?

**Comment by escowles** [comment]
I think a ScannedResource would also need to know if its FileSets are done, and a MVW would need to know if its volumes are done.

**Comment by tpendragon** [comment]
Yeah, I think that's handled by "a parent isn't processed if its children aren't"

**Comment by escowles** [comment]
👍 that sounds reasonable to me.
