### ISSUE TITLE
New Record Templates/Dashboard

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2448]
Currently, studio staff have to know what object type to create objects in, and what collections/etc. to set for scanned resources.  I talked with @kelea99 about making the slip that accompanies items more detailed to include this information.

But I think we could create new record templates, where you would select all of those settings to configure object type, collections, visibility, etc.  And then we could have a dashboard that would list the current projects, with a button you could click for each one that would create the correct object type with those things pre-populated.

**Comment by kelea99** [comment]
I will also be adding this as an agenda item for DPSG mtg. this month, @escowles, to discuss the best ways to get desired collections/other information in hand in order to populate the possible templates/slips before the physical items get to the studio.
