### ISSUE TITLE
Links with time-expiring tokens

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2459]
Would like to be able to give users download links that will only work for a specified period of time to access & download private items.

**Comment by tpendragon** [comment]
To download PDFs of private items yes?

**Comment by escowles** [comment]
Yes, PDFs of private items is the main fulfillment scenario where single-use links would be useful.

**Comment by hackmastera** [comment]
Recent meeting with ADAPT+ suggests that a token that is set to expire on a specific date would be more useful than a single-use link. Updating title and description.
