### ISSUE TITLE
Document fulfilment functionality

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2460]
All-hands feedback from RBSC staff who will be staging items for private reading room viewing: would like documentation of fulfillment functionality:
* Known-item search (searching by ids/title)
* Downloading PDF and/or TIFF page images

**Comment by escowles** [comment]
I've drafted an overview of search and download functionality in Figgy: https://docs.google.com/document/d/1J1FAhUbwPHebdxlNMbF3KtSmQ-x-l6Xut4WtdTq-jSY/edit

**Comment by hackmastera** [comment]
I read over it a few days back and it looked good to me. It might be good to have a user / expert read it?

**Comment by escowles** [comment]
👍 I talked to Faith about this yesterday, and she'll ask Squirrel and Christa to look at them and give feedback.

**Comment by escowles** [comment]
I haven't heard anything either way, but I've directed several people at these docs and I'm going to close this ticket.  We can create additional doc tickets if people report problems with those docs or ask for new docs.
