### ISSUE TITLE
Support Text Reserve Materials?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2476]
* Should we use Figgy to generate and/or serve text reserve materials? (scanned or born-digital articles, book chapters, etc.)
* Would it be useful to store text reserve materials in Figgy for later re-use?
* What would we need to do to support that? #2140? Anything else?

**Comment by tpendragon** [comment]
@escowles Was this a user request?

**Comment by escowles** [comment]
Closed by https://github.com/pulibrary/figgy/pull/3138
