### ISSUE TITLE
Add "refresh metadata" button to collections

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2490]
Button should trigger source metadata refresh for all child objects with imported metadata.

part of this work should be removing everything that was needed for the nightly refresh, implemented in https://github.com/pulibrary/figgy/pull/2347/files, since this functionality replaces that.

Ultimately, using this button requires #2489

**Comment by tpendragon** [comment]
Collections can have imported metadata now, so we may need to call this button something like "Refresh All Child Metadata"? Although it looks like we're back in the zone of wanting to automatically update finding aid metadata.

**Comment by tpendragon** [comment]
We're auto-refreshing everything now, not needed.
