### ISSUE TITLE
Collection owner report should not error if there are owners associated that are not currently in the database

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2492]
## Backtrace

    line 5 of [PROJECT_ROOT]/app/mailers/collections_mailer.rb: block in owner_report
    line 5 of [PROJECT_ROOT]/app/mailers/collections_mailer.rb: map
    line 5 of [PROJECT_ROOT]/app/mailers/collections_mailer.rb: owner_report

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/44956779)

**Comment by escowles** [comment]
If there are bad userids in the collection owner field, we should skip them and send the rest of the reports.

**Comment by escowles** [comment]
Sending a HoneyBadger error so we know we need to fix the data would also be good.
