### ISSUE TITLE
Make all graphics arts collections have pdf_type color

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2496]

**Comment by escowles** [comment]
https://figgy.princeton.edu/catalog/c22ec699-33eb-4687-8989-f773acf7ea59
https://figgy.princeton.edu/catalog/cb39a516-a2f5-4cda-b14d-057462d9da96
https://figgy.princeton.edu/catalog/8c1d66c5-9113-473b-bf3e-09f8481a786b
https://figgy.princeton.edu/catalog/b80f8d41-3be5-440e-8bdb-eff6489f3088
https://figgy.princeton.edu/catalog/1958402e-3ffd-4de0-bff8-063ae10d2409
