### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2497]
## Backtrace

    line 427 of [PROJECT_ROOT]/app/services/manifest_builder.rb: download_url
    line 434 of [PROJECT_ROOT]/app/services/manifest_builder.rb: display_content
    line 8 of [PROJECT_ROOT]/app/services/manifest_builder/record_property_builder_v3.rb: apply

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/44994727)

**Comment by christinach** [comment]
also https://app.honeybadger.io/projects/53391/faults/45500931
