### ISSUE TITLE
Additional views of scrolls (the container) have been lost 

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/figgy#2501]
Two objects from PUDL had as their thumbnail image the container.  The object was just the whole scroll image.  That was an arrangement for PUDL, but we really need to regularize this for DPUL.  The images of the containers have been lost.  These are the two objects:

https://catalog.princeton.edu/catalog/10639166
https://catalog.princeton.edu/catalog/10638008

**Comment by escowles** [comment]
@joycebcat I've uploaded the other images that we had for those items in PUDL:

* https://figgy.princeton.edu/catalog/61a439a0-eab9-4067-9b09-3f91f0bf8e47
* https://figgy.princeton.edu/catalog/d0d1e27c-4060-44d4-b912-75b6f0f980ff

**Comment by tpendragon** [comment]
I set those images as the thumbnail, and closing these.
