### ISSUE TITLE
Visibility note for geo materials is incorrect

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2506]
Scanned maps, vector resources, and raster resources are all indexed into Pulmap no matter what visibility value is chosen. Visibility just influences whether previews and downloads are available to users.

<img width="1141" alt="screenshot 2019-01-30 23 35 53" src="https://user-images.githubusercontent.com/784196/52032754-f5b78080-24e7-11e9-906a-368c69dce11e.png">

**Comment by escowles** [comment]
@eliotjordan Do you think we should just remove "Maps Portal" from the note, or do you think it would be better to remove the note entirely from the Geo resources?

**Comment by eliotjordan** [comment]
I'm not sure. I think removing it entirely is the easiest option. Alternatively, the note would need to be customizable by resource type.

**Comment by tpendragon** [comment]
@eliotjordan Review please.
