### ISSUE TITLE
Problem reordering volumes

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2540]
Willow Dressel reported a problem reordering volumes of this item: https://figgy.princeton.edu/catalog/d96c5114-3c0b-4c2a-af88-83182450ee74

This item was created, and then a new volume was added, but when she tried to move the newly-added item to the correct position, the order manager did not show any volumes.

**Comment by tpendragon** [comment]
Caused by https://app.honeybadger.io/projects/53391/faults/44857510#notice-comments

**Comment by tpendragon** [comment]
My guess is that the graphql is erroring if it doesn't have a thumbnail?

**Comment by tpendragon** [comment]
Confirmed it's fixed now.
