### ISSUE TITLE
Unable to ingest the following LAE barcode: 32101086454848

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2547]
It throws solr errors when it tries.

**Comment by tpendragon** [comment]
The files are on the PUDL share in `lae_to_ingest`

**Comment by tpendragon** [comment]
The error comes from the rake task `lae:ingest_disk_files`. The error's probably lost, but it was throwing a solr error that may be in honeybadger somewhere?

**Comment by hackmastera** [comment]
no real clues here in honeybadger, datadog, or sidekiq dead jobs list. i'll work on trying to replicate locally.

**Comment by hackmastera** [comment]
here's the solr error (400 bad request) https://app.honeybadger.io/projects/53391/faults/39543223#notice-trace

**Comment by hackmastera** [comment]
the error is cut off in honeybadger. here it is in datadog logs https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&context_event=AAAAAWkGfUD6oo65kwAAAABBV2tHZlVFT1pGSkxENDAxbFBsVg&event&from_ts=1550591913700&index=main&live=false&messageDisplay=inline&query=host%3Alib-proc6++++++service%3Afiggy++++++filename%3Aproduction.log+++++-CheckFixityJob+-CheckFixityRecursiveJob+-CharacterizationJob+-BrowseEverythingIngestJob+-CreateDerivativesJob&saved_view&stream_sort=desc&to_ts=1550592145829

**Comment by hackmastera** [comment]
can't find any clues in the error log. maybe i'll try reindexing just the resources; perhaps I can bisect to a problem record.

**Comment by hackmastera** [comment]
same error when reindexing all the folders.  also still get `Failed to find the resource ab8236da-b222-4d4f-aedb-555456d10401` maybe that is related; will look into that and if I can't figure anything out from there will try bisecting.

**Comment by hackmastera** [comment]
the problem record is https://figgy.princeton.edu/catalog/14b354c2-5a03-4a84-823a-66a3a3fee7aa

**Comment by hackmastera** [comment]
the id that couldn't be found corresponds to a subject entry

**Comment by hackmastera** [comment]
I resolved the record and sidekiq is in the midst of re-running the job right now.  I don't think it has made it to this record yet, but I'm not sure if it's holding a version of the resource from before I made the correction. I'll keep an eye on it and if it fails again I'll kill the job, fix the record, and start the task again.

**Comment by tpendragon** [comment]
Looks like it worked. It's just generating derivatives now.
