### ISSUE TITLE
Reindex everything

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2549]
Now that #2541  is merged, we should reindex everything to make sure all of the updated metadata indexing is applied to all resources.

**Comment by escowles** [comment]
Needed to completely fix #383

**Comment by hackmastera** [comment]
depends on #2830

**Comment by tampakis** [comment]
In progress. Zube sent me an e-mail that this was assigned to me. Pretty cool!

**Comment by tampakis** [comment]
Done!
