### ISSUE TITLE
Propose cloud storage strategy

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2556]
Child of #1551
Blocks #912

Create a proposal for cloud storage preservation, and get agreement from stakeholders and finance.

**Comment by tpendragon** [comment]
This seemed the most reasonable place to put this, and I don't want it to just come up as a surprise:

I think bags as a preservation strategy have a few problems.

1. They're a moderately expensive format to write.
2. They don't handle nested structures well. For instance, storing a "collection" brings up a host of questions, and if we ever change our mind regarding multiple parents our entire preservation structure is going to need regenerated.
3. Storing the metadata as effectively a derivative means we'll have to regenerate all our bags (at significant cost and effort) every time we make a change to our metadata schema, just to ensure that it can reload.

I guess I want to know what the goal of preservation for us is. Is it "backup"? If so, I think the following is more easily maintained and we'd have a higher confidence in its implementation:

1. Change our disk storage utility to store files and derivatives all in the same directory.
2. MAYBE change our disk storage utility to store files and derivatives in a directory named after the containing resource (this would mean we're making a hard commitment to either not have multiple parents, or do it via ProxyFileSets like we did for Reserves, which I think is quite nice.)
3. RSync (or equivalent) those folders to cloud storage. If we ever move Figgy to the cloud, then we can even have a special bucket with auto-backup for things we really want preserved.
4. Back up the postgres database periodically, store those in the cloud. (We already do the first half of this.)

The only reason I can think of that the latter wouldn't be better is if we really feel strongly that we need to be able to look at the file system, by itself, and say "oh yeah that's page 6 of volume 1 of Bible, Latin", and ship that representation off to someone else. That doesn't seem important to me for preservation, but I may be wrong?

**Comment by escowles** [comment]
I think don't think storing a postgres dump and/or copy of the storage directory addresses the same use cases as well.   By far the most common restore scenario is restoring individual objects because of accidental deletion, and having them individually packaged makes this much easier than whole-repo archives.  You mention storing files and derivatives in a single directory, but, IMHO, that's essentially recreating the Bag.

Bags in particular have other advantages, mostly that our stakeholders know and trust them, that they have an established mechanism for storing checksums for all the files, and that they are easy to validate (either with Bag-specific software, or with common utilities like md5sum/shasum).

**Comment by escowles** [comment]
Multiple parents and changing metadata schema both seem like solvable problems to me.  

* I think we can just say that we don't allow multiple parents, or only allow it via proxies so every item has one "real" parent that's used for preservation.

* I think it makes sense to think about all the possible scenarios for metadata restore, and other uses of the Bags, and decide what makes the most sense for including metadata.  We may decide that it makes more sense to store MARC/EAD XML metadata, or we may decide that we should update all the metadata files every time we change our schema (if we can do that without touching unchanged master files, I don't think that needs to be expensive).

**Comment by tpendragon** [comment]
> You mention storing files and derivatives in a single directory, but, IMHO, that's essentially recreating the Bag.

I disagree. The big difference being the tag files and nested objects not needing to be a concern.

> By far the most common restore scenario is restoring individual objects because of accidental deletion, and having them individually packaged makes this much easier than whole-repo archives.

Only if it works. I'm really concerned that we're trusting an exporter/importer for important recovery use cases, when it would be more reliable to decrease the delta between what we're backing up and what we're actually using.

**Comment by escowles** [comment]
I think it's worth thinking about whether we should change our Bag format to be closer to our live data.  For example, maybe the bag `data` directory should have two directories:
1. `files`: a `Valkyrie::Storage::Disk` data store for the files in the object
2. `metadata`: a files-on-disk metadata adapter, which would have the same limitations as the current Bag metadata adapter

Then the Bag-specific tooling would have much less to do with the workings of Figgy and just treat the data directory as a bunch of files.  Figgy wouldn't need to know nearly as much about the Bag format.

**Comment by tpendragon** [comment]
You don't have any concern that it's another moving part just waiting to break?

**Comment by escowles** [comment]
No — on write, Bags are basically just writing files to a directory, calculating checksums, and writing some metadata files — none of that seems risky to me.  On read, it seems even less likely to break, since you can just ignore the Bag stuff and use the data directory by itself.

The other piece of new software would be a metadata adapter for storing metadata as files on disk.  That doesn't seem particularly different from the memory adapter, except for some disk I/O.

**Comment by tpendragon** [comment]
It seems to me like exporting rather than backing up means we're trusting our own tooling over actual data tooling. We have to rely on things like jobs completing, our software working, retries working as expected, handling sync problems, updating without losing data, etc. I'm worried it's overly complex with little benefit.

**Comment by tpendragon** [comment]
There is a medium ground here. We could make "preservation" mean "bags are archived in Glacier" and "Original files are on S3." Then we can configure the S3 bucket for "preservation-necessary" items to have versioning and multi-region duplication. That way if someone deletes something we can go get it. We can also dump the nightly postgres backups in that bucket (if it's not super huge..)

**Comment by tpendragon** [comment]
One problem that's going to be a problem no matter what we do is that Glacier doesn't play super nice with a bunch of small files. From what I was reading it sort of expects you to tar up your resources and put them up all at once, since you have to request each individual file you want when you get them back out.

That accurate from your experience @eliotjordan & @hackmastera ?

**Comment by eliotjordan** [comment]
Dealing with lots of small files in Glacier would definitely be a painful.

**Comment by hackmastera** [comment]
I think we're looking to ensure both a preservation strategy and a backup routine. Here are some use cases; we can argue or clarify at the upcoming meeting:

Backups: all data at a series of points-in-time. Recoverable as a full set to a newly-built environment.

1. e.g. hardware failure / malicious corruption, full restore needed
2. e.g. user error; restore to another box and export / import discrete objects

Preservation: all data at its desired / final state. Recoverable as above, but also 

1. preservation practices protect against bit rot
2. preservation data is human readable / usable natively on disk without the software that created it
    1. I think to a large extent this is tied to the problem of obsolete file formats. Is it possible this is a concern outside figgy's purview?

**Comment by escowles** [comment]
Yes, I think Anna calls out two important things we're trying to address with preservation:
1. Bitrot — any kind of corruption that might go unnoticed for a long time (which is likely given how infrequently we use the master files)
2. Restoration of the content without requiring the software — making the preservation copies more robust by being usable with the simplest tooling

I think handling obsolete formats is a different concern — and since we have a significant amount of control over our preservation masters, not a huge concern for us (though it will be a bigger concern when we start doing video).  We'll need to be able to replace all the preservation copies if we migrate to a new video container or codec, for example.

**Comment by tpendragon** [comment]
> 1. Bitrot — any kind of corruption that might go unnoticed for a long time (which is likely given how infrequently we use the master files)

I think any backup strategy has to solve for this, and the above does.

> 2. Restoration of the content without requiring the software — making the preservation copies more robust by being usable with the simplest tooling

Okay. This seems reasonable I guess. I'm concerned that bags solve this use case at the expense of reliable trustable backup. I have a really, really hard time trusting the results of a transformation over an rsync. If I'm the only one though, then I'll drop it.

**Comment by escowles** [comment]
@tpendragon it's definitely not just you — I agree that a database/filesystem backup will be more reliable (and perform better).  I think we should do those too.

**Comment by kayiwa** [comment]
worth adding that we will be using continuous archiving *in addition* to `pg_dump`ing once we move to a cloud setup. 
https://www.postgresql.org/docs/10.1/continuous-archiving.html

**Comment by hackmastera** [comment]
Yes, I don't think we're looking for a solution that does both backup and preservation. I think we'll need 2 sets of strategies. Currently we have pg backups and isilon snapshots, and no real preservation process.

**Comment by escowles** [comment]
Feedback from stakeholders was tentatively in support of not doing full-scale fixing checking of all content, and using multiple storage providers as a hedge against any vendor lock-in.  Decisions documented in team drive: https://docs.google.com/document/d/17X-kmhL417I0DaqZuYamxhf5DrRRQnAy5ue9X9ryXZg/edit#
