### ISSUE TITLE
Display accession info in Coin form

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#2574]
In the current numismatics database, an accession note displays as "Gift of: Antioch Excavation, Princeton, 1/1/1939"

This is a concatenation of values found in the firm and accession table. The forms don't currently support this. For now we are using the "Accession ID" value to insert the full note in free text.

**Comment by tampakis** [comment]
Child of #2002

**Comment by christinach** [comment]
[coin-accession-firm-xslsx.xlsx](https://github.com/pulibrary/figgy/files/2963823/coin-accession-firm-xslsx.xlsx)

**Comment by christinach** [comment]
In the file `firm_note` is the `firms.firmname+' '+ firms.firmcity+' ,'+ coins.finddate`
[join-coin-accession-firm.xlsx](https://github.com/pulibrary/figgy/files/2964143/join-coin-accession-firm.xlsx)
