### ISSUE TITLE
Refuse to update PULFA ARKs, but don't error

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2595]
We currently raise an exception when refusing to update PULFA ARKs:

https://github.com/pulibrary/figgy/blob/master/app/services/identifier_service.rb#L28

But we should notify the user that the ARK won't be updated, but still allow saving and other actions to work.

**Comment by tpendragon** [comment]
Didn't https://github.com/pulibrary/figgy/pull/2585 close this?

**Comment by escowles** [comment]
@tpendragon No — #2585 handled the exception so the user gets an appropriate error message.  But this ticket is to make the update succeed instead of failing.  We need to be able to edit and complete records with findingaids ARKs, so the object can be shown in PULFA and DPUL.

**Comment by tpendragon** [comment]
Instead of notifying them, maybe we should just silently create a new ark and put it in identifier?

**Comment by escowles** [comment]
I think it's fine to have the old ARK — they want them to point to PULFA, and have PULFA embed the Figgy digital object.

**Comment by tpendragon** [comment]
That's not what we've done in the past though. Usually the object ends up with two arks. We can start doing that I guess? As long as we don't change our minds, that ark is used as the key for DPUL.
