### ISSUE TITLE
Test Preservation

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2601]
~~Blocked by #2556~~
~~Blocked by #2772~~
~~Blocked by #2773~~
Child of #1876 

- [x] Verify that content is Preserved as expected
- [x] Verify that content is checked as expected
- [x] Intentionally corrupt an object in cloud storage
- [x] Verify that fixity checking discovers and reports the corruption

**Comment by tpendragon** [comment]
I've corrupted the fixity for the binary file attached to https://figgy.princeton.edu/catalog/48bfc589-7556-42b6-96c8-54a001ed73a1. I changed it from `980b3a70d05f3104c7cb30732f2958db` to `980b3a70d05f3104c7cb30732f2958dc`

**Comment by tpendragon** [comment]
Our billing as of this moment looks like this:
```
Class A Requests (Coldline): 2.59
Class B Requests (Coldline): 1.94
Coldline Data Retrieval: $0.06
CPU Time (Cloud Functions): $0.00
Inter-Region data delivery (pubsub): $0.0.00
Internet Data Delivery from Americas to Americas (pubsub): $0.00
Intra-Region Data Delivery (pubsub): $0.00
Invocations (Cloud Functions): $0.00
Memory Time (Cloud Functions): $0.00
Message Delivery Basic: $0.00
Subscriptions Message Backlog: $0.00
Subscriptions Retained Acknowledged Messages: $0.00
```

I'm going to queue up fixity checking now. This will be checking 127,105 objects representing 10.67 TB of data in Google Coldline. Expected cost is $700.

**Comment by tpendragon** [comment]
They've all been queued up now.

**Comment by tpendragon** [comment]
They all started failing: `"Error: quota exceeded (Quota exceeded for quota group 'NetworkIngress' and limit 'CLIENT_PROJECT-100s' of service 'cloudfunctions.googleapis.com' for consumer 'project_number:639448642333'.); check and increase your quota at https://console.cloud.google.com/iam-admin/quotas?project=pulibrary-figgy-storage-1&service=cloudfunctions.googleapis.com&usage=ALL. Function cannot be executed.`

I've requested an increased quota and killed the old subscription, hopefully that stops the functions running.

**Comment by tpendragon** [comment]
The functions are done running now. `11,049` events were processed in that time.

**Comment by tpendragon** [comment]
Functions are running now with a maximum concurrency number of 100 functions at a time, no quota issues.

**Comment by tpendragon** [comment]
It happens very rarely, but the google storage download checks to make sure the file downloads correctly and sometimes it doesn't:

```
Error: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again. at onComplete (/srv/node_modules/@google-cloud/storage/build/src/file.js:930:43) at ServiceObject.request.call (/srv/node_modules/@google-cloud/common/build/src/service-object.js:186:13) at Util.handleResp (/srv/node_modules/@google-cloud/common/build/src/util.js:142:9) at retryRequest (/srv/node_modules/@google-cloud/common/build/src/util.js:423:22) at onResponse (/srv/node_modules/retry-request/index.js:200:7) at /srv/node_modules/teeny-request/build/src/index.js:222:13 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by tpendragon** [comment]
They're all done. Finished at 8:09 PM PST, and successfully found the corrupted file.

**Comment by tpendragon** [comment]
Billing didn't post today. I'll close this ticket when I have numbers.
