### ISSUE TITLE
delete any subject field entry with value ab8236da-b222-4d4f-aedb-555456d10401

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2604]
this term has been deleted and reindexing errors if it comes up.

**Comment by escowles** [comment]
I think this is a special case of one of the oldest Figgy tickets: https://github.com/pulibrary/figgy/issues/241

**Comment by hackmastera** [comment]
@escowles this one is to clean up after the one specific deletion. I think https://github.com/pulibrary/figgy/issues/2603 is the special case.

**Comment by hackmastera** [comment]
oh i see what you mean. yeah this is a manifestation of that ticket.

**Comment by hackmastera** [comment]
3 ephemera folders will need to be updated manually by a metadata expert. 2 of them had only this one subject, and a subject is required by the form. the other lacks a different required field, the folder number:

- [ ] https://figgy.princeton.edu/catalog/7fa1ce90-032b-4209-a3c7-4d50330f685e
- [ ] https://figgy.princeton.edu/catalog/3eecb0d5-6681-44a5-bf5c-12d2da1826e5
- [ ] https://figgy.princeton.edu/catalog/5e988ed6-7108-4870-a77d-a83f86b43427
