### ISSUE TITLE
For AV materials, the UV title should be the title of the playlist in addition to the track

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2608]

**Comment by tpendragon** [comment]
![screen shot 2019-02-19 at 3 25 34 pm](https://user-images.githubusercontent.com/2806645/53054851-9f8c8c00-345a-11e9-81c1-e77b0c88e5d5.png)

Dan would like the top to say "The Wiz : Original Soundtrack"

**Comment by escowles** [comment]
This seems like the same issue as https://github.com/pulibrary/orangelight/issues/1283 — when we have multi-part manifests, we'd like the viewer title to be the top-level (collection) title, not the volume/track/part/etc. title.

**Comment by tpendragon** [comment]
Similar, but MVWs do that because it's a collection and the top level just loads the lower level. AV is just a manifest and it does that just because.
