### ISSUE TITLE
Create base query class?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2610]
There is a lot of boilerplate for custom query classes — defining accessors, creating a method named after the class to run a query, and adding that method to the list of available queries.  Could we create a base class that did all of that, and individual query implementations could just define the SQL?

**Comment by tpendragon** [comment]
This might be hard, the queries are quite different sometimes. Would need a spike to see if it feels easier.

**Comment by tpendragon** [comment]
Our team says we're not sure this would help, so we're going to close it rather than let it languish in the icebox.
