### ISSUE TITLE
Users should be able to mark a resource as non-downloadable

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2628]
This will let them see the synced resource and go through the viewer, but not download a PDF, images, or anything else. Should disable the download frame in UV.

**Comment by escowles** [comment]
I think it would be good to implement this like the PDF controls: with a property that controls the allowable download options.  So far we know about two options (original file+full-res JPEG, no download), but it should be easy to add other options (e.g., grayscale only).

**Comment by jrgriffiniii** [comment]
Attempting to disable downloads completely for images in the Universal Viewer (following the strategy in https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder/record_property_builder_v3.rb#L11) has resulted in the following error:

<img width="1119" alt="figgy-issues-2628-screenshot-0" src="https://user-images.githubusercontent.com/1443986/54233562-92a40b00-44e3-11e9-8aeb-7496f4691433.png">

Please note that this was the case after ensuring that only IIIF V3 Presentation API manifests are now generated for images: https://github.com/pulibrary/figgy/compare/issues-2628-jrgriffiniii-mark-non-download#diff-55f651679ae90d845871424d7d4e9bd3R630
