### ISSUE TITLE
Permanent URLs for collection and item manifests

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2631]
* Collection manifests should use the URLs based on ARKs, e.g., https://figgy.princeton.edu/iiif/lookup/ark:/88435/p2677017n instead of the URLs that use Figgy IDs
* There should be a lookup function for collection manifests, either by assigning them ARKs or something similar

**Comment by jpstroop** [comment]
Also, these URLs should be exposed in the UI and it should be clear that this is what should be used in citations.

**Comment by escowles** [comment]
Currently, the URLs for the manifests show up in DPUL only as a IIIF drag-and-drop icon just below the viewer (and not at all in Figgy or other apps). But "these URLs should be exposed in the UI and it should be clear that this is what should be used in citations" sounds like the actual URL should be displayed as a metadata field, and/or in the metadata drawer, with a label like "Permanent Manifest URL" or something like that.

**Comment by jpstroop** [comment]
⬆️ yes, that
