### ISSUE TITLE
Fileset cannot generate derivatives because it's being characterized as `text/plain`

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2632]
deleting the fileset and uploading the image again does not fix the problem.
fileset: https://figgy.princeton.edu/catalog/6d4398b1-6bc5-4f6a-a46a-8bebc5c56b95
parent: https://figgy.princeton.edu/catalog/78ef7db6-27ca-44f5-b74d-6f3ebff11574

**Comment by tpendragon** [comment]
@hackmastera How'd you reupload it?

**Comment by tpendragon** [comment]
When I reupload that image into a new fileset it works: https://figgy.princeton.edu/catalog/parent/1669388e-10dd-4fa8-b8c0-842f688de94a/20647baa-1975-44b2-9561-8a4893fe1e5c

**Comment by tpendragon** [comment]
Fixed this manually, we'll have to keep an eye on if this happens again.
