### ISSUE TITLE
Check for file sets with mime_type "text/plain"

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2634]
see https://github.com/pulibrary/figgy/issues/2632 for background. are there any more files like that, that didn't get characterized?

**Comment by tpendragon** [comment]
There are 26.

**Comment by tpendragon** [comment]
Earliest one was updated on August 14 2018, latest was today.

**Comment by tpendragon** [comment]
I couldn't find logs relating to any of them. For now I re-characterized them all. We'll just have to keep an eye out I guess.

**Comment by tpendragon** [comment]
For reference, this is how I queried for them:

```ruby
output = change_set_persister.query_service.custom_queries.find_by_property(property: :file_metadata, value: [{mime_type: ["text/plain"]}])
```
