### ISSUE TITLE
Bulk Edit should not complete items in takedown state

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2635]
Users can work around this by faceting on state to select only items of one particular state (e.g., pending).  But we wouldn't want a bulk complete action to accidentally restore access to items marked takedown.

**Comment by hackmastera** [comment]
Hm. Would this be a valid state transition? I think maybe the state machine would not allow it, and the bulk edit logic would throw an error if the change set is not valid.

**Comment by hackmastera** [comment]
oh, just checked, it is a valid transition.
