### ISSUE TITLE
[Figgy/production] MiniMagick::Error: cache resources exhausted

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2637]
## Backtrace

    line 165 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: cleaned_file
    line 156 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: clean_filename
    line 88 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: rescue in run_tiff_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/45430091)

**Comment by hackmastera** [comment]
similar error in https://app.honeybadger.io/projects/53391/faults/44765967#notice-summary
