### ISSUE TITLE
Bad tiff

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2642]
[Figgy/production] PDFGenerator::Error: PDFGenerator::Error

## Backtrace

    line 38 of [PROJECT_ROOT]/app/services/pdf_generator.rb: rescue in render
    line 15 of [PROJECT_ROOT]/app/services/pdf_generator.rb: render
    line 70 of [PROJECT_ROOT]/app/resources/scanned_resources/scanned_resources_controller.rb: pdf

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/44396418)

**Comment by hackmastera** [comment]
@roelmoon I think this is a bad file. If you look at the file set page you will see the error: https://figgy.princeton.edu/catalog/parent/75de99fe-aeb1-4c62-b3ec-15454d696b21/a32f1592-b957-435d-a946-e95249f5f6b1

When I download my system will not open it. Could you take a look?

**Comment by jrgriffiniii** [comment]
As https://app.honeybadger.io/projects/53391/faults/44396418#notice-summary does not indicate that this has occurred in six months, and given that there have been no updates to this issue, I'm going to proceed with closing this.

**Comment by jrgriffiniii** [comment]
Apologies, I was not aware of the `Follow Up` ZenHub column; I will reopen this and add this issue into the column.

**Comment by tpendragon** [comment]
This was image 9 and it's been reuploaded.
