### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `members_with_parents' for #<NumismaticMonogramWayfinder:0x00007f43ad18fb80>

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2645]
## Backtrace

    line 104 of [PROJECT_ROOT]/app/controllers/concerns/resource_controller.rb: file_manager

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/44380514)

**Comment by christinach** [comment]
related to #2583

**Comment by eliotjordan** [comment]
Closed by #2668
