### ISSUE TITLE
Ephemera maps

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2670]
New use case: an ephemera item is also a scanned map, and should be included in Pulmap.  Maybe the item should just be a scanned map and included in the ephemera DPUL collection (see #2669)?

**Comment by hackmastera** [comment]
Seems like a good one to consider in the context of this discussion https://github.com/pulibrary/figgy/issues/2623

**Comment by tpendragon** [comment]
We're going to close this as nobody's asked us recently and we don't know of an actual physical map that has this use case. Can you reopen this if you have more info @escowles ?
