### ISSUE TITLE
Create a new Google OAuth project

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2671]
Figgy currently uses Google OAuth in order to provide access to Google Drive for file uploads (using Browse Everything).  This needs to be available to all developers.

**Comment by jrgriffiniii** [comment]
I'll need to investigate whether or not this is affected by https://developers.google.com/+/api-shutdown, but I have not received any notifications that the OAuth settings for this need to be updated.

**Comment by jrgriffiniii** [comment]
The OAuth settings used for Google Drive access do *not* to be updated for Figgy in the production or staging environments in response to the Google+ API shutdown.

**Comment by tpendragon** [comment]
@jrgriffiniii Can you clarify what needs to be done here and why and categorize appropriately if possible?
