### ISSUE TITLE
Transcripts and/or corrected OCR

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2705]
We should add support for human-edited transcripts or corrected OCR.  These differ from machine-generated OCR because they should not be overwritten by automatic processes.

**Comment by escowles** [comment]
One question I have is about transcripts (which would not typically have coordinates) — can we use them for IIIF search-within?

**Comment by tpendragon** [comment]
We can use them for search-within and just not provide coordinates, yeah.

**Comment by escowles** [comment]
@tventimi mentioned a contact at Harvard who may be a source of higher-quality text extraction for our Chinese manuscripts.

**Comment by tpendragon** [comment]
This ticket is not actionable. We need content with a transcript that needs ingested and supported.
