### ISSUE TITLE
Server-powered typeahead for relations on Numismatic resource forms

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#2715]
Lookup values instead of pre-loading all of them, because that's really slow.

**Comment by eliotjordan** [comment]
- Query solr based on form input
- Can we leverage Blacklight suggest component and twitter typeahead?
- Start with Numismatic Place

**Comment by tampakis** [comment]
- Make sure that we have a stored + indexed label/title field in the numismatic place solr document (for now testing with city field). Make sure this field is compatible with the "suggest" field type.
 - We want to support multiple suggester components, one suggester per autocomplete field.
 - There is a payload parameter that we will use to get the id value to be used in the edit form.
