### ISSUE TITLE
Default thumbnail on error in search results should either be smaller or not be there at all

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2717]
Requested by Dan

**Comment by tpendragon** [comment]
It might be nice to have a like..."summary" view? Something which is just a bunch of titles and some minimal metadata, no images.

**Comment by escowles** [comment]
Is this a different search results view, or a new kind of report (e.g., for downloading to a spreadsheet)?

**Comment by tpendragon** [comment]
Different search results view. Dan doesn't want to see the thumbnails, and it seems easier to just have a view that doesn't show those
