### ISSUE TITLE
[Figgy/production] NameError: uninitialized constant NewChangeSet

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2722]
## Backtrace

    line 12 of [PROJECT_ROOT]/app/change_sets/dynamic_change_set.rb: class_from_param
    line 26 of [PROJECT_ROOT]/app/resources/scanned_resources/scanned_resources_controller.rb: change_set_class
    line 109 of [PROJECT_ROOT]/app/resources/scanned_resources/scanned_resources_controller.rb: ingest_folder

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/46908296)

**Comment by escowles** [comment]
Looks like this is causing it: https://github.com/pulibrary/figgy/blob/f442fb4da76ef36f89a6ea5369019002ee55eba0/app/assets/javascripts/save_and_ingest_handler.es6#L13

**Comment by escowles** [comment]
Fixed by #2723

**Comment by christinach** [comment]
most recent https://app.honeybadger.io/projects/53391/faults/46908296
`NameError: uninitialized constant ScannedResourcesChangeSet`
