### ISSUE TITLE
Move numismatic artist from coin to issue

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2729]
According to the current database.

**Comment by christinach** [comment]
@eliotjordan I renamed the issue title since the artist is on the numismatic issue.

**Comment by eliotjordan** [comment]
@christinach I renamed it again. I should have been more specific. The nested numismatic artist field should be on issue, not on coin.

**Comment by christinach** [comment]
are you talking about this https://github.com/pulibrary/figgy/blob/34ec30a8669a535fbe645e808a784dc8b8efed14/app/resources/numismatic_issues/numismatic_issue.rb#L10

**Comment by eliotjordan** [comment]
The artist form element should be on the issue show page rather than the coin show page. 

Steps: 

[ ] - Add the artists form element to numismatic_issue.
[ ] - Remove the artists form element from coin.
[ ] - Remove `numismatic_artist_ids` attribute from coin.

**Comment by christinach** [comment]
The artist should be in the numismatic issue https://github.com/pulibrary/figgy/pull/2712/files

**Comment by eliotjordan** [comment]
This was my error. I was looking at an old version of Figgy deployed to staging.
