### ISSUE TITLE
ActionDispatch::TestProcess shouldn't be global in scope

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#275]
This was discovered by @hackmastera , noting that `WARNING: It appears you may be including ActionDispatch::TestProcess globally. Check out https://www.honeybadger.io/s/adtp for more info.` is logged as a warning when running the test suites.

**Comment by escowles** [comment]
Not sure what test is causing this — I tried to debug this as part of #371 , but when I run each directory of test individually, none of them triggers this warning.  There are ~25 test files that include ActionDispatch::TestProcess, but running individual test files doesn't trigger the error, either.

**Comment by hackmastera** [comment]
I thought I might take a look.

**Comment by hackmastera** [comment]
I tried to isolate this to the problem spec, but now I'm not even getting the warning anymore. closing.
