### ISSUE TITLE
RegenerateDerivativesJob errors

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2750]
This is a problem because we changed the interface for DerivativeJobs, but not the gem.

## Backtrace

    line 11 of [PROJECT_ROOT]/app/derivative_services/default_derivative_service.rb: new
    line 8 of [PROJECT_ROOT]/app/jobs/regenerate_derivatives_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/46628336)

**Comment by jrgriffiniii** [comment]
Might this have simply been a result of the changes in https://github.com/pulibrary/figgy/commit/f09408d5b44a63903275c4e3a1ce678c4ec8a448, and users were not using the feature from this update onwards?

**Comment by tpendragon** [comment]
Yeah, that's in the post.
