### ISSUE TITLE
[Figgy/staging] ActionView::Template::Error: can't convert String into Hash

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2765]
When unauthenticated users attempt to access the index view the catalog (e. g. `https://figgy-staging.princeton.edu/catalog?utf8=%E2%9C%93&q=`), this error is triggered.

## Backtrace

    line 118 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/41384418)

**Comment by jrgriffiniii** [comment]
This was triggered for me after deploying `master` locked to https://github.com/pulibrary/figgy/commit/67ecdc930f32619e6987567b9e40d734ee2d464d into the staging environment.
