### ISSUE TITLE
[Figgy/staging] TypeError: can't convert String into Hash

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2768]
## Backtrace

    line 186 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in find_inverse_references_by
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/47381004)

**Comment by christinach** [comment]
The error was triggered when I visited the show page for different coins

**Comment by hackmastera** [comment]
looks like these were deleted on staging
