### ISSUE TITLE
Mark 10TB of objects for cloud preservation

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2772]
Child of pulibrary/figgy#1876
Depends on pulibrary/figgy#2883 

- [x] Implement a preservation profile toggle
- [x] Implement background workers to Bag objects with a given preservation policy (Likely implemented by #911)
- [x] Identify a set of objects that constitute approximately 10TB of files for the next scale of cloud preservation.
- [x] Mark those objects with a preservation policy that triggers cloud preservation

**Comment by tpendragon** [comment]
Blocked until @escowles tells us which objects we should mark for preservation.

**Comment by escowles** [comment]
The first two collections I checked added up to 9.7TB:
* Yemeni Manuscript Digitization Initiative https://figgy.princeton.edu/catalog/eff75507-11bf-486b-b422-8fe29638b060
* Scheide https://figgy.princeton.edu/catalog/e4ad9ded-bdbb-4d29-b088-95c4a8c8df02

**Comment by tpendragon** [comment]
Going to mark Scheide for preservation in about 10 minutes.

**Comment by tpendragon** [comment]
Command for marking Scheide:
```
RAILS_ENV=production COLL=e4ad9ded-bdbb-4d29-b088-95c4a8c8df02 PRESERVATION_POLICY=cloud bundle exec rake bulk:update_attrs
```

**Comment by tpendragon** [comment]
Scheide is all marked for cloud preservation, FileSets are uploading now.

**Comment by tpendragon** [comment]
Scheide uploaded. I want to close pulibrary/figgy#2883 before we mark Yemeni, since it's much bigger.

**Comment by tpendragon** [comment]
Queueing up Yemeni Manuscripts. Command:
```
RAILS_ENV=production COLL=eff75507-11bf-486b-b422-8fe29638b060 PRESERVATION_POLICY=cloud bundle exec rake bulk:update_attrs
```

**Comment by tpendragon** [comment]
Yemeni Manuscripts are running now. Napkin math says it'll be done in 18 hours.

**Comment by tpendragon** [comment]
Yemeni manuscripts are up. Current storage:

`8.59 TiB     gs://figgy-preservation`

Close enough, or do we want to add more @escowles?

**Comment by escowles** [comment]
Let's add the Ethiopic MSS (54745b3c-9663-4d95-9030-4554eb5088ea) which my script says are 2GB of files to push it over 10TB.

**Comment by tpendragon** [comment]
Queued up Ethiopic MSS.

**Comment by tpendragon** [comment]
Should be done in about 4 hours.

**Comment by tpendragon** [comment]
There we go: `10.66 TiB    gs://figgy-preservation`
