### ISSUE TITLE
Include project documentation with with Collections / Objects

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/figgy#2780]
E.g. project proposals, other assessments

**Comment by tpendragon** [comment]
@jpstroop Do we have a concrete use case here? Preferably a collection that has these documents we need to store?

**Comment by jpstroop** [comment]
Came up in DPSG just now. @escowles do you recall who asked?

**Comment by escowles** [comment]
@jpstroop I think it was Steve Ferguson who asked about this.

**Comment by tpendragon** [comment]
Closed until someone comes to us with actual documents they need ingested.
