### ISSUE TITLE
Refactor duplicated upload code into a module?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2784]
There is a fair amount of code duplication around handling uploads between:
* https://github.com/pulibrary/figgy/blob/master/app/controllers/base_resource_controller.rb
* https://github.com/pulibrary/figgy/blob/master/app/controllers/bulk_ingest_controller.rb

Do we want to refactor that out into a module?

**Comment by jrgriffiniii** [comment]
The disambiguation between `BrowseEverythingController` and `BulkIngestController` methods is also disorienting, perhaps this refactor could address this as well.
