### ISSUE TITLE
Create numismatics import service

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2785]

**Comment by christinach** [comment]
We will have to update these file names https://github.com/pulibrary/figgy/issues/2794#issuecomment-487092319 with an english O.

**Comment by christinach** [comment]
also: 
vermont2185R.tif
Vermont2185O.tif
Judd7R.tif
Judd7O.tif
DG2H4418.tif
DG2H3181.tif
DG2H2250.tif
DG2H2245.tif
DG2H2038.tif
don't much a coin id.
