### ISSUE TITLE
Generate list of missing coin images

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2794]

**Comment by christinach** [comment]
/mnt/hydra_sources/pudl/pudl0049/ find numismatics

**Comment by christinach** [comment]
I started cleaning the data. 
1. there are tif names like 'Vermont' that we can't match to a coinID
2. Some tif names are ending in not English characters e.g a Greek O vs English O (these ones I will log them but also replace them with the English character)
3. There are duplicate tif names. 
I'm logging them and will add the result in this issue.

**Comment by christinach** [comment]
non-ascii char 
- from the numismatics directory: 
3353Ο.tif
9821Ο.tif
9824Ο.tif
- from the numis_edited directory
3353Ο.tif
I updated them.

**Comment by christinach** [comment]
The attached file includes coins that cannot match tif images in one of the numismatics dir (numismatics and numis_edited)

**Comment by christinach** [comment]
start 
`/mnt/hydra_sources/pudl/pudl0049/numis_edited`
`/mnt/hydra_sources/pudl/pudl0049/numismatics`

     - coinID updated with O and R counts: 26008
     - The numis_edited dir counts: 9135 tif -
     -      with unique tif: 8079 -
     - The numismatics dir counts 20454 tif -
     -      with unique tif: 16547
     - Not common tif between numis_edited and numismatics: 8473
     - Common tif between numis_edited and numismatics 8074
          total: 16547
     - Coins not matching images in numismatics dir:  423
     - Coins matching images in numismatics dir: 16124
     - Coins not matching images in numis_edited_dir: 423
     - Coins matching images in numis_edited_dir: 8031
     - Good! The same images miss from both directories
 end

**Comment by christinach** [comment]
The attached file includes the common tif images between numismatics and numis_edited

[common_tif_between_numismatics_and_numis_edited.xlsx](https://github.com/pulibrary/figgy/files/3122099/common_tif_between_numismatics_and_numis_edited.xlsx)

**Comment by christinach** [comment]
These 5 files are in the numis_edited directory but not in the numismatics:
1597O.tif
1665R.tif
3043R.tif
Judd7O.tif
Judd7R.tif
[numis_edited_not_in_numismatics.txt](https://github.com/pulibrary/figgy/files/3122339/numis_edited_not_in_numismatics.txt)

**Comment by eliotjordan** [comment]
@christinach I'm having a little trouble figuring out what all of the lists are. Is there a list that shows coins that are in the database that have missing images regardless of the directory?

**Comment by christinach** [comment]
@eliotjordan the file 
[coins_not_matching_in_numismatics_dir.txt](https://github.com/pulibrary/figgy/files/3122762/coins_not_matching_in_numismatics_dir.txt) is the one that the coinID does not match an image.

**Comment by christinach** [comment]
but you want a list of coinIDs. ok I'll add this one.

**Comment by christinach** [comment]
@eliotjordan attached is a file with coinids that they don't have images: 9,883
[list_coinids.txt](https://github.com/pulibrary/figgy/files/3122990/list_coinids.txt)

**Comment by eliotjordan** [comment]
Email sent to Alan and Roel. Thanks @christinach!
