### ISSUE TITLE
Create a Figgy GraphQL endpoint for events associated with a resource

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2804]
The first use case for this is to say "PreservationObject Fixity Verified"
These events should be stored outside the resource, so that updating or creating them don't cause the resource's updated_at to change which may trigger a new bag.

**Comment by jrgriffiniii** [comment]
My understanding of this requirement is that a unidirectional relationship from `Events` linked to both `FileMetadata` nodes and the parent `PreservationObjects` would provide the ability to verify fixity checks at the Bag level and at the level of the individual files.  Is this acceptable, or are their arguments to restrict events just to fixity checks at the level of files?

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-2804-jrgriffiniii-graphql-events introduces a generic `Event` Resource which stores messages and has a relation to modified resources (e. g. `PreservationObjects`).  Further, I've implemented a GraphQL Mutation which permits a client to search for Events by the modified resources, and update the message for any given Events.

Should it be the case that the GraphQL Mutation just creates new Events for PreservationObjects?  If so, should we indefinitely store the Events as a form of an audit trail?
