### ISSUE TITLE
Make error message more useful on failed reindex

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2808]
Log the ids of all the records in the current batch.

**Comment by hackmastera** [comment]
it should output the ids to a file, since there are 1000 of them.

**Comment by tpendragon** [comment]
Maybe we should see if we can make reindex more resilient in general? If a solr save errors, catch it and save it for the end and then iterate over those individually?

**Comment by hackmastera** [comment]
yeah i like that. then catch any errors at that point, also. log the ID, send it to honeybadger, get the rest indexed.
