### ISSUE TITLE
Schedule a full reindex on a frequent / regular basis

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#2810]
So we can see any errors in honeybadger and improve the index-ready state of the data.

**Comment by hackmastera** [comment]
once a week? what day?

**Comment by escowles** [comment]
Once a week seems like the right frequency — and I would look at analytics to see when our lowest traffic times are.

**Comment by hackmastera** [comment]
we should consider when OL schedules solr jobs, too, and avoid having both apps index at the same time.
