### ISSUE TITLE
files stuck in "pending uploads" box

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2819]
User tried to upload some items and when they appeared stuck in pending uploads, tried again the next day. They uploaded successfully later so the images are there, but so is the pending uploads box. https://figgy.princeton.edu/concern/scanned_resources/2b25f02d-552c-480e-bd93-a7de3dadfbf9/file_manager

Update Willow.

**Comment by tpendragon** [comment]
Two BrowseEverythingIngestJobs got queued for this, I think it was just a race condition.

**Comment by tpendragon** [comment]
Cleaned these up.
