### ISSUE TITLE
Order manager should be able to assign page numbers for images that contain multiple pages

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2822]
e.g. "I have an item where there are 2 pages per image.  Is there an easy way in Figgy to automatically number the pages like p. 1-2, p. 3-4, p. 5-6 etc?"

requested by @tventimi

Pulled from #3768

Most recent use case for shooting items two-up: Thomas Keenan and a faculty member have requested two-up viewing for runs of historic soviet periodicals. Although the viewer can always be changed to two up/paged viewing post-ingest, the problem comes in with the two page pictorial spreads within the periodicals that are not shot one-up, but two-up. A studio precedent to shoot two-up was set for two page spreads (that are not text based) for our digitized materials a while back. I share Thomas's reasoning for the request here: From a periodical studies standpoint recreating the physical object by showing how the 2-page spreads open up is important and it’s really difficult for a user to try to mentally recreate that looking at string of single pages.

**Comment by jpstroop** [comment]
I [added this](https://github.com/jpstroop/page_label_generator/blob/master/README.md#2-ups) to my little study from 2015. See the [specs](https://github.com/jpstroop/page_label_generator/blob/master/spec/labeGenSpec.js#L106-L164) for the API.

**Comment by kelea99** [comment]
@hackmastera - got a use case from Jen Cabral on Friday afternoon for another bulk pagination issue. Every other page is labeled in the digital surrogate she was working on. The page numbers can therefore be inferred on the unnumbered pages, but should be in brackets. can we find a away to automat this (one page in brackets, the following page not in brackets)? Lemme find the item she was working on and Ill post in a sec.

**Comment by sdellis** [comment]
@hackmastera and @tpendragon the page_label_generator npm package has been updated to 1.1.0 and should allow multiple page labels per image. https://www.npmjs.com/package/page-label-generator
