### ISSUE TITLE
Exception is raised when a source metadata identifier has an extra space

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2828]
Should we trim any accidental spaces?

## Backtrace

    line 44 of [PROJECT_ROOT]/app/services/pul_metadata_services/client.rb: retrieve_from_pulfa
    line 14 of [PROJECT_ROOT]/app/services/pul_metadata_services/client.rb: retrieve
    line 44 of [PROJECT_ROOT]/app/models/remote_record.rb: client_result

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/47767616)

```
URI::InvalidURIError: bad URI(is not URI?): CD-18264 .xml

https://figgy.princeton.edu/concern/scanned_resources/new/recording
```

https://github.com/pulibrary/figgy/blob/master/app/services/pul_metadata_services/client.rb#L44

**Comment by hackmastera** [comment]
It seems like the right time to do this sort of processing would be as it's coming out of the form into the change set. Like we need cleaners alongside the validators or something.

**Comment by hackmastera** [comment]
Another problem with this error is that the `source_metadata_identifier` provided is a CD number when it should be a bib number.
