### ISSUE TITLE
Files duplicated when added to a resource

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2836]
Paraphrasing from a slack conversation with Squirrel:

When adding files to a new resource via file manager > upload files from server (I'm uploading them from pudl\rbsc_backup\rbsc_studio.

I'm having an issue uploading images in Figgy. It uploads all of the images, but it also adds a bunch of the files again at the beginning, out of order. Cf https://figgy.princeton.edu/catalog/0c8bba02-a64d-4d91-bae4-65c1fa99d5dc  It's always the same numbers, as you can see here too: https://figgy.princeton.edu/catalog/855efa96-eb8b-4356-aece-e3ee9ba8e465

It's always the same numbers in the files and in the same order. 00000116, 00000056, 00000093, etc.

I noticed it this morning for my last 3 items, which includes C0101_c001964 as well.

May be related to changes in browse everything? Squirrel also notes that they no longer see directories expand when clicking on the checkbox next to them (Squirrel sent a screenshot I can attach if needed of this issue.). Squirrel said this happens on Mac or PC.

**Comment by hackmastera** [comment]
It looks like the files were uploaded 4 times; there are 668 files where there should be 167.

**Comment by hackmastera** [comment]
I've been able to replicate this. If you check the box next to the directory it adds all the files in a non-alphabetic order. If you then open and close the directory it re-adds the files each time.

So currently the only way to add the files you want in the order you need is to open the directory using the little arrow, then check the box next to the directory, and then upload without opening / closing it more. I think this must be related to recent work in browse everything. @jrgriffiniii would you mind giving your opinion when you get a chance?

**Comment by jrgriffiniii** [comment]
I can reenable the directory expansion, but this will require a separate branch for browse-everything.  I can address this.

**Comment by jrgriffiniii** [comment]
This is definitely partly related to the JavaScript for the file-selection widget.  In some cases file entries are not deselected when they are unchecked; I suspect that this might also be involved in the ordering bug.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/tree/issues-2836-jrgriffiniii-browse-files-duped should resolve this (I've tested this locally, and I'm currently waiting for files being uploaded on staging to finish).  I can issue this as a PR once I've confirmed that it indeed addresses the bugs on staging.

**Comment by hackmastera** [comment]
Here's what I'm seeing in development:
```
{"method":"POST","path":"/browse/resolve","format":"json","controller":"BrowseEverythingController","action":"resolve","status":200,"duration":6.61,"view":0.86,"db":0.0,"ddsource":["ruby"],"params":{"utf8":"✓","authenticity_token":"KS1Jr1MZx/42wmN500O/QmrVPs+JUzi5JzA4WQGGO78PnZrC6A7aiyYt6/+RrqXZ22XQVtBzPRhk+WTEKweTyw==","context":"","selected_files":["file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000001.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000002.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000003.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000004.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000005.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000006.tif"],"browse_everything":{"selected_directories":["file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847"],"selected_files":["file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000001.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000002.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000003.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000004.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000005.tif","file_system:/Users/headleya/src/figgy/staged_files/studio_new/RBD1.1_c847/00000006.tif"]}},"sql_queries":"'User Load (0.87) SELECT  \"users\".* FROM \"users\" WHERE \"users\".\"id\" = $1 ORDER BY \"users\".\"id\" ASC LIMIT $2'","sql_queries_count":1,"@timestamp":"2019-04-10T13:27:52Z","@version":"1","message":"[200] POST /browse/resolve (BrowseEverythingController#resolve)"}
```

**Comment by hackmastera** [comment]
Oh the upstream fix maybe worked; just deleting some methods that are now overriding upstream behavior.
