### ISSUE TITLE
Not all Cicognara items have 510 note

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2845]
Some exported MARC records are missing the 510 note linking to the Cicognara virtual collection, so they get imported into the Getty Research Portal, but don't get associated with the collection.  The note should be:

```
510 4_ $a Cicognara, $c 123
```

**Comment by tpendragon** [comment]
https://bibdata.princeton.edu/bibliographic/8540302 is an example. It looks like we should be pulling the current 024 where subfield c is "cico" and shoving that into a 510.

**Comment by hackmastera** [comment]
Is there some further action we can identify here to close the ticket beyond what was done in https://github.com/pulibrary/figgy/pull/3492?

**Comment by tpendragon** [comment]
OAI needs deployed and tested, Adam told about it, their process run, and then we need to make sure this got them all.
