### ISSUE TITLE
Add "additional collections" to Bulk Edit form, to add all items to another collection.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#2862]
is this possible? Example: adding another collection (ex: Edith Wharton) to items within an already assigned collection: https://figgy.princeton.edu/catalog?utf8=✓&q=Edith+Wharton+Manuscripts+C0118

**Comment by escowles** [comment]
@kelea99 Yes, we plan to add a few more things to the bulk edit screen:
1. collection membership
2. rights statement
3. preservation policy

See #2586 and #2842

So far, we have assumed that all the items being bulk edited would be in a single collection, and we only show the bulk edit button when the search is limited to a collection (to limit the potential for accidental system-wide changes).  That is true for the Edith Wharton items (where they are all in the Manuscripts collection).  But I'd appreciate feedback on other scenarios where that might not be the case.

**Comment by kelea99** [comment]
Absolutely, re: feedback. this one actually came from Squirrel in RBSC, and I thought it was a good idea as well (Edith Wharton's stuff is currently in 2 collections: MSS and one other, hence the want to create a new collection for them).

**Comment by kelea99** [comment]
Another use case for this for all the Latin American and Iberian Studies Collections. the feature should have the functionality to add only those items that are not already in the collection to it.
