### ISSUE TITLE
Questions / potential refactors for BrowseEverything::Parameters

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#2863]
1. It might be nice to extract methods for just the files and just the directories here:
https://github.com/jrgriffiniii/browse-everything/blob/252bd8504086be0281ad38c04996cbb231371a50/app/controllers/concerns/browse_everything/parameters.rb#L12-L23

 1. Related to the above, there's already a `selected_files` method, which I think gets all selected files and all files within selected directories. It would be nice to have a version that just gets directly-selected files, and of course important to name them clearly.

 1. Why on line 15 does it default to an array but on line 36 to a hash? It seems like we would expect one or the other
https://github.com/jrgriffiniii/browse-everything/blob/252bd8504086be0281ad38c04996cbb231371a50/app/controllers/concerns/browse_everything/parameters.rb#L15
https://github.com/jrgriffiniii/browse-everything/blob/252bd8504086be0281ad38c04996cbb231371a50/app/controllers/concerns/browse_everything/parameters.rb#L36

**Comment by tpendragon** [comment]
Close this ticket when a duplicate ticket exists in BrowseEverything

**Comment by tpendragon** [comment]
@jrgriffiniii Is this still valid? Can we close this?
