### ISSUE TITLE
Files uploaded to GCS should be validated via MD5

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2897]
Unsure what the API for this should be like - Valkyrie doesn't really support this. The library will though:

http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-storage/latest/Google/Cloud/Storage/Bucket.html#create_file-instance_method

**Comment by tpendragon** [comment]
Blocked by https://github.com/samvera/valkyrie/issues/705

**Comment by jrgriffiniii** [comment]
I'm testing https://github.com/samvera/valkyrie/pull/722 against `valkyrie-shrine` and `valkyrie-sequel`, and while the latter passed locally (I'm just waiting for https://circleci.com/gh/jrgriffiniii/valkyrie-sequel/2), the former seemed to have raised some unrelated errors (https://circleci.com/gh/jrgriffiniii/valkyrie-shrine/2).
