### ISSUE TITLE
Increase testing for generating Fixity Check Events from Google Cloud Pub/Sub Topic

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2898]
A google worker should be running (https://github.com/ursm/activejob-google_cloud_pubsub) which pulls from that topic and creates events based on if it's a success or failure.

**Comment by jrgriffiniii** [comment]
Does this simply require extending `UpdateFixityJob`?  If so, I can work off of https://github.com/pulibrary/figgy/compare/issues-2898-jrgriffiniii-gcs-pub-sub-events?expand=1 and  proceed with that approach.

**Comment by jrgriffiniii** [comment]
This may be already resolved by https://github.com/pulibrary/figgy/pull/2932/files, but https://github.com/pulibrary/figgy/compare/issues-2898-jrgriffiniii-gcs-pub-sub-topic introduces an improved acceptance test.

**Comment by tpendragon** [comment]
@jrgriffiniii Can we close this? Or do you want to adjust this ticket to add another acceptance test?
