### ISSUE TITLE
Improve handling for Google authentication errors

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2903]
These errors were reported by a user:

```
This morning I've been scanning "Hydrocarbon Processing" magazine and uploading it into Figgy.

However, the files upload into Figgy, however, the images don't upload.   The link also disappeared.

The bib for Hydrocarbon Processing is:  626389.  

I was uploading the files into:  Vol. 49, no. 7-12, 1970, now that link is gone.  

https://figgy.princeton.edu/catalog/5ddf552f-96d6-45b6-bcb2-4282bd6b1de3  
```

**Comment by jrgriffiniii** [comment]
I have not yet received details from the user who reported the issue, but can confirm that, for the "File Manager" interface, files are successfully ingested from Google Drive folders and shared folders.

**Comment by jrgriffiniii** [comment]
I also failed to reproduce any errors when ingesting items from private and shared Google Drive folders using the "Bulk Ingest" interface.

**Comment by jrgriffiniii** [comment]
The user now reports that this has been resolved without any intervention by PUL team members, but notes that there was an error initially which may be related to authentication (presumably, through the Google OAuth integration).

**Comment by tpendragon** [comment]
@jrgriffiniii Can we close this?
