### ISSUE TITLE
Fixity Dashboard should show all failures and recent successes of Cloud Fixity operations

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2910]

**Comment by jrgriffiniii** [comment]
Would using the current layout of the dashboard be acceptable?  I currently have the following simple layout:

<img width="1380" alt="figgy_issues-2910-jrgriffiniii-cloud-fixity-status_screenshot_0" src="https://user-images.githubusercontent.com/1443986/56686930-1fc1ae80-66a3-11e9-8650-2c7e277803c5.png">

**Comment by escowles** [comment]
That looks like a reasonable starting point to me @jrgriffiniii .
