### ISSUE TITLE
Add a widget to search for an issue in the edit coin screen, instead of using the drop-down select menu

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#2916]
![Screen Shot 2019-04-23 at 6 02 41 PM](https://user-images.githubusercontent.com/9905193/56619777-be430680-65f4-11e9-9e0a-4501395e180e.png)

**Comment by christinach** [comment]
![Screen Shot 2019-04-24 at 9 25 54 AM](https://user-images.githubusercontent.com/9905193/56662973-13bdf880-6673-11e9-94f0-d67cfc43c908.png)

@escowles I was thinking if we really need a widget? After https://github.com/pulibrary/figgy/pull/2913 is merged the user is able to type the number of the issue and bring it up.

**Comment by escowles** [comment]
@christinach I think that's good enough for now — if they have trouble looking up the issue number, then we could add something like the widget we use to add tracks to a playlist.

**Comment by christinach** [comment]
thank you!

**Comment by christinach** [comment]
Updated the select dropdown box to have a max-height of 300px.  https://github.com/pulibrary/figgy/pull/2913. Closing this issue.
