### ISSUE TITLE
Namespace Numismatics resources

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2928]
Might make class names more clear.

Numismatics::Artist
Numismatics::Citation
Numismatics::Subject

etc..

Directory structure:

- numismatics
  - artist.rb
  - citation.rb
  - subject.rb

**Comment by escowles** [comment]
Yes, that seems reasonable to me to create that kind of hierarchy.  Would that mean all of the numismatics models/controllers/etc. would be under `app/resources/numismatics/`?  I.e., does this include moving Coin and Issue to Numismatics::Coin and Numismatics::Issue too?

**Comment by escowles** [comment]
Fixed with https://github.com/pulibrary/figgy/pull/3108
