### ISSUE TITLE
Home screen for numismatics

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2929]
Given the number of numismatic resources that can be managed and created, it might be useful to have a home screen just for numismatics.

**Comment by escowles** [comment]
👍 on creating a home screen for numismatics.  There's been a ticket for redesigning the home page as a dashboard (https://github.com/pulibrary/figgy/issues/894), and this seems like a good step in that direction.

**Comment by christinach** [comment]
![Screen Shot 2019-05-06 at 2 20 17 PM](https://user-images.githubusercontent.com/9905193/57245999-2e488800-700a-11e9-9da5-48ecaa428109.png)

**Comment by christinach** [comment]
![Screen Shot 2019-05-07 at 1 27 43 PM](https://user-images.githubusercontent.com/9905193/57320033-f73aab00-70cb-11e9-8d3d-336d1e3801e8.png)

**Comment by christinach** [comment]
![Screen Shot 2019-05-07 at 7 43 28 PM](https://user-images.githubusercontent.com/9905193/57339654-7649d680-7100-11e9-9fe2-e6ccef0ccf61.png)
