### ISSUE TITLE
As a fulfiller, I would like to download several audio files at once

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2939]
Related to #2462 and #2968

* In the reading room, a user might want to access all the objects in an archival media collection, and downloading dozens or hundreds of audio files is tedious

**Comment by tpendragon** [comment]
@escowles Can you triage this one?

**Comment by escowles** [comment]
I think this should stay in the backlog — because there is a lot of bulk functionality that's been implemented recently that works fine for resources that can be exported to PDF, but audio files will need something different.
