### ISSUE TITLE
Bulk Download Functionality for Fulfillers

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2968]
Existing download functionality is cumbersome to use for more than a few images or items.  Fulfillers sometimes need to download many items at once, e.g.:
* TIFF files for several pages in a book, up to an entire book
* TIFF files for several items in a collection, up to an entire collection
* PDF files for several items in a collection, up to an entire collection

**Comment by escowles** [comment]
Some ideas:
* Add a button to the bulk edit screen for "download these items as TIFF images" or "download these items as PDF"
* Add a button to the order manager for "download these pages as TIFF images" or "download these pages as JPEG images"

These would stage the items to disk somewhere accessible by the user, and send an email with the location when done

**Comment by kelea99** [comment]
I remember us writing something similar to this recently. @escowles is this related to #3910 and #3909 and should the issues be merged in some way?

**Comment by escowles** [comment]
Yes, I think these are all basically the same issue — downloading a single page is fine, but downloading several pages, or PDFs for several items, is very cumbersome. So I think the key thing I'm not clear about here is what the delivery mechanism should be. I was mostly thinking of staff doing the request, where Isilon or other local staging disk seemed like the right place to put things. But if end users have the same need, then maybe Google Drive or some other system like that would be better?

**Comment by tpendragon** [comment]
See #1891. @escowles @kelea99 Can we close this one also as a duplicate?

**Comment by escowles** [comment]
👍  Yes, closing this as a dupe of #1891
