### ISSUE TITLE
Test sync with DPUL

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#297]

**Comment by tpendragon** [comment]
The process:

1) An object is saved
2) An event is fired to RabbitMQ on a fanout exchange
3) DPUL registers a queue on the exchange and has a worker which pulls out the event and knows to fire a reindex of the IIIF manifest.

Basically, this SHOULD work if the IIIF manifest is setup right. Testing this will probably mean pointing hydra-dev's configuration to the RabbitMQ server on figgy-staging.
