### ISSUE TITLE
State/Visibility Propagation Caused StaleObjectError

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2970]
To the user, all he did was try to edit an object to have a new collection and got a "something went wrong" page. What actually happened was saving that object propagated state/visibility (maybe FileSets didn't have their visibility set right?), and one of them had just finished being characterized.

**Comment by escowles** [comment]
I think the minimum we can do here is catch the error and warn the user that something else made an update.  Ideally, the user would be able to easily retry their update without having to manually repeat the changes.
