### ISSUE TITLE
Improve the Rake queue management for Redis tasks

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#2977]
Should users wish to cancel asynchronous jobs initiated using `Rake`, this cannot be easily done.

**Comment by escowles** [comment]
There's a FAQ entry saying Sidekiq doesn't provide this functionality, and gives some guidance on implementing your own cancel function: https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job
