### ISSUE TITLE
When I look at Ethiopic manuscripts, Id like to see all finding aid fields mapped to figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#2987]
This came up in a meeting this morning from a scholar. There is a lot of information that can be pulled from PULFA site on the Ethiopic manuscripts that would be useful to see in DPUL site as well. Could we do this? Example:   
https://findingaids.princeton.edu/collections/C0744.03/c0002
_and_
https://figgy.princeton.edu/catalog/7d9e690b-0590-4138-9a5d-9fe99b9a3d2b

**Comment by escowles** [comment]
We need to make sure that we handle the diversity of finding aid metadata gracefully — so we'll need to get example records from different finding aids, and stakeholders to review metadata extraction to make sure they are handled well.

**Comment by kelea99** [comment]
Sounds good, @escowles . I'll contact Alexis A. this week to start discussions.

**Comment by tpendragon** [comment]
@kelea99 Any progress on getting these fields?

**Comment by kelea99** [comment]
@tpendragon. Lemme check. I can't remember off the top of my head

**Comment by tpendragon** [comment]
They're moving all these to MARC records.
