### ISSUE TITLE
Images do not display in UV on figgy-staging

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2988]
There’s a problem with `figgy-staging` that I don’t understand. I thought it was just the coins I imported last night, but it appears in other resources as well. The UV fails to load image tiles, throwing this error:

`Tile a.Tile failed to load: https://figgy-staging/cantaloupe/iiif/2/77%2F86%2F08%2F77860841d01b49478b234a340b410497%2Fintermediate_file.jp2/full/29,/0/default.jpg - error: Image load aborted`

https://figgy-staging.princeton.edu/catalog/5c17218c-c321-4220-b5a9-a6bfa65468dc

No clue why the domain and TLD are being dropped. The manifest looks fine to me. 

https://figgy-staging.princeton.edu/concern/scanned_resources/5c17218c-c321-4220-b5a9-a6bfa65468dc/manifest

No idea how long this has been happening. Related to the shift to NGINX? A Cantaloupe issue?

**Comment by eliotjordan** [comment]
Calling `info.json` returns the malformed url, so I'm guessing something is up with Cantaloupe:

https://figgy-staging.princeton.edu/cantaloupe/iiif/2/77%2F86%2F08%2F77860841d01b49478b234a340b410497%2Fintermediate_file.jp2/info.json

**Comment by eliotjordan** [comment]
The cantaloupe proxy on figgy-staging is not forwarding the fully qualified domain name. As a temporary fix, I manually set the `X-Forwarded-Host` to `figgy-staging.princeton.edu`.

/etc/nginx/sites-enabled/passenger: line 44
```
# proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Host "figgy-staging.princeton.edu";
```

@kayiwa Can you take a look at this?

**Comment by tpendragon** [comment]
I tried fiddling with setting figgy-staging's Host and X-Forwarded-Host variables and none of them seemed to stick after reloading. I dunno if nginx plus is doing something weird or what.

**Comment by kayiwa** [comment]
you bring up a good point here @tpendragon the changes you were making on `lib-adc1` wouldn't reflect on figgy-staging because it wasn't the active node. when running this on prem you only run them active/passive and adc1 was the passive one.

**Comment by kayiwa** [comment]
will work on this. https://docs.nginx.com/nginx/admin-guide/high-availability/configuration-sharing/

**Comment by jrgriffiniii** [comment]
Is this still an issue?  I'm not able to reproduce this with any Figgy resource in staging which uses Canteloupe as the image server.

**Comment by eliotjordan** [comment]
This is still an issue because my temporary fix from May 8 is still in place.

**Comment by tpendragon** [comment]
We don't use cantaloupes anymore.
