### ISSUE TITLE
Replace Kakadu

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2989]
We are currently using Kakadu's `kdu_compress` to convert TIFFs to JP2k.  Replace `kdu_compress` with another tool, such as OpenJPEG.

Related to #163

**Comment by tpendragon** [comment]
@roelmoon is gonna see if he can get a good conversion command.

**Comment by tpendragon** [comment]
`opj_compress -i <file> -o output.jp2 -b 64,64 -t 1024,1024 -p RPCL -n 8 -r 1`

**Comment by tpendragon** [comment]
For indexed color map images we'll have to pre-convert with the `-type truecolor` option

**Comment by tpendragon** [comment]
Looks like we can run a pre-process step for everything:
`convert <inputfile>.tif -type truecolor -profile <iccprofilefromhydraderivatives> output.tif`

**Comment by tpendragon** [comment]
We don't have to remove compression from the TIF to generate the JP2 with OpenJPEG.
