### ISSUE TITLE
5709O.tif can't be converted to JP2

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2996]
## Backtrace

    line 99 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: create_tiff_derivative
    line 93 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: run_tiff_derivatives
    line 86 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: run_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/49293918)

**Comment by eliotjordan** [comment]
```
MiniMagick::Invalid: `identify /tmp/mini_magick20190508-24362-1g8e4.tif` failed with error:
identify: Unknown field with tag 37680 (0x9330) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1000.
identify: Sanity check on directory count failed, zero tag directories not supported. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/652.
identify: Failed to read custom directory at offset 25050172. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/652.
identify: Unknown field with tag 37680 (0x9330) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1000.
```
