### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3]
Plum/Figgy should probably have its own brand, and we should use that instead of DPUL (see https://github.com/pulibrary/figgy/pull/2/files#diff-37c9b835927e3c363588f172de9bb6faR24).

That brand might be "Plum" or it might be something else, but it shouldn't be DPUL.

**Comment by tpendragon** [comment]
Acceptance Criteria: Change header to "Figgy"

**Comment by escowles** [comment]
Let's just call it "Figgy"
