### ISSUE TITLE
Add drop-down for Rights Statement & Holding Location

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#30]
Are we still happy with QA and `Hyrax::LicenseService` etc for this? Is there anything simpler?

**Comment by escowles** [comment]
We could use the Vocabs from LAE to manage the rights statements (we would probably want to include a description field).  Would that be simpler?  Since we're not using any of the remote discovery functionality in QA, it feels like it's not really getting us much.

**Comment by tpendragon** [comment]
I dunno, but the whole rights service thing doesn't feel very clear to me whenever I use it.
