### ISSUE TITLE
Determine and document process for archival media bag ingest error correction

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3021]
Currently, when there are files the ingest script couldn't match to any particular component id, a media resource is created and they are all just stuck in there together.

When this happens, collections professionals can sort out the problems and this often involves fixing up the EAD so that files are matched to the correct component id. We need to determine the next course of action for the ingest.

Should we delete the media resources which ingested incorrectly and re-run the import? If so, that work flow should be tested for idempotence.

Should we delete and re-ingest the entire bag at once (so everything has the same upload set)?

Are there other ways of proceeding that make sense?

Once this is figured out, #3016 #3017 and #3018 can be used to test approaches, since they all need fixes.

**Comment by hackmastera** [comment]
Implementing a way for collections professionals to resolve these manually could advance the use case of reorganizing a finding aid.

**Comment by escowles** [comment]
Decision: for an entire Archival Media Collection, re-run the matching rules and move/combine/split MediaResources and/or FileSets according to the current rules and finding aid data.

**Comment by hackmastera** [comment]
We'll accomplish this by making the following structural changes:
1. Files will be grouped into resources by physical origin (aka files that share a barcode / thumbnail image / `.xml` metadata file will be filesets on the same resource)
1. Additional resources will be created as proxies for the archival description. Component IDs will live here and metadata will be pulled from finding aids.

Here is a diagram:
https://docs.google.com/drawings/d/1kR_jV-84jXZNI3GfV8enDqv5rMHMizBxZx4-3GszggE/edit

**Comment by hackmastera** [comment]
Then the ingest process will be updated to first load all the files out of the bag, then create the description proxies and organize the resources into them. The 2nd step of this process should be repeatable / idempotent.

**Comment by tpendragon** [comment]
We're assuming that the structure will never go deeper than ArchivalMediaCollection -> MediaResource (component_id) -> MediaResource (barcode) -> FileSets. Where should we document that?

**Comment by escowles** [comment]
@tpendragon That could be an ADR — is there somewhere better to document that?

**Comment by hackmastera** [comment]
It seems like it would be good to have some user-facing documentation. Maybe near whatever UI we end up creating to close this ticket?
