### ISSUE TITLE
Improve error handling for controlled vocabulary term dropdown fields in the resource edit view

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3028]
## Backtrace

    line 327 of [PROJECT_ROOT]/app/models/controlled_vocabulary.rb: []
    line 327 of [PROJECT_ROOT]/app/models/controlled_vocabulary.rb: block in all
    line 326 of [PROJECT_ROOT]/app/models/controlled_vocabulary.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/49507284)

**Comment by jrgriffiniii** [comment]
`no implicit conversion of Symbol into Integer` was raised when attempting to construct a new `Term` within https://github.com/pulibrary/figgy/blob/master/app/models/controlled_vocabulary.rb#L327.  One possible cause for this would be that one of the values for the `record` JSON property/value Hash contained an Array for a value.
