### ISSUE TITLE
playlist show page: Don't show table headings under track search until there are results

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3035]
Currently it looks like floating mystery words:

![Screen Shot 2019-05-16 at 9 34 00 AM](https://user-images.githubusercontent.com/845363/57858035-49f81f00-77be-11e9-9e59-78edee6e39d5.png)

**Comment by jrgriffiniii** [comment]
This should be fixed with https://github.com/pulibrary/figgy/compare/issues-3035-jrgriffiniii-playlist-theads, but I can't seem to implement functional test for Selenium (Vue seems to be breaking in my local environment when this is tested).
