### ISSUE TITLE
Research UV transcript support

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3038]
Decide how to include transcripts
* Format: HTML, PDF, plaintext
* Encoding: UV has an example manifest: https://wellcomelibrary.org/iiif/b16748967/manifest (http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb16748967%2Fmanifest)

**Comment by tpendragon** [comment]
There's a working group and also shortly a IIIF recipe.
