### ISSUE TITLE
Add preservation support to a/v resources

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3041]
Do we want a whole Archival Media Collection package to be the unit of preservation, or each Media Resource?

Implement by adding the preserve property.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-3041-jrgriffiniii-av-preservation introduces preservation support for `MediaResourceChangeSets`, but it seems to be constructing `PreservationObjects` for both the `MediaResource` and `FileSet` separately.

**Comment by tpendragon** [comment]
It's correct behavior that it's constructing `PreservationObjects` for both `MediaResource` and `FileSet`.

**Comment by tpendragon** [comment]
To close this ticket we need to make sure that on import the Recording is set to be preserved and test it in staging.

**Comment by tpendragon** [comment]
Tested. Works!
