### ISSUE TITLE
Hide the sticky sidebar when the user is not signed in

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3052]

**Comment by christinach** [comment]
![Screen Shot 2019-05-20 at 1 07 37 PM](https://user-images.githubusercontent.com/9905193/58039307-623ea580-7b00-11e9-9c67-48fea458a2f8.png)

**Comment by hackmastera** [comment]
Ah! good catch! This is why it looked wrong in safari for me on friday. Thanks
