### ISSUE TITLE
Can we assume bags will be valid?

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3057]
Bag validation takes a long time. Do archives folks validate them as part of their workflow prior to load? If so, we may be duplicating effort. If not, could we find / create a tool that would help them feel confident before loading into figgy?

**Comment by escowles** [comment]
I don't think we can assume they are valid at ingest — too many people have the ability to change files, and of course disk problems, etc. could happen too.  But we don't need to validate as part of reading the Bags to show the user how things will ingest.
