### ISSUE TITLE
Update z-index in add_content or in sticky bar

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3059]
![Screen Shot 2019-05-21 at 1 59 38 PM](https://user-images.githubusercontent.com/9905193/58119387-d9436f00-7bd0-11e9-9353-975eab58180e.png)

**Comment by christinach** [comment]
Update z-index in the add_content menu or in the sticky-bar so that the sticky bar does not cover the menu

**Comment by hackmastera** [comment]
👍 probably in the add_content menu because the sticky bar has the lowest z-index it can have while still rendering on top of the leaflet controls (which are z-indexx 1000)
