### ISSUE TITLE
Numismatics Issue needs a monogram description field

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3062]
I think this can be accomplished by attribute description but I want to make sure. The staff were describing the need to describe the positioning of the monogram on the coin.

**Comment by christinach** [comment]
When saying positioning of the coin do we mean: Top, Bottom, Left, Right, Top-Right, Top-Left, Bottom-Right, Bottom-Left ? Or something more specific?

**Comment by christinach** [comment]
I updated the comment with 'monogram'

**Comment by tampakis** [comment]
Yeah they generally describe where the monogram is found on the coin.

**Comment by christinach** [comment]
While discussing with @eliotjordan :
A monogram can be part of more than one NumismaticIssue.
All coins from a numismatic_issue will have the same monogram (we think). (If an issue has 10 coins and 2 monograms, are these monograms in all the coins or 1 monogram can  be found in 2 coins and the other monogram can be found in all the 10 coins? )

**Comment by eliotjordan** [comment]
We should add a simple text Description field to NumismaticIssue.

**Comment by christinach** [comment]
Can we close this? In the meeting we agreed that they will use the Numismatic Issue -> Reverse and Obverse attributes to add description for the monogram. Is this correct? @eliotjordan @tampakis @escowles 
![Screen Shot 2019-05-24 at 7 18 25 AM](https://user-images.githubusercontent.com/9905193/58324335-982ba480-7df4-11e9-8b2c-a7fece1d34b6.png)
![Screen Shot 2019-05-24 at 7 18 18 AM](https://user-images.githubusercontent.com/9905193/58324340-9bbf2b80-7df4-11e9-8a6d-f4e17572a79e.png)

**Comment by escowles** [comment]
I agree with Christina — I thought we agreed yesterday that the existing attributes fields were good enough to describe how the monograms show up.

**Comment by christinach** [comment]
I will close it for now. If there is another opinion we can open it. - I think @eliotjordan added the comment after the meeting and while we were discussing in zoom the feedback from the meeting; 
 going back today and seeing the notes we don't need a description field.
