### ISSUE TITLE
Select monograms from a gallery of monogram thumbnails.

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3063]
Ideally the monogram can be selected from a gallery of monogram thumbnails and new monograms can be created from the issue form.

**Comment by christinach** [comment]
The current issue is to select monograms from a gallery of monogram thumbnails as @tampakis mentioned in the first comment.

**Comment by jrgriffiniii** [comment]
I've managed to introduce the following on the branch https://github.com/pulibrary/figgy/tree/issues-3063-jrgriffiniii-monogram-select
![image](https://user-images.githubusercontent.com/1443986/71023656-31901000-20d1-11ea-9817-9e5a83f6b1c3.png)

**Comment by jrgriffiniii** [comment]
Trying to implement a Vue-based alternative is breaking the rendering with https://github.com/pulibrary/figgy/tree/issues-3063-jrgriffiniii-monogram-select. I'm not quite sure why this won't render, but it will be needed given that loading the models (such as in https://github.com/pulibrary/figgy/compare/issues-3063-jrgriffiniii-monogram-select#diff-ea6dd108df6b280fc758fbda6ac299bbR29) are too slow to load using the Controller.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/commit/7fc7fd2885cbfce1a5787429b9acfa4ffac661a5 ensures that the components mount, but there are some issues with the IIIF-based thumbnail URLs.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/commit/7bcfa6dc1b577207be735244b11f350df915b885 sees this to the point where the Vue components now successfully update the `Monograms` for any given `Issue`. There exists a bug with thumbnail rendering for `Monograms` which I still need to resolve.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/commit/b6d50b25f9f611de4616d84ca1b057b8799d8908 fixes thumbnail rendering

**Comment by jrgriffiniii** [comment]
Monograms are now sorted to ensure that those which are attached are rendered first, and I've introduced some styling changes to handle the disparity in height between thumbnails, along with the overflow:
![image](https://user-images.githubusercontent.com/1443986/71110385-2b636780-2195-11ea-83a4-27b34d1dd1bd.png)

**Comment by jrgriffiniii** [comment]
I was using the terms `Attach` and `Detach` a bit blindly - are these appropriate? Perhaps `Select`/`Deselect` is more accurate?
