### ISSUE TITLE
Recordings should be able to ingest Intermediate/PreservationMaster/Service(MP3) files

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3069]

**Comment by hackmastera** [comment]
Hm. I'm not really sure acceptance criteria for this ticket. Should I write a test showing that a file set with these files can be attached to a recording? Should I try creating one in the console and see if the UI errors? I guess I'll go with the latter. I don't think we have doubts that a File Set can be attached to a scanned resource.

**Comment by escowles** [comment]
Maybe this is blocked by #3079 and should be renamed "Make sure we can still ingest and download MP3 files once IngestArchivalMediaBagJob is creating Recordings"?

**Comment by hackmastera** [comment]
@escowles I think "make sure it can download" is #3069.

I guess I'll just take this at face value and try it in dev.

**Comment by hackmastera** [comment]
Everything comes together fine in dev. I'm going to put the code I used to generate the object into a feature test, so it can be used for #3070.
