### ISSUE TITLE
Recording manifests should display an attached image FileSet if there is one as the background of the viewer

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3075]
This means a Recording will have member_ids which are four FileSets: XML File/Image/Two sound Files. The manifest builder will say "I'm a recording, I have an image FileSet, make it my background. Don't do anything with the XML file."

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-3075-jrgriffiniii-background-av-fileset updates the `ManifestBuilder` to generate manifests for `FileSets` with images on `Recordings`, but this still seems to be broken in the UV.  I'll need to look towards https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17307922%2Fmanifest for the manifest structure.

**Comment by jrgriffiniii** [comment]
Overriding the `CanvasBuilder` to use the `thumbnail` property did not seem to yield any fruitful results:
![image](https://user-images.githubusercontent.com/1443986/58846780-7fba5600-864e-11e9-8490-8ae21279935f.png)

Overriding the `ContentBuilder` (https://github.com/samvera-labs/iiif_manifest/blob/master/lib/iiif_manifest/v3/manifest_builder/content_builder.rb#L4) in order to provide the `thumbnail` property at the level of the Content Resource (https://iiif.io/api/presentation/3.0/#57-content-resources) might be more effective.

**Comment by jrgriffiniii** [comment]
This didn't prove effective, not did attempting to pass the `thumbnail` to the `Annotation`.  https://github.com/IIIF-Commons/iiif-av-component/blob/master/src/AVComponent.ts#L2533 seems to be where the background for audio resources would be set, I'll be tracing the functionality from this point.

**Comment by jrgriffiniii** [comment]
This has been successfully tested with a fixture for the UV, I can proceed by looking to use the needed image `FileSet`:

![image](https://user-images.githubusercontent.com/1443986/58962104-788f6700-8778-11e9-80f4-fac9427ff19f.png)

**Comment by jrgriffiniii** [comment]
https://github.com/samvera-labs/iiif_manifest/blob/master/lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb#L49 seems to be problematic when `record.display_content` is just empty (but not `nil`).

**Comment by jrgriffiniii** [comment]
https://figgy-staging.princeton.edu/catalog/62d724b9-062a-4f4f-b3fb-5420ea68fb0a demonstrates this (the branch currently offers the fixture manifest for an easy demonstration).

**Comment by jrgriffiniii** [comment]
Ensuring that the UV automatically displays the expanded thumbnail requires that the following be triggered: https://github.com/IIIF-Commons/iiif-av-component/blob/master/src/AVComponent.ts#L2899

Unfortunately I'm still struggling to access this using `jQuery` within the `iframe`

**Comment by hackmastera** [comment]
I have tried to do that sort of thing before as well. you can't get into an iframe with javascript. ☹️

**Comment by jrgriffiniii** [comment]
You technically can, but it's really not good:
```
let $uv = jQuery('iframe').contents().find('#uv')
```

I am still trying to work with the UV Object in https://github.com/pulibrary/figgy/blob/master/public/uv/helpers.js#L28, but I'm struggling to find the accessor I would need to invoke methods on the `AVComponent` Object.

**Comment by jrgriffiniii** [comment]
Introducing the update into the UV in order to provide to expanded thumbnails should be structured as a configuration option, and these should be passed to the AV extension component within https://github.com/UniversalViewer/universalviewer/blob/master/src/UVComponent.ts#L183

**Comment by jrgriffiniii** [comment]
Passing configuration options into the `BaseExtension` Class is definitely provided in these two locations: https://github.com/UniversalViewer/universalviewer/blob/master/src/UVComponent.ts#L424 and https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-shared-module/BaseExtension.ts#L49

However, I'm still struggling to find where these values are overridden by custom configuration options.

**Comment by jrgriffiniii** [comment]
This was the wrong approach (or, perhaps an alternative for another discussion).  Regardless, another approach which seems to successfully parse configuration options which are overridden follows this pattern: https://github.com/UniversalViewer/universalviewer/compare/master...jrgriffiniii:jrgriffiniii-share-manifest-collections-test

This will be introduced into https://github.com/UniversalViewer/universalviewer/pull/655

**Comment by jrgriffiniii** [comment]
The blocking issue for me was a TypeScript configuration issue for the UniversalViewer - https://github.com/IIIF-Commons/iiif-av-component/compare/master...jrgriffiniii:jrgriffiniii-postercanvas-expanded offers the change into the `@iiif/iiif-av-component`

**Comment by jrgriffiniii** [comment]
https://github.com/UniversalViewer/universalviewer/compare/master...jrgriffiniii:jrgriffiniii-postercanvas-expanded integrates those changes into the Universal Viewer.

**Comment by jrgriffiniii** [comment]
https://github.com/IIIF-Commons/iiif-av-component/pull/35#event-2410409000 was merged, I will move this ahead with a pull request for the Universal Viewer once a new release is available on https://www.npmjs.com/package/@iiif/iiif-av-component

**Comment by jrgriffiniii** [comment]
I'm sorry for missing this, it appears that a new release of https://www.npmjs.com/package/@iiif/iiif-av-component was published yesterday, I will see about updating this in the build for the UV.

**Comment by jrgriffiniii** [comment]
https://github.com/UniversalViewer/universalviewer/pull/674#issuecomment-508091847 blocks this from being introduced entirely upstream, but there is a community call scheduled for tomorrow (so perhaps there can be some support for addressing this).
