### ISSUE TITLE
Student Worker guide for Numismatics workflow

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3088]
Document the workflow process for student workers. Will need to be completed after we have real feedback from Vicki, Razieh, and Alan about the forms. Maybe after All Hands.

**Comment by tampakis** [comment]
[Manual for Coin Data Entry.pdf](https://github.com/pulibrary/figgy/files/4098136/Manual.for.Coin.Data.Entry.pdf)

**Comment by jrgriffiniii** [comment]
I've managed to progress with completing the section outlining the creation of Issues: https://docs.google.com/document/d/1m1xgKG-44TItxlGIqmF_C-XDoYSnN5UDpqWOQe_SgFs/edit?usp=sharing

There are still other sections to be completed (along with a glossary), and it may be best if I add an animation detailing the attaching/detaching of Monograms.

**Comment by jrgriffiniii** [comment]
This draft is ready for review please, I am definitely able to trim down certain sections and work to address anything missing from data capture for the Numismatics Collection using Figgy.

**Comment by eliotjordan** [comment]
Done.
