### ISSUE TITLE
Handle Restricted Content in viewer

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3118]
For Toni Morrison papers:
- [x] If the user is logged into Figgy and has staff or admin role, display digital content
- [x] If a user's IP address is in a whitelist,  and they are logged in with a "reading room" role, then display the digital content
- [x] Otherwise, do not display the viewer

**Comment by tpendragon** [comment]
My plan is to implement this by utilizing the difference between discover and read permissions. If you have the right IP, you can discover, if you're also logged in you can read.
