### ISSUE TITLE
New Visibility Level: "Reading Room"

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3119]
Related to #3118 — this ticket is for adding the new permission setting to Figgy, #3118 is for making the access controls work in the viewer.

- [x] Add new authorization policy
- [x] Add new option to form
- [x] Add whitelist IPs to env via ansible

**Comment by hackmastera** [comment]
The IP whitelist portion of this ticket is blocked. The machines they currently use are on a private network and cannot access figgy. Operations team is looking into alternatives.
