### ISSUE TITLE
Enable OAI-PMH harvesting from clients

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#3128]
This was requested by one user, and would appear to be readily supported by the usage of https://github.com/projectblacklight/blacklight_oai_provider.

**Comment by tpendragon** [comment]
Who asked for this and why?

**Comment by tpendragon** [comment]
We need this now for Cicognara auto-harvesting from Getty.

**Comment by escowles** [comment]
I talked to Alexis, who asked about this previously for the In Her Own Right project. Those items will be in a finding aid, and harvested by the project.

**Comment by tpendragon** [comment]
Okay. That'll be a different metadata format then (OAI-DC) - http://inherownright.org/tutorials/data_access. I'm going to make a couple extra tickets as children of this one.

**Comment by kelea99** [comment]
@escowles - Is this a priority for anything? Looking through my archive, I have the BnF's OAI-PMH interoperability guide for referencing of digital documents in Gallica that was forwarded to us by Steve. But the most recent request in March from the BnF was if they could harvest our data in DC format after Steve provided them with our OAI url.

**Comment by escowles** [comment]
The highest priority use for this that I know of is to make our archival content harvestable for France in the Americas (#3649).

**Comment by kelea99** [comment]
ok. so this will be up with the other related issues. Thanks!

**Comment by hackmastera** [comment]
I think those other tickets stand on their own as specific use cases that don't need a parent epic, and technically we have enabled oai-pmh; moving forward it's just a matter of validating our feed on a case-by-case basis. Can we close this ticket? @tpendragon

**Comment by tpendragon** [comment]
Sounds good to me.

**Comment by hackmastera** [comment]
👍 I just converted it back to a regular issue (instead of an epic) as well.
