### ISSUE TITLE
Links in PDF cover page should go to public-facing sites

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3130]
Currently, PDF cover pages include a link to the Figgy object, which directs users to a staff-facing application.  We should use the public-facing URL for the object, either the ARK URL or the Catalog/Finding Aids/etc. URLs they point to.

**Comment by tpendragon** [comment]
This was mentioned during 07/22/19 all-hands as something we need to fix.

**Comment by escowles** [comment]
We already have the logic for what these URLs should be in the ARK minting code, where we send things with Voyager records to Orangelight, stuff with PULFA ids to PULFA, etc.

**Comment by escowles** [comment]
For complete items, we should probably just use the ARK
