### ISSUE TITLE
UV footer displays div.positionPlacemaker after ingesting scanned resources with the same bibID

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3150]
https://figgy.princeton.edu/catalog/d5bfcf78-13ce-4929-b130-1b176e6e80ae
https://catalog.princeton.edu/catalog/1196768
<img width="1278" alt="Screen Shot 2019-06-21 at 8 26 22 PM" src="https://user-images.githubusercontent.com/9905193/59957067-def7d300-9462-11e9-83bb-716986414150.png">

**Comment by tpendragon** [comment]
This shows up because OCR was enabled, so you can search within.
