### ISSUE TITLE
UV can't play a collection of recordings

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3156]
This is a problem for our AV bags because they're typically a grouping of barcodes under one component ID. We can probably fix this by inlining all the child file sets for generation of the manifest (like we do for Sammelbands.)

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder.rb#L112 needs to ensure that cases where `Recording` child resources of `Recordings` properly generate IIIFv3 manifests for `ArchivalMediaCollections`.

**Comment by jrgriffiniii** [comment]
The manifests generated by https://github.com/pulibrary/figgy/compare/issues-3156-jrgriffiniii-uv-recording-coll seems to work in the UV (http://universalviewer.io/examples/#?c=&m=&s=&cv=1&manifest=https%3A%2F%2Ffiggy-staging.princeton.edu%2Fcollections%2Ff50f1a65-ca8f-4b4c-a68d-2185f16410d7%2Fmanifest&rid=https%3A%2F%2Ffiggy-staging.princeton.edu%2Fconcern%2Fscanned_resources%2F62d81c53-5e12-4c42-bfc1-72ff4034c861%2Fmanifest%2Frange%2Fre62c0deb-54a5-4d47-9f44-36ec856c6b24), but the generation of these is incredibly slow.

**Comment by tpendragon** [comment]
I'm unable to navigate to the other manifests using that link

**Comment by jrgriffiniii** [comment]
I've fixed the performance by avoiding recursion, but somehow I am getting `manifests` as the `Collection` property (this should be `items`: https://iiif.io/api/presentation/3.0/#51-collection):
![image](https://user-images.githubusercontent.com/1443986/60222111-21962280-984a-11e9-8c40-1f8653e4f791.png)

**Comment by jrgriffiniii** [comment]
That might not be related to this bug: https://github.com/samvera-labs/iiif_manifest/blob/master/spec/lib/iiif_manifest/v3/manifest_factory_spec.rb#L326

**Comment by jrgriffiniii** [comment]
No, this was indeed unrelated.  When switching these by updating the `iiif_manifest` Gem, the issue was not resolved:
![image](https://user-images.githubusercontent.com/1443986/60264508-5d180780-98b1-11e9-98ad-6021ead586e4.png)

**Comment by jrgriffiniii** [comment]
Attempting to generate these as `Manifests` (rather than `Collections`) does not seem to work either.  I'm able to generate a structure very similar to what is found for Playlists, but within the audio Ranges, some entries are missing labels.

**Comment by jrgriffiniii** [comment]
Fixing cases for `nil` labels in the Ranges seems to help, but I also suspect that cases where audio ranges are mixed with image content triggers a bug in the UV.  For cases where there is mixed media, the following are generated:
```
{
type: "Range",
id: "https://figgy-staging.princeton.edu/collections/f50f1a65-ca8f-4b4c-a68d-2185f16410d7/manifest/range/r431fa59d-89bc-44b8-ad14-a541405f04f9",
label: {
@none: [
"32101047382617_2"
]
},
behavior: "top",
items: [
{
type: "Canvas",
id: "https://figgy-staging.princeton.edu/collections/f50f1a65-ca8f-4b4c-a68d-2185f16410d7/manifest/canvas/408db7d1-d485-43d0-98c4-d881155a9fab#t=0,1835.253",
}
],
},
{
type: "Range",
id: "https://figgy-staging.princeton.edu/collections/f50f1a65-ca8f-4b4c-a68d-2185f16410d7/manifest/range/r3fce3046-1f55-4295-8076-8a0e88068863",
label: {
@none: [
"32101047382617_AssetFront.jpg"
]
},
behavior: "top",
items: [
{
type: "Canvas",
id: "https://figgy-staging.princeton.edu/collections/f50f1a65-ca8f-4b4c-a68d-2185f16410d7/manifest/canvas/a4c54863-7843-4f9d-b566-265d6dfe33ea#t=0,",
}
],
},
```

Perhaps the `#t=0` fragments lead to bugs when they link to image canvases?

**Comment by jrgriffiniii** [comment]
That was the problem!  The number of `Ranges` need to be equal with the number of `Canvases`, and hence both need to have `FileSets` with any images removed for `ArchivalMediaCollection` manifests.

**Comment by tpendragon** [comment]
Reopened: https://figgy-staging.princeton.edu/catalog/f18b98e5-b463-43fe-bb3d-9e2e1a976a89 still doesn't work.

**Comment by jrgriffiniii** [comment]
https://figgy-staging.princeton.edu/catalog/f18b98e5-b463-43fe-bb3d-9e2e1a976a89 is a rendering as a `sc:Collection` (it is a MVW `ScannedResource`).  There are *no* `renderings` in the Manifest, so I suspect that this somehow relates to https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder.rb#L117.  Perhaps it's checking for immediate FileSets (there are none for MVW's) and not recursing to the FileSets on the MVW members.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-3156-jrgriffiniii-mvws should still handle address this case with https://github.com/pulibrary/figgy/compare/issues-3156-jrgriffiniii-mvws#diff-1b1250bce97c96a537197f305d850d71R722, but it's still not working for https://figgy-staging.princeton.edu/catalog/f18b98e5-b463-43fe-bb3d-9e2e1a976a89.  I'll try and diagnose this from within the staging environment.

**Comment by jrgriffiniii** [comment]
For this case, I find the following on staging:

```
irb(main):022:0> res1.id
=> #<Valkyrie::ID:0x000000000c880890 @id="f18b98e5-b463-43fe-bb3d-9e2e1a976a89">
irb(main):023:0> res1.class
=> ScannedResource
irb(main):018:0> res1.decorate.file_sets.length
=> 0
irb(main):019:0> res1.decorate.volumes.length
=> 2
irb(main):020:0> res1.decorate.members.map { |child| child.decorate.members }.flatten.select { |x| !x.instance_of?(FileSet) }
irb(main):021:0> res1.decorate.members.map { |child| child.decorate.members }.flatten.map {|fs| fs.mime_type }
=> [["audio/x-wav"], ["audio/x-wav"], ["application/xml; schema=pbcore"], ["image/jpeg"], ["audio/x-wav"], ["audio/x-wav"], ["application/xml; schema=pbcore"], ["image/jpeg"]]
```

**Comment by jrgriffiniii** [comment]
I see what I was overlooking now, the `change_sets` was set to `recording`, and this was not being handled as a MVW by the changes I introduced.

**Comment by jrgriffiniii** [comment]
The UV functions with the FileSets for https://github.com/pulibrary/figgy/compare/issues-3156-jrgriffiniii-mvws now, but the `posterCanvas` is now being lost.

**Comment by jrgriffiniii** [comment]
The `posterCanvas` (now `placeholderCanvas` in 3.0 Beta: https://iiif.io/api/presentation/3.0/#placeholdercanvas) must be a single value for the entire Manifest, but this is generated now from the first member `Recording`.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera-labs/iiif_manifest/blob/master/lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb#L54 is where the labels should be inserted, but I'm not quite certain why this is not triggered by https://github.com/samvera-labs/iiif_manifest/blob/master/lib/iiif_manifest/v3/manifest_builder/structure_builder.rb#L38
