### ISSUE TITLE
 Stale object error for resources

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3172]
## Implementation

Make sure derivative jobs have fresh references to the resource after each save.

Check honeybadger for other instances of this error.

## Backtrace

    line 75 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/48943330)

---

Stale object errors were fixed for scanned map derivatives (https://github.com/pulibrary/figgy/pull/3136), but not for vector and raster derivatives.

**Comment by tpendragon** [comment]
Fix should be similar to https://github.com/pulibrary/figgy/pull/3136/files. We should test other derivative services that apply an error message too.

**Comment by eliotjordan** [comment]
This is occurring for Scanned Resources as well. 

```
Valkyrie::Persistence::StaleObjectError: The object 2e6c63af-7e2d-4191-a1b6-b4113394ce33 has been updated by another process.
```

https://figgy.princeton.edu/catalog/2e6c63af-7e2d-4191-a1b6-b4113394ce33

**Comment by eliotjordan** [comment]
Stale object error with audio recording: https://figgy.princeton.edu/concern/scanned_resources/e24dd511-f43e-45d3-bfee-234de62509ca/order_manager

**Comment by eliotjordan** [comment]
Latest error on ScannedMap:  `Valkyrie::Persistence::StaleObjectError: The object 9b14cdd5-e996-4089-8572-eee585687324 has been updated by another process.`
