### ISSUE TITLE
6170960 is not a map

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3186]
Convert this to a scanned resource and fix the `See the map` label in the catalog.

https://figgy.princeton.edu/catalog/d58261b2-979b-4e36-865f-6a51727f41ba
https://catalog.princeton.edu/catalog/6170960

**Comment by eliotjordan** [comment]
Also,

(Military chart)
https://figgy.princeton.edu/catalog/1fb630d4-ebd1-4ab8-854e-cf09ff8c9dd6

(Imaginary place)
https://figgy.princeton.edu/catalog/2512e369-1d09-4721-abbc-ce40f810d145
https://figgy.princeton.edu/catalog/0db7c7cb-d9d3-4f81-a89f-76bd7dbc221b

(Incorrect bibid for map)
https://figgy.princeton.edu/catalog/ae5b10f3-9a70-42f1-a0f2-4d07ef16681f

**Comment by tpendragon** [comment]
This will require talking to someone in the maps lab so that it can have the "See the map" label removed from Voyager.

**Comment by eliotjordan** [comment]
Someone from RBSC. It's in the Historic Maps Collection: `HMC01.6568`

**Comment by kelea99** [comment]
reingested: https://figgy.princeton.edu/catalog/9a86eabd-ec92-4401-8f23-288bc5a12be9

original scanned map still flagged and in figgy. emailed Vicki P. and Jen M. for help with getting the "see the map" label removed from the catalog record, @eliotjordan

**Comment by kelea99** [comment]
label has been removed in the catalog record by Jen, @eliotjordan Closing ticket. Please reopen if i missed anything.
