### ISSUE TITLE
Should 6773457 items be maps or scanned resources?

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3191]
Marked as maps, but only covers of books. Also, maybe these should be a MVW?

https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=6773457

**Comment by tpendragon** [comment]
These seem to be some sort of ingest problem. All of those have the same image (same checksum, filename, etc) as the image.

**Comment by escowles** [comment]
I see 26 identical viewers on the catalog page: https://catalog.princeton.edu/catalog/6773457#view

**Comment by tpendragon** [comment]
It seems like the correct version might be https://figgy.princeton.edu/catalog/77c7d8cf-6753-456a-94d5-c7f2349ad02f.

**Comment by tpendragon** [comment]
@eliotjordan Is the question "should this show up in the maps portal"?

**Comment by kelea99** [comment]
related to #1610. closed 1610. @eliotjordan , shall i delete the individual ingests that look to be bad ingests of this item, since we have a completed mapset?

**Comment by tpendragon** [comment]
Deleted the duplicates.
