### ISSUE TITLE
Save and Ingest should ignore hidden files (starting with .)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3194]
It's easy to miss these on the staging server, which can ruin a perfectly good ingest.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-3201-jrgriffiniii-file-mngr-filter-hidden?expand=1#diff-40e48b8cd8a2ae25b69add28897328bdR50 should address this, as "Save and Ingest" invokes methods on the `BulkIngestService` by means of https://github.com/pulibrary/figgy/blob/8d443fa0891e990a7b271abc85d90d0250c71dd7/app/jobs/ingest_folder_job.rb#L11 within https://github.com/pulibrary/figgy/blob/master/app/resources/scanned_resources/scanned_resources_controller.rb#L35

**Comment by jrgriffiniii** [comment]
Closed with https://github.com/pulibrary/figgy/pull/3207
