### ISSUE TITLE
File manager upload should filter out hidden files

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3201]
In one case there was a hidden file for each tiff (about 300). These all ingested and were listed first in the viewer. So when the viewer loaded on the first page, it pops up with an error. Removing each file one at a time in the UI would be prohibitively time-consuming.

**Comment by jrgriffiniii** [comment]
Modifying https://github.com/jrgriffiniii/browse-everything/blob/figgy-issues-3201-jrgriffiniii/lib/browse_everything/driver/file_system.rb#L80 should be the most straightforward, but I'll need to test further in order to confirm this.
