### ISSUE TITLE
Title of Playlist should show in viewer in addition to the title of the track

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3203]
Requested by Dan

**Comment by tpendragon** [comment]
![Screen Shot 2019-07-16 at 11 28 50 AM](https://user-images.githubusercontent.com/2806645/61319822-e9389300-a7bc-11e9-8d6b-490bb717a44d.png)

This is how it looks now.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/tree/issues-3203-jrgriffiniii-uv-viewer-title introduces the title using a GET parameter in the URL, which would result in the following:

![image](https://user-images.githubusercontent.com/1443986/61469150-b3c2af80-a94c-11e9-8185-8e9101ffd4bb.png)

However, it does introduce this into the authorized link:
![image](https://user-images.githubusercontent.com/1443986/61469216-d228ab00-a94c-11e9-8d89-fb03b8e0c20a.png)

This requires the least amount of modification to the code base in the Universal Viewer static page, but it is obviously fragile and results in an even lengthier URL.

**Comment by hackmastera** [comment]
@jrgriffiniii did you look at pulling it from the manifest itself? It would be nice if existing links would keep working and add in the title.

**Comment by jrgriffiniii** [comment]
I've been trying the various events which are triggered by the UV (https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-shared-module/BaseEvents.ts), and I'm failing to find one in which the manifest has been loaded (`Manifold` loads the manifest from the URL on https://github.com/UniversalViewer/universalviewer/blob/master/src/UVComponent.ts#L218 only after . the `RELOAD` event is triggered above on https://github.com/UniversalViewer/universalviewer/blob/master/src/UVComponent.ts#L202).

I will delve a bit further and then ask for guidance on the UV community Slack.

**Comment by escowles** [comment]
I wonder if we could set a label for the page in a header, so the HEAD request we just added could set the title: https://github.com/pulibrary/figgy/blob/master/public/viewer.html#L43

**Comment by jrgriffiniii** [comment]
Using the `HEAD` request was my first approach, but the body is empty.

Perhaps I could request the entire manifest with that as a GET request?  The status shouldn't be different if it is 401/403, and while we would be requesting the entire payload, we are already in the position where we are requesting server responses twice for the manifest.

**Comment by escowles** [comment]
I was thinking we could include it in the HTTP headers, and I think a `Link` header is the right way:

```
Link: <http://url/for/manifest>; rel="self"; title="the object title"
```

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/pull/3212/files#diff-a2a0ef3c9d957fe883a3329e70eed33dR27 restructures the approach in order to use link headers exclusively.
