### ISSUE TITLE
GraphQL Resources should have an Authorization Code and Authorization Message

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3214]
These will return what kind of access the user has to these resources.

Codes:

```
OK,
UNAUTHORIZED,
FORBIDDEN
```

Messages:
```
''
'Princeton Users may log in to view this resource'
'Digital Copy available on request.'
```

Above messages are drafts.

**Comment by hackmastera** [comment]
Maybe something that hedges a bit more like "Contact us for more information about accessing this item"?
