### ISSUE TITLE
List of "my recently deposited" objects with file status

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#3218]
As an imaging tech I need an easy-to-access list of the X (15? 25?) most recent things I have ingested, along with the ingest / processing status of the files (whether there were errors, how many images are finished processing).

Related to #2461 
Related to #3217

**Comment by tpendragon** [comment]
Implementation Options:

List on the front page (requested by Studio)
Display processing in index view, provide some sort of shortcut to it.

**Comment by hackartisan** [comment]
Note: an ingestor can now filter by their name, and then look for date created/modified.
