### ISSUE TITLE
A fixity failure should generate a honeybadger alert

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3221]

**Comment by hackmastera** [comment]
we might also want to update the honeybadger gem; it's been a while

**Comment by hackmastera** [comment]
I'm confused how this relates to #3285

**Comment by escowles** [comment]
I don't think we should fire a HoneyBadger error when we are still retrying, but once we give up retrying is when the error should be sent out so a human will notice it.

**Comment by hackmastera** [comment]
Another question. should this be for both cloud fixity checks and local?

**Comment by escowles** [comment]
Yes, I think it would be good to handle both local or cloud fixity failures.
