### ISSUE TITLE
Add documentation link to the front page of figgy

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#3224]
Also add link to "best practices" document; link is in the ‘ingesting’ google doc

ADAPT+ meeting

**Comment by sdellis** [comment]
@hackartisan can you provide the "documentation link" and the "best practices link" when you have a chance? I am unable to find the "ingesting" google doc.

**Comment by sdellis** [comment]
Currently blocked until we can resolve which documentation links need to be placed on the homepage.

**Comment by hackartisan** [comment]
The best practices document is this https://library.princeton.edu/digital-collections/digitization-best-practices -- it was developed by the studio and ADAPT thought it would be useful to reference.

@kelea99 could the other documentation link be https://drive.google.com/drive/u/1/folders/1--EaoC-9fCpJx2tW4ej0-SyNNbEBX4MX?

**Comment by sdellis** [comment]
@hackartisan @kelea99 I don't have access to that documentation link, so we would need to make the information public before linking to it.

**Comment by kelea99** [comment]
Access Given, @sdellis ! Those are traning documents and how tos that we developed and use with folks working in Figgy and DPUL. I am happy to move it to a better place to link out to, though?

**Comment by eliotjordan** [comment]
@kelea99  What if we make a confluence page with relevant links?

**Comment by kelea99** [comment]
@eliotjordan that is a great idea, and makes sense.

**Comment by hackartisan** [comment]
New confluence pages are in place, unblocking this issue. The link is https://pul-confluence.atlassian.net/wiki/spaces/IT/pages/1933580/Figgy+PUL+s+Digital+Repository
