### ISSUE TITLE
CI should fail a step if we don't add to release notes

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3228]
This step shouldn't block us from merging, but should force us to think about if something should be added there.

**Comment by hackmastera** [comment]
I looked through offerings in https://github.com/marketplace and didn't see anything that provides a check that a given file was updated.

**Comment by escowles** [comment]
Will a shell script exiting with a failure code make the build fail?

**Comment by hackmastera** [comment]
Oh, hey looks like @tpendragon did this as part of https://github.com/pulibrary/figgy/pull/3231
