### ISSUE TITLE
Archival Media Bag Ingest didn't migrate JPGs for C1557

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3243]
@kellybolding suspects it's because the extension is '.JPG' instead of '.jpg'.

**Comment by kellybolding** [comment]
This also happened for C1372.

**Comment by hackmastera** [comment]
I believe the expected course of action here is:
 - Accept files with extension `.JPG` and ensure they are handled correctly in general
 - Remove these from staging, fix the code, and then re-ingest

Appreciate confirmation or alternate proposal

**Comment by escowles** [comment]
@hackmastera Yes, that sounds right to me.
