### ISSUE TITLE
Hidden files still ingesting

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3247]
See https://figgy.princeton.edu/concern/scanned_resources/b8c1de10-8688-4b7b-a108-9d1057438762/file_manager

This happened when ingesting from Browse Everything.

**Comment by jrgriffiniii** [comment]
I was able to reproduce this by creating a normal directory with a single hidden file, and selecting the entire directory:

![image](https://user-images.githubusercontent.com/1443986/62495257-58454e00-b7a3-11e9-8f14-b8924a5070e4.png)

**Comment by jrgriffiniii** [comment]
This needs release notes
