### ISSUE TITLE
Read-Only User

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3293]
We have talked about having the Reading Room access require both an IP address and a user account.  However, all of the figgy roles we currently have would in theory allow the user to login to figgy and CRUD materials.  We should have a read-only role for this.

**Comment by tpendragon** [comment]
Don't we have a `reading_room` role for this?

**Comment by escowles** [comment]
The original request was for requiring both the IP address and a shared account.  The reading_room functionality that I see requires the IP address, but doesn't require a login at all.  Am I missing something?

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/blob/5a825cca273958394fd93eb052fbea27e2b7a9cf/app/models/ability.rb#L194 requires that they have the `reading_room` group

**Comment by escowles** [comment]
👍 — sorry I missed that, looks like we do indeed already have this.
