### ISSUE TITLE
When I delete a fileset there should be a tombstone for it

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3309]

**Comment by hackmastera** [comment]
attributes/properties:
 1. GCS metageneration #, since the file will be only in versioned storage
 1. the label from the FileSet
 1. original_filename of FileSet
 1. the date FileSet was deleted (possibly derived from created_at or updated_at)

**Comment by hackmastera** [comment]
Only create tombstones for things that were preserved?

**Comment by escowles** [comment]
@hackmastera I was originally going to say we should only create tombstones for things that were preserved.  But it does seem like it would be nice to have a record of deletion for uncompleted or otherwise not-preserved things.

**Comment by hackmastera** [comment]
If the parent itself is deleted, we don't want the file set to have a tombstone (there's nothing to restore it onto).
