### ISSUE TITLE
Submitting an invalid source metadata identifier should result in the edit form being displayed with an error message

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3331]
## Backtrace

    line 19 of [PROJECT_ROOT]/app/validators/source_metadata_identifier_validator.rb: rescue in validate
    line 9 of [PROJECT_ROOT]/app/validators/source_metadata_identifier_validator.rb: validate
    line 74 of [PROJECT_ROOT]/app/controllers/concerns/resource_controller.rb: update

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/53896417)

**Comment by escowles** [comment]
Currently, this produces a 500 "Something went wrong" error

**Comment by tpendragon** [comment]
Hasn't happened again, can't reproduce, closing.
