### ISSUE TITLE
Slug generation for Geo documents without a `held_by` fails.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3334]
[Figgy/production] NoMethodError: undefined method `parameterize' for nil:NilClass
## Backtrace

    line 20 of [PROJECT_ROOT]/app/services/geo_discovery/document_builder/slug_builder.rb: slug
    line 12 of [PROJECT_ROOT]/app/services/geo_discovery/document_builder/slug_builder.rb: build
    line 15 of [PROJECT_ROOT]/app/services/geo_discovery/document_builder/composite_builder.rb: block in build

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/53928941)

**Comment by eliotjordan** [comment]
This was not supposed to happen. I'm guessing that this occurred before `held_by` was assigned a default value.

https://github.com/pulibrary/figgy/blob/master/app/change_sets/concerns/geo_change_set_properties.rb#L9

I'll search for nil values and replace them.

**Comment by eliotjordan** [comment]
This affected 18 raster resources and 2 vector resources. These were fixed and this should no longer be an problem.
