### ISSUE TITLE
Resources should create a Tombstone when they're deleted

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3347]
## Success Criteria

On delete, a tombstone is made, it includes:

Deleter, deleted_at, resource, and a cache of the preservation object. Propagate functionality from FileSet.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/pull/3335 seems to have advanced this pretty far.  Should this be generalized for all Figgy `Resources`?
