### ISSUE TITLE
I should be able to restore a resource from its tombstone

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3349]
## Success Criteria

There's a job which can take a resource tombstone and restore it. Should work similarly to FileSet restore.

**Comment by jrgriffiniii** [comment]
I'm currently able to restore a `FileSet`, but without it's `FileMetadata` (please see https://github.com/pulibrary/figgy/compare/issues-3349-jrgriffiniii-restore-tombstones?expand=1).

I can certainly try to reconstruct the `FileMetadata` for the original file from the `PreservationObject` `FileMetadata`, but I just wish to confirm that this would be desireable.

**Comment by tpendragon** [comment]
I think a FileSet is handled by https://github.com/pulibrary/figgy/pull/3351. A resource would probably use the BlindImporter.

**Comment by jrgriffiniii** [comment]
I've started with this, but I needed to get tombstones generated with: https://github.com/pulibrary/figgy/commit/21fc9f28954564fb67ea9a8b46f7d54b8832c651

**Comment by eliotjordan** [comment]
Closed by https://github.com/pulibrary/figgy/pull/5609
