### ISSUE TITLE
Tombstones should be excluded from search

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3360]
[Figgy/staging] ActionView::Template::Error: undefined method `can_have_manifests?' for Tombstone:Class

## Backtrace

    line 35 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: geo_thumbnail?
    line 94 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: figgy_thumbnail_method
    line 26 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: figgy_thumbnail_path

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/54458804)

**Comment by christinach** [comment]
This error was triggered again. https://app.honeybadger.io/projects/53391/faults/54458804
https://github.com/pulibrary/figgy/blob/master/app/helpers/thumbnail_helper.rb#L35

**Comment by hackmastera** [comment]
Created #4153 for the new instance of the HB error.
