### ISSUE TITLE
[Figgy/production] ActionView::Template::Error: undefined method `titleize' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3370]
## Backtrace

    line 36 of [PROJECT_ROOT]/app/helpers/catalog_helper.rb: render_visibility_label
    line 3 of [PROJECT_ROOT]/app/views/catalog/index.html.erb: _app_views_catalog_index_html_erb__3829233171941171972_102320200

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/54822343)

**Comment by hackmastera** [comment]
this was fixed in #3371; data cleanup is #3374

**Comment by escowles** [comment]
I updated all of the Toni Morrison items to be `restricted` or `reading_room` instead of `private`, so I thought the data cleanup would be done now, too.
