### ISSUE TITLE
BrowseEverything is ingesting non-existent BMP files from Google Drive

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#3378]
This behavior was reported by a user:
```
I have some files that I am uploading from google drive that are originally tiffs but are ingesting as bmps. Anyone have any idea why that might be happening?

this record https://figgy.princeton.edu/catalog/c4865c2f-01d5-42c3-ab2e-2ee61ea35199
```

The BMPs appear to have been uploaded with TIFFs:
![image](https://user-images.githubusercontent.com/1443986/65162303-08df7800-da07-11e9-9f9c-6d07e492cacc.png)

The user confirms that these BMP files do not exist in the Google Drive Folder.

**Comment by jrgriffiniii** [comment]
I'm now not certain that this is related to `browse-everything`, as I could not reproduce this using Google Drive Folders containing image files in the TIFF.

**Comment by tpendragon** [comment]
@jrgriffiniii Can we check in with the user again? Who was it? Otherwise, can we close this until it happens again?

**Comment by jrgriffiniii** [comment]
https://library.princeton.edu/staff/ccleeton reported the issue, I can check with them and close this if it is no longer occurring.
