### ISSUE TITLE
PDF not generating Arabic script correctly

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/figgy#3379]
I got some user feedback indirectly (copied below).  I haven't verified it myself but I have responded to the user that we are looking into it. --Joyce 

Brief Description: error in arabic script titles in autogenerated pdfs of digitized mss

Comment: The autogenerated cover sheet for the pdf of a ms that I downloaded renders the Arabic script title with unconnected words (Arabic is never written in this way, and it is basically unreadable). Not sure if this is a problem you have identified already, but I think it would be important to fix it. I can send a picture of the coversheet if you’d like, but I can’t attach anything in the online formula I am using to send this. Best, Paul Babinski

**Comment by kelea99** [comment]
@tpendragon I can review the Arabic, if needed. Just let me know.

**Comment by tpendragon** [comment]
Closing as there's no example.
