### ISSUE TITLE
[Figgy/production] ActionView::Template::Error: bad URI(is not URI?): Newspaper Issue/

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3380]
## Backtrace

    line 24 of [PROJECT_ROOT]/app/resources/ephemera_terms/ephemera_term_decorator.rb: internal_url
    line 28 of [PROJECT_ROOT]/app/resources/ephemera_terms/ephemera_term_decorator.rb: uri
    line 39 of [PROJECT_ROOT]/app/decorators/application_decorator.rb: []

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/55083926)

**Comment by hackmastera** [comment]
It seems like the records weren't properly cleaned up after deletion of the subject. Should be taken care of by `CleanupTerms` change set persister class?

**Comment by eliotjordan** [comment]
A related issue I think: https://app.honeybadger.io/projects/53391/faults/55098084

**Comment by eliotjordan** [comment]
Resolved.

**Comment by hectorcorrea** [comment]
This issue is happening again: https://app.honeybadger.io/projects/53391/faults/55083926. Visiting the URL https://figgy.princeton.edu/catalog/92518d3e-f2b4-441a-889e-029f46911beb results in an error page

Error points to:

```
ActionView::Template::Error: bad URI(is not URI?): "investments,Foreign::Economics"

    ephemera_term_decorator.rb 24 internal_url(...)
    [PROJECT_ROOT]/app/resources/ephemera_terms/ephemera_term_decorator.rb:24:in `internal_url'

    return Array.wrap(model.uri).first if vocabulary.blank?
    vocabulary_uri = vocabulary.uri.to_s.end_with?("/") ? vocabulary.uri.to_s : vocabulary.uri.to_s + "/"
    URI.join(vocabulary_uri, URI.escape(camelized_label))
  end
```
