### ISSUE TITLE
Vocabulary form should not have itself as an option for parent vocabulary

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3384]
<img width="776" alt="Screen Shot 2019-09-23 at 9 35 58 AM" src="https://user-images.githubusercontent.com/2806645/65444751-921af400-dde5-11e9-9a39-117ce8274302.png">

**Comment by hackmastera** [comment]
Seems like some help text and a label change would also be good.

**Comment by tpendragon** [comment]
This broke Ephemera Folder Manifest generation because a vocabulary was its own parent.
