### ISSUE TITLE
Change "Vocabulary" label when editing a Vocabulary to say "Category", add help text.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3385]
<img width="776" alt="Screen Shot 2019-09-23 at 9 35 58 AM" src="https://user-images.githubusercontent.com/2806645/65444802-b080ef80-dde5-11e9-94ba-e0064638646e.png">

**Comment by hackmastera** [comment]
We should user test the actual label. Maybe "Parent Vocabulary" would be more helpful.

Also consider adding help text.

**Comment by tpendragon** [comment]
I think we should actually change this to work more like MVWs, where you only get that box when you're creating a category, and you don't get it when editing.
