### ISSUE TITLE
Initial views for some large images are not displaying

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3389]
It has been noticed that for some scanned maps, the initial view in the UV does not display. The image only appears after zooming in.

https://figgy.princeton.edu/catalog/c865c987-8d95-4069-bc9d-79ebe2e554dc
https://figgy.princeton.edu/catalog/ea8c0067-47b2-4f67-a92d-03479b2ac939

OpenSeadragon logs similar errors to the console for all cases:

```
Tile a.Tile failed to load: https://iiif.princeton.edu/loris/iiif/2/figgy_prod%2F9f%2Fa4%2F34%2F9fa4343f064840cab4eb6436cd3387c7%2Fintermediate_file.jp2/full/1,/0/default.jpg - error: Image load aborted
```

Notice the IIIF request with a width of 1px.

**Comment by tpendragon** [comment]
Ah, we thought this was fixed but that's probably the same issue as https://github.com/pulibrary/pomegranate/issues/265

**Comment by eliotjordan** [comment]
So... using Cantaloupe was/is the solution?

**Comment by tpendragon** [comment]
Apparently not! Since we're in Cantaloupe in production now.

**Comment by tpendragon** [comment]
https://app.datadoghq.com/logs?cols=core_host%2Ccore_service&event&from_ts=1569448240931&index=main&live=false&messageDisplay=inline&query=service%3Acantaloupe+qtp1053782781-531201&stream_sort=desc&to_ts=1569448261398 is a log for one of those. The error is "java.lang.IllegalArgumentException: Unknown image type 0"

**Comment by tpendragon** [comment]
You can see the error happen in raw OSD here: http://tomcrane.github.io/scratch/osd/single-image.html?image=https://iiif.princeton.edu/loris/figgy_prod/08%2F9a%2Fc8%2F089ac8c1afa044a99b1da8cf7690cf79%2Fintermediate_file.jp2/info.json

**Comment by tpendragon** [comment]
https://github.com/openseadragon/openseadragon/issues/980 points to https://github.com/sul-dlss/sul-embed/commit/2850ccaeaab92082f5ec66c3a073e98326c59862 as a potential fix.

**Comment by escowles** [comment]
IIRC, the problem with https://github.com/pulibrary/pomegranate/issues/265 was that one of the dimensions of the image was larger than allowed by the JPEG spec (64k pixels).  That's not the issue with either of the two samples though.

Though I did notice that both of the images were displaying warnings that they had errors generating derivatives.  So I triggered regenerating for one of them, and it's taking several minutes.  We'll see if it completes or if there is an error we can fix.

**Comment by escowles** [comment]
Followup: Looks unrelated.  The derivatives did finish regenerating for https://figgy.princeton.edu/catalog/ea8c0067-47b2-4f67-a92d-03479b2ac939  but it still doesn't display initially.

**Comment by eliotjordan** [comment]
I created a record in figgy-staging to reproduce the error:
https://figgy-staging.princeton.edu/catalog/7e2b4368-3453-4d2d-a8df-1cb0da12685c

Tried the `immediateRender` trick, but no luck.
https://github.com/pulibrary/figgy/compare/3389-osd

**Comment by tpendragon** [comment]
I think you put the option in the wrong place, it should be in seadragonCenterPanel right? 
https://github.com/sul-dlss/sul-embed/blob/2850ccaeaab92082f5ec66c3a073e98326c59862/public/uv-config.json

**Comment by eliotjordan** [comment]
Yep. Thanks. Should have looked a little closer!

**Comment by eliotjordan** [comment]
Works. Going to open a PR.
