### ISSUE TITLE
destroy schemas in favor of attribute lists per-model

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#339]
the indirection is confusing; not clear what we gain

**Comment by hackmastera** [comment]
Or some less drastic middle ground.

Pending further discussion.

**Comment by hackmastera** [comment]
In the schema directory, some files serve the purpose of grouping terms into their schema of origin, e.g., `app/models/schema/bibframe.rb` The benefit of these is that they serve as a point of documentation; many (maybe all) of them contain the uri for the term. They also make it easy to answer the question "what public schemas do we use terms from?" or "which terms do we use from X schema?"

Some files collect predicates / attributes by use, e.g. `geo`, `common`, `
- note both of these include other schemas as well

Some merely aggregate others, e.g. `ephemera` and `plum`
- note ephemera schema isn't actually used anywhere; all attributes are already spelled out in ephemera folder model.

There's a nested 'Plum::Local' schema which I find confusing and I think can be flattened out. Just break it out of the plum namespace and call it `schema/local`

@escowles has expressed a wish to avoid cases where we use different properties that mean the same thing, e.g. `created` for one reasource but `date_created` for another.

Note also that currently our schema files do not allow us to set valkyrie types; perhaps that's why the ephemera schema is not currently in use.

**Comment by hackmastera** [comment]
Are there attributes that are truly core between all models? If so, does it make sense to continue grouping them to avoid use of different property names in different places? If so, do we then do away with grouping by source (I think so)?

Can we stop aggregating in every class? Perhaps the schema files are really just lists of terms / types, and each model grabs the ones it needs and runs a few lines of code to create the properties from them.

**Comment by escowles** [comment]
Would getting rid of the aggregate schemas like `Common`, `Geo` and `Plum` be a good first step?  Then it seems like each model would at least be explicitly saying which schemas it wanted, and you would only need to consult that list of files to find a property definition.

If that's too cumbersome, maybe we could just keep `MARCRelators` in a schema, since it's gigantic and included in `Common` now, so probably in everything.

**Comment by tpendragon** [comment]
I think we decided during stand-up to just flatten it all and see how we like that. If we want to break out all the huge lists of shared attributes, I wonder if that points towards moving to a nested object with `descriptive_metadata` or something, and that model can have the entire data dictionary.
