### ISSUE TITLE
Large image raises ImageMagick error

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3395]
## Backtrace

    line 99 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: create_tiff_derivative
    line 95 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: rescue in run_tiff_derivatives
    line 92 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: run_tiff_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/48284921)

```
[Figgy/production] MiniMagick::Error: `identify -format %[channels] /tmp/mini_magick20190926-3600-1jaujs7[0]` failed with error:identify: unable to write pixel cache '/tmp/magick-10190ZlEH4b8t3v9': No space left on device @ error/cache.c/WritePixelCachePixels/5837.
```

```
`convert /opt/repository/files/6f/f4/5e/6ff45ebde7ea4024b04bdf89104c24f3/njgeol_map.tif +compress /tmp/20190927-25438-ud7iku` failed with error: convert-im6.q16: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/912. convert-im6.q16: width or height exceeds limit `/opt/repository/files/6f/f4/5e/6ff45ebde7ea4024b04bdf89104c24f3/njgeol_map.tif' @ error/cache.c/OpenPixelCache/3839. convert-im6.q16: no images defined `/tmp/20190927-25438-ud7iku' @ error/convert.c/ConvertImageCommand/3258
```

FileSet:
https://figgy.princeton.edu/catalog/70a1cd4d-eb04-47da-8708-2e95ac277eb5

**Comment by eliotjordan** [comment]
This particular image is 1.3Gb 29659x 44126 and it's size exceeds ImageMagick height and width limits. The current limits are as follows:

```
deploy@figgy2:/home/pulsys$ convert -list resource
Resource limits:
  Width: 107.374MP
  Height: 107.374MP
  List length: -1
  Area: 32.7436GP
  Memory: 15.2474GiB
  Map: 30.4949GiB
  Disk: unlimited
  File: 74999
  Thread: 4
  Throttle: 0
  Time: unlimited
```
I'm not sure if this problem occurred because those limits were exceeded, or if the server ran out or space or memory as the Honeybadger message indicates.

Options:

1. Raise the resource limits.
1. Ask map studio to reduce the TIFF size
1. Both?

**Comment by tpendragon** [comment]
I think we should try raising the resource limits. The Studio's been wanting to have bigger TIFFs than normal, so figuring out a way to handle them seems important.

**Comment by eliotjordan** [comment]
Closed in favor of https://github.com/pulibrary/figgy/issues/2979
