### ISSUE TITLE
Contributor Role for Ephemera Projects

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3398]
A user with the Contributor Role should be able to:

1. View/Create/Edit Ephemera Folders/Boxes for their Projects.
2. Not be able to see private materials outside of their Project.
3. Be unable to delete in all cases

Implementation Notes:

Three options:

1. Users have a list of Projects they're a member of.
2. Ephemera Projects have a list of "contributor_ids" which are UserIDs. Being part of this list gives one the "contributor" role.
3. Add a "scope" column to the Role model, so that a user can be a contributor for a specific subset of Projects.

Prefer Option 2, but report back if it's difficult.

Caveats:

Implement without worrying about Solr Discovery for now, as it's likely to be difficult and may not be necessary. The majority of the Ephemera use cases are handled via the dashboard, which is solely powered by Postgres. If this turns out to be a problem, we can look more into this.

**Comment by escowles** [comment]
> Be unable to delete in all cases (unconfirmed)

Yes, I think they should not be able to delete at all, and Library staff can handle any deletes.

**Comment by hackmastera** [comment]
What are the implications of implementing without worrying about solr discovery? The contributor will be able to search and will only see public results, and not necessarily the results from the project they are working on?

**Comment by tpendragon** [comment]
> What are the implications of implementing without worrying about solr discovery? The contributor will be able to search and will only see public results, and not necessarily the results from the project they are working on?

Yes. We're assuming they're not going to use the search box.

**Comment by escowles** [comment]
Given the role of service provider these contributors will be receiving training from us on how to use Figgy.  I think it's fine if the search functionality doesn't work as you might expect, since they don't need it to do the metadata entry and ingest work we're hiring them for.
