### ISSUE TITLE
Bounding box selection widget for ScannedMaps is failing to render for certain resources

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3403]
## Backtrace

    line 348 of [PROJECT_ROOT]/app/models/controlled_vocabulary.rb: json
    line 326 of [PROJECT_ROOT]/app/models/controlled_vocabulary.rb: all
    line 3 of [PROJECT_ROOT]/app/views/records/edit_fields/_holding_location.html.erb: _app_views_records_edit_fields__holding_location_html_erb___1664550733401658565_70351313377840

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/54656391)

**Comment by jrgriffiniii** [comment]
This was originally derived from an older issue on Honeybadger affecting the resource https://figgy.princeton.edu/concern/scanned_maps/5ad38aac-05ad-4399-a544-eff73d102f57/edit

**Comment by eliotjordan** [comment]
Error in the browser console:

```
TypeError: Cannot read property 'getNorth' of null
    at BoundingBoxSelector.updateBboxInputs (bounding_box_selector.self-65e50c2f8460b9d0c5c2763333eed945d6f7935b4e569eb240384763bfd151f5.js?body=1:118)
```
