### ISSUE TITLE
Update linked resource factory

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#3404]
Use a more idiomatic factory construction like `LinkedResource.for(resource:)` instead of `LinkedResourceFactory.new(resource:).new`.

**Comment by jrgriffiniii** [comment]
`*Factory.new(resource:).new` was a pattern I've followed based upon what I had observed elsewhere in the codebase (please see https://github.com/pulibrary/figgy/blob/master/app/change_set_persisters/change_set_persister.rb#L33).  I fully support this being refactored into a single class method invocation where appropriate.

**Comment by hackmastera** [comment]
In the change set persister the factories are created in one place and used in another. I think that's when it's appropriate to use a factory class (*Factory). Here, I checked the invocations before writing this ticket, and that's not done. Moving the factory from its own class to a `for` method on the `LinkedResource` class would help differentiate the use case.
