### ISSUE TITLE
All collections manifest won't load when there's an ArchivalMediaCollection.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3409]
## Backtrace

    line 11 of [PROJECT_ROOT]/app/services/manifest_builder/record_property_builder_v3.rb: apply
    line 784 of [PROJECT_ROOT]/app/services/manifest_builder.rb: manifest
    line 15 of [PROJECT_ROOT]/app/services/manifest_builder.rb: build

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/55544171)

**Comment by tpendragon** [comment]
If we don't fix this we can't ingest ArchivalMediaCollections

**Comment by jrgriffiniii** [comment]
I'm sorry, I was attempting to address this as a runner and did not progress with this.  I'm going to de-assign this until I'm finished with the ArcLight sprint (or have some opportunity before then to address it).
