### ISSUE TITLE
Automate exporting Toni Morrison collection as PDFs for reading room machines

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3411]
Blocked by https://github.com/pulibrary/figgy/pull/3170

We should automate the nightly export of the Toni Morrison collection as a local HTML finding aid with links to local PDFs.  This involves a few different tasks:
1. Exporting the Figgy objects as PDFs (see #3170)
2. Adding DAO links to EAD pointing at the exported PDFs (also in #3170)
3. Transforming the updated EAD to HTML (see https://github.com/pulibrary/pulfa-restricted/pull/14)

**Comment by tpendragon** [comment]
Closed in favor of VRR
