### ISSUE TITLE
Remove UpdateFgdcOnlinkJob

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3425]
Remove the UpdateFgdcOnlinkJob from vector and raster derivative services.

Related Pulmap ticket:
https://github.com/pulibrary/pulmap/issues/803

Related Honeybadger (Should help I think):
https://app.honeybadger.io/projects/53391/faults/48943330/9ffa47d8-e6c8-11e9-9796-0780287ebf8f#notice-summary

**Comment by tpendragon** [comment]
@eliotjordan Do with this what you will

**Comment by tpendragon** [comment]
It's gone.
