### ISSUE TITLE
rename "keywords" field to "tags"

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3432]
With fielded search on dpul will have a "keyword" search parameter. If "keyword" is also a field this is confusing to users.

**Comment by tpendragon** [comment]
This will result in two fields in DPUL being named tags. Did someone bring this up? Can we name it something else?

**Comment by hackmastera** [comment]
See #digital-libraries discussion on 10/10. We could name it something else.

**Comment by tpendragon** [comment]
We'll have to be careful that we add some processing to DPUL for this field so that it doesn't override the built in tags field in Spotlight.

**Comment by tpendragon** [comment]
We think this is a good idea, but too much work to be worth it when we can just rename the fielded search label, so we're going to do that.
