### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `attributes' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3442]
## Backtrace

    line 14 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister/apply_remote_metadata.rb: run
    line 179 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: block in before_save
    line 178 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/56088422)

**Comment by tpendragon** [comment]
Hasn't happened in a long time, trace is gone.

**Comment by jrgriffiniii** [comment]
This occurred on 12/03/20, with the following backtrace:

```ruby
apply_remote_metadata.rb  14 run(...)
[PROJECT_ROOT]/app/change_set_persisters/change_set_persister/apply_remote_metadata.rb:14:in `run'
12       return unless change_set.respond_to?(:source_metadata_identifier)
13       return unless change_set.apply_remote_metadata?
14       attributes = remote_record.attributes
15       apply(attributes)
16       change_set
```

Please see https://app.honeybadger.io/projects/53391/faults/56088422#notice-trace for reference.
