### ISSUE TITLE
Improve the process for creating and attaching monograms

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3449]

**Comment by jrgriffiniii** [comment]
The approach which I've undertaken https://github.com/pulibrary/figgy/compare/issues-3449-jrgriffiniii-monograms-issue-form, while more visually consistent, is deeply flawed given that the form helpers which are provided are inconsistently creating Monograms and Places as nested and unnested resources. I can look at trying to work with existing form helpers to create first-order unnested resources using AJAX, or take a more Vue-driven approach.

**Comment by jrgriffiniii** [comment]
This is mostly finished, but I'm currently struggling to get this passing just on CircleCI. Updating the versions of Google Chrome and chromedriver does not get the following breaking test to pass: https://circleci.com/gh/pulibrary/figgy/23352#tests/containers/3.

I am able to ensure that this test is passing in my local environment.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/commit/c0ba9d90df2a4eb179a751b74f7f3de6f270138c was necessary to get the tests passing. I am uncertain as to what triggered this in the CircleCI environment, but the DOM is actually rendering the Vue components. This was tested within an SSH session for the CircleCI container.
