### ISSUE TITLE
EphemeraFolder/EphemeraProject/EphemeraBox should preserve.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3454]
When a box is marked "all complete" it should preserve all of its folders.

When a box is marked "all complete" it should preserve.

When a folder is marked complete, it should preserve.

A project should preserve immediately. They don't have states.

**Comment by eliotjordan** [comment]
Do we really want to change the current state of Ephemera Preservation?

The current situation:
1. EphemeraProjects always preserve. Just metadata, no state.
2. EphemeraBoxes always preserve. Just metadata.
3. EphemeraFolders preserve when they are marked "complete"
4. Marking an EphemeraBox as "all_in_production" will propagate the "complete" state to all folders and they will preserve themselves.

This all seems fine to me. There are many Boxes in a non "all_in_production" state and it is probably a good idea for Folders to be preserved when complete despite the state of the Box.

**Comment by tpendragon** [comment]
The current state has evolved a lot! Have you checked the preservation store to make sure this all happens? I wasn't aware 4 was true, for instance.

**Comment by eliotjordan** [comment]
@tpendragon I'm pushing up a PR that adds tests for 2 and 4.

**Comment by eliotjordan** [comment]
@tpendragon Pretty sure that this is covering 4:
https://github.com/pulibrary/figgy/pull/5726/files#diff-e853398d3115ab6b67081bc92741745dc2c7c39c66bd78c205381f1ea4b45c30R58

**Comment by tpendragon** [comment]
@eliotjordan What happens to folders added to all_in_production boxes after it's marked? Maybe that doesn't happen - does it @kelea99 ?
