### ISSUE TITLE
Intermittently failing spec in RasterResourceDecorator

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3467]
https://circleci.com/gh/pulibrary/figgy/21801
```
Failures:

  1) RasterResourceDecorator exposes markup for rendered coverage
     Failure/Error: h.bbox_display(display_coverage)
     
     NoMethodError:
       undefined method `bbox_display' for #<#<Class:0x0000560843db1720>:0x0000560843a3daf8>
       Did you mean?  display
     # ./app/resources/raster_resources/raster_resource_decorator.rb:70:in `rendered_coverage'
     # ./spec/resources/raster_resources/raster_resource_decorator_spec.rb:29:in `block (2 levels) in <top (required)>'
```

**Comment by hackmastera** [comment]
Could be related to #1854; seems like the same sort of accessing helper from a decorator issue.

**Comment by tpendragon** [comment]
I found a seed that causes this, I'm running `rspec --bisect` now. The branch is `puo_structure`, and the seed is `47790`

**Comment by tpendragon** [comment]
The bisect never finished. It threw a stack trace, then setting an environment variable let it run, but it never got through the first test run. :(
