### ISSUE TITLE
Disallow bulk ingesting of resources as complete

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3477]
This seems to be happening with scanned maps and other Geo resources. This is causing issues with:

1. Publishing incomplete records and records with file-related errors to Pulmap.
1. Needlessly minting ARKs for records that are later deleted or duplicated.
1. Triggers multiple preservation events for each resource.

**Comment by tpendragon** [comment]
@eliotjordan Still a problem?

**Comment by tpendragon** [comment]
Closed in favor of #5579
