### ISSUE TITLE
Automate export of Cicognara metadata for Getty Research Portal

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3483]
We should export metadata from the Cicognara collection periodically so Getty can harvest it.

We'll have to communicate with our Getty Stakeholder Adam Brin

Questions for Adam:

1. How often do you want updates from us? Answer: However often you want to send them, but OAI is quarterly.
2. Do you have an automated process? Can we put the files somewhere you periodically check? Answer: Only via OAI-PMH. Otherwise send emails.

We've decided to implement OAI-PMH through #3128.

**Comment by hackmastera** [comment]
I have an email from Annie Rana dated 3/4/2019 that says "The methods by which the Portal can receive contributions have been updated to via email attachment or OAI harvest (we’ve struck the API repository and FTP methods)"

However, the current Getty documentation (which you can navigate to from the cicognara site) Does still list FTP
http://www.getty.edu/research/tools/portal/guidelines.html.

So it seems like the questions above still stand!

**Comment by tpendragon** [comment]
We're now shipping this via OAI.
