### ISSUE TITLE
BrowseEverything upload failures

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3487]
## Backtrace

    line 124 of [PROJECT_ROOT]/app/services/file_appender.rb: rescue in create_node
    line 112 of [PROJECT_ROOT]/app/services/file_appender.rb: create_node
    line 131 of [PROJECT_ROOT]/app/services/file_appender.rb: block in file_nodes

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/57254740)

**Comment by hackmastera** [comment]
resolved by #3484
