### ISSUE TITLE
Delete resources stuck in a bad "pending uploads" state

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3488]
[Figgy/production] ActionView::Template::Error: undefined method `first' for nil:NilClass

## Backtrace

    line 9 of [PROJECT_ROOT]/app/models/pending_upload.rb: original_filename
    line 13 of [PROJECT_ROOT]/app/views/base/_pending_uploads.html.erb: block in _app_views_base__pending_uploads_html_erb__3568314398988254467_70184313985700
    line 10 of [PROJECT_ROOT]/app/views/base/_pending_uploads.html.erb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/57256942)

Resource https://figgy.princeton.edu/catalog/3caad915-5768-4d51-ad21-f85f944105e8 says it has a pending upload but jobs queue is empty.

**Comment by hackmastera** [comment]
This was a result of #3487

**Comment by hackmastera** [comment]
There are a bunch of these, looks like 4 clumps of 30-ish so ~120.

**Comment by hackmastera** [comment]
I think we can find all these with `qs.custom_queries.find_by_property(property: "title", value: nil)`; haven't confirmed that retrieves the one in question, though. Also not sure if it will retrieve more than we're looking for. may need to further limit by created today.

**Comment by tpendragon** [comment]
Querying for nil with that query doesn't work unfortunately. It finds everything, weird side effect of the contains operator.

**Comment by hackmastera** [comment]
😆 no wonder it got hung up. I guess we should just look for resources with the pending uploads status. Maybe use read-only mode to ensure nothing is actually being ingested.

**Comment by jrgriffiniii** [comment]
Resources which have `PendingUploads` as members have these removed with https://github.com/pulibrary/figgy/blob/master/app/services/file_appender.rb#L175. An error should be raised with https://github.com/pulibrary/figgy/blob/master/app/services/file_appender.rb#L68 in order to prevent this from occurring, but this is not occurring (hence, while HoneyBadger notifications do not report these failures).

I would propose that `PendingUploads` should not be removed if there are such failures, and such failures should be explicitly logged.

**Comment by hackmastera** [comment]
I think these bad resources are still there; they show up in a blank search result if you page back far enough. I'm not sure how to retrieve them, though, and I'm not sure how far back you'd have to page at this point.

**Comment by tpendragon** [comment]
We haven't had any new ones since 2020, and most of them were from the same date. I did this to get rid of them:

```ruby
resources = ChangeSetPersister.default.query_service.custom_queries.find_by_property(property: :metadata, value: {pending_uploads: [{}], stat
e: ["pending"]})
resources = resources.select{|x| x.member_ids.length.zero?}
resources.each do |resource|
  ChangeSetPersister.default.delete(change_set: ChangeSet.for(resource))
end
```
