### ISSUE TITLE
UV at `/viewer` errors if given a manifest outside of Figgy

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3489]
This causes problems with Cicognara. It's caused by the config lookup we added to it.

Example: https://figgy.princeton.edu/viewer#?manifest=https%3A%2F%2Fdigi.ub.uni-heidelberg.de%2Fdiglit%2Fiiif%2Fpacichelli1693%2Fmanifest.json

**Comment by escowles** [comment]
[This line](https://github.com/pulibrary/figgy/blob/master/public/viewer.html#L68) should probably be:
1. If the manifest is from Figgy, use the builtin config based on the Figgy ID
2. If not, check the config parameter and use that
3. Else use a default config
