### ISSUE TITLE
PULFA export crashes when an EAD can't be found

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3499]
There are some Figgy objects linked to PULFA metadata that have a collection code (AC112.02) that doesn't map 1-to-1 to an EAD file on disk. When the EAD file can't be found, the export crashes.

**Comment by hackmastera** [comment]
Is this related to https://app.honeybadger.io/projects/53391/faults/57237823?

**Comment by escowles** [comment]
Yes, that error is what happens when it tries to parse an EAD with a `nil` filename
