### ISSUE TITLE
Bulk ingest of PDFs not pulling source metadata

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3505]
When bulk ingesting PDFs it's not pulling the metadata identifier from the folder name, and instead just naming it after the file that's being ingested.

To test this is fixed:

Ingest a folder of PDFs from https://figgy.princeton.edu/bulk_ingest/scanned_resource in the structure
```
- Parent Folder (selected)
  - 123456
    - file.pdf
  - 802310
    - file2.pdf
```

Ensure that the ScannedResources it creates are set with the SourceMetadataIdentifier `123456` and `802310`

**Comment by tpendragon** [comment]
This needs to be done by the end of the year for ingest of material for Annalise (aberdini in Slack)

**Comment by hackmastera** [comment]
@tpendragon just so I am understanding this issue, can you confirm: The result is a blank `source_metadata_identifier` field and instead a title pulled from the file name.

**Comment by tpendragon** [comment]
Yes, that's accurate.

**Comment by jrgriffiniii** [comment]
I am sorry, I haven't actually tested this with the BE upgrade, but I will investigate this further.
