### ISSUE TITLE
Bad Tiffs

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3509]
https://app.honeybadger.io/projects/53391/faults/44396418

Set of bad TIFFs is causing an error during PDF generation. Error for all of these is similar to:

```
failed with error: convert: Invalid TIFF directory; tags are not sorted in ascending order. `TIFFReadDirectoryCheckOrder' @ warning/tiff.c/TIFFWarnings/1000. convert: ASCII value for tag "Make" contains null byte in value; value incorrectly truncated during reading due to implementation limitations. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/1000. convert: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1000. convert: Read error on strip 2355; got 632 bytes, expected 4120. `TIFFFillStrip' @ error/tiff.c/TIFFErrors/652.
```

https://figgy.princeton.edu/catalog/parent/2b9c1aac-5a2b-4e78-a79a-d5c0c8ff63e6/e52478ef-dc55-4287-b6dd-a101b959da4d

https://figgy.princeton.edu/catalog/parent/2b9c1aac-5a2b-4e78-a79a-d5c0c8ff63e6/4a062dda-c0dd-44db-9ac2-d78d57f3cf1e

https://figgy.princeton.edu/catalog/parent/2b9c1aac-5a2b-4e78-a79a-d5c0c8ff63e6/bf319492-196f-42c3-ad3f-6835f19c17f6

https://figgy.princeton.edu/catalog/parent/2b9c1aac-5a2b-4e78-a79a-d5c0c8ff63e6/b80561c6-c1a6-46ef-8d16-5708a5a6a5e2

**Comment by eliotjordan** [comment]
@roelmoon Images 177 - 180 are corrupt on this record.

https://figgy.princeton.edu/catalog/2b9c1aac-5a2b-4e78-a79a-d5c0c8ff63e6

**Comment by roelmoon** [comment]
These were done in 2013. We can ask Crowley to redo, or we can do it if we can get the microfilm from Special Collections.

**Comment by kelea99** [comment]
@eliotjordan asking Colleen B. to rescan this. transferring issue to Microforms colleagues

**Comment by kelea99** [comment]
Got the go ahead from Eric.  @roelmoon is contacting AnnaLee to add this to the patron/priority request pipeline w/preservation review for the actual manuscript versus the film.

**Comment by kelea99** [comment]
@roelmoon  - AnnaLee has it in the queue for photography, but not a priority.

**Comment by tpendragon** [comment]
https://figgy.princeton.edu/catalog/569a0459-8e2b-4209-82f5-4de94617436b
