### ISSUE TITLE
Enable retries in Google Cloud Strorage preserver

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3510]
## Backtrace

    line 91 of [PROJECT_ROOT]/app/services/preserver.rb: preserve_metadata
    line 30 of [PROJECT_ROOT]/app/services/preserver.rb: preserve!
    line 11 of [PROJECT_ROOT]/app/jobs/preserve_resource_job.rb: block in perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/56532601)

**Comment by eliotjordan** [comment]
Not sure how to do this with the Shrine adapter, but the underlying google cloud gem allows it:
https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google-cloud-storage.rb#L139

From the docs:

```
Unavailable indicates the service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff
```

https://www.rubydoc.info/gems/google-cloud-core/0.20.1/Google/Cloud/UnavailableError

Sidekiq jobs are retried and succeed, but raise the `Google::Cloud::UnavailableError: Server error` exception in Honeybadger.

**Comment by tpendragon** [comment]
Weirdly, you can't pass in your own GCS storage object. We'll probably have to patch the upstream Shrine project: https://github.com/renchap/shrine-google_cloud_storage. Code to fix will be here: https://github.com/renchap/shrine-google_cloud_storage/blob/master/lib/shrine/storage/google_cloud_storage.rb#L20
