### ISSUE TITLE
Streamline and automate static collection export for Special Collections reading room

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3516]
Currently, there are two collections that we export to disk as a static HTML finding aid which links to PDFs of digital objects exported from Figgy. The process is currently implemented as a shell script that does a few different things:
* One rake task (`export:collection_pdf`) which exports PDFs of Figgy objects in a collection
* A second rake task (`export:pulfa_pdf`) which updates the EAD to have DAO links to those PDFs
* Uses XSLT from another repo (pulfa-restricted) to transform the EAD to a static HTML page
* Syncs CSS/JS/etc. assets needed by the static HTML to the output directory
* Reverts the changes to the finding aid

This ticket is to streamline and consolidate this process
- [ ] Merge the [pulfa-restricted](https://github.com/pulibrary/pulfa-restricted) repository into Figgy
- [ ] Create a single rake task to coordinate all of the steps
- [ ] Schedule a Whenever task to export the Morrison and Eliot/Hale collections nightly

**Comment by escowles** [comment]
Also worth noting: updating and then reverting changes to the EAD is not a good pattern — the `export:pulfa_pdf` rake task should read the EAD from its current location and write it to a temp file instead of updating it in-place.

**Comment by escowles** [comment]
Current config:
```
# eliot/hale collection
CID="dc37b1e7-7a1b-4675-87b6-5697a1ad1013"  
DST="/mnt/hydra_sources/archives/hale"      
EAD="$SVN_DIR/pulfa/eads/mss/C0686.EAD.xml" 

# toni morrison collection
CID="b476176b-c189-402c-b50b-edfbdacf423e"  
DST="/mnt/hydra_sources/archives/morrison"  
EAD="$SVN_DIR/pulfa/eads/mss/C1491.EAD.xml" 
```

Script: https://gist.github.com/escowles/6b98b391bfcc4a9d0e60098e91db32ab

**Comment by tpendragon** [comment]
We have a virtual reading room.
