### ISSUE TITLE
broken image; can it be restored?

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3517]
from @ccleeton:

Having an issue with one of the images not displaying here: https://findingaids.princeton.edu/collections/MC016/c8593 This was originally pulled from isilon, is there a way to fix this missing image?

**Comment by escowles** [comment]
I checked this image, and was able to regenerate the derivative without problem. So the image is now showing up in the viewer as expected.

**Comment by ccleeton** [comment]
@escowles So I could have fixed this myself by regenerating??

**Comment by escowles** [comment]
@ccleeton Yes — here's the steps I took:
1. Searched Figgy for the collection code/component ID "MC016_c8593" to find the item, and then verified the image wasn't displaying in Figgy either.
2. Went to the File Manager
3. Clicked the "Regenerate Derivatives" button under the broken image and waited a minute before refreshing and seeing the image was fixed.

**Comment by ccleeton** [comment]
Great!!! Now I know how to fix future issues myself!!

**Comment by hackmastera** [comment]
🎉 thank you @escowles !
