### ISSUE TITLE
Replace callnumber queries to OL postgres with OL api queries in RecordingCollector

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3530]

**Comment by tampakis** [comment]
Given that we are working on ingesting the orchestra performance archive and that most of the records in that collection are already in the Orangelight staging postgres call number browse, we will continue to use the current approach. For future collections, if/when the Orangelight implementation of the call number browse is reimplemented in Solr, the lookup process can be updated.

Initial exploration of this orangelight API lookup approach can be seen in branch: https://github.com/pulibrary/figgy/tree/3530-refactor-ol-cnlookup

**Comment by tampakis** [comment]
Additionally, given the frequency of Solr crashes recently, we did not wish to introduce further load to the infrastructure.
