### ISSUE TITLE
Numismatics Dashboard doesn't show Numismatics Issues

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3534]
The [Numismatics Dashboard](https://figgy-staging.princeton.edu/dashboard/numismatics) is querying for [Numismatics Issue](https://figgy-staging.princeton.edu/catalog?f%5Bhuman_readable_type_ssim%5D%5B%5D=Numismatic+Issue&q=), but they are ingested as [issues](https://figgy-staging.princeton.edu/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Issue&q=).

**Comment by jrgriffiniii** [comment]
This should remain `Issue` in the query, as this approach would be consistent with the one used for `Coins`: https://figgy-staging.princeton.edu/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Coin&q=
