### ISSUE TITLE
Sylvia Beach Papers member resources need to be rotated and reingested

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#3535]
Resources ingested from [Colly (C0108_c3241)](https://figgy.princeton.edu/catalog/9cb35af6-f707-4cb0-ad97-c37e986582b9) and [Philipson (C0108_c3529)](https://figgy.princeton.edu/catalog/9cb35af6-f707-4cb0-ad97-c37e986582b9) need to be rotated 180 degrees and reingested.

**Comment by tpendragon** [comment]
It looks somebody did these two already. @kelea99 I'm going to close this, reopen it if there's still a problem?

**Comment by kelea99** [comment]
Yup. I already did this. THanks!
