### ISSUE TITLE
Numismatic resources are indexed in solr but deleted from db

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#3536]
There are 2 resources in solr that do not exist in the db. we're not sure how they get there, or why they weren't properly cleaned up.

NumismaticAccession "Accession: 1" with id 0e4199ec-99fb-4527-bf0c-ab7276cded85 https://figgy.princeton.edu/catalog.json?f%5Bhuman_readable_type_ssim%5D%5B%5D=Numismatic+Accession&q=

NumismaticReference "CotW" with id 8cf42731-51ff-4147-bb1e-42df37d3d00f https://figgy.princeton.edu/catalog.json/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Numismatic+Reference&q=

These cause a results page to 404, kicking user back to index.

**Comment by tpendragon** [comment]
We're going to be reindexing for Solr 8.2 in the medium-term, so just delete these two instances and the other instances will get cleaned up by reindex.
