### ISSUE TITLE
Document workflows

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#354]
Add wiki docs for the workflows for ingesting books, maps, and ephemera

**Comment by escowles** [comment]
I've added a wiki page documenting the Ephemera and Book workflows: https://github.com/pulibrary/figgy/wiki/Workflow

Additional workflows can be added to that page as they are implemented.

**Comment by escowles** [comment]
@hackmastera @jrgriffiniii Please take a look at the wiki documentation and let me know if it's clear to you.

**Comment by hackmastera** [comment]
Looks good to me, thank you @escowles

**Comment by escowles** [comment]
Thanks @hackmastera !
