### ISSUE TITLE
Document StorageAdapters

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#355]
Documenting what lies within https://github.com/pulibrary/figgy/blob/master/config/initializers/valkyrie.rb#L5, including the use cases outlining precisely why these have been included (e. g. `disk` moves files).

**Comment by escowles** [comment]
I'm not sure what the use case is for moving files (I'd expect Plum ingest to hardlink to the existing files, and new ingest should probably copy the files) — so we may remove some of the options if there isn't a good use for them.

**Comment by hackmastera** [comment]
the link above goes to master and is now stale

**Comment by hackmastera** [comment]
Specifically document the `file_mover` lambda.
Also document copy vs. move vs. link
also document the instrumented adapter.

In-code docs.
