### ISSUE TITLE
Original file missing for file set

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3567]
https://figgy.princeton.edu/catalog/70d8c428-0373-4139-9d02-fc612da6656a

It also has no parent. Is this a broken orphan? It's blocking the fixity check job, so it would be good to resolve it.

**Comment by hackmastera** [comment]
Please resolve https://app.honeybadger.io/projects/53391/faults/38673293 once this file set is fixed or deleted.

**Comment by eliotjordan** [comment]
Looks like it was an orphan. I deleted the FileSet. Also, I've asked the map lab not to bulk import resources as "complete". 

Implementing this issue would help: https://github.com/pulibrary/figgy/issues/3477

**Comment by hackmastera** [comment]
Well that was quick. It looks like there are a few more similar file sets. See the "upcoming fixity checks" section of https://figgy.princeton.edu/dashboard/fixity

**Comment by eliotjordan** [comment]
Removed orphaned FileSets.
