### ISSUE TITLE
Remove numismatic place nested resource

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3580]
This is redundant:

https://github.com/pulibrary/figgy/blob/master/app/resources/numismatics/issues/numismatics/issue.rb#L22

 We now link to a place resource by ID:

https://github.com/pulibrary/figgy/blob/master/app/resources/numismatics/issues/numismatics/issue.rb#L13

**Comment by jrgriffiniii** [comment]
This does not affect the form UI components for creating or editing Issues.

**Comment by eliotjordan** [comment]
This was addressed in this PR: https://github.com/pulibrary/figgy/pull/3581
