### ISSUE TITLE
Rake Task for deleting Solr Documents with missing Resources

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#3588]
There are cases where the Solr collection and PostgreSQL table will fall out of synchronization, and Solr Documents will remain persisted for Resources which have been deleted. It may be beneficial to implement a Rake task in order to address these situations.

**Comment by hackmastera** [comment]
Can you give an example?

**Comment by tpendragon** [comment]
This should be super rare, and if it is we should be able to just reindex occasionally.

**Comment by tpendragon** [comment]
Closed because the intention is this shouldn't happen. If we run into an issue where it does happen, we should figure out why and make it stop.
