### ISSUE TITLE
File upload should work if I selected the file by clicking the name

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3591]
when im trying to select a file to submit for file upload from pudl share to figgy: if i click on the name versus checking the checkbox directly, the system freezes at 10% complete and wont allow me to click submit as an option.

reported by @kelea99 

![Screen Shot 2020-01-16 at 1 06 36 PM (3)](https://user-images.githubusercontent.com/845363/72554493-c9b41d00-3868-11ea-9a84-6c9681b85acc.png)

**Comment by jrgriffiniii** [comment]
This will be resolved for Google Drive with the BrowseEverything upgrade, but I don't believe that this is currently in place for the new UI for the File System driver.

**Comment by jrgriffiniii** [comment]
Apologies for not clarifying this, the new UI is included in the upgrade (please see [the package.json](https://github.com/pulibrary/figgy/pull/3754/files?file-filters%5B%5D=.erb&file-filters%5B%5D=.es6&file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.jsx&file-filters%5B%5D=.lock&file-filters%5B%5D=.rb&file-filters%5B%5D=.scss&file-filters%5B%5D=.sql&file-filters%5B%5D=.vue&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension&file-filters%5B%5D=dotfile#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R16)).
