### ISSUE TITLE
Ensure only 1 PreservationObject is made per Resource.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3592]
We saw a second one get created when re-saving a resource. We cleaned it up already though - just check to ensure this is the case.

## Success Criteria

Write a query to see if there are more than one preservation object with the same resource ID. If so, we have to clean them up and figure out why they're being created.

**Comment by eliotjordan** [comment]
Query run on the console:
```
SELECT metadata #>> '{"preserved_object_id",0,"id"}' as rid, COUNT(*)
FROM orm_resources orm 
WHERE internal_resource = 'PreservationObject'
GROUP BY rid
HAVING orm.count > 1
```

Found 8609 resources with two or more PreservationObjects.
https://docs.google.com/spreadsheets/d/1nhuTwoFj0w8Bsv1OA9Lw2-UK3qDW54nCpqc4Iv4JsUA

**Comment by eliotjordan** [comment]
Example: This [FileSet](https://figgy.princeton.edu/catalog/0002c3b1-ae6a-4a79-a75a-658841356189) has two related PreservationObjects.

b60878bf-05db-4b07-9204-8d18a3eb987d 
dcd45a8e-79e2-4899-9037-a16f2cce28db

**Comment by eliotjordan** [comment]
Query to get created dates in descending order:
```
WITH ids AS (
	SELECT metadata #>> '{"preserved_object_id",0,"id"}' as rid, COUNT(*)
	FROM orm_resources orm 
	WHERE internal_resource = 'PreservationObject'
	GROUP BY rid
	HAVING orm.count > 1
)
SELECT orm.id, orm.created_at, ids.rid
FROM (
	SELECT * FROM orm_resources
	WHERE internal_resource = 'PreservationObject'
	) as orm
INNER JOIN ids	
ON ids.rid = orm.metadata #>> '{"preserved_object_id",0,"id"}'
ORDER BY orm.created_at DESC
```

**Comment by eliotjordan** [comment]
May have found the problem:
https://github.com/pulibrary/figgy/blob/main/app/services/preserver.rb#L78

The wayfinder method is `preservation_objects`, plural. Looks like a new preservation object is created with each save.

**Comment by eliotjordan** [comment]
Most multiple PreservationObjects created for the same Resource resource link to this Coin:
https://figgy.princeton.edu/catalog/6c6994a7-4abd-4b6b-8488-38b128fb70c2

The PreserveResourceJob was queued 5 times in a 4 minute span.

![Screenshot 2022-12-06 at 3 52 28 PM](https://user-images.githubusercontent.com/784196/206032032-7fba5f88-ba02-4b66-9133-a1905a557c6a.png)

**Theory** A Coin is created and marked complete. Changes are made and saved multiple times before any other additional PreserveResourceJobs have completed. A new preservation object is created here on each job invocation:
https://github.com/pulibrary/figgy/blob/1c3e9ae220157e4294b7fde634e0dfec8d27f713/app/services/preserver.rb#L78

**Comment by hackartisan** [comment]
Sounds like a convincing theory!

**Comment by tpendragon** [comment]
Maybe when we queue up a PreserveResourceJob we should pass its optimistic lock token and compare before we do it?

**Comment by eliotjordan** [comment]
@tpendragon Am I understanding your suggestion?

1. Pass the lock token value of the resource to be preserved as a param of in the PreserveResourceJob
1. When the job is run, compare that param value with the current value of the resource.
1. Stop the job if they don't match

Seem like a good idea, although optimistic locking is only enabled for FileSets and ResourceChargeLists. Will prevent most of the multiple PreservationObject instances, but not all.

**Comment by tpendragon** [comment]
I think they're populated on the other resources, just not verified. Worth checking? It was an implementation detail

**Comment by eliotjordan** [comment]
I don't think they are populated in other resources. `enable_optimistic_locking` needs to be added to the model and the `optimistic_lock_token` property needs to be added to the change set.

https://github.com/pulibrary/figgy/blob/b59633f7f96b68e9e2748140245f696de5247d3a/app/models/file_set.rb#L3
https://github.com/pulibrary/figgy/blob/b59633f7f96b68e9e2748140245f696de5247d3a/app/change_sets/file_set_change_set.rb#L4

Only FileSet and ResourceChargeList have this.

**Comment by eliotjordan** [comment]
Ran `PrunePreservationObjectsJob` on all resources with multiple objects. There are no redundant preservation objects in Figgy now, but until #5584 and #5585 are merged, we'll have to periodically clean these up.

**Comment by tpendragon** [comment]
We think there might be a small race condition left over, but don't expect to hit it. We'll deploy #5584 and check to see if we're still getting duplicates.
