### ISSUE TITLE
Browse Everything files come through twice

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3606]
[Figgy/production] NoMethodError: undefined method `split' for nil:NilClass

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/60157535)

**Comment by hackmastera** [comment]
Browse Everthing appears to be passing each file twice: once with a location and once without. The files are serving fine so this either got them all anyway or the user tried again and it worked. But is this intended behavior?

```
Params {
    ...
    "browse_everything" => {"selected_files" => [
    {
      "name" => "cd-6484_01.wav",
      "size" => "66138298",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav"
    },
    {
      "name" => "cd-6484_02.wav",
      "size" => "63387610",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav"
    },
    {
      "name" => "cd-6484_03.wav",
      "size" => "49275586",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav"
    },
    {
      "name" => "cd-6484_04.wav",
      "size" => "47687980",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav",
      "location" => "file_system:/mnt/hydra_sources/music/cd-6000-6999/cd-6484/1133081/cd-6484_01.wav"
    },
    {
      "name" => "cd-6484_01.wav",
      "size" => "66138298",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav",
      "location" => "file_system:/mnt/hydra_sources/music/cd-6000-6999/cd-6484/1133081/cd-6484_02.wav"
    },
    {
      "name" => "cd-6484_02.wav",
      "size" => "63387610",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav",
      "location" => "file_system:/mnt/hydra_sources/music/cd-6000-6999/cd-6484/1133081/cd-6484_03.wav"
    },
    {
      "name" => "cd-6484_03.wav",
      "size" => "49275586",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav",
      "location" => "file_system:/mnt/hydra_sources/music/cd-6000-6999/cd-6484/1133081/cd-6484_04.wav"
    },
    {
      "name" => "cd-6484_04.wav",
      "size" => "47687980",
      "container" => "false",
      "provider" => "file_system",
      "type" => "audio/x-wav"
    }
  ]},
  "controller" => "browse_everything",
  "action" => "resolve"
}
```

**Comment by jrgriffiniii** [comment]
I will investigate this and get this fixed.

**Comment by jrgriffiniii** [comment]
I'm sorry for the delay in providing an update (`yarn` and `solr_wrapper` were delaying me in my local environment). I'm struggling to actually reproduce this behavior.

I have attempted the following:

- Attaching a single file for a ScannedResource
- Attaching multiple files for a ScannedResource
- Bulk ingesting a directory for a single volume ScannedResource
- Bulk ingesting a directory for a single volume ScannedResource (with the directory expanded in the BrowseEverything JavaScript dialogue)
- Bulk ingesting a directory for a MVW
- Bulk ingesting a directory for a MVW (with the directory expanded in the BrowseEverything JavaScript dialogue)

Perhaps this is just specific to audio files? I will look further towards reproducing this with those cases.

**Comment by jrgriffiniii** [comment]
I've also just tried this with a `Recording` specifically. I'm going to need to request a description of the behavior which triggered this before I can propose a solution for this.

**Comment by jrgriffiniii** [comment]
This will be resolved with the BE upgrade.

**Comment by tpendragon** [comment]
We can't find a way to reliably reproduce this. So instead we're going to upgrade BrowseEverything and see if it's reported by users again.
