### ISSUE TITLE
Try attaching more distinguishing properties to attributes

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#361]
To simplify decorators/change_sets we can define the behavior of properties all in the model. This would look something like:

`attribute :title, Valkyrie::Types::Set.optional, show_view: true, iiif_manifest: true, form_multiple: false`

**Comment by tpendragon** [comment]
I think this is a bad idea now - properties should be able to display differently in different contexts. I'm going to close this as I opened it, but someone else can reopen it. @escowles @hackmastera @jrgriffiniii @tampakis @eliotjordan @christinach?

**Comment by escowles** [comment]
👍  #1555 is a good example of a place where we want different behavior for the same fields in different contexts.
