### ISSUE TITLE
Bulk Edits for Late Soviet Posters Ephemera Project

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3613]
## Late Soviet Posters Ephemera Project

Boxes 1-23:

- [x] Add Princeton Slavic Collection as a collection to all folders. (Ephemera Project Title should also appear in DPUL as a collection)
- [x] Mark complete

## Ukraine Crisis and its Aftermath Project:

Boxes 1-16:

- [x] Add Princeton Slavic Collection as a collection to all folders. (Ephemera Project Title should also appear in DPUL as a collection)
- [x] Set Geo Origin to Ukraine

Boxes 1-8:

- [x] Geo Subject to Ukraine

Boxes 9-16:

- [x] Set Geo Subject to Ukraine and Russian Federation

Update: Anna M., Tomas K., and @kelea99

**Comment by tpendragon** [comment]
Priority update: They need this done by the end of the day 01/07/20. If it doesn't show up in the DPUL collection appropriately that's a separate bug we can tackle with a different priority.
