### ISSUE TITLE
Numismatics documentation: Save & Ingest instructions

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3614]
Where should images be staged?
What share should they be on?
What file format?
How should they be named?

**Comment by jrgriffiniii** [comment]
`numismatics/Coin Images - New System` was created and is accessed using the File Manager interface. The name of this folder may need to be updated, and the instructions should detail precisely how users should be uploading the files to the mounted shared.

**Comment by jrgriffiniii** [comment]
Within the directory, there should be a folder with the coin number as the name, with the naming scheme of each file being `obverse.tif` or `reverse.tif`. I can look to use the existing the file name scheme from the `fixtures` directory.

The objective should be to ensure that the users do not need to upload files using the interface, but this should always be an option for resources such as Monograms.

**Comment by jrgriffiniii** [comment]
It should be explicit and clear that images in the TIFF are the supported file format. JPEGs are derivatives generated by Figgy.

**Comment by tampakis** [comment]
Latest update: Numismatics staff are now instructed to save everything in numismatics/CoinImages on the diglibdata1 share. The naming convention will be:
```
12345O.tif
12345R.tif
12345Other.tif
```

**Comment by jrgriffiniii** [comment]
I have updated the draft documentation with https://docs.google.com/document/d/1m1xgKG-44TItxlGIqmF_C-XDoYSnN5UDpqWOQe_SgFs/edit#heading=h.tn9fjfea2px

**Comment by jrgriffiniii** [comment]
I did also add a section for `Monograms` (https://docs.google.com/document/d/1m1xgKG-44TItxlGIqmF_C-XDoYSnN5UDpqWOQe_SgFs/edit#heading=h.6e83x9huk158), however, I could not find any TIFFs on the network share for these (this is an assortment of JPEGs). Do we expect users to upload files for this?

**Comment by eliotjordan** [comment]
@jrgriffiniii Yes they will have to upload monogram image files.

**Comment by tpendragon** [comment]
They have a document.
