### ISSUE TITLE
Text entered in Ruler field is parsed as a UUID

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3615]
Comment on Honeybadger Ticket: `Nikitas entered "Chriss" in Ruler field, and it tried to use it as a UUID`

## Backtrace

    line 23 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: block in log_connection_yield
    line 17 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: log_connection_yield
    line 174 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in find_references_by

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/60427935)

**Comment by tampakis** [comment]
This is also true for the "master" field. These fields need to pull from the numismatic people dataset.
