### ISSUE TITLE
Ephemera project names should be indexed as *_tesim.

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3616]
There are over 1,000 items in the Late Soviet Posters ephemera project: https://figgy.princeton.edu/?f%5Bephemera_project_ssim%5D%5B%5D=Late+Soviet+Posters&q=
However they aren't retrievable by typing the project name in the search box (probably they aren't indexed as text fields, only strings): https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=late+soviet+posters

**Comment by tpendragon** [comment]
Yeah, that's a good call on the text thing. We'll have to change this:

https://github.com/pulibrary/figgy/blob/39151a4b4c6f331c9c9c14a5c4fd229babf4da08/app/indexers/project_indexer.rb#L13
