### ISSUE TITLE
Make more numismatics "dropdown" fields

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3618]
For non-linked metadata fields, change the behavior of the input field to pull from the existing values, while also allowing the submission of new field values. Example fields:
 - object type
 - denomination
 - metal
 - shape (default round)
 - color
 - edge

**Comment by jrgriffiniii** [comment]
These autocomplete input elements should query against Solr. If the values are not available, they should be persisted and retrieved for future requests to create new Issues.
