### ISSUE TITLE
Audit linked numismatics people fields

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3619]
Ruler, master, and artist are examples of these linked fields. In addition, it was requested to add the people dropdown functionality for:
 - provenance
 - accession
 - author (citation/reference?)
 
Check to see how these fields work and assess how easy it would be to make them all behave like artist. Also see #3615 for a related bug.

**Comment by eliotjordan** [comment]
New Drop downs:

Accession
- Person (linked)
- Firm (linked)

Reference
- Author (linked)
