### ISSUE TITLE
Add the ability to duplicate an issue/coin

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3621]
Users would like the ability to clone existing issues/coins with the metadata copied over (besides getting assigned a new accession number).

**Comment by jrgriffiniii** [comment]
This should follow the implementation for the "Save and Duplicate Metadata" form feature supported for Ephemera Folders.

**Comment by jrgriffiniii** [comment]
There should be some additional feedback captured from users before any final changes for the user interface/behavior are provided in response to this.
