### ISSUE TITLE
Display the new numismatics issue and coin number before creating/saving them

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3622]
Numismatics staff reported that they need the issue and coin numbers before photographing the coins. They said it would be helpful to see the issue and coin number before creating/saving the objects.

**Comment by jrgriffiniii** [comment]
Ideally, creating a new Issue or Coin should persist a new resource to the database, and the resulting auto-incrementing accession number should be assigned at this point. We do not wish to offer users the ability to modify or update the accession number; this should be automatically generated.

**Comment by jrgriffiniii** [comment]
The user interface need not be adjusted for the immediate solution to this - the documentation should be updated in order to direct users to just create New Issues and Attach Coins, with the instructions directing them to edit the metadata after these have been persisted.
