### ISSUE TITLE
Saving many files on Order Manager is slow.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3637]
Feedback has been that this costs "hours." Not knowing if something is just being slow or has broken is a problem.

**Comment by kelea99** [comment]
I have had feedback regarding this by individuals now working in Order manager for the past two weeks, @tpendragon. I'd say its worth prioritizing this, since the likelihood of having more people contributing to figgy in this way is high.

**Comment by tpendragon** [comment]
Closed. Feedback from users has been that it's fast enough, they just need to know it's not broken. Opened #3824 instead.

**Comment by kelea99** [comment]
@tpendragon, one of the studio folks working with order manager this morning reported that Figgy is very slow for her when the number of images/items per volume is high. She was able to zip through the items that had 100 or less but this one with 600+ images is dragging--everything is slow to load, bulk edit, typing into the label field, etc. Im checking with the other folks in teams 1 and 2 to see if they are having problems as well.

**Comment by kelea99** [comment]
@tpendragon example of item that is super slow for the user: Lapidus_3424267-01

**Comment by hackmastera** [comment]
The record in question is responding well now.
