### ISSUE TITLE
Provide very obvious information that Figgy is staff-only.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3638]
Maybe this is in the banner, or a message, or something. The home page? I'm not sure, but someone was expecting it to be a digital library portal for patrons.

**Comment by kelea99** [comment]
How about something like this @escowles and @tpendragon? _Figgy is the backend Staff Only Digital Repository system developed at Princeton University Library and is the primary tool used for our digital content management. Once published by staff in Figgy, digital objects are displayed to users in one or more of our many online gateways._

**Comment by kelea99** [comment]
This seems like an easy one to get approved and close quickly to get it off the board.  Not sure who is responsible for reviewing wording, @escowles .

**Comment by escowles** [comment]
👍 I'd be happy to review any language here.

**Comment by kelea99** [comment]
Thankyou, @escowles ! See above.

**Comment by tpendragon** [comment]
The issue that's really happening is people are being sent to either search results or individual records. We suspect that there's things we can do to better position Figgy as a backend-only system - a message won't really get that across.
