### ISSUE TITLE
EphemeraProjects should generate IIIF collection manifests

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#364]

**Comment by tpendragon** [comment]
For DPUL to work a few things need to happen:

https://plum.princeton.edu/iiif/collections needs to list the IIIF collections for ephemera projects

Ephemera Projects need an "Exhibit" metadata item representing the slug in the IIIF manifest. Could be auto-generated?

Ephemera Project manifest URIs need to display child boxes like so: https://figgy.princeton.edu/collections/d7e3a5aa-d15a-4c57-bdc5-d13666673909/manifest

RabbitMQ needs to publish the project slug when a folder/box gets saved.

**Comment by jrgriffiniii** [comment]
> Ephemera Project manifest URIs need to display child boxes

@tpendragon Understood, I was approaching this by attempting to just exposing the Manifests for Ephemera Folders.  I'll restrict this to the level of Boxes

**Comment by tpendragon** [comment]
Boxes will need to be IIIF Collections too (like a MVW), which has child folder manifests.

**Comment by jrgriffiniii** [comment]
> Ephemera Projects need an "Exhibit" metadata item representing the slug in the IIIF manifest. Could be auto-generated?

As discussed during the check-up on 10/13/17, it was decided that slugs should be structured as additional properties.

**Comment by jrgriffiniii** [comment]
After the check-in held on 10/16/17, it was decided that the `slug` property for `EphemeraProject`'s should be required for users (with the value being prepopulated on the form using a form of the `label`).
