### ISSUE TITLE
Evaluate Ephemera Subject Heading entry for trained cataloguers

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3641]
This ticket isn't yet actionable, and is largely here for informational purposes while we figure out what to do. The issue:

* Greek Ephemera is being entered by trained cataloguers rather than students. They want to be able to enter LCSH headings the same way they do in every other system and feel confident that those headings will talk to other systems.

* They want to be able to add new subject headings freely, as they're trained to know how to pick and form them.

Some options discussed:

1. Allow for some Projects to have free-form Subject fields they can just enter text into.
2. Create a new Vocabulary for Greek Ephemera Subjects so they can freely add subject headings to them.
  a. Add a concept of "Shared Vocabularies" maybe? So the large list can be chosen from, but they can add their own things too?
  b. Add a way to quickly create new Terms in a vocabulary from the Folder form, like numismatics?
3. Add an LCSH Term Builder, using id.loc.gov information.
  a. Lots of work, and I kind of want to avoid creating a complex cataloguing experience.

**Comment by kelea99** [comment]
My two cents, @tpendragon:  Looking at Ephemera as a whole and as I understand how it was/is? intended to be used, controlled vocabularies are put in place to ensure that collections may be searched not only within their own collections, but throughout the Ephemera collections as a whole. I like the idea of 2a, where the list at large may be chosen from but (certain?) collections may request adding their own things as well. The requests would then be reviewed by the metadata specialist put in charge by Jennifer (currently Rex) and a decision made for that subject to be added to the controlled vocab.
