### ISSUE TITLE
Ingest Sodargye Lectures from Wayne Bivens-Tatum

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3646]
This is a series of audio recordings along with PDFs that go with them.

**Comment by kelea99** [comment]
We are ingesting these as transcripts become available.   Yuming Sun and Wayne Bivens Tatum are heading this effort. @kelea99 has been doing the ingests. https://dpul.princeton.edu/khenpo_sodargye
Closing ticket.
