### ISSUE TITLE
Implement OAI_DC for France in the Americas

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3649]
The France in the Americas collection currently only holds items that came from bibdata, because that was the only oai we were making available.

Another important set of records for this collection is the Louis-Alexandre Berthier Collection (C0022), which are all from findingaids.

However, we need OAI_DC for all of the items we send to  Bibliothèque nationale de France (BnF), and intend to group them in a single collection (France in the Americas), so the oai_dc needs to handle both types of records.

BnF's documentation:  https://drive.google.com/file/d/1LMy60Dou9uD8LPxXX1UaPyYXaP1Mw1z_/view?usp=sharing (note: `Gallica` is the name of their digital library)

**Comment by tpendragon** [comment]
@kelea99 Which part/collection? And is there info on what kind of metadata they need? OAI_DC? MARC21?

**Comment by kelea99** [comment]
OAI. Lemme get the specs and send them to you via email.  The big collection we are wanting to send with the first batch at the end of this month is the Louis-Alexandre Berthier Collection (C0022).

**Comment by tpendragon** [comment]
I have the docs, we're going to see if we can post it here. The format is OAI_DC, the doc says which fields are necessary on page 8.

**Comment by tpendragon** [comment]
We should be able to implement this by defining `to_oai_dc` on `ScannedResource`

**Comment by kelea99** [comment]
hi, @tpendragon! Got a reminder on my calendar to check in on this one at the end of the month.

**Comment by tpendragon** [comment]
@kelea99 @escowles told me he checked in to inform y'all we wouldn't have time to work on this and was going to chat about alternatives, if I remember right. I don't know if that's changed.

**Comment by kelea99** [comment]
@tpendragon Yup! @escowles check in with us that you probably wouldn't be able to get to it until the end of March, so I thought I would check in at the end of March, so that I would not drop the ball  :)

**Comment by kelea99** [comment]
@tpendragon . got an email forwarded to me from the BNF for something else. can we work it into this sprint?

**Comment by kelea99** [comment]
also see #3496

**Comment by kelea99** [comment]
BnF Document: https://drive.google.com/file/d/1LMy60Dou9uD8LPxXX1UaPyYXaP1Mw1z_/view?usp=sharing
