### ISSUE TITLE
1890 Trenton Sanborns are missing. Re-Ingest & Ensure Figgy Uses existing ARKs

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3650]
These were among the list of missing TIFFs when we ingested into Figgy. Patron is asking for them.

Solutions:

1. Attempt to find the old JPEG2000 derivative images and ingest those.
1. Re-photograph the atlas.
1. Ingest JPEG2000s to start and them re-shoot the maps later.

The last solution seems best.

See 1890 here: https://library.princeton.edu/libraries/firestone/rbsc/aids/sanborn/mercer/trenton.html

**Comment by escowles** [comment]
@roelmoon We think re-photographing this is the best way forward, since otherwise we'd lose the full-resolution images. How much work are these to photograph?

**Comment by tpendragon** [comment]
@kelea99 I'm putting the PO review label on this, can you get a hold of @roelmoon?

**Comment by kelea99** [comment]
yup, @tpendragon . standby.

**Comment by roelmoon** [comment]
Not hard to photograph. Looks like 42 maps?

**Comment by kelea99** [comment]
@roelmoon remembers doing a bunch Sanborn about 10 years ago--tiffs--for John Delaney, who then handed them off to Wangyal for jp2 creation and ingest to GIS.

**Comment by eliotjordan** [comment]
@kelea99 @roelmoon We have the JP2s, but not the tiffs. Chances of finding the original images are pretty much nil at this point. So re-photographing is probably the best way to move forward.

**Comment by kelea99** [comment]
thanks @eliotjordan! @roelmoon was going to have one last quick look on the isilon tonight/tomorrow, just to make sure the Delaney files are not still backed up in an old PUDL collection on it. If nil? then re-photographing should only take a day or so whenever back in the studio.

**Comment by escowles** [comment]
How much work would it be to ingest the JP2s? Given the uncertainty of when we'll be able to rephotograph these, it might  make sense to do that if we really can't find the original TIFFs anywhere.

**Comment by kelea99** [comment]
@eliotjordan : @roelmoon found tiff backups on the isilon for the GIS stuff (what they are, unknown...but there is a lot of them. thousands).   In the PUDL share on the isilon: Its in Vol4_pudl_merged_rm. There are 2 subdirectories there for the GIS Archive (/Volumes/pudl/Vol4_pudl_merged_rm/gis ).  we don't know what the numbers mean post PUmap_xxxx.? Is this what you are looking for? Also @escowles re: JP2 bulk ingest into figgy. Is this a question for us? in theory its doable but would figgy try to create jp2s from the jp2s because that's what it does?

**Comment by eliotjordan** [comment]
@kelea99 I did some digging around. Unfortunately, the images in `/Volumes/pudl/Vol4_pudl_merged_rm/gis` are just copies of images in another Isilon share. I think tracking down and ingesting the JPEG2000 derivatives is the only way to proceed in a timely manner. As far as I know, we don't have a way of ingesting JPEG2000 images directly as original files, but that is something we can work on.

**Comment by kelea99** [comment]
@eliotjordan , alas and I'm so sorry it was a not go with locating the tiffs.  Would it faster for us to convert the jp2s to tiffs pre-ingest for this time, while you all work on the future of jp2 ingest? @roelmoon and/or I could do it, I'm sure?

**Comment by eliotjordan** [comment]
Completed. Images uploaded and links work. 

https://maps.princeton.edu/catalog/princeton-7s75df087

**Comment by tpendragon** [comment]
Good work!

**Comment by kelea99** [comment]
YAY!

**Comment by hackmastera** [comment]
yay!
