### ISSUE TITLE
Swap FileSets on two Scanned Maps

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3651]
There are two scanned maps that need their FileSets swapped. Reported by AnnaLee Pauls:

> we’ve just discovered (with our patron’s help) that there are two records containing swapped digital images. The map associated with the first record here:
>  
> https://catalog.princeton.edu/catalog/6226443
>  
> actually should be swapped with the map attached to the following record:
>  
> https://catalog.princeton.edu/catalog/6226548

**Comment by tpendragon** [comment]
We might be able to just swap the source metadata identifiers and everything will fix itself up.

**Comment by eliotjordan** [comment]
Fixed.
