### ISSUE TITLE
Import New Tiffs and attach to a coin

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3654]

**Comment by christinach** [comment]
numismatics/New Tiffs

**Comment by tpendragon** [comment]
We need to figure out what this ticket is.

**Comment by eliotjordan** [comment]
This is a valid ticket. There is a folder with coin images that need to be connected to their Coin resources. It is now found at
```
numismatics/Archive/New Tiffs
```

**Comment by eliotjordan** [comment]
Done.
