### ISSUE TITLE
Remove Right Sidebar and Copyright fields for Numismatics Forms

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3657]
Numismatics objects are always open access and copyright-free. Users expressed frustration with the amount of space the right sidebar takes up in the form.

**Comment by christinach** [comment]
@tampakis besides the sidebar do we want to remove also :
![Screen Shot 2020-02-12 at 3 31 26 PM](https://user-images.githubusercontent.com/9905193/74374655-d2870880-4dac-11ea-88f1-ac7d6ac2aeb8.png)

**Comment by tampakis** [comment]
Yes
