### ISSUE TITLE
Remove UV from Issue show page and move to Coin show page

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3658]
On the Issue show page, there is a big black box for the UV which never renders if there aren't images attached to the issue's coins.

Move the UV rendering to the coin show page instead because it shows a preview of what the viewer will look like in the public catalog UI.

**Comment by eliotjordan** [comment]
When there are coins, it could be useful to display them together. I wonder if we should instead hide the viewer if there are no attached coins with images.

**Comment by christinach** [comment]
@eliotjordan check also https://github.com/pulibrary/figgy/pull/3090
