### ISSUE TITLE
Add more numismatics dropdown fields

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3661]
Related to #3656 and #3618 

Issues (reverse and obverse):
Figure
Part
Orientation
~~Description (these are more unique, but seeing existing fields would guide the user with the data entry format)~~
~~Attributes name and description~~

Coins:
Holding location
Numismatics collection

**Comment by eliotjordan** [comment]
Attributes names and descriptions can't be easily done as these are multi-valued nested forms. It's possible we can add them later, but I would suggest splitting them off into a seperate issue of lower priority.

**Comment by eliotjordan** [comment]
Description previews are not good because of latency involved with the select widget searching thousands of values. I'm going to split these off into a separate ticket with low priority.
