### ISSUE TITLE
There is no way to clear a field value in a numismatic dropdown field

### ISSUE THREAD

**Issue by tampakis** [pulibrary/figgy#3662]
For numismatics issues, "Color" isn't a commonly used field. The user was unable to leave the field empty after interacting with the edit form dropdown. The color should be removed from this one and the dropdowns should allow the field to be clearable:  https://figgy.princeton.edu/catalog/01c87f6c-e55f-4bd2-8213-f6e6a537406e

**Comment by jrgriffiniii** [comment]
This is likely blocked until https://github.com/pulibrary/figgy/issues/3656 is resolved.

**Comment by eliotjordan** [comment]
I think most of these fields should have a selectable value, whether or not is commonly used or not. It will help to reduce noise in the data. My vote is to leave Color as it is.
