### ISSUE TITLE
Add numismatics dropdown fields for attribute name and description

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3673]
Split off from this issue: #3661

Add dropdown fields for Numismatic Issue:

- Obverse attribute name
- Obverse attribute description
- Reverse attribute name
- Reverse attribute description

This is going to prove somewhat difficult as attributes are multivalued nested properties that are stored as serialized objects in Solr. I'd suggest that this is a lower priority ticket than others at the current time.

**Comment by tpendragon** [comment]
Seems like the strategy would be spin up a custom indexer for attributes so they can be used for the form.
