### ISSUE TITLE
SemVer?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#372]
As we move to production deployment, should we start tagging releases?

**Comment by jrgriffiniii** [comment]
I agree with this proposal, it would certainly benefit both the developers and stakeholders to have an itemized list of improvements or new features between these tagged releases.

**Comment by escowles** [comment]
I have mixed feeling about whether we should tag Figgy `1.0.0` (e.g., Plum never got to `1.0`) or `2.0.0`

**Comment by tpendragon** [comment]
I assume we still plan to change the repo to Plum again, so `2.0.0` is probably best. I've always found it a little weird to semver applications, since backwards compatibility isn't really a concern. If it makes everyone more comfortable though, works for me.

**Comment by hackmastera** [comment]
Would we announce releases, and wait to deploy until we've created a release?

And if we want to do this primarily for the purpose of release notes, we may want to look into some automated release notes generator that uses structured language from commits or PRs

**Comment by tpendragon** [comment]
> Would we announce releases, and wait to deploy until we've created a release?

Major versions maybe? I'm not super convinced this is worthwhile given our interaction with stakeholders and the small audience, though.

**Comment by escowles** [comment]
I'm not sure release notes are going to be useful.  I was mostly thinking it would be nice to be able to identify major releases, list commits since them, etc.

I was mostly thinking that we'd push a new version tag when we were going to deploy to production.  Maybe we could automate that, so pushing a new version tag would trigger the deploy?

**Comment by hackmastera** [comment]
I think @tpendragon has a good point that semver feels weird for an application. It would be good to discuss beforehand what would count as a "backwards incompatible" change. Or maybe we just have numbered releases that aren't semver, just for the sake of having points in time to refer to?

**Comment by escowles** [comment]
And maybe "semver" is too specific (because I agree that backwards-compat is probably not super relevant here).

I was more thinking of keeping track of what we've deployed to production, and in particular marking what's a major/milestone release.

**Comment by hackmastera** [comment]
Then I would expect to always increment up and never be maintaining, like a 3.x and a 4.x at the same time, right?

It would be nice to add to the automation functionality to paste the link to the gh comparison / commit list into slack. or even better into a gh release? idk how easy that would be.

**Comment by escowles** [comment]
@hackmastera Yes, I'm not suggesting that we make any big changes to our dev process, like maintaining multiple branches.

The link to compare against current is pretty easy to build: e.g., https://github.com/pulibrary/plum/compare/v0.1.0...master
