### ISSUE TITLE
Enable the Cloud Build API before April 20, 2020

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3727]
I expect many of us received this email. Links aren't copying over but refer to the email if needed.

Enable the Cloud Build API for your projects before April 20, 2020, to ensure Cloud Function is built and deployed correctly.

Hello Anna,
Starting April 20, 2020, Cloud Functions will use Google Cloud Build, Container Registry, and Google Cloud Storage to build and store your source code, and deploy container image(s) before running them on Google Cloud. You must enable the Cloud Build API for your project(s) to ensure your Cloud Function is built and deployed correctly. Once you enable the API, you may incur charges if your Cloud Build, Container Registry, or Cloud Storage usage exceeds the free tier limits for these products. You can find a list of your projects that are using Cloud Functions and may be affected by this change at the bottom of this email.

What do I need to know?
Using Cloud Build, Container Registry, and Cloud Storage provides the following benefits, including the ability to:
More easily see and debug issues through detailed function build logs in the GCP console.
Use build time that exceeds the current build quota of 120 build-mins/day.
View a built container image for your function in Container Registry.
Cloud Build provides a free tier where only usage above 120 build-minutes per day will be charged. If your usage is within the free tier, you will not be charged for the Cloud Build portion of Cloud Function deployments. Please see Cloud Build pricing for more information.
Similarly, Cloud Storage and Container Registry share a free tier as well. Please see Container Registry Pricing and Cloud Storage pricing for more information.

What do I need to do?
Follow the instructions below to ensure the Cloud Build API is enabled for your Google Cloud project(s) by April 20, 2020.
Access the Cloud Build API link in the Cloud Console.
Select your project from the drop-down menu.
Click Continue to enable the Cloud Build API for the project. A box will appear in the lower-left corner to confirm the API is enabled.

Your affected projects are listed below:
pulibrary-figgy-storage (pulibrary-figgy-storage-1)

If you have any questions or require assistance, please contact Google Cloud Billing Support or Google Cloud Functions support. When contacting support please provide the following:
Project ID
List of cloud functions

Thank you for being a valued Google Cloud Functions customer.
—The Google Cloud Functions Team

**Comment by tpendragon** [comment]
I did this as soon as I got the message. Closing.
