### ISSUE TITLE
We should validate the latest date to be greater than the earliest date

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3731]
We should add a validation where we validate if the latest_date > earliest_date

**Comment by eliotjordan** [comment]
Or validate that `earliest date` is older than `latest date` to account for dates BCE date ranges.

**Comment by christinach** [comment]
I think in the database the BCE dates are displayed with a minus (-). so a math validation will still be valid. 
BCE latest_date : -100     
BCE earliest_date: -300 
`latest_date > earliest_date => true`

**Comment by christinach** [comment]
Will remove my self for now.
