### ISSUE TITLE
Numismatics Form: Invalid latest or earliest date will error the application 

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3732]
@christinach will add an example invalid date here.

## Backtrace

    line 8 of [PROJECT_ROOT]/app/views/numismatics/issues/edit_fields/_object_type.html.erb: _app_views_numismatics_issues_edit_fields__object_type_html_erb__2734315473041151124_148916080
    line 3 of [PROJECT_ROOT]/app/views/base/_form_metadata_inner.html.erb: block in _app_views_base__form_metadata_inner_html_erb__3021096868733550160_148881940
    line 2 of [PROJECT_ROOT]/app/views/base/_form_metadata_inner.html.erb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/61266105)

**Comment by christinach** [comment]
Currently when the user passes an invalid date (earliest or latest ) the application will error.

**Comment by christinach** [comment]
https://github.com/pulibrary/figgy/blob/e9bfa3e6c32b1e99572d293b5fd78ac23fbbc5a1/app/resources/numismatics/issues/numismatics/issue_change_set.rb#L73

We use the year validator :true https://github.com/pulibrary/figgy/blob/master/app/validators/year_validator.rb
Example:
Edit issue: https://figgy-staging.princeton.edu/concern/numismatics/issues/0b757075-0f2a-4b06-a4b3-18831723351c/edit
1. Add: earliest_date or latest_date the value "12344" (>4) -> Save
2. Add: earliest_date or latest_date the value "shg" -> Save
the app will error
