### ISSUE TITLE
Add a property for provenance

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#374]
As discussed within the meeting on 10/13/17, a stakeholder requested that an additional property for Ephemera resources in order to track provenance.

**Comment by hackmastera** [comment]
cardinality? I would assume it can be multiple but should we confirm?

**Comment by escowles** [comment]
Given the use case, I think this should be singular — if there's some complicated situation where there is more than one donor/contributor, then I would expect that to be reflected in the text of a single value, rather than having a list of donors.

**Comment by escowles** [comment]
Closed with #382
