### ISSUE TITLE
Ingest missing volume from Cicognara item

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3748]
This directory: https://diglib.princeton.edu/tools/ib/crowley_cico/batch01/BOX05/7sc/VOL01
should be ingested as a new volume on this Figgy item: https://figgy.princeton.edu/catalog/0cbe4d3a-4304-480a-b789-0768d9649fda

**Comment by kelea99** [comment]
@escowles, is this something @roelmoon or I can do? is there any reason why we can't?

**Comment by escowles** [comment]
@kelea99 Sure, I'm sure either of you could do that any time you have a minute.

**Comment by kelea99** [comment]
Just did this. closing ticket.
