### ISSUE TITLE
Going back from the Ephemera Folder form returns the user to the home page

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#375]

**Comment by hackmastera** [comment]
Steps in attempting to reproduce:
- navigate to an ephemera folder object
- click edit button
- after form loads, click browser back button.

Everything looks fine. @jrgriffiniii can you provide any more info?

**Comment by escowles** [comment]
@hackmastera Click "Cancel" instead of going back — it takes you to the app root instead of going back to the show page.

**Comment by hackmastera** [comment]
#434 introduced a regression here
