### ISSUE TITLE
Ingest full pages of WC055

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#3750]
Individual images are now in Figgy; would be good to ingest the albums as albums, so that the full-page image sets and annotations are available.

**Comment by tpendragon** [comment]
@cwulfman Can you post some information about where the pages are?

**Comment by cwulfman** [comment]
The album is on the Isilon here: `/ifs/pudl/pudl0017/wc055/1139550`

**Comment by cwulfman** [comment]
done
