### ISSUE TITLE
Ensure figgy-staging2 doesn't send collection report emails (or run crons more generally)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3762]
[Figgy/staging] Errno::EHOSTUNREACH: No route to host - connect(2) for "lib-ponyexpr.princeton.edu" port 25

## Backtrace

    line 14 of [PROJECT_ROOT]/lib/tasks/figgy.rake: block (3 levels) in <top (required)>
    line 13 of [PROJECT_ROOT]/lib/tasks/figgy.rake: each
    line 13 of [PROJECT_ROOT]/lib/tasks/figgy.rake: block (2 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/61887550)

**Comment by hackmastera** [comment]
For now I just deleted the contents of crontab on that box.
