### ISSUE TITLE
Support S3 for ingest

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3764]
Some of our digitization vendors would like to provide files via S3 bucket instead of shipping hard drives. We should be able to ingest those files directly from S3.

**Comment by kelea99** [comment]
@jrgriffiniii  can we get this working sooner vs. later, just in case we become dependent on accepting files in this way from a vendor in the near future?

**Comment by tpendragon** [comment]
Are we giving them access to our S3 or they want us to ingest from their bucket?

**Comment by kelea99** [comment]
@tpendragon they would want us to ingest from their bucket. Vendor is Hudson.

**Comment by tpendragon** [comment]
Are their S3 buckets publicly available? Or will we have some sort of token, or do they want to provide access to a user we use? Will they put them in the structure we have already? Is it a new bucket per ingest?

**Comment by kelea99** [comment]
the current idea, if and when it comes to it, would be to provide @roelmoon access to a folder in their bucket.

**Comment by tpendragon** [comment]
If we have a digitization project with Hudson that can survive a couple weeks from delivery to ingest it might be easier to just start it and implement the feature when we have real files from them to ingest. There's a number of ways this could happen and I'm scared we'd implement the wrong one on accident.

**Comment by kelea99** [comment]
so far we are going with sending the HDs via UPS until it is no longer an option, for one reason or another. as soon as I know that will no longer work, but there are still files that could be sent there ways, Ill let y'all know.

**Comment by tpendragon** [comment]
Great! Thanks!

**Comment by kelea99** [comment]
Thank you!!

**Comment by tpendragon** [comment]
Closing this until we have a project with specifics we can implement.
