### ISSUE TITLE
"PUmap_27825" bad tiff

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3766]
## Backtrace

    line 90 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: create_tiff_derivative
    line 83 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: run_tiff_derivatives
    line 76 of [PROJECT_ROOT]/app/derivative_services/jp2_derivative_service.rb: run_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/61998664)

**Comment by hackmastera** [comment]
This image is quite large but I also think it's a bad tiff. When I download it and view it locally I initially can see part of the map but then the bottom portion won't load then then it all turns blue. Here's the figgy object. https://figgy.princeton.edu/catalog/47d088c0-33fa-4dc3-afe3-ceb2e0daa068

**Comment by tpendragon** [comment]
We're regenerating derivatives to see if VIPS does it better.

**Comment by eliotjordan** [comment]
New VIPS thumbnail service fixed this.
