### ISSUE TITLE
Bulk ingest doesn't update identifier attribute

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#3767]
e.g.,
``` sh
DIR=/mnt/diglibdata/pudl/pudl0017/wc064/H/H0001 BIB=WC064_c1 OBJID=ark:/88435/m039k5139 COLL=e201720c-e1bb-48eb-854d-5bc0aa6f57c6 FILTER=.tif MODEL=ScannedResource bundle exec rake bulk:ingest 
```
where the environment variable OBJID is passed to `IngestFolderJob` as a (new) attribute `identifier`.

The problem appears to be in changeset.validate().  In `update_properties_from(doc, options, format)` in representable.rb, the `representable.map!` method seems to update a global variable `represented` with a set of attributes, but it ignores `identifier`.  There seems to be a set of "blessed" attributes somewhere, and `identifier` isn't among them. Perhaps not surprising, as @escowles and I added it to support passing in the ark.  Looks like whatever that registry of blessed identifiers needs to be updated, or another method needs to be devised to update the identifier in the ScannedResource.

**Comment by tpendragon** [comment]
@cwulfman I have a fuzzy memory of you fixing this. Can you check and close if true?
