### ISSUE TITLE
Subject categories are duplicated

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#377]
If two distinct terms with distinct categories are selected for a given EphemeraFolder, the category of the term first selected is duplicated on the Show Page.

**Comment by escowles** [comment]
We should display subjects and categories as Category--Subject — with the Category linked to a category search, and Subject linked to a Category+Subject search.

If the Category and Subject are the same (e.g., Health--Health), just display the Category.

**Comment by hackmastera** [comment]
Are there implications here for some other codebase? If this needs to happen in a user-facing app I'm not sure which one.

**Comment by escowles** [comment]
@hackmastera Yes, I've added a ticket in in the LAE Blacklight app: https://github.com/pulibrary/lae-blacklight/issues/157
