### ISSUE TITLE
Build failing: orangelight event generator tests expecting bulk: false; getting bulk: true

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3773]
https://app.circleci.com/pipelines/github/pulibrary/figgy/902/workflows/593db022-53f8-4d36-af20-bfde80661a37/jobs/25335

These failures might make sense in light of https://github.com/pulibrary/figgy/pull/3749 but that was merged 12 days ago and these build failures are new.

**Comment by hackmastera** [comment]
Well last night's succeeded.

**Comment by hackmastera** [comment]
Still getting this failure intermittently. We should look into it.

**Comment by escowles** [comment]
Looks like this is driven by an environment variable, did we change this in the CircleCI config? https://github.com/pulibrary/figgy/blob/master/app/services/event_generator/orangelight_event_generator.rb#L64

**Comment by hackmastera** [comment]
Pretty sure this is a test order issue. When https://github.com/pulibrary/figgy/blob/002435aba00cdd481d73971c5140be1c2d345d87/spec/services/orangelight_reindexer_spec.rb runs the env gets set here:
https://github.com/pulibrary/figgy/blob/002435aba00cdd481d73971c5140be1c2d345d87/app/services/orangelight_reindexer.rb#L17

Then it's occasionally still set when the orangelight_event_generator test runs.
