### ISSUE TITLE
Order Manager doesn't use custom page label

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3776]
When I select multiple pages in the Order Manager and change the "label" field, it continues to use the default value ("p. "). The same is true when I try foliation (it uses "f. " even if I change the "label" to something else).

**Comment by sdellis** [comment]
This used to work. I believe it has something to do with the `watch` method that was added recently [here](https://github.com/pulibrary/figgy/blob/master/app/javascript/components/OrderManagerFilesetsForm.vue#L137-L140).

**Comment by tpendragon** [comment]
Fixed as part of order manager speedup work.
