### ISSUE TITLE
Typo in download/usage disclaimer on PDFs

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/figgy#3786]
The last sentence says:
> We request that users reproducing this resource cite it according the guidelines described at...

Should be:

We request that users reproducing this resource cite it according **to** the guidelines described at...

**Comment by jpstroop** [comment]
The URL in the blurb could be updated as well: https://library.princeton.edu/special-collections/policies/forms-citation

**Comment by hackmastera** [comment]
Reopening; just noticed the link update request.
