### ISSUE TITLE
Request another verification for Figgy from Google for Drive Support

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#3788]
The verification was dropped for Figgy without notification from Google, resulting in the following error message:

![image](https://user-images.githubusercontent.com/1443986/78725693-2e2dc800-78fe-11ea-96e5-29b59d9d7471.png)

Attempting to use a previous client ID and password (used for development), Google restricts access further:

![image](https://user-images.githubusercontent.com/1443986/78725625-fcb4fc80-78fd-11ea-88ac-03ce9f060095.png)
 
I can only look to resolve this by requesting verification from Google once again for Figgy.

**Comment by jrgriffiniii** [comment]
I have the following status now reported:

![image](https://user-images.githubusercontent.com/1443986/78726146-44885380-78ff-11ea-8f3b-a9d85bd09a98.png)

**Comment by jrgriffiniii** [comment]
This too would be closed by the BrowseEverything upgrade.

**Comment by hackmastera** [comment]
no longer needed due to BE upgrade.
