### ISSUE TITLE
Exception raised when OAI endpoint is accessed without a `set` param

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3790]
`https://figgy.princeton.edu/oai?verb=ListRecords&metadataPrefix=marc21`

[Figgy/production] NoMethodError: undefined method `enhance_cicognara' for nil:NilClass

We should gracefully catch this instead of triggering an exception.

## Backtrace

    line 5 of [PROJECT_ROOT]/app/models/oai_provider/oai_wrapper.rb: to_marc21
    line 5 of [PROJECT_ROOT]/app/controllers/oai_controller.rb: index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/59240642)

**Comment by jrgriffiniii** [comment]
I could not reproduce this with https://figgy.princeton.edu/oai?verb=ListRecords&metadataPrefix=marc21
