### ISSUE TITLE
I would like a csv download of Collections with their source metadata identifier, whether or not they have structure, and their state

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3793]
I would love to have this information for all collections, if it is easier for you to do this way. otherwise, for now:

- Mesoamerican: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Mesoamerican+Manuscripts&q=

- Scheide: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Treasures+of+the+Scheide+Library

- Marquand: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Marquand+Library+Selections

- Numismatics: https://figgy.princeton.edu/catalog?utf8=✓&q=numismatics
(this was not a collection, but a general keyword search - most coins not tagged with a collection)

**Comment by kelea99** [comment]
Followup question: Is it possible (or is this a unicorn question) for you to identify records in figgy that still have the 00000000 or 00000000.tif labels for their pages in the viewer?

**Comment by kelea99** [comment]
example sheet (see to be assigned tab): https://docs.google.com/spreadsheets/d/1udsJcf9nLjWMwTFTM8VDMHCxe5mOORNRklPtAk9KI2I/edit#gid=0

**Comment by tpendragon** [comment]
We're going to talk about this at check-in - it may be we have a better way to fulfill this need.

**Comment by tpendragon** [comment]
Closing because we're going to do #3831 instead.
