### ISSUE TITLE
In the Ephemera form, I would like to be able to save an item without being required to add dimensions/measurements.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3813]
Born Digital items do not have this information, so it seems like a reasonable request.

**Comment by escowles** [comment]
It looks like boxless ephemera do not require measurements — I think the plan was to have born digital items not be in boxes, and we changed the required fields based on that.

**Comment by kelea99** [comment]
@escowles . Thanks for the information!  Ellen (SAE subject Selector) and I talked a lot about boxes versus collections and it was decided the virtual boxes with dummy barcodes would be the best way forward. I share our rationale here, as well as the proposed workflow. If there is any downside and it would, indeed, be preferable to not use boxes, please let me know! :) 

- **Decision:** create dummy boxes (use "00000000000000" for the barcodes, since they will be required) — those boxes won't show up in dpul, but can be used in figgy to segment the items for management

- **Rationale:** Creation of dummy boxes versus adding collections would simplify ingest, and diminish potential for human error when adding to/deciding on collections in the future.

- **Workflow:** https://docs.google.com/document/d/1-k8jQuP8DbUVFjQZ0srz2PSA2EJ7rI4sqwn52IwpNYs/edit

**Comment by escowles** [comment]
It seems like there are a couple of different options here to resolve these two competing needs:
1. Have collections that don't show up in DPUL (maybe draft vs. complete?)
2. Have boxes that are "virtual" boxes whose members don't require dimensions
3. Have some new kind of grouping in ephemera projects for born-digital collections

**Comment by tpendragon** [comment]
@kelea99 has asked us to just remove the requirement from all Ephemera.
