### ISSUE TITLE
Viewer for groups of objects linked to a single finding aid component

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3815]
Archival collections often have aggregate descriptions where the most granular component metadata corresponds to a number of digital objects. It would be nice to display a viewer at the component level that included all of the items linked to that component.

This pretty much works if the items are added to a collection, using the `/uv/uv` viewer. The only issue with that is the thumbnail tab is displayed by default instead of the index tab.

**Comment by escowles** [comment]
This is related to the automatic EAD linking process, since that takes each complete object that is linked to a finding aid component and adds the DAO link. Maybe this should work like the Orangelight lookup based on bib number? Or maybe we could make an endpoint similar to the ARK-based one that would give you a manifest or collection of manifests based on how many matches there were?

**Comment by tpendragon** [comment]
@escowles Can you provide a specific use case here with specific items so we can adjust them appropriately? We've talked about a few options, but it depends on what specifically the data we have is like.

**Comment by escowles** [comment]
@tpendragon The main case right now is the Grounds and Buildings collections. Currently, the Figgy items don't have links to the finding aid, but SC staff are going to provide that mapping. There are ~220 buildings and more than 7000 photos, so we expect dozens per component.

E.g., AC111_c0002 (Aaron Burr Hall) will have these 24 photos from Figgy: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=pudl0038&q=aaron+burr+hall

**Comment by tpendragon** [comment]
Wait, really? There's descriptive per-object notes in the MODS for those records. Isn't SC going to mint new component IDs and transfer the mods to the finding aid like they've done for other collections?

**Comment by escowles** [comment]
Not at this time — the scale of this project has always been a barrier to any metadata updates, and is the reason why it's languished. For the first time, Mudd has the capacity to at least group the photos into the components, so doing at least that seems reasonable to me.

We definitely plan to retain the MODS and I can imagine migrating those comments into the finding aid in a later project, though.

**Comment by tpendragon** [comment]
Okay. Then I think the solution here is that we have a parent record with the component ID and have each child record as the volume, with a title that comes from the MODS probably? Then we don't have to change anything and it reflects what's going on.

**Comment by escowles** [comment]
@tpendragon Yes, I agree that's the best way to handle the Ground and Buildings records, and having the child volumes means that if we want to go back and migrate more of the MODS metadata, we have ScannedResources to attach them. I'm closing this ticket since the current functionality works fine for the immediate use case and we can open new tickets for other use cases that pop up.
