### ISSUE TITLE
Error in JS console: IIIF required parameters not provided

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3820]
The first page of this item does not load in the viewer: https://figgy.princeton.edu/catalog/01a82542-fc51-4614-b2e5-31ba9d09c49a

Console says
```
IIIF required parameters not provided.
    at new h.IIIFTileSource (openseadragon.min.js:8)
    at openseadragon.min.js:8
```

**Comment by tpendragon** [comment]
This was one of the ~ 37 that failed the lambda width/height conversion process, in this case because it was too big. Regenerating derivatives now.

**Comment by hackmastera** [comment]
👍 all better
