### ISSUE TITLE
Can we get the remaining collections for Princeton's Performance Archive up and available?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3822]
Had a meeting with @escowles about the collection and that only a subset of it is currently available.  @tpendragon and @hackmastera - how big of an ask is it to request is this?

**Comment by tpendragon** [comment]
Moderately big. Someone would have to dedicate a couple weeks to it at least, migration tickets are hard to estimate. You just have to dig in and start and see what happens.

**Comment by kelea99** [comment]
Hmm. ok. Shoot. so currently its only the  orchestra and glee club recordings in figgy that I can see. for something that would be this big, how many recordings are we talking about (or where can I look to get the information myself)? would it be more reasonable to make tickets to migrate by sub-collections? This is what I could find from Mendel's webpage. assuming this is it?

**Performance Ensemble Archive**
- _Glee Club (Complete?)_
- Chamber Choir
- Jazz Ensemble
- _Orchestra (Complete?)_
- Sinfonia
- Wind Ensemble
- PLork
- Princeton Sound Kitchen
- Chapel Choir

**Music Department**

- Faculty Recitals
- Music Department Class Performances

**Miscellaneous**

- Princeton A Cappella Groups

**Comment by tpendragon** [comment]
I think the glee club ones are ones that were done manually, we've never migrated any, so I don't think it's a complete set. We'd have to talk to Dan. The Orchestra should be done.

I don't think we need a ticket for each one unless there's a priority order for which get done first.

I'd give you a number for how many recordings it is, but the music reserves database is down. 😓 Hopefully they'll get it back up soon and I can peek.

**Comment by tpendragon** [comment]
The following is a list of course IDs we should ingest:
```
babbitt,Faculty Recordings
boretz,Faculty Recordings
chamber,Performance Ensembles
chapel,Performance Ensembles
compgrad,Performance Ensembles
cone,Faculty Recordings
dembski,Faculty Recordings
faculty,Performance Ensembles
footnotes,Performance Ensembles
katz,Performance Ensembles
lansky,Faculty Recordings
Mackey,Faculty Recordings
mendel,Faculty Recordings
musica,Performance Ensembles
nassoons,Performance Ensembles
opera,Performance Ensembles
organ,Performance Ensembles
perle,Faculty Recordings
plork,Performance Ensembles
pucomp,Performance Ensembles
puje,Performance Ensembles
puperf,Performance Ensembles
puwe,Performance Ensembles
randall,Faculty Recordings
reunions,Reunion Recordings
sessions,Faculty Recordings
sinfonia,Performance Ensembles
student,Performance Ensembles
students,Performance Ensembles
tiger,Performance Ensembles
tigeressions,Performance Ensembles
tigerlilies,Performance Ensembles
tigertones,Performance Ensembles
westergaard,Faculty Recordings
white,Faculty Recordings
wildcats,Performance Ensembles
wuorinen,Faculty Recordings
```

I'm going to just try running them all.

**Comment by tpendragon** [comment]
These are running on lib-proc7 now.

**Comment by tpendragon** [comment]
All of these were migrated. 161 recordings couldn't be imported because of missing files where they were expected. I've sent Dan a CSV with the recording IDs for those that couldn't be found, hopefully he can manually look into getting them in.

**Comment by tpendragon** [comment]
If anything is broken we should make a new ticket. Closing this.
