### ISSUE TITLE
Order Manager should support bracketing of even/odd numbered pages.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3826]
Extracted from #2822

@kelea99 says:
> got a use case from Jen Cabral on Friday afternoon for another bulk pagination issue. Every other page is labeled in the digital surrogate she was working on. The page numbers can therefore be inferred on the unnumbered pages, but should be in brackets. can we find a away to automat this (one page in brackets, the following page not in brackets)? Lemme find the item she was working on and Ill post in a sec.

The label manager supports it via this:
```javascript
   * A note about bracketing: Only one of `bracket`, `twoUpBracketLeftOnly`,
   * `twoUpBracketRightOnly` can be set, and `bracketEvens` and `bracketOdds`
   * can only be set if none of the first three options are set. The following
   * is an example of the difference between each option (this is also shown in
   * greater detail in the README).
   *
   * `bracket` wraps the whole string in brackets: [f. 1a], [f. 1b], [f 2a], ...
   *
   * `bracketEvens` and `bracketOdds` wraps just the evens/odds in brackets,
   *  and doesn't make much sense for twoUp configs: [p. 1], p. 2, [p. 3], ...
   *
   *  `twoUpBracketLeftOnly` and `twoUpBracketRightOnly` brackets just the
   * value on the right or left side of the separator: f. 2a/[1b], f. 3a/[2b],
   * f. 4a/[3b], ...
```

Close this ticket when the following happens:

1. If "Add Brackets" is not checked, do nothing.
2. If "Add Brackets" is checked, display a dropdown with the options "All", "Left Side Only", "Right Side Only"
3. If "Add Brackets" is checked, "Left Side Only" or "Right Side Only" is chosen, and "twoUp" is enabled, pass "twoUpBracketLeftOnly" or "twoUpBracketRightOnly" as appropriate.

**Comment by kelea99** [comment]
@tpendragon , all options appear to be covered here. Looks good to me and covers Jen's use case.
