### ISSUE TITLE
Bulk edit form should not allow invalid workflow state selections

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3835]
@eliotjordan reports these errors were due to an attempt to go from "pending" to "complete", which the aasm settings do not allow. Perhaps the bulk edit form shouldn't allow an invalid state selection to begin with.

## Backtrace

    line 16 of [PROJECT_ROOT]/app/jobs/bulk_update_job.rb: block (2 levels) in perform
    line 5 of [PROJECT_ROOT]/app/jobs/bulk_update_job.rb: each
    line 5 of [PROJECT_ROOT]/app/jobs/bulk_update_job.rb: block in perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/52135026)

**Comment by eliotjordan** [comment]
I think it should allow selecting other states besides complete. So we can advance the workflow towards complete.

**Comment by tpendragon** [comment]
Closed in preference of #3846.
