### ISSUE TITLE
Some Finding Aids fields are not showing up in Figgy and one field is mapped to the wrong place in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3839]
This was discovered during a meeting with Gabriel Swift, regarding collection review of [WC064 in Figgy](https://figgy.princeton.edu/catalog?utf8=✓&q=WC064) (Western Americana)versus the [Finding Aid](https://findingaids.princeton.edu/collections/WC064/c423) before completion. @cwulfman and I checked another collection - [Sylvia Beach 0108 in Figgy](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Sylvia+Beach+Papers+C0108&q=Sylvia+beach) and in [Finding Aids](https://findingaids.princeton.edu/collections/C0108/c000002357) and the findings were the same. This is a probable issue with pulling in the FA metadata in general versus collection-specific.

1. The **Creator** field in figgy is pulling in the metadata from the **Collection Creator** field in the finding aid. There are two separate entries in the FA: **Creator** and **Collection Creator**. It is important to have the Creator information for the Western Americana collection, as it identifies the photographer, which is the primary method of discovery for this collection by patrons, according to Gabriel.
2. **Description** field from FA (this appears to have been the same metadata as the "notes" field in PUDL) is nowhere in Figgy item. **Description** field is important for the Western Americana collection, as it gives additional information for the piece and, in some cases, who holds the copyright.
3. **Dimensions** field from FA is nowhere in Figgy item.

**Comment by kelea99** [comment]
@escowles , this will probably affect the grounds and buildings work as well. I'd view this as a priority. thoughts?

**Comment by tpendragon** [comment]
Before I move this to backlog can we get some specific references to items that should have these metadata fields? Both a link to their finding aid page, as well as the item ingested in Figgy, so we have a good handle on the success state.

**Comment by tpendragon** [comment]
@kelea99 Can you find examples of the above?

**Comment by kelea99** [comment]
sorry, I just saw this, @tpendragon. one sec

**Comment by kelea99** [comment]
@tpendragon getting more examples now, but there are links to a couple in the original comment. is this what you are asking for? can also make screenshots.

**Comment by kelea99** [comment]
Just a question: are all fields from the FA supposed to be represented in Figgy? if so, there are others that should be added to the "needed in figgy" column. 

**Berthier Collection** 

- figgy: https://figgy.princeton.edu/catalog/ceed998a-7a18-4ed7-8954-5779213e9a91

- https://findingaids.princeton.edu/collections/C0022/c0155

**Comment by tpendragon** [comment]
We've just done the ones that have been requested, historically.

**Comment by tpendragon** [comment]
I appreciate the examples up top, I guess I was just hoping for "this record should have X, which is in this component."

**Comment by kelea99** [comment]
@tpendragon OH! I am happy to do that. would you prefer a spreadsheet with links?

**Comment by cwulfman** [comment]
Here's where the creator field is coming from:

- https://github.com/pulibrary/figgy/blob/master/app/services/pul_metadata_services/client.rb#L42 retrieves a record from the findingaids site. NB: this is not the EAD; it is the enhanced EAD that is produced during ingest into pulfa.
- https://github.com/pulibrary/figgy/blob/master/app/services/pul_metadata_services/pulfa_record.rb#L59 maps `creator` and `publisher` to `collection_creators`, which is an "enhanced" (non-EAD) field in the retrieved record https://github.com/pulibrary/figgy/blob/master/app/services/pul_metadata_services/pulfa_record.rb#L121

This might be the right value to use for a whole collection (though I would suggest the `origination` element in the EAD's top-level `did` would be the better value to use), but for constituents, `creator` should be mapped to the component-level `ead:c/ead:did/ead:origination` element.

**Comment by cwulfman** [comment]
Simply implementing component_creators for pulfa records #3877 is not enough; creator field is still wrong in the UI

**Comment by tpendragon** [comment]
@kelea99 For each of the fields you need can you make a ticket with the following?

1. The field
2. A figgy link to an item that needs that field indexed, and the value the field should be.

That'd help a lot!

**Comment by kelea99** [comment]
@tpendragon. Yup. Ill get to it today and you will have it by tomorrow. :)

**Comment by kelea99** [comment]
@tpendragon. think I got them all. issues made for each field request, which links to finding aid component and figgy instance of it.

**Comment by tpendragon** [comment]
@kelea99 Can we close this?

**Comment by kelea99** [comment]
Yes! closing. :)
