### ISSUE TITLE
I would like to have a view for MVWs where all the pages for the volumes are available in Order Manager [and Structure Manager]

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3840]
use case: Eugene K. asked how to navigate to all the pages within a MVW so that he could label/paginate each volume in Order Manager. @tpendragon thought it would be an interesting proposal, but it’d probably exacerbate any performance issues. while you are at it, might as well see how it might work for Structure Manager, too. This is not a a priority, but may be fun (and helpful!) to work through at some point. I share below his original correspondence:

Eugene Kaganovich Hi All, in bib id 490935, I can view a long set of thumbnails of two volumes, but when I switch to order manager, I cannot open individual pages, just the volumes covers.Is there any trick to this?

**Comment by tpendragon** [comment]
We might be able to do this with some sort of tabbed interface.
