### ISSUE TITLE
I would like a csv download of a subset of numismatics with their source metadata identifier and if the images are *not* yet labeled "obverse" and "reverse".

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3848]
This is the result of question within the original issue #3811: can we identify  numismatics records in figgy that are not yet labeled as "obverse" and "reverse"? Examples include items that still have the 00000000 or 00000000.tif labels for their pages in the viewer? Jen Meyer in SC would like to have this pick list of items in need of labeling for the numismatics collection. She will still use the button once it is sin production, but would prefer to work from a pick list.

**Comment by eliotjordan** [comment]
@kelea99 Is this a one-off request or is it a feature that we'll use regularly? A one-off list should be fairly straightforward to generate. A new feature will take some more design work.

**Comment by kelea99** [comment]
@eliotjordan This should be a one-off request.

**Comment by kelea99** [comment]
Hi, @eliotjordan ! one of the SC folks asked me about this. Is it possible for me to give them an approx timeframe as to when we can get the list to them? Thank you so much!

**Comment by eliotjordan** [comment]
@kelea99 We'll try to get this done next week.

**Comment by hackmastera** [comment]
There were only 3!

@kelea99 
[numismatic_coins_to_label.csv.txt](https://github.com/pulibrary/figgy/files/4612026/numismatic_coins_to_label.csv.txt)

**Comment by kelea99** [comment]
@hackmastera , I just saw this. what??? no.way. looking now.

**Comment by hackmastera** [comment]
@kelea99 I'm pretty sure it's implemented correctly. If y'all find an example of one or more that weren't caught, though, please send it along.

**Comment by kelea99** [comment]
@hackmastera I did a random search of the coins in the catalog yesterday and was finding the obverse/reverse info. is spot on. im wondering if the only items that were not labeled were the studio additions for exhibitions. Looking at that by the end of the day.  Thank you so much!

**Comment by hackmastera** [comment]
Ah, those were ingested as scanned resources, right? So they wouldn't have been caught by my report.

**Comment by kelea99** [comment]
They are.  BUT! That does help narrow it down! I can let Vicki and Jen know.  Thank you so much!
