### ISSUE TITLE
Page labels in order manager should not be truncated.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3851]
use case: Conservation staff would like to have a bit more information describing the image (example below). can we discuss the pros and cons of text wrapping under the image itself? Not sure what to do about the info display top center of the viewer.   
![image](https://user-images.githubusercontent.com/45043014/80538566-f3a2d280-8973-11ea-846a-183295dd69c4.png)

We should be able to fix this via setting `white-space: normal;`

**Comment by kelea99** [comment]
Example of what currently happens: https://figgy.princeton.edu/catalog/15cde939-ec59-4e72-8f62-2c662e960b53

**Comment by hackmastera** [comment]
@kelea99 can you explain more? The title mentions order manager but the screen shot shows the viewer. Which text and which image? What am I supposed to see when I follow the link?

**Comment by kelea99** [comment]
@hackmastera Of course! When one changes the label for an image, it done in order manager. I  (perhaps wrongly)assumed that if we were wanting to have the text wrapped, it would be within order manager's functionality? but you are correct, it also does not wrap in the viewer (the lovely folks in conservation made this mockup illustrating generally what they were thinking about, but would be happy to see the text wrapping).

**Comment by tpendragon** [comment]
@kelea99 I'm going to put this in the backlog. Fixing it might be a bit messy, since styles are complex in the viewer, but please prioritize it however makes sense for how important this is.

Thanks!

**Comment by kelea99** [comment]
thanks, @tpendragon and @hackmastera ! we can keep it there for now until we learn more about their needs/what a future CMS may do for them as well. @escowles, would you agree?

**Comment by escowles** [comment]
@kelea99 👍 that makes sense to me. We might also consider whether expanding the display in the File Manager might be a better fit for this use case, because ultimately they have more info about the images than is likely to fit in the viewer.

**Comment by kelea99** [comment]
Updated melody regarding this ticket today. I suggested we come back to the ticket and reassess their needs after hearing from the folks from the other CMS demos this month.
