### ISSUE TITLE
Users cannot continue labeling/paginating images while loading bar in the order manager is saving

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3854]
@tpendragon Eugene reported this today (original message below).  I'm not sure what the best way forward is for this and if continuing to add labeling as the item was saving was actually a bug that is now fixed.  
original message: Hi Kim, please assign your next batch to me. Also, I noticed that figgy behavior on applying changes became different. Before, it was possible to scroll down and even continue modifications when apply changes button was pressed, and now it is not possible, one must wait on spinning wheel while the changes are applied.

**Comment by tpendragon** [comment]
@kelea99 Is the new behavior a problem? It'd be pretty hard to ensure changes don't get lost if they, for instance, re-edit the page label.

**Comment by kelea99** [comment]
hard to tell, @tpendragon, since they cannot click on anything to test it due to the circle covering the entire view of all the pages in order manager. I would say it is not something to see as a priority, just a heads up. :)

**Comment by tpendragon** [comment]
Doing this before had a good chance of introducing data problems anyways - likely we just need to find a way to make saving faster. Given that, we're going to close this.
