### ISSUE TITLE
Capitalize non-numeric numismatics values

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3869]
The first letters of non-numeric values should be capitalized.

Option 1:
 - Capitalize values on existing records.
 - Implement a capitalization validator.

Option 2:
 - Capitalize values on ingest into Orangelight.

**Comment by tpendragon** [comment]
Option 2 seems easiest to walk back from.

**Comment by hackmastera** [comment]
It seems like it would be nice to ensure they're capitalized in form completion dropdowns, also

**Comment by hackmastera** [comment]
Some fields, like `metal` are pure description. Some, like `obverse_legend`, are clearly transcribed and seem like they shouldn't be transformed in this way.

`edge` has a little of both; values in production are: 
```
"serrated", "plain", "FIFTY CENTS OR HALF A DOLLAR", "PAX UNA TRIUMPHIS INNUMERIS POTIOR", "reX regVM consVLta DeVs fortVnet VbIqVe (=1691)", "milled", "GOTT MIT UNS", "smooth with arabesques", "beaded border", "**ONE**DOLLAR**OR**UNIT*** UNDRED CENTS**", "**ONE**DOLLAR**OR**UNIT***HUNDRED CENTS**", "**ONE**DOLLAR**OR**UNIT***HUNDR*D CENTS**", "inscription: AP", "inscribed (see description)", "reeded"
```

Many of thse, like "serrated" and "plain", which are common values, seem like they should be capitalized. But "reX regVM consVLta DeVs fortVnet VbIqVe (=1691)" seems like it shouldn't be. For now I lean towards not including this field.

`obverse_figure` has a mix of capitalized proper nouns like "Pan" and uncapitalized nouns like "arms". Leaning towards including this field.

**Comment by hackmastera** [comment]
Followed up with Alan. He provided a list of fields to capitalize:


Issue fields:

- metal - cap
- era - cap
- obverse_figure - cap
- reverse_figure - cap
 
Coin fields:

- analysis - normal sentence format
- public_note - normal sentence format

He also said this is only required on the display (orangelight) side.

**Comment by eliotjordan** [comment]
Done.
