### ISSUE TITLE
Bulk ingest needed this week for Volker Collection

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3871]
Is it possible to do this from the command line? Will would like to report back to his department this week about his project. See info below:

**Collection Tag for figgy**: "Paul Volcker Papers"
**Visibility:** PRIVATE (all of them)
**State:** Pending
**Owner:** Will Clement (I should have already added this)

should link up to finding aid.

**3 locations in Isilon are as follows:** 

- \bcadmin\publicpolicy\MC279\Volcker_1_Bag\data\Volcker 1
- \bcadmin\publicpolicy\MC279\Volcker_2_Bag\data\Volcker 2
- \bcadmin\publicpolicy\MC279\Volcker_3_Bag\data\Volcker 3

**Comment by tpendragon** [comment]
These are ingesting now. Ingested using commands like the following:
```ruby
IngestFoldersJob.perform_later(directory: "/mnt/hydra_sources/archives_bd/bcadmin/publicpolicy/MC279/Volcker_3_Bag/data/Volcker 3", property: "source_metadata_identifier", member_of_collection_ids: ["9dcf42e0-b2bd-4b73-bea9-6cb84572a392"], visibility: "restricted")
```

**Comment by kelea99** [comment]
Thank you, @tpendragon !

**Comment by tpendragon** [comment]
These ingested, but didn't pull FA metadata. Fixing now.

**Comment by tpendragon** [comment]
@kelea99 This should be done. Can you double check and close if so? https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Paul+Volcker+Papers+MC279

**Comment by jrgriffiniii** [comment]
@kelynch will look to review this as well.

**Comment by kelea99** [comment]
@tpendragon  @kelynch  this is done.
