### ISSUE TITLE
Ingest JTS Geniza images

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3872]
Stakeholder: Marina Rustow

Files are on the Isilon in `pudl/geniza` and/or `pudl/geniza2` directories.

There are two spreadsheets with some metadata:
* [PGP metadata](https://docs.google.com/spreadsheets/d/1OhMKmjgi0ExiPv1B8WR5gpXjytIR6fyQD-WQagclpmY/edit#gid=765432524): About 4,000 of the JTS fragments have metadata in the PGP, and we should link to the PGP site (e.g., PGP 1234 is https://geniza.princeton.edu/pgpsearch/?a=object&id=1234)
* [JTS Shelfmarks](https://docs.google.com/spreadsheets/d/1nsNzs0Z7AzN0YW-gbu95KSJxWKUtYfRVQcjT8u-qbrE/edit) has shelfmarks (in column D) and various other metadata. Marina says this metadata is derived from the Friedberg Geniza Project website, and we'd need their permission to include the rest of the metadata, and linking to their site would be hard.

**Comment by cwulfman** [comment]
The files constitute a genizah of their very own.  The directories appear to be hard-drive dumps, with haphazard directory names.  Most filenames adhere to a shelf-mark-based naming convention.  About half are tifs; the other half are .dng.

One subset of files are different. NEH_Geniza comprises 5 deliveries in six directories; some directories contains items organized by volume; each of these directories is subdivided into images of individual fragments and images of sheets.  Others are tiffs of MSS pages (bound and unbound); one directory contains images of oversized items, sub-divided into various stages of stitching. These must be processed differently from the rest.

**Comment by cwulfman** [comment]
Here's what I learned from @rlskoeser
> We want IIIF manifests and images that we can connect to existing metadata and transcriptions, display on a public site, and use with IIIF annotations to display, add, and edit transcriptions

She would like JTS to be credited somewhere in the metadata -- what field should that be?

images should be labeled recto and verso -- how to assign labels to images at ingest?

She doesn't know what of the NEH-funded images (or any of the images, for that matter) Marina wants for the PGP; perhaps someone might go over the image set with her?

**Comment by rlskoeser** [comment]
@cwulfman the images we care about for PGP are the ones that are listed in the PGP metadata spreadsheet you have linked in the description above. Filter by JTS for Library and then match on Shelfmark.  

I don't know if there are images beyond what's in the spreadsheet that are relevant for PGP.

I understand from the PGP team that archival designation of recto/verso doesn't always match scholar determination of recto/verso, but where the images indicate recto/verso according to JTS, it would be nice to have access to that information in some structured way (preferably image label, for consistency with Cambridge geniza materials).

**Comment by cwulfman** [comment]
Thank you for this information, @rlskoeser.  I'll be curious to hear Esmé's take on this.

**Comment by rlskoeser** [comment]
Does the metadata you have in the Friedberg Geniza Project (FGP) include original dimensions? That's something I've learned more recently that scholars care about, when looking at images of fragments. It seems to me that dimensions would be factual data that FGP can't claim ownership on, curious what y'all think. If there's any way to include that information now or add it later, it would be great to have; storing it in Figgy with the digitized fragments seems like the logical/preferred place to me.
