### ISSUE TITLE
Some coins are ingested as non Numismatics::Coins

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3882]
These coins are currently ingested as ScannedResources and were ingested for display in DPUL. We'll have to get these images over to the equivalent Numismatic::Coins.

Some examples: https://figgy.princeton.edu/?q=12034

https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Conservation-Exhibition+Photography&q=Coin

Ideally these would sync into DPUL as Coins.

Corollary: https://figgy.princeton.edu/catalog/0ecd7986-3d1b-4732-b35c-589fbbaf1a97

This item has more images than the Numismatics team wants, but these images may be important for the exhibit.

**Comment by tpendragon** [comment]
Questions that need answers:

1. Do we want multiple objects representing the same data?
2. Is there a problem with moving all the images to the Numismatic::Coin and making them sync to DPUL?
3. Do the ScannedResources have metadata the Coins don't?

Ideally we'd have one representative object in our repository, so we're not treating Figgy as a management system for display of things in DPUL.

@kelea99 This will probably require some collaboration between the exhibit builders and the numismatics lab, and if we decide to move images to the coin will definitely require some work to make coins sync to DPUL.

**Comment by kelea99** [comment]
@tpendragon you are in luck, considering I was the exhibits builder for the exhibits with coins in them and would be happy to collaborate and perhaps we could ask if Vicki P. may be able to help as well.  my two cents to your questions:
1. No, we would not want multiple objects representing the same data if we can help it.
2. I personally see no downside to this other than the potential adventures with syncing to DPUL.
3. I believe the coins and medals the studio shot were ingested as title only, but I will confirm that now. all other metadata for the coins was added in DPUL for the exhibits.
I agree with your one representative object in our repository.
