### ISSUE TITLE
Display numismatics date ranges with "to" rather than a dash

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3885]
In this decorator:

https://github.com/pulibrary/figgy/blob/master/app/resources/numismatics/people/numismatics/person_decorator.rb#L33

Maybe somewhere else?

**Comment by hackmastera** [comment]
Once this is done an orangelight reindex event will need to be triggered.

**Comment by hackmastera** [comment]
looks like the right spot. I looked through some other change sets and decorators and didn't see any other obvious places.

**Comment by eliotjordan** [comment]
Complete and new values indexed into the catalog.
