### ISSUE TITLE
Metadata for WC064 completed items are not mapping to DPUL collection “Ho! For the open country “

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3891]
Something funky is happening with WC064. the metadata isnt mapping over to DPUL for any of the competed selections for the new exhibition. example: https://dpul.princeton.edu/open-country/catalog/4q77fr62j

**Comment by tpendragon** [comment]
JSON-LD: https://figgy.princeton.edu/catalog/b627a6ce-6717-4dd0-a16a-7a0c0b8a5788.jsonld

Figgy Record: https://figgy.princeton.edu/catalog/b627a6ce-6717-4dd0-a16a-7a0c0b8a5788

Looks like a number of fields aren't mapping to the JSON-LD. Date/Date Created/Extent/etc.
