### ISSUE TITLE
Remove rb-readline

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3893]
This gem makes it so that I can't use unicode strings in the pry console (see https://github.com/rweng/pry-rails/issues/69). @cwulfman Do you recall why you needed to add it?

**Comment by cwulfman** [comment]
I don't remember; it may have had something to do with creating zip files, but I see no evidence of it.

**Comment by hackmastera** [comment]
It's only installed in development so it would have been something specific to a local environment.

**Comment by cwulfman** [comment]
I think it can be removed.  Would you like me to do it?

**Comment by hackmastera** [comment]
Okay thanks! I can do it.
