### ISSUE TITLE
Numismatic Issue shape dropdown returns to default value when editing

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3895]
The selected shape property on numismatic issue does not reflect the set value when editing.

E.g.

1. Set the shape as "Round" on an Issue.
1. Save.
1. Return to the edit page and the selected value in whatever is at the top of the list. "12-pointed star" on staging or "10-pointed star" in production.

**Comment by hackmastera** [comment]
It seems like maybe we were implementing from some old documentation? The version of select2 that we use doesn't support the hidden field strategy we are using. See https://select2.org/upgrading/migrating-from-35#no-more-hidden-input-tags; https://github.com/pulibrary/figgy/blob/9cf3ed854fe1f9804e23c3ac407ac32f69003640/app/views/numismatics/issues/edit_fields/_shape.html.erb

**Comment by hackmastera** [comment]
Issue a PR to fix this bug; created #3897 for the deprecated behavior
