### ISSUE TITLE
Excel Spreadsheet of ephemeral metadata needing to be batch migrated into figgy with digital images for LAE

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3896]
please see first: https://github.com/pulibrary/lae-blacklight/issues/283  

This is for the newly requested Chilean photos sub-collection ("Proyecto Fotografías Chile").  Excel spreadsheet and all images supplied via dropbox to @kelea99 and @roelmoon .

**Comment by kelea99** [comment]
Update for this ticket.  @escowles , @kelynch and I met with Fernando and Gabrielle. For the time being, they would like the Chilean photographs mentioned here ingested in LAE. sub collection/sub page on hold. https://www.dropbox.com/sh/vwidtvyavprv5vy/AAAB6L-qGlc0uka_b2d73Ri9a?dl=0

**Comment by kelea99** [comment]
@cwulfman, This is ephemera and it to be treated like the [Spain 15M](https://figgy.princeton.edu/catalog/70433c80-ca9e-4ade-9687-8c98f72875bc) collection and [LAE ](https://figgy.princeton.edu/catalog/d7c889ba-9992-494e-8fe4-2c4a9b3c3d7d)in figgy  I will confirm this collection title with fernando, but it will also need the [Latin American and Iberian Studies](https://figgy.princeton.edu/catalog/e9709523-ec23-4eb0-9dd3-002746b91d13) Collection tag as well

**Comment by kelea99** [comment]
Collection tag for Chile exhibit, to be added along with the latin american and iberian.....  "Colección Archivo Fotográfico de la Protesta en Chile 2019"

**Comment by cwulfman** [comment]
Created https://figgy.princeton.edu/catalog/c1b3c804-85bf-4ecc-b7dd-f65f1cbcd7d6.

**Comment by kelea99** [comment]
images and metadata ingested. i converted the most recent metadata i used for ingest to CSV and am including it here. Images migrated to PUDL share. located in "Chilean_Photographs_LAE" directory: https://drive.google.com/file/d/1V29ARf27I9NCtdfhroRVCIAoI4EAHFY3/view?usp=sharing.
