### ISSUE TITLE
I would like OCR to be automatically triggered and embedded in PDFs and/or TIFFS selected for download by patrons.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3902]
Recent use case supplied by Tomas Keenan regarding a requested download from a scholar of all the issues of 30 dnei.  OCR also requested, ideally embedded in the OCR. @escowles exported the issues for now without the OCR.

**Comment by kelea99** [comment]
See also https://github.com/pulibrary/figgy/issues/3909, which was part of this request.

**Comment by escowles** [comment]
See https://gist.github.com/wcaleb/7337097 for one implementation of embedding OCR in a PDF using pdftk

**Comment by kelynch** [comment]
I just tried this tool (https://github.com/jbarlow83/OCRmyPDF) out on a PDF from Figgy and it works pretty well.  It seems reasonably performant (~75 text-heavy pages per minute) and uses tesseract under the hood, plus it looks like it handles PDF image conversion for us.  Worth looking into as well?

**Comment by tpendragon** [comment]
I think we can just tell prawn to embed an invisible text layer. I'll test it now. @kelea99 do we have a set of files that this was requested with?

**Comment by kelea99** [comment]
yes, we do @tpendragon . @escowles already fulfilled the request for the tiffs, but obviously not the embedded OCR.  here is the collection: https://dpul.princeton.edu/slavic/catalog/6h441043b /  https://figgy.princeton.edu/catalog/d2d488af-2980-4554-a9ef-aacbaf463ec8

**Comment by tpendragon** [comment]
The volumes in that collection aren't marked as generating OCR (the MVW is, so I assume they expected it to propagate that downwards, but it doesn't.) That's #2835 

I've got a PR in now to embed OCR into PDFs. It doesn't jump you to the word, but it'll get you to the correct page if you search.

**Comment by kelea99** [comment]
@tpendragon I think that sounds reasonable. @escowles , unless you disagree, I see not problem with this way forward.

**Comment by escowles** [comment]
👍 that sounds good to me — I agree that embedding the plaintext OCR is fine.
