### ISSUE TITLE
I would like "Collection Creator: " field in finding aids to map to a "Collection Creator" field in Figgy.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3911]
Finding aid component: https://findingaids.princeton.edu/collections/WC064/c423
Figgy Component equivalent: https://figgy.princeton.edu/catalog/ba9ae2c4-b4b8-489f-a262-f926ae479b30

**Comment by tpendragon** [comment]
@kelea99 These field tickets should probably be prioritized in the digital projects board somewhere. Can you handle that when you get a chance?

**Comment by kelea99** [comment]
@tpendragon , it looks like all of these have been completed! Ill double check, but everything appears to now be mapped to both Figgy and DPUL from FA content. If so, Ill just close all of these.
