### ISSUE TITLE
I would like "Access Restrictions:" field in Finding Aids to map to a "Access Restrictions field in Figgy.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3913]
Finding aid component: https://findingaids.princeton.edu/collections/WC064/c423
Figgy Component equivalent: https://figgy.princeton.edu/catalog/ba9ae2c4-b4b8-489f-a262-f926ae479b30

**Comment by kelea99** [comment]
@escowles can we say this is already covered in visibility and copyright selection within figgy? thoughts?

**Comment by escowles** [comment]
@kelea99 I think this might be different — maybe somebody wanted the text displayed? Do you remember if someone asked for this?

**Comment by kelea99** [comment]
I remember this being a part of getting Western Americana to display all metadata in DPUL when it was migrated/linked with FA metadata for Gabriel.  Individual tickets were made as a request for each field.

**Comment by escowles** [comment]
OK, I think it's fine to close this — the access restriction note is displayed in pulfalight. If they would also like it to be displayed in DPUL, then that would be a DPUL ticket (and maybe indexing directly from the finding aids data would make more sense than indexing from figgy, anyway).
