### ISSUE TITLE
Should we create a "Credit this material:" field from Finding Aids in Figgy? 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3915]
Finding aid component: https://findingaids.princeton.edu/collections/WC064/c423
Figgy Component equivalent: https://figgy.princeton.edu/catalog/ba9ae2c4-b4b8-489f-a262-f926ae479b30
@escowles, if that credit line is needed, it would be good to have it in figgy so that it may map to DPUL in the future, since that is another point of discovery of our digital content. Thoughts?

**Comment by escowles** [comment]
I'm not sure about this — that value is computed at various levels of the finding aid, not stored on individual components. So I would expect us to do the same thing in Figgy/DPUL if we want it.

**Comment by kelea99** [comment]
leave this for now. not a priority.

**Comment by tpendragon** [comment]
@kelea99 Can we leave it so deeply that we can close this issue?

**Comment by kelea99** [comment]
@tpendragon yup. moving to center of the earth.
