### ISSUE TITLE
Two separate items in figgy with the same bib id (2274590) also share the same ark

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3927]
_both items migrated from PUDL_

ark:/88435/h128nd78z keep as is for https://figgy.princeton.edu/catalog/33bdc21e-cfb4-4094-8dd9-2a583afd0d1d.  Screenshot: 
![Screen Shot 2020-05-19 at 6 05 39 PM](https://user-images.githubusercontent.com/45043014/82383276-79f28780-99fb-11ea-9410-7c27797d41aa.png)
------------------------------------
ark:/88435/ms35t871w should go to https://figgy.princeton.edu/catalog/e71b6217-0313-474c-85c9-f8b21cf2a684 Screenshot: 
![Screen Shot 2020-05-19 at 5 55 30 PM](https://user-images.githubusercontent.com/45043014/82382558-2d5a7c80-99fa-11ea-9823-a3ad46f3756e.png)

**Comment by tpendragon** [comment]
@kelea99 Updated ARK for the second one. Can you close after you confirm?

**Comment by kelea99** [comment]
@tpendragon identifier in the imported attributes section is still incorrect for  https://figgy.princeton.edu/catalog/e71b6217-0313-474c-85c9-f8b21cf2a684 , but is correct in the attributes section?

**Comment by tpendragon** [comment]
Yeah. It's what happens when one bib record has multiple ARKs. It picks the first one for importing, but if it's wrong we have to manually adjust the value in the attributes.

**Comment by kelea99** [comment]
ugh. sorry.
