### ISSUE TITLE
PulfaExporter should create download links for file types not supported by UV

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3928]
PulfaExporter currently has some logic to handle multi-volume works and PDFs:
https://github.com/pulibrary/figgy/blob/master/app/services/pulfa_exporter.rb#L77

But there are some file types (e.g., Zip files ingested for content migrated from WebSpace) that do not work in the viewer. We may want to add support for more file types, which would be a separate ticket. But PulfaExporter should link to the download URL instead of a non-working viewer for any non-supported file types.

**Comment by tpendragon** [comment]
@kelynch Can we get a Figgy record with a not-UV file that needs to get exported to PULFA which we can use as the use case?

**Comment by escowles** [comment]
@cwulfman Should be able to give you an example Figgy object with Zip content.

**Comment by cwulfman** [comment]
https://figgy.princeton.edu/catalog/bed9d14e-d9d1-4847-8aeb-aa3891b1a99f

**Comment by tpendragon** [comment]
Couple of things:

1. This came up in another working group I'm in. Do we need persistent links to these downloads? Like should there be an ARK that goes to the download link? Maybe not important for this.

2. Maybe not important, but the example ZIP is pretty nuts - it's like 8 levels of folders deep which seems to replicate the hydra_sources directory structure. Maybe something to fix on that example record?

3. An empty broken viewer is going to show up in PULFA as soon as this record is marked complete, and I'm not sure adding a download link will fix it. We'll have to test it.

Anyways, as a first step it seems like to close this ticket I'll just make it put the download link in for ZIPs, but some thoughts about future potential issues above.

**Comment by escowles** [comment]
@tpendragon Those sound like good things to look at before we complete the items.  Some thoughts:

1. I haven't heard any desire for ARKs linking to the downloads as opposed to the finding aid or other landing page.

2. I agree the deep folder structure of that object isn't great, and reflects a lot of the Figgy server setup and the bagging structure of the content. @cwulfman should probably checkin with Annalise and make sure the Zip files in Figgy have the structure we want to preserve, and not anything extra.

3. It would be great to prevent an empty viewer showing up. Either making the viewer iframe show the download link, or suppressing the display of the viewer completely if it's not going to work, would be much better.

**Comment by kelynch** [comment]
Here is the complete example (synced to Figgy DAO workflow) - https://figgy.princeton.edu/catalog/b1cd5592-19bb-4a18-b370-b286194e2a90
