### ISSUE TITLE
I would like a report of all PUDL arks present/missing in figgy 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3929]
@escowles can we compare the two to generate this report? I would like to see any arks that are missing. I'd want the identifier/title/collection in the report as well.

**Comment by escowles** [comment]
I've downloaded a report of all our ARKs from EZID and I'm running a script to resolve the URLs now to see where they are all pointing.

**Comment by escowles** [comment]
Here's the full report of all the Princeton ARKs and the URLs they resolve to:
[ark-report.txt.gz](https://github.com/pulibrary/figgy/files/4664724/ark-report.txt.gz)

And here's a spreadsheet listing all the PUDL ARKs and a quick breakdown of the domains resolved to: https://docs.google.com/spreadsheets/d/1H3Ct3yNULsiqZwScfA-MKUE3nBFte_mWO15UQ25SF1c/edit#gid=0
