### ISSUE TITLE
Ingest [Engelmann Archive of Proofs and Samples]  as MVW into Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3932]
PUDL Permalink: http://arks.princeton.edu/ark:/88435/3484zk471
Identifier (MARC): 8555444

3 (three)volumes total

Also see: https://github.com/pulibrary/pudl-migration/issues/6

**Comment by tpendragon** [comment]
@kelea99 Should this be in the PUDL Migration board somewhere?

**Comment by kelea99** [comment]
@tpendragon it should be. moving now.

**Comment by kelea99** [comment]
@cwulfman just moved this here. im about to have a look, but if there is not a lot of structure to this, It may be easier/faster for me to just ingest into figgy from the PUDL share. thoughts?

**Comment by kelea99** [comment]
copy from issue #6 from @cwulfman : This is in pudl0130:

deploy@lib-proc6:/mnt/diglibdata/pudl/pudl0130$ ls -l
total 0
drwxr-xr-x 2 deploy www-data 0 Mar 27  2017 10149154
drwxr-xr-x 2 deploy www-data 0 Sep  8  2015 3051613
drwxr-xr-x 2 deploy www-data 0 Jan 18  2017 5240761
drwxr-xr-x 2 deploy www-data 0 Mar 25  2016 6109684
drwxr-xr-x 2 deploy www-data 0 Oct 23  2014 8555444
drwxr-xr-x 2 deploy www-data 0 Dec  1  2014 gc060
NB 8555444 doesn't appear to be a bibid (it doesn't appear in the catalog). These seem to be Graphic Arts materials.

**Comment by cwulfman** [comment]
completed.
