### ISSUE TITLE
Ingest from google drive not working.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3934]
Getting the following error after I select "google Drive" as provider. immediately jumps to error page
![Screen Shot 2020-05-21 at 1 42 12 PM](https://user-images.githubusercontent.com/45043014/82588664-23a35700-9b69-11ea-9d4c-dc88e9f1b666.png)

**Comment by hackartisan** [comment]
This one actually not resolved by pulibrary/princeton_ansible#1913

**Comment by hackartisan** [comment]
Confirmed this is still a problem for @kelea99. Look to pair with her to debug.

**Comment by tpendragon** [comment]
We've given up.
