### ISSUE TITLE
Small selection of Slavic Posters folders not added to boxes and floating in figgy, not identified as ephemera project

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3937]
Anna Meerson alerted me to this today: "box #26, folders #1335-1338. 2 days ago I added them to the collection and now for some reason they disappeared. My first thought was that it happened because my computer disconnected from the internet, which happens quite often, but then I thought, how I was able to save the metadata then?"

I found the folders in figgy via the barcode, but they are not a part of the ephemera collection, and the "Ephemera Project" facet itself doesn't display to the left. 

Example (search with the barcode numbers in figgy) : https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Princeton+Slavic+Collections&q=32101108350644#

**Comment by hackmastera** [comment]
@kelea99 which ephemera project should they be in?

**Comment by hackmastera** [comment]
Ah okay I think "Late Soviet Posters"

**Comment by kelea99** [comment]
Let me double check, @hackmastera .

**Comment by kelea99** [comment]
yup. late soviet posters!

**Comment by hackmastera** [comment]
These 4 items have been added into the desired box.

**Comment by kelea99** [comment]
informed Anna Meerson about this just now. thanks!
