### ISSUE TITLE
Ingest from Isilon PUDL share failing in figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3938]
https://figgy.princeton.edu/catalog/58386f27-2a95-4138-a30e-4dde3aeb0aaa.

**Comment by tpendragon** [comment]
Are we sure it failed? The queue is really backed up atm, and I don't see any evidence that jobs have run on those new files yet.

**Comment by kelea99** [comment]
it usually displays an  its in the queue banner or some sort of indicator,  I thought? This is all I see now: 
<img width="1440" alt="Screen Shot 2020-05-28 at 1 56 17 PM" src="https://user-images.githubusercontent.com/45043014/83176447-75109080-a0eb-11ea-9cee-da5c6a86e90b.png">

**Comment by kelea99** [comment]
@tpendragon ill check in on it again this evening and tomorrow morning to see if its just waiting in the queue.

**Comment by kelea99** [comment]
They are ark! closing the ticket.
