### ISSUE TITLE
Stop making JPEG2000 derivatives

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3940]
We should stop making JPEG2000 derivatives now that we're using pyramidal TIFFs. Include an ADR.

**Comment by tpendragon** [comment]
I'm still not confident I've gotten the final go ahead that we should keep doing it and that the expense is fine. @escowles?

**Comment by escowles** [comment]
Yes, we have final go-ahead to stop making JP2s. Now that we have more than a month of data, it would be good to [update the doc estimating sizes/costs](https://docs.google.com/document/d/17dE1gfcAt-U5H_cSqq8dmhSEtm1310gAleHCY4y2pM0/edit), but we can go ahead and migrate all of our image server content to the AWS Lambda.

**Comment by tpendragon** [comment]
I've updated that document.

**Comment by tpendragon** [comment]
I started doing this and ran into an issue with Hathi export. Should we just generate those JP2s on demand?
