### ISSUE TITLE
[Figgy/staging] OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3942]
## Backtrace

    line 30 of [PROJECT_ROOT]/app/services/voyager_updater/event_stream.rb: parsed_json
    line 15 of [PROJECT_ROOT]/app/services/voyager_updater/event_stream.rb: events
    line 22 of [PROJECT_ROOT]/app/services/voyager_updater/event_stream.rb: process!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/64270463)

**Comment by christinach** [comment]
same as https://github.com/pulibrary/marc_liberation/issues/686
