### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3943]
Link: https://figgy.princeton.edu/catalog/parent/a538af11-8d21-4be7-aaa0-40c1e9514d89/f33a6599-acdd-483c-9462-d3292aff8796

## Backtrace

    line 472 of [PROJECT_ROOT]/app/services/manifest_builder.rb: block in leaf_nodes
    line 472 of [PROJECT_ROOT]/app/services/manifest_builder.rb: select
    line 472 of [PROJECT_ROOT]/app/services/manifest_builder.rb: leaf_nodes

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/64108537)

**Comment by christinach** [comment]
https://figgy.princeton.edu/catalog/a538af11-8d21-4be7-aaa0-40c1e9514d89
no audio was uploaded. `      @leaf_nodes ||= super.select { |x| x.mime_type.first.include?("audio/") }
`
the https://figgy.princeton.edu/concern/scanned_resources/a538af11-8d21-4be7-aaa0-40c1e9514d89/manifest will trigger a nil error.

**Comment by tpendragon** [comment]
This was a file that couldn't characterize because of an apostrophe. We fixed that bug, but need to recharacterize https://figgy.princeton.edu/catalog/parent/a538af11-8d21-4be7-aaa0-40c1e9514d89/f33a6599-acdd-483c-9462-d3292aff8796

**Comment by tpendragon** [comment]
Characterized and derivatives generated.
