### ISSUE TITLE
Stage OCR-ed PDFs for delivery in ILLiad

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#3951]
Related to pulibrary/figgy#3950.

Once PDFs have OCR generated and embedded, PDFs should be staged in the appropriate directory for the ILLiad Odyssey process to pick them up and delivery them to the patron. 

Acceptance criteria:

* The staging process can determine when a PDF has successfully completed the OCR generation process
* The PDF is staged in the "images" directory for the ILLiad Odyssey process to pick it up

**Comment by tpendragon** [comment]
Absorbed into #3950.
