### ISSUE TITLE
spelling error in namespace in imported_metadata -- xlin when should be xlink

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#3958]
See, e.g., https://figgy.princeton.edu/catalog/95ba6627-5aa9-4732-9955-fc8d25665721.  The string "xlink" is correct in the source EAD https://findingaids.princeton.edu/collections/C0744.03/c0335

The error also appears in spec fixtures:
```sh
cd /your/figgy/path
ag "xlin:"
```

I don't see the error in any code.

**Comment by tpendragon** [comment]
Figgy's just storing a copy of the EAD. This is likely just a problem with our EAD. @cwulfman is this causing a problem somewhere? I wonder if this is something that will just get fixed up through the process of moving to ArchiveSpace.
