### ISSUE TITLE
Create ocr_request objects for PDFs staged for OCR in Figgy

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#3964]
When PDFs are added to the "ocr_scan" directory for automated OCR generation, create an ocr_request object for each one, to be visible to users in the OCR Requests view to monitor progress.

Acceptance criteria:
* PDFs staged for OCRing have ocr_request objects created in Figgy upon being added to the ocr_scan directory
* OCR request objects are updated based on job status
* These statuses are visible in the OCR Requests view to staff users

**Comment by kelynch** [comment]
Depends on #3950

**Comment by tpendragon** [comment]
Closed as it was absorbed into #3950.
