### ISSUE TITLE
Check OAI earliestDatestamp

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3967]
Gallica's documentation lists this as a pre-req. It looks like ours has not been set.

**Comment by tpendragon** [comment]
The OAI specification says:

```
earliestDatestamp : a UTCdatetime that is the guaranteed lower limit of all datestamps recording changes, modifications, or deletions in the repository. A repository must not use datestamps lower than the one specified by the content of the earliestDatestamp element. earliestDatestamp must be expressed at the finest granularity supported by the repository.
```

Right now we have one, but it's set to the unix epoch. That value's cheap to set and there's definitely nothing modified before that, so I wonder if it's just okay as is? Thoughts @hackmastera ?

**Comment by hackmastera** [comment]
The documentation for this project says

> Check that the date is credible (if you created your repository in 2010, the oldest
> datestamp is 2010!)

Which is why I created this ticket. Perhaps @kelea99 could recommend someone to contact at BNF regarding this requirement?

**Comment by tpendragon** [comment]
Thanks for that! We'll just have to run the query.

**Comment by kelea99** [comment]
@hackmastera, Steve always forwards email from Alexandra Adamova. Ill forwarding the address to you via email now.
