### ISSUE TITLE
Add  figgy-staging2 to the lib-ponyexpr.princeton.edu approved list

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3968]
```
[Figgy/staging] Errno::EHOSTUNREACH: No route to host - connect(2) for "lib-ponyexpr.princeton.edu" port 25
```

## Backtrace

    line 14 of [PROJECT_ROOT]/lib/tasks/figgy.rake: block (3 levels) in <main>
    line 13 of [PROJECT_ROOT]/lib/tasks/figgy.rake: each
    line 13 of [PROJECT_ROOT]/lib/tasks/figgy.rake: block (2 levels) in <main>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/64769229)

**Comment by eliotjordan** [comment]
Made a request to lsupport to add figgy-staging2 to the pony express approved list.

**Comment by jrgriffiniii** [comment]
@eliotjordan I am very sorry, I could not find this within SN@P, but given the age for this issue, I'm going to assume that this was closed.
