### ISSUE TITLE
Items from "Julian Scott Photographs for the 11th Census C1412" collection need a new collection tag added,  in order to map to Western Americana DPUL exhibit

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3970]
Gabriel Swift would like the [Julian Scott Photographs for the 11th Census C1412 ](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Julian+Scott+Photographs+for+the+11th+Census+C1412) to be added to the [Western Americana Collection](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Western+Americana+Collection&q=Western+Americana) in figgy, so that it may be discoverable via the DPUL site for Western Americana.

**Comment by tpendragon** [comment]
Done.
