### ISSUE TITLE
publish dc:type field in oai_dc

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#3972]
from gallica documentation:

Create at least one &lt;dc:type&gt; element including one of the DCMI repository
values: http://dublincore.org/documents/dcmi-type-vocabulary/

The &lt;dc:type&gt; must be repeated with the most precise values, like those
currently handled in Gallica.

See Appendix: &lt;dc:type&gt; used in Gallica

**Comment by hackmastera** [comment]
This is already defined as a field so it just needs to be processed in the `OaiWrapper` decorator 

https://github.com/code4lib/ruby-oai/blob/52aa1cc0d3d2a250f0d4480e0be32f13d8c97692/lib/oai/provider/metadata_format/oai_dc.rb

**Comment by hackmastera** [comment]
Okay first, it seems like they want at least one of "text, image, video, sound." But this isn't mime type this seems to be type for the original work, like if it's a book of words they want "Text" even though what we have is of course images of it. Maybe someone else could read the documentation and confirm this interpretation. If this is the case, though, it's a pretty big ask. We'd need to create a mapping from every possible lcsh genre value that might be in figgy? Plus whatever is used in pulfa since we have both finding aid and bibdata materials. This "type" information is not pulled from finding aid objects.


Then in addition they want a narrower term but one from their list.

For example https://figgy.princeton.edu/catalog/293290cc-ee72-4ce5-ab49-61a303d77776 has type "Pictorial works" but that is not on their list.

Should we send what we have anyway for this second narrower term? It doesn't seem reasonable to attempt a mapping here.

**Comment by tpendragon** [comment]
No, you're right. The broader term should be achievable for those things which come from bibdata - it's the same field that powers our type facet. For the PULFA things, I guess we just default to Text?

**Comment by hackmastera** [comment]
So I think what we can do here is:

1. Determine how static this collection will be. If we don't anticipate adding more to it then we don't need as general of a solution. (cc: @kelea99 )
1. Pull all the types for france_americas and c0022 collections and create a mapping to the broad terms. (@kelea99 am I correct that these are the 2 collections we plan to send?)
1. Default to "text" whenever a type is not found. Note this will include all the pulfa items.

I've asked on the #pulfa channel and there doesn't appear to be a standard way to encode this type of data. In the case of c0022 it's simply provided in general description / free text fields such as description and title, so there's no way to pull it out.

It looks like the requirement for this field seems to be at the level of this specific harvester. I can't find any documentation saying it's required for oai_dc more broadly, or for dublin core itself.  So in the general case it might be better to leave it out than to default to "text", but I don't really see a mechanism for adjusting the response based on the requested set.

**Comment by kelea99** [comment]
@hackmastera "France in the Americas" is something we plan on continuing to contribute to when we can.  @escowles, this is how I understand the agreement.

**Comment by hackmastera** [comment]
It would be helpful to know with what frequency we will add to this collection, and/or what the process will be. There may need to be a bit of metadata review each time something is added.

@kelea99 For the current / upcoming submission, do the collections `c0022` and `france_americas` comprise the complete set?

**Comment by escowles** [comment]
@kelea99 Yes, I agree we plan to add to it over time, and there will probably be additional items digitized and added.

@hackmastera The additions will probably be proposed as digitization projects, so I think it's fine to just assume that this process will entail some metadata review when that happens. Could we default to "text" for items that don't have a machine-readable type info, and provide a way to override that?

**Comment by kelea99** [comment]
@hackmastera we have a long listing of the proposed items, of which a smaller subset was prioritized for the first round of submissions. I can share the overall list, if this helps with your metadata questions from your end.

**Comment by hackmastera** [comment]
Update after discussion at checkin and follow-up with @kelea99

For bibdata items:
- We'll use the bibliographic fixed field type to map to the high-level type BNF wants. These should already be in the figgy records as "format" (not displayed for some reason)
- We'll also include the "type" field as a narrower term.

For pulfa items:
- We'll default to "text" for now.
- We discussed the best way to override this value and believe it should be done in finding aids as per the conclusions from the Archival Description in Figgy Working Group. I'll create a follow-up ticket for that.

**Comment by hackmastera** [comment]
Formats that may come from bibdata are here: https://github.com/pulibrary/marc_liberation/blob/94c77e2c582178c977ec7cafcf3a21aa42f52d8c/marc_to_solr/lib/format/bib_format.rb#L26-L34

2 others that may come from the catalog are coins, senior theses. these are visible as the "format" facet values (see front page of catalog)
