### ISSUE TITLE
Ingest PUDL WC054 photo books (2 volumes) as scanned resource, linking to bib id

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3979]
@cwulfman -- this was Requested by Gabriel Swift. He would like the two volume work for WC054 (k: http://arks.princeton.edu/ark:/88435/m326m213x) to be added to the bib id: https://catalog.princeton.edu/catalog/4584826

Figgy Collection tag: [Western Americana Collection](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Western+Americana+Collection&q=western+americana)

**Comment by cwulfman** [comment]
Done: https://figgy.princeton.edu/catalog/f7d56d72-457c-4dfa-878e-41d9ab8f6f19
