### ISSUE TITLE
Ingest PUDL WC055 photo books (2 volumes) as scanned resource, linking to bib id

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3980]
@cwulfman -- this was Requested by Gabriel Swift. He would like the two volume work for
WC055, 2 volumes: http://arks.princeton.edu/ark:/88435/gb19f621v to be added to the catalog record bib id:  Catalog record: https://catalog.princeton.edu/catalog/1139550

Collection tag in figgy: Western Americana Collection

**Comment by cwulfman** [comment]
@kelea99 I don't know how to edit catalog records; this should probably be assigned to a cataloger?

**Comment by kelea99** [comment]
hi, @cwulfman ! we wont need to edit the cat records. I dont know how the migration works from PUDL to figgy.  If i were ingesting into figgy, and assumed it would work similar for items with marcs as it would for fas? I would link the marc bib id to the item. if gabriel would like the ark in the 856. i can do that as well.
