### ISSUE TITLE
Bookmarks view not displaying bookmarks

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#3982]
Bookmarks added in Figgy from the index page indicate success, but can't be viewed in the bookmarks interface.

Acceptance criteria:
* Bookmarks created by users can be viewed in the "/bookmarks" view.

**Comment by kelea99** [comment]
Stephanie R. alerted me to the bookmarks and asked how she could find what she bookmarked.  This would be a great user function for folks working on selecting materials directly from Figgy for their DPUL exhibit.  It would be ideal for Curated Collections Program (in Special Collections) workflow.

Use case:
As a DPUL curator for a Curated Collections Program Exhibition, I would like to search Figgy and book mark items I believe may work for my exhibit. I would then like to review the items I have book marked for final selection of materials. 

*unicorn request: CSV download with ark included an option here?*

**Comment by tpendragon** [comment]
@kelea99 I moved this into the Figgy backlog. If you think it's something we should work on in the medium term can you move it to the digital projects backlog?
