### ISSUE TITLE
[Figgy/production] Vips::Error: /tmp/intermediate_file20200527-9780-oxai6z.tif: Error writing TIFF header
tiff: unable to open "/tmp/intermediate_file20200527-9780-oxai6z.tif" for output

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#3993]
## Backtrace

    line 82 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: run_derivatives
    line 66 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: create_derivatives
    line 9 of [PROJECT_ROOT]/app/jobs/generate_pyramidal_tiff_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/63228597)

**Comment by jrgriffiniii** [comment]
I contend that these errors *should* trigger notices in Honeybadger, but perhaps an error with an ID to the Resource or FileSet might assist with manually generating the derivatives.
