### ISSUE TITLE
"The requested resource does not exist" banner pops up when attempting to execute an all search.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3997]
This happened shortly after I attempted to add a new scanned resource ( 8555444), and got an error. 
<img width="1440" alt="Screen Shot 2020-06-23 at 1 11 45 PM" src="https://user-images.githubusercontent.com/45043014/85434064-751d7800-b553-11ea-9a4a-cc990f66d20f.png">

**Comment by tpendragon** [comment]
There was a bad item in the index I had to delete - should be fine now.
