### ISSUE TITLE
Search page does not render for search term `2516638`

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#4003]
Report from @roelmoon 

This item is done, in figgy, showing in the catalog https://figgy.princeton.edu/catalog/757a5c3e-78f4-453d-8225-69311bc9d164. But searching for this by bib ID (2516638) shows a blue bar saying that the item doesn’t exist.

Expected: Search results page including this item
Actual: Alert message, redirect to home (screenshot below)
Replicate: Submit a search for `2516638`
Impact: Currently they have a workaround, but their workflow is to search by bib id. So far it's only happening with this one item.

![Screen Shot 2020-06-24 at 9 57 43 AM](https://user-images.githubusercontent.com/845363/85570464-5ecdf580-b601-11ea-89b6-3eb024a28203.png)

**Comment by tpendragon** [comment]
This is what happens when an item isn't in postgres, but is in Solr. Likely happened because of the solr outages. I just manually deleted that solr record - if we see it again we may have to reindex.
