### ISSUE TITLE
405 Not Allowed error when attempting to ingest from Isilon, but now showing as ingested

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4004]
I have tried a couple of times today (and once yesterday) to ingest https://figgy.princeton.edu/catalog/c17effa0-0f14-4231-8ca5-0001ea8ab8a4. I kept getting the 405 error, but now it is showing as pending and processing files.  I'm not sure if it fixed itself, but thought it would be good to document, regardless.
![Screen Shot 2020-06-24 at 11 28 54 AM](https://user-images.githubusercontent.com/45043014/85585790-56c88280-b60e-11ea-892d-bc55c2eafc83.png)

**Comment by kelea99** [comment]
update: the ingest did not work as expected. it did not ingest as a MVW. it did not acknowledge the subdirectories for the 3 volumes within the main directory.

**Comment by hackmastera** [comment]
@kelea99 Did you ensure there's a top-level directory containing the mvw? Examples are on the bulk ingest page if you click "show example directory structure", e.g.:

* ingest_dir
  * bib_id
    * vol1
      * 1.tiff
    * vol2
      * 1.tiff

**Comment by kelea99** [comment]
@hackmastera , yup. here is the path, just to make sure you see what I am seeing?  smb://diglibdata1.princeton.edu/pudl/pudl0130/8555444

**Comment by hackmastera** [comment]
Hm. well I don't see that bib number in that directory.

Regardless, the directory you'd need to select for ingest would be `pudl0130` in order to get the multi-volume work. Or if you don't want to ingest everything in there, you need to create a new ingest directory to hold 8555444 and then select that new directory.

**Comment by hackmastera** [comment]
If there's a way to reword the help text let's open another ticket for that!

**Comment by kelea99** [comment]
okie dokie! lemme try again and thank you, @hackmastera !

**Comment by kelea99** [comment]
@hackmastera did as you suggested and still a no go. Ive ingested MVWs before and have not had trouble. @roelmoon  and I did have this problem before, but with a periodical and we thought it was just Bulk ingest being broken?

**Comment by hackmastera** [comment]
@kelea99 Which directory did you ingest?

**Comment by kelea99** [comment]
First attempts: 8555444
Second attempt: pudl0130_1

**Comment by tpendragon** [comment]
I think this is the error we used to get on a load balancer time out. Did it spin for > 60s before showing the error?

**Comment by kelea99** [comment]
yes.

**Comment by hackmastera** [comment]
@kelea99 is this not it? https://figgy.princeton.edu/catalog/49add4a8-e4fc-4ddf-a533-b335f9b21b18

**Comment by cwulfman** [comment]
Something odd here: If I go to Figgy and search for 6109684 (https://figgy.princeton.edu/catalog?utf8=✓&q=6109684), I'm taken to a page for a collection named PUDL0130, which contains a single item (the Engelmann, 8555444).

**Comment by tpendragon** [comment]
We've much improved ingest, this should be fixed now.
