### ISSUE TITLE
Ingest type field from pulfa records

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#4009]
As discussed in #3972, we'd like to provide 'type' data as part of our oai_dc response in order to fulfill the requirements of the France in the Americas project.

Initial discussion suggests that this information might sometimes be found in the scopecontent element at the component level and/or at a parent component level and/or at the collection level. It might also be in unittitle. scopecontent appears to be used for description, so these are not machine-readable locations.

This issue can be closed when we have an archival collection with this data ingested into figgy and populating the 'type' field.

This issue is blocked pending a standard, machine-readable ead field to pull the data from (or set of machine-readable ead fields to check for in sequence), and an archival collection in which said ead field has been populated.

**Comment by tpendragon** [comment]
@kelea99 We think it's unlikely our EADs are going to get changed in a machine-readable way. Can we close this ticket and re-open it if the France in the Americas project shows that our type data for our EAD-powered items isn't good enough?

**Comment by kelea99** [comment]
Yes, I think that is reasonable. Closing now, @tpendragon
