### ISSUE TITLE
Figgy is very slow when one clicks "save and ingest" for one item (bib. id. 4836238)

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4018]
Is there a lot of stuff in the queue for figgy? Lauren from the studio mentioned it was super slow for her on her work machine in the Digital Studio.

User reports it took about a minute after pushing the "save and ingest" button.

**Comment by tpendragon** [comment]
There is, but I don't think it'd be slowing down ingest.

**Comment by kelea99** [comment]
Correspondence with Anna:
1. for the files it may just be because the background workers are chewing through other things. So new ingests will be prioritized but they may have to wait a minute for workers to free up. 

2. **Request from developers**: For the save and ingest It would be helpful to know if it’s variable (sometimes as expected and sometimes slow) or consistently slow.  _Update from Lauren: It is consistently getting slower on everything she saved/ingested since going back to the studio [in Firestone--since Monday?]._

**Comment by tpendragon** [comment]
We should follow up after preservation jobs are done.

**Comment by kelea99** [comment]
Update as of 06/29: Lauren said its a lot quicker today vs. last week, FYI.
