### ISSUE TITLE
[Figgy/production] LoadError: cannot load such file -- /opt/figgy/shared/bundle/ruby/2.6.0/gems/rsolr-2.3.0/lib/rsolr/error.rb

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4021]
## Backtrace

    line 94 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save_all
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39115500)

**Comment by christinach** [comment]
LoadError: cannot load such file -- /opt/figgy/shared/bundle/ruby/2.6.0/gems/rsolr-2.3.0/lib/rsolr/error.rb. It happens very often and maybe we should check the box for any rails env related errors.
