### ISSUE TITLE
Create a CDL::ChargeManager

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4026]
A CDL::ChargeManager is a persisted object representing the charges for items attached to a digital object.

See https://docs.google.com/drawings/d/1GdntEd_fiS4rsFbILK63woF9862ZnO8KgV5zE4p-VVU/edit

Open Questions:

1. Should it be attached to a figgy resource or a source metadata identifier? If an identifier has two Figgy resources, do they share the same charge manager?
2. If bibdata's suppressing items, how will we know which ones are eligible for CDL? Maybe we can't, and those ones shouldn't be charged?

**Comment by tpendragon** [comment]
Until we have concrete use cases use some sort of stubbed data for question 2, and assume it should be attached to a figgy resource for question 1.

**Comment by hackmastera** [comment]
When / where is this  object created / persisted? How does it interact with other figgy classes?

**Comment by tpendragon** [comment]
I suspect it's created the first time a charge is requested on a CDL eligible item? Or when the availability of charging is asked about for a CDL eligible item?

I suspect interaction is just Wayfinder.for(scanned_resource).cdl_charge_manager.
