### ISSUE TITLE
Send an event to Google Analytics when a resource is charged via CDL

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4031]
# Implementation Notes

Send the following data:

Event Category: `CDL - {patrongroup}`
Event Action: `charge`
Event Label: `{bibid}`

The following CURL is an example of the kind of data we should send:

```
curl --verbose -d "v=1&tid=UA-15870237-29&cid=96afa471-e575-4aac-b07b-f3af862cd9a0&t=event&ec=CDLTest - Staff&ea=charge&el=123456&ua=Figgy" -X POST https://www.google-analytics.com/collect
```

We can get the user's patron group from `https://bibdata.princeton.edu/patron/{{netid}}`. Figgy's already been added to the allowed list to access this data.

**Comment by christinach** [comment]
I can see 'patron group' but not a 'type'.

**Comment by christinach** [comment]
we get the patron group info from https://github.com/pulibrary/voyager_helpers/blob/0d8f633f1fbf258331cbf64baec4ba937f999224/lib/voyager_helpers/liberator.rb#L794

**Comment by kelynch** [comment]
Per Web Analytics meeting with ITIMS this morning, we're going to Google Analytics to record this.
