### ISSUE TITLE
Develop an abstraction to check which items for a given SourceMetadataIdentifier are eligible to be charged for CDL.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4033]
Something like a
```ruby
class ChargedItemsQuery
  def initialize(source_metadata_identifier:)
  end

  def item_ids
    ['1234', '5678']
  end
end
```

This could be a valkyrie CustomQuery, but I don't know if that's necessary, and wouldn't be very separated from the rest of the stack.

The query shouldn't return the item IDs which aren't currently charged (that's for the CDL::ChargeManager to figure out), just those which have been placed on hold for the CDL program.

This will query bibdata.

**Comment by hackmastera** [comment]
Per discussion in checkin, this will likely be a service with the query as a method on that service.
