### ISSUE TITLE
PreservationObjectDecorator raises exception when resource has no title

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4035]
[Figgy/staging] ActionView::Template::Error: undefined local variable or method `title' for #<PreservationObjectDecorator:0x00007f13d9af0250>

## Backtrace

    line 114 of [PROJECT_ROOT]/app/decorators/valkyrie/resource_decorator.rb: titles
    line 4 of [PROJECT_ROOT]/app/document_presenters/valkyrie_show_presenter.rb: heading
    line 3 of [PROJECT_ROOT]/app/views/catalog/show.html.erb: _app_views_catalog_show_html_erb__2034888652874455888_46996164128700

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/65213216)

 https://figgy-staging.princeton.edu/catalog/82bfc327-d395-4df7-a534-37b4bf474c27

**Comment by hackmastera** [comment]
Looks like this issue was created off the staging error notification. Here's the one on prod: https://app.honeybadger.io/projects/53391/faults/59196826

**Comment by hackmastera** [comment]
This happens when you try to view a show page for a PreservationObject. Do we have / want a show page for a PreservationObject?
