### ISSUE TITLE
Bad file descriptor @ io_fread

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4036]
[Figgy/production] Errno::EBADF: Bad file descriptor @ io_fread - /opt/repository/files/21/f1/d9/21f1d9338bab4e4e8106dbb1e157f29a/00000239.tif

Errno::EBADF: Bad file descriptor @ io_fread - /opt/repository/files/f6/0a/69/f60a696787f74d429626c8722db0655a/00000222.tif

Errno::EBADF: Bad file descriptor @ io_fread - /opt/repository/files/56/53/62/565362e572b2412aaf63cac628d19bff/00000221.tif

There's not a convenient way to query for the FileSet and Resource parents of these file to check into this further. Perhaps creating a FileMetadata ID query would be helpful.

## Backtrace

    line 8 of [PROJECT_ROOT]/app/resources/nested_resources/multi_checksum.rb: for
    line 47 of [PROJECT_ROOT]/app/services/preserver/preservation_intermediary_node.rb: calculate_checksum
    line 40 of [PROJECT_ROOT]/app/services/preserver/preservation_intermediary_node.rb: build_preservation_node

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/65173002)

**Comment by eliotjordan** [comment]
Also related: 

https://app.honeybadger.io/projects/53391/faults/65018583
