### ISSUE TITLE
PDFs should be split into page images

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4067]
There are two cases where PDFs don't meet our needs for end-user display:
1. For CDL, PDFs are downloadable and shouldn't be
2. For very large PDF files, the viewer performance is much worse than page images.

So we should split PDFs into page images and use those images to drive the viewer. This will provide a better experience and be compatible with our CDL requirements.

## Technical Requirements

The PDF should be converted to Tiffs
The original PDF should be preserved.
The PDF shouldn't show up in the viewer.

## Possible Implementations

1. Don't embed PDFs at all in manifests anymore, and just ignore PDFs. (Don't do this if there's a time lag between this and #4119)
2. Mark the PDF as a preservation master, and each of the tiffs as an intermediate file.
3. Store the PDF on the resource or in some other thing not collected as a member.

**Comment by tpendragon** [comment]
Always?

**Comment by escowles** [comment]
Yes, I think it makes sense to always do this, and I've updated the ticket description accordingly.

**Comment by hackmastera** [comment]
@kelynch suggests looking at https://gist.github.com/wcaleb/7337097
