### ISSUE TITLE
Create wireframe for File Browser Upload in Figgy

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4072]
Child of #4071

**Comment by tpendragon** [comment]
![Screen Shot 2020-07-09 at 11 54 13 AM](https://user-images.githubusercontent.com/2806645/87079471-f83d0000-c1da-11ea-8be9-ffe8fdc68092.png)

**Comment by kelynch** [comment]
Looks good so far, looping in @kelea99 to take a look.

**Comment by kelea99** [comment]
@tpendragon this looks great so far. Clean and straight forward
