### ISSUE TITLE
Cloud fixity failures for items no longer in Figgy

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4078]
Instead of erroring, we should check figgy to see if the item has been deleted and then... just carry on?

HB notice: https://app.honeybadger.io/projects/53391/faults/59168201

This honeybadger notice is gone, but to test this we can run the job on a non-existent ID.

## Success Criteria

Don't error if the object is gone.

**Comment by tpendragon** [comment]
Is this a duplicate of https://github.com/pulibrary/figgy/issues/3814?
