### ISSUE TITLE
Object thumbnail set to orphaned file set

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4079]
`thumbnail_id` for this object is this fileset, which has no parent. object has a different fileset as page 1.

Tasks here:
- [ ] Just set `thumbnail_id` to the actual page 1? Any cleanup needed?
- [ ] Replicate the conditions that lead to this state; ensure we don't get here in the future.

HB error: https://app.honeybadger.io/projects/53391/faults/55188222

The result of this error is that the order manager won't load and the Orangelight query won't resolve. The thumbnail ID is set to a resource which exists, but has no parent.

Maybe there's some sort of race condition?

**Comment by eliotjordan** [comment]
While not a systemic fix for this, on geo resources we allow users to select the thumbnail from a dropdown menu on the edit page. With scanned resources, the way to set a thumbnail is through the order manager, but this doesn't work because the initial graphql query fails.

**Comment by tpendragon** [comment]
The item's gone from honeybadger log. Closing until we see it again.
