### ISSUE TITLE
Add CDL::CDLController#renew

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4084]
This should renew a charge if the user's charge is renewable.

Implementation notes:

`CDL::ChargeManager#renew(netid:)` should check `renewable?`, and if it's true then update the expiration date of the existing charge.

`renewable?` should return true if the user has an existing charge on the resource, there are no holds in the hold_queue, and it expires in the next 15 minutes.

**Comment by hackmastera** [comment]
`renewable?` should also check that the hold queue is empty. (hold queue implemented in https://github.com/pulibrary/figgy/pull/4097). I'll update the description.

**Comment by tpendragon** [comment]
We decided they can just check it out again.
