### ISSUE TITLE
Add ChargeManager#activate_holds

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4090]
## Implementation Notes

Do nothing if there's no available charge slots.

For every available charge slot, find the next inactive hold and give it an expiration time 1 hour in the future. Send an email to the user notifying them that they have the item on hold. The text of the email should be something like

Subject: `Available for Digital Checkout: < resource title >`

Body:
> < resource title > is now available for check out for the next 1 hour. In that time please visit the catalog here(link to catalog) to view it.

We can probably do better than that, but that's what I got at the moment.

ALSO, if there are any expired holds delete them from the hold_queue and notify the appropriate user that their hold's expired.

**Comment by hackmastera** [comment]
I think this changed to 1 hour; updating description.
