### ISSUE TITLE
"Princeton University Glee Club" shows up as a collection in the collections facet, but i can find it nowhere

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4105]
Any ideas what is going on? the PU Glee Club is a collection, created by Dan G.  
<img width="1440" alt="Screen Shot 2020-07-16 at 1 56 05 PM" src="https://user-images.githubusercontent.com/45043014/87705679-47031080-c76c-11ea-8145-152139f4f600.png">

**Comment by tpendragon** [comment]
The collection isn't a member of itself. To find the collection record you can either click through to a member and click the link to the collection, or search like this:

![Screen Shot 2020-07-16 at 11 11 56 AM](https://user-images.githubusercontent.com/2806645/87706984-3eeba680-c755-11ea-88c0-48654f55359b.png)

**Comment by tpendragon** [comment]
I think those items just need reindexed?

**Comment by kelea99** [comment]
That worked! thanks, @tpendragon ! Closing ticket.
