### ISSUE TITLE
Import metadata from ArchivesSpace

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4113]
Once we migrate to ArchivesSpace, we should import metadata for finding aids objects from ASpace API instead of from PULFA.

**Comment by tpendragon** [comment]
## Technical Implementation

`RemoteRecord.retrieve` should check to see if a thing looks like an ASpace ID (I think they all contain the string "aspace"), and if so spin up a new `ArchiveSpaceRecord`.

`ArchiveSpaceRecord` 

https://archivesspace.github.io/archivesspace/api/#get-an-ead-representation-of-a-resource211 has some documentation on how to get a record out of ASpace. We might be able to not get the EAD representation and just pull the JSON (which I think is the same path but no `.xml` at the end.) Need a spike to try it out when we have real data in there.
