### ISSUE TITLE
Javascript error on non-cdl item viewer

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#4120]
Looking at https://figgy.princeton.edu/catalog/0343b536-82ba-4224-bcf2-6fde9a0caf30

<img width="867" alt="Screen Shot 2020-07-21 at 10 18 54 AM" src="https://user-images.githubusercontent.com/845363/88066413-bd708b80-cb3b-11ea-8f56-68b8ad6794db.png">

**Comment by tpendragon** [comment]
Closed by #4217
