### ISSUE TITLE
CDL Automated Ingest

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4133]
As we need to handle bulk ingest of hundreds of PDFs to enable as-fast-as-possible scanning for CDL, we'd like a low-touch method of ingesting them. We accept that several of the objects that will be ingested this way and marked complete will likely have problems, and suffer from a lack of mediation.

## Implementation Details

1. Every night a cron job should run which ingests all PDFs from a directory. They should be ingested as a `CDL::ResourceChangeSet`, which will be used as a change set on top of a ScannedResource. The following defaults should be set:
    * Source Metadata Identifier is the name of the PDF.
    * Visibility: Private
    * Collection: https://figgy.princeton.edu/catalog/fad1929d-01ca-4888-aa32-f59e51bca7c9
    * Rights Statement: In Copyright
    * Download: None
    * ocr_language nil

2. Every hour a cron job runs which looks for every `CDL::ResourceChangeSet` which is pending, checks to see if all of its derivatives have been generated, and makes sure `ManifestBuilder` is able to generate a manifest from it. If it can, mark that resource complete.

Three Parts:

- [x] Add `CDL::ResourceChangeSet`
- [x] Add automatic ingester
- [ ] Add automatic completer.

**Comment by kelynch** [comment]
Regarding open question #2, this is a good name, and the share has been created.  The figgy service account utilized in the current ocr_pdf workflow has been granted read/write access to the share.

**Comment by escowles** [comment]
Some answers:

* 1: I've created a [CDL collection](https://figgy.princeton.edu/catalog/fad1929d-01ca-4888-aa32-f59e51bca7c9) that items should be added to.
* 3: Let's leave OCR language blank for now. I suspect we don't need to set this unless we want to do OCR to help creating a text alternative for accessibility reasons.
* 4: Yes, it's OK to email when an item is marked complete

**Comment by tpendragon** [comment]
The automatic completer turned out to be more complicated than I expected. Priorities have shifted a bit, so I'm putting this back into Ready and moving to a high priority ticket.
