### ISSUE TITLE
File exists @ dir_s_mkdir - /mnt/diglibdata/hydra_binaries

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4138]
## Backtrace

    line 12 of [PROJECT_ROOT]/app/jobs/create_ocr_request_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/66271391)

**Comment by christinach** [comment]
The file existed already and it triggered an error. 
`ocr_request.pdf.attach(io: File.open(file_path), filename: filename, content_type: "application/pdf")`

**Comment by tpendragon** [comment]
Hasn't happened in a while. Closing and resolving, assuming it was a mount problem.
