### ISSUE TITLE
Should we make an addition to the collections facet for items associated with no collections? 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4141]
Tom V. asked a question in the #digital-library channel, which indirectly touched on this. It would probably be useful to folks to be able to search for those items not tagged with any collection name.  Thoughts?

**Comment by tpendragon** [comment]
@kelea99 Until someone's unable to find their item because of this, can we close this issue?

**Comment by kelea99** [comment]
We can for now.

**Comment by kelea99** [comment]
Nevermind, @tpendragon ! Figured out a way to get the same information by searching with what is already available. example (Japanese Language items not associated with collections): https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&f%5Bdisplay_language_ssim%5D%5B%5D=Japanese&q=NOT+%22Treasures+of+the+Cotsen+Collection%22+and+NOT+%22Marquand+Library+Selections%22+and+NOT+%22East+Asian+Library+Tables+of+Contents%22+and+NOT+%22Treasures+of+the+East+Asian+Library%22+and+NOT+%22Tokaido+Road%22+and+NOT+%22Treasures+of+the+Manuscripts+Division%22+and+NOT+%22ABC+Books%22+and+NOT+%22Cotsen%22#
