### ISSUE TITLE
"Settings50" and "Settings82" items blocking fixity check queue

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4145]
These two resources appear to have errors and are blocking the fixity check queue.

In the past the queue has been blocked by orphaned file sets, but in this case the resources exist but with invalid files.

Seems like this needs to be investigated and maybe these should be deleted and reingested.

**Comment by tpendragon** [comment]
I think all of these are just accidental ingests anyways. @roelmoon is it safe to delete the resources named "Settings50" and "Settings82"?

**Comment by tpendragon** [comment]
We think we can just delete all of these.
