### ISSUE TITLE
Derivatives failing for several images of "Sweetheart Bible"

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4150]
https://figgy.princeton.edu/concern/scanned_resources/1b30338b-6c56-460b-9503-c8b99c946979/file_manager

pages 672, 674, 676, 678, 680, 743

https://app.honeybadger.io/projects/53391/faults/64185746/fb6b64f2-d412-11ea-8cb4-2a75281602c0

**Comment by tpendragon** [comment]
These got reuploaded.
