### ISSUE TITLE
All resources should be able to generate an authentication token link for use with courses.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4151]
## Use Case

At times a class needs access to a set of materials digitally. That class should be the only ones eligible to access and view that material. So, as with Music Reserves, an auth token should be able to be generated which provides access to a single resource similar how it currently works for Playlists. We should be able to revoke that authorization token. Users who access via this token should not be able to view the download dialogue or create a PDF from the resource.

## Technical Implementation Notes

Playlists implement this via the following property, which should work for all resources:

https://github.com/pulibrary/figgy/blob/7be7f14cf7dd10bd93d8a8f289715cdce897069a/app/resources/playlists/playlist.rb#L12

One problem with this is right now it appears that folks can download the material if they are authorized to view the FileSet:

https://github.com/pulibrary/figgy/blob/7be7f14cf7dd10bd93d8a8f289715cdce897069a/app/models/ability.rb#L39-L41

We'll have to add tests to make sure that works right.

As soon as the ChangeSet responds to `auth_token` it should render the little token widget in Figgy's show page. To make that work, the ChangeSet and Resource needs to have the following:

https://github.com/pulibrary/figgy/blob/master/app/resources/playlists/playlist_change_set.rb#L12
https://github.com/pulibrary/figgy/blob/master/app/resources/playlists/playlist_change_set.rb#L16
https://github.com/pulibrary/figgy/blob/master/app/resources/playlists/playlist.rb#L24-L26

We'll probably have to just add those to `Resource`? Or maybe just to `ScannedResource` for now? Do you want us to avoid adding this feature to Maps/etc right now @eliotjordan ?

## Details of implementation right now

1. If a ChangeSet responds to `auth_token` then display a form/button for generating a link: https://github.com/pulibrary/figgy/blob/7be7f14cf7dd10bd93d8a8f289715cdce897069a/app/views/catalog/_auth_link_default.html.erb#L1
  * The form requires a `mint_auth_token` boolean on the ChangeSet to work, which works with `app/change_set_persisters/change_set_persister/apply_auth_token.rb`
2. If a resource class responds to `tokenized_access`, is marked complete, and doesn't have an auth token already then `ApplyAuthToken` mints one. We may want to adjust this so it'll only generate an auth link when we ask it to? https://github.com/pulibrary/figgy/blob/7be7f14cf7dd10bd93d8a8f289715cdce897069a/app/change_set_persisters/change_set_persister/apply_auth_token.rb#L12-L18
3. When an auth token is passed which matches the resource's auth token property, then it's given read/download access to the resource via `Ability#token_readable?`: https://github.com/pulibrary/figgy/blob/7be7f14cf7dd10bd93d8a8f289715cdce897069a/app/models/ability.rb#L324-L327

**Comment by hackmastera** [comment]
What do you mean by "We may want to adjust this so it'll only generate an auth link when we ask it to?"? Isn't it only generating if the change set has `mint_auth_token == true`?

**Comment by eliotjordan** [comment]
@tpendragon Yes, let's add this to maps and geo material. It seems especially likely that scanned maps will be requested for a class at some point.

**Comment by tpendragon** [comment]
@hackmastera Right now it generates a token when marked complete. We might want it to have no token until you hit a button.

**Comment by tpendragon** [comment]
This use case will be handled by #4169 instead. It turned out that there were too many resources to generate and manage individual links per resource for a class.
