### ISSUE TITLE
Open visibility content from Paul A Volker Papers (MC279) not showing up when refining search to "online only" in PUL Finding Aids site

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4166]
Example from Alexis A. : 
when you run this search https://findingaids.princeton.edu/?v1=Volcker&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0&has-digital-content=true

this folder with digital content doesn't display when you check the online only box https://findingaids.princeton.edu/collections/MC279/c184

**Reason for Priority: t**his is time sensitive due to a press release about to go out so if this cannot be fixed fairly quickly then, please let Alexis A. and the ADAPT team know. They can tweak the press release.

**Comment by kelea99** [comment]
update: @hackmastera  thinks the issue may be an indexing problem on the pulfa side. its syncing from figgy fine. updated Alexis and @kevinreiss in #pulfa slack channel.  @kevinreiss , where to add a ticket for this? Im closing the issue for figgy.

**Comment by sdellis** [comment]
@kelea99 this is an indexing problem on the pulfa side. However, the issue is that the MC279 file is not valid and causing the indexing process to fail. The solution is to validate the EAD data before checking files into SVN. This is the responsibility of the Mudd technical services staff.

**Comment by kelea99** [comment]
Thank you, @sdellis ! Writing to #PULFA channel now. standby

**Comment by kelea99** [comment]
nevermind! you got it! thanks so much, @sdellis !
