### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4167]
## Resources

A script Esmé wrote to:

1. rename master to main
2. create an alias from master to main (to prevent PRs from being closed, links breaking, etc.)
3. use the github api to make main the default branch

https://gist.github.com/escowles/eed4567d818f77811311386df8e71133

---
Github's [Renaming](https://github.com/github/renaming) repo

Note: Branch protection policies need to be transferred to the new branch

Document updating local clones

**Comment by hackmastera** [comment]
Notes:

Esmé's script starts off by deleting the repo locally, then cloning it anew. I wasn't really wanting to do this, for fear of losing local work that I'd stashed or accidentally losing a branch I had wip on. So I ran it in a different location.

Steps:

- Clone Esmé's script to some location, cd there, make it executable
- Run the script
- Change the base/target of all open PRs. They won't close automatically but merging them will merge them to master, not to main.
- Transfer branch protection policies
- All devs will need to update local settings
  - Delete 'master' branch from local clones
  - run `git symbolic-ref --short refs/heads/master refs/heads/main` to protect yourself when you accidentally try to checkout master (this will give you main instead)
  - Not sure what others will encounter, but as a user of the `hub` command line tool I had to run this to ensure my PRs will issue to the correct target base: `git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main`
  - do `git branch -r --delete origin/master` to remove the local reference to `remotes/origin/master`

**Comment by hackmastera** [comment]
Note this hasn't been run on figgy yet

**Comment by hackmastera** [comment]
TODO: figure out how to adjust deploy bot

**Comment by hackmastera** [comment]
Also try out https://github.com/mheap/github-default-branch

**Comment by hackmastera** [comment]
Pretty sure the pulbot question is just a matter of changing the default branch to deploy in figgy's `deploy.rb`.

The https://github.com/mheap/github-default-branch tool worked great and did all the things it promised to do, including updating the base of open PRs, changing the default branch, and migrating branch protection rules.

So the steps would then be:

1. Run the tool
2. Create a PR updating the default branch in `deploy.rb`


Follow-up required for with my local clone was:

- Run `git fetch`
- Delete local 'master' branch: `git branch -d master`
- Not sure what others will encounter, but as a user of the hub command line tool I had to run this to ensure my PRs will issue to the correct target base: `git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main`

**Comment by hackmastera** [comment]
Okay it will keep deploying master: 
https://github.com/atmos/hubot-deploy/blob/c0b0dc89c875b919d1905899825d8afc4ba84d09/src/scripts/deploy.coffee#L102

So if we run this migration we'll have to always start specifying 'main' aka `pulbot deploy figgy/main to production`. Otherwise I guess we could fork that project and update it. It's abandoned. I'll bring this for discussion this afternoon.

**Comment by hackmastera** [comment]
https://github.com/pulibrary/figgy/pull/4196 will keep hubot-deploy working as it has been.

The default branch of figgy is now "main".

**Comment by hackmastera** [comment]
Note we also needed to fix the nightly build and release notes check: https://github.com/pulibrary/figgy/pull/4199
