### ISSUE TITLE
Improve quality of tiffs generated from PDFs

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#4168]
@hackmastera commented on [Fri Aug 07 2020](https://github.com/pulibrary/orangelight/issues/2177)

pdfload has a `dpi` option, maybe we can use that. https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-pdfload

**Comment by tpendragon** [comment]
Make sure we regenerate derivatives for the PDFs already ingested for CDL.
