### ISSUE TITLE
Make "Reading Room" items available through CDL for 30 simultaneous users

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4169]
Made visible through the Finding Aid, allow "Reading Room only" items to be checked out via CDL workflow for up to 30 simultaneous users.

## Technical Implementation Notes

Add a clause to the `CDL::EligibleItemService` which checks to see if it's reading room only and just returns an array of 1-30 as strings if it is. Add some tests to `ability.rb` to ensure that a reading room only item is discoverable, but can't be read unless the person has the item checked out. Make sure it's also not downloadable.

**Comment by tpendragon** [comment]
Closed in preference for #4181
