### ISSUE TITLE
Confirm that lib-proc6,9,11 all have access to lib-ponyexpr

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4170]
[Figgy/production] Errno::EHOSTUNREACH: No route to host - connect(2) for "lib-ponyexpr.princeton.edu" port 25

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/66507804)

**Comment by eliotjordan** [comment]
Sent an email to l-support about this.

**Comment by eliotjordan** [comment]
Resolved. proc6,9,11 added to the ponyexpress approved list.

**Comment by eliotjordan** [comment]
Re-opened the SNAP ticket to check on  lib-proc7,8, and 10.

**Comment by eliotjordan** [comment]
7,8, and 10 have been added.
