### ISSUE TITLE
METS Ingest doesn't work for any(!?) PUDL collections

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4179]
IngestMETSJob expects the METS document to have a ```<div TYPE="IsPartOf">``` that has a CONTENTIDS attribute containing a slug to be used in determining what Figgy collection to ingest the object into. None of the pudl METS actually have such an element, or such an attribute.

See also #1689 ; #1742

**Comment by tpendragon** [comment]
IngestMETSJob is written to process a combined METS/MODS document that was generated by @jpstroop. We used to pull them off a google drive - I don't have them on hand, maybe @escowles does?

**Comment by cwulfman** [comment]
Doesn't show up here https://drive.google.com/drive/u/1/search?q=IsPartOf%20parent:1vM0mkt62UeRICyc45SlRnt9LgHxMnK-j

**Comment by cwulfman** [comment]
I'm assuming the short answer is to write some new code to handle the actual METS/MODS we have.

**Comment by escowles** [comment]
Or update the METS files to have the expected `IsPartOf` div? The files we ingested most of the PUDL content from had StructMaps that started like this:

```
<mets:structMap TYPE="RelatedObjects">
  <mets:div DMDID="q6wwb r7db1" ID="e4lns" LABEL="Default">
    <mets:div CONTENTIDS="pudl0001" TYPE="IsPartOf"/>
```

**Comment by escowles** [comment]
Also, I do have METS files with `IsPartOf` divs for most of PUDL, but I strongly suspect these are the collections that have already been ingested:

pudl0001, pudl0002, pudl0003, pudl0004, pudl0006, pudl0007, pudl0008, pudl0009, pudl0011, pudl0013, pudl0014, pudl0016, pudl0017, pudl0021, pudl0022, pudl0023, pudl0024, pudl0027, pudl0028, pudl0032, pudl0036, pudl0038, pudl0044, pudl0045, pudl0046, pudl0053, pudl0058, pudl0059, pudl0063, pudl0064, pudl0067, pudl0069, pudl0070, pudl0071, pudl0072, pudl0073, pudl0074, pudl0075, pudl0076, pudl0077, pudl0079, pudl0081, pudl0085, pudl0087, pudl0090, pudl0091, pudl0094, pudl0100, pudl0102, pudl0104, pudl0105, pudl0106, pudl0107, pudl0112, pudl0114, pudl0115, pudl0116, pudl0117, pudl0118, pudl0120, pudl0122, pudl0123, pudl0124, pudl0125, pudl0126, pudl0127, pudl0129, pudl0132, pudl0134, pudl0135, pudl0137, pudl0139

**Comment by cwulfman** [comment]
IngestMETSJob was created quite some time ago to ingest some hybrid METS/MODS @jpstroop created for (some) PUDL collections.  Based on discussion with @hackmastera and @tpendragon , I'll modify ingest_ephemera_mods to handle the GNIB MODS.

**Comment by jpstroop** [comment]
I don't think I ever 'compiled' pudl0066 (I really hope I can forget these numbers someday).
The METS that are used to ingest into Figgy have just a slightly different flavor (don't ask me what now) from the PUDL MODS, and there's some ancient code on a branch of PUDL that should be able to make the METS that you need: 

https://github.com/pulibrary/pudl_mets_compiler/tree/plum_migration

I can fire up my old dev machine in the next few days and see if it just works; not sure why it would be different from any other collection.

**Comment by cwulfman** [comment]
No worries, @jpstroop.  I met with @tpendragon and @hackmastera this afternoon, and I've now got it well in hand!

**Comment by tpendragon** [comment]
The use case here was actually to ingest some Ephemera items, pulling metadata from MODS documents. We used `ingest_ephemera_mods` instead, which got the job done. Closing.
