### ISSUE TITLE
I would like bulk add a new collection to all items within the Spainish 15M Ephemera Collection

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4185]
New Collection Name to be added : [Latin American and Iberian Studies Collections](https://figgy.princeton.edu/catalog/e9709523-ec23-4eb0-9dd3-002746b91d13)

Collection that needs the new tag. **Important** : please retain the original collection tag as well. this will be used as a sub-collection facet in DPUL):  https://figgy.princeton.edu/catalog/70433c80-ca9e-4ade-9687-8c98f72875bc

I have also updated [#2862](https://github.com/pulibrary/figgy/issues/2862#issuecomment-673590757) with this use case.

**Comment by tpendragon** [comment]
@kelea99 Do you want all folders, whether they're in a box or not, to be added to this collection?

**Comment by kelea99** [comment]
@tpendragon , I'm about to have a look, but can you give an example of what you mean, to ensure I'm understanding correctly?

**Comment by tpendragon** [comment]
@kelea99 Just confirming that, for example, https://figgy.princeton.edu/catalog/parent/bddbafd7-e08d-4eab-82d9-b585bd31661b/993573ea-cbb8-4538-94f4-e89cf62cf6eb should have the collection added and not just the boxless folders.

**Comment by kelea99** [comment]
@tpendragon, correct. Boxed folders and boxless folders are both included in the Spain 15M dpul exhibit. The complete collection is needing that new collection tag, in addition to the Spain 15 M one. thanks!!

**Comment by kelea99** [comment]
reopening this. I cant see the second collection and it isnt mapping into DPUL. can we try this again?

**Comment by tpendragon** [comment]
@kelea99 Is this done now? Looking at a few they're in the collection.

**Comment by kelea99** [comment]
Yes. this is complete. closing.
