### ISSUE TITLE
Upgrade to Solr 8

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4193]
# Strategy for Production

1. Create princeton_ansible PR to point to solr8, put it up as a draft.
2. Create a collection in solr8 with one replica. 
3. Create a branch that enables index read only mode, push it up and deploy it.
4. Start the reindex job as BATCH_SIZE=100 CLEAN_REINDEX_SOLR_URL=http://lib-solr8.princeton.edu:8983/solr/figgy bundle exec rake reindex
    * This will take ~ 18 hours.
5. When reindex is done, in the solr console add two replicas.
6. When replicas are green run your princeton ansible playbook branch as `ansible-playbook playbooks/figgy.yml --tags site_config
7. Redeploy main.
8. Mark your Ansible PR as ready to merge.

**Comment by hackmastera** [comment]
related: https://github.com/pulibrary/figgy/issues/1903, https://github.com/pulibrary/figgy/issues/3034

**Comment by hackmastera** [comment]
This plan looks great. I would be in favor of using read-only mode. It would be good to update this issue with a time estimate once the current reindex is finished, to get a sense of impact. There is a bug with read-only mode; not sure of its impact, either: https://github.com/pulibrary/figgy/issues/2866

**Comment by tpendragon** [comment]
I kicked off a reindex in lib-proc11 tonight just to see how far it gets.

**Comment by tpendragon** [comment]
Reindexing improvements in #4602 bring the estimate down to 92 hours. I think we're still indexing too much, though.

**Comment by tpendragon** [comment]
When reindexing at 500/batch Solr8 threw a timeout error. Trying to run it with 100/batch and pointed directly at the leader now. I also disabled soft commits by overriding `Valkyrie::Persistence::Solr::Repository::COMMIT_PARAMS = {}.freeze` before the task ran.

Current estimate is 14 hours for 6,724,594 objects, but it just started so that estimate will probably go up.

**Comment by tpendragon** [comment]
Test index took ~ 21 hours and failed to index 3 things.
```
E, [2021-09-18T00:14:31.938747 #27746] ERROR -- : Could not index bdbba79d-72c1-4238-ba69-99c741dd00a5 due to RSolr::Error::Http                             E, [2021-09-18T00:14:31.969881 #27746] ERROR -- : Could not index 0fb4f29c-547c-4ec4-a9c6-bc47cf43c742 due to RSolr::Error::Http
E, [2021-09-18T00:14:32.360729 #27746] ERROR -- : Could not index 39f13dcd-247d-46bf-bc2e-40e7949c3c4d due to RSolr::Error::Http                             E, [2021-09-18T00:14:45.806319 #27746] ERROR -- : Could not index 392e0a93-b15d-46b9-8b8f-249c7f217de5 due to RSolr::Error::Http
```

**Comment by tpendragon** [comment]
We did it!
