### ISSUE TITLE
Fix binstubs

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4211]
The Rails binstub broke when bootsnap was introduced.

**Comment by eliotjordan** [comment]
@hackartisan I can't replicate this ticket it my local environment. If they're still broken, please post steps to replicate and I'll work on fixing them.

**Comment by hackartisan** [comment]
No it looks like it's working again! thanks for checking.

**Comment by hackartisan** [comment]
It was working for `bin/rails c` but broken still for `bin/rails s`. figured it out; PR incoming.
