### ISSUE TITLE
complete Ark URLs needed in identifier field for france in the americas

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4227]
Original Correspondence from BnF to Steve Knowlton (@kelynch and I have asked if we might be able to email the BnF directly to discuss this further):
_Unfortunately we can't convert the partners oai data and need the links leading to the https://arks.princeton.edu/
Please, could you add an additional dc:identifier with the complete link in your data ?
For exemple,

```xml
<dc:identifier>ark:/88435/9306t5233</dc:identifier>
<dc:identifier>https://arks.princeton.edu/ark:/88435/9306t5233</dc:identifier>
```

**Comment by kelynch** [comment]
@kelea99 and I suggested that they could prepend the URL "https://arks.princeton.edu/" value to the identifier value upon harvest.  However according to their response, they're unable to do this.  Is this something that we want to support, either for all oai_dc, or on a set-by-set basis?  Are there collections we want to make publicly harvestable but their ark URL shouldn't be part of the public set?

**Comment by kelea99** [comment]
@kelynch I am uncomfortable with the idea of having all ark URLs within all aoi_dc.  There are some items that live only in figgy for various reasons. Am I being overly cautious? What are your thoughts?

**Comment by kelynch** [comment]
@kelea99 I agree, an across-the-board change seems risky to me.  @hackmastera is also evaluating this.

**Comment by hackmastera** [comment]
I don't really understand the concern. if we're giving the id then giving the link is equivalent, in terms of telling people where to find it. If they aren't allowed to access it figgy won't let them view it. In general arks point to catalog or pudl records. Numismatics items are an exception and we have a ticket to repair that. 

Adding this additional identifier field should be pretty straightforward.

**Comment by kelea99** [comment]
@hackmastera i guess my concern is that items not in catalog/pudl records will be directed to figgy (whether or not they will be able to view anything), right? do we really want folks directed there? Yay for numismatics fix, btw.

Regarding adding additional identifier field: great!!

**Comment by hackmastera** [comment]
@kelea99 Is there any item you know of whose ark goes to figgy? the numismatics ones are the only ones I know about.

I know there has been some analysis of where the arks go. I think @escowles did that -- maybe he can speak to this concern.

**Comment by kelynch** [comment]
I spoke with @hackmastera offline, and I think we should be OK to distribute the ark URLs.  They're intended for public distribution.  Private items won't show up in the OAI feed to be harvested.  Items that do display in the feed will have an ark URL that resolves to a public URL like the catalog, DPUL, or PULFA.  As mentioned, the only exception is coins, and we have a ticket for that.

**Comment by hackmastera** [comment]
(Also, yes to everything @kelynch just said. The ark destination analysis had slipped my mind when we were talking about it.)

**Comment by kelea99** [comment]
@hackmastera and @kelynch sounds good.

**Comment by hackmastera** [comment]
@kelea99 this is done and deployed to production.

**Comment by kelea99** [comment]
Thank you, @hackmastera, @kelynch and @tpendragon! Emailing BnF now.
