### ISSUE TITLE
Collection selection not saving when trying to do so in "Save Draft" mode.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4229]
Example: 
Go to edit screen of: https://figgy.princeton.edu/concern/ephemera_folders/9009c5dd-8966-4814-b6e4-07acccaf5d19/edit

Try adding a collection from pulldown screen and click "Save Draft"

refresh page

Collection tag has not been saved.

**Comment by tpendragon** [comment]
I see collections being saved, they're just not displaying.
