### ISSUE TITLE
As a user, I want to be able to ingest non-catalogued items into Figgy

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4233]
Use case:  I have a collection of digitized items that are not in the catalog but have detailed bibliographic metadata in MODS.  I want to be able to ingest them into Figgy without associating them with a BibID or a Finding Aid.

**Comment by tpendragon** [comment]
We need to talk about this in a longer form format. Maybe @cwulfman or @kelea99 can put together a meeting? According to the Archival Description in Figgy working group, all items which have a finding aid should have item-level finding aid metadata. In cases where there isn't, a data reconciliation project should be undertaken (much as was done for western americana.) You can find the report here: https://docs.google.com/document/d/1pkhMDZcumPWgfSBiFzkTzaEVpuvwTMJMHuzW-UoDrCc/edit

**Comment by kelea99** [comment]
@tpendragon , sure. Ill schedule something for us. this is a helpful document, thank you

**Comment by tpendragon** [comment]
@kelea99 Can we close this issue?

**Comment by kelea99** [comment]
yup. closed @tpendragon
