### ISSUE TITLE
Viewer should display link to takedown policy

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4234]
We are in the process of posting an official takedown policy and request form. Once that is up, the Figgy viewer should display a link to it.

**Comment by escowles** [comment]
The takedown info page and form is now available at https://library.princeton.edu/takedown-request

**Comment by escowles** [comment]
Having a text notice below the viewer would be fine. There may be additional kinds of links requested (harmful content, suggest a correction, etc.) so having room for additional links might be good.

**Comment by kelynch** [comment]
Mockup:
![takedown](https://user-images.githubusercontent.com/7795797/123484405-4a3a8980-d5d6-11eb-990a-86ad3bd9654c.png)

**Comment by kelynch** [comment]
Alert icon PNG available here - https://drive.google.com/file/d/1QE2fWIvhgiSLrsD2RctgL5eh2ROilXhs/view?usp=sharing
