### ISSUE TITLE
Graphql should parse `.` in pulfa id

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#4236]
The javascript-based viewer is broken on https://findingaids.princeton.edu/collections/AC107.02/c1019 with an error returned from the figgy graphql as follows:

```
{"errors":[{"message":"Parse error on \".\" (error) at [2, 40]","locations":[{"line":2,"column":40}]}]}
```

**Comment by tpendragon** [comment]
This turned out to be a PULFA JS issue. I should have the fix soon.

**Comment by tpendragon** [comment]
https://github.com/PrincetonUniversityLibrary/pulfa/pull/1229 should close this issue.
