### ISSUE TITLE
Ingest strategy needed for folder of .wav files

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#4239]
These are on [google drive](https://drive.google.com/drive/folders/1A2OxindIgW8k3teu6DnYiy65Z4pU3a-Q), and user has no access to the isilon mount. There are 39 items ranging in size from 214MB to 3GB. (note: Access to the drive is restricted and must be added on an individual basis.)

Google drive integration is not working for this user. Attempts to upload via drag-and-drop were unsuccessful.

Contact Christa when we can accept these items.

**Comment by tpendragon** [comment]
We moved the items to the Isilon in `ingest_scratch` via the `drive` CLI utility.
