### ISSUE TITLE
Display a banner when the viewer is visible for a non-public item

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4251]
We have the viewer from Figgy embedded in frontend applications (Orangelight, PULFA, etc.), and it's disconcerting to users when private content shows up (which happens when they are logged in to Figgy).

We should show a clear visual cue that the item is being displayed because they are logged in, so users don't worry that private content is accidentally being made public. This could be a banner at the top or bottom of the viewer, or it could be a colorful border, or different background color, etc. But it would be good to have a clear visual indicator that the item is private/campus-only/etc. and not public.

**Comment by kelea99** [comment]
@escowles , I have a ghost of a memory from the great  PULFAlight wireframe demos @sdellis presented. They had a color coded content access visual.  it would be nice to try to standardize at least the colors for something like that for all of our applications, perhaps?

**Comment by escowles** [comment]
That's a good connection to make @kelea99 — using a standard set of colors to make it clear what the access status is would be good to reinforce things consistently across apps.
