### ISSUE TITLE
CDL::EligibleItemService should not error when Voyager is down.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4252]
## Backtrace

    line 12 of [PROJECT_ROOT]/app/resources/cdl/eligible_item_service.rb: block in item_ids
    line 11 of [PROJECT_ROOT]/app/resources/cdl/eligible_item_service.rb: each
    line 11 of [PROJECT_ROOT]/app/resources/cdl/eligible_item_service.rb: flat_map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/66931818)

**Comment by christinach** [comment]
eligible_item_service.rb 12 block in item_ids(...)

10         response = Faraday.new(url: bibdata_base).get("bibliographic/#{source_metadata_identifier}/items")
11         items = JSON.parse(response.body).flat_map do |_location, holdings|
12           holdings.flat_map do |holding|
13             holding["items"]
14           end

This is happening when voyager is down at am. The service cannot retrieve items.
