### ISSUE TITLE
HoldMailer email bug

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4268]
[Figgy/production] ActionView::Template::Error: undefined method `expiration_time' for nil:NilClass

## Backtrace

    line 6 of [PROJECT_ROOT]/app/views/cdl/hold_mailer/_header.html.erb: _app_views_cdl_hold_mailer__header_html_erb__1124463094637417776_69983843026560
    line 3 of [PROJECT_ROOT]/app/views/cdl/hold_mailer/hold_activated.html.erb: _app_views_cdl_hold_mailer_hold_activated_html_erb___3660175166905008685_69983843005560
    line 9 of [PROJECT_ROOT]/app/resources/cdl/hold_mailer.rb: hold_activated

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/67556652)

**Comment by hackmastera** [comment]
Oh, so there are actually 2 errors here that are likely interacting.

The mailer template is trying to pull `Wayfinder.for(@resource).resource_charge_list.hold_for(netid: @user.uid).expiration_time.in_time_zone("America/New_York")`. Sometimes the `hold_for` comes back nil and sometimes `expiration_time` comes back nil.

Perhaps there's an error causing the `expiration_time` to be nil and then after a number of retries the hold has expired and then the `hold_for` begins to return nil.

@tpendragon suggested it may be trying to send the email before recording the update with the expiration time.

**Comment by tpendragon** [comment]
As a first step I'd just change `deliver_later` to `deliver`.

**Comment by hackmastera** [comment]
sure i can do that real quick.
