### ISSUE TITLE
validate method for EphemeraFolder too aggressive?

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4276]
when executing
```sh
COLL=c9373093-1b5c-4bd1-b79b-013dae80f4a6  APPEND_COLL=e9709523-ec23-4eb0-9dd3-002746b91d13 bundle exec rake bulk:append_coll
```
The following lines appear to be logged for every folder in the GNIB collection and the folders are not updated with the new collection information.

``` sh
I, [2020-09-29T14:16:16.958525 #11773]  INFO -- : Updating attributes for EphemeraFolder: 705354e4-a2b9-451b-99f5-563d81ab8564
W, [2020-09-29T14:16:16.972349 #11773]  WARN -- :   Failed validation: {:barcode=>["can't be blank"], :folder_number=>["can't be blank"], :language=>["can't be blank"]}
```
See     https://github.com/pulibrary/figgy/blob/3fce63041bb7bcb1164770580264097c0547426e/app/services/bulk_edit_service.rb#L9

**Comment by tpendragon** [comment]
You can add `skip_validation: true` to the attributes in the rake task if you want it to not process validations.

**Comment by cwulfman** [comment]
I've tried that and it doesn't work.  Would you mind showing how that should be done?
