### ISSUE TITLE
Default state for migrated EphemeraFolders should be "needs_qa"

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#429]
I'm seeing an error editing some ephemera folders (but not others).  One example is: https://figgy.princeton.edu/concern/ephemera_folders/2da396fe-527f-431c-9786-0c919adeebd6 — when I try to save an edit to that folder, I get no error message, but the edit form is displayed (and some fields like Language are displayed as IDs instead of the select menus being displayed)

**Comment by escowles** [comment]
Two things that might be relevant: 
1. I think this happens on all folders without content
2. I'm editing as a non-admin user to test permissions

**Comment by tpendragon** [comment]
That folder you linked to is giving me a 404.

**Comment by escowles** [comment]
I think it's removed from Solr, but still in Postgres: because the edit form still works: https://figgy.princeton.edu/concern/ephemera_folders/2da396fe-527f-431c-9786-0c919adeebd6/edit

**Comment by tpendragon** [comment]
Ha.

**Comment by tpendragon** [comment]
This seems like a folder validation is failing.

**Comment by escowles** [comment]
This was an error in migrating the state — I'll rename this issue to reflect that.
