### ISSUE TITLE
Handle CanCan::AccessDenied

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#430]

**Comment by escowles** [comment]
Show a flash message instead of a 500 error

**Comment by hackmastera** [comment]
Operating on the assumption that we want the flash message on a log-in page if the user is not logged in, and on the front page for new/update, on the resource page for edit/create/destroy.

**Comment by tpendragon** [comment]
If they don't have permission I think we should just universally shunt them off to the root page and display a flash message there. If they're not logged in, I think it should try to log them in.

**Comment by hackmastera** [comment]
Redirecting to the login page doesn't accommodate a flash message.

**Comment by hackmastera** [comment]
`:manifest` and ':structure` actions will also be redirected after this change; please let me know if they need to be handled differently.
