### ISSUE TITLE
ingesting ephemera: hard-coded vocab label breaks production system

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4304]
https://github.com/pulibrary/figgy/blob/a3d741e794f25cfe3a0b6d58520005cadd994633/app/services/ingest_ephemera_csv.rb#L122

In the production environment, the vocabulary label is "LAE Geographic Areas".  This seems like a hack; there should be a way to find out what vocabularies are being used by a project and referring to them.

**Comment by tpendragon** [comment]
@cwulfman Can we close this?
