### ISSUE TITLE
[Figgy/production] Net::SMTPFatalError: 553 5.1.3 <kimberlyleaman@gmail.com@princeton.edu, rmunoz@princeton.edu>... Invalid route address

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4336]
## Backtrace

    line 14 of [PROJECT_ROOT]/lib/tasks/figgy.rake: block (3 levels) in <main>
    line 13 of [PROJECT_ROOT]/lib/tasks/figgy.rake: each
    line 13 of [PROJECT_ROOT]/lib/tasks/figgy.rake: block (2 levels) in <main>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/70128173)

**Comment by tpendragon** [comment]
@kelea99 had a GMail user as an owner of a collection and the email was added wrong for that user before we fixed that. I went in and fixed it manually.

**Comment by hackartisan** [comment]
Do we need to check to make sure there aren't any more waiting to fail?

**Comment by tpendragon** [comment]
No, I already took care of it before I closed this.
