### ISSUE TITLE
Google File Picker showing a new login for some users, and eventually errors

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4338]
Sherry Zhang is seeing this, and it looks like this:

![Screen Shot 2020-12-03 at 10 20 05 AM](https://user-images.githubusercontent.com/2806645/101071286-3a335d80-3551-11eb-8e19-2aa44897feed.png)

When she clicks the button it loads a new window, which closes, and she gets the sign in button again. If she tries yet again, she gets an error message in the google popup. The error is "The server cannot process the request because it is malformed. It should not be retried. That’s all we know."

**Comment by tpendragon** [comment]
Alexis is suddenly having the same problem.

**Comment by jrgriffiniii** [comment]
I may not be the best to try and reproduce this (apologies, this has worked for me through multiple iterations of testing), but I could not reproduce this error.
