### ISSUE TITLE
I would like to batch change "user download" field from "public" to "none" for all items in " Colección Archivo Fotográfico de la Protesta en Chile 2019" ephemera project

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4347]
Reasoning: the photographers who have supplied the photos would not like their images (that have been marked in copyright) downloadable. Fernando is going to unpublish the dpul site until we get the image download option set to none. @tpendragon , thank you so much!

**Comment by kelea99** [comment]
Ephemera project link: https://figgy.princeton.edu/catalog/126bb7fd-afbe-4133-ac20-9deae5109e5a

**Comment by tpendragon** [comment]
All done.
