### ISSUE TITLE
Improve error handling for CDL::EligibleItemService.item_ids

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4351]
## Backtrace

    line 12 of [PROJECT_ROOT]/app/resources/cdl/eligible_item_service.rb: block in item_ids
    line 11 of [PROJECT_ROOT]/app/resources/cdl/eligible_item_service.rb: each
    line 11 of [PROJECT_ROOT]/app/resources/cdl/eligible_item_service.rb: flat_map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/67200786)

**Comment by tpendragon** [comment]
I think Figgy just needs deployed: https://github.com/pulibrary/figgy/pull/4335

**Comment by jrgriffiniii** [comment]
I apologize @tpendragon, I will close this.
