### ISSUE TITLE
Increase the error handling for TikaFileCharacterizationService#file_characterization_attributes

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4353]
## Backtrace

    line 35 of [PROJECT_ROOT]/app/characterization_services/tika_file_characterization_service.rb: file_characterization_attributes
    line 22 of [PROJECT_ROOT]/app/characterization_services/tika_file_characterization_service.rb: characterize
    line 22 of [PROJECT_ROOT]/app/characterization_services/default_characterization_service.rb: characterize

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/53418725)

**Comment by jrgriffiniii** [comment]
Errors such as `NoMethodError: undefined method `[]' for nil:NilClass` are currently not handled, which Honeybadger traces to the following:

```ruby
tika_file_characterization_service.rb  35 file_characterization_attributes(...)
[PROJECT_ROOT]/app/characterization_services/tika_file_characterization_service.rb:35:in `file_characterization_attributes'
33     result = JSON.parse(json_output).last
34     {
35       width: result["tiff:ImageWidth"],
36       height: result["tiff:ImageLength"],
37       mime_type: result["Content-Type"],
```

Please see https://app.honeybadger.io/projects/53391/faults/53418725#notice-trace for reference.

**Comment by hackartisan** [comment]
How should this error be handled?

**Comment by hackartisan** [comment]
We get this error when a pdf runs through tika. In one case this was because the mime_type was set wrong (see https://app.honeybadger.io/projects/53391/faults/53418725#notice-comments)
