### ISSUE TITLE
CDL::BulkHoldProcessor.change_set_persister raises RuntimeError: Unable to find unregistered adapter `indexing_persister'

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4354]
## Backtrace

    line 13 of [PROJECT_ROOT]/app/resources/cdl/bulk_hold_processor.rb: change_set_persister
    line 6 of [PROJECT_ROOT]/app/resources/cdl/bulk_hold_processor.rb: process!
    line 5 of [PROJECT_ROOT]/lib/tasks/cdl.rake: block (2 levels) in <main>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/67640376)

**Comment by jrgriffiniii** [comment]
I'm not certain how frequently this occurs, but it should be noted that this is a possible bug. The backtrace provided by Honeybadger is:

```ruby
bulk_hold_processor.rb  13 change_set_persister(...)
[PROJECT_ROOT]/app/resources/cdl/bulk_hold_processor.rb:13:in `change_set_persister'
11     def self.change_set_persister
12       ::ChangeSetPersister.new(
13         metadata_adapter: Valkyrie::MetadataAdapter.find(:indexing_persister),
14         storage_adapter: Valkyrie.config.storage_adapter
15       )
```

(Please see https://app.honeybadger.io/projects/53391/faults/67640376#notice-trace)

**Comment by tpendragon** [comment]
This happens when postgres is down.
