### ISSUE TITLE
I would like to make a Ephemera project copy of SAE Project Box 04 so that I may give external contributors access to only that box. 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4355]
This is something we have done for DK agencies, India in the past. may we do this for [box four]( https://figgy.princeton.edu/catalog/parent/f99af4de-fed4-4baa-82b1-6e857b230306/bcfeb10b-0ad4-43d8-a369-11fbca1e0062)? Digitization of the materials is completed, but I thought we could hold off on ingest of the images until after the metadata is copied over into its own project. is this okay?

**Comment by kelea99** [comment]
hi, @kelynch and @cwulfman ! can we get this done for Ellen sometime this week? I need to touch base with her :)

**Comment by tpendragon** [comment]
@kelea99 

Can you give a description of the goal here? I realize we've done this before, but I wasn't really involved so I want to make sure I do the right thing. I assume the deal is that you need a new project with the same configuration as the other project, then move that box to the new project, then you'll assign external contributors to it so they can enter metadata off the digital images? Then when they're done we move it back?

**Comment by kelea99** [comment]
This is all correct, @tpendragon ! yes, that is exactly why.  this is for the folks in India who are working on the metadata for the digitzed items. I am happy to set up the project. standby

**Comment by kelea99** [comment]
Confirmed with Ellen. We can and should continue using the [DK - SAE ephpmera project ](https://figgy.princeton.edu/catalog/f09fc91d-7a9b-47b5-afff-ce7db76b4e92)  .  the stuff from before is still there. will we be able to copy back just the most recent box when it is complete? or is this an all or nothing transfer back to the SAE collection when metadata is complete for the entire project?

**Comment by tpendragon** [comment]
We can do one box at a time. Do you want the box copied or moved?

**Comment by kelea99** [comment]
what is easiest for you? I would assume moved? since we have to move the entirety back over once complete, anyway? What do you think?

**Comment by tpendragon** [comment]
Yes, unless you have a reason for duplicates moving is easier.

**Comment by kelea99** [comment]
No reason for duplicates. Yes, moving the box over to the DK project and we can move it back to SAE upon completion.  Thank you!!

**Comment by tpendragon** [comment]
@kelea99 I think it's done, can you confirm?

**Comment by kelea99** [comment]
Looks good to me!! Just informed Ellen. Thank you!!!

**Comment by tpendragon** [comment]
Sure! Glad it worked. :)

**Comment by kelea99** [comment]
Great and thank you!!!
