### ISSUE TITLE
Vamdermaelen atlas requires additional work

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4356]
This list has been copied from https://github.com/pulibrary/figgy/issues/1600, which pertains to PUDL migration.

- Images need to be converted to individual scanned map children while maintaining structure.
- Many of the pages in the Atlas were cataloged separately in Voyager have already been ingested into Figgy as individual sheets. These need to be moved into the atlas or deleted.
  - https://figgy.princeton.edu/catalog/79e865c5-1abc-4978-a10b-6528b75066bd
  - https://catalog.princeton.edu/catalog/5740218
- Bound boxes need to assigned to images not cataloged individually.

**Comment by tpendragon** [comment]
@eliotjordan @cwulfman Is this still open?
