### ISSUE TITLE
MVW CDL items are not viewable to some who have checked them out in the online catalog

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4357]
We (Colleen Burlingham, @kelynch , and @kelea99 ) were not able to replicate this error that Colleen and @kelea99 witnessed with Jennifer Hunter this morning, who was not able to access any reels in the viewer for Trentonian, CDL, in the online catalog.  What we did:
Colleen:
1. we destroyed colleen's role in figgy.
2. Colleen checked to ensure her cache/history was clear in Firefox
3. Colleen navigated to the [Trentonian in the online catalog](https://catalog.princeton.edu/catalog/9670839)
4. She clicked on "Princeton Users: Log In to Digitally Check Out" 
5. This time she was directed to the same screen that Jennifer Hunter saw. This is different from those who have figgy roles, which takes one directly to the item/viewer.
6. The viewer appeared and we could see all reels available in the trentonian, along with the checkout button and timer in the upper left

We tried this same thing with Edge browser. Colleen was able to access the item again.

Jen Hunter, who does not have any figgy role assigned to her, could not access the content. she used Chrome:
1. Jen Navigated to the [Trentonian in the online catalog](https://catalog.princeton.edu/catalog/9670839)
2. She clicked on "Princeton Users: Log In to Digitally Check Out" 
3. she was directed to the same screen that Colleen saw when we removed her figgy role. This is different from those who have figgy roles, which takes one directly to the item/viewer.
4.  A black/blankviewer appeared, with nothing inside it, Jen could see the checkout button and timer in the upper left, which was counting down.

**Comment by tpendragon** [comment]
My guess is ability.rb isn't giving permission to child resources if the parent is checked out via CDL. I'd probably make it so getting to the cdl eligibility checker for a child resource returns the checker for the parent. I'm guessing it works for some people because that person is on VPN or something and the volumes are set to on campus only or something.

**Comment by kelynch** [comment]
Thanks @kelea99 and @tpendragon!  It's also worth noting that Colleen and I both tried to replicate the error as non-admin Figgy users, just authenticating for CDL without any role associated with our net IDs.

**Comment by hackartisan** [comment]
@kelynch and I just looked at this with Jenn and of course it is now working for her.

This feels like a caching issue somewhere, although I'm not sure exactly where.

**Comment by kelea99** [comment]
update:  I got another “This is not working for me ” email regarding the MVW that is the Trentonian. I tried via CDL myself and got a big blank screen where the viewer should be (see screenshot, and also has the time). it took close to 5 minutes to load and become visible to me. I'm not sure if the patrons are waiting that long? This is the first time something like this has happened for me for this item. 
![Screen Shot 2020-12-22 at 5 39 04 PM](https://user-images.githubusercontent.com/45043014/102948944-1189ee00-4495-11eb-8204-1931106e835c.png)

**Comment by kelea99** [comment]
Another user case issue with [Le Monde](https://catalog.princeton.edu/catalog/567623). The requester cannot access this CDL item in the online catalog.  @kelynch and I were informed by Colleen B., who heard from the patron this morning. They just checked and were not able to access (it is the first time they made an attempt to access). @escowles , this is not an immediate need, but its the second instance of an MVW item not working in CDL.
