### ISSUE TITLE
Empty tif in "Virtue and Vice: or the History of Charles Careful, and Harry Heedless"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4358]
[Figgy/production] Vips::Error: VipsForeignLoad: "/opt/repository/files/4b/8a/d2/4b8ad2f1e782424c85c1df82378eb3c9/00000001.tif" is not a known file format

When I download this file and try to open it I get an error saying it is empty. The object is https://figgy.princeton.edu/catalog/59a63df6-2f5d-4184-aa7c-ae1da54417ae. I'm emailing the depositor to let them know the upload failed and see if they can delete the resource and try again. I'm going to delete the job from sidekiq in the meantime.

## Backtrace

    line 108 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: image_from_file
    line 98 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: vips_image
    line 82 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: run_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/67132649)

**Comment by hackartisan** [comment]
This was successfully reingested.
