### ISSUE TITLE
Please add Mendel, Mudd, and Marquand shares to file upload options in figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4364]
we need these new ingest points from the scratch share added to figgy's dropdown of options before we contact branches to explain use.  thank you! 

smb://lib-dps-server.princeton.edu/BRANCH SITE NAME
(Mudd, Mendel, Marquand)

**Comment by kelea99** [comment]
Do you think we can get this up and running for next week? @roelmoon and I would like to get folks (especially from mudd) set up to ingest to figgy from the share.

**Comment by tpendragon** [comment]
I sent a message to Phil to get some auth info for these mounts, then it should be reasonably quick to set up.

**Comment by kelea99** [comment]
Thank you!!  I have the user names and passwords if it helps?

K. E. Leaman
Information Technology Project Manager
Princeton University  Library
Princeton, NJ 08544
T 609.258.8878
https://library.princeton.edu/digital-collections

Written from cell phone. Please excuse brevity
________________________________

**Comment by tpendragon** [comment]
I'm not sure if the mounts should be the same auth info as the mount info for users. We'll get it worked out soon. :)

**Comment by tpendragon** [comment]
@kelea99 This should be done. I'm gonna close this, reopen if there's a problem?

**Comment by kelea99** [comment]
Great! will do. We are still having some server issues last i checked, but will test with @roelmoon  either today or tomorrow to ensure it works.  Thanks!
