### ISSUE TITLE
Further increase the ulimit for the NGINX plus configuration

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4367]
## Backtrace

    line 94 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save_all
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38866714)

**Comment by jrgriffiniii** [comment]
Please see https://app.honeybadger.io/faults/38866714/comments/14630950 for context.

**Comment by tpendragon** [comment]
Solr was down. We'd see a file handler error otherwise.
