### ISSUE TITLE
Ingest second spreadsheet for Dissidents SAE ephemera for Ellen

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4382]
Second spreadsheet (created from @cwulfman 's CSV):   https://docs.google.com/spreadsheets/d/1qVFJ3qrgnG3H_wiQpkbrYtEiZ0mUjIXWSN6nRNbCl9E/edit?ts=5fcb842b#gid=1707963384

**Comment by cwulfman** [comment]
This workbook has multiple spreadsheets (tabs) in it.  Those with checkmarks in the list below have been ingested.

- [ ] sae_ephemera_left_wing
- [ ] SAE_AILS_Tissa Balasuriya
- [ ] SAE_AILS_WERC
- [ ] SAE_AILS_Yohan Devadanda
- [ ] SAE_AILS_Michael Rodrigo
- [ ] SAE_AILS_Paul Caspersz
