### ISSUE TITLE
Reingest Moscow Mayoral Ephemera Project

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4383]
Please include dummy barcode and folder numbers
Please include language Russian
Please add collection tag: Princeton Slavic Collections

**Comment by cwulfman** [comment]
Using https://docs.google.com/spreadsheets/d/1asw8eyuy_ZgZw7ROySXwG6tNKG8EVyxmUalnaHH0L7E/edit?usp=sharing

Procedure: 
bundle exec rake csv:ingest_ephemera

bundle exec rake bulk:add_ephemera_to_collection
