### ISSUE TITLE
Metadata Search-Within

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4384]
Use case: Grounds and Buildings photographs. We have decided to ingest these historical photographs as MVWs, grouping all photos of a building into one object, but keeping the metadata for each individual photograph (e.g., date, photographer) attached to the volumes.

The old ARKs used to point to the individual photos in PUDL, but now there's no easy way to find the individual photo that an ARK refers to. Could we turn on search-within with just the metadata of the volumes? That would at least allow you to search for the ARK and find the object that was referenced.

**Comment by tpendragon** [comment]
...What? Sorry, I'm confused. So you want to search for the ARK of a child record in Figgy and have the parent record return?

**Comment by escowles** [comment]
@tpendragon This is one of a handful of SC collections that have item-level metadata, including ARKs, in PUDL because that's the way they were ingested in PUDL. But there aren't components or item-level metadata for each photo in the finding aid.

So the compromise for getting these migrated to Figgy is to create a MVW linked to each finding aid component (representing all photos of a building), with child volumes for each photo, which allows us to:

1. Have a single object linked to the finding aid component, and embed the viewer in Pulfa/Pulfalight
2. Attach the item-level metadata to the child volumes (where it's accessible in the metadata drawer in the viewer)

The main outstanding issue is a navigation problem. Each photo has an ARK that currently points at PUDL. We can update those ARKs to go to the finding aid, but there are dozens or hundreds of photos for some buildings. But if you have a citation including the ARK, how would you know which photo it was referring to? We'd like some way for a user who lands at the finding aid component to navigate to the right photo.

**Comment by tpendragon** [comment]
Oh. So a link which navigates to the page in pulfa and the viewer loads the right item? There's a IIIF working group for this, but also an existing solution in UV I think. Would take some fiddling.

**Comment by kelea99** [comment]
closing this and wishlisting
