### ISSUE TITLE
EAL item will not keep the reorganized page order I create in order manager, as well as in structure manager after saving.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4385]
Item: https://figgy.princeton.edu/catalog/fbdd4cb6-16c2-41ab-a12c-a27226fc7add
Issue posted by Tom Ventimiglia and error replicated by @escowles and myself.
 
Problem: Tom could not change the order of pages in the order manager for the above item.  It allows him to reorder the pages, but after he saves and exits the order is back to the original (17 pages to be reordered are at the end of the thumbnails: pages 638-642; 687-698).
@escowles was able to move the out of order pages in order manager but did not see any error in the logs, etc. When he reloaded, they were back to as they were before. After opening a private window and doing the same, he saw the same thing. same when switching to the thumbnail view in the viewer.
@kelea99 tried reordering pages 638-642 in structure manager and saving.  still would not hold the reoranized pages.

@kelea99 tried navigating to one of the chapters (the one that starts before the chapter starting on page 643). and it stalled and did not navigate. rotating square of sadness (see screenshot)

@tpendragon  suspects some hidden validation error

![Screen Shot 2021-01-20 at 1 35 59 PM](https://user-images.githubusercontent.com/45043014/105220761-299d6d80-5b26-11eb-9afb-39003c57b9a5.png)

**Comment by kelea99** [comment]
Tom thinks he remembers something like this happening with another item before.  he doesn't now the details of the solution, but there was some extraneous object in the item (invisible to him) that was keeping the changes from holding.  Could that be the case here?

**Comment by kelea99** [comment]
![Oct_19_correspondence](https://user-images.githubusercontent.com/45043014/105221719-8188a400-5b27-11eb-859c-debd0d98784d.png)

**Comment by tpendragon** [comment]
There was a deleted member in the member IDs again. We'll have to fix this validation eventually to make sure the mismatch isn't because of hidden members.
