### ISSUE TITLE
I would like support added for ingesting mp3s directly into Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4400]
We have use cases for this need. the Khenpo Sodargye lectures being one of them (see "audio_tibet" on the PUDL share of Isilon.  I also found another open ticket ([#3070](https://github.com/pulibrary/figgy/issues/3070)) regarding download links for MP3s, but there was a UV bug that opened the ticket again. has this been solved?

**Comment by escowles** [comment]
The alternative would be converting the MP3 source files to WAV for ingest. But since we added support for ingesting JPEG and PNG, supporting MP3 seems more consistent.
