### ISSUE TITLE
Empty values in controlled vocabularies

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4404]
These were causing 500 errors on the ephemera folder edit page

HB notification: https://app.honeybadger.io/projects/53391/faults/76092480

From figgy console:

[#<EphemeraTerm id=#<Valkyrie::ID:0x000055ffd4f0af80 @id="0d72d21a-2959-403e-80a7-27f5f0ba4ba4"> internal_resource="EphemeraTerm" created_at="2021-02-10T19:04:11.356Z" updated_at="2021-02-10T19:04:11.356Z" new_record=false read_groups=[] read_users=[] edit_users=[] edit_groups=[] label=nil uri=nil code=nil tgm_label=nil lcsh_label=nil member_of_vocabulary_id=[#<Valkyrie::ID:0x000055ffd4f0b200 @id="e7771cb0-e5a9-4ef7-b7ea-8e2f9b103302">]>, #<EphemeraTerm id=#<Valkyrie::ID:0x000055ffd4eeec68 @id="7f18ecf9-85cc-446e-aceb-c59baf0e2a6b"> internal_resource="EphemeraTerm" created_at="2021-02-10T18:43:33.976Z" updated_at="2021-02-10T18:43:33.976Z" new_record=false read_groups=[] read_users=[] edit_users=[] edit_groups=[] label=nil uri=nil code=nil tgm_label=nil lcsh_label=nil member_of_vocabulary_id=[#<Valkyrie::ID:0x000055ffd4eef1e0 @id="e7771cb0-e5a9-4ef7-b7ea-8e2f9b103302">]>]

**Comment by hackartisan** [comment]
From Gabrielle:

Now that you mention. The problem started when "Abandoned children" popped up when I tried to pick a subject. Since "Abandoned children" isn't a a controlled vocabulary, I couldn't uncheck it. And  that's when the error messages started popping up...

**Comment by tpendragon** [comment]
I deleted all the empty ones, this was the result of a failed bulk ingest of materials by a developer. Deleting them looked like this:

```ruby
csp = ScannedResourcesController.change_set_persister
terms = csp.query_service.find_all_of_model(model: EphemeraTerm).select{|x| x.label.blank?}
terms.each do |term|
  change_set = ChangeSet.for(term)
  csp.delete(change_set: change_set)
end
```
