### ISSUE TITLE
Character encoding failure on images generated from PDF 

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4407]
See https://figgy.princeton.edu/catalog/b7be4b52-3736-4b49-8814-cbc715dfbbfb. In the Summer 2010 issue, in image 4 (p. iv), all the Chinese characters have been converted to “tofu” (white boxes). This doesn’t happen elsewhere in the document.  And the source PDF is fine (I can provide if needed).

I’ve noticed a few other oddities.  For example, on p. 37 of the same issue, the apostrophe in “Plato’s” is converted to an odd-looking fullwidth apostrophe, though it does not appear that way in the source PDF.

Reported by @tventimi

**Comment by tventimi** [comment]
Joshua Seufert suggested that we try converting the PDFs to PDF/A format before ingesting, and this solved the problem!  I replaced the problematic files so the link cited above no longer shows the issue.  We don't have any other issues with this item, but if you still want to investigate the original issue, please let me know and I can prove the original unconverted file.

**Comment by hackartisan** [comment]
That's great! I'll go ahead and close this since you found an acceptable workaround.
