### ISSUE TITLE
Metadata nodes not staying in sync with preservation storage.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4415]
Error: [Figgy/staging] Notice: Cloud fixity failure on object with resource id: c94e6622-a9ee-4400-9c70-efc2f72a0cee, child property: metadata_node, child id: e47a34c3-487a-4357-9b4c-5540ae28c15b

## Backtrace

    line 12 of [PROJECT_ROOT]/app/jobs/update_fixity_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/64816078)

We know for sure this is happening, but don't have a current example. We'd have to research the architecture and search for race conditions.

This might be resolved when we do #2431, as right now it's updating FileSet metadata without going through a ChangeSetPersister.

This ticket won't be closable until we re-preserve everything to fix the checksums that are in the database, and the files in cloud storage, which is #5556

## Fix Proposal

Find all the cloud fixity metadata failures and run the fixer from #5736 on them.

**Comment by tpendragon** [comment]
The auto fixer in #5736 also might be able to clear this up.

**Comment by eliotjordan** [comment]
Script to get failed cloud fixity events and queue up fix jobs:

```
query_service = ChangeSetPersister.default.query_service
events = query_service.custom_queries.find_by_property(property: :status, value: "FAILURE", model: Event)
cloud_failures = events.select { |e| e.type == "cloud_fixity" && e.current == true }

cloud_failures.each { |e| RepairCloudFixityJob.perform_later(event_id: e.id.to_s) }

**Comment by eliotjordan** [comment]
Cleaned these up and resolved. Some notes:

1. Some of the events referenced preservation objects and resources that no longer exist
2. Some of the events were fixed using RepairCloudFixityJob
3. The rest were fixed by forcing re-preservation

In total, there were 150 current cloud fixity failure events
