### ISSUE TITLE
BrowseEverything ingest shouldn't fire if no files are selected.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4416]
## Error

[Figgy/production] NoMethodError: undefined method `container_ids' for nil:NilClass

## Backtrace

    line 120 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: upload_files
    line 103 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: block in new_pending_uploads
    line 102 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/63756895)

**Comment by hackartisan** [comment]
Same error?

https://app.honeybadger.io/projects/53391/faults/80858477

**Comment by sdellis** [comment]
Another similar error: 
https://app.honeybadger.io/projects/53391/faults/82303783

**Comment by hackartisan** [comment]
duplicate of #4499
