### ISSUE TITLE
Volumes with collection membership show up as separate resources in DPUL

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4423]
If I create a MVW with both the MVW and the individual volumes both being members of a collection, the volumes will show up as independent resources in DPUL. We have seen problems with object counts not matching between Figgy and DPUL, and I wonder if this is a/the cause.

**Comment by tpendragon** [comment]
Why are volumes also members of a collection?

**Comment by escowles** [comment]
@tpendragon I'm not sure if they were ingested as separate objects and then combined into a MVW, or if the ingest process added the collection membership at both levels. I edited the objects I was working with to remove the volume-level collection membership and DPUL updated as expected.

Since it's no longer possible to do this using the UI, this is probably mostly a note for future debugging. It's possible there are other collections that predate the forms change, so maybe this ticket is really "run a script to identify any volumes with collection membership and remove it"
