### ISSUE TITLE
Two Titles are showing for the lapidus collection in figgy and in DPUL,  but not in online catalog

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4427]
Example of this:
Online catalog: https://catalog.princeton.edu/catalog/3662763  (see that the title without article is in the viewer, though, as one would expect)
Figgy: two titles being imported in with bib id:  https://figgy.princeton.edu/catalog/d6da09aa-6531-4baf-925e-8646fa1a6f57

DPUL: (see entry 1): https://dpul.princeton.edu/lapidus/browse/browse-the-collection

Im not sure if this is a MARC (the way in which it was cataloged), or if something funky is happening when the metadata is being pulled in to figgy?

**Comment by tpendragon** [comment]
This was an old bug in Figgy, I just re-fetched the metadata via the checkbox for this item and it was fixed. Is it doing this for a bunch of items?

**Comment by kelea99** [comment]
yes. it is doing it for almost all of them @tpendragon

**Comment by kelea99** [comment]
Fixed!!! Closing ticket, but please feel free to reopen if needed.

**Comment by kelea99** [comment]
alas. only one is fixed

**Comment by tpendragon** [comment]
@kelea99 Yeah if this is across the whole collection we'll have to refresh the metadata for the whole collection.

**Comment by kelea99** [comment]
yea, its across the whole collection

**Comment by tpendragon** [comment]
I kicked off a refresh of all the metadata across lapidus, it'll probably be done later tonight.

**Comment by kelea99** [comment]
Thanks! Ill let Steve know.
