### ISSUE TITLE
As a figgy ephemera project owner, I would like to download a CSV of all folders in my project, including those that are boxless

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4431]
I'm looking at the SAE ephemera project and notice that those items that are not in boxes are not showing up when I try to download an ephemera report.  I would like the report to include all folders in the project, in boxes and those that have no box assigned.

**Comment by cwulfman** [comment]
I think you can fix this by changing reports_controller.rb#8 to
``` ruby
@resources = @ephemera_project.boxes.map(&:folders).flatten + @ephemera_project.folders
```
