### ISSUE TITLE
Stakeholder wants Geniza fragments consolidated into multivolume works

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4433]
Each fragment is identified by a shelf mark, which can usually be parsed.  Stakeholder would like objects with a common document identifier to be gathered into multivolume works so they can be discovered and browsed in that form in DPUL.

Strategy: begin with the NS library/sub-collection (~7,000 items).  Collect objects with a common document id; create a new MVW. Make all the objects members of that MVW.  Remove them from any other collection to which they belong.

**Comment by kelea99** [comment]
@cwulfman @escowles closing this

**Comment by kelea99** [comment]
REopening. the NS/MS is not complete
