### ISSUE TITLE
Should we change grayscale pdf download selection to color download selection on items in figgy?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4435]
Usecase: Emma asked why an Middle east Mss had only grayscale download option in the viewer. I remember a conversation that grayscale PDF was the default setting in figgy for a while before it was changed to color. We think it would be useful to change the PDF setting to Color for at least some collections in figgy (like manuscripts).  Has this been discussed before?

**Comment by tpendragon** [comment]
Some things are set to grayscale because the PDF generates faster and is smaller. Is this a request to bulk change some to color?

**Comment by kelea99** [comment]
@tpendragon yes. some (like illuminated manuscripts) may be identified as needing color for the lot of a specific figgy collection. if that became a request, would it be a large on for DRDS?
