### ISSUE TITLE
Serve audio reserves through OARSC

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4444]
We have a use case for an audio collection (James Baldwin Interviews) that is currently set to private, ready to be changed to Reading Room in Figgy that should be made available via OARSC for the Virtual Reading Room.

**Comment by tpendragon** [comment]
It shouldn't be too hard to add restricted users to archival media collections, but as a workaround we could also just create a regular collection with all these items in it and set restricted users there.

**Comment by tpendragon** [comment]
Or if they're done ingesting bags to that collection we could just convert it to a regular collection. AMCs are just an ingest pipeline.

**Comment by kelynch** [comment]
Thanks Trey, this makes sense.  I'll see if we're done with ingesting to that collection.

**Comment by kelynch** [comment]
Confirmed this works after #4447.  Closing.
