### ISSUE TITLE
Figgy throwing error when trying to navigate to sub-section of a controlled LAE subject vocaubulary for Ephemera

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4448]
![Screen Shot 2021-03-23 at 6 39 59 PM](https://user-images.githubusercontent.com/45043014/112228233-5db90b80-8c07-11eb-90d5-b1350e661679.png)

what i did:
1. i clicked on "Manage ephemera vocabularies" from the + dropdown.
2. I clicked on "LAE Subjects"
3. clicked on "History"
error pops up. (see screenshot above)

**Comment by kelea99** [comment]
update: it is not all the subjects. "History" throws up the error.  others do not.

**Comment by tpendragon** [comment]
This turned out to be the same as https://github.com/pulibrary/figgy/issues/4404. I cleaned it up and it seems fine now - maybe @cwulfman has some info on a bulk ingest or something that might have created empty terms?

**Comment by cwulfman** [comment]
@tpendragon is right: an ingest of some ephemera introduced some mal-formed subjects. Shouldn't happen again for this batch. @tpendragon, could you detail what you did to clean it up?

**Comment by tpendragon** [comment]
I ran the same code as in #4404

```ruby
csp = ScannedResourcesController.change_set_persister
terms = csp.query_service.find_all_of_model(model: EphemeraTerm).select{|x| x.label.blank?}
terms.each do |term|
  change_set = ChangeSet.for(term)
  csp.delete(change_set: change_set)
end
```
