### ISSUE TITLE
Add Phoenix Application to generate collection manifests

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4452]
Goal:

* Speed up collection manifest generation.
* Ship an Elixir application.
  * Deployment note: https://hexdocs.pm/phoenix/releases.html#runtime-configuration

**Comment by hackartisan** [comment]
WIP branch is now called figx.
Next we should work on deploying.
https://github.com/pulibrary/princeton_ansible/pull/2398 makes that possible.

**Comment by tpendragon** [comment]
We've deployed it to staging, next step is add systemd to auto-start it in the background and figure out why one of the collections errored about description.
