### ISSUE TITLE
Make arks for SC Inventories materials link to the downloadable pdf

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4465]
https://figgy.princeton.edu/catalog/07e883c6-e81e-4800-bb6f-4fa6dfd30d9f

In the manifest, it is the sequences/rendering with format application/pdf.  Even better, download the Ark report for the collection and work from that.

**Comment by tpendragon** [comment]
@escowles @kelea99 is asking if this is taken care of.

**Comment by escowles** [comment]
I'm not sure — wasn't Vicki Principi adding the links to these items? Have we heard if they are using the PDF links?
