### ISSUE TITLE
Add option to render Figgy objects as links instead of as a UV viewer

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4469]
Use case: I have many PDF files that I would like to store in Figgy instead of Google Drive, websites, etc. But these are supplemental materials that were linked to, not scans of the item, so I would rather link to the PDF file in Figgy, not display the viewer to avoid confusing users who equate the viewer with the whole item.

Currently, storing the item in Figgy with the BibID as the source metadata identifier triggers displaying the viewer, so I'm ingesting as title-only and adding the ARK to the Bib record in an 856. However, this link goes to the Figgy show page, which we would rather not direct users to.

Ideally, I would enter the BibID as the source metadata identifier, enter a portion note to explain how the material was related to the item, and check a box saying the item should display as a link instead of the viewer. Then the ARK would direct people to download the original PDF instead of the show page.

**Comment by tpendragon** [comment]
@kelea99 said to close this.
