### ISSUE TITLE
Error when searching long title

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4470]
A title search for `स्वदेशी : बहुराष्ट्रीय कंपनियों के विकल्प के रूप में स्वदेशी उपभोक्ता वस्तुओं की सूची : स्वदेशी का प्रयोग, समृद्धि का आधार` results in an error.

datadog shows a log entry with error "upstream sent too big header" https://app.datadoghq.com/logs?cols=host%2Cservice%2C%40http.url_details.path%2C%40server&context_event=AQAAAXjQv44wGlMwlgAAAABBWGpRdjUyMUFBQjl6Y2VNLWpoNUxRQUk&event&from_ts=1618407098099&index=&live=true&messageDisplay=inline&query=vikalpa&stream_sort=desc&to_ts=1618410698099&viz=

Possibly we need to increase the nginx buffer size: https://ma.ttias.be/nginx-proxy-upstream-sent-big-header-reading-response-header-upstream/

**Comment by escowles** [comment]
Searching for a substantial chunk of the title (e.g., `स्वदेशी : बहुराष्ट्रीय कंपनियों के विकल्प के रूप में स्वदेशी उपभोक्ता वस्तुओं`) works, so it may be that the URL or headers being generated are too long when URL-escaping happens.
