### ISSUE TITLE
Provide an easy way to link to Figgy PDFs by ARK

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4472]
Currently, to link to either the PDF that Figgy generates, or the original PDF ingested into Figgy, requires going to copy the URL (and navigating the File Manager for the original PDF).

Related to #4469 , it would be good to be able to link to the PDF using the ARK, e.g., by appending "/pdf" to the end of the ARK url: `http://arks.princeton.edu/ark:/88436/xyz12345x/ark`. This would let us link to PDFs using ARKs.

**Comment by kelea99** [comment]
@escowles is this way forward approved/ready to be added to workflows?

**Comment by escowles** [comment]
@kelea99 Not yet — I've updated my PR to address Trey's review comments, but he hasn't re-reviewed that yet. But I think that's likely to happen today.
