### ISSUE TITLE
Handle possible 429 from bibdata during CDL check

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4475]
bibliographic/:bib_id/items might return a 429. We should probably display a "try again later" message.

**Comment by christinach** [comment]
Do we want this `try again later` to display in the viewer?

**Comment by tpendragon** [comment]
This is a hard ticket with a lot of moving parts. We should talk about it during check-in.

**Comment by tpendragon** [comment]
Right now Figgy won't display the viewer if it gets a 429, which is fine.
