### ISSUE TITLE
Automatic pagination for two up images not funtioning in figgy order manager

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4476]
I’m making a new ticket for this, but I’m positive we already have one. Anna Meerson also mentioned the need for automated  two up pagination for order manager (for the microfilm)

**Comment by tpendragon** [comment]
This is a feature already (it's the 'two-up' setting), but it does look like it's broken right now for some reason.

**Comment by sdellis** [comment]
@kelea99 Do we know if this ever worked or is this a new feature? Is the expected outcome that two consecutive images would get "Page 1-2" and "Page 3-4" as a labels, instead of "Page 1" and "Page 2"?

**Comment by tpendragon** [comment]
@sdellis This worked once upon a time. This is the purpose of the "two-up" dropdown.

**Comment by kelea99** [comment]
to confirm here as well: Yes, the expected outcome for the two up auto-pagination feature would be:
[LABEL] 1-2 OR 1/2 .  Thank you!

**Comment by sdellis** [comment]
Thanks for testing @kelea99 , I'm dropping your video here as validation: https://drive.google.com/file/d/1rkwA2JVEhh5q_jLgM7r3ak41KlN7YJj6/view?usp=sharing_eil_m&ts=6149fae0

I think the bracket feature works, but it only brackets the left or right and you have to select it afterwards. If this is not what's intended, let's open a new ticket.

**Comment by kelea99** [comment]
I know there are some instances (rare) that have all the pages bracketed, but it has only ever been for one up pagination of some special collections item(s) and the bracketing works fine there. I do not know of any use cases with two up bracketing for the entire volume/item.

**Comment by tpendragon** [comment]
@sdellis Is there another ticket to create so we can close this?

**Comment by kelea99** [comment]
@sdellis and @tpendragon I do not believe we would need brackets around the entirety of the two up numbering. until we have a use case,  I am closing this ticket.  If you would like: can make a separate one for the bracketing!

**Comment by sdellis** [comment]
@kelea99 and @tpendragon I would wait until we discover brackets on all pages are needed to make a ticket.
