### ISSUE TITLE
Remove voyager updater code

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4477]
New functionality is needed (see https://github.com/pulibrary/figgy/issues/4690) but it won't work the same way.

- [x] remove all the voyager_updater code
- [ ] remove the processed_event model

When removing the processed event model, use a migration like 
```
DELETE FROM orm_resources WHERE internal_resource = 'ProcessedEvent'
```

**Comment by tpendragon** [comment]
## Technical Reference

Rake task:
https://github.com/pulibrary/figgy/blob/335e0fdaaa6377e92969eff2c5f1e7288e2cf4ee/lib/tasks/figgy.rake#L18-L24

Event Stream Processing:

https://github.com/pulibrary/figgy/blob/335e0fdaaa6377e92969eff2c5f1e7288e2cf4ee/app/services/voyager_updater/event_stream.rb#L12-L23

Event:

https://github.com/pulibrary/figgy/blob/335e0fdaaa6377e92969eff2c5f1e7288e2cf4ee/app/services/voyager_updater/event.rb

Processing IDS:

https://github.com/pulibrary/figgy/blob/335e0fdaaa6377e92969eff2c5f1e7288e2cf4ee/app/services/voyager_updater/dump.rb#L12-L27

**Comment by hackartisan** [comment]
I'm making this into a ticket just about removing the old functionality. Use https://github.com/pulibrary/figgy/issues/4690 for implementing new functionality

**Comment by eliotjordan** [comment]
ProcessedEvent records removed from the staging and prod databases.
