### ISSUE TITLE
Bulk Collection tagging needed for "Julian Scott Photographs for the 11th Census C1412" Figgy Collection

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4480]
All 171 items in the [Julian Scott Photographs for the 11th Census C1412 Collection
](https://figgy.princeton.edu/catalog/f79d51d9-835b-4ff4-9fc0-b790a3642a72) will be needing an additional collection tag: [Archiving the American West](https://figgy.princeton.edu/catalog/f26e1fff-49fe-4ece-9977-74efa6eee12d). This is for a HIST431 class project that the students will commence work on mid-next week (the week of 04/26/2021).  I have added collection tags to everything else and gotten them started in DPUL, but could someone do this for me before Wednesday of next week?

**Comment by kelea99** [comment]
@kelynch , is there anyone who could help me with this one?

**Comment by kelea99** [comment]
Thank you so  much!!!

**Comment by tpendragon** [comment]
Should be done. Can you check and close when you get a chance?

**Comment by kelea99** [comment]
They are all there! thank you, @tpendragon !!
