### ISSUE TITLE
Address security vulnerabilities

### ISSUE THREAD

**Issue by bess** [pulibrary/figgy#4482]
As of 26 April 2021, Figgy has 13 security issues that dependabot can't handle automatically. 

https://github.com/pulibrary/figgy/security/dependabot

**Comment by bess** [comment]
The remaining issues here are related to the cloud-fixity and I don't want to upgrade anything before it is in CI.

**Comment by eliotjordan** [comment]
Security vulnerabilities addressed as much as possible at this point. What's left:

1. Created [ticket](https://github.com/pulibrary/figgy/issues/6131) for updating Google Pub/Sub and Storage packages
2. Dependencies from Lux - will be replaced at some point
3. OmniAuth issue - tried patch in Pulmap and it's not great.
