### ISSUE TITLE
Tried to parse error page as json

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4491]
## Backtrace

    line 10 of [PROJECT_ROOT]/app/services/pul_metadata_services/aspace_pulfa_record.rb: attributes
    line 64 of [PROJECT_ROOT]/app/models/remote_record.rb: attributes
    line 14 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister/apply_remote_metadata.rb: run

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/79044416)

**Comment by hackartisan** [comment]
Created https://github.com/pulibrary/princeton_ansible/issues/2227 and https://github.com/pulibrary/princeton_ansible/issues/2228
