### ISSUE TITLE
Handle empty upload set from browse everything

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4499]
To replicate:
Go to a file Manger page and click "Upload files from server". Select google drive (It may also work with the filesystem; haven't tried it). Once presented with the model listing the files, click the "x" in the corner or the "cancel" button.

Params:
{
  "utf8" => "✓",
  "authenticity_token" => "96ZQIbgZCnBY21ZwESpM_lLQsj9iIONYgd3DOKyw0WbGXxeqlP2X8XBQDlS08-VEm5x7-PZ4Jz-GkxIPafvkUA",
  "browse_everything" => {"uploads" => ["undefined"]},
  "controller" => "vector_resources",
  "action" => "browse_everything_files",
  "id" => "cf4e1fdd-9a84-430a-afb5-97fadf652e9e"
}

## Backtrace

    line 120 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: upload_files
    line 103 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: block in new_pending_uploads
    line 102 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: map

View full backtrace and more info at honeybadger.io:
- https://app.honeybadger.io/projects/53391/faults/79097728
- https://app.honeybadger.io/projects/53391/faults/89712193
- https://app.honeybadger.io/projects/53391/faults/89902024

**Comment by hackartisan** [comment]
There are a lot more examples of this error in honeybadger. Search for `browse_everything_files` in the figgy project to find them.

**Comment by tpendragon** [comment]
See also https://app.honeybadger.io/projects/53391/faults/85408479

**Comment by eliotjordan** [comment]
Won't fix since we're replacing BE.
