### ISSUE TITLE
Change state of select ephemera items "needs QA"

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4513]
Items in need of batch state or visibility change:  https://figgy.princeton.edu/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Ephemera+Folder&f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Princeton+Slavic+Collections&f%5Bstate_ssim%5D%5B%5D=complete&q=-member_ids_tsim%3A%5B%22%22+TO+%2A%5D

The records are solid and should be in figgy. However, they were completed before their digital surrogates were ingested to them. I am not sure what the easiest path would be: Batch marking them Private or batch un-completing them to be "needs QA". @escowles found these.  THoughts?

**Comment by escowles** [comment]
As long as we need to write a custom script to update these, changing their state back to draft seems like the best change.

**Comment by cwulfman** [comment]
Their visibility already seems to be "Private".  What is the end goal here?  Do they need to be uncompleted in order to attach their images?

**Comment by cwulfman** [comment]
They are private now; closing ticket.

**Comment by kelea99** [comment]
wait. they were all marked private when you looked? when?
