### ISSUE TITLE
Prompt before completing items with no members

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#4515]
I have found a number of ephemera folders, scanned resources, and scanned maps that are complete and public, despite not having any files (or volumes, etc.) attached. See:

https://figgy.princeton.edu/?f%5Bstate_ssim%5D%5B%5D=complete&q=-member_ids_tsim%3A%5B%22%22+TO+%2A%5D

In most cases, these are probably accidents or completed by a user who didn't understand the workflow. Prompting to confirm that an item should be completed even though it doesn't have any members would prevent most of these cases.

**Comment by hackartisan** [comment]
A lot of completion happens in bulk, though, right? It might be good to figure out for sure how some of these happened.

**Comment by escowles** [comment]
@hackartisan That's a good point about bulk completion. @kelea99 and I are reviewing these and will reach out to stakeholders for some of these. One of the big sets of items in this state are an ephemera collection where items were completed before the files were ingested. Excluding those, (and Coins/Issues which are fine without files), I'm not immediately seeing a pattern, so I think in general people aren't bulk completing items without files (though maybe they bulk completed collections that had a couple of items without files).

**Comment by kelea99** [comment]
@hackartisan , yes! it does. I also found the same thing as @escowles . No real patterns, save 1 example (and a couple of test/example records).  I should think this could be solved by making clear what the best practices are for completing items in figgy within the documented workflows themselves and training  opportunities for figgy users.  Or perhaps a best practices document for figgy in general?
