### ISSUE TITLE
Test failing on order dependency

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4518]
https://app.circleci.com/pipelines/github/pulibrary/figgy/2532/workflows/f9e1308b-ecfe-4bba-859f-96ebce5d1b17/jobs/32095

The right objects were returned, but in the wrong order.

Does this test truly intend to enforce order? Or should it be changed to `contains_exactly`?

**Comment by tpendragon** [comment]
We think order matters but it's not failing anymore.

**Comment by hackartisan** [comment]
This failed again https://app.circleci.com/pipelines/github/pulibrary/figgy/2802/workflows/fb67d514-06d6-43f5-a574-eff29f6283f4/jobs/33091

**Comment by hackartisan** [comment]
Again today https://app.circleci.com/pipelines/github/pulibrary/figgy/2858/workflows/6e7df656-5ecb-403f-bb18-aabace192240/jobs/33262
