### ISSUE TITLE
[Figgy/production] ThreadError: can't create Thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4519]
This is an issue raised within sidekick .

## Backtrace

```
[GEM_ROOT]/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:23:in `initialize' 

def safe_thread(name, &block)
      Thread.new do
        Thread.current['sidekiq_label'] = name
        watchdog(name, &block)
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/35108866)

**Comment by tpendragon** [comment]
This is the issue that makes all our workers stop working.

**Comment by hackartisan** [comment]
We haven't seen this in a long time. closing.
