### ISSUE TITLE
Convert select AMCs to standard collections for VRR/OARSC

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4520]
Please convert the following collections on Figgy from Archival Media Collections to a Collection.  They are ready to be managed with OARSC.

- Emir Rodríguez Monegal Papers (C0652)
- Ann Tashi Slater Collection of Cuban Writings (C0799)
- Juan García Ponce Papers (C0977)
- Dolores Koch Collection of Reinaldo Arenas (C0984)
- Gabriela Mora Collection of Elena Garro (C0994)
- Thomas Colchie ‘64 Collection on Jorge Amado (C1450)
- François Wahl Collection on Severo Sarduy (C1470)
- Rita Guibert Collection of Latin American Authors (C1502)
- Juan Gelman Papers (C1511) (ark:/88435/mk61rp43m)
- Ricardo Piglia Papers (C1513)

**Comment by tpendragon** [comment]
Done.
