### ISSUE TITLE
Raise a specific error when a work has an invalid ocr language

### ISSUE THREAD

**Issue by bess** [pulibrary/figgy#4527]
If a work is submitted with an invalid `ocr_language`, e.g., "eng " instead of "eng", tesseract will error in a non-helpful way, and the work will stay stuck in the sidekiq processing queue forever.

- [ ] the OCR background job should raise a specific error that it has encountered an `ocr_language` that it doesn't recognize so the problem can be fixed.

**Comment by tpendragon** [comment]
We're going to fix this with workflow.
