### ISSUE TITLE
Review Comment and additional settings in "edit scanned resource" did not hold save/submit when page was refreshed.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4530]
item: https://figgy.princeton.edu/catalog/ed682dc4-6672-4a41-b163-8749d99e6cf3

What i Did:
1. created a new item in figgy and ingested PDF via drag and drop function to item by 4:21PM
2. added "review comment" and clicked "Submit".  confirmed review comment made it in and was visible below the submission box.
3. added selections in "edit scanned resource": No PDF download, no User download, added portion note stating they were ToCs and clicked save
4. refreshed page later to ensure imaged loaded.
5. images are there.  information added from 2-3 above are now gone.

**Comment by kelea99** [comment]
are we not able to update/edit and save item records while image ingests are processing?

**Comment by tpendragon** [comment]
USUALLY it's fine, it looks like you just happened to hit a bad window. :(

**Comment by kelea99** [comment]
That's good, though! Id rather it be a rare occurrence and just my bad timing. Ok. I will close the ticket and will reopen if it happens again (how many bad windows can i find, i wonder?!) Thanks.
