### ISSUE TITLE
Numismatics fields missing from input form

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4536]
Some fields appear to be missing from the numismatics input form in Figgy, among them Region, State, City, Publication, Accession Number, Analysis, and Public Information.

Field values still appear indexed in the catalog ([example](https://catalog.princeton.edu/catalog/coin-13845)) but aren't visible in the show page in Figgy ([example](https://figgy.princeton.edu/catalog/e0a46faa-8c53-49c6-b89b-ff35c743ec6e)).

**Comment by kelynch** [comment]
Possibly related: #4537

**Comment by tpendragon** [comment]
@kelynch Those are all properties of the coin, not the issue: https://figgy.princeton.edu/catalog/parent/e0a46faa-8c53-49c6-b89b-ff35c743ec6e/e74585f8-e46a-4fff-8066-81eca8917843

**Comment by kelynch** [comment]
👍🏻 I followed up with Alan clarifying that the fields are visible in the Coins input form (https://figgy.princeton.edu/concern/numismatics/coins/new).  Thanks @eliotjordan and @tpendragon
