### ISSUE TITLE
Cannot create new numismatics Issues in figgy-staging

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4537]
New issues can be created in figgy production but trying to create a new Issue in figgy-staging when authenticated as a figgy admin results in the following:
<img width="887" alt="Screen Shot 2021-06-08 at 4 53 58 PM" src="https://user-images.githubusercontent.com/7795797/121257760-15130500-c87c-11eb-8317-efd248286115.png">

**Comment by kelynch** [comment]
Possibly related: #4536

**Comment by tpendragon** [comment]
I deleted the most recently created monogram, which had a broken thumbnail, and that allowed the form to work.
