### ISSUE TITLE
[Figgy/production] TypeError: no implicit conversion of nil into Array

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4543]
## Backtrace

    line 85 of [PROJECT_ROOT]/app/resources/numismatics/issues/numismatics/issue_decorator.rb: |
    line 85 of [PROJECT_ROOT]/app/resources/numismatics/issues/numismatics/issue_decorator.rb: date_range
    line 117 of [PROJECT_ROOT]/app/resources/numismatics/coins/orangelight_coin_builder.rb: document_parent_hash

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/79889811)

```
TypeError: no implicit conversion of nil into Array

    issue_decorator.rb 85 |(...)
    [PROJECT_ROOT]/app/resources/numismatics/issues/numismatics/issue_decorator.rb:85:in `|'


    def date_range
      return nil unless earliest_date | latest_date
      [earliest_date, latest_date].compact.join(" to ")
    end
```

**Comment by hectorcorrea** [comment]
Honeybadger reports that the error is happening in line:

```
return nil unless earliest_date | latest_date
```

This is probably because one of the dates is `nil` instead of an array. 

The `|` works fine when both values are arrays:

```
earliest = [1]
latest = [2]
earliest | latest
=> [1, 2]
```

but blows up with one of the values is `nil`

```
earliest = [1]
latest = nil
earliest | latest

Traceback (most recent call last):
        5: from /Users/correah/.rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        4: from /Users/correah/.rubies/ruby-2.6.6/bin/irb:23:in `load'
        3: from /Users/correah/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):29
        1: from (irb):29:in `|'
TypeError (no implicit conversion of nil into Array)
```

**Comment by eliotjordan** [comment]
https://github.com/pulibrary/figgy/issues/4544
