### ISSUE TITLE
Coin without an issue

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4547]
```
$ curl -i https://figgy.princeton.edu/concern/numismatics/coins/0e3bbb22-5204-4a3e-8e4e-f07bba989d7a/orangelight
HTTP/2 200 
[snipped]

{"error":"Coin: 3383 with id: 0e3bbb22-5204-4a3e-8e4e-f07bba989d7a has no parent numismatic issue and cannot build an OL document."}% 
```

Probably shouldn't give 200 here and also we should fix the coin.

From my log of indexing numismatics:
```
Failed to index individual record , error was: RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {                                                                                  
  "responseHeader":{                                                                      
    "status":400,                                                                         
    "QTime":1},                                                                           
  "error":{                                                                               
    "metadata":[      
      "error-class","org.apache.solr.common.SolrException",                               
      "root-error-class","org.apache.solr.common.SolrException"],                         
    "msg":"Document is missing mandatory uniqueKey field: id",                            
    "code":400}}                                                                          

URI: http://localhost:56110/solr/orangelight-core-dev/update?wt=json                                                                                                     
Request Headers: {"Content-Type"=>"application/json"}                                                                                                                    
Request Data: "[{\"error\":\"Coin: 3383 with id: 0e3bbb22-5204-4a3e-8e4e-f07bba989d7a has no parent numismatic issue and cannot build an OL document.\"}]"
```

These are orphans. We should check for equivalent coins and then delete them if there are equivalents.

**Comment by tpendragon** [comment]
We'll have to figure out how something like this could happen.

**Comment by eliotjordan** [comment]
Found 16 coins without parents. I don't have a solid theory on how this occurred. Perhaps these are an artifact of the initial import process? The modified dates seems to support this.

1d82c7db-28f9-409e-9eb9-1a51364e9977
f26c324d-35d7-4177-8d7c-56d57062be59
1eb38893-a844-4b63-bd0c-91f15f9a3c8b
0e3bbb22-5204-4a3e-8e4e-f07bba989d7a
817bf53f-d317-4962-a6ec-ad309c59fc94
98ca9bc3-849f-44f8-bae9-62b0a63ea4dc
6dc9e22d-aaa3-4006-8f7b-94d3d194db8a
4febddd9-51cf-4ad9-9240-c7c1f961b786
51e6dfd6-7fc5-42fd-bb9a-c426ce35a578
8fa11acf-e5ed-45e5-97aa-b719869f0239
ccd0d90c-c523-4935-9358-14be8ee04f13
989fb991-7dc6-47d5-a6d8-50dd97d71aa8
35bd1c25-f7c0-49cb-b4e6-173bb7e524dc
35ec621e-f58e-4de7-8af2-e6163ea63359
9695c168-5b6a-4c58-b013-bdeae9b20c37
1a6da761-543d-4dc5-99ba-479ade1c45f6

**Comment by eliotjordan** [comment]
Most of these coins were duplicates and were deleted. One of the coins had no metadata and no images and was deleted as well.
