### ISSUE TITLE
I need a rake task performed  to batch download selected ephemera folders for a researcher (LAE/Fernando)

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4581]
Fernando is in need of digital copies of all TIFFs from 179 ephemera folders for a researcher.  Everything is NOT on the Isilon, @roelmoon just looked at the boxes to check. Figgy itself will have to be raked.   The spreadsheet provides the folder bar codes, as well as the box bar codes.  It would probably be easiest to make the files available via google drive and share that with Fernando. 

https://docs.google.com/spreadsheets/d/1fOZ928HoK7S8Jpu1BjvJbD4U2jfXxRLh1qQh6lvYZp0/edit?usp=sharing

**Comment by escowles** [comment]
@kelea99 I'm confused — If the files are on the Isilon, then why do we need to run the rake task? Isn't the point of the rake task to download files from Figgy storage in a way that's easier to share?  And I couldn't access the spreadsheet.

**Comment by kelea99** [comment]
@roelmoon looked again today and not all of them are on the isilon for whatever reason.

**Comment by escowles** [comment]
These items have been exported to the Isilon `ingest_scratch` space, and Kim and Roel will get them staged in Google Drive for the user.
