### ISSUE TITLE
[Figgy/production] Valkyrie::StorageAdapter::FileNotFound: Valkyrie::StorageAdapter::FileNotFound

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4649]
## Backtrace

    line 27 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in trace
    line 43 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/79893226)

**Comment by hackartisan** [comment]
data no longer retained for this error
