### ISSUE TITLE
Report of objects with ARKs where the ARK isn't in the MARC record

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#465]
Produce a CSV report listing the bibid and ARK for all objects that have an ARK, but the ARK is not present in the imported metadata.

**Comment by tpendragon** [comment]
Here's the query:
```
select id from orm_resources where internal_resource='ScannedResource' AND NOT metadata @> '{"imported_metadata":[{"identifier": []}]}' AND (metadata @> '{"identifier": []}');
```

It runs in 166ms on staging.

**Comment by escowles** [comment]
👍  I'm not sure what the best place for this is — it seems at home in the Hyrax/Sufia dashboard, but we don't really have any place like that in Figgy.

**Comment by hackmastera** [comment]
when you're logged in the front page is kind of a dashboard. Maybe a section there?

**Comment by escowles** [comment]
@tpendragon that query works for me in postgres, but when I try to make a query object in Figgy, I get the error "ActiveModel::MissingAttributeError: missing attribute: metadata"

**Comment by tpendragon** [comment]
@escowles Sorry, for the query object one change it to `select * from....`
