### ISSUE TITLE
CDL::AutomaticIngester errors sometimes when calling mkdir_p to create the "ingesting" directory.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4669]
## Backtrace

    line 12 of [PROJECT_ROOT]/app/resources/cdl/automatic_ingester.rb: initialize
    line 6 of [PROJECT_ROOT]/app/resources/cdl/automatic_ingester.rb: new
    line 6 of [PROJECT_ROOT]/app/resources/cdl/automatic_ingester.rb: run

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/79013255)

## Resolution Details

Find a way to replicate this in a test.

Line needs a `unless Dir.exist?` guard clause.
https://github.com/pulibrary/figgy/blob/main/app/resources/cdl/automatic_ingester.rb#L12

**Comment by eliotjordan** [comment]
Doesn't appear to be happening any more.
