### ISSUE TITLE
Ephemera box test failing

### ISSUE THREAD

**Issue by thanyabegum** [pulibrary/figgy#4675]
When I run the test on line 73 in ephemera_box_spec.rb by itself, the test fails. But when I run the whole file it passes when it isn't the first test run. 

Seed 39257 generates a passing test, while running the test by itself or with seed 27337 generates a failing test.

**Comment by eliotjordan** [comment]
Is this still failing?

**Comment by m-ichelleliu** [comment]
The test now passes.
