### ISSUE TITLE
DK-SAE Project boxes: 3 (three), 4 (four), and "NYU_Hindu Nationalist" need to be migrated to SAE Project in figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4686]
@tpendragon These are the boxes  that are ready to be moved from DK's project into SAE project. Ellen's grad student can compete review on them in the SAE project once migrated.

**Comment by tpendragon** [comment]
@kelea99 Done.

**Comment by kelea99** [comment]
Thank you!
