### ISSUE TITLE
Corrupt file: Page 145 of Opinion de M. Moreau de Saint-Méry

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4687]
File: https://figgy.princeton.edu/catalog/8dfdd23c-3cf5-4ea9-852d-89f392fedcb9

@roelmoon @kelea99 Can you take a look?

Edit: Looks like page 59, 141, 145, 452 are all broken: https://figgy.princeton.edu/catalog/9b018e76-7087-4896-bd7d-fc746f7942de

When this is fixed, resolve https://app.honeybadger.io/projects/53391/faults/80089019

**Comment by kelea99** [comment]
Looks like the item was reingested. old record is gone. https://figgy.princeton.edu/catalog/72f09ea8-16ac-4d0c-b2da-5169389b8b68

closing ticket
