### ISSUE TITLE
Error handling for `PlumChangeSetPersister`

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#469]
Currently, clients are able to persist invalid ChangeSets for resources with valid data.  Given than `1234` is an invalid value for the `barcode` property for some Resource `box`:
```ruby
[33] pry(main)> change_set.validate(change_set.attributes)
=> false
[34] pry(main)> change_set_persister.save(change_set: change_set)
  Valkyrie::Persistence::Postgres::ORM::Resource Load (0.4ms)  SELECT  "orm_resources".* FROM "orm_resources" WHERE "orm_resources"."id" = $1 LIMIT $2  [["id", "026d9828-17ae-48d4-b473-f4f63a3a886b"], ["LIMIT", 1]]
   (0.3ms)  BEGIN
   (0.1ms)  COMMIT
[...]
[35] pry(main)> box.barcode
=> ["1234"]
```

Shouldn't `PlumChangeSetPersister` handle the validation errors and prevent the resource from being persisted?

**Comment by tpendragon** [comment]
Is there a problem with just branching if `change_set.validate(change_set.attributes)` returns false?

**Comment by jrgriffiniii** [comment]
After a brief discussion, it was clarified by @tpendragon that these cases should be supported either by branching if the changed values are invalid, or by strictly typing the properties within the model definitions (please see http://dry-rb.org/gems/dry-struct/).
