### ISSUE TITLE
Ingest Trustee's Minutes (remainder of PUDL0004)

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4706]
Should be linked to https://findingaids.princeton.edu/catalog/AC120

**Comment by cwulfman** [comment]
All volumes have now been ingested as individual items; see <https://figgy.princeton.edu/catalog/dcdbdb65-40ac-4e35-8944-6d90f1f71d2b>. They are not properly linked to the Finding Aid, however, and the arks go to the finding aid, not the object.

**Comment by escowles** [comment]
These are ingested here: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Board+of+Trustees+Minutes+Volumes+I-XII
