### ISSUE TITLE
Refactor LinkedData::Resource.for

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4712]
It's ignoring a bunch of cops and is pretty complicated.

**Comment by eliotjordan** [comment]
Working Refactorama branch: https://github.com/pulibrary/figgy/compare/4712-refactor-linked-data-resource

**Comment by hackartisan** [comment]
For next time:

- Should ScannedResource handle the simple resource change set situation
- Once it's a single line do we still need a factory method?
