### ISSUE TITLE
Folder Number sort/sequencing in Figgy Ephemera Project source code for lacking or inclusion of leading zeros (ex: 1, 001, 0001) should have identical effect. 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4716]
User request with SAE. Current situation is not ideal. When Folder number sort is selected, this is how it sorts now (see below). Ideally, the folder numbers would go in sequence, regardless of leading zeros being present: 
![image (1)](https://user-images.githubusercontent.com/45043014/137007297-8743b07a-97c8-4418-9959-5d450a240fe3.png)

**Comment by tpendragon** [comment]
We can't replicate this. Kim will reach out and close this if appropriate.

**Comment by kelea99** [comment]
looks good to user. aok to close
