### ISSUE TITLE
CSV-migrated item-level metadata for scanned resources from Historic Postcards Finding Aid Collection is not displaying in DPUL Collection.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4717]
Not sure if this should be a Figgy ticket instead, @tpendragon and @escowles 
Figgy Collection: "[Post cards - Item level ingest](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Postcards+-+Item+level+ingest&q=Item+level)"

DPUL Collection: https://dpul.princeton.edu/historical-postcards

The collection in Figgy: Digital images ingested as scanned resources along with item level metadata that was scripted in to figgy by @cwulfman. Items are not linked up to MARC or FA component IDs in figgy (items are also not being pushed to FA/MARC as a result)

The collection in DPUL: Title, Collections, EDM rights, ark,  range label are the only fields that are mapping over to DPUL.  In edit mode, these fields are also the only things that display. this is odd if you compare it to edit mode for [title only,](https://dpul.princeton.edu/picturesque/catalog/6m311v670/edit) [marc,](https://dpul.princeton.edu/piranesi/catalog/gq67k163z) [ephemera](https://dpul.princeton.edu/sae_sri_lanka_dissidents/catalog/410525b7-21ce-4021-b7df-5e3789a526ed), and [FA](https://dpul.princeton.edu/pudl0017/catalog/w37637491) examples in DPUL.

**Comment by escowles** [comment]
After the indexing issues were resolved, the items were reindexed and now all of the metadata is displaying properly.
