### ISSUE TITLE
[Figgy/production] Notice: Local fixity failure on file disk:///opt/repository/files/36/5b/dd/365bdd37c0694568aa8b3428bea37097/parcels_13111_2019.xml

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4742]
## Backtrace

    line 108 of [PROJECT_ROOT]/app/resources/nested_resources/file_metadata.rb: run_fixity
    line 19 of [PROJECT_ROOT]/app/resources/file_sets/file_set.rb: run_fixity
    line 8 of [PROJECT_ROOT]/app/jobs/check_fixity_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/82223674)

**Comment by eliotjordan** [comment]
Deleted existing FileSet and re-uploaded. Fixity check is on the queue and will run again.
