### ISSUE TITLE
Refactor RelatedResourcesTable

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4748]
https://github.com/pulibrary/figgy/blob/dd1dbac79002ee7fbe39773a3909d9e77d034c60/app/assets/javascripts/relationships/related_resources_table.es6

Since https://github.com/pulibrary/figgy/pull/4747 it needs to be reviewed for what the shared functionality actually is.

**Comment by tpendragon** [comment]
This happened in #4819
