### ISSUE TITLE
DAO Generation should handle if the digital object has already been created.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4761]
Right now if it got created by a process that then failed it tries to create the digital object again and fails because the identifier must be unique.

The error Aspace returns is:

```ruby
irb(main):012:0> digital_object = updater.create_digital_object(archival_object)
=> {"error"=>{"digital_object_id"=>["Must be unique"]}}
```

It should catch the error for failing to create the digital object, and instead find the existing digital object and attach it instead.

See here: https://github.com/pulibrary/figgy/blob/0d0af960c433693ac34c90b25c47b96647dcc23e/app/services/dao_updater.rb#L16

**Comment by hackartisan** [comment]
Some initial work-in-progress is on 4761-dao-exists
