### ISSUE TITLE
Resource has ark with `pdf` appended to it and cannot mark complete

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4765]
[Figgy/production] Ezid::IdentifierNotFoundError: bad request - no such identifier

The [catalog record](https://catalog.princeton.edu/catalog/9940846763506421/staff_view) has the ark with pdf appended and in that case it links to the pdf, but in figgy it uses the ark to try to communicate with the ezid service so it needs to be just the ark not a whole url.

In this case there's another figgy resource with the same ark: https://figgy.princeton.edu/catalog/1847e70a-fa11-4e9d-ae4b-325edc48366c -- that's the one the catalog record is pointing to.

## Backtrace

    line 41 of [PROJECT_ROOT]/app/services/identifier_service.rb: update_metadata
    line 7 of [PROJECT_ROOT]/app/services/identifier_service.rb: mint_or_update
    line 22 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister/mint_identifier.rb: mint_identifier

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/82122362)

Follow-up with @laurenobell - this resource needs to be marked complete

**Comment by hackartisan** [comment]
It looks like this object is pulling a bad ark from the catalog record

https://github.com/pulibrary/figgy/blob/3b7e1b4575f36c4244c74258a1ae2b976bf81ebc/app/change_set_persisters/change_set_persister/apply_remote_metadata.rb#L49

**Comment by hackartisan** [comment]
The first series has the same problem. Report from @laurenobell:

I am trying to "complete" this item in Figgy. It is the first series of the one I had an issue with last week (which was the second series of the collection). I'm receiving the same error as last time. (bib ID: 9919685413506421)
- Figgy item: https://figgy.princeton.edu/catalog/21e392d3-4bc3-4d6d-bea7-2228d623b455
- Figgy error: https://figgy.princeton.edu/concern/scanned_resources/21e392d3-4bc3-4d6d-bea7-2228d623b455
- Catalog Record: https://catalog.princeton.edu/catalog/9919685413506421 (edited)

**Comment by tpendragon** [comment]
We should fix the new instance, and think about ways to make sure we don't inherit arks for resources which are in Figgy but already have that ARK maybe?

**Comment by hackartisan** [comment]
The new instance of this was fixed manually in the same way as the previous one.
