### ISSUE TITLE
Cannot generate derivatives for ESRI Shapefile zip

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4766]
The error on this honeybadger issue is [Figgy/production] NoMethodError: undefined method `visibility_badge' for #<#<Class:0x00007f0c80faab20>:0x00007f0c80fa8e38>

But that's only showing up once, while there have been 12 retries on the job so I'm not sure it's the whole story.

Here's the item: https://figgy.princeton.edu/catalog/968cc5ed-4fd0-4e3b-9f05-4a42a699028f

## Backtrace

    line 48 of [PROJECT_ROOT]/app/decorators/valkyrie/resource_decorator.rb: block in visibility
    line 47 of [PROJECT_ROOT]/app/decorators/valkyrie/resource_decorator.rb: map
    line 47 of [PROJECT_ROOT]/app/decorators/valkyrie/resource_decorator.rb: visibility

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/82370933)

**Comment by eliotjordan** [comment]
This looks to be a case where the parent resource was deleted before the regenerate derivates job completed.
