### ISSUE TITLE
Generate mosaic JSON documents

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#4770]
1. Generate a mosaicJSON document from a RasterSet.
1. The reference tool for building these is python-based, so will need to be installed via pip
1. A possible approach is to structure it like a generated PDF; cache based on member IDs.
1. Another approach is to generate (and regenerate a mosaic.json) derivative on the RasterSet and upload that to S3. Might be more performant.

Spec: https://github.com/developmentseed/mosaicjson-spec
CLI tool: https://github.com/developmentseed/cogeo-mosaic

Example JSON: https://gist.githubusercontent.com/tpendragon/6a5e23a0f05b5be4c61759358f48f9a8/raw/e51ed5cbe87550bfd08c0ba47b861568ffa39cd4/mosaic.json

**Comment by eliotjordan** [comment]
Example WMTSCapabilities.xml: https://gist.github.com/eliotjordan/da5a1c4ad1a1b8b2b7bd490d3929a53d

**Comment by hackartisan** [comment]
websequencediagrams.com: 

![mosaic-json-request.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/b7f3b616-25d8-4013-83bc-d816e5dd9db7)

```
title mosaic.json  Request


actor User
User -> +cloudfront-viewer-request: Puts map-tiles link in GIS software
note right of cloudfront-viewer-request: is a lambda
cloudfront-viewer-request -> +figgy: get s3 url of mosaic.json (including fingerprint)
note right of cloudfront-viewer-request: optional cache here.
note right of cloudfront-viewer-request: optional fallback here to fingerprint-less mosaic.json
note right of figgy: calculate fingerprint
note right of figgy: check s3 for fingerprinted json file
note right of figgy: generate it to s3 if needed, both with and without fingerprint
figgy --> -cloudfront-viewer-request: return s3 url


note right of cloudfront-viewer-request: put s3 url as a param
cloudfront-viewer-request -> +titiler lambda: request the image tile
titiler lambda --> -cloudfront-viewer-request: return the image tile

cloudfront-viewer-request --> -User: return image tiles
```

**Comment by hackartisan** [comment]
Figgy should store the mosaic.json files on s3 under a bucket path named after the figgy resource id.
