### ISSUE TITLE
Add WMTS reference to Pulmap Solr document for RasterSets

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#4772]
WMTS: Web Map Tile Service

These should link out the to the new raster image and mosaic service (titiler).

This enables showing a link to these in the modal in pulmap.

**Comment by hackartisan** [comment]
Add via the references builder: https://github.com/pulibrary/figgy/blob/c912e061dc7725f787de7f8a0d1f17ea78c287cb/app/services/geo_discovery/document_builder/references_builder.rb

should probably look similar to these https://github.com/pulibrary/figgy/blob/c912e061dc7725f787de7f8a0d1f17ea78c287cb/spec/services/geo_discovery/document_builder_spec.rb#L83-L84 need to get the exact uri

**Comment by hackartisan** [comment]
I think it's WMTS. I found http://www.opengis.net/def/serviceType/ogc/wmts

I don't see one for TMS though. https://defs.opengis.net/vocprez/search?search=tms&from=all

**Comment by eliotjordan** [comment]
@hackartisan We should probably add WMTS in an upstream PR to GeoBlacklight.

TMS ref is here: https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/constants.rb#L19

**Comment by hackartisan** [comment]
@eliotjordan do you just mean a GBL PR to add wmts to that list? Or something more?

**Comment by hackartisan** [comment]
Created https://github.com/pulibrary/figgy/issues/4865 for the TMS (or XYZ) service and updating this issue to only be WMTS.
