### ISSUE TITLE
Oxford Common Filesystem Layout?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#478]
There is a working group getting started that's looking at filesystem persistence from a interoperability/migration/backup perspective.   See https://groups.google.com/d/msg/fedora-community/k7sU1IosEIU/zf_08rsFDAAJ

Is this something we should participate in?  For Figgy, or for Valkyrie?

**Comment by escowles** [comment]
Yes, I think it's much more realistic to talk about how files should be exported for migration/backup purposes.  But I can imagine using the same layout natively in a repository, if the simultaneous modification on disk use case was important enough to you.

**Comment by stain** [comment]
Here are some links on OCFL for the benefit of new readers (like myself):

Working document: https://docs.google.com/document/d/13gFfSu1fePKx0eQYk458zE6OZwCW5JH_hTIG58f3S8c/edit

GitHub repo (currently empty): https://github.com/OCFL/spec -- intended to populate https://ocfl.github.io/spec/ ?

OXCFL Telcons (like [2018-01-19](http://bit.ly/ocfl-2018-01-notes
)) announced at: http://mail.asis.org/pipermail/pasig-discuss/

**Comment by tpendragon** [comment]
There's no call locally to implement OCFL, so we'll close this and open another issue if it happens. For now we're going to be storing bags on our preservation infrastructure.
