### ISSUE TITLE
Faulty digital objects in ArchivesSpace need to be removed and figgy re-synced

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4781]
Question from Will Clements:

We have some faulty digital objects in ArchivesSpace. They do have corresponding items in Figgy, but the digital objects don't point to them. If we delete those objects in ASpace, is there a way to re-sync to Figgy so that the finding aid points to the correct item and the digital object is created anew?

The DaoUpdater contains code to create these objects and link them: 
https://github.com/pulibrary/figgy/blob/0d0af960c433693ac34c90b25c47b96647dcc23e/app/services/dao_updater.rb#L16-L18

This gets called via the change set persister when a pulfa-linked resource changes its state to complete:
https://github.com/pulibrary/figgy/blob/0d0af960c433693ac34c90b25c47b96647dcc23e/app/change_set_persisters/change_set_persister/update_aspace_dao.rb#L13

Will is going to delete the bad digital objects from aspace. This spreadsheet enumerates the ones that will need to be re-run through figgy: https://docs.google.com/spreadsheets/d/1sUJVx1YnsdZAaYtx4MOCKj-g2r0CTMRQipAzkwjZ5lU/edit#gid=591174644

## Sudden Priority Justification

Researchers aren't able to access this material and actively want to - our staff can't currently provide this content to them. The DAOs will get removed from ASpace by Regine, probably, so we can delay a little bit here until that's done. Current plan is to do this as a high priority on our next maintenance week - likely the week of November 15.

**Comment by hackartisan** [comment]
Note that researchers are asking for these materials

**Comment by regineheberlein** [comment]
The outdated digital objects have been deleted from ASpace.

**Comment by tpendragon** [comment]
The process I've done so far:

Update remote metadata for all these items (not necessary, but seemed nice.)
Enqueue `UpdateDaoJob` for each of these items.
After those are done, went to pulfalight-prod and ran `bundle exec rake pulfalight:indexing:incremental` (this would have run eventually, but I wanted to get this ticket closed)

When those are done we should be able to check the content and make sure the viewers display.
