### ISSUE TITLE
Large number of South Asian Ephemera items are missing memberOf for the sae collection

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4782]
## Expected

The DPUL "Collections" facet count for "South Asian Ephemera" on https://dpul.princeton.edu/sae should include the full set of items indexed into the exhibit.

## Actual

Only a subset of them are included in this facet. It appears to be a subset that overlaps entirely with the items in the "Dissidents" collection.

## Additional info

Here are 3 examples where there are no collections indexed:
* "K" of Pakistan
  * https://dpul.princeton.edu/sae/catalog/c7f5a589-4ef9-4bfa-8c7d-88078ad5b7d6
  * https://figgy.princeton.edu/catalog/c7f5a589-4ef9-4bfa-8c7d-88078ad5b7d6.jsonld
* 'Kalyāṇa kosha'
  * https://dpul.princeton.edu/sae/catalog/ef872767-08ed-4914-be00-21e515ec1fd9
  * https://figgy.princeton.edu/catalog/ef872767-08ed-4914-be00-21e515ec1fd9.jsonld
* 2013 Election Manifesto
  * https://dpul.princeton.edu/sae/catalog/0fdcb86a-1198-4017-8e2e-7884c662fff2
  * https://figgy.princeton.edu/catalog/0fdcb86a-1198-4017-8e2e-7884c662fff2.jsonld

All 3 are in boxes and their "memberOf" reflects their box membership.

## Follow-up

Contact Ellen when this is resolved; she wants to turn the collection facet back on in sae once the numbers are correct.

**Comment by hackartisan** [comment]
Does figgy need to add a `memberOf` entry for the ancestor ephemera project to ephemera folders that are inside boxes?

**Comment by kelea99** [comment]
By memberOf , do you mean something like that of adding the collections or something on the backend? I can't see if there is something up with their assocation with the SAE project now.  

I also  wonder if moving boxes from one project to another also is an issue? This is the ephemera that transfers materials from a locked down project to the SAE project, once external contributors have completed metadtata.

**Comment by tpendragon** [comment]
> Does figgy need to add a `memberOf` entry for the ancestor ephemera project to ephemera folders that are inside boxes?

yup

**Comment by hackartisan** [comment]
The code is correct; see https://github.com/pulibrary/figgy/blob/b62b4cd7ffa3df19133657e0b84155f51249468e/spec/models/linked_data/linked_ephemera_folder_spec.rb#L301-L302.

it looks like there's an issue with the data:

```
irb(main):008:0> folder.decorate.ephemera_box.id
=> #<Valkyrie::ID:0x000056445b951a50 @id="0dc372aa-e377-4b9f-ae8e-6de99fe02d36">
irb(main):009:0> folder.decorate.ephemera_project.id
=> #<Valkyrie::ID:0x000056445bf56fe0 @id="f99af4de-fed4-4baa-82b1-6e857b230306">
```
