### ISSUE TITLE
Ingest example raster dataset for mosaic.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4785]
I'm uploading the dataset to S3 now, should be available soon.

Ingest these as one Raster Resource, with several child raster resources.

Example is in browse everything under `ingest_scratch/mosaic/output`, devs can get a download link from #digital-library-services.

The idea is to have something in figgy-staging we can try the other features out with.

Write up the process in /docs/user-stories under an `Ingest Stories` heading. 

Format the files into a structure as defined by #4888

**Comment by tpendragon** [comment]
We should talk to Dan Walker about how they bulk ingest raster resources/scanned maps. We should invite him to one of our meetings to show us, or one can be scheduled.

**Comment by tpendragon** [comment]
Command I'm using to get files locally:

```
rsync -vaz pulsys@lib-proc7.princeton.edu:/mnt/hydra_sources/maplab/dan/bulk_raster_tests tmp/
```

**Comment by tpendragon** [comment]
Over VPN this was too slow to finish in a reliable amount fo time, so I'm tar/gzipping up the directory and I'll put it on S3.

**Comment by hackartisan** [comment]
The test set contains 4 directories: `1_scanned(ARK_dcwp988v99m)`, `2_georeferenced`, `3_clipped`, and `GeoTIFF_copy`. `1_scanned(ARK_dcwp988v99m)` contains a single tiff of each scan; each of the other directories contains multiple files per scan. I did a test ingesting the tiffs from the directory `GeoTIFF_copy`. I massaged them into the following directory structure:

```
└── raster_bulk_geotiffs_test
    └── 99125433518606421
        ├── Adrianople
        │   └── Adrianople.tif
        ├── Constantinople
        │   └── Constantinople.tif
        ├── Elbasan
        │   └── Elbasan.tif
        ├── Gallipoli
        │   └── Gallipoli.tif
        ├── Gumuljina
        │   └── Gumuljina.tif
        ├── Ipek
        │   └── Ipek.tif
        ├── Jumaa_i_Bala
        │   └── Jumaa_i_Bala.tif
        ├── Kirjali
        │   └── Kirjali.tif
        ├── Kozana
        │   └── Kozana.tif
        ├── Lemnos
        │   └── Lemnos.tif
        ├── Monastir
        │   └── Monastir.tif
        ├── Mt_Athos
        │   └── Mt_Athos.tif
        ├── Prishtina
        │   └── Prishtina.tif
        ├── Rodosto
        │   └── Rodosto.tif
        ├── Salonika
        │   └── Salonika.tif
        ├── Scutari
        │   └── Scutari.tif
        ├── Sofia
        │   └── Sofia.tif
        ├── Uskub
        │   └── Uskub.tif
        ├── Valona
        │   └── Valona.tif
        └── Vize
            └── Vize.tif
```

It created a RasterSet as expected, pulling in the metadata from the catalog as expected. Each member had a title taken from the name of the directory, as expected.

I did the same with the mix of tiffs and pngs from the `3_clipped` directory. These ingested with no errors but the png resources did not generate all the desired derivatives. They generated only an intermediate tiff.

![Screen Shot 2022-01-12 at 9.59.57 AM.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/7de8e9b1-4dc3-45bc-8e62-f5a78bdd43ec)

![Screen Shot 2022-01-12 at 10.02.31 AM.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/3fa0f026-17c4-4821-803d-d9b6461d8d0b)

**Comment by hackartisan** [comment]
I copied the ingest-ready / geotiffs-only directory to `hydra_sources/ingest_scratch/mosaic/raster_bulk_geotiffs_test` and then used that to create https://figgy-staging.princeton.edu/catalog/9a3dd626-d169-49b4-b6eb-c21132d0bd32

**Comment by hackartisan** [comment]
reopening - documentation piece not completed

**Comment by tpendragon** [comment]
I'm not 100% sure this is the right format yet either - we'll need an ingest that has both the collared and uncollared versions.

**Comment by tpendragon** [comment]
I've painstakingly prepped the ScannedMap w/ Rasters example. It should be ready to bulk ingest after #4931 and #4930 are merged.

```
deploy@figgy-staging2:/mnt/hydra_sources/ingest_scratch/mosaic/scanned_map_bulk_ingest_test$ tree .
.
└── 99125413918506421
    ├── 9968666393506421
    │   ├── Monastir.tif
    │   └── Raster
    │       ├── Monastir_done_cropped.tif
    │       └── Monastir_done.tif
    ├── 9968666433506421
    │   ├── Adrianople.tif
    │   └── Raster
    │       ├── Adrianople_done_cropped.tif
    │       └── Adrianople_done.tif
    ├── 9968666453506421
    │   ├── Raster
    │   │   ├── Valona_done_cropped.tif
    │   │   └── Valona_done.png
    │   └── Valona.tif
    ├── 9968666473506421
    │   ├── Constantinople.tif
    │   └── Raster
    │       ├── Constantinople_done_cropped.tif
    │       └── Constantinople_done.png
    ├── 9968666513506421
    │   ├── Gallipoli.tif
    │   └── Raster
    │       ├── Gallipoli_done_cropped.tif
    │       └── Gallipoli_done.png
    ├── 9968666533506421
    │   ├── Lemnos.tif
    │   └── Raster
    │       ├── Lemnos_done_cropped.tif
    │       └── Lemnos_done.tif
    ├── 9968666543506421
    │   ├── Raster
    │   │   ├── Rodosto_done_cropped.tif
    │   │   └── Rodosto_done.tif
    │   └── Rodosto.tif
    ├── 9968666553506421
    │   ├── Jumaa_i_Bala.tif
    │   └── Raster
    │       ├── Jumaa_I_Bala_done_cropped.tif
    │       └── Jumaa_I_Bala_done.tif
    ├── 9968666583506421
    │   ├── Raster
    │   │   ├── Vize_done_cropped.tif
    │   │   └── Vize_done.png
    │   └── Vize.tif
    ├── 9968676993506421
    │   ├── Kozana.tif
    │   └── Raster
    │       ├── Kozana_done_cropped.tif
    │       └── Kozana_done.tif
    ├── 9968677003506421
    │   ├── Raster
    │   │   ├── Salonika_done_cropped.tif
    │   │   └── Salonika_done.tif
    │   └── Salonika.tif
    ├── 9968677013506421
    │   ├── Mt_Athos.tif
    │   └── Raster
    │       ├── Mt_Athos_done_cropped.tif
    │       └── Mt_Athos_done.tif
    ├── 9968677023506421
    │   ├── Elbasan.tif
    │   └── Raster
    │       ├── Elbasan_done_cropped.tif
    │       └── Elbasan_done.png
    ├── 9968677033506421
    │   ├── Gumuljina.tif
    │   └── Raster
    │       ├── Gumuljina_done_cropped.tif
    │       └── Gumuljina_done.tif
    ├── 9968677043506421
    │   ├── Ipek.tif
    │   └── Raster
    │       ├── Ipek_done_cropped.tif
    │       └── Ipek_done.tif
    ├── 9968677053506421
    │   ├── Kirjali.tif
    │   └── Raster
    │       ├── Kirjali_done_cropped.tif
    │       └── Kirjali_done.tif
    ├── 9968677063506421
    │   ├── Prishtina.tif
    │   └── Raster
    │       ├── Prishtina_done_cropped.tif
    │       └── Prishtina_done.tif
    ├── 9968677073506421
    │   ├── Raster
    │   │   ├── Scutari_done_cropped.tif
    │   │   └── Scutari_done.png
    │   └── Scutari.tif
    ├── 9968677083506421
    │   ├── Raster
    │   │   ├── Sofia_done_cropped.tif
    │   │   └── Sofia_done.tif
    │   └── Sofia.tif
    └── 9968677093506421
        ├── Raster
        │   ├── Uskub_done_cropped.tif
        │   └── Uskub_done.tif
        └── Uskub.tif
```

**Comment by tpendragon** [comment]
https://figgy-staging.princeton.edu/catalog/2a91d82c-541c-426c-b787-cc62afe8f248
