### ISSUE TITLE
Bulk move filesets from Da Ming lü li fu jie [microform]

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4793]
Request for a bulk fileset move from @tventimi 

The main item affected is https://figgy.princeton.edu/catalog/d4530b35-0c84-4959-b9aa-8870a9827706 .    Images 947 - 1247 can be deleted as they are duplicates of content elsewhere.  Images 1 - 185 should be moved to the end of another item: https://figgy.princeton.edu/catalog/171055a1-7066-4409-b0be-1e5eec080985 .

So, only images 186 - 946 should be retained in the original item.

**Comment by tpendragon** [comment]
It's been a long time. Kim will check in.

**Comment by kelea99** [comment]
Contacted Tom.  Will update ticket when needs  are confirmed

**Comment by tventimi** [comment]
https://figgy.princeton.edu/catalog/171055a1-7066-4409-b0be-1e5eec080985 looks good.
Can images 1-185 be removed from https://figgy.princeton.edu/catalog/d4530b35-0c84-4959-b9aa-8870a9827706 ?  Thanks.
