### ISSUE TITLE
Bibdata error page returns 200

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#4798]
Proxy for: https://github.com/pulibrary/princeton_ansible/issues/2227

Honeybadger report: https://app.honeybadger.io/projects/53391/faults/82577998

Example code:
```response = Faraday.new(url: bibdata_base).get("bibliographic/#{source_metadata_identifier}/items")```

**Comment by hackartisan** [comment]
related to https://github.com/pulibrary/princeton_ansible/issues/2227
