### ISSUE TITLE
Search for Lapidus_11426331-02 gives "The requested resource does not exist" flash

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4802]
This title-only item was ingested today and is 900+ images. The ingests all finished in sidekiq but a search for that string in Figgy hits the error handling in place for Valkyrie::Persistence::ObjectNotFoundError:  https://github.com/pulibrary/figgy/blob/730edfe598430060ead1ba3cdbdf76da1bacdf8b/app/controllers/application_controller.rb#L75-L83

Need to figure out what happened to the item, whether there is clean up to be done, and advise @roelmoon on next steps.

**Comment by tpendragon** [comment]
I checked the JSON to see what could be erroring: https://figgy.princeton.edu/catalog.json?utf8=%E2%9C%93&q=Lapidus_11426331-02

There were two results -  the second one had an ID that's not in postgres. ID: `76364993-48d3-40b7-91eb-3c13d88a4427`

I searched the logs, and it looks like this corresponds to https://app.honeybadger.io/projects/53391/faults/82636440.

In the logs that corresponds to this error:

```
Task queue processing has stalled for 20001 ms with 0 remaining elements to process.
```

We saw this in reindexing.

I think what's happening is Solr's taking 20 seconds (which is NUTS!) to commit some big record combos. The indexing adapter sees this error and rolls back, with the assumption that solr's errored so it didn't get the record persisted. Unfortunately, Solr's throwing this error but -still indexing.-

**Comment by tpendragon** [comment]
I'm hoping https://github.com/pulibrary/princeton_ansible/pull/2575 will fix this. I've deployed it, and I'll resolve the relevant honeybadger errors and we can keep an eye on it.

**Comment by tpendragon** [comment]
I deleted the one bad solr record, I'm going to see about doing a quick check for some bad solr records which would come up in searches.

**Comment by tpendragon** [comment]
Step 1: Get all IDs in Solr created in the last three days:
```ruby
doc_ids = Valkyrie::MetadataAdapter.find(:index_solr).connection.get("select", params: { q: "!(internal_resource_ssim:FileSet)", fq: "created_at_dtsi:[#{3.days.ago.iso8601} TO NOW]", fl: "id", rows: 200000})["response"]["docs"].map{|x| x["id"]}
```

Step 2: Find all of them which don't have a postgres equivalent

```ruby
bad_docs = doc_ids.reject do |id|
begin
  ChangeSetPersister.default.query_service.find_by(id: id)
rescue
end
end.compact
```

**Comment by tpendragon** [comment]
That's been run in production - closing this ticket.

**Comment by tpendragon** [comment]
We got this today after catalog reindexing locked up solr, queries above found 34 records and fixed them.

**Comment by hackartisan** [comment]
Checked again just now since the alert went off a bunch of times but there were no bad ids 👍🏻
