### ISSUE TITLE
Create some actions for missing ARK report window?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#481]
Looking at: https://figgy-staging.princeton.edu/reports/identifiers_to_reconcile

I imagine it would be useful to view a record and maybe refresh remote metadata from this panel. Depends on how they intend to use it though.

**Comment by escowles** [comment]
Yes, I think they'll want to update remote metadata after they've loaded the ARKs into Voyager.  So being able to refresh remote metadata for some or all of the records would be good.

**Comment by tpendragon** [comment]
We update metadata nightly and now we're talking about automating this process, so closing this ticket.
