### ISSUE TITLE
Resource has member that doesn't exist

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4811]
resource: https://figgy.princeton.edu/catalog/1c3bf917-f7c2-4f6c-b651-6bf023b339ab
member 404: https://figgy.princeton.edu/catalog/parent/1c3bf917-f7c2-4f6c-b651-6bf023b339ab/65fc3d12-dd8e-4de2-ac74-6e9d018078d1

![Screen Shot 2021-11-29 at 9 22 51 AM](https://user-images.githubusercontent.com/845363/143884841-dc7182df-607a-4486-9cbd-db37a2a2b9cd.png)

## Sudden Priority Justification

This content is marked complete and needed for patrons.

**Comment by kelea99** [comment]
From Steve: 
- Yes, there was a real file.  
-  This happened  on Wed evening Nov 24: he had deleted it then as he was waiting for Figgy to reset and show the deletion, Figgy just spun and spun – no action --  
- He eventually I just quit Figgy. 
-  Checked back on Sunday evening Nov 28,  and saw the ghost and then wrote to me.

**Comment by hackartisan** [comment]
Same problem is happening on https://figgy.princeton.edu/catalog/1e5e140d-cb93-4d09-b2a9-3e4c4e8c00b3 although the thumbnail is still visible on that one.

**Comment by hackartisan** [comment]
This looks like a solr timeout. honeybadger notification: https://app.honeybadger.io/projects/53391/faults/82724727

**Comment by hackartisan** [comment]
That honeybadger notification is for the second instance. Can't actually find a honeybadger error off the first id.

**Comment by hackartisan** [comment]
Fixed the first one. The second had been fixed already, I guess it was done again via the UI.
