### ISSUE TITLE
Re-enable lib-solr-prod4 replica in Solr

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4812]
From @tventimi:

In Figgy, I keep getting the message “Sorry, there was a problem saving your work” when trying to save changes in the order manager. This is the item I am having trouble with: https://figgy.princeton.edu/concern/scanned_resources/7299ec40-f0ea-4f06-801a-f0e8e3d708a7/order_manager

**Comment by hackartisan** [comment]
Also had several reports from Steve of this issue today. It works incrementally.

**Comment by tpendragon** [comment]
We think this is because of solr timeouts caused by replicating across data centers. We've disabled lib-solr-prod4 as a replication target for Figgy, which means both replicas are in the same data center. If that fixes it we may need a third replica in the same center.

**Comment by tpendragon** [comment]
Ops has very helpfully moved lib-solr-prod4 to the same data center as 5/6 - we think this makes it safe to re-enable the third replica. We'll do as a high priority during maintenance week.
