### ISSUE TITLE
Intermittent error on charles ruas papers manifest

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4814]
[Figgy/production] NoMethodError: undefined method `downloadable' for #<FileSet:0x0000559f4def8200>

## Backtrace

    line 11 of [PROJECT_ROOT]/app/services/manifest_builder/record_property_builder_v3.rb: apply
    line 800 of [PROJECT_ROOT]/app/services/manifest_builder.rb: manifest
    line 15 of [PROJECT_ROOT]/app/services/manifest_builder.rb: build

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/58887779)

**Comment by tpendragon** [comment]
This is the collection manifest for an ArchivalMediaCollection, which has some special stuff to make it a V3 collection manifest to display all its audio files as an embedded set. I don't remember the use case for this, and it doesn't seem to display anywhere.

**Comment by eliotjordan** [comment]
We'll re-open if error happens again.
