### ISSUE TITLE
Ephemera Folders should display height/width in JSON-LD as "# cm" instead of "#"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4832]
This will correct the display in DPUL.

## Acceptance Criteria

- [ ] https://figgy.princeton.edu/catalog/f092c02a-9d59-4c5d-9158-e0dceb92e57f.jsonld displays "width" as "21 cm" and "height" as "30 cm"

## First Step

Update the test to expect "10 cm" for width.

## Implementation Details

https://github.com/pulibrary/figgy/blob/main/spec/controllers/catalog_controller_spec.rb#L827 is a good place to add something like `expect(json_body['width']).to eq ["10 cm"]`

https://github.com/pulibrary/figgy/blob/main/app/models/concerns/linked_data/linked_ephemera_folder.rb#L133

is where width is defined for JSON-LD.

**Comment by kelea99** [comment]
See https://github.com/pulibrary/dpul/issues/1213
