### ISSUE TITLE
Remove references to cantaloupe

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4837]
Figgy doesn't use cantaloupe anymore. There is some configuration for it still (check figgy codebase and princeton_ansible) and some comments that reference it.

**Comment by m-ichelleliu** [comment]
@tpendragon Below are the instances cantaloupe is mentioned wrt figgy in the princeton_ansible repo. What can and cannot be deleted? Thank you!

./group_vars/figgy/staging.yml:figgy_cantaloupe_images_mount: iiif-staging1
./group_vars/figgy/staging.yml:figgy_derivatives_mount: '/mnt/{{figgy_cantaloupe_images_mount}}/data/jp2s/figgy_staging'
./group_vars/figgy/staging.yml:    # cantaloupe will use terminal value as directory name, but slashes aren't
./group_vars/figgy/staging.yml:  - name: CANTALOUPE_URL
./group_vars/figgy/production.yml:figgy_cantaloupe_images_mount: 'libimages2'
./group_vars/figgy/production.yml:  - name: CANTALOUPE_URL
./group_vars/figgy/production.yml:cantaloupe_user: '{{deploy_user}}'
./group_vars/figgy/production.yml:cantaloupe_group: '{{deploy_user}}'
./group_vars/figgy/production.yml:cantaloupe_FilesystemResolver_BasicLookupStrategy_path_prefix: /opt/repository/derivatives/
./group_vars/figgy/production.yml:cantaloupe_cache_source: FilesystemCache
./group_vars/figgy/production.yml:cantaloupe_cache_derivative: FilesystemCache
./group_vars/figgy/production.yml:cantaloupe_create_FilesystemCache_dir: yes
./group_vars/figgy/production.yml:cantaloupe_version: 3.3.2
./group_vars/figgy/production.yml:cantaloupe_KakaduProcessor_path_to_binaries: /opt/kakadu
./group_vars/figgy/production.yml:cantaloupe_log_application_level: all
./roles/figgy/tasks/main.yml:    - '{{ figgy_cantaloupe_images_mount }}'
./roles/figgy/tasks/main.yml:- name: Create cantaloupe images mount
./roles/figgy/tasks/main.yml:    name: '/mnt/{{ figgy_cantaloupe_images_mount }}/data'
./roles/figgy/tasks/main.yml:    src: '//{{ figgy_cantaloupe_images_mount }}.princeton.edu/data'
./roles/figgy/defaults/main.yml:figgy_cantaloupe_images_mount: 'iiif-staging1'
./roles/figgy/defaults/main.yml:figgy_derivatives_mount: '/mnt/{{figgy_cantaloupe_images_mount}}/data/jp2s/figgy_staging'
./roles/figgy/templates/nginx_cantaloupe_config:location ~ ^/cantaloupe.* {
./roles/figgy/templates/nginx_cantaloupe_config:    if ($request_uri ~* "/cantaloupe/(.*)") {
./roles/figgy/templates/nginx_cantaloupe_config:    proxy_set_header X-Forwarded-Path /cantaloupe;
./roles/figgy/templates/nginx_cantaloupe_config:    proxy_redirect http://127.0.0.1:8182/ /cantaloupe;

**Comment by tpendragon** [comment]
I think all of them can go.
