### ISSUE TITLE
Bad tiff from Kitāb al-Barakah fī madḥ al-saʻy wa-al-ḥarakah microfilm needs to be reingested

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4848]
resource: https://figgy.princeton.edu/catalog/4026100a-d906-410c-818b-905c5051f7fa
fileset: https://figgy.princeton.edu/catalog/parent/4026100a-d906-410c-818b-905c5051f7fa/d98614ac-1cfe-4d32-9c1d-dc117c145c90

honeybadger error: https://app.honeybadger.io/projects/53391/faults/83258041

**Comment by tpendragon** [comment]
@kelea99 will follow up on this.

**Comment by kelea99** [comment]
Wrote to Colleen and Roel about this one.
