### ISSUE TITLE
Thumbnail helper should return false for `can_have_manifests?' if there's no parent.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4850]
[Figgy/production] NoMethodError: undefined method `can_have_manifests?' for NilClass:Class

Add `return false unless parent`
https://github.com/pulibrary/figgy/blob/b7fcce1cb3819c66f0f818db704ac0582611109b/app/helpers/thumbnail_helper.rb#L35

Also send a notice to honeybadger so we can be notified of orphan filesets.

## Backtrace

    line 35 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: geo_thumbnail?
    line 94 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: figgy_thumbnail_method
    line 26 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: figgy_thumbnail_path

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/55188222)

**Comment by taylor-yamashita** [comment]
I believe this issue has already been resolved: https://github.com/pulibrary/figgy/blob/40dc3bd30a8ed4dc45905aa0a40b6b9abd907b0e/app/helpers/thumbnail_helper.rb#L35
