### ISSUE TITLE
Add Tilejson reference to Pulmap Solr document for RasterResources

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4865]
Split off from #4772. Solution should be similar (a link to the titiler service).

The link should be to the tilejson endpoint in Titiler. An example:

https://map-tiles-staging.princeton.edu/mosaicjson/tilejson.json?id=f75a1e91ade3427a82a109d321d47cbf

This will be in support of https://github.com/pulibrary/pulmap/issues/990

**Comment by eliotjordan** [comment]
Difference between TMS and XYZ tile schemes: https://gist.github.com/tmcw/4954720

**Comment by eliotjordan** [comment]
Example URL value:

```
https://map-tiles-staging.princeton.edu/mosaicjson/tiles/{z}/{x}/{y}?id=f75a1e91ade3427a82a109d321d47cbf
```

**Comment by eliotjordan** [comment]
Confirmed that TiTiler serves tiles in XYZ format.

**Comment by eliotjordan** [comment]
URI for the Key:

```
https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
```

**Comment by tpendragon** [comment]
Updated this issue to use tilejson instead of xyz.

**Comment by tpendragon** [comment]
I'm pulling this issue out of the work cycle - we're using the XYZ in geoblacklight, so this is just indexing that won't be used.

**Comment by tpendragon** [comment]
In fact, I'm closing it.
