### ISSUE TITLE
Handle both collared and un-collared raster images in a RasterSet

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#4867]
For certain types of raster data (georeferenced scanned maps - e.g. topgraphic map sets), the maplab has two types of data product that they want archived into Figgy:

1. The full georeferenced image including the collar (anything that isn’t part of the ‘map’ itself; border, compass, title, publishing info etc..)
1. A cropped image where the collar is removed.

The un-collared image is what is needed for creating a mosaic service.

Core issue: How do we ingest both data types, link them to together, and make them available for discovery?

**Comment by hackartisan** [comment]
There's a third file which is the initial scanned map, yes? We need to articulate the relationship there, as well. Will it continue to use the parent / member structure that is currently in use?

We should document whatever we end up with in https://github.com/pulibrary/figgy/blob/a73d0efd1225c4fce13003e4354c1d4877b9b640/docs/use_cases.md

**Comment by tpendragon** [comment]
Closed by #4929, #4890, #4893, #4889, and #4895
