### ISSUE TITLE
Create document describing the TiTiler architecture

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#4883]
1. Add a document describing the TiTiler architecture to the docs folder
2. Copy the sequence diagram image to the docs folder and link to it in the folder

https://github.com/pulibrary/figgy/issues/4770#issuecomment-993914941

Priority for sudden justification:

Newer vector datasets in Figgy don't have WMS links in their references. Users can't preview the data in Pulmap.

**Comment by hackartisan** [comment]
Work started in https://github.com/pulibrary/figgy/pull/5052
