### ISSUE TITLE
ScannedMaps with raster resources should have IIIF and mosaic web service endpoints.

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#4898]
To support new mosaic workflow.

Close this ticket when MapSet records have the mosaic web service indexed.

**Comment by thanyabegum** [comment]
@eliotjordan What's the IIIF service referenced in the title? Is there something more than WMTS?

**Comment by eliotjordan** [comment]
@thanyabegum Resources with IIIF services (typically scanned map) get a IIIF manifest link in Pulmap. 
![Screen Shot 2022-01-24 at 2 34 00 PM](https://user-images.githubusercontent.com/784196/150860481-716bcbf2-bb81-4266-8007-a248804f63e1.png)

**Comment by hackartisan** [comment]
@eliotjordan that one should already be in place, though, right?

**Comment by eliotjordan** [comment]
Yes, it should.

**Comment by hackartisan** [comment]
Maybe we should put an accessor for that query in the resource decorators for scanned maps and raster resources

**Comment by hackartisan** [comment]
closed by #4958
