### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `source' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4902]
## Backtrace

    line 33 of [PROJECT_ROOT]/app/services/dao_updater.rb: link_digital_object
    line 15 of [PROJECT_ROOT]/app/services/dao_updater.rb: update!
    line 6 of [PROJECT_ROOT]/app/jobs/update_dao_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/83624578)

**Comment by thanyabegum** [comment]
Rescue the error and send a notification to Honeybadger saying:
- If the source metadata identifier looks like a component id (e.g. MC001), talk to the product owner
- Otherwise, ask on the figgy slack channel if anyone recognizes what's going on
