### ISSUE TITLE
Cannot access playlist

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4915]
## Backtrace

    line 11 of [PROJECT_ROOT]/app/helpers/file_proxy_helper.rb: block in proxies_with_recording_data
    line 8 of [PROJECT_ROOT]/app/helpers/file_proxy_helper.rb: map
    line 8 of [PROJECT_ROOT]/app/helpers/file_proxy_helper.rb: proxies_with_recording_data

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/83689496)

Sudden priority justification:
Dan is preparing this playlists for the first weeks of a class which has just started. The playlist needs to work.

**Comment by hackartisan** [comment]
There was an orphan fileset whose proxy was a member of the playlist. I deleted the fileset but then I also had to delete the proxy. Once they were both deleted the playlist looks healthy and loads its show page.
