### ISSUE TITLE
Allow creating a new folder from the show or edit pages of ephemera folder

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#492]

**Comment by tpendragon** [comment]
The comment that spawned this was:
```
c) Both Save and Save and Create Another (folder) kicks me into the View mode, from which I can edit the folder, but to create a new folder, I have to go back to the original box number. Would it be possible to install a workable Create New Folder button in the Edit and the View mode?
```

I went and tried "save and create another", and I think the problem is it's copying over title and barcode and there's no flash message, so it's unclear that it's actually creating another one.

**Comment by escowles** [comment]
I think the main issue is that when you save a folder, you go to the show page, where there isn't a button to create a new folder.  You have to go back to the box to create another folder.

The set of buttons on the edit form is already pretty crowded, so I'm not sure how to fit another button there.  But there's plenty of room on the show page to just add a button to create another folder in the same box.

**Comment by tpendragon** [comment]
I think both are issues. "Save and Create Another" is super confusing when you hit it.
