### ISSUE TITLE
Cannot create new ephemera folders

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#493]

**Comment by tpendragon** [comment]
Templates were broken, but I can't reproduce this. Moving back to backlog - we'll have to talk to them.

**Comment by escowles** [comment]
Agree — I just removed myself from the admin group on staging, and I was able to create a new ephemera folder without issue.  I think we should screen-share to see what's going on.

**Comment by escowles** [comment]
I'll meet with Gabrielle tomorrow at 2pm EDT, and I will update this ticket with more info.

**Comment by escowles** [comment]
Verified with Gabrielle that she can now create EphemeraFolders
