### ISSUE TITLE
Folders which are not "Complete" and whose box is not marked "all in production" should not show up in LAE front-end and should be unavailable to users without permission.

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#494]
Visibility: It looks like all folders are "Open to the world." We can manually make them "Private" until the images arrive. After that, would it be possible to identify all the folders designated as private without having to look for them folder by folder? If not, is there a feature we could add?

**Comment by escowles** [comment]
Hide folders until the box is completed

**Comment by hackmastera** [comment]
Is 'completed' a workflow state on a box?

**Comment by escowles** [comment]
Sorry, wrong terminology: this should be `all_in_production`

**Comment by hackmastera** [comment]
application should treat folder visibility as `"restricted"` unless its containing box has state `all_in_production`

**Comment by hackmastera** [comment]
I think this can be done by overriding `enforce_show_permissions` in the catalog controller, once #524 is resolved.

https://github.com/samvera/hydra-head/blob/7a911e54a7cc0c49ca0e9cc8da1c6d47f9a467bb/hydra-core/app/controllers/concerns/hydra/catalog.rb#L9

**Comment by hackmastera** [comment]
scratch that previous comment; this should be indexer logic. Boxes should then reindex all member folders on save if the state has changed.

**Comment by jrgriffiniii** [comment]
I must test #548 against [pulibrary/lae-blacklight](https://github.com/pulibrary/lae-blacklight) before it is prepared for a review, but currently it works exclusively with an additional Indexer (`blacklight-access_controls` is used to establish a pattern within https://github.com/samvera-labs/valkyrie/blob/master/valkyrie/lib/valkyrie/indexers/access_controls_indexer.rb in which `read_groups` is used to manage access controls for any given Resource).
