### ISSUE TITLE
Consider making FileAppender raise an error again, rather than swallowing them

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4946]
If the FileAppender errors right now, we end up with a broken resource and nobody knows.

Problematic code:

https://github.com/pulibrary/figgy/blob/9c92d2359e441fb383afe3f30421bd3e4a2de06f/app/services/file_appender.rb#L131-L134

## Sudden Priority Justification

Ingests are failing and not fixing themselves, and in cases where there are hundreds of pages it's very easy to miss.

**Comment by tpendragon** [comment]
Eliot and I poked around a little, and this is happening fairly often. We found at least two cases where the derivative file failed to upload to S3 and the job happily succeeded, resulting in no IIIF display for that image.

**Comment by tpendragon** [comment]
I think you'd end up with orphaned binaries, but no database entries. That's a good concern though.

I'm concerned about more network-related issues causing a bunch of broken files that could have been automatically fixed more than I am some disk space being used, I think? You're right though that it depends on how often this kind of thing happens.

**Comment by hackartisan** [comment]
Hm. If we're going to have orphaned binaries, then maybe I'd rather have them attached to orphaned database entries.

**Comment by tpendragon** [comment]
I'm behind your suggestion - rescue and notify Honeybadger and keep an eye on it. If we're finding that we're constantly going in and manually digging up files to add because of network issues or something we should consider letting it all fail and just paying the cost of stranded binaries.
