### ISSUE TITLE
Cloud fixity checks not running

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4954]
There are no reported successes in the fixity dashboard since 01/4/22 - there should be new ones every day.

**Comment by tpendragon** [comment]
We can look at this during the upcoming preservation work cycle.

**Comment by eliotjordan** [comment]
- Fixed an issue with a new rake command namespace on the pubsub worker service definition.
- Deployed update with Ansible and worker spun up 25K UpdateFixityJobs.
- Jobs completed and the Fixity dashboard shows updated events.

Closing in favor of https://github.com/pulibrary/princeton_ansible/pull/3527
