### ISSUE TITLE
Download and ingest Google Books books

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#496]

**Comment by tpendragon** [comment]
Huh?

**Comment by escowles** [comment]
Roughly 300k of Princeton's public domain books were scanned by Google and we can download them from Google Books.  There's not much of an API for that, but we can probably script the conversion and download process, and then it would be pretty easy to load them into Figgy.

**Comment by tpendragon** [comment]
Lower priority than PUDL or Millberg ingest.

**Comment by mzelesky** [comment]
Why not download them from the source (Voyager)?

**Comment by escowles** [comment]
@mzelesky This is downloading the page images, not the metadata — so we need to get them from Google.

**Comment by kelea99** [comment]
@cwulfman , can you look into this?
