### ISSUE TITLE
 Save and Ingest for MVWs is not working for Digital Studio

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4970]
### Summary
The digital studio is unable to utilize the save and ingest function (perhaps tied to bulk ingest) for MVWs.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is hindering, but not ceasing work in the digital studio. It is certainly slowing work down.

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked_
The amount of MVWS needing ingest from the studio moves this up to a high priority due to daily workflows and needs for multiple departments. 

### Expected behaviour
Properly staged ingests from studio server should ingest as MVWs.
### Actual behaviour
As of 2/1, figgy ingests record but no images. Workaround is manual attachment of volumes to ingested record.
### Steps to reproduce behaviour
Stage MVW from DPUL directory on studio share and use "save and ingest".

**Comment by tpendragon** [comment]
This is linked to this honeybadger issue: https://app.honeybadger.io/projects/53391/faults/83771929
