### ISSUE TITLE
Provide useful error message when bulk update fails

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4988]
How can we ensure a user knows their bulk update did not succeed?

RuntimeError: Bulk update failed for batch ["aa19d5f7-10eb-4b35-b35f-af06f0c62525", "d7279971-6786-485c-9b93-42a2905e1ad0", "5b980b38-0455-4b3d-9659-ddd64ce98507", "cf8ab88a-3781-4afd-810a-399d265224f7", "5d9d2f3c-c9c5-468e-835e-d52d1714b661", "5da68972-cc9a-461e-a6db-2cfd3e7c72fd", "ec86e028-21c9-4ae9-9d09-cf6c9045f10c", "2a1e61b0-9c8a-49c2-a62a-00696ed101ab", "3b11211b-ca1d-4983-b3d3-83fdf434f419", "2f939e92-208e-4aef-b5a1-30d803fdae89", "78792880-024b-4fe6-9884-27a620502e32", "11b0ed43-70b2-4738-a44b-d2ee9dae92dc", "3d55f8d2-f52c-4180-8188-2e4828def98c", "1b9acd8b-eece-44b8-b808-22dc27c50bc7", "cb033c43-8e0c-44f7-8968-b06362fd6dca"] with args {:mark_complete=>false, :append_collection_ids=>["bc89f42f-d1ee-4338-80bc-a95b036024e4"]} due to invalid change set on resource d7279971-6786-485c-9b93-42a2905e1ad0

## Backtrace

    line 16 of [PROJECT_ROOT]/app/jobs/bulk_update_job.rb: block (2 levels) in perform
    line 5 of [PROJECT_ROOT]/app/jobs/bulk_update_job.rb: each
    line 5 of [PROJECT_ROOT]/app/jobs/bulk_update_job.rb: block in perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/80314410)

```
/opt/figgy/releases/20220209221635/app/jobs/bulk_update_job.rb:16:in `block (2 levels) in perform'
/opt/figgy/releases/20220209221635/app/jobs/bulk_update_job.rb:5:in `each'
/opt/figgy/releases/20220209221635/app/jobs/bulk_update_job.rb:5:in `block in perform'
/opt/figgy/releases/20220209221635/app/change_set_persisters/change_set_persister.rb:132:in `block (2 levels) in buffer_into_index'
/opt/figgy/releases/20220209221635/app/change_set_persisters/change_set_persister.rb:185:in `with'
/opt/figgy/releases/20220209221635/app/change_set_persisters/change_set_persister.rb:131:in `block in buffer_into_index'
/opt/figgy/releases/20220209221635/app/adapters/indexing_adapter.rb:94:in `block (2 levels) in buffer_into_index'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sequel-5.49.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sequel-5.49.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sequel-5.49.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sequel-5.49.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sequel-5.49.0/lib/sequel/database/transactions.rb:195:in `transaction'
/opt/figgy/releases/20220209221635/app/adapters/indexing_adapter.rb:93:in `block in buffer_into_index'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/valkyrie-3.0.0.pre.beta.1/lib/valkyrie/persistence/buffered_persister.rb:41:in `with_buffer'
/opt/figgy/releases/20220209221635/app/adapters/indexing_adapter.rb:92:in `buffer_into_index'
/opt/figgy/releases/20220209221635/app/change_set_persisters/change_set_persister.rb:130:in `buffer_into_index'
/opt/figgy/releases/20220209221635/app/jobs/bulk_update_job.rb:4:in `perform'
```

```
        "args" => {
          "mark_complete" => false,
          "append_collection_ids" => ["bc89f42f-d1ee-4338-80bc-a95b036024e4"],
          "_aj_symbol_keys" => [
            "mark_complete",
            "append_collection_ids"
          ]
        },
```

**Comment by tpendragon** [comment]
Maybe we should kick off some sort of email notification on completion?

**Comment by kelea99** [comment]
@hackartisan, I kept it basic and similar to that of the weekly collection report emails. Editing and suggestions most welcome. 

### Bulk Update Fail

- Bulk update failed for XX Resource(s) in batch [LINK].  You received this email because you initiated a bulk update for these Resource(s). 

### Bulk Update Success

- Bulk update was successful for XX Resources(s) in batch [LINK]. You received this email because you initiated a bulk update for these Resource(s).
