### ISSUE TITLE
Broken link to a manifest in Kennan Papers (MC076)

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#4992]
In https://figgy.princeton.edu/collections/d1887238-ac91-4ea4-a7e3-285d69d58c04/manifest
```
    {
      "@context": "http://iiif.io/api/presentation/2/context.json",
      "@type": "sc:Manifest",
      "@id": "https://figgy.princeton.edu/concern/scanned_resources/923c73e9-0d8d-4958-bbaf-1c5e0bd5074e/manifest",
      "label": [
        "1970-1973"
      ]
    },
```
Trying access the manifest returns a 404 error.
https://figgy.princeton.edu/concern/scanned_resources/923c73e9-0d8d-4958-bbaf-1c5e0bd5074e/manifest

**Comment by escowles** [comment]
That's weird — I can see and edit the ScannedResource (and the images show up in the file manager): https://figgy.princeton.edu/catalog/923c73e9-0d8d-4958-bbaf-1c5e0bd5074e

But I get a 404 when I try to access the manifest, and it doesn't display in the object or in the finding aids.
