### ISSUE TITLE
Cannot create new scanned resource

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5004]
[Figgy/production] ActionView::Template::Error: undefined method `>' for false:FalseClass

to replicate, go to the front page and click Scanned Resource > Add new

## Backtrace

    line 3 of [PROJECT_ROOT]/app/views/records/edit_fields/_member_of_collection_ids.html.erb: sort_by
    line 3 of [PROJECT_ROOT]/app/views/records/edit_fields/_member_of_collection_ids.html.erb: _app_views_records_edit_fields__member_of_collection_ids_html_erb___3695333516981878466_27418840
    line 3 of [PROJECT_ROOT]/app/views/base/_form_metadata_inner.html.erb: block in _app_views_base__form_metadata_inner_html_erb___3560612377366513516_27418700

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/84371050)

Sudden priority justification: staff cannot add new resources to figgy

**Comment by hackartisan** [comment]
I tried to replicate locally but was unable to

**Comment by hackartisan** [comment]
it's also not a problem on staging.
