### ISSUE TITLE
"Edit this scanned resource" is throwing "sorry, something went wrong" error

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5006]
### Summary
Steve Ferguson made us aware of this. When we try to go into "edit scanned resource" within figgy as a Figgy user, we get a "We're sorry, something went wrong" Message (see screenshot)

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Work is halted when doing anything for collections within that edit window.
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
 It is a fundamental step of the Lapidus Worfklow, that is on deadline for June.
### Expected behaviour
As a user, when I click on "edit scanned resource", I expect to see options to add bib/component id, collection, copyright, visibility,etc.  
### Actual behaviour
When I click on edit scanned resource i get the error in the screenshot below
### Steps to reproduce behaviour
Go to: https://figgy.princeton.edu/catalog/c4c35b0d-c2d3-4948-a7fd-711bd2443251
Click on "edit this scanned resource"
tadaa
### Screenshots
![Screen Shot 2022-03-04 at 10 33 11 AM (2)](https://user-images.githubusercontent.com/45043014/156792949-ca8e19fc-5e20-4789-ba9f-e2cde8fb43b2.png)

**Comment by tpendragon** [comment]
We updated to Ruby 2.7 yesterday which brought with it an RDF minor version upgrade, which broke sorting RDF literals along with strings. There are two collections with titles that are `RDF::Literals`, so this is breaking (see #5004.) The fix is to just roll back the version of RDF for now and add a test to replicate.
