### ISSUE TITLE
Ezid concurrency issues

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5017]
The BulkUpdateJob sent too many concurrent requests to the EZID service. Is there anything we can or should do about this?

## Backtrace

    line 30 of [PROJECT_ROOT]/app/services/identifier_service.rb: mint_identifier
    line 35 of [PROJECT_ROOT]/app/services/identifier_service.rb: assign_new_identifier
    line 9 of [PROJECT_ROOT]/app/services/identifier_service.rb: mint_or_update

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/82981113)

**Comment by eliotjordan** [comment]
Better message: "Couldn't mint ARK, please try again later"
