### ISSUE TITLE
Can't generate derivative for PDF

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5018]
[Figgy/production] Vips::Error: pdfload: unable to load page 1

https://figgy.princeton.edu/catalog/e4c5106e-bfe4-44d4-9249-9075b1a961ef

## Backtrace

    line 87 of [PROJECT_ROOT]/app/derivative_services/pdf_derivative_service.rb: block in convert_pages
    line 40 of [PROJECT_ROOT]/app/derivative_services/pdf_derivative_service.rb: each
    line 40 of [PROJECT_ROOT]/app/derivative_services/pdf_derivative_service.rb: each_with_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/84558468)

**Comment by eliotjordan** [comment]
Another similar error (can't load page 897):
https://app.honeybadger.io/projects/53391/faults/84558468
https://figgy.princeton.edu/catalog/94879b11-7229-4aa7-a6a9-6ea4ad1b8007

**Comment by sdellis** [comment]
Whoever takes this ticket should find out who the ingested is and let them know that there's a problem with their PDF file.

**Comment by kelea99** [comment]
@sdellis  this is a concert programs PDF. the fix should go to Dan Gallagher.

**Comment by tpendragon** [comment]
We're having a hard time getting a hold of Dan. I'll reach out to him again, and see if there's something he can do and if not inform him that we're going to be deleting this resource.

**Comment by tpendragon** [comment]
Dan fixed it.
