### ISSUE TITLE
Allow download of original PDF

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5020]
If the resource was uploaded as a PDF, downloading the pdf should short-circuit pdf generation and provide the original PDF.

Original question:

We have a large set of Chinese TOCs we would like to host somewhere, preferably Figgy.  But they are searchable PDFs and it’s important that this feature be preserved.  I know Figgy can do OCR for Chinese, but even at its best it will be a step down from the files in their original format.

This content isn’t really right for DSpace, so we are just trying to figure out where we can make these files available in their current format.

Sample file:
https://drive.google.com/drive/u/2/folders/1UCWTYy9OGpw2iUklm58ULjpPzGGed15N

Follow up with @tventimi 

## Success Criteria

When a user has permission to download a resource which was generated from a PDF they should have a link in the UV to download the Original PDF instead of the generated PDF.

**Comment by tpendragon** [comment]
DLS discussion on 03/22: We'd like to get this done at some point in the relatively near future just so folks don't upload this kind of content to DSpace or (especially) DSS, in alignment with the policy: (https://lib-confluence.princeton.edu/display/COM/Linking+External+Documents+to+Catalog+Records+and+Finding+Aids). That being said it's probably best resolved as "make people's lives better ticket" - nobody's work is being halted here and we have a lot of important sudden priority and maintenance tickets to get through.

We need one for this cycle, so I'll put it in this cycle. When Kim's back if she has a better candidate for the slot for this cycle we can do that.

**Comment by hackartisan** [comment]
This functionality already exists if you go to the catalog route rather than the concerns route.

https://github.com/pulibrary/figgy/blob/43a72978a46b7a763218a1af5f2ef57b868215af/app/controllers/catalog_controller.rb#L222-L225

**Comment by escowles** [comment]
> Presumably if these items are eligible for download we don't need to provide cover pages for these PDFs?

Yes, the main use cases for providing downloads of the original PDFs are all cases where Princeton owns the copyright (concert programs, curatorial notes, etc.) or where the items are clearly fair-use (tables of contents).

> This functionality already exists if you go to the catalog route rather than the concerns route.

Looking at the Ability class, I think this likely means that we need to add some logic to say that PDF source files are downloadable, maybe here: https://github.com/pulibrary/figgy/blob/main/app/models/ability.rb#L274
