### ISSUE TITLE
Remove a bunch of map resources

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5025]
These were ingested from a directory below the intended directory, so they created a whole bunch of unrelated resources. 

They were ingested again as https://figgy.princeton.edu/catalog/f97e8e8b-5bfe-466e-8c67-e17be912033e. Once that ingest is complete we need to delete all the ones that have source metadata IDs that are the titles of the children of that resource (should be all the broken no parent ones.)

**Comment by tpendragon** [comment]
Done.

Looked like this:

```ruby
qs = ChangeSetPersister.default.query_service
correct = qs.find_by(id: "f97e8e8b-5bfe-466e-8c67-e17be912033e")
children = Wayfinder.for(correct)
bad_resources = qs.custom_queries.find_by_source_metadata_identifiers(source_metadata_identifiers: children.flat_map(&:title))
bad_resources.each do |bad_resource|
  change_set = ChangeSet.for(bad_resource)
  ChangeSetPersister.default.delete(change_set: change_set)
end
```
