### ISSUE TITLE
Saving MapSet mosiac raises exception

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5030]
NoMethodError: undefined method `raster_set?' for #<ScannedMapDecorator:0x0000560ebc4c6a00>

## Backtrace

    line 9 of [PROJECT_ROOT]/app/jobs/mosaic_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/84754557)

**Comment by eliotjordan** [comment]
I think we can remove this check as the methods that call this job do their own checks to confirm that the resource is a mosaic.

https://github.com/pulibrary/figgy/blob/48b223704bf82706e0316c934a40d63c02411005/app/jobs/mosaic_job.rb#L9
