### ISSUE TITLE
Adding a collection with a nonexistent source_metadata_id breaks the scanned resource form

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5042]
To replicate
* create a collection and give it a source metadata id that looks like a component id but isn't a real component id. don't forget you have to fill in the slug field.
* Go to the new scanned resource form

This error was discovered when a collection was made from an unpublished finding aid. Once the finding aid was published and the metadata synced it resolved. https://figgy.princeton.edu/catalog/2c11ef96-c7ba-4756-b7c5-d30a97e13193

Resolve either by not allowing the object to be created (this was expected behavior and may be preferred) or by ensuring collections with nil titles are filtered out just before the location of the error.

Honeybadger:
https://app.honeybadger.io/projects/53391/faults/84371050

```

1: <% if !resource_has_parents?(f.object.resource, params) || f.object.kind_of?(EphemeraFolderChangeSetBase) %>
    2:   <%= f.input :member_of_collection_ids,
    3:               collection: @collections.sort_by(&:title),
    4:               label_method: :title,
    5:               value_method: :id,
    6:               input_html: { multiple: f.object.multiple?(key) },
```
```
app/views/records/edit_fields/_member_of_collection_ids.html.erb:3:in `sort_by'
app/views/records/edit_fields/_member_of_collection_ids.html.erb:3:in `_app_views_records_edit_fields__member_of_collection_ids_html_erb__1137239044168021665_605200'
app/views/base/_form_metadata_inner.html.erb:3:in `block in _app_views_base__form_metadata_inner_html_erb__3945062815367994064_603580'
app/views/base/_form_metadata_inner.html.erb:2:in `each'
app/views/base/_form_metadata_inner.html.erb:2:in `_app_views_base__form_metadata_inner_html_erb__3945062815367994064_603580'
app/views/base/_form_metadata.html.erb:4:in `_app_views_base__form_metadata_html_erb__2340373240580214423_603560'
app/views/base/_form.html.erb:7:in `block in _app_views_base__form_html_erb__2554498001300087046_603540'
app/views/base/_form.html.erb:2:in `_app_views_base__form_html_erb__2554498001300087046_603540'
app/views/base/new.html.erb:1:in `_app_views_base_new_html_erb___4234022672507813375_42183560'
```

**Comment by tpendragon** [comment]
If a finding aid ID is given that doesn't resolve it shouldn't allow the collection to be created.

**Comment by hackartisan** [comment]
The problem is that it's not getting the item from pulfa and then it reaches out to the legacy pulfalight url and gets a 301. the body of the 301 is just passed into a remote resource and the success check passes. 

The proper fix is to take out the fallback code. To do so there is at least one test which needs to be rewritten to use a new pulfalight fixture, however getting that fixture isn't currently possible due to pulibrary/pulfalight#799.

The test that needs to be replaced
https://github.com/pulibrary/figgy/blob/92738dbf585db1af573e48688ab38177c1793e6c/spec/services/pul_metadata_services/client_spec.rb#L41

Behavior that needs to be removed
https://github.com/pulibrary/figgy/blob/f5c4ab5907c80a99cef9f3f44b159e6da10dc20e/app/services/pul_metadata_services/client.rb#L15-L18

There's also some config we should update
https://github.com/pulibrary/figgy/blob/f5c4ab5907c80a99cef9f3f44b159e6da10dc20e/config/config.yml#L36-L37

**Comment by hackartisan** [comment]
I think https://app.honeybadger.io/projects/65922/faults/70813262/01G0Z3V85QDF2BFVN9AS39JF2W#notice-summary is also related. Once we fix this should we try resolving that?
