### ISSUE TITLE
`logo` property in IIIF 3 manifests should be an array.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5046]
This is stopping our AV manifests from rendering in other AV viewers (specifically https://samvera-labs.github.io/bloom-iiif/)

See https://github.com/IIIF-Commons/vault for a related issue.

**Comment by hackartisan** [comment]
Here's a link to a recording resource:

https://figgy.princeton.edu/catalog/f3fe7e9a-256f-4d63-8b57-84a843071ec1
Here's it's presentation v. 3 manifest that shows the logo value is a string and not an array: https://figgy.princeton.edu/concern/scanned_resources/f3fe7e9a-256f-4d63-8b57-84a843071ec1/manifest

Here's the clover demo viewer: https://samvera-labs.github.io/clover-iiif/docs/viewer/demo -- there are some errors in the javascript if you look at the developer console, but it doesn't mention the logo. But we probably should still fix this.
