### ISSUE TITLE
Lapidus Item not pulling metadata using MMS into an existing scanned resource.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5059]
### Summary
Reported by Steve Ferguson. He is attempting to hook 99114254593506421 to [Lapidus_11425446 ](https://figgy.princeton.edu/catalog/7f9dcc40-71a3-4458-9878-5310c11a721a). It times out (he waited over 20 minutes). @eliotjordan also tried this in staging. He is able to pull the metadata using the mms id into a new record but he is also seeing production Figgy hang when updating the current record.
Online catalog is not showing the metadata: https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=99114254593506421

Bibdata is: https://bibdata.princeton.edu/bibliographic/99114254593506421

Figgy Staging is: https://figgy-staging.princeton.edu/catalog/c3dec848-8ab6-4fd6-91f3-8e916d1fed21

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Work is stopped for Steve on the Lapidus project if he cannot hook metadata to the digital surrogates.He is also on hard deadline for June of this year, when all items are to be completed and in DPUL. 
### Priority recommendation

- [x] asap (see below)
- [x] within the next 3 weeks (see below)
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
**I am on the fence with this one. If it is not affecting more than this one item, I would say get to it within the next three weeks. If this is stopping what Steve (as well as others) will be needing in order to make objects discoverable, then I would like to move it to asap. 
### Expected behaviour
When I go to edit scanned resource, add "99114254593506421" to the source metadata identifier field, and click "save" I expect the metadata from the MMS id to populate the record shortly thereafter

### Actual behaviour
When I go to edit scanned resource, add "99114254593506421" to the source metadata identifier field, and click "save", figgy hangs in waiting forever, never saving.

### Steps to reproduce behaviour
Go to: https://figgy.princeton.edu/catalog/7f9dcc40-71a3-4458-9878-5310c11a721a
click on edit scanned resource
Add: 99114254593506421 to Source Metadata ID field
Click save
wait....

**Comment by hackartisan** [comment]
It looks like this went through.

**Comment by kelea99** [comment]
What was the issue, @hackartisan ? Anything we should look out for in the future?

**Comment by hackartisan** [comment]
@kelea99 it was synced when we went to look at it yesterday so I'm not sure. We will try to look more if it happens again!
