### ISSUE TITLE
Generate Figgy ark  report for selected Derrida Items

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5071]
### Summary
Jennifer Baxmeyer and Don  Thornbury in SC  are needing a figgy  ark report  generated for Derrida items. The items currently have Component IDs. They have provided a [NEW SPREADSHEET](https://docs.google.com/spreadsheets/d/1GgNi8be-vOZRpUdVoEK3G3RYNw6Zwu6iH0KKoTZpZT0/edit?usp=sharing) containing the component ID and the figgyid.

Reason: Don is now creating MARC records for this collection. He  will be  using the information to generate 856 fields in the MARC records that will be created.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not stopping  or hindering work. The arks will need  to be added  at some point and it would be helpful to  get those in while don is working on the MARC.

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks - Can be negotiated if needs be.
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
While not an asap/hard deadline request, it will be helpful to get these in the MARC  in a timely  manor. Speaking with Jennifer,within  3 weeks would work great for their needs

**Comment by kelea99** [comment]
We got the new spreadsheet, @eliotjordan . I added the link to it here.   Figgy IDs and Component IDs look  like they match up

**Comment by eliotjordan** [comment]
@kelea99 Here's the ARK report:

[Figgy856-ARK.csv](https://github.com/pulibrary/figgy/files/8671569/Figgy856-ARK.csv)

**Comment by kelea99** [comment]
Thank you so much! Ark report has been uploaded into google drive and shared with Jennifer and Don
