### ISSUE TITLE
File appender failure notices are too frequent

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5078]
https://app.honeybadger.io/projects/53391/faults/84134442

It takes a lot of time to triage this notice
* copy the resource id
* navigate to it in figgy
* if it's a resource, click the file manager and browse through children clicking "regenerate" button as needed
* if it's a file set (usual case), click through to parent and its file manager
* if it's a file set with no parent link, go into prod console to see if it has a parent, potentially delete the file set

It may be sufficient to update the notice with more info (like a link to the file appender page of the parent if it's a file set -- note that sometimes it's a resource). Or maybe we need to think about whether we can find some circumstances under which we can retry.

The underlying errors appear to vary. examples:
* NetTimeout
* SSL error
* "Resource temporarily unavailable @ rb_sysopen"
* multipart upload failed: Your socket connection to the server was not read from or written to within the timeout period.

Let's use this space at least for now to record which underlying error we saw and whether we found a resource with derivatives that failed to generate, a resource that had been deleted, or a resource that looked fine (these cases may have been resolved by the ingester already). Maybe then we can identify some cases where it makes sense to do a retry.

## Fix Proposal

This Honeybadger notice and rescue in https://github.com/pulibrary/figgy/blob/792ac531a5c59187578073a6d6c37af6e60d458d/app/services/file_appender.rb#L126-L131 was added in response to flakiness ingesting from Google Drive. We don't ingest from Google Drive anymore, and most of the errors that happen here are fixed by a manual retry from the developers. If we remove that block of code, Figgy will retry by itself, meaning most times we won't have to do anything.

Let's remove it.

**Comment by tpendragon** [comment]
Relevant issue: https://github.com/pulibrary/figgy/issues/4946

Do you think we're at the point of just letting this error again?

**Comment by hackartisan** [comment]
I think it might be possible to sort out some different kinds of errors a bit better.

**Comment by hackartisan** [comment]
One thing I notice is that even when there are failed derivatives for these resources, there's not the banner message "x/y derivatives generated" or whatever it says that cues ingesters to know there may be an issue. If they're looking for that and not scanning through the actual file list or viewer they won't notice these problems.

Error analysis.

- "multipart upload failed" (note nested Net::OpenTimeout errors): Needed derivatives regenerated. Steps I took: Use the resource id to get to the resource in figgy, click through to its parent, go to file manager, click "regenerate derivatives" button for the corresponding file.
  - some of these were fine; may have been regenerated by ingester
- Net::OpenTimeout
  - one was fine (although it may have been regenerated by ingester)
  - some others needed derivatives regenerated
- "multipart upload failed: The difference between the request time and the current time is too large.": needed derivatives regenerated
- "SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello": needed derivatives regenerated
- "multipart upload failed: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello": needed derivatives regenerated
- "execution expired": needed derivatives regenerated
- "multipart upload failed: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.": needed derivatives generated; several of these
- "multipart upload failed: Connection reset by peer": needed derivatives regenerated
- "The AWS Access Key Id you provided does not exist in our records.": this stemmed from key rotation event but nothing needed to be regenerated. not sure if someone else did that.
- "multipart upload failed: Failed to open TCP connection to iiif-image-production.s3.amazonaws.com:443 (getaddrinfo: Temporary failure in name resolution)"
  - needed to be regenerated
 
This one was not something I had seen before.
- multipart upload failed: undefined method `read' for #<IngestableFile:0x0000555f3e839558>
  - created https://github.com/pulibrary/figgy/issues/5352

**Comment by tpendragon** [comment]
Okay I think there are two places where this error could happen:

1. During ingest, where there are LOTS of `files`. If we raise an error here, we'll end up with a bunch of orphaned files on disk without a way to retry just a subset of files. I don't know how to do that without re-architecting the file append infrastructure to work like ServerUpload, where all things are PendingUploads that can be serialized from a Valkyrie ID.
2. During derivative creation, where a single file is being uploaded to a cloud storage provider.

Based on the errors above, I think #1 never happens. Or at least, not often enough for us to have a record of it.

#2 happens a -lot-.

So, my proposal: Let's rescue the error, and if the resource it's appending to is a FileSet, then it's probably a derivative and we want it to fail, so re-raise as a generic FileAppender error we can track in one place in Honeybadger. Otherwise do the honeybadger notify.

This should let the majority of our derivative errors actually fail and restart.
