### ISSUE TITLE
Tiffs are bad for files 153 through 164 of microfilm_06074_reel_12

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5082]
The derivative generation is failing, seems to be bad tiffs.

https://figgy.princeton.edu/concern/scanned_resources/24ffd824-9a43-4f70-9f20-32ef442dd2ad/file_manager

https://app.honeybadger.io/projects/53391/faults/80554711

**Comment by kelea99** [comment]
Contacted Colleen and @roelmoon . they still have the original scans on the server and are reuploading the problem issues.

**Comment by hackartisan** [comment]
@kelea99 thank you! I think that's all we can do - I'll close this issue.
