### ISSUE TITLE
Add warnings about harmful content to our viewer

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5090]
The Harmful Content Working Group provided the following recommendations:

> The Harmful Content Working Group recommends that PUL implement cover images and/or warnings for harmful content in its collections. This implementation will be done on a project basis for collections or materials that are known to include harmful content as well as on an ad hoc basis as content is identified by staff or library users. Access mediation will not be used to restrict or limit access to content, only to provide a buffer in the event that a user would prefer not to view harmful or distressing content. 

> The working group recommends developing a feature in Figgy that allows for the application of a cover image with a warning statement that users click through to confirm they are comfortable viewing content that has been identified as harmful. We propose the following specifications and workflows, though it should be noted that certain details will need to be reviewed and approved by key stakeholders, notably IT staff, metadata specialists, public services staff, and curators and selectors. In addition to DPOG, the Working Group recommends that DSSG and the Inclusive and Reparative Metadata Working Group also review these recommendations and determine how this work will be implemented moving forward, including any revisions to our recommendations that may be appropriate. We also recommend that regular user testing be conducted once these features are implemented to see if and how they are helpful to researchers. 

> Specifications:
Cover image: Greyed out/blurred image; in cases where a Figgy record includes multiple images, only the first image would be blurred out.
“View Content” button that users can click if they choose to access the content
Content warning: 
Preferred: specific note included in descriptive records (see below); or
Boilerplate note, such as: “Image(s) depict harmful or distressing content.”
In addition, the warning should also include the following: “For more information about harmful content in Princeton’s collections, see [link to full statement]. 

## Blockers

- [x] Specification on how we can tell when a component in ASpace has harmful content.
   * Perhaps @faithc or @ccleeton know this already, as Pulfalight POs, and can fill us in?
- [ ] Specification on how we can tell when a record in Alma has harmful content.
   * @tpendragon can talk to Jennifer Baxmeyer and see if CAMS has a standard for this.
- [x] Add harmful content flag to JSON output by FindingAids.
- [ ] Add harmful content flag to JSON output by Bibdata.

## Research Needed

- [x] Create a wireframe for what this interaction looks like.
- [x] Come up with an implementation plan.

## Sudden Priority Justification

The output of this group is in direct support of the library's mission, vision, and north star statements. We should ensure we get it in place as soon as possible in an effort to support that effort and ensure it's respected.

## ArchivesSpace Implementation

ArchivesSpace users will add a `<scopecontent>` note (normally labeled in Pulfalight as `description`) with the label "Content Warning".

Pulfalight will index and display the label "Content Warning" (https://github.com/pulibrary/pulfalight/issues/817 is a ticket making it so labels in ASpace will display in the front-end, so if there's two scopecontent notes one will say "Content Warning" and one will say "Description")

Pulfalight will add content warnings to its JSON output

Figgy will import content warnings as imported metadata and understand that it's an item that should display a warning.

**Comment by tpendragon** [comment]
Reached out to Jennifer today and she said they'd talk about it and get back to me.

**Comment by tpendragon** [comment]
Current proposal for ASpace is to add a scope/content note with a harmful content note heading, but is dependent on displaying the scope content header label.

**Comment by faithc** [comment]
Example: https://aspace.princeton.edu/staff/resources/3757#notes (Content Warning Scope Note); https://aspace.princeton.edu/staff/resources/3950#tree::archival_object_1448342

**Comment by faithc** [comment]
Relates to https://github.com/pulibrary/pulfalight/issues/817

**Comment by tpendragon** [comment]
We'll also need to support Ephemera content.

**Comment by tpendragon** [comment]
Comments from a discussion with Jon:

For Ephemera we'll probably need freeform text entry in addition to an option to select from a couple of boilerplate statements instead.

**Comment by escowles** [comment]
If we have several statements (e.g., one for harmful content, and a separate one for graphic content), would it be possible to display multiple statements? Or would we need to choose one per object to display?

**Comment by jpstroop** [comment]
I think it would be better to have multiple statements. Maybe in figgy it's a checkbox sort of experience, and so if you check the "graphic" box you get one statement. If you check the "offensive" box you get another, or both, but with separate headings. This contradicts what I was saying before, but I think it might scale better if we need to add other types of warnings--otherwise we would need to come up with statements for all possible combinations.

**Comment by tpendragon** [comment]
Kim had the idea that this could be a generic "click-through" feature, to also support click-through requirements for senior theses.

**Comment by escowles** [comment]
The other click-through use case I know about is the Council on Foreign Relations audio recordings, which have a click-through copyright acknowledgement.

**Comment by escowles** [comment]
Followup on the comments above about whether multiple statements can be displayed, or whether we'd need to have a combined statement for each desired permutation: Trey and I agreed that multiple statements would make the most sense, and I'll work with stakeholders to develop mockups/wireframes.

**Comment by escowles** [comment]
Draft mockup and statement language:
https://docs.google.com/presentation/d/1eNAiwQB4eMog7BQffaGQXmIPIPb-3UEEEmqXGmzLW4A/edit

There are currently two statements:
1. harmful content
2. explicit content 

But as noted above there are a few other use cases that may expand that to 3-5 statements.

**Comment by hackartisan** [comment]
Implementation notes: https://docs.google.com/document/d/1tpBHlK8knTsmT4MZjMqMUXiywj9iGvHWea5hHNUGQ6w/edit

**Comment by tpendragon** [comment]
Implementation tickets: https://github.com/pulibrary/pulfalight/issues/1195, https://github.com/pulibrary/figgy/issues/5490, and https://github.com/pulibrary/figgy/issues/5492

**Comment by tpendragon** [comment]
Implementing this for MARC records will mean adding a harmful_content tag to Orangelight if the right metadata appears (which CAMS hasn't decided on yet), so we may be able to create a ticket in Orangelight and leave implementation to DACS.

**Comment by tpendragon** [comment]
We think the work from here on is for DACS, to close this ticket communicate with them and see if that's correct and if there's a ticket to migrate this to.

**Comment by maxkadel** [comment]
[Slack message from Minjie](https://pulibrary.slack.com/archives/C04RPKK3UJW/p1682438921385479) - The 520 first indicator 4 is for "Content advice". See also https://www.loc.gov/marc/bibliographic/bd520.html

**Comment by escowles** [comment]
Jennifer confirmed we would want to share the harmful content warnings in 520s with OCLC/POD/etc.
