### ISSUE TITLE
Add "Remove from a Collection" to bulk edit functionality

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5101]
### Summary
_As a figgy user, I would like to remove items from a collection via the bulk edit feature in figgy. Sometimes I may accidentally add a lot of items to a collection  i did not intend to and manually editing each item would be cumbersome._ 
This is due to an actual use  case.  A user accidentally added a large number of items to a collection in figgy that they would like  removed. It would  be useful to give users the ability to  remove items from collections as well via the bulk edit feature. 
### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
There are no hard deadlines for this
### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize - Will discuss with DLS to prioritize as a team

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by tpendragon** [comment]
We might want to warn people if they're about to ungroup things which are grouped by the collection they're faceted by, because then they'll never be able to bulk edit those things again.
