### ISSUE TITLE
[Figgy/staging] NoMethodError: undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5119]
## Backtrace

    line 47 of [PROJECT_ROOT]/app/services/identifier_service.rb: metadata
    line 29 of [PROJECT_ROOT]/app/services/identifier_service.rb: mint_identifier
    line 35 of [PROJECT_ROOT]/app/services/identifier_service.rb: assign_new_identifier

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/85491177)

**Comment by hackartisan** [comment]
no info.
