### ISSUE TITLE
Figgy is not allowing me to make changes in structure manager and change the title to an EAL MVW

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5154]
### Summary
When I try to delete structure, i am able to delete and save. when i go back to structure manager, however, the changes I make were not saved. When I try to change the title in structure manager and save, i encounter the same thing.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This hinders work in processing microfilm for @tventimi  of EAL items

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
If our structure manager is seemingly saving but reverting back to its original state when figgy users navigate out of structure manager, it is tedious work that will be lost or potentially go unnoticed. 
### Expected behaviour
When I go to Structure manager and make changes within it - changing a title, deleting structure, adding structure. I expect those changes to save when i click "save" and navigate back to the main record.

### Actual behaviour
When I go to structure manager and make changes and click save. Changes are not held when i navigate out of structure manger to the main record.

### Steps to reproduce behaviour
Go to: https://figgy.princeton.edu/concern/scanned_resources/cfa08806-5a73-4920-9bcc-2c9df295dd38/structure
Delete the bottom structure that is blank at the bottom of the page.
Change a title
Click Save
Navigate out of structure manager
go back to structure manager and review items that were changed.

### Screenshots / Demos
https://drive.google.com/file/d/1NyZRUBHsc1e1Bx5BqBBt2hexnNkka8PX/view?usp=sharing

**Comment by kelea99** [comment]
FYI: I can no longer find this item in figgy with this id. but! I found another ingest of it: https://figgy.princeton.edu/catalog/644a1a07-94c8-4930-8033-2c773a182150
Perhaps it was deleted and reingested, @tventimi ?

**Comment by tventimi** [comment]
Thanks for looking into this.  Fortunately all of the same structural data
is present in this version.  But when I try to go to the structure manager
for the first volume, I get the "Something went wrong" error...

**Comment by hackartisan** [comment]
Fixed.
