### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5155]
- Fix the date and make the decorator method less brittle.

## Backtrace

    line 196 of [PROJECT_ROOT]/app/decorators/scanned_resource_decorator.rb: parse
    line 196 of [PROJECT_ROOT]/app/decorators/scanned_resource_decorator.rb: block in display_date_range
    line 196 of [PROJECT_ROOT]/app/decorators/scanned_resource_decorator.rb: map!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/86040579)

https://github.com/pulibrary/figgy/blob/957d7696653083554eebc11687a40af242dfa674/app/decorators/scanned_resource_decorator.rb#L196

```
    def display_date_range(date_value)
      dates = date_value.to_s.split("/")
      dates.map! { |date| Date.parse(date).year }
      dates.join "-"
    end
```

**Comment by hackartisan** [comment]
We don't know what resource this was.
