### ISSUE TITLE
Palmipsest TIFFs raise error during derivative creation

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5156]
I think there are derivative generation issues with some of the multispectral imagery.

https://figgy.princeton.edu/catalog/4fd9b528-1e73-415f-88ac-1f87946b9118

[Figgy/production] Vips::Error: TIFFFetchDirectory: Sanity check on directory count failed, zero tag directories not supportedTIFFReadDirectory: Failed to read directory at offset 202164936magick2vips: libMagick error:magick2vips: unable to read file "/opt/repository/files/c5/2c/f4/c52cf4ab961847afa0e024ed66ba07c2/PULPalimpsests_9979943233506421-FrontPastedown-600N_010_R.tif"

## Backtrace

    line 108 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: image_from_file
    line 98 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: vips_image
    line 82 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: run_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/80089019)

also https://app.honeybadger.io/projects/53391/faults/80121765

**Comment by eliotjordan** [comment]
@kelea99 Is this related to the multispectral work?

**Comment by kelea99** [comment]
Yes, @eliotjordan . This is the MSI stuff

**Comment by tpendragon** [comment]
I think this one might just be corrupt - I can't open https://figgy.princeton.edu/catalog/parent/529ae704-370f-4090-a50a-8d200b976e07/f6f03fc1-e494-4dd2-b027-526caaf0fd8b

**Comment by kelea99** [comment]
@roelmoon can you have a look at the TIF that was generated for this item? its: PULPalimpsests_9979943233506421-FrontPastedown-600N_010_R

**Comment by kelea99** [comment]
Roel It was dead on the isilon too. New tif has been staged for ingest

**Comment by hackartisan** [comment]
This file is still bad and is still attached to the resource.
