### ISSUE TITLE
Bootstrap 4: Unclaim button

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5178]
- “Unclaim” button/link needs styling of some sort

![Screen Shot 2022-06-14 at 11.57.32 AM.png](https://images.zenhubusercontent.com/5cba0acbb9c3ba7837d00c68/78ac82c7-de56-4dcb-a0ee-92bdfc4faedd)

**Comment by tpendragon** [comment]
Closed by #5181
