### ISSUE TITLE
naming convention for decorator methods that return decorated objects

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#518]
I like this idea from @tpendragon

**Comment by escowles** [comment]
👍  I'd much rather it be clear that you were getting decorated objects, and having a naming convention would also avoid clobbering any underlying methods, so you could still access the raw values if you wanted them.

**Comment by tpendragon** [comment]
The methods have the right name on the wayfinder, there are several `@TODO` comments in the decorators about methods which need to have their name changed to close this ticket.

**Comment by hackmastera** [comment]
close in favor of https://github.com/pulibrary/figgy/issues/2689
