### ISSUE TITLE
Upgrade: Archival media collection

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5185]
- Creation of an Archival Media Collection fails with a “We’re sorry something went wrong” message. (Using AC168_c02596 as the ID)

Comment (Eliot): This works for me. Worth trying again.

**Comment by hackartisan** [comment]
This works locally on latest branch. do `cp -r spec/fixtures/av/la_c0652_2017_05_bag staged_files/.` and use source_metadata_identifier `C0652`
