### ISSUE TITLE
Subject controlled vocabulary for Ephemera Folders doesn't expand/collapse.

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5190]
We used bootstrap-select to do this before, but the library's since changed and our old code is no longer working.

**Comment by tpendragon** [comment]
The vocab wasn't in staging, so I added it, but all the subject categories are showing up expanded and can't be collapsed.

**Comment by tpendragon** [comment]
Bootstrap-select has been upgraded and our old overrides in `app/assets/javascripts/bootstrap_select_dropdown.js` are no longer working.

I'm having a hard time fixing it - hiding the <li>s results in the select dropdown resizing wrong.

**Comment by hackartisan** [comment]
I think this may be working now. Here's what it looks like for me locally

![Screen Shot 2022-06-29 at 3.01.24 PM.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/965dbd72-930f-4f36-b08f-b7fad6054e12)

**Comment by hackartisan** [comment]
Oh wait they aren't grouped right.

**Comment by hackartisan** [comment]
I got as far as successfully replicating the issue, hooray
