### ISSUE TITLE
Ingest for All Underdogs Go to Heaven  failing

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5198]
### Summary
https://figgy.princeton.edu/catalog/f703e416-7902-4bfb-916c-a2ddd66a3123

Location on Isilon: PUDL -> AR.2021.030 -> All Underdogs Go to Heaven (Gamma Compensation Patch) - 1.18.21.mp4

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [x ] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by tpendragon** [comment]
Uploaded. https://figgy.princeton.edu/catalog/f703e416-7902-4bfb-916c-a2ddd66a3123

**Comment by tpendragon** [comment]
I had to ingest this from the command line via using the `disk_via_copy` StorageAdapter, adding this as an IngestableFile, and persisting/waiting for the copy to finish.

I THINK a bulk ingest would have worked here if the folder structure was set up right, but it wasn't. In the future we'll have to think about ways to pass the files to be added as a background job - copying files of this size takes too long.
