### ISSUE TITLE
Hitting the ephemera folder Save button twice creates duplicates

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#520]

**Comment by hackmastera** [comment]
what should be done? disable save with javascript after it's been clicked?

**Comment by tpendragon** [comment]
Rails should be doing that, some other JS is probably interrupting it.

**Comment by hackmastera** [comment]
cannot reproduce

**Comment by jrgriffiniii** [comment]
As was the case with @hackmastera , I failed to reproduce this on the `master` branch under the following conditions:
- Saving a new EphemeraFolder
- Saving a new (and subsequently creating another) EphemeraFolder
- Saving a new EphemeraFolder with "private" visibility

**Comment by jrgriffiniii** [comment]
Further, I also failed to reproduce this within the production environment

**Comment by jrgriffiniii** [comment]
On 11/29/17, @hackmastera and @escowles confirmed that the original reporter should be updated with our inability to reproduce the bug.
