### ISSUE TITLE
Rails 6 upgrade: Ephemera field "favorite terms" dropdown not presenting term options

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5225]
It should have dropdown functionality like the field in the edit form does.

manage ephemera project > controlled fields > edit

**Comment by hackartisan** [comment]
@kelea99 it's working, it's just that there are two vocabularies called LAE Ephemera in staging and one was empty. Attaching the other one revealed that the functionality is the same as on an edit page.

**Comment by kelea99** [comment]
Fantastic!! thank you.
