### ISSUE TITLE
Refresh Metadata for all items in "The Sid Lapidus '59 Collection on Liberty and the American Revolution"

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5227]
### Summary
Link to Collection: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=The+Sid+Lapidus+%2759+Collection+on+Liberty+and+the+American+Revolution&q=Lapidus

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
All metadata needs to be refreshed before launch/PR stuff in Fall. Needed because Alma sync isn't working.

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] DLS will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by hackartisan** [comment]
@kelea99 With the bulk edit feature now in place, can this be done via the UI and then closed?
