### ISSUE TITLE
methods in ephemera_folders_controller maybe not ready for boxless projects

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#523]
https://github.com/pulibrary/figgy/blob/master/app/controllers/ephemera_folders_controller.rb#L66

https://github.com/pulibrary/figgy/blob/master/app/controllers/ephemera_folders_controller.rb#L74

**Comment by escowles** [comment]
Not sure if this is the same issue or not, but I noticed last week that the form for boxless items doesn't use the controlled vocabularies attached to the project.
