### ISSUE TITLE
Archival Media Bag ingest issue

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5240]
Kelly is having trouble ingesting this bag into Figgy:
```
/archives_bd/bcadmin/mss/av_backlog/TC071/TC071_2022_06_bag_a
```

Processing raises an error here:
https://github.com/pulibrary/figgy/blob/a510ae807551bd713bee3d8e1ca0beda8df61a51/app/models/archival_media_bag_parser.rb#L218

**Comment by eliotjordan** [comment]
Kelly says within the next three weeks. 8/5/2022

**Comment by tpendragon** [comment]
We'll work this the maintenance week which starts 8/15. Confirmed with Kelly.

**Comment by tpendragon** [comment]
Same issue with

```
/mnt/hydra_sources/archives_bd/bcadmin/mss/av_backlog/C1436/C1436_2022_06_bag_a
```

Kelly says the pbcore may have a `pbcoreTitle[@titleType="item_title"]` instead.

**Comment by tpendragon** [comment]
Kelly will be providing the two pbcore examples here: https://docs.google.com/document/d/1sYciZwgh9MObEVhqykQKREwV5CVTB66gBrp8pH_7oqY/edit
