### ISSUE TITLE
DEPRECATION WARNING: render_thumbnail_tag

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5247]
DEPRECATION WARNING: render_thumbnail_tag is deprecated and will be removed from blacklight 8.0 (Use IndexPresenter#thumbnail.thumbnail_tag). (called from block in _app_views_numismatics_monograms_index_html_erb___4513417858383851083_416800 at /home/circleci/figgy/app/views/numismatics/monograms/index.html.erb:15) (4 times); e.g.:

**Comment by eliotjordan** [comment]
Found another one in `monograms/index.html.erb`

**Comment by hackartisan** [comment]
@eliotjordan I can add to the open PR

**Comment by hackartisan** [comment]
@eliotjordan that one looks done already?

**Comment by eliotjordan** [comment]
Ooops. Yep. I was on an old branch.
