### ISSUE TITLE
Add original FileSet filename to IIIF Manifest somehow

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5286]
CollectorSystems is importing our IIIF manifests into their software which is in use at Conservation, but Conservation wants to know what the filenames were before they got put into Figgy (their filenames contain some information about what the image is I guess?)

**Comment by kelea99** [comment]
Hmm. Something to confirm with Conservation. My understanding is:
1.  Collector systems is importing the original file names.
2. Conservation wants their title changes in order/structure managers or edit scanned resource that they did in Figgy itself.
Example: https://figgy.princeton.edu/catalog/c202f31b-9fab-4203-8251-a202bb343ae0

**Comment by tpendragon** [comment]
They're not importing original file names right now, because Figgy isn't providing it. They're importing the label, I believe.

**Comment by kelea99** [comment]
Uh... huh. lemme look at the original files. standby. They should be on the isilon

**Comment by tpendragon** [comment]
For instance https://figgy.princeton.edu/catalog/parent/4b376692-19b6-4f97-a014-18412888a0e8/3e8d0c29-3972-443a-ab57-e5c2d5c758d8 is "20.065_AT.01" in Figgy, but its original filename is 00000001.tif. I guess Melody wants the numbered ones?

**Comment by kelea99** [comment]
Yea, it is not clear to me what information is gained here. I would love to learn more, if possible.
![Screen Shot 2022-07-26 at 3 14 55 PM (2)](https://user-images.githubusercontent.com/45043014/181092793-e41bc942-9b27-48a2-a3cb-60fe88b8cc1d.png)

**Comment by tpendragon** [comment]
We determined in meeting with Melody that they want the label that's in Figgy, which is the canvas label.
