### ISSUE TITLE
Upgrade remaining panels

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5312]
There are still some panels that need to be turned into cards, see https://getbootstrap.com/docs/4.0/migration/ for more info.

List of files:

- [x] app/views/base/_custom_file_manager_actions.html.erb
- [x] app/views/catalog/_auth_link_default.html.erb
- [x] app/javascript/components/playlist_members.vue

**Comment by hackartisan** [comment]
Is this file maybe not used anymore? https://github.com/pulibrary/figgy/blob/main/app/views/base/_custom_file_manager_actions.html.erb

**Comment by tpendragon** [comment]
Yeah that might be from back when the file manager did order manager stuff
