### ISSUE TITLE
[Figgy/production] StandardError: Get footprints
/usr/local/lib/python3.6/dist-packages/cogeo_mosaic/mosaic.py:236: UserWarning: Multiple MinZoom, Assets different minzoom values
  "Multiple MinZoom, Assets different minzoom values", UserWarning
/usr/local/lib/python3.6/dist-packages/cogeo_mosaic/mosaic.py:246: UserWarning: Multiple MaxZoom, Assets have multiple resolution values
  UserWarning,
Traceback (most recent call last):
  File "/usr/local/bin/cogeo-mosaic", line 8, in <module>
    sys.exit(cogeo...

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5341]
## Backtrace

    line 15 of [PROJECT_ROOT]/app/services/mosaic_generator.rb: run
    line 34 of [PROJECT_ROOT]/app/services/tile_metadata_service.rb: rescue in mosaic_path
    line 29 of [PROJECT_ROOT]/app/services/tile_metadata_service.rb: mosaic_path

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/87205580)

**Comment by hackartisan** [comment]
a bunch of these crashed figgy. https://app.datadoghq.com/logs?query=service%3Afiggy%20status%3Aerror&cols=host%2Cservice%2C%40http.status_code&event=AQAAAYJvustoR49sXAAAAABBWUp2dXVENkFBQW5ORl9hNC1XQXBnQUE&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1659731803507&to_ts=1659731890074&live=false

**Comment by tpendragon** [comment]
This was from mis-migrating a few raster resources.
