### ISSUE TITLE
PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed outSSL SYSCALL error: Connection timed out

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5344]
## Backtrace

    line 23 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: block in log_connection_yield
    line 17 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: log_connection_yield
    line 75 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/81174648)

These appear to be due to network issues.

We get these errors from lib-proc 7 and 10. They are both on hosts with primary location in New South, the others are on hosts with primary location in Forrestal.

The psql box figgy uses is in Forrestal, and it's a physical box, so those connection errors may be related to data center locations.

other relevant honeybadger notifications:
- https://app.honeybadger.io/projects/53391/faults/81997939
- https://app.honeybadger.io/projects/53391/faults/87152309
- https://app.honeybadger.io/projects/53391/faults/44309693
- https://app.honeybadger.io/projects/53391/faults/84380011
- https://app.honeybadger.io/projects/53391/faults/86428023

# How to Fix

1. Wait until Figgy is migrated to the new postgres cluster.
2. See if it still errors.
3. If it does, connect with operations and work with them to investigate firewall connections.

**Comment by hackartisan** [comment]
We've migrated to the new postgres and this error still occurs. moving back to inbox.
