### ISSUE TITLE
Ingest issue with items in Princeton Internships in Civic Service (PICS) collection

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5348]
Characterization failed on several resources and they need to be reviewed.

note that these are all zip files.

- https://figgy.princeton.edu/catalog/5324c437-b1f9-44cd-a470-5b59e4902c49
- https://figgy.princeton.edu/catalog/612180e2-1509-4856-b052-2825c2defd52 
- https://figgy.princeton.edu/catalog/370923af-56e5-4875-b9eb-e31a726e7353
- https://figgy.princeton.edu/catalog/30915689-a163-453d-bb58-3586c64e675f
- https://figgy.princeton.edu/catalog/36be976c-0cf9-41e8-ab01-672d0d75d937
- https://figgy.princeton.edu/catalog/89db47c6-c7c4-426d-8ae8-f42c307bd01c
- https://figgy.princeton.edu/catalog/e7342081-f26e-4999-949a-d71568ea17df

discovered while investigating https://app.honeybadger.io/projects/53391/faults/79898382/01G52BXDH4J5DQM4WC3EN4710K#notice-params

## To Fix

The files above are broken. Contact the depositor and ask them to reupload.

## Sudden Priority Justification

These files are broken and we're putting them up like they're not, the longer we go without fixing it, the harder it'll be to find those files.

**Comment by tpendragon** [comment]
Sent a message to the ingester, haven't heard back yet.
