### ISSUE TITLE
fileset with too many derivatives

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5352]
Is this right? https://figgy.princeton.edu/catalog/99bd0a3f-488c-4c36-8519-d75fb0a87b44

found while investigating errors from 8/4 on https://app.honeybadger.io/projects/53391/faults/84134442/01G9MZNGJDN3SD9FEJP9Z0FZ72#notice-summary

There were 587 errors on 8/4; one was a scanned resource image that needed a regenerated derivative.

Here's a list of ids: https://gist.github.com/hackartisan/9ee3224cc8b45cd9c4e1bb6e00b32317

**Comment by hackartisan** [comment]
there are about 586 of these. I'm working on extracting a list of ids.

**Comment by hackartisan** [comment]
There were more of these on 8/11 and 8/12.

**Comment by hackartisan** [comment]
The merged PR ensures these derivatives don't continue to be re-generated. The next step is to identify resources with too many derivatives and regenerate derivatives for them to clean up the ones with too many.

**Comment by hackartisan** [comment]
The errors on these were "Aws::S3::MultipartUploadError: multipart upload failed: undefined method `read' for #<IngestableFile:0x00007f0e58b88c20>"

**Comment by tpendragon** [comment]
Reopening until this migration is run.

**Comment by hackartisan** [comment]
Ran it.
