### ISSUE TITLE
Manifests are not consistently caching

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5353]
- Each of the four figgy front-end servers must separately cache the same manifest for consistently fast results.
- figgy-web-prod-2 does not appear to be caching manifests at all.  Repeated calls to the same manifest trigger a full regeneration.
![Screen Shot 2022-08-11 at 12 00 59 PM](https://user-images.githubusercontent.com/784196/184192473-7ce29d27-9156-452e-91b8-4c2786ef601c.png)

![Screen Shot 2022-08-11 at 12 04 37 PM](https://user-images.githubusercontent.com/784196/184192489-98d5bf2c-9e9d-465a-aefa-c4b0a4f011bd.png)

## Sudden Priority Justification

Manifests are one of our core services and for large items we depend on caching for a reasonable user experience. It's important we maintain that user experience so we're then unburdened to work other priorities.

**Comment by tpendragon** [comment]
We used to cache these in memcached hosted on figgy1, maybe something broke?

**Comment by eliotjordan** [comment]
Only figgy-web-prod-4 can connect to figgy1 memcached.

`telnet 128.112.201.194 11211`

**Comment by acozine** [comment]
All four figgy web VMs are on the newer, replicated Library cluster. `1` and `4` are on hosts in Forrestal; `2` and `3` are on hosts in New South. Which means the data center *could* be causing the problem, though it seems unlikely. Do we know when this broke?

**Comment by eliotjordan** [comment]
@acozine No we don't.

**Comment by acozine** [comment]
It seems to be network-related. We're working on it.

**Comment by eliotjordan** [comment]
This is working now. Thanks @acozine!
