### ISSUE TITLE
[Figgy/production] Date::Error: invalid date

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5358]
Can't view https://figgy.princeton.edu/catalog/14784d3c-603e-4f26-878a-3bda2c2fd1e7

## Backtrace

    line 196 of [PROJECT_ROOT]/app/decorators/scanned_resource_decorator.rb: parse
    line 196 of [PROJECT_ROOT]/app/decorators/scanned_resource_decorator.rb: block in display_date_range
    line 196 of [PROJECT_ROOT]/app/decorators/scanned_resource_decorator.rb: map!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/87113909)

**Comment by hackartisan** [comment]
this resource has been deleted

**Comment by eliotjordan** [comment]
Decorator should handle invalid dates more gracefully.

https://figgy.princeton.edu/catalog/b4822329-4e57-48df-ad3f-9a1c9294fdf9
https://github.com/pulibrary/figgy/blob/0eadbed6a9c1798c78534c482e28c7160016160f/app/decorators/scanned_resource_decorator.rb#L196
