### ISSUE TITLE
[Figgy/production] Ezid::Error: unauthorized

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5359]
## Backtrace

    line 30 of [PROJECT_ROOT]/app/services/identifier_service.rb: mint_identifier
    line 35 of [PROJECT_ROOT]/app/services/identifier_service.rb: assign_new_identifier
    line 59 of [PROJECT_ROOT]/app/services/identifier_service.rb: mint_or_update_geo_resource

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/79991624)

**Comment by hackartisan** [comment]
accidentally clicked the issue create button; we don't need this.
