### ISSUE TITLE
Scanned Map with single raster child is not displaying correctly in the viewer. 

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5362]
The viewer should draw a "Default" as well as "Map" tab. 

https://figgy.princeton.edu/catalog/2ad71ae6-18ad-4afc-b3be-d6532657d677

**Comment by tpendragon** [comment]
We're getting a CORS error, thinking that we set up CORS for the mosaic endpoint and not the COG endpoint.

**Comment by eliotjordan** [comment]
Wasn't a CORS issue. The raster FileSet did not have a cloud file. Regenerated derivatives and it works fine now.
