### ISSUE TITLE
Megaticket, Structure Manager: Figgy is not saving/retaining addition, deletion, and edits of structure users manually execute in some resources in Structure Manager 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5364]
### Summary

- #5154 
- #5087 
- #4206 (Closed)
- #3166 (Closed)
- Graduate Students for the Middle East Manuscripts project also reported this issue for specific items. Example:
- https://figgy.princeton.edu/catalog/9f57a91e-08ed-4e0a-9662-0d6670fb848b
- https://figgy.princeton.edu/catalog/5226264c-be8a-42a4-a4c7-235dce87ac3f

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This does impact the workflow and will become a major problem once we near the end of time the Grad Students are able to contribute. While we have come up with work arounds (ex: Save to ensure you can after a couple changes or move on to another item), it is a major pain point. Especially if a lot of work is lost. It isnt urgent/stops work entirely, but Id love to see this as a "within the next 3 weeks", along with the order ticket #5363 .
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by tpendragon** [comment]
We think this is similar to #5363, but is caused by the `MemberValidator`. When we check validations for the example resource given we get the following:

```
irb(main):006:0> change_set.errors.full_messages
=> ["Member ids b5b3bda9-8f80-444a-b7b7-520d7e8f77fd does not resolve to a resource"]
```

**Comment by tpendragon** [comment]
I started working on this, but MemberValidator got added here: https://github.com/pulibrary/figgy/commit/f3e3dbb86e7f0f81f9df75e66420a3328598b225, which supports the "Attach" button on scanned maps. So this validator is so that if someone puts an ID in there to a non-existent resource it gives them an error. Maybe it should only be checking new member_ids..?
