### ISSUE TITLE
Try adding optimistic locking to Figgy resources

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5365]
Spike to see how big a project it would be to add optimistic locking to:

- scanned resources
- geo resources
- ephemera folders
- any other ones that i forgot about?

Note that the resource superclass is used for all kinds of other things so it probably can't be done there.

Created this issue out of a suspicion that https://github.com/pulibrary/figgy/issues/5363 may have been caused by a race condition.

**Comment by hackartisan** [comment]
Consider what impact this might have on users.

Potentially try not using the lock in form? This is what we do with FileSets.

**Comment by eliotjordan** [comment]
Completed.
