### ISSUE TITLE
Giant PDF isn't creating page derivatives for every page.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5366]
### Summary

The following resource isn't properly creating derivatives - sometimes it doesn't make enough pages, sometimes it doesn't generate derivatives for every page, sometimes it creates too many pages.

https://figgy.princeton.edu/catalog/parent/92d93408-4e7d-4e0c-81cb-611b214644ad/56e43f56-25fc-4c48-a47a-eb19c823346d

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

We can prioritize this for the maintenance cycle starting 09/05/22

## Sudden Priority Justification

Tom Ventimiglia's trying to do this work and is unable to.

**Comment by hackartisan** [comment]
Is it possible the metadata about how many pages are in the pdf is unreliable / bad?

**Comment by hackartisan** [comment]
The resource was deleted. Closing this ticket; please reopen if there's other action required.
