### ISSUE TITLE
Add embargo_date property to all resources

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5372]
There should be a spot in the form to edit it along with a datepicker. It should store ISO8601 dates that coordinate with midnight on a given day in the eastern time zone.

For instance, if I put in 2022-01-02, that means the date stored should be midnight on the January 2nd 2022 in the eastern time zone.

We might have to configure Rails' default time zone to Eastern to do this. See https://stackoverflow.com/questions/6118779/how-to-change-default-timezone-for-active-record-in-rails.

If that doesn't work, another option might be wrapping code in `Time.use_zone("Eastern Time (US & Canada)") do`, but this might get complicated.

Part of #5367

**Comment by hackartisan** [comment]
Given that the rails `time_zone` configuration seems to be partially about converting the zone back and forth during database updates / access, and we won't be storing this with active record, it might be good to be more explicit.

**Comment by tpendragon** [comment]
Oh my understanding was the rails time zone defines what the TZ Time.current and such returns, and the AR config was what did the database stuff.

**Comment by hackartisan** [comment]
Hm, I see what you mean. That configuration just makes Rails convert anything it sees to the configured time zone? Would this have implications for our other values? It doesn't seem to be a field-specific configuration.

**Comment by hackartisan** [comment]
Looks like the global configuration will be disruptive of other date values, including years entered for other properties. We'd have to do a data migration or something? Here's a sample test run showing the way years would behave https://app.circleci.com/pipelines/github/pulibrary/figgy/4628/workflows/05cc6aaf-7070-4bae-becb-a5552c34ac1b/jobs/39488

**Comment by tpendragon** [comment]
What do you think we should do?
