### ISSUE TITLE
Add a way to set Figgy metadata as part of bulk ingest.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5374]
## Use Case

When bulk ingesting ETDs every year each record will have a different visibility and embargo date. There should be a format so we can still use our existing bulk ingest UI, but every record has unique data for those properties.

## Proposal

Add support for a `figgy_metadata.json` that allows users to provide ChangeSet attributes. For example:

```json
{
  "visibility": "open",
  "embargo_date": "2022-01-02"
}
```

Part of #5367 

Properties in the bulk ingest interface should apply first, then those in the file should override those on a per-resource basis.

## Considerations

We considered doing YML and decided against it because YML tends to have more security problems.

We considered `resource_metadata.yml`, but felt `figgy_metadata.yml` was more descriptive and evokes thoughts of the types of resources in Figgy.

## Thoughts

We're not sure how we would handle invalid resources that were caused by putting bad metadata in the JSON file.

### Proposal for handling invalid resources

1. JSON Schema validation?
2. Capture failing resources & shoot them into their own job, notify somehow?
    * Maybe no job, just email the ingester that there were some resources that failed validation?

**Comment by escowles** [comment]
Will all attributes be supported in this JSON/YML file? If so, this seems like an interesting SIP format that could be an alternative to the Rake-based import tasks.
