### ISSUE TITLE
Generate documentation on the expected ETD bulk ingest format for RDSS.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5375]
Put it in `docs/use_cases.md`

Right now we're expecting a format like:

- 📁 ingest_folder
    - 📁 \<mmsid\>
        - 💿 resource_metadata.yml (or json, see https://github.com/pulibrary/figgy/issues/5374)
        - 💿 anyfilename.pdf
    - 📁 \<mmsid\>
        - 💿 resource_metadata.yml (or json, see https://github.com/pulibrary/figgy/issues/5374)
        - 💿 anyfilename.pdf

**Comment by escowles** [comment]
Are supplemental files going to be handled as part of this ingest? If so, then a naming convention to make sure we correctly identify the thesis PDF would be helpful.

**Comment by tpendragon** [comment]
@escowles I'd need an example of an ETD with supplemental files in DSpace to answer that question.
