### ISSUE TITLE
lib-proc8 can't connect to ponyexpress

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5382]
lib-proc8 can't connect to ponyexpress on port 25. I tried lib-proc7 and lib-proc6 and they are fine. Not sure if this is a configuration issue on the pony express server or a firewall / network issue.

## Backtrace

[Figgy/production] Errno::EHOSTUNREACH: No route to host - connect(2) for "lib-ponyexpr.princeton.edu" port 25

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/87463168)

**Comment by eliotjordan** [comment]
Can connect now.
