### ISSUE TITLE
Move Boxes from DK SAE Ephemera Project to SAE Ephemera Project in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5383]
### Summary

Ellen Ambrosone is read to have Boxes 9,10, 12, 13, 14, and 15  migrated from the DK SAE ephemera project to the SAE ephemera project. DK agencies in India has wrapped up the metadata for this batch of material, and it is now ready for migration,  review, and go live.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Not impeding work, but would be great to have set up and ready to go for the grad students reviewing the content this fall.  

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks 
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by hackartisan** [comment]
Done.

**Comment by kelea99** [comment]
Contacted stakeholder to let them know today
