### ISSUE TITLE
Document use case for Mendel programs & special collections supplemental material PDFs

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5392]
They're ingesting the PDF as a title-only resource, marking it complete, and copying https://arks.princeton.edu/<arkhere\>/pdf to the 856 of the record.

**Comment by sdellis** [comment]
Users don't want to see a viewer in the catalog, but would rather have a direct link to supplemental material files. This use case should be entered in the use case file in the `docs` directory in Figgy. 

Here is the link to these two end user workflow documentation: https://drive.google.com/drive/folders/1f2-XSDTYiFsvS1i0BxNrNjnldXLPWSlT
