### ISSUE TITLE
Wireframe a new Structure Manager interface

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5395]
Keep in mind these past and current tickets:

https://github.com/pulibrary/figgy/issues/5390
https://github.com/pulibrary/figgy/issues/5389
https://github.com/pulibrary/figgy/issues/4971
https://github.com/pulibrary/figgy/issues/179
https://github.com/pulibrary/figgy/issues/180
https://github.com/pulibrary/figgy/issues/1723

**Comment by sdellis** [comment]
This is a [living Use Case and Requirements document](https://docs.google.com/document/d/1Rez1RljZmUSDa6ok6j_PJ7f9-f_lusEBHP5PvAbA4hY/edit#) so we know what we are building.

**Comment by sdellis** [comment]
Here's the [latest demo](https://xd.adobe.com/view/2b10a99b-4fe6-47c1-b2ae-ed743cf7bbbd-7e43/). Still needs work.

**Comment by sdellis** [comment]
[The final wireframe is complete.](https://xd.adobe.com/view/de230b48-d3c3-4fbc-9831-5515cf6545c6-8b70/)
