### ISSUE TITLE
CDL scans not ingesting

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5396]
Over the past couple of weeks we've had multiple reports of cdl scans being placed in the scans file, disappearing, and then never showing up in figgy.

One such report: https://faq.library.princeton.edu/admin/ticket?qid=9992013
Another older report: https://faq.library.princeton.edu/admin/ticket?qid=9932492 

### Sudden priority justification
Staff aren't able to do their work, which in this case directly supports instructional and research needs of the University.

**Comment by hackartisan** [comment]
Via a scheduled rake task, the CDL::AutomaticIngester kicks off a CDL::PDFIngestJob. The last time I see [that job in the logs](https://app.datadoghq.com/logs?query=service%3Afiggy%20PDFIngestJob&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1660232325564&to_ts=1661528325564&live=true) is August 22nd. This suggests there was an error before that job was enqueued.

Also the file is no longer in the scan directory. It's also not in the ingest directory (which is empty).

**Comment by hackartisan** [comment]
Looked at this a bit more with @tpendragon. Notes:

For figgy to have malfunctioned in the manner observed, the AutomaticIngester would have to have moved the file to an incorrect location, then crashed the process without alerting honeybadger. If it moved to the correct location we would see the file there. And if it didn't crash then PDFIngestJob would still have been invoked.

https://github.com/pulibrary/figgy/blob/0d3d0dc7e380664a89e9b602e452495518a25ddd/app/services/cdl/automatic_ingester.rb#L20-L21

This scenario seems extremely unlikely. It seems more likely that some other process is moving the file before the ingester is run. The rake task that runs that ingester is scheduled to run each hour.

(Also note that there are some PDFIngestJobs from today; this issue is intermittent.)

**Comment by tpendragon** [comment]
Peter Bae's theory is that it's the bookeye B-Scan software stealing the files. He's going to check and get back to us.

**Comment by tpendragon** [comment]
We can't figure out what's stealing those files. Subfolders don't seem to be affected, so we're going to switch everything to `cdl_scans/figgy_ingest`

**Comment by tpendragon** [comment]
The subfolder is working. Closing this.
