### ISSUE TITLE
Can't load structure manager on a resource

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5407]
Resource: https://figgy.princeton.edu/catalog/cfa08806-5a73-4920-9bcc-2c9df295dd38

```
NoMethodError: undefined method `thumbnail_id' for nil:NilClass
```

## Backtrace

    line 71 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: iiif_thumbnail_path
    line 26 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: figgy_thumbnail_path
    line 24 of [PROJECT_ROOT]/app/views/base/_structure_node.html.erb: block (2 levels) in _app_views_base__structure_node_html_erb__2068060152399724350_4539460

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/87791509)

**Comment by tpendragon** [comment]
This is the same ticket as https://github.com/pulibrary/figgy/issues/5154

**Comment by hackartisan** [comment]
We investigated the object in question and found that it has 37 leaf structure nodes that hold proxy objects with ids for (FileSet) resources that have been deleted.

Relevant code: 
https://github.com/pulibrary/figgy/blob/0ee595585c6e94d686f29790084445892830797b/app/views/base/_structure_node.html.erb#L22-L25

The array holds the proxy object, but when the code goes to fetch the object it comes back nil, so the thumbnail errors.

Code we used to discover this state:
```ruby
id = "cfa08806-5a73-4920-9bcc-2c9df295dd38"
r = ChangeSetPersister.default.query_service.find_by(id: id)
change_set = ChangeSet.for(r)
logical_order = change_set.logical_structure.first
members = Wayfinder.for(change_set.resource).members_with_parents
logical_order = WithProxyForObject.new(logical_order, members)
def add_leaves(a, nodes)                                                                                                                                             
   nodes.each do |node|                                                                                                                                               
     if node.nodes.empty?                                                                                                                                             
       a << node                                                                                                                                                      
     else                                                                                                                                                             
       add_leaves(a, node.nodes)                                                                                                                                      
     end                                                                                                                                                              
   end                                                                                                                                                                
 end                                                                                                                                                                  
 leaves = []                                                                                                                                                          
 add_leaves(leaves, logical_order.nodes) 
```

Note that the resource didn't have any members in its member ids list that had been deleted, just the proxy nodes.

Possible next steps:
- Figure out how these logical nodes persisted after their proxy objects were deleted and prevent that from happening
- Change the code to check `proxy_for_object` instead of `proxy.present?`
- Delete these dead nodes on this resource.

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/blob/use_catalog_jsonld/app/change_set_persisters/change_set_persister/cleanup_structure.rb should be what gets run when a file set is deleted.

**Comment by hackartisan** [comment]
Could we filter out dead nodes when we load them in the controller? Then if/when the structure is saved again they would get cleaned up.

**Comment by tpendragon** [comment]
That's a cool idea.

**Comment by hackartisan** [comment]
probably optimistic locking would be the way to prevent this.

**Comment by hackartisan** [comment]
We looked more closely at the manifest builder and it's not filtering out these bad structure nodes. The manifest includes them and the viewer just doesn't error (and doesn't show them, presumably because it couldn't find them).
