### ISSUE TITLE
Add iiif link to manifests

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#542]
I should be able to get the IIIF manifest from /catalog/id/manifest (redirect?) Guessing the model for the URL is annoying. 

Add a iiif link to the manifest. Use https://zimeon.github.io/iiif-dragndrop/

**Comment by tpendragon** [comment]
It seems wrong to mess with the routes just because we as developers want to be able to get to the manifest. Needs more discussion. Back to Backlog.

**Comment by rlskoeser** [comment]
It would be helpful for me to have an easy way to get from the item detail page to the manifest.  Either an easier url pattern to follow or a link somewhere on the page would work for me.

**Comment by hackmastera** [comment]
Add a iiif link to the manifest. Use https://zimeon.github.io/iiif-dragndrop/

**Comment by hackmastera** [comment]
Here is a workaround! go to the file manager, then replace `file_manager` in the url with `manifest`

**Comment by escowles** [comment]
Maybe we should have IIIF drag-and-drop icons on collection pages, in addition to object pages?

**Comment by tpendragon** [comment]
This is in the viewer now, as well as the record pages. Closing.
