### ISSUE TITLE
Make Add Embargo Date / Remove Embargo Date settings  Bulk Ingest and/or Bulk Edit options in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5429]
### Summary

- _As a Figgy user who can bulk ingest, I would like to be able to set an embargo date for an entire collection that I am ingesting._
- _As a Figgy user who reviews and edits collections that have been ingested, I would like to be able to set OR remove an embargo date for an entire collection or collection-level search result via the Bulk Edit function._

Use case: Will Clements made this request in #digital_library Slack channel.  He needs to bulk ingest a large amount of material, and needs to restrict the entire corpus as a group for a specific number of years. We are currently able to bulk set the visibility, but not the embargo date.

PO note:  thinks option to remove an embargo date in bulk edit may be useful in the future. The known need for a  "Remove from Collection" enhancement and the use of bulk visibility changes supports this possible future need. The needs for this ticket would therefore be:

- BULK INGEST: Set embargo date functionality
- BULK EDIT: Set Embargo Date AND Remove Embargo Date Functionality

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This does not impede work (he can bulk set all items to Private), nor is there a hard deadline, but the use case is pretty solid for adding this functionality at some point.  It would help with UX -- they would not have to remember to go to our repository in XXX years to change visibility. 

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize 
## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

### Expected behaviour
When I go to bulk ingest a collection, I expect there to be an option to set an embargo date.

When I execute a collection-level search in figgy, I expect to be able set an embargo date by means of bulk edit.

**Comment by kelea99** [comment]
See also #5430 and #5101  and perhaps prioritize these tickets together

**Comment by thanyabegum** [comment]
After talking with @hackartisan, we came up with the wireframe below for what the bulk edit form UI should look like to allow setting and removing an embargo date.

<img width="1201" alt="Screen Shot 2022-11-02 at 2 23 33 PM" src="https://user-images.githubusercontent.com/66143640/199580132-4434a04d-ffb6-422b-8676-2c2fb424d97b.png">

**Comment by kelea99** [comment]
Update: We are only going to do the Bulk edit feature. Not  "add embargo date" at bulk ingest.  bulk ingest with set embargo dates for senior theses will be added in the ingest via developers.  That is the one use case I know of.
