### ISSUE TITLE
Make Holding Location setting a Bulk Ingest and/or Bulk Edit option in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5430]
### Summary

- _As a Figgy user who can bulk ingest, I would like to be able to set a Holding Location for an entire collection that I am ingesting._
- _As a Figgy user who reviews and edits collections that have been ingested, I would like to be able to set a Holding Location for an entire collection or collection-level search result via the Bulk Edit function._

Use case: @ccleeton made this request in #digital_library Slack channel. she needs to be able to bulk edit a collection to set the holding location and/or set the holding location at bulk ingest. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This does not impede work, nor is there a hard deadline, but the use case is pretty solid for adding this functionality at some point. It would help with UX -- they would not have to individually set holding location for individual items.
### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize - perhaps prioritize this ticket along with #5429 and #5101

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

### Expected behaviour
- [ ] When I go to bulk ingest a collection, I expect there to be an option to set a Holding Location.

- [x] When I execute a collection-level search in figgy, I expect to be able set a Holding Location by means of bulk edit.

**Comment by hackartisan** [comment]
Potential reference PR for the bulk ingest portion of this issue: https://github.com/pulibrary/figgy/commit/2a7ec6acf20f73fe4e7e3a9a611e2f5d3cd1e9a6
