### ISSUE TITLE
Epic: Add Functionality to Bulk Ingest and/or Bulk Edit Feature(s) in FIggy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5434]
### Summary
Epic ticket for:

- [x] #5430 (PRIORITY 01)
- [ ] #5429 (PRIORITY 02)
- [x] #5101 (PRIORITY 03)

Conversation should probably be had regarding where to add this functionality - at bulk ingest? Bulk edit? both?  - for each request.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize - Make users lives easier epic

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by kelea99** [comment]
Prioritized sub-tickets just now (see above)

**Comment by tpendragon** [comment]
There's just #5429 left, so we'll leave that open and close this.
