### ISSUE TITLE
Inherit OCR setting in Host/Parent down to individual volumes in a MVW

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5435]
### Summary
This should work like that of the embargo date functionality for a MVW.  if the parent is set, it becomes the default setting for all the children.  

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

### Expected behaviour
When I go to the edit scanned resource form for a  host/parent record in figgy and set the OCR language, I expect that setting to be the default for all constituents/children linked to the host record. 

**If a host record OCR is not set:** when I go to the edit scanned resource form for individual constituents/children, i expect to be able to set OCR language for each volume separately.

**Comment by kelea99** [comment]
@tpendragon can i close this one, noting the https://github.com/pulibrary/figgy/issues/6013?

**Comment by tpendragon** [comment]
@kelea99 Sounds good

**Comment by kelea99** [comment]
Closed, in favor of https://github.com/pulibrary/figgy/issues/6013
