### ISSUE TITLE
Implement viewer-restrictions on "Senior Thesis" click-through option.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5446]
Blocked by #5438.

When "Senior Thesis" is the click-through, display a click-through in viewer and make it available for 1 hour.

The click-through text can be found while on VPN at https://dataspace.princeton.edu/handle/88435/dsp01jm214s331 

Look and see if we can leverage some of the CDL (controlled digital lending) work we've done in the past to display . Be sure to look towards also being able to implement #5447.

As many people as you want can access a senior thesis at once as needed.

**Comment by tpendragon** [comment]
We decided to work on documenting the existing display first.

**Comment by hackartisan** [comment]
implementation notes: https://docs.google.com/document/d/1tpBHlK8knTsmT4MZjMqMUXiywj9iGvHWea5hHNUGQ6w/edit
