### ISSUE TITLE
Resource with `.jpf` files failing derivative generation

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5457]
https://figgy.princeton.edu/concern/scanned_resources/77362f63-2fe4-4527-b1c3-eae5e60618d8/file_manager

discovered via https://app.honeybadger.io/projects/53391/faults/87174573/01GE0G24R4CRTHPA4JWFH41F42#notice-summary

**Comment by hackartisan** [comment]
@kelea99 Does this look familiar? Do you know what these jpf files are?

**Comment by tpendragon** [comment]
@kelea99 will fix this.

**Comment by kelea99** [comment]
Fixed! https://figgy.princeton.edu/catalog/0a61e17a-17b0-431b-bb06-0852c733ed2a
