### ISSUE TITLE
Missing file needs to be re-scanned

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5481]
The files on FileSet 765 are missing on this resource:

https://figgy.princeton.edu/catalog/171055a1-7066-4409-b0be-1e5eec080985

https://figgy.princeton.edu/catalog/parent/171055a1-7066-4409-b0be-1e5eec080985/a1db7a37-0f2a-43a8-b174-a4ba4010e8a0

 Probably needs to be re-ingested.

## Backtrace

    line 43 of [PROJECT_ROOT]/app/services/preserver/preservation_intermediary_node.rb: calculate_checksum
    line 36 of [PROJECT_ROOT]/app/services/preserver/preservation_intermediary_node.rb: build_preservation_node
    line 28 of [PROJECT_ROOT]/app/services/preserver/preservation_intermediary_node.rb: preservation_node

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/89365150)

**Comment by kelea99** [comment]
@tventimi is most likely the person to ask about this. Ill reach out to him

**Comment by kelea99** [comment]
Colleen is recalling the reel from ReCAP and redigitizing next week.

**Comment by tpendragon** [comment]
@kelea99 will check in with Colleen.

**Comment by kelea99** [comment]
Colleen will rescan the reel next week.
