### ISSUE TITLE
Duration not characterized for WAV files ingested.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5486]
This is breaking display of the files:

https://figgy.princeton.edu/catalog/dd67730a-9d93-4634-aea9-a6e9f694b1fe

Previously this has been because mediainfo got uninstalled. Did that happen again?

## Sudden Priority Justification

This is needed for a class and isn't working, and if we don't fix it quickly then there will be many to fix later.

**Comment by eliotjordan** [comment]
Checked figgy VMs. They all have mediainfo installed.

```
MediaInfoLib - v22.09
```

**Comment by eliotjordan** [comment]
I tried re-characterizing this track and duration was not added to the file metadata.
https://figgy.princeton.edu/catalog/parent/a137ec85-8227-4ddd-84b8-9bb8be9a99b6/6bb3f14a-472e-439c-96ff-6c9c7e2d0f0b

Downloaded the original file and uploaded to a new resource in figgy-staging and the duration was not recorded either.
https://figgy-staging.princeton.edu/catalog/parent/765c6b36-ceb3-45a3-99a3-9e604f276681/8b9e72cd-a82e-440c-a22c-a9e69bf55626

**Comment by eliotjordan** [comment]
On figgy-staging, I uploaded a short test .wav file. Running the mediainfo ruby command yeilds correct metadata:
```
MediaInfo.from("/opt/repository/files/59/5f/c0/595fc0f81f4744c38c8145634d33f5e2/StarWars3.wav")
```

On the misbehaving track from above ("08 - Coleman Hawkins"), the same command returns an error.

```
MediaInfo.from("/opt/repository/files/6f/ed/47/6fed4769ac9f45c483eb7d3c7ee529f9/08 - Coleman Hawkins Orchestra - Body And Soul.wav")
```

```
NameError (`@pre-emphasis' is not allowed as an instance variable name)
```

**Comment by eliotjordan** [comment]
Might be useful: https://github.com/greatseth/mediainfo/blob/master/lib/attribute_standardization_rules.yml

**Comment by eliotjordan** [comment]
I processed the WAV file locally using an audio tag editor called [Kid3](https://kid3.kde.org/). Removed the PRE-EMPHASIS and PRE-GAP tags and uploaded to a new resource on figgy-staging. Characterization ran correctly and the duration was recorded.

https://figgy-staging.princeton.edu/catalog/parent/f8aa5382-3087-46e3-8eb2-06ce2667aceb/b186819a-8af0-41af-9b45-15c72e8c35ac

```
irb(main):005:0> r=Valkyrie::MetadataAdapter.find(:postgres).query_service.find_by(id: "b186819a-8af0-41af-9b45-15c72e8c35ac")
^[[A=> #<FileSet id=#<Valkyrie::ID:0x0000560c0881ebc8 @id="b186819a-8af0-41af-9b45-15c72e8c35ac"> internal_resource="FileSet" created_at="2022-10-26T18:45:56.015Z" updated_a...
irb(main):006:0> r.original_file.duration
=> ["183.507"]
```

**Comment by tpendragon** [comment]
Oop, I thought you were gone. There's a branch: fix_mediainfo_parser, that does your proposal.

**Comment by eliotjordan** [comment]
Re-ran characterization and the issue was resolved.
