### ISSUE TITLE
Cleanup stray files and filesets

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#549]
Due to ingest and deletion errors, we have a significant number of unattached FileSets, with TIFFs and JP2s on disk.  We should identify all files and FileSets that aren't attached to works and delete them.

Rake task or Thor command to check every file on disk and see if it's linked to by a resource. 

Iterate over every file, see if a fileset exists. If no, delete. `StorageAdapter` doesn't have `#all` so probably just use `Dir`.

Iterate over every file_set, delete if it has no parent.

An option for safety is to move all the files to a new location, then validate that all the objects have files before actually deleting.

This seems both low-priority and high-risk. Delay until we have a mirror of the data.

**Comment by escowles** [comment]
Also, we're queueing up CleanupDerivativesJobs in PlumChangeSetPersister (https://github.com/pulibrary/figgy/blob/master/app/change_set_persisters/plum_change_set_persister.rb#L28), but then deleting the metadata it needs before it can execute.

We either need to delete derivatives inline, or we need to modify the derivatives cleanup to use file paths instead of using the metadata.

**Comment by tpendragon** [comment]
Closing as I can't see us prioritizing this as a project.
