### ISSUE TITLE
When content_warning is populated from remote metadata, display that content warning in the viewer

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5492]
See mockup:

https://docs.google.com/presentation/d/1eNAiwQB4eMog7BQffaGQXmIPIPb-3UEEEmqXGmzLW4A/edit#slide=id.g16995e60172_3_0

Related to https://github.com/pulibrary/pulfalight/issues/1195 and https://github.com/pulibrary/figgy/issues/5490

## Implementation Details

We should populate `notice` in the graphql with this information when it's available. Probably in https://github.com/pulibrary/figgy/blob/harmful_warnings/app/graphql/types/resource.rb#L111-L116

**Comment by eliotjordan** [comment]
Should the "For more information on harmful content please see the [PUL Statement on Harmful Content](https://library.princeton.edu/statement-harmful-content)" statement be appended for each resource or will the metadata have it when it's needed?

This part of the statement isn't in the example record metadata.
