### ISSUE TITLE
Move all boxless LAE Project posters to a box in LAE Project

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5496]
### Summary
new use case - LAE has created a box for posters and would like to add all the Figgy [free floating posters](https://figgy.princeton.edu/catalog/d7c889ba-9992-494e-8fe4-2c4a9b3c3d7d) in the figgy  LAE Project to it. 

_Until it is apparent this is a common/more frequent need, a feature request to allow users to batch edit ephemera in this way is on hold._

The box: [Box 000](https://figgy.princeton.edu/catalog/parent/d7c889ba-9992-494e-8fe4-2c4a9b3c3d7d/9e15484f-ab6e-4ef5-a9ba-5ae59a4f9221)

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Emailed with LAE stakeholders - waiting 3 weeks is no problem.
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
This way we could upload the entire box to the LAE website and make the posters quickly available to researchers, versus an individual adding boxes manually to 2,748 posters

**Comment by kelea99** [comment]
I reached out to folks to confirm deadlines/needs to ensure it falls under sudden-priority

**Comment by kelea99** [comment]
Test project in staging environment first.

**Comment by hackartisan** [comment]
Add a test that the boxes are still in the project.

**Comment by hackartisan** [comment]
The task was tested on staging and looks good. invoke like:

```
bundle exec rake figgy:lae:box_boxless_folders PROJECT_ID=d7c889ba-9992-494e-8fe4-2c4a9b3c3d7d BOX_ID=9e15484f-ab6e-4ef5-a9ba-5ae59a4f9221
```
