### ISSUE TITLE
Bad tiffs in Ukraine ephemera project items

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5499]
https://figgy.princeton.edu/catalog/d030f779-f5a2-47ca-829c-9424be7317d2 and https://figgy.princeton.edu/catalog/535a5f07-c3f1-4988-8799-9d36f49ea23e each have 1 bad tiff, which need to be reingested. Who should we contact?

Related to https://app.honeybadger.io/projects/53391/faults/80089019

**Comment by kelea99** [comment]
@hackartisan Ill let @roelmoon know. Muhanad's backup should still have them.

**Comment by kelea99** [comment]
Roel checked, they are bad tifs on the backup as well. just wrote to Anna and Thomas and Roel is going to recall box 16 to reshoot what is needed

**Comment by kelea99** [comment]
Fixed!  @roelmoon  is a wizard. Closing ticket.
