### ISSUE TITLE
Allow HTTP PATCH request from Vue Filemanager

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#551]
Sending PATCH data to the backend returns error about an Invalid Authenticity Token. Perhaps some modifications are needed for how the app handles CSRF in this context. 

The following data was sent (to this endpoint `http://localhost:3000/concern/ephemera_folders/9a25e0ce-4f64-4995-bae5-29140a453fa3`):

```
{"scanned_resource": 
{"member_ids": ["80b02791-4bd9-4566-9a9f-4b3062ba2e0d", "50b5e49b-ade7-4278-8265-4f72081f26a5", "e7208ea3-21f3-43d4-9b14-489e15e9791e", "0a3e268f-5872-444e-bdbd-b1a7b01dcb57", "dae7619f-16a7-4306-93e4-70b4b192955c", "b484cd88-fdf2-477c-afe9-d46a49d8822b"], "id":"9a25e0ce-4f64-4995-bae5-29140a453fa3:}}
```

I'm uncertain if this is the correct endpoint, or if it needs to submit to some other route (file_sets?).  If the above is correct, I'm not clear on how the Filemanager app is supposed to know what kind of resource it is so it can construct an endpoint properly.

**Comment by hackmastera** [comment]
@sdellis I would like to poke at this to see if maybe I can help get you unblocked. Can you give me instructions on how to generate the error? Do I need to set up the vue app and run it against my local figgy instance?

**Comment by hackmastera** [comment]
@sdellis I don't think you will be hitting a file set. can you not get to the object by replacing `concern/ephemera_folders/` with `catalog/`? your work may be dependent on https://github.com/pulibrary/figgy/issues/542
