### ISSUE TITLE
Princeton Performance Archive failing reindexing

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5510]
### Summary

DPUL is having issues syncing with Figgy/reindexing for [Princetons Sound archive collection](https://dpul.princeton.edu/performances). Its failed the past 3  attempts at a manual reindex it seems.  I am not sure if a particular item is causing the fail or if it is the size.  

History: I believe this is the collection that Trey/developers had to get into DPUL. Might that be an issue as well?

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [x] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
Broken sync behavior keeps users from seeing the correct data and/or resources.

### Expected behaviour
I expect DPUL collections to automatically re-index. however, when I go in to dashboard, click on 'Items" and kick off a manual reindex, I expect that reindex to succeed for the entire collection

### Actual behaviour
DPUL Performance Archive does not seem to be auto-reindexing.  Manual reindex has failed the last 3 attempts.

**Comment by hackartisan** [comment]
this is due to https://github.com/pulibrary/dpul/issues/1367

**Comment by hackartisan** [comment]
collection looks like it indexed correctly.
