### ISSUE TITLE
Update UV viewer tab name from "Default" to "Sheets"

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5511]
![Screen Shot 2022-11-07 at 11 48 59 AM](https://user-images.githubusercontent.com/784196/200380072-b84508b1-e156-4872-8f3d-0bd8d5f7e9fd.png)

## Sudden priority Justification
They're working on an exhibit and need these to look nice for its launch

**Comment by sdellis** [comment]
@eliotjordan does this ticket have a sudden-priority justification?
