### ISSUE TITLE
Numismatics "People": Find all instances of "Alexius I" and replace with "Alexios I Komnenus".

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5516]
### Summary
Discovered by Alan Stahl and Elena Baldi.  There are 2 spellings for the same ruler in the numismatics database. They have requested that all instances of "[Alexis I](https://figgy.princeton.edu/catalog/85c98d97-3adc-46a2-9d29-3d9a8ed531f3)" are replaced with "[Alexios I Komnenus](https://figgy.princeton.edu/catalog/2f9ecf66-d8d6-4044-aaa0-4b1d66c1e4df)".

I will confirm: That "Alexius I" should be removed entirely from the People Drop downs. I would assume this is a given, but always good to check. 

@escowles suggested (assuming we created a separate ruler/people resource - which y'all have!)  investigating the possibility of creating a separate  "ruler" resource and these coins are linking to it.  _this might be as easy as finding the relevant ruler object, changing the name, and reindexing the impacted coins (which is basically the same ticket as "reindex all objects in a collection after changing the collection name")._

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
While this is not impeding work, Dr Baldi was hired as a term appointment to catalogue the two large collections of Byzantine coins. If she is also going through the corpus to clean up the controlled vocabularies, it would probably be a good idea to keep on top of that in a sustainable way for y'all.  I am going to place it for 'within the next 3 weeks", since a ton of students work on these collections and it would be good to have only one instance of the Ruler Name they are meant to pick (so the issue does not grow). 

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Since the cataloger is here for a finite amount of time and since a ton of students work on these collections, it would be good to have only one instance of the Ruler Name they are meant to pick (so the issue does not grow). 

### Strategy

Find all issues which have a ruler linked to 85c98d97-3adc-46a2-9d29-3d9a8ed531f3 and replace it with a link to 2f9ecf66-d8d6-4044-aaa0-4b1d66c1e4df.

Add the years active to 2f9ecf66-d8d6-4044-aaa0-4b1d66c1e4df

Delete 85c98d97-3adc-46a2-9d29-3d9a8ed531f3

We should write a task or something to do this and put it in a PR so we can review.

**Comment by eliotjordan** [comment]
There were 11 issues "Alexis I". Fixed by hand and duplicate person deleted.

**Comment by kelea99** [comment]
I emailed Alan and Elena today and shared the ticket with them. Thank you, @eliotjordan !
