### ISSUE TITLE
Allow multiple fileset objects to be updated with a single HTTP request

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#552]
It seems as though the Filemanager may need to send two different HTTP requests "on save". One updates the order of the objects against the "resource type" (i.e., ephemera_folders, scanned_resources, etc.), the other updates the labels and page_type via "fileset". (It's unclear to me which should receive "thumbnail" and "start_page" data.)

@hackmastera says that the current design requires a single http request for each fileset object, so a 1000 page book will require 1000 http requests (if all pages were relabeled). If this is the case, it will introduce an unnecessary performance impact when persisting data.  Instead, we should create an `update` method for filesets that can take accept a json representation of all changed objects in a single request.

**Comment by escowles** [comment]
@sdellis I can see the benefit of having a single controller action for this, and having the controller manage breaking that up into N+1 object interactions.  It will be much more efficient (and will let us do it in a transaction to allow rolling back if some succeed and others fail for some reason).

But I don't think this should block other work — the current file manager makes N+1 HTTP requests and the performance is acceptable.

**Comment by hackmastera** [comment]
achieved via graphql
