### ISSUE TITLE
Document preservation process

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5526]
- Document the full life cycle of resource preservation
- include diagrams where we have them.
- Describe the different aspects of the system from a technical perspective
- Ensure sufficient technical description while avoiding so much detail that it will quickly become outdated.

There's initial work on https://github.com/pulibrary/figgy/pull/5573, written before the current preservation work cycle. It needs to be reviewed, updated, and edited.

## Acceptance criteria
- [x] Review and update preservation section
- [x] Review and update fixity checking sections
- [x] Add documentation of autofix process, including mermaid diagram in https://github.com/pulibrary/figgy/issues/5736
- [x] Review and update UI / status display sections
- [x] Review and update resource restoration sections
- [ ] #6114

related to #5508

**Comment by hackartisan** [comment]
We have https://github.com/pulibrary/figgy/pull/5573 as a draft to reference during this work cycle; once we're done we'll decide whether to update that and keep it or just delete it. This is therefore blocked until the end of the work cycle.

**Comment by tpendragon** [comment]
We're close enough to done that we can talk about the diagram now.

**Comment by hackartisan** [comment]
this diagram is relevant https://github.com/pulibrary/figgy/issues/5736

**Comment by tpendragon** [comment]
I added an ERM diagram and did a little editing of the Preservaiton & Fixity checking sections on #5573. My eyes started to cross so I'm putting this down for a bit.
