### ISSUE TITLE
UI Use Case: Fixity check has failed, how do I fix it?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5539]
## Success Criteria

We need a wireframe for providing enough information for a user to decide if they should re-preserve or restore from the cloud. Things a user might want to do:

1. Run a cloud fixity check
1. Run a local fixity check.
1. Display properties of cloud vs local version.
1. Download the local primary file and look at it.
1. Download the cloud file and look at it.
1. Have a button to re-preserve or do a restore.

Questions: Where do you do this from? In response to a fixity check event? From a FileSet show page? Get to it from the fixity dashboard?

**Comment by sdellis** [comment]
> Display properties of cloud vs local version. 

What properties need to be compared? The fixity status and last fixity event?

**Comment by sdellis** [comment]
How does a re-preserve action work? Does it pull whichever version passed the most recent fixity check and replace the failed version with that one? If both are broken, does that mean that our preservation system failed and they have to locate (or re-digitize) and re-ingest the original object?

**Comment by sdellis** [comment]
At today's standup, I heard an explanation for why we have the steps @tpendragon listed above. I'm uneasy that we are building this system and checklist/workflow primarily as a way to catch race condition errors. Are we not able to prevent race conditions through file locking, or other means? Also, if manually checking the metadata file is part of the workflow, is that the first step?

**Comment by sdellis** [comment]
Also, I'm assuming running a fixity check can take some time. If that's the case, they will need to kick each fixity check off and then come back later. Being able to step through the tasks and fix it right away would be a better experience. Is it possible to run the fixity check on both before the user arrives at this page? Perhaps triggered by the original fixity failure that brought them to this screen?

Also, a user is not just looking at a file, they are making a judgement. The above workflow assumes they will be able to see a difference. What if they look identical to the naked eye, but have some subtle variation that is not noticeable? How do they select the file that was intended?

**Comment by tpendragon** [comment]
We'll unblock this ticket by having a meeting, making decisions, and updating this ticket.

**Comment by tpendragon** [comment]
Closed in preference of #5736
