### ISSUE TITLE
Improve UI for File Set Show Page Fixity Status

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5543]
![Screen Shot 2022-11-29 at 9 04 53 AM](https://user-images.githubusercontent.com/2806645/204594996-66559f7c-ce32-4926-b4a7-5455cfd29465.png)

Things we noted:

* The date is hard to read.
* Non-primary files will never have any status.
* For the count on the resource page, we assume success if there's no event (assuming it wouldn't have been able to be uploaded to cloud storage if fixity was bad), but display "in progress" on this page.
* "In progress" isn't really true - it's not happening right now.

**Comment by sdellis** [comment]
What are non-primary files?

**Comment by hackartisan** [comment]
There's one primary file per file set, determined by the following algorithm: https://github.com/pulibrary/figgy/blob/7d4a77a9e94c88e58bc4f9915b53bb770f73a816/app/models/file_set.rb#L94-L102

Any other file on that file set is non-primary. Yes, I agree we should make it clear that they're intentionally not preserved.

To get to a file set show page from any resource, click on "file manager" and then select one of the edit / popout icons on one of the files in the list (top right corner of each file card).

**Comment by sdellis** [comment]
![fixity.png](https://images.zenhubusercontent.com/5cba15f2e89c9c3b0c58e0d1/97f4ebc7-e69d-4f69-9094-8704f0a9c90a)

Here's a pass at more clarity on this screen. The one scenario not shown is a failed fixity check. In my mind, that would look similar to the "Not tested yet // [Test manually]()" note/link, but would read "Failed // [Fix the problem]()".

**Comment by hackartisan** [comment]
We discussed this together. It might be nice to say why it's not preservered, maybe say "Derivative files are not preserved" or something like that.

The success date formatting could match last motified.

It will be good to have indication of what happens when I click "test manually" -- assuming this enqueues a fixity job, we may need to look into whether it's realistic to implement an "in progress" display. We may need to implement this in the front-end and so it might be worth considering priority of this "test manually" button.

**Comment by sdellis** [comment]
![local-fixity.png](https://images.zenhubusercontent.com/5cba15f2e89c9c3b0c58e0d1/2269024f-6811-4d8c-935b-9cdcce01bec9)

This is a new version that addresses the issues we last discussed. As for the "Test manually" link/button, I had imagined it would change to say "Queued for Fixity Check" when clicked. It would be nice to provide a little more info to the user, but given the space and the backend unknowns think that is ok to do this in the front-end for now.

**Comment by hackartisan** [comment]
this looks fantastic 👍🏻 💯

**Comment by kelea99** [comment]
100% agree. its awesome, @sdellis !
