### ISSUE TITLE
find_cloud_fixity_failures query is slow

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5545]
and causes the fixity dashboard to run slow.

https://github.com/pulibrary/figgy/blob/main/app/queries/find_cloud_fixity_failures.rb

find all events where there isn't an event after that event that's for the same properties and has a success.

We might be able to do a much simpler and faster query that's based on GROUP BY and ORDER.

**Comment by hackartisan** [comment]
This looks potentially helpful
https://learnsql.com/cookbook/how-to-select-the-first-row-in-each-group-by-group/

and a related comment: https://stackoverflow.com/questions/3800551/select-first-row-in-each-group-by-group/7630564#comment40993977_3800572

**Comment by tpendragon** [comment]
We tried the above solutions. The fastest we could get a 100% index-based DISTINCT and CTE-based solution to work was 11 seconds.

The existing query, at that time, ran in 5 seconds.

EXPLAIN ANALYZE shows that it's pulling something like 1.4 million rows, which is just a lot of rows to unique-ify, which takes time.

@hackartisan and I discussed an alternate strategy:

1. Add a `current: true/false` property to Event.
2. When adding a new event that has the same Type and child_id, mark all previous events with that type and event_id as `current: false`.
3. In this query, just select where current: true. That should use an index and be very fast.

**Comment by tpendragon** [comment]
These are the things we tried, some of which may be useful for a migration as part of the above:

CTE + ROW_NUMBER (could be adjusted to find everything that's not the first row)
```sql
WITH summary AS (
  select res.*, ROW_NUMBER() OVER(PARTITION BY res.metadata->>'child_id' ORDER BY res.updated_at DESC) AS rank FROM orm_resources res WHERE res.internal_resource = 'Event'
) select * from summary WHERE rank = 1 AND metadata @> '{"status": ["FAILURE"]}' ORDER BY updated_at ASC LIMIT 50;
```

SELECT DISTINCT
```sql
WITH summary AS (
  SELECT DISTINCT ON (metadata->>'child_id') * FROM orm_resources WHERE internal_resource = 'Event' ORDER BY metadata->>'child_id', updated_at DESC LIMIT 50
) select * from summary WHERE metadata @> '{"status": ["FAILURE"]}' ORDER BY updated_at ASC LIMIT 50;
```


Indexes we built to speed up SELECT DISTINCT and CTE/ROW_NUMBER

```sql
CREATE INDEX event_metadata_child_id_idx ON orm_resources ((metadata->>'child_id'), updated_at DESC) WHERE (internal_resource) = 'Event'
```

Existing query, but minus a few checks (resource_id and child_property):
```sql
SELECT res.* FROM orm_resources AS res WHERE NOT EXISTS (
  SELECT a.* FROM orm_resources AS a WHERE
  a.internal_resource = res.internal_resource AND
  a.metadata @> '{"status": ["SUCCESS"]}' AND
  a.metadata->'child_id' = res.metadata->'child_id' AND
  a.updated_at >= res.updated_at
) AND
res.metadata @> '{"status": ["FAILURE"]}' AND
res.internal_resource = 'Event'
ORDER BY res.updated_at ASC
LIMIT 50
```

Removing those extra checks cut off like a second, not significant enough to do.

**Comment by hackartisan** [comment]
Close in favor of #5589
