### ISSUE TITLE
Preserve everything that's not already preserved.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5556]
After everything's fixed up, we'll want to ensure they're preserved, the metadata is the most recent version, and any missing children are also preserved.

We should try to preserve only those things which aren't preserved already and correct. Re-preserving everything would be very expensive.

This is done when everything generated by the report run by #5978 is fixed. i.e. blocked by finishing / merging #5978

## implementation
- Input will be the bad_resources.txt from #5978. 
- task should try to preserve them all, with force: true

**Comment by tpendragon** [comment]
Blocked until after the fire drills - if something comes up there we'll want to fix it.

**Comment by tpendragon** [comment]
Thinking through how to preserve everything without re-preserving things if not necessary.

To preserve everything:

Go through every resource
Should it be preserved? Skip if no
Does it have a PreservationObject? If no, queue PreserveResourceJob
Does the PreservationObject have all the binary_nodes and metadata_node it should have? Queue a forced PreserveResourceJob if no.
Do the checksums of the binary_nodes match the stored checksum upstream? (Check metadata, don't actually run a CloudFixityJob, to save money.) If no, force PreserveResourceJob.
Do the checksums of the metadata_node match the stored checksum upstream? (Check metadata, don't actually run a CloudFixityJob). If no, PreserveResourceJob with no force flag.

Other considerations:

Should we be thinking about parents/children here? Maybe we should run the parents first?

**Comment by tpendragon** [comment]
I'm running this query in a tmux terminal on lib-proc8 to get an idea of how many resources we'd have to re-preserve if we just triggered preservation on all root parents:

```ruby

query_service = ChangeSetPersister.default.query_service

parent_resources = query_service.custom_queries.find_by_property(property: :member_ids, value: [{}], lazy: true)
parent_resources = parent_resources.select do |resource|
  # Nothing that has a parent
  !Wayfinder.for(resource).try(:parent)
end
count = parent_resources.filter_map do |resource|
  1 if HealthReport::CloudFixityCheck.for(resource).status == :in_progress
end.reduce(&:+)

puts "Parent resources not preserved: #{count}"
```

**Comment by tpendragon** [comment]
Parent resources not preserved: 21419

**Comment by tpendragon** [comment]
Running this to get an idea of how many file sets this would be:

```ruby
query_service = ChangeSetPersister.default.query_service

parent_resources = query_service.custom_queries.find_by_property(property: :member_ids, value: [{}], lazy: true)
parent_resources = parent_resources.select do |resource|
  # Nothing that has a parent
  !Wayfinder.for(resource).try(:parent)
end
count = parent_resources.filter_map do |resource|
  (Wayfinder.for(resource).try(:deep_file_set_count) || 1) if HealthReport::CloudFixityCheck.for(resource).status == :in_progress
end.reduce(&:+)

puts "File sets needing preserved: #{count}"
```

**Comment by tpendragon** [comment]
File sets needing preserved: 132701

If I'm doing the math right, I think that's only about another $130 in storage.

**Comment by tpendragon** [comment]
We're going to queue up those 132,701 file sets as a first step.

**Comment by tpendragon** [comment]
I kicked these off:

```ruby
query_service = ChangeSetPersister.default.query_service

parent_resources = query_service.custom_queries.find_by_property(property: :member_ids, value: [{}], lazy: true)
parent_resources = parent_resources.select do |resource|
  # Nothing that has a parent
  !Wayfinder.for(resource).try(:parent)
end
parent_resources.each do |resource|
  health_report = HealthReport::CloudFixityCheck.for(resource)
  PreserveResourceJob.set(queue: :super_low).perform_later(id: resource.id.to_s) if health_report.valid? && health_report.status == :in_progress
end
```

**Comment by eliotjordan** [comment]
File sets needing preservation as of 8/3/23: 81884

**Comment by tpendragon** [comment]
I was thinking about this:

I think what we need is something which will go through every resource in the database (maybe excluding POs/Events), see if it should be preserved, validate it's preserved if so, fix it if not, and record the actions it took. Then we can look at the report and when that's empty can say "yup, done."

**Comment by hackartisan** [comment]
blocked by #5978

**Comment by eliotjordan** [comment]
Tickets created for bad resources and FileSets:
https://github.com/pulibrary/figgy/issues/6136
https://github.com/pulibrary/figgy/issues/6137

**Comment by eliotjordan** [comment]
Through multiple iterations, we've got the number of un-preserved resources down to 541. These are all represented in the tickets from the previous comment.

Rechecked a final time from the output of[ ticket 5978](https://github.com/pulibrary/figgy/issues/5978#issuecomment-1841149005).
