### ISSUE TITLE
Run preservation fire drills

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5557]
Scenarios:

For the following resource types:
* ScannedResource
    * Volume in a MVW
* EphemeraFolder
* ScannedMap
* Numismatics::Issue
* Numismatics::Coin
* Numismatics::etc.

1. I deleted a resource two weeks ago and want it back.
1. I deleted page 6, I want it back.
1. I deleted everything in the collection and want it back.
1. I deleted everything in a collection and also the collection.
1. The Isilon lit on fire, I need Figgy again.
  * Replicate postgres production database/solr production to the staging environment.
  * Point Figgy to the AWS replica, with a read only user?
     * Maybe writes go to a new AWS bucket, and old file reads come from the AWS backup?
     * Alternatives are restore everything from preservation backup.
  * How much money are we willing to spend to test this use case?

## Implementation Plan

1. Get a staging environment for each of the above scenarios.
2. Perform the thing.
3. Decide how well that went, document the process for recovery.

## Research That Could Make This Easier

- [ ] #5754

## Acceptance Criteria:

- [ ] Finish tasks in the notes document linked below.
- [ ] Re-instate 2 day deletion rule in the preservation google cloud bucket for staging.

**Comment by hackartisan** [comment]
We made a bunch of smaller tickets and we're done with this ticket.
