### ISSUE TITLE
Use identify instead of Tika?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#556]
I think we could get all of the properties we currently generate for TIFFs (width, height, file size, mime type) using ImageMagick's `identify` command.  During some informal testing, `identify` could extract these for TIFFs in < 1 sec, where Tika took 5+ seconds.

**Comment by tpendragon** [comment]
This should be quick to try out.

**Comment by escowles** [comment]
@tpendragon I have a branch I'll push up
