### ISSUE TITLE
FileSet with missing file

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5563]
Page 765 of https://figgy.princeton.edu/catalog/171055a1-7066-4409-b0be-1e5eec080985 gives a file not found if you try to download the tif. Its parent is giving pdf errors (https://app.honeybadger.io/projects/53391/faults/64487740#notice-params). and if you try to regenerate you get a not found error as well (https://app.honeybadger.io/projects/53391/faults/91224740).

A new file needs to be uploaded. @kelea99 do you know who we should contact?

In the meantime I'm deleting this file set, so that we don't get the pdf error any more.

File set label / page number: 765
Parent resource: https://figgy.princeton.edu/catalog/171055a1-7066-4409-b0be-1e5eec080985
Original file: 00000025.tif

**Comment by hackartisan** [comment]
@kelea99 will contact Colleen and Tom.

**Comment by kelea99** [comment]
Slacked Colleen and @tventimi about this one.

**Comment by hackartisan** [comment]
close as a duplicate of #5481
