### ISSUE TITLE
Files need to be re-scanned

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5565]
The last 12 pages of this resource are bad tiffs. https://figgy.princeton.edu/concern/scanned_resources/3e153a4d-9e9e-4197-be1d-423ec1187ab1/file_manager

@kelea99 do you know who we should contact?

## Backtrace

    line 82 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: run_derivatives
    line 66 of [PROJECT_ROOT]/app/derivative_services/vips_derivative_service.rb: create_derivatives
    line 64 of [PROJECT_ROOT]/app/derivative_services/default_derivative_service.rb: block in create_derivatives

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/80554711)

**Comment by hackartisan** [comment]
i'm deleting the file sets with bad tiffs to prevent continued error triaging. I downloaded each of them and confirmed they are bad.

Parent resource: https://figgy.princeton.edu/concern/scanned_resources/3e153a4d-9e9e-4197-be1d-423ec1187ab1/file_manager

page numbers: 1226 - 1237

original file names:
- 00001226.tif
- 00001227.tif
- 00001228.tif
- 00001229.tif
- 00001230.tif
- 00001231.tif
- 00001232.tif
- 00001233.tif
- 00001234.tif
- 00001235.tif
- 00001236.tif
- 00001237.tif

**Comment by hackartisan** [comment]
@kelea99 will contact Colleen

**Comment by kelea99** [comment]
notified colleen about this one
