### ISSUE TITLE
Add "Complete (When Processed)" as a state to Bulk Ingest

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5579]
This state will automatically mark the resource complete when all the derivatives are generated.

## Implementation Details

Ideas:

1. Add a new state (processing_for_complete maybe?)
2. Use Sidekiq batches or something else to know when everything's generated derivatives and automatically mark it as complete when that's done.
3. Remove "Complete" as an option from Bulk Ingest (ticketed separately as #5566)

## Related Tickets

#5566 
#3477

**Comment by eliotjordan** [comment]
This ticket might have interactions with Derivative generation re-try logic in this ticket: https://github.com/pulibrary/figgy/issues/5736

We should discuss implementation.

**Comment by tpendragon** [comment]
**Action Item**: Add this info to an ADR for the PR that closes this.

What we decided:

Resources can be set as "Complete When Processed"

Every 30 minutes a rake task will get run which will find all resources that are marked "complete when processed" and mark them complete.

Reasoning:

* The batch method had a variety of edge cases around jobs being deleted in Sidekiq, files being added afterwards (outside of the batch), and seemed pretty complex to think about and if it broke DLS would have to fix it manually, probably from the rails console.
    * It's also more code.
* The cron doesn't have to worry about race conditions because all of our resources have optimistic locking enabled. If two run into one another, one of the rake tasks will "win" appropriately.
  * We'll rescue all errors and log them to Honeybadger, but let the cron continue so that one bad resource doesn't block the rest.
* The cron job is really simple to think about.
