### ISSUE TITLE
Identify FileSets with broken derivatives, do a one-time fix

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5582]
There are many resources in Figgy that have broken derivatives - to prevent us finding them haphazardly as time goes on we should do a single clean-up process, especially after #5579 and #5581 are done.

Use #2461 for the follow up, "if unable to automatically fix them, present the broken resources to users on the home page"

## Implementation Proposal

Write a service which finds all file sets that are in processing status and have been for over a month. Count them, and then queue up recharacterization for those to see if they'll be fixed! If they break again, presumably they'll record an error, and the fact that they're broken will now show up in the UI.

Blocked by #6059

**Comment by eliotjordan** [comment]
Ticket for resources with broken FileSets that need to be re-ingested:

https://github.com/pulibrary/figgy/issues/6137

**Comment by eliotjordan** [comment]
Found FileSets with an error message with this query:

```ruby
  def relationship_query
    <<-SQL
      SELECT id FROM orm_resources a,
      jsonb_array_elements(a.metadata->'file_metadata') AS g(file_metadata)
      WHERE internal_resource = 'FileSet'
      AND g.file_metadata->'error_message' != '[]'::jsonb
    SQL
  end

  query_service.connection[relationship_query]
```

And queued up CreateDerivativesJobs for the each of the 752 resulting resources.

**Comment by tpendragon** [comment]
Wasn't adding error messages broken for a long time? Did the proposal above not work?

**Comment by eliotjordan** [comment]
Good catch. I didn't mean to close this just yet. However, I ran the proposal above and generated lists of FileSets with derivative errors and "in-process" processing_status values. I uploaded them to ticket https://github.com/pulibrary/figgy/issues/6137.
