### ISSUE TITLE
Update fixity queries to use Event's new `current` field

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5590]
Depends on #5589 

- [x] add a unique index on event for one current event per unique (resource_id, child_id)
- [x] Update FindCloudFixityFailures to use the current true/false flag
- [x] FindCloudFixity to use the current true/false flag.
- [x] Update FindDeepFailedCloudFixityCount to use the current true/false flag instead of inner joins (see https://github.com/pulibrary/figgy/blob/687a55059a246b8cd67adbbbe03c8b170bddcb89/app/queries/find_deep_failed_cloud_fixity_count.rb#L40-L49)

**Comment by eliotjordan** [comment]
Complete
