### ISSUE TITLE
Allow  for PDF only downloading option, even when jpeg/tif page images cannot be downloaded

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5604]
### Summary
_As a subject selector working within the expectations of external collabors and their collections, I need to be able to not allow/turn off jpeg/tif page images but keep on the option for PDF downloads for users._ 

Use case: From Ellen Ambrosone, with regard to the  MFA Boston volumes we are digitally hosting: https://catalog.princeton.edu/catalog/99125404772006421
It has been requested by the MFA Boston that only PDF download be allowed for these volumes in our applications. In other words, they would like higher res JPGs/TIFF image downloads disabled. But are willing to have PDF download.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
While not stopping work, the Professor involved with the initiation of this project is moving forward with preparations for publicity of the items in our catalog. I will confirm a better deadline with Ellen, but for now Ill add to "within the next 3 weeks". There is a work around - we could use the supplemental materials PDF workflows for the item, if the complexity of the feature pushes down its priority with the team.

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Im confirming the deadline with ellen, but a professor who Ellen is collaborating with is starting to move forward with prep for publicity of us hosting these items digitally.
### Expected behaviour
When I go to edit the scanned resource of: Each volume OR the parent record, I expect to be able to enable the pdf selection, while selecting User Download to None.  I expect the PDF to be enabled for users, while the JPEGs and Tiffs to be diabled for download when I make these selections.

### Actual behaviour
When I go to edit the scanned resource of: Each volume AND/OR the parent record, I enable the pdf selection, while selecting User Download to None.  Zero downloads are enabled for users. only an embed share.

**Comment by jpstroop** [comment]
> It has been requested by the MFA Boston that only PDF download be allowed for these volumes in our applications. In other words, they would like higher res JPGs/TIFF image downloads disabled. But are willing to have PDF download.

I want to point it out: The volume is from 1903, i.e. out of copyright (and it's a photo album of likely even older photos). This is a nice preference from the MFA, but they have no legal claims to the intellectual content. We really should not be encouraging this behavior.

**Comment by kelea99** [comment]
@jpstroop I believe this was in the agreement signed by the library. But I can double check this.

**Comment by kelea99** [comment]
This was not promised to external party in paperwork. Closing ticket and Ill walk through other options with Ellen.
