### ISSUE TITLE
Problems with 12 files on Chilean political transition microform reel 3

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5619]
This resource is linked to some vips errors and the files probably need to be reingested:
https://figgy.princeton.edu/concern/scanned_resources/6e88c7d3-f1fd-411a-a88d-11e61ee69ad2/file_manager

honeybadger errors:
- https://app.honeybadger.io/projects/53391/faults/80089019
- https://app.honeybadger.io/projects/53391/faults/80554711

The following at the fileset ids with the vips errors:
```
e22bd71c-8927-43fc-839b-83c24537eab5
ab7c10f2-6a5a-47e3-993e-58a1c998a020
96551a43-eaf3-4f69-b92a-0f794a367221
9ea8ab42-7800-44c7-ae9c-bc43c0937337
50891a71-0646-464a-bbf1-81e9e2dd0eef
c703e577-2bb2-4f89-919d-a7611ec0db27
7050a796-7c79-4836-a06c-f33f700cab4a
5a744463-7f9c-4d2a-86df-afecf776d61c
dbcddc8c-e588-4b75-bf89-22cd3cbb9c56
37ced6cb-f209-4241-8d42-b8c7fc8b183d
0940853f-105b-4921-921b-edf63b9e8775
3743e8e5-6a83-47c5-bebd-830e13376c9c
```

I'm deleting the sidekiq jobs from the retry queue.

The files are numbered 506 through 517 in the file manager. The original filenames are 00000506.tif through 00000517.tif.

**Comment by tpendragon** [comment]
@kelea99 Can you take a look at this and forward it to the appropriate person?

**Comment by kelea99** [comment]
Done! Slacked Colleen and Natalie, includes @roelmoon for troubleshooting, if needed

**Comment by kelea99** [comment]
Will check back in on this one.

**Comment by kelea99** [comment]
its been done! heard back from Colleen and Natalie.  Closing ticket.
