### ISSUE TITLE
Numismatics: Athena Ruby Font required in Figgy for coin descriptions

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5623]
### Summary
Elena tried to catalog a coin using the Athena Ruby font (shelley z. installed last week for her, im assuming on her local machine).  inserted all the right symbols on a .doc file and copied everything into Figgy, but the result was that in the image that she sent (see below). 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This stops her work cataloging coins in need of this font, but i do not have specifics. 
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
she is a term position here, i believe, so her time to work on this project is finite. 

### Screenshots
![image0](https://user-images.githubusercontent.com/45043014/212989619-e8dc5cd3-8fb5-4e83-b34c-dd1db4b07d9c.jpeg)

**Comment by tpendragon** [comment]
We've determined the boxes are from the private use area of that particular font, which we won't support. Closing this as wontfix, if they need a new font just to improve the non-PUA parts, then we'll look into that later.
