### ISSUE TITLE
Generate Report for "Patron Requests - Portions" and "Patron Requests" for stakeholder

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5627]
### Summary
From Jon: Would like a report of all items in the Patron Requests - portions and Patron Requests collections in figgy, minus the Microfilms. 

Date parameters: 7-1-2021 through 6-30-2022
Collections: [Patron Requests](https://figgy.princeton.edu/catalog/b7e8c42b-6fd0-4cfb-bc6d-b5e5a5c79f5c) , [Patron Requests - Portions](https://figgy.princeton.edu/catalog/a5454850-8b97-4750-8390-2c5884134f1f)

Do not include: items in the Microfilm collection

Needs: image count , item count

 ### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
"Sometime in the next few days" @jpstroop , is there a hard deadline?
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
See above

**Comment by hackartisan** [comment]
This is immediate need; more permanent solution will also be necessary; see #5677

**Comment by tpendragon** [comment]
We now know the resource count is 2043:

```sql
select COUNT(id) from orm_resources WHERE created_at between '2021-07-01' and '2022-06-30' AND metadata @> '{"member_ids": []}' AND (metadata @> '{"member_of_collection_ids": [{"id": "b7e8c42b-6fd0-4cfb-bc6d-b5e5a5c79f5c"}]}' OR metadata @> '{"member_of_collection_ids": [{"id": "a5454850-8b97-4750-8390-2c5884134f1f"}]}') AND NOT metadata @> '{"member_of_collection_ids": [{"id": "d7e0141b-ff30-4a9b-b260-09525662a65c"}]}'

```

**Comment by tpendragon** [comment]
The image count should be 319,450:

```sql
WITH RECURSIVE deep_members AS (
  select member.*
  FROM orm_resources a,
  jsonb_array_elements(a.metadata->'member_ids') AS b(member)
  JOIN orm_resources member ON (b.member->>'id')::UUID = member.id
  WHERE a.created_at between '2021-07-01' and '2022-06-30' AND a.metadata @> '{"member_ids": []}' AND (a.metadata @> '{"member_of_collection_ids": [{"id": "b7e8c42b-6fd0-4cfb-bc6d-b5e5a5c79f5c"}]}' OR a.metadata @> '{"member_of_collection_ids": [{"id": "a5454850-8b97-4750-8390-2c5884134f1f"}]}') AND NOT a.metadata @> '{"member_of_collection_ids": [{"id": "d7e0141b-ff30-4a9b-b260-09525662a65c"}]}'
  UNION
  SELECT mem.*
  FROM deep_members f,
  jsonb_array_elements(f.metadata->'member_ids') AS g(member)
  JOIN orm_resources mem ON (g.member->>'id')::UUID = mem.id
  WHERE f.metadata @> '{"member_ids": [{}]}'
)
select COUNT(*) AS count from deep_members
WHERE internal_resource = 'FileSet'

```

**Comment by jpstroop** [comment]
@tpendragon would it be difficult to run the same query for the past few FYs (three or four)?

**Comment by tpendragon** [comment]
@jpstroop Do you want it per year?

**Comment by jpstroop** [comment]
Yes, if possible--I don't know how long this has been a collection in Figgy, so really as far back as you think we can go accurately.

**Comment by tpendragon** [comment]
@jpstroop The patron requests collection got made September 2020. So I can maybe do 2020 - 2021 and it'd be close? It's also June now, so I could do 2022-2023 and only miss a month or so.

**Comment by tpendragon** [comment]
@jpstroop Yes

**Comment by tpendragon** [comment]
The following reports were created with #5872 and this script:

```ruby
collection_ids = ["b7e8c42b-6fd0-4cfb-bc6d-b5e5a5c79f5c", "a5454850-8b97-4750-8390-2c5884134f1f"]

years = {
  2021 => DateTime.new(2020,7,1)..DateTime.new(2021,6,30),
  2022 => DateTime.new(2021,7,1)..DateTime.new(2022,6,30),
  2023 => DateTime.new(2022,7,1)..DateTime.new(2023,6,30)
}

years.each do |year, date_range|
  puts "Creating report for #{year}"
  report = ImageReportGenerator.new(collection_ids: collection_ids, date_range: date_range)
  report.write(path: Rails.root.join("tmp", "image-report-#{year}.csv"))
  puts "Created report for #{year}"
end
```

@jpstroop Are these what you needed?

[image-report-2021.csv](https://github.com/pulibrary/figgy/files/11692511/image-report-2021.csv)
[image-report-2022.csv](https://github.com/pulibrary/figgy/files/11692512/image-report-2022.csv)
[image-report-2023.csv](https://github.com/pulibrary/figgy/files/11692513/image-report-2023.csv)

**Comment by jpstroop** [comment]
Those are great, thanks! I'm going to need the FY2023 one again sometime in the first week of July.

**Comment by tpendragon** [comment]
@jpstroop Here's 2023, now that June's over:

[image-report-2023.csv](https://github.com/pulibrary/figgy/files/12074313/image-report-2023.csv)
