### ISSUE TITLE
Generate report for any and all Cotsen Items within the Digital Repository

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5630]
### Summary
Original email included from Minjie below (@pmgreen was kind enough to email me about this request that was sent to him. Peter, this is the ticket!) . The location codes minjie is referencing are the prefix of the location field in figgy (example: 

Location | CTSN Eng 18 359
-- | --

From Minjie:
I don’t know what fields the CSV files will include. I would like to add three things about the form I filled out below.

1) As you know, 852 subfield tags have changed because of Alma migration. If the report is not based on refreshed metadata, might 852 be a mixed bag? If yes, I can take the whole 852 string and parse it myself.

2) About criteria. I need all items that have any of the Cotsen location codes, which are--
ctsn
ctsnrf
hsvc
xc (or previously rcpxc)
scactsn
scahsvc
xcr

3) I need one extra element in the report: the collections an item belongs to.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not stopping work and is not an urgent need, but it would be good to generate at some point within the next three weeks, if possible, while stakeholders are interested in curating their collections in figgy.
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by minjiec** [comment]
Hi, I see that no. 3 mentions "Collections" only. A longer list of fields I requested is in the OIT ticket. Let me list them here again for your convenience. Thanks!

_Elements I would like to have in the spreadsheet:_

- MMSID
- Title
- 852 $c (location code)
- 852 $k (shelving location)
- 852 $h (call number)
Special note: If the report is not able to obtain refreshed metadata, and will send a mixture of metadata from Voyager and Alma, then please just have one 852 field and I will parse it myself. Voyager ($b $c) and Alma ($b $c $k) have different subfields for locations in 852.
- 300 $a (page number)
- Total number of image files (i.e., the number listed after “Total files” in Figgy File Manager) I am hoping to use this value, in comparison with the number in 300$a, to filter items that have only a few selected pages digitized.)
- Collections (i.e., in which collections this item belongs to)

**Comment by kelea99** [comment]
Hi minjie! I copied and pasted from the email forwarded to me. apologies!

**Comment by hackartisan** [comment]
It would be very helpful to hear the full user story for this issue. What is the broader task that this data will enable?

We don't store marc data by subfield, so some of these data points aren't available from Figgy right now.

It may be possible to achieve the larger goal, however, with some other implementation.

@kelea99 can we talk more about this at a standup?

**Comment by minjiec** [comment]
Hello!

Cotsen Children's Library is grappling with one issue. We don't know what titles have been digitized, in full or only partially, from our collection. This happened since PUL adopted decentralized digitization practices and uploaded images from patron requests to Figgy as well. We would like to curate a DPUL collection <https://dpul.princeton.edu/cotsen> that contains all _complete_ digital surrogates of Cotsen's holdings.

I hope this explains the context of the request for report? We sorely need a good help with clearing up errors we keep spotting in DPUL concerning the organization of Cotsen titles. Keyword searching proves not reliable/exhaustive. Please let me know any further clarification we can provide. Thanks!

Minjie

**Comment by tpendragon** [comment]
I ran the report like this, and gave the output to Kim:

```ruby
docs = Blacklight.default_index.connection.get("select", params: {qt: "search", fl: "id, imported_location_tesim", qf: "imported_location_tes
im", "q.alt": "imported_location_tesim:(CTSN CTSNRF HSVC XC RCPXC SCACTSN SCAHSVC XCR)", defType: "edismax", rows: 10000})["response"]["docs"].map{|x| x["id"]
}.lazy.map{|x| ChangeSetPersister.default.query_service.find_by(id: x)}
report = CSVReport.new(docs, fields: ImportedMetadata.fields)
report.write(path: Rails.root.join("tmp", "report.csv"))
```

It's not pretty, but it's literally every field Figgy knows how to import or manages itself.

**Comment by minjiec** [comment]
Thank you Trey! It sounds like you found an innovated method for my problem. I look forward to receiving the csv file from Kim!
Best,
Minjie

**Comment by tpendragon** [comment]
I sent the updated report with file counts and collections to the CSV.

Script:

```ruby
docs = Blacklight.default_index.connection.get("select", params: {qt: "search", fl: "id, imported_location_tesim", qf: "imported_location_tes
im", "q.alt": "imported_location_tesim:(CTSN CTSNRF HSVC XC RCPXC SCACTSN SCAHSVC XCR)", defType: "edismax", rows: 10000})["response"]["docs"].map{|x| x["id"]
}.lazy.map{|x| ChangeSetPersister.default.query_service.find_by(id: x)}
fields = ImportedMetadata.fields
fields = fields.insert(2, :title, :collections, :file_count)
report = CSVReport.new(docs, fields: fields)
report.write(path: Rails.root.join("tmp", "report.csv"))

```

**Comment by minjiec** [comment]
Hello Trey!

Thank you for the Cotsen Figgy report you provided last month! I've reviewed it and am sharing my findings at 2023-04-Feedback-to-Cotsen-Figgy-report.gdoc<https://docs.google.com/document/d/19FQOdVKiboP_yxlfwbRNxnqEO3q1PIWZIZbpAOHIMFE/edit#heading=h.uox19gbi0w61>
It contains three parts.

I Issues I observed about the report

II Useful fields for future reports
Of the 357 fields, I identified 15 fields to be kept for future reports.

III Action: change collections for selected items
I checked items that need to be added to or taken out of collections, depending on whether the items are truly from Cotsen's holdings, whether they are digitized fully or in portion. Close to 130 items will be affected, so it had better be done by batch work if possible.

Please let me any questions. Thanks for your help!
Minjie

**Comment by minjiec** [comment]
As indicated in Section I-c of 2023-04-Feedback-to-Cotsen-Figgy-report.gdoc, the current report can’t seem to capture all Cotsen items in Figgy. 

> cotsen_report: 1241 items
> Figgy collection “Lloyd E. Cotsen”: 1598 members


Note the discrepancy of 1598-1241=357 items between the Figgy collection “Lloyd E. Cotsen” and cotsen_report.csv.

For the next report, could I obtain all items that are currently members of the following four collections? I would like to wait till _after_ the [suggested changes](https://docs.google.com/spreadsheets/d/1Zgyi9k2HXiouXn1qgkV_ek6a6ULLn55megVXmdZmUXY/edit?usp=share_link) have been made for the second report.

1. Lloyd E. Cotsen
2. Cotsen Children's Library
3. Cotsen (Welcome Additions Exhibition)
4. Soviet Era Books for Children and Youth

The fields needed are listed in Section II, or repeated here--

1. Id
2. Title
3. Collections
4. File count
5. Depositor
6. Visibility
7. Extent
8. Identifier
9. Date
10. Local identifier
11. Portion note
12. Source metadata identifier
13. Call number
14. Location
15. Downloadable

Thanks!
Minjie

**Comment by minjiec** [comment]
We have a mystery I am unable to solve. Wonder if you could help me and Andrea out there.
We notice that in the **Location** field of a Figgy record, there are two types of displays.

One type shows "Special Collection" and misses Cotsen's location codes, even though they are in the Alma holdings records. (I tried refreshing metadata and it didn't seem to help.)
![image](https://github.com/pulibrary/figgy/assets/54282275/25466e56-0cc4-4f60-8c8a-976767b61188)
([9947140843506421](https://figgy.princeton.edu/catalog/c1c755f3-34f3-4c62-b5dd-805d4972d755))

The other type shows the location code as found in holdings record 852$c
![image](https://github.com/pulibrary/figgy/assets/54282275/01780d07-59d9-44c1-b4d9-44e4c2f8f704)
([9947470923506421](https://figgy.princeton.edu/catalog/f8e8c4d6-90e1-43cc-991c-300f7b142d40))

Type 1 is a problem. Those records are missing from the report I requested based on location codes. Any thought on what caused this? Thanks!
Minjie
