### ISSUE TITLE
Generate report for any and all Graphic Arts items in Figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5631]
### Summary
Request by new Graphic Arts curator, Molly D.  Interested in any and all Graphic Arts materials in figgy. Assuming this will also be by location prefix but will confirm what all of those are.

This is a cataloging and catalog cleanup project.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation
Perhaps run at same time as #5630 ?
- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

There's postings for a job that is going out, and Kim needs to hand this report over by Friday.

**Comment by hackartisan** [comment]
@kelea99 We still need more information about the requirements here. It would be helpful to hear the full user story that's motivating this request.

Is there another way to get these records besides location code? Do we think there are records that are part of graphics are but aren't in the graphic arts collection?

And what data is needed about them?

**Comment by kelea99** [comment]
@hackartisan I can do a search in figgy to confirm that all items / most items are in the GA collection in figgy

**Comment by kelea99** [comment]
Requested Collections/Searches to run: 

- https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Treasures+of+the+Graphic+Arts+Collection
- GA: https://figgy.princeton.edu/catalog?q=%22GA%22
- GAX/Patron Requests: https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Patron+Requests&q=%22GAX%22

**Comment by kelea99** [comment]
_User story: As a Graphic Arts Curator that is new to PUL, I would like a report generated of any/all GA/GAX items in the digital repository. I am in the process of preparing for a large 3-6 year cataloging and digitization project for my materials and I would like to get a better idea:
1. How many items have been ingested in figgy from my collections
2. How many images (total) have been ingested in figgy from my collections
3. A CSV download of GA/GAX/"Treasures of the Graphic Arts Collection" items, containing:  The title, Source Metadata Identifier, Ark, Visibility, state, and call number
I will use this information to determine what collections should be targeted for digitization, metadata cleanup, or metadata creation._

**Comment by hackartisan** [comment]
Note that GA and GAX are partial location code values.

**Comment by kelea99** [comment]
Most are in the collection, but I found items that are graphic arts materials in patron requests that were not tagged. I could probably just do that and it would be easier to run the report on your end, then.

**Comment by hackartisan** [comment]
@kelea99 It sounds like for a generalizable solution we'll need to be able to handle this location code value specification.

**Comment by kelea99** [comment]
user story confirmed with Molly! She is also reviewing the two searches (listed above) outside of the Treasures of the graphic arts figgy collection. If all the items in those searches need to be added, I will do so and change the ticket to just generate a report for that one collection. Thank you, @hackartisan !

**Comment by kelea99** [comment]
Ok, folks!  Everything is moved into one collection, so only one report is needed.  Please run a report for:

[Treasures of the Graphic Arts Collection](https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Treasures+of+the+Graphic+Arts+Collection)

**Comment by tpendragon** [comment]
Threw together https://github.com/pulibrary/figgy/pull/5684 to extract the portion of this request that is "generate a CSV"

**Comment by tpendragon** [comment]
Created report and gave it to @kelea99 in slack.
