### ISSUE TITLE
Bug: fixity success count may be off

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5635]
Here we subtract fixity failures from total number of preservation objects

https://github.com/pulibrary/figgy/blob/b3ec9d7e8b77a04450b552e65e2b6a541fc183f9/app/wayfinders/base_wayfinder.rb#L136

however, one preservation object may correlate to fixity checks for more than one binary file, e.g. if a preservation and intermediate copy are both preserved.

**Comment by tpendragon** [comment]
We think it's okay.
