### ISSUE TITLE
Resources which had duplicate PreservationObjects deleted are no longer in preservation storage

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5642]
We have a list of FileSet IDs which had their duplicates deleted. We can re-preserve all of them.

ID File:

[resources.csv](https://github.com/pulibrary/figgy/files/10494247/resources.csv)

## Potential Strategies:

1. Delete the PreservationObject for all of those, and re-preserve them in a background job.
2. Manually call `Preserver#preserve_binary_content(force: true)` and `Preserver#preserve_metadata` for all of the above FileSets. We have to force it, because those POs already thing that they're preserved and it doesn't validate that against GCS.

**Comment by eliotjordan** [comment]
PreservationJobs completed.
