### ISSUE TITLE
Implement Resource Health Report Wireframe

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5644]
This should replace the preservation status indicators on the resource show page.

It will also remove the local fixity numbers in the members list for MVW.

Use the following mockup as guidance, but leave off the date from the text and don't implement the derivatives portion of this yet.

![](https://user-images.githubusercontent.com/609368/210654266-135f9cd6-c3e3-4743-b415-bee02a4ea246.png)

![](https://user-images.githubusercontent.com/609368/210654271-93ddded3-3269-4a64-843e-118dac024bb3.png)

![](https://camo.githubusercontent.com/3ea23f6d69428763332dd29bc0b9342043b0f7131e639ebf3e71a22f4286d676/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563626131356632653839633963336230633538653064312f39373864616335352d626363382d343261662d623963362d633364616639613235376364)

**Comment by tpendragon** [comment]
@sdellis Where can we find the icons you've used for this mockup?

**Comment by tpendragon** [comment]
Icon ticket is #5654

**Comment by tpendragon** [comment]
Blocked by #5654

**Comment by sdellis** [comment]
Health Report icons have been added to LUX ([see screenshots](https://github.com/pulibrary/lux/pull/416)):

    LuxIconDerivativesHealthy
    LuxIconDerivativesUnhealthy
    LuxIconFileHealthy
    LuxIconFileUnhealthy
    LuxIconLockClose
    LuxIconLockOpen
    LuxIconReportHealthy
    LuxIconReportUnhealthy
