### ISSUE TITLE
Some FGDC FileSets can't be preserved

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5652]
```
[Figgy/production] Google::Cloud::InvalidArgumentError: invalid: Provided MD5 hash "LjqvrSgZeFwUx9nTfrvfMg==" doesn't match calculated MD5 hash "OifSHT83wa5LzQdPeXv/Nw=="
```

We fixed this in the past so it won't happen for future FGDC files, but the past ones have bad checksums. Re-preserve every FGDC file to ensure they're right.

## Backtrace

    line 62 of [PROJECT_ROOT]/app/services/preserver.rb: preserve_binary_node
    line 50 of [PROJECT_ROOT]/app/services/preserver.rb: block in preserve_binary_content
    line 47 of [PROJECT_ROOT]/app/services/preserver.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/92882692)

**Comment by tpendragon** [comment]
We remember fixing this in the past, it may not be this. We might have to update checksums on old FGDC files.

**Comment by eliotjordan** [comment]
Ran `GenerateChecksumJob` and then `PreserveResourceJob` on all FGDC FileSets. This did not fix the issue, but I was able to list of FGDC FileSets that are generating these errors.
[failed_checksum_filesets.csv](https://github.com/pulibrary/figgy/files/11065226/failed_checksum_filesets.csv)

**Comment by eliotjordan** [comment]
I'm going to put this back in Ready and lower the priority.

**Comment by tpendragon** [comment]
Next step: Rerun PreserveResourceJob for the FileSets in the attached CSV, see if it errors still.

**Comment by eliotjordan** [comment]
Possible solution: re-ingest file sets

**Comment by eliotjordan** [comment]
Ran script to re-ingest failing fdgc.xml files. Ran cloud fixity check on several and they look good.

```
ids = []

CSV.foreach("/home/deploy/fgdc.csv") do |row|
  ids << row[0]
end

ids.each do |file_set_id|
  change_set_persister = ChangeSetPersister.default
  query_service = change_set_persister.query_service
  file_set = query_service.find_by(id: file_set_id)
  parent = Wayfinder.for(file_set).parent
  file_path = file_set.primary_file.file_identifiers.first.to_s.gsub("disk://","")
  file = IngestableFile.new(
          file_path: file_path,
          mime_type: "application/xml",
          original_filename: "fgdc.xml",
          copy_before_ingest: true,
          container_attributes: {
            title: "fgdc.xml"
          }
        )
  parent_cs = ChangeSet.for(parent)
  parent_cs.files = [file]
  change_set_persister.save(change_set: parent_cs)
rescue
  next
end

ids.each do |file_set_id|
  change_set_persister = ChangeSetPersister.default
  query_service = change_set_persister.query_service
  file_set = query_service.find_by(id: file_set_id)
  change_set_persister.delete(change_set: ChangeSet.for(file_set))
rescue
  next
end
```
