### ISSUE TITLE
Numismatics: Generate Report for any and all issues containing general "DOC" selection in citation field.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5668]
### Summary
Request from Elena Baldi, Byzantine cataloging specialist. She is needing a report generated of any and all issues that contain the general DOC selection in the dropdown for citations. There are options in that same drop down that are volume specific and she would like to add the more granular volume-level selection for all items.  This would also allow her to clean up the manually entered "part" data. 
MVP fields needed:
1. Issue #
2. Coin # (s)
3. Citation: Numismatic reference and Part

Example of issue with the general citation selection: 
https://figgy.princeton.edu/catalog/c584bd4d-2477-40e7-bb6b-4b09dfe83996

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Elena is here for one year. This is something she can work on while the Ruby-Athena conversation continues. Can this report be created in the same cycle as: #5627 , #5630 , #5631 ? 
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Term Position is in need of this report to start clean up work of data. 

## Success Criteria

When I go to a numismatic issue, I can click on the reference (for example DOC), and it will show me all issues that have that reference in a citation.

### Screenshots
![Screen Shot 2023-02-08 at 2 22 37 PM (2)](https://user-images.githubusercontent.com/45043014/217632684-76128103-2a3c-4cc3-b358-ad722dfcb212.png)

**Comment by hackartisan** [comment]
Implementation idea:

* Index numismatic reference
* Add an invisible facet for numismatic reference
* make the rendered version of a citation have a clickable reference -- link goes to search results page of all resources that have that same numismatic reference citation value.

Reading this ticket, it doesn't seem like we need a report necessarily -- just a way to get to these resources that need to be updated, so a set of search results might be more efficient for the task.

**Comment by tpendragon** [comment]
This got closed by 5703, but I don't think it's quite done yet - they need to be able to click the reference in Figgy to get all of them that have that reference, so they know which to edit.

**Comment by eliotjordan** [comment]
@kelea99 CSV reports for coins and issues with DOC references:

[coins_doc.csv](https://github.com/pulibrary/figgy/files/10923936/coins_doc.csv)
[issues_doc.csv](https://github.com/pulibrary/figgy/files/10923937/issues_doc.csv)

Re-open the ticket if they need anything else.

**Comment by kelea99** [comment]
This looks great, @eliotjordan ! Thank you so much! Sending to Elana now for review.

**Comment by eliotjordan** [comment]
Script used in the console.

```
query_service = ChangeSetPersister.default.query_service
issues = query_service.find_all_of_model(model: Numismatics::Issue); nil
issues_w_refs = issues.select { |c| c.numismatic_citation.present? }; nil

CSV.open("/home/deploy/issues.csv", "wb") do |csv|
  issues_w_refs.each do |issue|
    issue.numismatic_citation.each do |citation|
      if citation.decorate.decorated_numismatic_reference &&citation.decorate.decorated_numisma
tic_reference.short_title == "DOC"
        csv << [issue.title.first, citation.decorate.title, issue.id.to_s]
      end
    end
  end
end
```
