### ISSUE TITLE
Local fixity only runs on primary file

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5669]
Cloud preservation and thereby cloud fixity will run on more than one file per file set. Do we want them to behave differently? If so we should document it. If not we should bring them in line.

Success Criteria:

Run local fixity on everything that Cloud Fixity runs on.

To close this ticket:

- [x] run characterization on every FileSet that has an intermediate file.
- [x] store the child_id for local fixity events as the FileMetadata ID it ran against (or change the meaning of a failed local fixity check to be "one of the binary files failed figure it out")
- [x] delete all the old local fixity events
- [x] re-run local fixity on everything

**Comment by eliotjordan** [comment]
After looking into this, I recommend that we don't change the behavior of the local fixity job. Local fixity is checked on the primary file:
https://github.com/pulibrary/figgy/blob/main/app/jobs/local_fixity_job.rb#L94

which is one of either `original_file`, `preservation_file`, or `intermediate_file`:
https://github.com/pulibrary/figgy/blob/main/app/models/file_set.rb#L93

Similarly, the cloud preserver creates binary nodes for each of those file types:
https://github.com/pulibrary/figgy/blob/main/app/services/preserver.rb#L75

However, it seems to me that there is always only **one** primary file type per FileSet. Is this true?

Regardless, I feel that checking fixity only on the primary file is sufficient.

**Comment by tpendragon** [comment]
@eliotjordan A file can have a PreservationFile and an IntermediateFile, and both of those are hand-crafted files. If one of them disappears we can't get them back. PreservationFile is -more- important, but still.

For instance, hand-placed watermarks is one use case. We'd have to try to re-hand-place watermarks if we lost that intermediate file. Another is hand-crafted audio derivatives.

**Comment by tpendragon** [comment]
Eliot and I looked at this together, and found the following things:

* We don't calculate local checksums for IntermediateFiles. Characterization only runs on primary_file, and then the derivative services look at intermediate after that.
* Cloud preservation re-generates the checksum for every binary node it preserves the first time, which includes intermediate nodes. This means the cloud has a checksum value for preserved intermediate files, and is able to check that.

To close this ticket we'd have to do the following:

* Calculate checksums for intermediate files during characterization (maybe re-queue characterization when appending an intermediate file?)
* We'd have to run characterization on every FileSet that has an intermediate file.
* We'd have to store the `child_id` for local fixity events as the FileMetadata ID it ran against (or change the meaning of a failed local fixity check to be "one of the binary files failed figure it out")
* If we do the above, we'd have to re-run local fixity on everything again.

**Comment by eliotjordan** [comment]
Re-ran characterization on FileSets with both Preservation and Intermediate files. There are currently **1541** of these in Figgy.
