### ISSUE TITLE
Build UI to display the item and image count for a given collection over a given time frame

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5677]
This UI will allow someone to independently generate the reports like those requested in https://github.com/pulibrary/figgy/issues/5627.

## Implementation Options

1. Provide a facet for date created in search results and some summary of item and image count in that result set.

* Range slider for Date Created
  * There's a date range picker in lux we could use instead.
* Summary box? A button for "Reports"?
* It might take a long time for these numbers to be calculated, so that might be a complication here.
* @kelea99 also notes that users explicitly want a report they can send around.

2. Create a CSV export button for search results, include a summary row in that CSV that has "Image Count", "Resource Count", and "Megabytes". Email users when that report is ready (or something)

  * This solution also requires the date range facet for date created
  * Maybe include a totals row, and in each record row have "Image Count". Don't include "Resource Count", because we have no way to correlate "physical objects" to "digital representations."

**Comment by sdellis** [comment]
Date Range and Collection ID fields should be required and validated. No "since forever" start dates.
