### ISSUE TITLE
Failing microform ingests

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5679]
Ingests are failing for the following paths:
* /mnt/hydra_sources/microforms/new_ingest/993808393506421
* /mnt/hydra_sources/microforms/new_ingest/999930333506421
* /mnt/hydra_sources/microforms/new_ingest/992591563506421
* /mnt/hydra_sources/microforms/new_ingest/993809863506421

They should ingest as multi-volume works, each with a single volume.

To replicate, go to bulk ingest and select `microfilms/new_ingest` as the folder.

These failures came through as https://app.honeybadger.io/projects/53391/faults/83771929.

## Sudden priority justification
These errors are blocking ingest, and a new batch needs to go in. These in particular are patron request items.

**Comment by hackartisan** [comment]
Note that there is a reminder of directory structure requirements on https://figgy.princeton.edu/bulk_ingest/scanned_resource if you click "show example directory structure". feedback welcome on the contents of that help area.

**Comment by kelea99** [comment]
@roelmoon , please see @hackartisan 's information above. This is something to work through with Microforms to ensure the structure is correct. Can you walk through this with Natalie? The ingest should work, once directory structure is aok.

**Comment by roelmoon** [comment]
The structure used in this instance assumes future ingests as these are patron requests of a single roll from a multi-role collection. These four are the only four that didn't ingest from a larger bulk ingest that included multiple reels. All other ingests went through, so it appears that these ingests are the the only MVW ingests that are trying to go as single volumes.

**Comment by hackartisan** [comment]
Figgy is interpreting the numbers of the subdirectories as alma IDs. It interprets any number greater than 4 digits as an alma ID. If you want to get these in while we work on updating figgy, changing those subdirectory names should make it work.

**Comment by hackartisan** [comment]
Renaming the directories was used as a workaround. We should use #4977 to track updates to the alma ID validation.
