### ISSUE TITLE
StaleObjectError preventing resource deletion

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5683]
## Backtrace

    line 103 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: save
    line 36 of [PROJECT_ROOT]/app/controllers/file_sets_controller.rb: block in update
    line 135 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: block (2 levels) in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/87415141)

**Comment by hackartisan** [comment]
Actually I think this is okay. the resource isn't getting deleted but someone could go in and try again. doesn't look like there's a background job or anything.
