### ISSUE TITLE
Download options are cropped on UV with multiple tabs

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5709]
Flipping to the "Map" tab and fires a resize and the download options re-appear.

https://maps.princeton.edu/catalog/princeton-fq977x249

![Screenshot 2023-03-09 at 1 44 48 PM](https://user-images.githubusercontent.com/784196/224137060-05f75155-9c03-40f6-ba62-a45c99a00976.png)

**Comment by tpendragon** [comment]
Still happening: https://maps.princeton.edu/catalog/princeton-fq977x249

**Comment by sdellis** [comment]
I had another branch for this with a fix that was working. It seems to have been merged. It was a race condition, and I thought I had increased the timer for waiting for the element to display. I'll give it another shot. 
https://github.com/pulibrary/figgy/commit/356e915199e3a9c7e1366f8010130d7d739afc78

**Comment by hackartisan** [comment]
Yeah it looks like it was deployed, too. version.txt says `Branch main (at 05703a70f6a19ad66e11937d219a359249e7dbfc) deployed as release 20230630185652 by deploy`
