### ISSUE TITLE
Allow GeoTiff download option for single sheet GeoTiff

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5710]
Allow GeoTiff download option in the UV for for single sheet GeoTiffs.

Probably need to make an adjustment here:
https://github.com/pulibrary/figgy/blob/27cb7b25edcb20e7865b62a9414d5933d712ef09/app/services/manifest_builder/canvas_rendering_builder.rb#L26

Example in Maps Portal: https://maps.princeton.edu/catalog/princeton-dccz30q432r
Example in Figgy: https://figgy.princeton.edu/catalog/3af117c8-96d9-40b9-9aeb-783f41c9d48f
File that should be downloadable: https://figgy.princeton.edu/catalog/parent/c79243a8-3ef5-43a4-9403-736bef4c96d0/22d70018-0961-409f-a814-88d3a5c3473d

Note: This already works if there's multiple sheets (see code above), but doesn't work if there's only one sheet. That got implemented here: https://github.com/pulibrary/figgy/pull/5051

**Comment by hackartisan** [comment]
Need example record
