### ISSUE TITLE
Resources that have PDFs and no pdf derivatives are often broken, showing mirrored images

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/figgy#5714]
There are a few items in this collection that when the viewer window is expanded the images reverse, mirror and shrink.

I think these are ingested from webspace historically.

Examples:
[https://findingaids.princeton.edu/catalog/AC120_c0109](url)
[https://findingaids.princeton.edu/catalog/AC120_c0105](url)

## To Fix

Rerun all derivatives for resources that have one FileSet that is a PDF.

**Comment by tpendragon** [comment]
I think this is a bug with items that were PDFs, but they were ingested before we started processing PDFs into individual images. I regenerated derivatives from the file manager for the second one and I can't replicate now.

**Comment by tpendragon** [comment]
There were only a little over 1,000 of these, so I'm just regenerating derivatives for all of them.

Code to do so:

```ruby
csp = ChangeSetPersister.default
qs = csp.query_service

# Get all FileSets which are an original file (no PDF processing yet - the PDF
# derivative service changes them to preservation files)
resources = qs.custom_queries.find_by_property(property: :file_metadata, value: [{use: [Valkyrie::Vocab::PCDMUse.OriginalFile], mime_type: ["application/pdf"]}], model: FileSet)
resources.each do |file_set|
  parent = Wayfinder.for(file_set).parent
  # Make sure it's the only member of its parent
  if(parent.member_ids.length == 1)
    # CharacterizationJob will run the derivative job.
    CharacterizationJob.perform_later(file_set.id.to_s)
  end
end

```
