### ISSUE TITLE
RefreshRemoteMetadataJob didn't retry

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5715]
example: https://figgy.princeton.edu/catalog/e99c19bb-b873-49d5-a0cb-45ce5aa51daa -- was queued for refresh on 3/20/2034. The job failed but why didn't it retry? 

## Backtrace

    line 21 of [PROJECT_ROOT]/app/services/pul_metadata_services/client.rb: retrieve_from_aspace_pulfa
    line 12 of [PROJECT_ROOT]/app/services/pul_metadata_services/client.rb: retrieve
    line 71 of [PROJECT_ROOT]/app/models/remote_record.rb: client_result

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/87738526)

**Comment by hackartisan** [comment]
Recent occurrence definitely retried -- I can see the 2nd try in the log.
