### ISSUE TITLE
Error when cleaning up pdf derivatives

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5720]
Arguments on these jobs: 

- "a99cbcfe-953f-47f0-b7d1-d24ee032fcfc", "49b7f909-062f-49b2-b921-d2948d67fce4"
- "d301594a-984c-44ff-ae39-2731a0f3bab8", "e0936947-453c-4d32-8c5b-9cbff4eccbfc"
- "7beb0d7c-5fc2-4d39-bd6d-750561ef203a", "ba5e4a10-0f34-42d8-841c-91b649b019f9"
- "1fc90b19-ac92-43d4-a6d6-195cac48a1a2", "70e93d72-8345-41ad-8aef-43af7bbefd57"
- "20d8134a-0a90-4a80-9495-d5dd66c60236", "f0c69d41-8c81-472b-90e8-a642aab2bb56"
- "4ed8175b-063e-4318-b8f1-2df2ce84de3b", "b0d70b5f-7418-460a-9ae1-c8d2b8012fc1"
- "85dc2943-9f6c-4fba-a42d-2673caec4127", "1f935092-b42e-4341-91a8-e8512f508b59"
- "a44ed480-cd50-4f23-b432-da62fbd401bb", "a1fb0a85-6572-4ad5-b2c5-fbed82b724ec"
- "84b0d858-e5c6-44d5-8481-0ec3cbe95714", "0203c9dd-21d8-4b56-b85c-a46384b1295d"
- "69811343-052c-4ba8-8357-3276b0f8a82b", "506ff8c2-442e-472c-93f0-bf44b109c405"

They're all PDF file sets where the 2nd argument represents a resource that has been deleted.

## Backtrace

    line 84 of [PROJECT_ROOT]/app/wayfinders/base_wayfinder.rb: block in member_relationship
    line 54 of [PROJECT_ROOT]/app/derivative_services/pdf_derivative_service.rb: cleanup_derivatives
    line 15 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister/cleanup_pdf_derivatives.rb: run

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/94643850) 

```
 query_service.rb  102  find_members(...)
[GEM_ROOT]/gems/valkyrie-sequel-3.0.0.pre.beta.1/lib/valkyrie/sequel/query_service.rb:102:in `find_members'
  base_wayfinder.rb  84  block in member_relationship(...)
[PROJECT_ROOT]/app/wayfinders/base_wayfinder.rb:84:in `block in member_relationship'
  pdf_derivative_service.rb  54  cleanup_derivatives(...)
[PROJECT_ROOT]/app/derivative_services/pdf_derivative_service.rb:54:in `cleanup_derivatives'
  cleanup_pdf_derivatives.rb  15  run(...)
[PROJECT_ROOT]/app/change_set_persisters/change_set_persister/cleanup_pdf_derivatives.rb:15:in `run'
  change_set_persister.rb  238  block in before_delete(...)
[PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb:238:in `block in before_delete'
  change_set_persister.rb  237  each(...)
[PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb:237:in `each'
```

## Consequences

This error means that PDF FileSets never get deleted and are left as orphans.

## To Fix:

Look at this code and see if it can be fixed without getting the parent: https://github.com/pulibrary/figgy/blob/bdcab5b8cbfe6cb26b5ff364bbd4b71ed98e5431/app/derivative_services/pdf_derivative_service.rb#L53-L58

The scenario that's failing is I delete the parent resource that has a PDF and derivatives. Add a test for that - in this case you don't have to explicitly clean up the images, they'll get queued for deletion anyways.

**Comment by hackartisan** [comment]
I deployed the PR and deleted the 14 pdf filesets which were indicated by the honeybadger notice.
