### ISSUE TITLE
Convert lib-proc2/3 into Figgy workers

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#574]

**Comment by escowles** [comment]
@rmoon says they don't really need all three lib-proc1/2/3 machines, so we should confirm that we can take 2 & 3 to Figgy workers.

**Comment by roelmoon** [comment]
Confirming from the studio, we only need lib-proc1. If you take 2 and 3 as figgy workers, should they be relocated?

**Comment by escowles** [comment]
Sure, we can move them into the Systems suite somewhere.

**Comment by roelmoon** [comment]
Let me know where, I can arrange to have them moved. They can certainly stay in the studio but I assume you'd like them to have better UPS than the short battery backups we have them on now.

**Comment by escowles** [comment]
There's no rush to move them — we'll figure it out next week when we're all in town.
