### ISSUE TITLE
Implement New Structure Manager Interface

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#5741]

**Comment by sdellis** [comment]
Informed by [wireframes](https://xd.adobe.com/view/de230b48-d3c3-4fbc-9831-5515cf6545c6-8b70/) completed in #5395

**Comment by sdellis** [comment]
This work is in active development on the [struct-manager branch](https://github.com/pulibrary/figgy/tree/struct-manager).

**Comment by sdellis** [comment]
Remaining Tasks:

- [ ] Add a Zoom modal/trigger/key-command for inspecting thumbnails (in OSD) in both the tree and gallery components
- [ ] Add drag and drop to Tree
- [ ] Add cut and paste to Tree
- [ ] Add drag and drop between Gallery and Tree
- [ ] Add cut and paste from Tree to Gallery
- [ ] Save Structure to Figgy Database
- [ ] Create New Folder From Selection (in Gallery or Tree)
- [ ] What else?

**Comment by sdellis** [comment]
Bugs to squash... 

1. Can't select the Tree widget folders via keyboard
2. When confirming deletion of folder with sub-items, canceling doesn't seem to cancel

**Comment by sdellis** [comment]
From 10/26 Standup
- Do not allow Tree and Gallery items to be selected simultaneously. 
- Attach zoom button to Gallery card elements in Figgy (don't update Gallery in LUX)

**Comment by sdellis** [comment]
Issue: Second node in tree will not delete

**Comment by tpendragon** [comment]
Closed by #6205
