### ISSUE TITLE
Add Rights Statement to Bulk Ingest

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5751]
### Summary

The rights statement needs to be changed to Copyright Not Evaluated for finding aids material the studio's ingesting, but there's no way to do it from bulk ingest.

### Impact 

Would make bulk ingest significantly easier, so they don't have to bulk ingest to a new collection then bulk edit, or ingest one at a time. This was requested by the studio in #digital_studio.

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by kelea99** [comment]
@tpendragon , yup. It's a gret idea. I heard this same request for ephemera.

**Comment by tpendragon** [comment]
@kelea99 Did you set it asap? If so I need a sudden priority justification

**Comment by kelea99** [comment]
This is a MULE ticket. the sudden priority/etc.. need I interpreted from what you were saying about your conversations with the studio, and @roelmoon 's conversations with me re: AnnaLee's expectation to have all the patron requests default to that copyright statement.
