### ISSUE TITLE
Bulk ingest file renaming being overridden

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/figgy#5757]
Having an issue with some items in bulk ingest. I have 2 items that I am working with but there will be more.
https://figgy.princeton.edu/catalog/0ba117b8-2a60-4f60-9cda-f91b231f5577
https://figgy.princeton.edu/catalog/897c870d-17ca-4f3f-9b26-1a9431b5f7e2
I clicked the button to not rename the files but it did it anyways.

## Sudden Priority Justification

This is a core use case for bulk ingest that got broken by the bulk ingest page changes we implemented.

**Comment by tpendragon** [comment]
This was ingested from Mudd/AC116

it should look like https://findingaids.princeton.edu/catalog/AC116_c60112-61836
