### ISSUE TITLE
Add Derivative Health to Health Report

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5766]
See https://github.com/pulibrary/figgy/issues/5644

**Comment by tpendragon** [comment]
These are important to us but not preservation related, and we want to prioritize finishing preservation, so pulling these out of the cycle.

**Comment by tpendragon** [comment]
We keep track of if it's processed or not, if it's not we can say "Broken"

**Comment by hackartisan** [comment]
Questions.
1. Should the heading on a resource show page continue to be "Preservation Status: ..."? Or should it maybe be "Resource Health: ..." (values are "Healthy," "In Process," and "Needs Attention")
3. What about the error message that might be stored on a file? Seems like we should use `processing_status` to display "In Process" for the derivatives, and `error_message` to display "Needs Attention"
4. Do we still want the banner display that says "Files Processed: ..." at the top of a page? Do we want the health report to now incorporate that message? It would require an extra click to see it.

**Comment by tpendragon** [comment]
Standup decisions:

1. "Health Status"
2. Agreed.
3. Let's have both - the banner has more info and will be the thing that's stopping them from completing the resource.
