### ISSUE TITLE
[Figgy/production] RSolr::Error::Timeout: RSolr::Error::Timeout
URI: http://lib-solr8-prod.princeton.edu:8983/solr/figgy-production/update?wt=json&softCommit=true&versions=true
Request Headers: {"Content-Type"=>"application/json"}
Request Data: "[{\"id\":\"b9a687a8-f5e5-4627-a159-8c48563ae88a\",\"join_id_ssi\":\"id-b9a687a8-f5e5-4627-a159-8c48563ae88a\",\"created_at_dtsi\":\"2023-04-26T20:16:02Z\",\"updated_at_dtsi\":\"2023-04-26T20:16:43.795509Z\",\"internal_resource_tsim\":\"ScannedResource\",\"interna...

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5769]
## Backtrace

    line 100 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: block (2 levels) in buffer_into_index
    line 91 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: block in buffer_into_index
    line 90 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/95533325)

**Comment by hackartisan** [comment]
oops issue not needed
