### ISSUE TITLE
Can't view ephemera project or box

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5772]
[Figgy/production] NoMethodError: undefined method `template_label' for #<DeletionMarkerDecorator:0x00007f0c2fccf5f0 @object=#<DeletionMarker id=#<Valkyrie::ID:0x00007f0c2fcc4268 @id="b6f0ac43-3c95-45ae-88d2-2844ed648e43"> internal_resource="DeletionMarker" created_at="2023-04-14T16:24:51.871Z" updated_at="2023-04-14T16:24:51.871Z" new_record=false optimistic_lock_token=[#<Valkyrie::Persistence::OptimisticLockToken:0x00007f0c2fcc95b0 @adapter_id=#<Valkyrie::ID:0x00007f0c2fcc9600 @id="9205c983e9b1fa93f19f...

## Backtrace

    line 89 of [PROJECT_ROOT]/app/views/catalog/_members_ephemera_project.html.erb: block in _app_views_catalog__members_ephemera_project_html_erb__4110717268843592970_757100
    line 87 of [PROJECT_ROOT]/app/views/catalog/_members_ephemera_project.html.erb: each
    line 87 of [PROJECT_ROOT]/app/views/catalog/_members_ephemera_project.html.erb: _app_views_catalog__members_ephemera_project_html_erb__4110717268843592970_757100

View full backtrace and more info at honeybadger.io
* https://app.honeybadger.io/projects/53391/faults/95251961
* https://app.honeybadger.io/projects/53391/faults/95253553

Sudden priority:
This is an ephemera project that can't be viewed or worked on.

**Comment by eliotjordan** [comment]
Member EphmeraBox raises errors as well:
https://figgy.princeton.edu/catalog/24e5ac3b-96bd-43fb-a974-1d903bba2ba0
