### ISSUE TITLE
Characterization and derivative errors - autofix workflow

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5779]
This is spun off from the diagram on https://github.com/pulibrary/figgy/issues/5736. We currently track some error states during this process, but there appear to be times when we don't display an error state on a file that's broken. In addition, there are times when derivatives didn't get generated but they go through fine when we manually fix them. 

Goals are:
- Ensure we're displaying error states in any case where the file is broken or derivatives don't exist but should
- Do what we can to autofix issues. Display the correct status in health report and file manager during that process.

Draft diagram, started in #5736 

```mermaid
flowchart TD
    A(Preservation Error Occurs) --> B{What Type of Failure Event?}
    B -->|Derivative Generation| E[System re-runs derivative generation X number of times]
    E -->|If derivatives cannot be generated| O[Displays `Cannot fix, requires human attention`]
    O --> P{Can DLS fix?}
    P --> |YES| Q(DLS manually repairs until Display has no errors)
    P --> |NO| R(Display `Re-ingest Required`)

**Comment by tpendragon** [comment]
We'll have a service to remedy ones that are stuck in processing with #5582, most derivative and characterization errors can't actually be fixed if they make it past the system retries (we'd have to be down for 2 weeks for those jobs to fail out), and we don't think we'd get a high return for this work.
