### ISSUE TITLE
Reports Needed for 2 Collections (Patron Requests, Patron Requests Portions)

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5780]
### Summary
I need figgy reports generated for 2 collections (see below):
### [Patron Requests](https://figgy.princeton.edu/collections/b7e8c42b-6fd0-4cfb-bc6d-b5e5a5c79f5c/manifest) (NOT including Microfilm)

Total Image Counts for itemized visibilities (Open, Private, Princeton Only, Reading Room)

05/01/2022-05/01/2023 ingests (NOT including microfilm)
- Total Image Counts for itemized visibilities (Open, Private, Princeton Only, Reading Room)
- Total titles count for visibilities (Open, private, prinecton only, reading room)

### [Patron Request Portions](https://figgy.princeton.edu/collections/a5454850-8b97-4750-8390-2c5884134f1f/manifest)

Total image counts for itemized visibilities (Open, Private, Princeton Only, Reading Room)

05/01/2022-05/01/2023 ingests
- Total Image Counts for itemized visibilities (Open, Private, Princeton Only, Reading Room)
- Total titles count for visibilities (Open, private, prinecton only, reading room)

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Not stopping work, but would help greatly to have for a meeting.
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Requested for meeting on 05/02/2023

**Comment by tpendragon** [comment]
Done. The script was this:

```ruby
csp = ChangeSetPersister.default
query_service = csp.query_service
collection_id = "b7e8c42b-6fd0-4cfb-bc6d-b5e5a5c79f5c"
collection = csp.query_service.find_by(id: collection_id)
members = Wayfinder.for(collection).members
# Filter out microfilm
members = members.select do |member|
  !Array.wrap(member.call_number).any? { |x| x.to_s.include?("MICROFILM") }
end
# Filter out anything that is a volume
members = members.select do |member|
  Wayfinder.for(member).parent.blank?
end
# Filter out anything before May 1 2022
members = members.select do |member|
  member.created_at >= Time.new(2022, 0o6, 0o1)
end
members = members.group_by { |x| x.visibility.first }
result = Hash[
  members.map do |visibility, visibility_members|
    file_set_counts = visibility_members.map do |mem|
      query_service.custom_queries.find_deep_children_with_property(
        resource: mem,
        model: FileSet,
        property: :file_metadata,
        value: nil,
        count: true
      )
    end
    file_set_counts = file_set_counts.sum
    [visibility, { image_count: file_set_counts, member_count: visibility_members.length }]
  end
]
```

It outputted something like:

```ruby
{"restricted"=>{:image_count=>39895, :member_count=>414},
 "open"=>{:image_count=>299841, :member_count=>881},
 "reading_room"=>{:image_count=>2448, :member_count=>87},
 "authenticated"=>{:image_count=>1395, :member_count=>12}}
```

Restricted is private, authenticated is Princeton only. I adjusted the collection ID and which filters were used appropriately.

**Comment by kelea99** [comment]
THANK YOU!!!!
