### ISSUE TITLE
EphemeraFolder / EphemeraBox / Recording are all preserving before completion

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5787]
Resources with the the draft/complete workflow, such as recordings, should be preserved when marked complete.

EphemeraFolder has its own workflow with `needs_qa` and `complete`.
https://github.com/pulibrary/figgy/blob/ee4c675b0373681f55e054950901724c91261d7b/app/models/folder_workflow.rb#L7-L8

EphemeraBox also has its own workflow 
https://github.com/pulibrary/figgy/blob/ee4c675b0373681f55e054950901724c91261d7b/app/models/box_workflow.rb#L5-L9

EphemeraBoxes should be preserved at the `all_in_production` state.

Discovered as part of #5557

**Comment by kelea99** [comment]
Images are added after, at the very least, the MVP metadata.  Do we have variations of preservation for specific things? ex: we would have local fixity on in process stuff and do the full preservation once complete? i.e. keep it from the cloud until completion? Is that silly?

**Comment by hackartisan** [comment]
Before completion, it is backed up (the isilon is backed up to AWS). At completion, it is preserved, and will be recoverable via the deletion marker UI.

We decided to use the complete state to trigger preservation, as initially proposed in this ticket.
