### ISSUE TITLE
Prevent deletion of Numismatics resources until all related resources are detached

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5793]
For the following resource types, prevent deleting a resource until all related resources are detached:

Numismatics::Monogram
Numismatics::Accession
Numismatics::Firm
Numismatics::Person
Numismatics::Place
Numismatics::Reference

Related to https://github.com/pulibrary/figgy/issues/5557

**Comment by tpendragon** [comment]
We're deprioritizing this, because we're currently able to restore these items back to their original resources since it doesn't clean up relationships when they're deleted. That being said, we should do this so we can make it so the relationships are cleaned up.
