### ISSUE TITLE
Restored member of map set should not show in search results

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5795]
To replicate:
* Delete a scanned map member of a map set (e.g. https://figgy-staging.princeton.edu/catalog/b4d9cbc0-b6a2-40fc-8655-31fab2d38563)
* Restore the member using the deletion marker search UI
* Go to the search results page, see the restored member listed.

Expected behavior: A member of a map set should not show in search results, only its parent should show.

Discovered during fire drill exercise, #5557

**Comment by eliotjordan** [comment]
Did a couple of tests in staging and the restored ScannedMap children of a MapSet to do not appear in the search results. Which is the intended behavior. Closing this ticket.
