### ISSUE TITLE
Collections do not restore from deletion

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5798]
Behavior observed: You can find the collection's deletion marker in the deletion marker search UI, and you can click its "restore" button. Then you get a flash message saying it is queued for restoration. However, it does not restore and its deletion marker continues to be listed in that search UI.

Question: Since you can only delete a collection once it's been emptied, is there a use case for restoring a collection? Do we want to make this work or do we want to make it not available as a restore target?

Discovered during fire drill exercise, #5557

**Comment by tpendragon** [comment]
We're going to try to fix this because we're not sure why it's broken, which means it could affect other things.
