### ISSUE TITLE
Add Attach Files into Vue Filemanager

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#580]

**Comment by sdellis** [comment]
@escowles I'm able to trigger the Browse Everything file select from Vue, but I'm not exactly sure how Browse Everything is supposed to work. I click "Upload from Server" and select some files and then I see a list of "Pending Uploads". Is it working in Figgy or broken? If it's working, is this supposed to refresh with the upload progress, or is there some other way I'm notified? Do I need to click something else that I'm not seeing?

**Comment by tpendragon** [comment]
You don't get notified, you just refresh and the list goes down.

**Comment by sdellis** [comment]
Ok, well that's unintuitive. Let me look into integrating that better. Not sure how yet, but we'll see. Thanks for the quick response.

**Comment by tpendragon** [comment]
We intended to make it auto-refresh at one point, but since it's such a long process they tend to just kick it off and go away, so it's not really a priority.

**Comment by sdellis** [comment]
Uploads are possible in Vue Filemanager now, however, I need to add a way to view pending files.
