### ISSUE TITLE
Remove code autocomplete on production

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5800]
Anna and I really don't like it.

**Comment by tpendragon** [comment]
What's a code hint?

**Comment by eliotjordan** [comment]
Autocomplete in vim.

**Comment by hackartisan** [comment]
It shows suggestions as you type and it's very hard to backspace when they're popping up.

**Comment by hackartisan** [comment]
We think this is a rails feature. Need to figure out how to turn it off.

**Comment by eliotjordan** [comment]
We need an `.irbc` file in the project or in the deploy user home directory.

`IRB.conf[:USE_AUTOCOMPLETE] = false`

https://docs.ruby-lang.org/en/master/IRB.html#module-IRB-label-Configuration
