### ISSUE TITLE
Error during Ephemera Box when Deleting and Restoring from Deletion Marker

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5801]
## Backtrace

    line 19 of [PROJECT_ROOT]/app/views/catalog/_admin_controls_ephemera_box.html.erb: block in _app_views_catalog__admin_controls_ephemera_box_html_erb__3728865529703011451_41212240
    line 17 of [PROJECT_ROOT]/app/views/catalog/_admin_controls_ephemera_box.html.erb: each
    line 17 of [PROJECT_ROOT]/app/views/catalog/_admin_controls_ephemera_box.html.erb: _app_views_catalog__admin_controls_ephemera_box_html_erb__3728865529703011451_41212240

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/95902818) 

Discovered during preservation fire drill, #5557

**Comment by sdellis** [comment]
[Figgy/staging] NoMethodError: undefined method `template_label' for #<DeletionMarkerDecorator:0x00007f9cac923628 @object=#<DeletionMarker id=#<Valkyrie::ID:0x00007f9cac918318 @id="2c6cc180-00c4-4c86-83e2-b8bd276c6177"> internal_resource="DeletionMarker" created_at="2023-05-11T18:11:12.930Z" updated_at="2023-05-11T18:11:12.930Z" new_record=false optimistic_lock_token=[#<Valkyrie::Persistence::OptimisticLockToken:0x00007f9cac923808 @adapter_id=#<Valkyrie::ID:0x00007f9cac923858 @id="968fb44a1dd16a6b8285025...

**Comment by tpendragon** [comment]
Closed by #5821
