### ISSUE TITLE
Errors when restoring Ephemera Project

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5802]
## Backtrace

    line 20 of [PROJECT_ROOT]/app/characterization_services/null_characterization_service.rb: valid?
    line 9 of [PROJECT_ROOT]/app/jobs/characterization_job.rb: block in perform
    line 92 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: block (2 levels) in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/94999588)

discovered while working on fire drill, #5557

**Comment by sdellis** [comment]
In one case, we were able to find the restored project, but got an error when trying to view it. In another case, the project said it was restored, but it was not and the deletion marker persisted.

One of the errors:
[Figgy/staging] NoMethodError: undefined method `mime_type' for nil:NilClass

**Comment by hackartisan** [comment]
This is no longer observed. projects do restore, but without their members. created https://github.com/pulibrary/figgy/issues/5928 for that.
