### ISSUE TITLE
GeoServerPublishJobs are erroring

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5808]
[Figgy/production] ArgumentError: wrong number of arguments (given 1, expected 0; required keywords: workspace_name, file_path, id)

## Backtrace

    line 12 of [PROJECT_ROOT]/app/services/geoserver_publish_service.rb: create
    line 21 of [PROJECT_ROOT]/app/services/geoserver_publish_service.rb: update
    line 16 of [PROJECT_ROOT]/app/jobs/geoserver_publish_job.rb: block in perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/95833926)

**Comment by eliotjordan** [comment]
Ruby 3 requires that keyword args be unpacked with the double splat operator when passed through `send`:

https://github.com/pulibrary/figgy/blob/79b7d1073f3b45ba7e5daad7308ac00a3bd984f4/app/services/geoserver_publish_service.rb#LL12C29-L12C42
