### ISSUE TITLE
Implement Preservation Errors on FileSet items in File Manager UI 

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#5824]
Implements [#5528](https://github.com/pulibrary/figgy/issues/5528#issuecomment-1398705984)

### Expected Behavior
This mockup provides preservation error messaging given that there may be several types of errors on a given fileset, that preserved filesets should display "preserved", and cards should remain the same size. The errors and warnings stack on top of each other below the thumbnail. 

We will need to display the following possible error messages:

- Repairing Derivatives
- Repairing Local Fixity
- Repairing Cloud Fixity
- Derivatives Failed | Report
- Local Fixity Failed | Report
- Cloud Fixity Failed | Report

![filemanager-fixity5](https://user-images.githubusercontent.com/609368/236327234-d679073a-9156-43fd-a80b-818060def9f5.jpg)

One thing to note is that a user may "Report" a fixity failure to DLS to try to fix. Clicking that link will generate a Honeybadger notification with the `user's id`, the `filemanager page URL`, and the `ID of the problematic fileset`. This will allow us to easily create a GitHub ticket with the click of a button. The "Report" link will not generate events or save state to the server.

Team consensus is that, at a minimum, there will be some system notification to the user that the issue was reported. This may be a flash alert or in-place animation that confirms it was successfully reported (or not). The state of which files have been reported would not be saved on the server. 

Note: If state is not saved, it could be hard for a user to know which issues have been reported or not if there are a lot of errors in the Filemanager interface. We could mitigate this confusion by storing ids that have been reported locally on the client, saving the state at least for the duration of the user's session or until they clear their cookies. However, this could be added later if the use case arises and should not get in the way of closing  this ticket.

**Comment by hackartisan** [comment]
https://github.com/pulibrary/figgy/pull/6003 is the initial implementation. It needs to be refactored for performance. @eliotjordan's idea was to use a single query to get deep child fixity status per resource (maybe by updating the deep_cloud_fixity_count query to return the list of resources rather than just a count) instead of one query per file set.
