### ISSUE TITLE
Add ability to represent non-image-based files in Vue Filemanager

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#583]
@escowles At the moment, are we trying to represent files other than images and geo-related xml?

**Comment by escowles** [comment]
No — we'll have audio and video files soon-ish, but we can determine how to represent them (and whether they should have a different file manager or no file manager) as part of that.

**Comment by sdellis** [comment]
Ok, cool. Not to be overly critical, but I actually find the "Extract Metadata" Geo-XML process that @eliotjordan showed me yesterday to be strange and unintuitive. It seems shoved into this filemanager shoe, but it doesn't really fit. 

I'm not sure I have a better alternative at the moment, but going forward I'd like to see us think more about the UX of these features before they are implemented. UX and design work needs to happen up-front (or at least in tandem), but it's been squeezed in after the fact on the last few projects I've worked on. I just don't want to see this become a pattern.

**Comment by eliotjordan** [comment]
I understand the confusion about this, but it does seem to be an improvement (to me anyway) from where it existed before, which is on the the work edit page with files listed on a dropdown menu. The "Extract" button could be located on the show page for the FileSet that contains the metadata file, accessible via the File Manager, but this just seems like adding an extra step for the user.

As a side note, much of the UI/UX in Figgy was pulled from Plum which derives much of it's UI/UX from Hyrax (Sufia). Many of these concerns are ones that the wider Samvera community shares as well. We could have started 100% from scratch with Figgy, but there was a real need to get a performant alternative running as quickly as possible.

**Comment by sdellis** [comment]
Yes, I'm sure my perspective is limited, and my thoughts were not meant to be critical of anyone's work to date. It's obviously more complicated when trying to balance the Samvera community needs, expectations, and previous work. 

I do think we should have a live discussion at some point about how we can get UX and design work into the process earlier though because in the long run I think it can save us time and make for a better product.  Anyway, I'm certainly grateful to be on this project. Happy Thanksgiving!

**Comment by tpendragon** [comment]
I wonder if we should close this until we have a more solid use case? @escowles @hackmastera @sdellis @eliotjordan ?

**Comment by escowles** [comment]
I think now that the non-image files are accessible in the File Manager, we can close this.

**Comment by sdellis** [comment]
But isn't this one of the reasons I'm rewriting the Order Manager to not use IIIF manifests? For reordering/labeling non-image-based files?

**Comment by hackmastera** [comment]
Perhaps https://github.com/pulibrary/figgy/issues/1178 covers this same ground from the perspective of a more specific use case?

**Comment by escowles** [comment]
@sdellis I thought the main reasons we were rewriting the order manager were to (1) improve the overall user experience, and (2) have a consistent API for reading/writing that could be portable beyond Figgy.  Adding the ability to manage files that aren't part of the manifest is one request that's part of 1 and enabled by 2.  But when we've talked about how these resources should be handled, we haven't reached consensus.  The one use case we have now (Geo metadata files) is handled by the file manager.

I'm fine keeping this ticket open as a "nice-to-have" enhancement over having the separate file manager.

**Comment by sdellis** [comment]
@hackmastera I think that #1178 is simply the ability for MediaResources to use the OrderManager, right? If that's the case, I don't thing it covers the same ground.

@escowles I don't think either of those statements are accurate.  Generally speaking, the user experience remains the same between the two versions. The only experience that improves is that users will have the ability to order/relabel Sammelbands in OrderManager. We also get the ability to reorder audio and video files (and other non-image files, should there be a need). This is important if a box of tapes gets digitized and they need to play in a specific order. 

Although OrderManager will be easier to install in non-figgy apps, it now uses a custom API rather than the IIIF standard, so I'm not sure whether it's a portability win or not. 

I'm going to keep this open until I finish.

**Comment by hackmastera** [comment]
From conversation here, it looks like several of us were confused between the order manager and the file manager. Ultimately it seems like this issue, regarding the file manager, is indeed closed. There's a new ticket for the vue order manager: #1709
