### ISSUE TITLE
Upgrade Redis

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5830]
We run redis locally on the Figgy machines.

The following process will upgrade redis to 7.2.1

Staging:

- [x] create a PR that updates lando to use redis 7. everything else is in good shape (including sidekiq version)
- [x] turn off workers for the app
- [x] Note the number of jobs processed today on the sidekiq dashboard (3)
- [x] Enqueue some jobs (3)
```
bundle exec cap staging rails:console
GenerateChecksumJob.perform_later("bec65df0-8327-4a18-a465-a6187fcc0954")
GenerateChecksumJob.perform_later("951ba06d-31e1-498c-a842-ccdca6e69952")
GenerateChecksumJob.perform_later("b247f29c-59e5-4522-9e71-f8ec5e50eb08")
```
- [x] check out https://github.com/pulibrary/princeton_ansible/pull/4310, then run `ansible-playbook playbooks/figgy_staging.yml --tags redis`, then run `ansible-playbook -e host_group=figgy_staging playbooks/upgrade_redis.yml`
- [x] Ensure the workers are still off, and the jobs above still enqueued.
- [x] check that it can connect like `redis-cli -u redis://figgy-staging2.princeton.edu:6379/0 INFO`
- [x] deploy figgy. This will also restart workers.
- [x] check the number of jobs processed; it should go up otherwise we've lost redis data

If it worked, proceed to prod. If not, we'll need readonly time.

Prod:

- [x] turn off workers for the app
- [x] check ansible branch, then run the app's usual ansible playbook with redis tag, then run the upgrade_redis playbook.
- [x] deploy main. This will also restart workers

**Comment by hackartisan** [comment]
looks good on staging. We can run prod without fear of losing jobs.

**Comment by hackartisan** [comment]
done
