### ISSUE TITLE
Allow "Extract Metadata" option for Geo-XML files in Vue Filemanager

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#584]
There should be a PUT request somewhere for merging this data with a scanned map resource...

**Comment by sdellis** [comment]
Decided to punt on this for the time being and keep the old filemanager in place for Geo works. We should revisit the best approach for this feature.

**Comment by hackmastera** [comment]
@eliotjordan is this still relevant?

**Comment by eliotjordan** [comment]
No longer relevant.
