### ISSUE TITLE
[Figgy/production] Notice: FileAppender: Failed to append the new file fgdc.xml

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5856]
Title was: [Figgy/production] Notice: FileAppender: Failed to append the new file fgdc.xml for 529bcc8c-cfb2-45a7-81e8-4edd843aa69d to resource 299512fb-73e1-4750-b172-0ab80e1d68f8: No such file or directory @ rb_sysopen - /opt/repository/files/11/c5/c5/11c5c5323878432e81008c7f85b178a2/pa_hous.xml

What should we do when we get this notice?

## Backtrace

    line 137 of [PROJECT_ROOT]/app/services/file_appender.rb: rescue in create_node
    line 114 of [PROJECT_ROOT]/app/services/file_appender.rb: create_node
    line 144 of [PROJECT_ROOT]/app/services/file_appender.rb: block in file_nodes

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/95398408)

**Comment by eliotjordan** [comment]
This particular append file issue resolved.
