### ISSUE TITLE
Rasters with parents and no (good) title are synchronizing to the maps portal

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5858]
https://maps.princeton.edu/catalog/princeton-dcv118rq98t

https://maps.princeton.edu/?utf8=%E2%9C%93&search_field=all_fields&q=Raster

I think when we bulk ingest ScannedMaps with a raster file for mosaics that we name the resulting raster resource "Raster." The assumption was that these wouldn't be discoverable in the maps portal - they'd just be accessed via the parent resource. Why are these showing up in the maps search results? Can we hide them?

**Comment by eliotjordan** [comment]
Reindexed.
