### ISSUE TITLE
Health report taking 10 minutes to render for ephemera project

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5859]
See https://app.datadoghq.com/apm/trace/2136465316698227896?colorBy=service&env=none&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=4232283646328833803&spanViewType=metadata&timeHint=1685653820682.003

and 

https://figgy.princeton.edu/catalog/1e722b00-8876-4a94-9092-ece7007e9894

**Comment by hackartisan** [comment]
Yeah I agree with disable checking on projects.
