### ISSUE TITLE
CloudFixityJob creating duplicate current metadata_node events

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5873]
https://figgy.princeton.edu/catalog/b20d4f94-bc2c-4fae-b8da-a51ebc785dc6 has three metadata_node current: true events.

This is because the CloudFixityJob repairs resources by re-preserving, but re-preserving creates a new MetadataNode, which means every event that gets made for `metadata_node` has a different `child_id`, and the following code always returns an empty array:

https://github.com/pulibrary/figgy/blob/60e337aa98fe78ba25d396ed70f5af8e9c57ac0f/app/jobs/cloud_fixity_job.rb#L65-L77

## Implementation Notes

I think we can fix this by not querying for child_id if it's a `metadata_node` - there's never two metadata_nodes, unlike for `binary_nodes`.

**Comment by hackartisan** [comment]
should we have more unique indexes?
