### ISSUE TITLE
Titles in show view should show up on different lines instead of joined by `and`

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#588]
Figgy:
<img width="263" alt="screen shot 2017-11-22 at 8 16 35 pm" src="https://user-images.githubusercontent.com/2806645/33158819-1b5ec072-cfc2-11e7-9831-1a5f293d0e90.png">

Plum:

<img width="170" alt="screen shot 2017-11-22 at 8 16 38 pm" src="https://user-images.githubusercontent.com/2806645/33158821-21099f10-cfc2-11e7-9e76-a1b0d000e517.png">

**Comment by escowles** [comment]
In the breadcrumb area, we probably want to use the first title.

In the header above, we want all the titles to display, each on its own line (to gracefully handle RTL text)

**Comment by hackmastera** [comment]
Probably a different issue, but it's weird to have a breadcrumb with no links in the case where there's not a parent.

**Comment by hackmastera** [comment]
Other places that use header:
* member lists (substitute semicolon-separated list? so translated values will be shown?) (e.g. https://github.com/pulibrary/figgy/blob/master/app/views/catalog/_members_multi_volume_work.html.erb#L15)
* https://github.com/pulibrary/figgy/blob/master/app/models/concerns/linked_data/linked_ephemera_folder.rb#L84 ? use one-line list?
* https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder.rb#L50 ? one-line list?

**Comment by hackmastera** [comment]
uses of `heading` (currently implemented as first title):
* https://github.com/pulibrary/figgy/blob/master/app/document_presenters/valkyrie_show_presenter.rb#L4 used by blacklight (catalog_helper) to set heading on record page

that's really the only one I guess; I'll change this directly to insert the newlines

**Comment by hackmastera** [comment]
Not sure how that manifest `to_s` is used; that method isn't in plum. The manifests themselves look different in the label: https://plum.princeton.edu/concern/multi_volume_works/pb5647p872/manifest vs https://figgy.princeton.edu/concern/scanned_resources/9c145976-1525-4047-80dd-49a4b27d2457/manifest will look into how that's done.

**Comment by hackmastera** [comment]
remaining instances of the sentence format that I've noticed:
- [ ] manifest label
- [ ] search results show view (not sure where this comes from; it may be that blacklight uses 'header' and I'll just need to finally change how that's formatted (in plum it's separated with a comma)

**Comment by hackmastera** [comment]
I sort of think plum was doing the manifest label wrong. it seems like it should be a string. http://iiif.io/api/presentation/2.1/#label
