### ISSUE TITLE
Ephemera Forms:  L=>R English and R=>L original script descriptions needed for items in Ephemera

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5886]
### Summary
For multi-lingual collections,   Deborah Schlein and Gilda Modjtahedi have illustrated the need for two separate descriptions in the ephemera form.  One box or two boxes would need to display the English description, while the other would need to be able to display a Right aligned, R=>L script of the original Persian/Farsi.  

- If there were 2 separate description boxes, this may prove easier to do. 
- A need would also be selection of Right versus Left aligned script for the description box (but this seems to be done automatically by script).
- At the least: A need for carriage returns in description box (separate ticket??) and Left or right alignment automatically assigned by the script directly after carriage return.

### User Story
As a Figgy Ephemera metadata creator for R=>L script languages , I need a space in the figgy ephemera form to put two descriptions:

- A description of the item/items in the language of the country of origin.  Reasoning of importance: The item/items should be accessible to groups who speak/read and/or identify with the language reflected in the item being described, especially if the descriptions have been provided by the creator of the work.
- A description of the item/items in english. Reasoning of importance: The item/items should also be accessible in english, to broaden the scope of global discovery in our applications, their access, and use.

Two separate containers for description would be ideal, due to the alignment of the text for Western versus R=>L language scripts. This appears to be done automatically in the current form, using the first script as an indicator of alignment.  As a builder, I would like the ability to align the text in the description box according to script, if this is not done automatically for me with multiple scripts in one box. if 2 separate scripts are in one box, a carriage return at the least would be needed. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
There are no hard deadlines, but this collection is particularly timely,  showing born digital artwork highlighting the protests and dissent in Iran. 
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize (potential MULE ticket? what to do here?)

## Sudden Priority Justification

They'd like this project to ship at the end of the year, but can't if the descriptions are all squished together. We can look at this during a maintenance cycle.

### Expected behaviour
I would have two separate boxes to write descriptions in English translation/original Farsi within the edit form of ephemera folders.
I would be able to Right or Left align the text for the description box.

### Actual behaviour
I have one box to write both the farsi and English in, with no option to carriage return. example: https://figgy.princeton.edu/catalog/parent/82624edb-c360-4d8a-b202-f103ee639e8e/35367c95-0b5b-4e9f-8b11-bf229aaae4a3

### Screenshots
<img width="1512" alt="Screenshot 2023-06-28 at 1 52 11 PM" src="https://github.com/pulibrary/figgy/assets/45043014/ab0097f1-e44a-4b29-95a5-29e2c65f963f">

**Comment by tpendragon** [comment]
@kelea99 Which resource is that?

**Comment by kelea99** [comment]
add as mule ticket for next cycle if possible.

**Comment by kelea99** [comment]
also an addition to the ephemera form. perhaps both can go in as mule request? https://github.com/pulibrary/figgy/issues/5996
