### ISSUE TITLE
Generate a report of all Figgy resources which have MMS-IDs that no longer resolve in the catalog

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5897]
Message from Minjie:

I am examining Patron Requests items in Figgy to scavenge for titles scanned from Cotsen's collection but not marked so, and chanced upon some odd cases. The Figgy items have Source Metadata Identifier listed, but when I click on the hyperlinked MMSID, Blacklight can't open the page. I threw a few in Alma to check if these are suppressed bibs--they are not. I can give you the list of MMSIDs if anyone would like to look into it. Many seem to be Graphic Arts materials
[10:00](https://pulibrary.slack.com/archives/C9Z0ZR5UY/p1689094802578269)
For example, MMSID "[99106510843506421](https://catalog.princeton.edu/catalog/99106510843506421)" linked from Figgy item titled [Lillian Gish](https://figgy.princeton.edu/catalog/000833dd-bacd-4662-8d82-19e5ce24e867)
[10:01](https://pulibrary.slack.com/archives/C9Z0ZR5UY/p1689094860355559)

would it be possible to get a report of the Figgy records with these phantom MMSIDs? Don Thornbury would like to troubleshoot a bit.

For any ghost records, Don would also like a dump of those records' metadata. We should be able to do something similar to https://github.com/pulibrary/figgy/issues/5630#issuecomment-1458856544

They want these fields:

```
Id
Title
Collections
File count
Depositor
Visibility
Extent
Identifier
Date
Local identifier
Portion note
Source metadata identifier: Could the value of this field be kept as text strings and thus be prevented from conversion to the scientific number format?
Call number
Location
Downloadable
```

## Sudden Priority Justification

Minjie's tasked with finding these ghost records, and we'd like to enable her to get her work done.

**Comment by doncat** [comment]
The .csv file should work just fine for my metadata purposes.  The small Graphic Arts set includes 2 deleted records.  As of now, it looks like the others never made it to Alma in the first place.  So any and all descriptive fields will be useful.

**Comment by minjiec** [comment]
Reminder to recepient of the report: Opening the .csv directly in Excel risks corrupting the MMSID, which may be converted to scientific notations. [Import it](https://answers.microsoft.com/en-us/msoffice/forum/all/data-corruption-issue-when-editing-csv-files-with/b2e8a31e-12fc-4d39-9fbd-435b9d832865) instead to avoid the corruption.

**Comment by tpendragon** [comment]
We're unable to do this report this month, because we're hitting an Alma API limit.

**Comment by minjiec** [comment]
What triggered this request were the following MMSIDs, which display in Figgy but can't be found in Alma. (I found them among Patron Requests, by the way.)
9940737833506421
99106510693506421
99106510703506421
99106510713506421
99106510723506421
99106510733506421
99106510743506421
99106510753506421
99106510763506421
99106510773506421
99106510783506421
99106510793506421
99106510803506421
99106510813506421
99106510823506421
99106510833506421
99106510843506421
99106510853506421
99106510863506421
99106510873506421
99106510883506421
99106510893506421
99122816063506421

**Comment by hackartisan** [comment]
Check on the API limit. If we're clear, work this ticket.

**Comment by tpendragon** [comment]
I have a query running in a tmux session in lib-proc7, should take ~ 2.5 hours.

**Comment by tpendragon** [comment]
All MMSIDs that don't resolve:

[failed-ids.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0t2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be50a481572501de57e80c174b1b94046b6784f8/failed-ids.txt)

**Comment by tpendragon** [comment]
Full report:

[missing_ids_report.csv](https://github.com/pulibrary/figgy/files/12653594/missing_ids_report.csv)

**Comment by tpendragon** [comment]
@minjiec @doncat The report is above. I'll ping you in #digital_library and close this ticket.
