### ISSUE TITLE
CloudfixityJob UniqueConstraintViolation: PG::UniqueViolation errors

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5900]
Seeing a handful of CloudfixityJob UniqueConstraintViolation errors. 

Figure out why they are being created again and make it stop.

https://figgy.princeton.edu/sidekiq/filter/retries

## Backtrace

    line 23 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: block in log_connection_yield
    line 17 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: log_connection_yield
    line 110 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: save

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/92833083)

**Comment by hackartisan** [comment]
It's curious that these started all of a sudden on 7/3 but I can't find anything that seems relevant in terms of deploys around that time.

**Comment by hackartisan** [comment]
I downloaded the errors from honeybadger and noticed that every time this has happened it's been a metadata node.

**Comment by hackartisan** [comment]
@tpendragon Did something happen on July 3rd -- any kind of batch re-preservation or re-check of some subset of resources?

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/issues/5556#issuecomment-1610390680 happened June 27, only thing I can think of.

**Comment by hackartisan** [comment]
I downloaded the honeybadger export and pulled out the preservation object ids and converted them to the resource ids. Here is the list of affected resources
```
> resources.map(&:id).map(&:to_s)                                                                                                                                         
=>                                            
["ddb13313-852d-440e-80cc-8ff13ec5bd65",
 "ca2d4407-84d3-459c-8260-2fd76b9f9382",
 "6b9cca43-e562-41a3-afb7-fd2106062e44",
 "c6bb0a40-6050-410d-9478-b9120848b5e2",
 "dc68a8f8-a80e-4290-8001-20f721aeb2ed",
 "5b3f6a3b-ba13-4911-91bd-df24f2b24545",
 "d6ecea8f-182e-4a4c-bfcc-0537ed802e45",
 "96f3d86f-572e-496c-83f0-925d3f1e5477",
 "1dd680d3-dd3a-4796-bd20-046b458e2674",
 "6ebaa585-799d-4a62-9fda-1a77b0993819",
 "b2d0ba66-53ad-44a0-ab46-a85435d47b23",
 "51dba73c-58da-4240-a498-0d8c41dd4a30",
 "ecfea54c-f4a6-4894-bbe5-2d462ff4d3a9",
 "8f3e3ac2-44a7-4a82-a591-4753776da324",
 "a448619d-e861-471b-9e28-e5b523143314",
 "68d6bb2b-7b90-484b-8e22-5b608c2522f1",
 "26dde925-7267-4aa8-bd90-9f908dd92765",
 "390b6a04-0910-4b21-a246-beb2f00f9516",
 "7ef2f8bf-c407-431f-907d-6bae36f77334",
 "8b7f6bff-6897-4d4a-9129-94e4cb995981",
 "9a6c0a83-158a-49a0-af93-366d153510a3",
 "b2f4db21-8299-4e6a-9a58-224f91330aa6",
 "5ef6bb28-dfb9-48bf-a250-f2af947c731c",
 "07b9429e-24ab-4217-8e56-82de929dae83",
 "a232d37e-f415-430d-9ea0-b33c89d50448",
 "ad7698df-657a-4981-876a-484008dcb1b2",
 "653779b1-7066-40b0-bd5d-91fb5d1b0984",
 "c65504eb-e918-42d3-ad80-f30a098a523e",
 "e6d24b64-11e4-4715-b495-8062d93a76a8",
 "61386913-ca81-4066-a6a1-3ee752ff6e22",
 "8f503630-351e-4325-ae1c-1fadc16f4e04",
 "f4f391f7-b470-436b-8b3b-61c00e632459",
 "879829ce-be93-4d65-a266-1237e69869c5",
 "4868d690-025e-4616-9fa8-c8f8ae064130",
 "ecbfd6ae-4096-4db3-b2b8-d7e81dfd5944",
 "7cb0b195-8edf-4f23-a926-e310bc299fbd",
 "757eac5b-92c7-4166-bf84-7902d846d985"]               
```

note that they are different kinds of resources: 
```
 resources.map(&:class)
=> 
[FileSet,
 ScannedMap,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 ScannedResource,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 Numismatics::Issue,
 FileSet,
 FileSet,
 ScannedResource,
 FileSet,
 FileSet,
 ScannedResource,
 ScannedResource,
 ScannedMap,
 Numismatics::Issue,
 FileSet,
 FileSet,
 ScannedMap,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 FileSet,
 ScannedMap,
 FileSet,
 FileSet,
 FileSet]
```

**Comment by hackartisan** [comment]
Looking at one of these, there is already more than one previous current event. When we do `.first` and update one of them to be `current: false`, there's still another one that's `current: true` https://github.com/pulibrary/figgy/blob/23fa2ad0c8b1329bb50cac3050e78023902552e3/app/jobs/cloud_fixity_job.rb#L65-L71

How did there come to be more than one current Event, considering we have the constraint? Maybe it doesn't matter, and we just have the code mark them all `current:false`, knowing we won't create more like this moving forward.

**Comment by tpendragon** [comment]
The constraint is:

No two events with metadata `'{"current": [true]}' and the same resource_id and child_id can exist.

You're saying there are cases in the DB where that happens?

**Comment by tpendragon** [comment]
Sorry I didn't realize this was for metadata - I think you're right, we should just mark them all `current: false`
