### ISSUE TITLE
Local fixity failure on file set

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5901]
New resource in the MVW with a failed local fixity issue: https://figgy.princeton.edu/catalog/f8532b69-8a0c-4389-be79-65e2fb0b1c83

**Comments below are old and have been addressed:**
https://figgy.princeton.edu/catalog/4234c313-83fa-4b4c-9005-3766611fddbf

[Figgy/production] Notice: Local fixity failure on file set 4234c313-83fa-4b4c-9005-3766611fddbf at location disk:///opt/repository/files/86/61/dd/8661dd5c735341628ee09a28b2e80a76/00000725.tif

## Backtrace

    line 45 of [PROJECT_ROOT]/app/jobs/local_fixity_job.rb: build_event_change_set
    line 32 of [PROJECT_ROOT]/app/jobs/local_fixity_job.rb: check_fixity
    line 15 of [PROJECT_ROOT]/app/jobs/local_fixity_job.rb: block in perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/97810653)

**Comment by tpendragon** [comment]
First thing to try - try running local fixity on that file again and see if that fixes it.

**Comment by tpendragon** [comment]
Local fixity check ran successfully.

**Comment by eliotjordan** [comment]
Reopening because there is a another local fixity failure on a different volume in the MVW.

https://figgy.princeton.edu/catalog/f8532b69-8a0c-4389-be79-65e2fb0b1c83

**Comment by eliotjordan** [comment]
This is fixed now. Preservation status now shows "Healthy".
