### ISSUE TITLE
Migrate to Postgres 15

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5903]
Postgres 10 is super out of date and difficult to even get installed now it's so unsupported. Migrate to figgy-db-prod1.

Notes: https://docs.google.com/document/d/1dBN7AllCKwp-AyYc7KVBeQFo6YtWz85q2ShlQnWdUAw/edit#heading=h.kqmal60l50l

## Steps

Ruby
- [x] Update CI to use Postgres 15 (see https://github.com/pulibrary/figgy/pull/5918)

Staging
- [x] Create a staging database infrastructure (two staging database servers) (Create on production infra) (https://github.com/pulibrary/figgy/issues/5947)
- [x] Allow figgy-db-staging1 to access lib-postgres3 (update pg_hba to add figgy-db-staging1's IP)
- [x] Dump figgy_staging database schema
    * `pg_dumpall --schema-only -d figgy_staging -H lib-postgres3 -U postgres -f figgy_staging_schema.sql`
- [x] Dump figgy_staging database users
    * `pg_dumpall --roles-only -H lib-postgres3 -U postgres -f figgy_staging_roles.sql` (then trim it down to the figgy ones)
- [x] Set up the second staging database server as a "warm standby" replica
    * https://hevodata.com/learn/postgresql-streaming-replication/
- [x] Restore figgy_staging_schema.sql & figgy_staging_roles.sql to the new staging database.
- [x] Set up logical replication between lib-postgres3 and new one.
     * On lib-postgres3, connected to figgy_staging: `CREATE PUBLICATION figgy_staging_publication FOR ALL TABLES;`
     * On staging db, connected to figgy_staging: `CREATE SUBSCRIPTION figgy_staging_subscription
CONNECTION 'host=lib-postgres3.princeton.edu port=5432 dbname=figgy_staging user=postgres password=postgrespassword' PUBLICATION figgy_staging_publication;`
- [x] Copy postgres users from lib-postgres3 to figgy-db-staging1
- [x] Verify row counts for all tables between lib-postgres3 and figgy-db-staging1 (ensures replication has finished)
- [x] Set figgy-staging to read only
- [x] Verify row counts for all tables between lib-postgres3 and figgy-db-staging1 (ensure replication is up to date)
- [x] Update sequences in figgy-db-staging1
    * https://wiki.postgresql.org/wiki/Fixing_Sequences
- [x] Swap figgy-staging to figgy-db-staging1.
- [x] Restart nginx and workers
- [x] Ensure everything looks okay
- [x] turn off logical replication -- Delete the subscription on figgy-db-staging1 (`DROP SUBSCRIPTION figgy_staging_subscription;`)
- [x] Turn off read only on figgy-staging
- [x] Restart nginx and workers
- [x] Ensure we can create objects and the database changes.
- [x] Make sure the follower gets new changes.

Prod - Prep

- [x] Create figgy-db-prod1 (https://github.com/pulibrary/figgy/issues/5947)
    * https://github.com/pulibrary/princeton_ansible/pull/3953
- [x] Create figgy-db-prod2
- [x] Set up warm standby between figgy-db-prod1 and figgy-db-prod2.
    * https://hevodata.com/learn/postgresql-streaming-replication/
- [x] Dump schema from lib-postgres3 to figgy-db-prod1
- [x] Set up logical replication between lib-postgres3 and figgy-db-prod1
- [x] Copy postgres users from lib-postgres3 to figgy-db-prod1
- [x] Make sure the figgy production playbook runs.
- [x] Negotiate 3 hours of read only time.
- [x] Verify row counts for all tables between lib-postgres3 and figgy-db-prod1 (ensures replication has finished)
- [x] Set Figgy to read only
- [x] Verify row counts for all tables between lib-postgres3 and figgy-db-prod1 (ensures replication is up to date)
- [x] Update sequences in figgy-db-prod1
    * https://wiki.postgresql.org/wiki/Fixing_Sequences
- [x] Swap Figgy to figgy-db-prod1.
- [x] Restart nginx and workers
- [x] turn off logical replication -- Delete the subscription on figgy-db-prod1 (`DROP SUBSCRIPTION figgy_subscription;`)
- [x] Turn off read only
- [x] Restart nginx and workers
- [x] Set up and enable backup, verify.

## Prod - Migration Steps On Day Of

- [x] Open a terminal to each database server:
    * `ssh pulsys@figgy-db-prod1`
    * `ssh pulsys@lib-postgres3`
- [x] Open a SQL terminal connected to `figgy_production` on both servers: `sudo -u postgres psql -d figgy_production`
- [x] Check row counts for all tables between both servers:
```sql
WITH tbl AS
  (SELECT table_schema,
          TABLE_NAME
   FROM information_schema.tables
   WHERE TABLE_NAME not like 'pg_%'
     AND table_schema in ('public'))
SELECT table_schema,
       TABLE_NAME,
       (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from %I.%I', table_schema, TABLE_NAME), FALSE, TRUE, '')))[1]::text::int AS rows_n
FROM tbl
ORDER BY rows_n DESC;
```
- [x] Assuming they're close, move on. If they're far off, stop here. Something's broken.
- [x] Send a message to #digital-library: `@here We're now starting scheduled maintenance of Figgy, it will be going into read only mode for up to 3 hours. We'll send another message here when it's ready for regular use again.`
- [x] In princeton_ansible, edit `group_vars/figgy/production.yml`, set `figgy_read_only_mode: 'true'`
- [x] `ansible-playbook playbooks/figgy_production.yml --tags=site_config`
- [x] Check row counts for all tables between both servers: (copy above)
- [x] If they're not exact, wait a minute, try again. If they never become exact for `orm_resources` and `users` then stop. Otherwise, continue.
- [x] Run the following query in figgy-db-prod1's psql terminal.
```sql
 SELECT SETVAL('public.active_storage_attachments_id_seq', COALESCE(MAX(id), 1) ) FROM public.active_storage_attachments;
 SELECT SETVAL('public.active_storage_blobs_id_seq', COALESCE(MAX(id), 1) ) FROM public.active_storage_blobs;
 SELECT SETVAL('public.active_storage_variant_records_id_seq', COALESCE(MAX(id), 1) ) FROM public.active_storage_variant_records;
 SELECT SETVAL('public.auth_tokens_id_seq', COALESCE(MAX(id), 1) ) FROM public.auth_tokens;
 SELECT SETVAL('public.authorization_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.authorization_models;
 SELECT SETVAL('public.bookmarks_id_seq', COALESCE(MAX(id), 1) ) FROM public.bookmarks;
 SELECT SETVAL('public.browse_everything_authorization_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.browse_everything_authorization_models;
 SELECT SETVAL('public.browse_everything_session_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.browse_everything_session_models;
 SELECT SETVAL('public.browse_everything_upload_files_id_seq', COALESCE(MAX(id), 1) ) FROM public.browse_everything_upload_files;
 SELECT SETVAL('public.browse_everything_upload_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.browse_everything_upload_models;
 SELECT SETVAL('public.delayed_jobs_id_seq', COALESCE(MAX(id), 1) ) FROM public.delayed_jobs;
 SELECT SETVAL('public.ocr_requests_id_seq', COALESCE(MAX(id), 1) ) FROM public.ocr_requests;
 SELECT SETVAL('public.roles_id_seq', COALESCE(MAX(id), 1) ) FROM public.roles;
 SELECT SETVAL('public.searches_id_seq', COALESCE(MAX(id), 1) ) FROM public.searches;
 SELECT SETVAL('public.session_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.session_models;
 SELECT SETVAL('public.upload_files_id_seq', COALESCE(MAX(id), 1) ) FROM public.upload_files;
 SELECT SETVAL('public.upload_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.upload_models;
 SELECT SETVAL('public.users_id_seq', COALESCE(MAX(id), 1) ) FROM public.users;
```
- [x] Edit group_vars/figgy/production.yml. Change the following variables:
```yml
postgres_host: 'figgy-db-prod1.princeton.edu'
postgres_version: 15
```
- [x] Send this message to #infrastructure: `We're removing some Figgy web nodes from the load balancer, please don't run the nginx+ playbook or edit the load balancer until we're done (at most 3 hours).`
- [x] Pull the web hosts in figgy_production_group_a off the load balancer.
    * `ssh pulsys@lib-adc1.princeton.edu` in one terminal, `ssh pulsys@lib-adc2.princeton.edu` in another terminal
    * Identify the "active" load balancer by running `ip a | grep 146` in each, the one that returns is active.
    * On inactive one:
        - `sudo vi /etc/nginx/conf.d/figgy-prod.conf`
        - Comment out `figgy1` and `figgy-web-prod2` by adding a `#` at the start of those lines.
        - run `nginx -t`, if it says okay continue
        - run `sudo systemctl restart nginx`
    * Repeat on active one.
- [x] Run the playbook against figgy_production_group_a `ansible-playbook playbooks/figgy_production.yml --limit figgy_production_group_a`
- [x] Pull the web hosts in figgy_production_group_b off the load balancer, put group_a back on
    * `ssh pulsys@lib-adc1.princeton.edu` in one terminal, `ssh pulsys@lib-adc2.princeton.edu` in another terminal
    * Identify the "active" load balancer by running `ip a | grep 146` in each, the one that returns is active.
    * On inactive one:
        - `sudo vi /etc/nginx/conf.d/figgy-prod.conf`
        - Uncomment `figgy1` and `figgy-web-prod2` by removing `#` at the start of those lines.
        - Comment `figgy3` and `figgy-web-prod4` by adding `#` at the start of those lines.
        - run `nginx -t`, if it says okay continue
        - run `sudo systemctl restart nginx`
    * Repeat on active one.
- [x] Make sure https://figgy.princeton.edu/catalog/30488f2b-b4d3-45f8-bf77-fa0530031c4a loads
- [x] Run the playbook against figgy_production_group_b `ansible-playbook playbooks/figgy_production.yml --limit figgy_production_group_b`
- [x] Put the web hosts in figgy_production_group_b back on load balancer.
    * `ssh pulsys@lib-adc1.princeton.edu` in one terminal, `ssh pulsys@lib-adc2.princeton.edu` in another terminal
    * Identify the "active" load balancer by running `ip a | grep 146` in each, the one that returns is active.
    * On inactive one:
        - `sudo vi /etc/nginx/conf.d/figgy-prod.conf`
        - Uncomment `figgy3` and `figgy-web-prod4` by removing `#` at the start of those lines.
        - run `nginx -t`, if it says okay continue
        - run `sudo systemctl restart nginx`
    * Repeat on active one.
- [x] Make sure https://figgy.princeton.edu/catalog/30488f2b-b4d3-45f8-bf77-fa0530031c4a loads
- [x] In princeton_ansible, edit `group_vars/figgy/production.yml`, set `figgy_read_only_mode: 'false'`
- [x] `ansible-playbook playbooks/figgy_production.yml --tags=site_config`
- [x] Check again, if something's wrong the time between the last step and now might be lost data.
- [x] Create a new work, make sure that works, add a new file, make sure it loads.
- [x] Make sure HoneyBadger's not spamming errors more than normal: https://app.honeybadger.io/projects/53391/faults?q=-is%3Aresolved+-is%3Aignored&sort=last_seen_desc
- [x] If good, throw a party.
- [x] If bad, put it back in read only mode, check the time, and either resolve or undo everything.
- [x] turn off logical replication -- Delete the subscription on figgy-db-prod1 (DROP SUBSCRIPTION figgy_subscription;)
- [x] Send a message to #infrastructure when done saying `We've finished maintenance on Figgy, feel free to do whatever work you need to with the load balancer.`
- [x] Send a message to #digital-library: `We've completed the planned maintenance for Figgy. Thank you for your patience, you can resume work in Figgy as normal.`

Possible Follow Ups:

* Decommission lib-postgres3
* Figure out how to promote a warm standby
* Fire drill warm standby promotion on staging.
* Document the steps to promote a warm standby.

## Sudden Priority Justification

lib-postgres3 has had problems lately and we've found that postgres 10 is very hard to get installed on something.

**Comment by tpendragon** [comment]
Copying postgres users:
```
pg_dumpall --host lib-postgres3.princeton.edu -U postgres --roles-only --file=roles.sql
psql --host figgy-db-prod1 -U postgres -f roles.sql
```

**Comment by tpendragon** [comment]
Check row count:

```sql
WITH tbl AS
  (SELECT table_schema,
          TABLE_NAME
   FROM information_schema.tables
   WHERE TABLE_NAME not like 'pg_%'
     AND table_schema in ('public'))
SELECT table_schema,
       TABLE_NAME,
       (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from %I.%I', table_schema, TABLE_NAME), FALSE, TRUE, '')))[1]::text::int AS rows_n
FROM tbl
ORDER BY rows_n DESC;
```

figgy-db-prod1:

```
table_schema |               table_name               |  rows_n
--------------+----------------------------------------+----------
 public       | orm_resources                          | 29953031
 public       | searches                               |  8227730
 public       | browse_everything_upload_files         |  2212748
 public       | ocr_requests                           |    20090
 public       | browse_everything_session_models       |    15829
 public       | browse_everything_authorization_models |     7918
 public       | browse_everything_upload_models        |     6990
 public       | users                                  |     5469
 public       | auth_tokens                            |      617
 public       | roles_users                            |      390
 public       | bookmarks                              |      162
 public       | schema_migrations                      |       35
 public       | active_storage_blobs                   |        4
 public       | active_storage_attachments             |        4
 public       | roles                                  |        3
 public       | ar_internal_metadata                   |        1
 public       | active_storage_variant_records         |        0
 public       | delayed_jobs                           |        0
```

lib-postgres3:

```
table_schema |               table_name               |  rows_n
--------------+----------------------------------------+----------
 public       | orm_resources                          | 29953031
 public       | searches                               |  8227731
 public       | browse_everything_upload_files         |  2212748
 public       | ocr_requests                           |    20090
 public       | browse_everything_session_models       |    15829
 public       | browse_everything_authorization_models |     7918
 public       | browse_everything_upload_models        |     6990
 public       | users                                  |     5469
 public       | auth_tokens                            |      617
 public       | roles_users                            |      390
 public       | bookmarks                              |      162
 public       | schema_migrations                      |       35
 public       | active_storage_attachments             |        4
 public       | active_storage_blobs                   |        4
 public       | roles                                  |        3
 public       | ar_internal_metadata                   |        1
 public       | delayed_jobs                           |        0
 public       | active_storage_variant_records         |        0
```

I'm assuming the 1 missing search is just because read only wasn't on when I ran this, and it hadn't synced to figgy-db-prod1 yet.

**Comment by tpendragon** [comment]
figgy-db-staging1:

```
table_schema |               table_name               | rows_n
--------------+----------------------------------------+--------
 public       | orm_resources                          | 176540
 public       | browse_everything_upload_files         | 104640
 public       | upload_files                           |   8626
 public       | searches                               |   5324
 public       | browse_everything_session_models       |    641
 public       | browse_everything_authorization_models |    332
 public       | browse_everything_upload_models        |    173
 public       | users                                  |     61
 public       | roles_users                            |     41
 public       | schema_migrations                      |     35
 public       | session_models                         |     32
 public       | authorization_models                   |     22
 public       | auth_tokens                            |     20
 public       | upload_models                          |     12
 public       | ocr_requests                           |      8
 public       | bookmarks                              |      7
 public       | roles                                  |      2
 public       | ar_internal_metadata                   |      1
 public       | delayed_jobs                           |      0
 public       | active_storage_blobs                   |      0
 public       | active_storage_variant_records         |      0
 public       | active_storage_attachments             |      0
```

figgy-db-staging2:

```
table_schema |               table_name               | rows_n
--------------+----------------------------------------+--------
 public       | orm_resources                          | 176540
 public       | browse_everything_upload_files         | 104640
 public       | upload_files                           |   8626
 public       | searches                               |   5324
 public       | browse_everything_session_models       |    641
 public       | browse_everything_authorization_models |    332
 public       | browse_everything_upload_models        |    173
 public       | users                                  |     61
 public       | roles_users                            |     41
 public       | schema_migrations                      |     35
 public       | session_models                         |     32
 public       | authorization_models                   |     22
 public       | auth_tokens                            |     20
 public       | upload_models                          |     12
 public       | ocr_requests                           |      8
 public       | bookmarks                              |      7
 public       | roles                                  |      2
 public       | ar_internal_metadata                   |      1
 public       | delayed_jobs                           |      0
 public       | active_storage_blobs                   |      0
 public       | active_storage_variant_records         |      0
 public       | active_storage_attachments             |      0
```

lib-postgres3

```
table_schema |               table_name               | rows_n
--------------+----------------------------------------+--------
 public       | orm_resources                          | 176540
 public       | browse_everything_upload_files         | 104640
 public       | upload_files                           |   8626
 public       | searches                               |   5324
 public       | browse_everything_session_models       |    641
 public       | browse_everything_authorization_models |    332
 public       | browse_everything_upload_models        |    173
 public       | users                                  |     61
 public       | roles_users                            |     41
 public       | schema_migrations                      |     35
 public       | session_models                         |     32
 public       | authorization_models                   |     22
 public       | auth_tokens                            |     20
 public       | upload_models                          |     12
 public       | ocr_requests                           |      8
 public       | bookmarks                              |      7
 public       | roles                                  |      2
 public       | ar_internal_metadata                   |      1
 public       | delayed_jobs                           |      0
 public       | active_storage_variant_records         |      0
 public       | active_storage_blobs                   |      0
 public       | active_storage_attachments             |      0
```

**Comment by tpendragon** [comment]
figgy-db-prod1:
```
 table_schema |               table_name               |  rows_n
--------------+----------------------------------------+----------
 public       | orm_resources                          | 31225083
 public       | searches                               |  8234952
 public       | browse_everything_upload_files         |  2212748
 public       | ocr_requests                           |    20494
 public       | browse_everything_session_models       |    15829
 public       | browse_everything_authorization_models |     7918
 public       | browse_everything_upload_models        |     6990
 public       | users                                  |     5495
 public       | auth_tokens                            |      618
 public       | roles_users                            |      395
 public       | bookmarks                              |      162
 public       | schema_migrations                      |       35
 public       | active_storage_blobs                   |        4
 public       | active_storage_attachments             |        4
 public       | roles                                  |        3
 public       | ar_internal_metadata                   |        1
 public       | active_storage_variant_records         |        0
 public       | delayed_jobs                           |        0
```

figgy-db-prod2:

```
table_schema |               table_name               |  rows_n
--------------+----------------------------------------+----------
 public       | orm_resources                          | 31225084
 public       | searches                               |  8234953
 public       | browse_everything_upload_files         |  2212748
 public       | ocr_requests                           |    20494
 public       | browse_everything_session_models       |    15829
 public       | browse_everything_authorization_models |     7918
 public       | browse_everything_upload_models        |     6990
 public       | users                                  |     5495
 public       | auth_tokens                            |      618
 public       | roles_users                            |      395
 public       | bookmarks                              |      162
 public       | schema_migrations                      |       35
 public       | active_storage_blobs                   |        4
 public       | active_storage_attachments             |        4
 public       | roles                                  |        3
 public       | ar_internal_metadata                   |        1
 public       | active_storage_variant_records         |        0
 public       | delayed_jobs                           |        0
```

lib-postgres3
```
table_schema |               table_name               |  rows_n
--------------+----------------------------------------+----------
 public       | orm_resources                          | 31225084
 public       | searches                               |  8234953
 public       | browse_everything_upload_files         |  2212748
 public       | ocr_requests                           |    20494
 public       | browse_everything_session_models       |    15829
 public       | browse_everything_authorization_models |     7918
 public       | browse_everything_upload_models        |     6990
 public       | users                                  |     5495
 public       | auth_tokens                            |      618
 public       | roles_users                            |      395
 public       | bookmarks                              |      162
 public       | schema_migrations                      |       35
 public       | active_storage_attachments             |        4
 public       | active_storage_blobs                   |        4
 public       | roles                                  |        3
 public       | ar_internal_metadata                   |        1
 public       | delayed_jobs                           |        0
 public       | active_storage_variant_records         |        0
(18 rows)
```

**Comment by hackartisan** [comment]
Migration has been run successfully on `figgy-staging2`. `figgy-web-staging-1` superficially appears to also be hooked up but should be considered to be in an unknown state until the full playbook runs successfully on it.

**Comment by tpendragon** [comment]
Next steps for production migration:

Get ansible playbook running on Figgy Production all the way through on all the boxes before we start
Add info about only doing half the web servers in prod

**Comment by kayiwa** [comment]
one surprise
```sql
ERROR:  relation "public.session_models" does not exist
LINE 1: ...ssion_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.ses...
                                                             ^
ERROR:  relation "public.upload_files" does not exist
LINE 1: ...upload_files_id_seq', COALESCE(MAX(id), 1) ) FROM public.upl...
                                                             ^
ERROR:  relation "public.upload_models" does not exist
LINE 1: ...pload_models_id_seq', COALESCE(MAX(id), 1) ) FROM public.upl...
                                                             ^
```
