### ISSUE TITLE
Some PreserveResourceJobs are failing

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5905]
https://figgy.princeton.edu/sidekiq/filter/retries

Two separate errors:
1. `Google::Cloud::Error: execution expired`
2. `Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() SSL SYSCALL error: EOF detected`
3. 
Honeybadger: https://app.honeybadger.io/projects/53391/faults/87152309

also https://app.honeybadger.io/projects/53391/faults/95511670

These PreserveResourceJobs are taking hours for some reason. How can we preserve files at the scale of 150 GB? Is changing the timeout a good option? Is there some chunking and / or resumability we can investigate?

**Comment by tpendragon** [comment]
These might be really big items, so we're putting it in work cycle.

**Comment by tpendragon** [comment]
A little research while I have a second:

shrine-gcs uses the google-cloud-storage gem:

https://github.com/renchap/shrine-google_cloud_storage/blob/04a7b0a029ce445d37d22cb1d880812b7b75b365/lib/shrine/storage/google_cloud_storage.rb#L169C54-L169C54

That gem has a timeout option for the client: https://github.com/renchap/shrine-google_cloud_storage/blob/04a7b0a029ce445d37d22cb1d880812b7b75b365/lib/shrine/storage/google_cloud_storage.rb#L169C54-L169C54

Right now nothing's set, so it defaults to the underlying protocol, which is HttpClient:

https://github.com/googleapis/google-api-ruby-client/blob/4c6c8a1e7c4a177e62660b79b526fe914aefa7ae/google-apis-core/lib/google/apis/core/base_service.rb#L459C26-L459C26

HttpClient's default is 60 seconds:

https://github.com/nahi/httpclient/blob/4658227a46f7caa633ef8036f073bbd1f0a955a2/lib/httpclient/session.rb#L145C1-L149

(I'm not 100% sure that's where the timeout default is defined.)

However, we can't pass it through the gem. We CAN configure it at the global level though:

https://cloud.google.com/ruby/docs/reference/google-cloud-storage/latest/Google-Cloud-Storage#Google__Cloud__Storage_configure_class_

So I think what we'd need is something like

```ruby
Google::Cloud::Storage.configure(timeout: 36000) # 10 hour timeout
```

in `config/initializers/valkyrie.rb` and test it.
