### ISSUE TITLE
Resources that are "flagged" no longer preserve

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5926]
This means that if someone flags a resource because it was throwing preservation errors, the health report no longer returns a problem.

See https://figgy.princeton.edu/catalog/92b4a7a4-c245-45eb-934f-dfbf68ba0ee2 as an example.

Should we preserve flagged resources? Still display preservation status but not preserve? If we do that, how do they get it to unflagged if it was flagged because of preservation status? Flagged is post-complete, maybe that means we should preserve them.

**Comment by hackartisan** [comment]
"if someone flags a resource because it was throwing preservation errors" -- is this what we expect people to do?

either way I vote to preserve them.

**Comment by eliotjordan** [comment]
I vote preserve as well.
