### ISSUE TITLE
Viewing direction not respected by viewer

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#593]
Even when viewing-direction is set to `right-to-left`, the viewer is displaying items left-to-right, e.g.:
https://figgy.princeton.edu/catalog/8222a875-9549-4261-9cbd-6bf5f5da9814

**Comment by hackmastera** [comment]
It looks right-left to me, in terms of image order. the first image looks like the right-most page, just from the stack of pages that appear to be on the other side.

How can I tell for sure? What should I expect to see here?

**Comment by escowles** [comment]
@hackmastera See the item in Plum: https://plum.princeton.edu/concern/multi_volume_works/p8p58sc37s — the arrows in the viewer are on the left so you can page through it from right to left.

**Comment by hackmastera** [comment]
Okay, thanks. In plum Image 1 is on the left in the contents / thumbnail listing; presumably it would be better if it were on the right. Image 3/4 are shown right-to-left, just below.

**Comment by escowles** [comment]
I think the issue is that the viewingHint isn't being included in the manifest, but I'm not sure — that's what I'd look at first.
