### ISSUE TITLE
PDF not creating derivatives

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5932]
Reported by Tom V.

This is the file: https://figgy.princeton.edu/catalog/parent/82ccfe9f-dd5a-42c7-a4ff-1029763fe798/4a26df57-3780-4568-8b27-52d9c416846b

Here is the relevant honeybadger error: https://app.honeybadger.io/projects/53391/faults/97580878#notice-params

The pdf loads fine. We've tried regenerating a couple of times.

**Comment by hackartisan** [comment]
Tom is re-ingesting. Record is now https://figgy.princeton.edu/catalog/3931aa55-afd6-4c29-88bc-afaac7251f38

**Comment by hackartisan** [comment]
related honeybadger error: https://app.honeybadger.io/projects/53391/faults/80089019

**Comment by tpendragon** [comment]
Reran the failed PDFs with the new processing and it's all done!
