### ISSUE TITLE
Bulk edit request for "Wenshi Ziliao"

### ISSUE THREAD

**Issue by tventimi** [pulibrary/figgy#5935]
### Summary

Last year, the Figgy team was gracious enough to perform a set of bulk edits for me on a set of 15 MVWs called "Wenshi Ziliao".  This is because these options are not yet available in the user-facing "Bulk Edit" function.  I just added another 14 MVWs to this collection, and I would like to request the same bulk edits.  Here is the ticket for the original request:

https://github.com/pulibrary/figgy/issues/5149

The bulk edits to be performed for all volumes are: 1) set the OCR language to chi_sim, 2) use paged viewing, 3) strip the leading zeros from the page numbers. 

The names and URLs of the items that were just added are:

Wenshi Ziliao (Anhui) | https://figgy.princeton.edu/catalog/a3ff99c8-b134-422d-ba69-22e4d3e19ee5
Wenshi Ziliao (Chongqing) | https://figgy.princeton.edu/catalog/5ff61b5c-5d68-422b-8498-012a3ffd0234
Wenshi Ziliao (Guangdong) | https://figgy.princeton.edu/catalog/57a14dbe-7b8c-4daf-9b88-0583e7b36e78
Wenshi Ziliao (Guangxi) | https://figgy.princeton.edu/catalog/d4e05b51-80e2-4d1a-a628-5f2a2b57122d
Wenshi Ziliao (Guizhou) | https://figgy.princeton.edu/catalog/ac176b62-f3ca-48f3-9bbb-5b71d9a5d42d
Wenshi Ziliao (Heilongjiang) | https://figgy.princeton.edu/catalog/4f4c1da4-7e3e-453a-8808-b3ab85bfde19
Wenshi Ziliao (Hubei) | https://figgy.princeton.edu/catalog/3931aa55-afd6-4c29-88bc-afaac7251f38
Wenshi Ziliao (Jiangsu) | https://figgy.princeton.edu/catalog/b2a57dfe-80ac-4044-b476-9b753396f0c1
Wenshi Ziliao (Liaoning) | https://figgy.princeton.edu/catalog/b13d3f15-263e-48d3-8193-bd76a4b26ed6
Wenshi Ziliao (Neimeng) | https://figgy.princeton.edu/catalog/35685dc1-c72a-4212-9318-734ed3e1f2c5
Wenshi Ziliao (Shaanxi) | https://figgy.princeton.edu/catalog/40b269e6-37b2-4a40-9636-c8998ac2319e
Wenshi Ziliao (Shandong) | https://figgy.princeton.edu/catalog/6863884c-f06e-4f5b-8de2-8b537e675d35
Wenshi Ziliao (Tianjin) | https://figgy.princeton.edu/catalog/619fadee-7b1f-489f-8669-f302f1be59b0
Wenshi Ziliao (Zhejiang) | https://figgy.princeton.edu/catalog/2344a324-1045-430c-9694-a6a3d12ca699

As of now, the "Hubei" item is still in the process of loading, and its status is "pending".  The other items have loaded and are complete.

### Impact 

These changes will improve the user experience, but the items are usable in their current state.

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
I put "within the next 3 weeks" below because that is what @tpendragon set the priority to last time.  This is not urgent, but will improve ease of use and ensure consistency with the other 15 items in the collection.

**Comment by kelea99** [comment]
@tpendragon Looking the selection, I can do the ocr set and pretty quickly strip the zeros and set the page viewing myself? for a handful of items, its probably faster to do in bulk edit and manually?

**Comment by tpendragon** [comment]
@kelea99 If you wanna do this manually have at it, don't let me stop ya.

**Comment by tventimi** [comment]
Just an update, the Hubei item has finished loading...

**Comment by tventimi** [comment]
The requested changes have been added manually to each volume in each MVW.
