### ISSUE TITLE
Optimize PDF processing

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5937]
It is currently taking several hours sometimes to process a PDF into images. Example: https://github.com/pulibrary/figgy/issues/5932

It also seems to take much more disk space than we would expect. The proc machines all have at least 100GB of disk, and that should be more than enough.

Desired outcomes:
* PDFs should process an order of magnitude faster.
* Disk space should not be an issue.

Sudden priority justification: This is making ingest very slow and unpleasant, curators have to babysit ingest. For developers, we're spending time responding to alerts and babysitting VMs.

Related honeybadger issues (resolve these when issue is closed):
* https://app.honeybadger.io/projects/53391/faults/96005953
* https://app.honeybadger.io/projects/53391/faults/98918521

**Comment by tpendragon** [comment]
Previous work:

https://github.com/pulibrary/figgy/pull/4164 attempted to fix a file handle problem (https://github.com/libvips/ruby-vips/issues/67)

https://github.com/pulibrary/figgy/pull/4216 changed to extracting images in batches.

**Comment by tpendragon** [comment]
A major example of a PDF that won't process:[ 993660003506421](https://figgy.princeton.edu/catalog/345fd620-8b15-4b4c-a358-d833e882e085)

It's a ~1000 page PDF which we've processed before, I'm not sure what's changed.

**Comment by tpendragon** [comment]
Attempting to recreate the problem in staging.

**Comment by tpendragon** [comment]
Upgrading VIPS didn't fix it. Going to try lowering the number of pages at a time.
