### ISSUE TITLE
Figgy Search cannot find MMS ID 9964843433506421

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5943]
### Summary
Reported by Natalie in Microforms.  We can find this item by [the link provided](https://figgy.princeton.edu/catalog/e40ee532-c030-407d-9db8-b23d6a31f3b4) last week in slack. The MMS id (9964843433506421) yields zero search results in figgy.  The hyperlinked MMS id in the figgy record links to the orangelight catalog aok.  Not sure what is going on.  I tested other MMS ids, in pending state, that are MVWs. can find them fine in figgy via MMS id search.  Ideas? 
### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not exactly stopping work, but it is adding a painpoint.  Items on the server cannot be deleted until it is confirmed 9964843433506421 is good to go in figgy. 
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
 Suggestion: It might be good to investigate within the next 3 weeks, while still fresh in folks minds, just in case this is only one of a few/some/many affected similarly (and we just havent caught them yet).

**Comment by kelea99** [comment]
What makes this ticket perhaps more interesting is the fact that this is the record that would not take in bulk ingest with the other ingests. I added each volume manually to a host record and seemed to be fine. not sure what is up.

**Comment by tpendragon** [comment]
This is very very weird.

Eliot noticed that https://figgy.princeton.edu/?f%5Bmember_of_collection_titles_ssim%5D%5B%5D=Patron+Requests&f%5Bstate_ssim%5D%5B%5D=pending is failing, which I think is what we get when we have a resource in the index that doesn't have a postgres record

**Comment by tpendragon** [comment]
Oops. It's not that it had zero results, it's that one of the search results was broken and causing an error page that looked like it was no results.

I parsed out the IDs from the first page of search results and deleted records that had no matching postgres record. Probably from our solr woes. We should reindex at some point.
