### ISSUE TITLE
Provision Postgres 15 Machines

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5947]
# Reasoning

lib-postgres3 is actively exploding, is very out of date, and needs to be migrated to VMs. See https://github.com/pulibrary/figgy/issues/5903 for further reasoning

# Boxes to Provision

I don't actually care what these are called.

## Staging

- [x] figgy-db-staging1 (figgy-jammy-staging-db1)
- [x] figgy-db-staging2 (figgy-jammy-staging-db2)

Create these on prod infrastructure since the staging infra is overprovisioned.

## Production

- [x] figgy-db-prod1
- [x] figgy-db-prod2

# Deadline

I don't have a deadline, but we're in a tough place if this system dies again. I'd set the priority higher than my other provisioning requests.

**Comment by acozine** [comment]
The two staging servers are done:
figgy-db-staging1: lib-vmserv01a, 4 CPU, 80+30GB hard drives, 64GB memory
figgy-db-staging2: lib-vmserv03a, 4 CPU, 80+30GB hard drives, 64GB memory

**Comment by acozine** [comment]
First round on the two prod servers is done. Still need refinement, but for today:
figgy-db-prod1: lib-vmserv03b, 8 CPU, 30+300+200GB hard drives, 128GB memory
figgy-db-prod2: lib-vmserv02a, 8 CPU, 80+300GB hard drives, 128GB memory
