### ISSUE TITLE
Health Status Icon showing as funky text on Microfilm MVW item

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5952]
### Summary
Reported by Natalie in Microforms.  [This item](https://figgy.princeton.edu/catalog/d799c392-9bda-4157-93c6-6cf88cac6d6a) in figgy is not showing the health status icon.  I checked Chrome and Firefox on other items in figgy and things work fine. Natalie checked another item as well. Healthcheck icon was there and fine. Seems to be affecting this one (and others that have the same error??).
See screenshots

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Not halting work, but should probably be reviewed during the preservation workcycle?
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Fits into preservation workcycle, I should think. 

### Screenshots
Wonky Health status anti-icon
<img width="1512" alt="Screenshot 2023-08-10 at 8 42 59 AM" src="https://github.com/pulibrary/figgy/assets/45043014/6896e39a-3177-4ef4-9079-e755e2bb2902">

Working health status icon
<img width="1512" alt="Screenshot 2023-08-10 at 8 43 03 AM" src="https://github.com/pulibrary/figgy/assets/45043014/0d52f8d7-7140-4360-828f-2cff8b9e12a7">

**Comment by eliotjordan** [comment]
Steps:

1. Once https://github.com/pulibrary/figgy/pull/5988 is merged and deployed, QA against this record.
2. Figure out why this record is stuck in repairing status and fix.

**Comment by eliotjordan** [comment]
Fixed the resource. Can a cloud fixity check against the resource and all of it's file sets as well as local fixity checks against all file sets.

**Comment by eliotjordan** [comment]
```ruby
r = ChangeSetPersister.default.query_service.find_by(id: "1e544e7b-4566-439b-ab4f-b48d0585ee42")

r.member_ids.each do |id|
  CloudFixity::FixityRequestor.queue_resource_check!(id: id.to_s)
end

r.member_ids.each do |id|
  LocalFixityJob.perform_later(id: id.to_s)
end
```
