### ISSUE TITLE
Update node to 18

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5965]
https://nodejs.org/en/about/releases/

depends on https://github.com/pulibrary/figgy/issues/5946

refs https://github.com/pulibrary/princeton_ansible/issues/3476
Example: https://github.com/pulibrary/princeton_ansible/pull/4324/files

**Comment by hackartisan** [comment]
On boxes, run the upgrade_gcc playbook before running the application playbook with the new yarn version. see https://github.com/pulibrary/princeton_ansible/pull/4442/files

**Comment by eliotjordan** [comment]
Done.
