### ISSUE TITLE
Move DK Ephemera  Project Boxes 22 and 23 to SAE Ephemera Project

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5971]
### Summary

DK agencies has finished metadata for boxes 22 and 23 in [DK Ephemera Project](https://figgy.princeton.edu/catalog/f09fc91d-7a9b-47b5-afff-ce7db76b4e92). Please move Boxes 22 and 23 to [SAE Ephemera Project](https://figgy.princeton.edu/catalog/f99af4de-fed4-4baa-82b1-6e857b230306https://figgy.princeton.edu/catalog/f99af4de-fed4-4baa-82b1-6e857b230306).

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Before September 20th
### Priority recommendation

- [ ] asap
- [X] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Due to meeting with journalists and photographer for article featuring Ellen  and Aditya.

**Comment by tpendragon** [comment]
Note: Add how you did this to this ticket. We'll be doing it again.

**Comment by kelea99** [comment]
@tpendragon  - checking in on this one can we get this done today?

**Comment by tpendragon** [comment]
Yup it's at the tip top of the priority.

**Comment by tpendragon** [comment]
Done. Commands:

```
bundle exec rake figgy:bulk:move_box TARGET_PROJECT_ID=f99af4de-fed4-4baa-82b1-6e857b230306 BOX_ID=e41600e1-b49a-4bb8-b191-85661ee95f06
bundle exec rake figgy:bulk:move_box TARGET_PROJECT_ID=f99af4de-fed4-4baa-82b1-6e857b230306 BOX_ID=2b544ba0-0d23-480d-b982-fd0a18dc9c8b
```

**Comment by kelea99** [comment]
Thank you! slacked stakeholder Ellen A. !
