### ISSUE TITLE
Repeatably Generate a Report on the Cloud Preservation Status of All Resources

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5978]
The report should be able to go through every resource in the database, make sure that (if it should be preserved - `ChangeSet.for(resource).preserve? == true`) that all of its files are in preservation storage, that its metadata is in preservation storage, and that both of those have the correct MD5s.

We can use the Google Cloud Storage calculated MD5 instead of re-calculating it so that we don't get charged for this check.

When this report has zero rows in it, we're done!

**Comment by tpendragon** [comment]
We ran this on production and found most resources failed because metadata checksums didn't match.

This is a flaw in checking metadata checksums as an idea. We add fields to FileSet over time, so the serialization changes. For instance, we've added `service_targets`. So if a FileSet is ingested on October 1, it says the following on both the cloud service and locally:

```
{
"title" => ["Test"]
}
```

but if we then add `service_targets` on October 3, locally it now says:

```
{
"title" => ["Test"],
"service_targets" => []
}
```
. The file's still preserved - if we restore the old file into the new it works, we're backwards compatible. However there's no way to translate the checksum for the old file serialization to the new.

We might want to change preservation metadata validation by storing the lock token on the object's metadata in GCS and checking that. We'd have to change our preservation function too.

**Comment by hackartisan** [comment]
Another idea is to not include properties that don't have values in the metadata json. This seems a bit simpler.

Either option will require re-preserving all the metadata targets.

**Comment by tpendragon** [comment]
> Another idea is to not include properties that don't have values in the metadata json. This seems a bit simpler.

This is a good idea, but I'm not sure if it fixes the fundamental problem of the schema being able to change over time. The most common issue is new fields that upstream doesn't have, but we could also add or change a default value, serialize something different, choose to delete a field on load, etc.

**Comment by tpendragon** [comment]
Running a report on lib-proc7 in a tmux pane.

**Comment by tpendragon** [comment]
First audit report with no metadata checks (except maybe at the end? It suddenly spiked in resource count..): https://drive.google.com/file/d/1-WTZ1SLMswlcYdWFoC4ekuDcnqol9Rkx/view?usp=drive_link

**Comment by tpendragon** [comment]
Running a report now that metadata for everything has been re-preserved. It's running on lib-proc7.

**Comment by tpendragon** [comment]
[bad_resources.txt](https://github.com/pulibrary/figgy/files/13562749/bad_resources.txt)
[since.txt](https://github.com/pulibrary/figgy/files/13562752/since.txt)

**Comment by hackartisan** [comment]
To run the report:
- make sure you're in a tmux session. it takes ~10 days.
- `rake figgy:preservation:count_unpreserved`

TODO:
- [ ] The report outputs some files in the rails root tmp directory. Make it output them to the rails shared directory.
  - Do this by adding shared/tmp/reports to https://github.com/pulibrary/figgy/blob/aa3f248081e866884b4aa962e6ca270c94a0e426/config/deploy.rb#L29 and then writing both the report and the resume timestamp there. The `state_directory` will need to be adjusted on the rake task.
- [ ] Add something to the rake task output that says that it does this, here https://github.com/pulibrary/figgy/blob/aa3f248081e866884b4aa962e6ca270c94a0e426/lib/tasks/preservation.rake#L11
