### ISSUE TITLE
FileSet errors aren't saving on the `original_file` on derivative failure.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5995]
We have a bunch of code in our DerivativeServices to save these, but they get rolled back by the transaction rollback system in place for our composite DerivativeServices like:

https://github.com/pulibrary/figgy/blob/2f370aaf8c30f2fa2b42ec9ed81164de79cbbd87/app/derivative_services/default_derivative_service.rb#L68-L74

If you write a test that uses the DefaultDerivativeService instead of the tested derivative services it replicates the error. That transaction needs to stick around, but we need a pattern to allow updating that FileSet outside of the transaction independent of success/failure.

**Comment by hackartisan** [comment]
How do I replicate? There's a suggestion but it's not specific.

**Comment by tpendragon** [comment]
You can replicate by changing this:

https://github.com/pulibrary/figgy/blob/5978-preservation-status/spec/derivative_services/vips_derivative_service_spec.rb#L165

to be `DefaultDerivativeService.new` instead of `derivative_service.new` - the right thing is probably to add a "malformed file" test to DefaultDerivativeService.
