### ISSUE TITLE
Add OCR language setting functionality to Parent record of a MVW in figgy.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6013]
### Summary
If you add an OCR language to the parent resource of an MVW, it doesn’t inherit to the child resources.

user story
_As a figgy user, I want to set the OCR language for a MVW in the parent record, so that all child/surrogate records will default to what was added in the parent record. If I want the volumes to have different OCR languages, I would set them on the children, and not set it on the MVW resource._  

- Example 01: I go to "edit scanned resource" in the parent record for a MVW. I set the OCR language to Spanish and Save.  Once saved, the Spanish OCR setting will be added to all child/surrogate records attached to the parent in the figgy MVW.
- Example 02: I notice multiple languages in my MVW. I go to "edit scanned resource" for each child/surrogate volume and set the preferred OCR for each volume.  I do not touch the parent record. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This will be helpful to EAL folks (Tom V. has a need for this in EAL) and others for their workflows. 
### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks - MULE
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
This is a MULE ticket

**Comment by tpendragon** [comment]
In chatting about this with @kelea99 we came to the conclusion that when you set an OCR language on a parent resource it should propagate to children.
