### ISSUE TITLE
Prevent deletion of a track that's part of a playlist

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6028]
And document this in https://github.com/pulibrary/figgy/blob/main/docs/technical/preservation/deletion.md

We can't restore the fact that it was in the playlist; this forces people to make an explicit choice to delete it both from the playlists and the recording.

It's also consistent with the way we've treated other deletions.

created out of #5557

**Comment by tpendragon** [comment]
I guess this means I also can't delete a recording that has tracks which are part of a playlist?

**Comment by eliotjordan** [comment]
Splitting the recording deletion part into a separate ticket.
