### ISSUE TITLE
Add facet for collection name to deletion marker search

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6031]
This means that when a resource is deleted we have to store the name of the collection it was a member of.

We're currently stashed the entire object in the deletion marker. Do a migration to look up member_of_collection_ids on deletion markers created before this issue was closed and add them to the deletion marker.

created out of #5557

**Comment by eliotjordan** [comment]
Migrated DeletionMarkers.

![Screenshot 2023-10-26 at 12 57 35 PM](https://github.com/pulibrary/figgy/assets/784196/9504393b-5660-41eb-9924-88fe5352e9cc)
