### ISSUE TITLE
Don't create DeletionMarker for Event objects

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#6038]
Not useful at this point and clutters the DeletionMarker search results.

Alternative:

Keep making DeletionMarkers for events, but hide them from DeletionMarker search results.

**Comment by eliotjordan** [comment]
We're going to stop creating DeletionMarkers for Events and delete existing Even markers.

**Comment by tpendragon** [comment]
This is deployed and I deleted all the DeletionMarkers for events.
