### ISSUE TITLE
[Figgy/production] GeoCoverage::InvalidGeometryError: n=29.51383 < s=88.077886

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6052]
## Backtrace

    line 24 of [PROJECT_ROOT]/app/values/geo_coverage.rb: initialize
    line 69 of [PROJECT_ROOT]/app/decorators/raster_resource_decorator.rb: new
    line 69 of [PROJECT_ROOT]/app/decorators/raster_resource_decorator.rb: coverage_from_file_set

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/99853527)

**Comment by sdellis** [comment]
It seems like this could be something we can validate and prevent Geometry Errors from entering the system?
