### ISSUE TITLE
Characterization failures should record an error_message on FileSets.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6059]
When things fail characterization they never leave processing and likely will never succeed, and the derivative health report should show that it's failed so they'll know they should reingest that item.

Right now some characterizers error and some ignore them (imagemagick.) Characterizers only have persisters, not ChangeSetPersisters, and the code in there is odd (it has instance methods that change their return value based on an instance variable that changes in a loop.)

**Comment by hackartisan** [comment]
We looked for errors that happen in characterization and found some examples that may be useful in writing tests and updating services. Assuming we just always want to record an error but retry as usual. Here are the errors we found:

- pdf service (`Vips::Error`): https://app.honeybadger.io/projects/53391/faults/100668696
- `CommandFailedError` in tika characterization: https://app.honeybadger.io/projects/53391/faults/95345499
- `NoMethodError` in tika characterization: https://app.honeybadger.io/projects/53391/faults/96395389
- `NoMethodError` in mediainfo: https://app.honeybadger.io/projects/53391/faults/103094817 on this line https://github.com/pulibrary/figgy/blob/6bb0c7c9b36e0b5f819164a01f8d487165f973c9/app/characterization_services/mediainfo_characterization_service.rb#L167
- `RSolr::Error::Timeout`: https://app.honeybadger.io/projects/53391/faults/97523712
- `DatabaseConnectionError`: https://app.honeybadger.io/projects/53391/faults/96017934
- `StaleObjectError`: https://app.honeybadger.io/projects/53391/faults/95936844

**Comment by eliotjordan** [comment]
Re-opening because error messages are not being saved when characterizatrion errors occur in actual Sidekiq jobs.
