### ISSUE TITLE
 Look into Performance for CDL items whose Login prompt seems delayed/not working in Orangelight

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6061]
### Summary
Original Ticket for CDL Login Prompt delayed/not working at all for CDL items : Orangelight repo 3788 : https://github.com/pulibrary/orangelight/issues/3788

Possible issue: bibdata call is being slow. 
Figgy uses bibdata to check permissions for CDL items.  Look into the performance

@tpendragon  suspects it's the same conclusion as @kevinreiss:  if they speed up the CDL flag in bibdata it'll speed that up.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
users cannot access our materials via CDL for some of these items and therefore cannot use those items in their research.
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
users cannot access our materials via CDL for some of these items and therefore cannot use those items in their research.

**Comment by hackartisan** [comment]
It seems like DACS would like us to rule out graphql as a potential cause for this slowness. If there's nothing that can be done on the figgy side they may move the cdl flag into the catalog index to speed things up.

**Comment by hackartisan** [comment]
I ran the network tab on the contents of the iframe that's loaded into the catalog. The examples given in the orangelight ticket took about 6 seconds to load for me. I also looked at honeybadger and didn't see any relevant errors. 

I looked at some APM and in particular at the ViewerController#auth action. It was averaging about 4 seconds, so that seems like a significant portion of the response time. I dug into the bibdata call that's part of that action, and it is just really variable. Sometimes it takes a very long time. Here's the page I was looking at: https://app.datadoghq.com/apm/resource/bibdata/rack.request/2f00923e58bd333e?query=env%3Aproduction%20service%3Abibdata%20operation_name%3Arack.request&env=production&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1698175628064&end=1698780428064&paused=true

**Comment by hackartisan** [comment]
It's curious to me that the examples given in the ticket as ones where it took a long time are not examples with a lot of holdings in the bibdata items response.

Looking at a few of the bibdata traces, the ones that took the longest were the ones with lots of items.

It would be helpful to be able to replicate this more reliably :(

Here are some potentially useful docs: 
- https://github.com/pulibrary/figgy/blob/main/docs/technical/viewer-flow.md
- https://github.com/pulibrary/figgy/pull/5483/files

**Comment by tpendragon** [comment]
A nice thing about Datadog is it'll track traces through multiple applications if we own them all. For instance:

https://app.datadoghq.com/apm/trace/2847947328791740378

That's the trace for this request. We can see that it's the Bibdata call, and we have to know if something's part of CDL to know if they could possible get access. I don't see another alternative from the Figgy side of things. Any other ideas I'm not thinking of?

**Comment by tpendragon** [comment]
Interestingly in the linked video they get a viewer, but it's blank, and for a really long time? I haven't been able to replicate that.

**Comment by tpendragon** [comment]
I think the only scenario where we render a blank screen is "I logged in for CDL and still don't have permission to see this resource" which...I'm not sure how to trigger for CDL. For reading room material it's easy.

**Comment by hackartisan** [comment]
But I'm not sure we've observed this close enough to know that bibdata is the bottleneck. Do we know the id of the resource in the video? And the day that happened? Could we find that actual trace?

**Comment by tpendragon** [comment]
We could speed this up by a few seconds if we cached CDL status for like a minute. Then Orangelight would say "Can I have a viewer?", Figgy would say "Yeah sure", then on viewer render the auth render would happen quick because it can cache the CDL check that the "Can I have a viewer" question did.

**Comment by hackartisan** [comment]
That's a great idea

**Comment by tpendragon** [comment]
The caching we've done here is a good enough first step to close this ticket - now the blue box appears pretty quickly on viewer load.
