### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `decorate' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6077]
## Backtrace

    line 121 of [PROJECT_ROOT]/app/controllers/application_controller.rb: viewer_exhibit_config

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/101858704)

**Comment by hackartisan** [comment]
figgy's viewer can't load a manifest from another institution. I don't know whether we have this use case, if so I guess it will come through as a feature request; closing.
