### ISSUE TITLE
As Ephemera Project owners, we would like a CSV download of all LAE Subjects controlled vocabulary, so that we can identify as a group core and area specific subjects in the control

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6086]
### Summary

same request by same stakeholders for same reasons in closed 2021 ticket #4639. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3-6 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
we said we could work it in after thansgiving/before winter break, which worked fine for stakeholders!

**Comment by tpendragon** [comment]
We think we can run `rake report:lae_subjects` and give them the CSV it makes.

**Comment by tpendragon** [comment]
[ephemera_subjects.csv](https://github.com/pulibrary/figgy/files/13676455/ephemera_subjects.csv)

**Comment by kelea99** [comment]
Reviewed and approved by Ellen A. Closing ticket.
