### ISSUE TITLE
Start Canvas does not show up on Manifest

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#609]
When saving from the Vue Filemanager, `start_canvas` gets passed but never ends up on the manifest. Alternatively, `thumbnail_id` also gets passed and does show up on the manifest.

**Comment by sdellis** [comment]
This should go on the Sequence (at least for now), although Presentation 3 API will support startCanvas on Manifests.

**Comment by hackmastera** [comment]
here's a spec
https://github.com/pulibrary/figgy/commit/9969695488ffdf6e67cdd1385615c28c429ca30a

that's as far as I've gotten but I'm putting this down for now.

**Comment by sdellis** [comment]
I may have missed it, but why was this removed from "ready"?

**Comment by escowles** [comment]
@sdellis We were doing sprint planning and cleared the ready column.  Feel free to pull out this or other tickets you plan to work on this week.

**Comment by sdellis** [comment]
Ok, thanks. I will discuss with @kevinreiss today to see if I can get one more Vue sprint in soon to take care of the remaining features/issues. This particular issue has to do with the manifest builder, but I can roll it into that work sprint.
