### ISSUE TITLE
Add line breaks after carriage returns in Ephemera description fields

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6092]
### Summary
Near East Collections Stakeholders also addressed the need for carriage returns in the descriptions for ephemera. They will be adding a lot of description to some of their ephemeral items. Carriage returns will make the user experience far better. An example provided by Gilda (see screenshot below). There are 6 paragraphs here that are running together. It would be ideal to have a. carriage return between each paragraph.
IMG_5516

https://figgy.princeton.edu/catalog/parent/82624edb-c360-4d8a-b202-f103ee639e8e/ee4e4edc-f06b-4dd8-a97d-95409ff4b614

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by tpendragon** [comment]
This is blocked by #5886. We'll review if this is still needed after that - it might be this becomes a migration ticket to transform the carriage returns that have been currently entered into multiple descriptions instead.

**Comment by tpendragon** [comment]
The folks who asked for this are working on description now, and are now able to use multiple description fields. We will not be doing a migration for this, and so we're closing this ticket.
