### ISSUE TITLE
preservation copy pdf displays "derivative files are not preserved"

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6101]
See this file set https://figgy.princeton.edu/catalog/parent/61fc351a-3fd5-499d-acf2-e6ca82505901/1d07e338-4c43-42df-8808-df31e6436d3a

Are PDFs not preserving even if they have a use of `preservation`? Or is this just an issue with the display text?

Note that the tiff derivatives are getting preserved, e.g. https://figgy.princeton.edu/catalog/parent/61fc351a-3fd5-499d-acf2-e6ca82505901/c817cda7-862a-4663-95d8-40eacd2fb823

## Acceptance criteria
- PDFs that are preservation files preserve
- PDFs that are preservation files display their fixity information

**Comment by hackartisan** [comment]
reopening until the migration added in #6106 is run.

**Comment by eliotjordan** [comment]
Migration run and (~10,000) preservation jobs running.
