### ISSUE TITLE
Set something up such that we run the preservation audit report again in X weeks or months

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6145]
How often do we want to run it? How will we ensure that it gets run and looked at?

Create a proposal for this and see what the team thinks.

**Comment by tpendragon** [comment]
Proposal: Use our optional DLS discussion time every 4 months to kick off the preservation audit, and then the one two weeks after to review the results.

The next one would be May 9, review on May 23.

One after that is September 12, review on September 26

One after that is January 9, review on January 23. Review in January book the next three, or see if we can set it up as a recurring meeting.

**Comment by tpendragon** [comment]
Meetings created.
