### ISSUE TITLE
FileSets added after being marked complete get out of sync metadata

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6150]
Characterization adds error messages and other things via a direct persister save, so the lock token increments but it doesn't re-preserve.

## Reproduce

Create a `FactoryBot.create_for_repository(:complete_scanned_resource)` with inline jobs, then compare the Preservation Object's `metadata_version` to the resource's lock token. They'll be off by 3.

**Comment by hackartisan** [comment]
Just to note that this issue said characterizers but the fix turned out to be in the create derivatives job.
