### ISSUE TITLE
fix external_metadata_derivative_service_spec.rb:54

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6158]
The build is currently broken; see https://app.circleci.com/pipelines/github/pulibrary/figgy/6872/workflows/44ab1ca9-f394-462b-a59f-ea407729032d/jobs/47563

**Comment by hackartisan** [comment]
I think #6162 worked toward this but the build is failing again on this same spec.

**Comment by eliotjordan** [comment]
Closed by https://github.com/pulibrary/figgy/pull/6165
