### ISSUE TITLE
Playlist plays but its figgy record 404s

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6161]
From Brittany:

I ran into a playlist that shows up when I search, but trying to access through figgy gives the message "The requested resource does not exist. You may have mistyped the address or the page may have moved"  The playlist is named: [MUS264 Week 07. Classes 13-14](https://figgy.princeton.edu/catalog/2d3a044a-835b-44f5-9d00-3a856f3afb52)   The link in ares to the playlist that works is: [redacted because it has an auth token; see slack message in #digital_library from 1/17/2024]

We think the playlist has a track that has been deleted. If so we can fix this by finding that track and removing it from the playlist member_ids.

## Sudden priority justification
This is needed for week 7 of a class taught in the upcoming Spring semester

**Comment by eliotjordan** [comment]
Removed proxy with missing file: "14.5a. Blowin' In The Wind - Bob Dylan (May 1963)".

Working now.
