### ISSUE TITLE
Bulk Ingest should accept WebVTT captions via a naming standard.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6180]
## Use Case

As a Figgy staff member I should be able to bulk ingest several videos, each with their own resource along with their captions so that I can have a vendor mass digitize materials and then ingest them later.

## Acceptance Criteria

When bulk ingesting a folder if there is a "filename.mp4" and a "filename.vtt" in the same folder, it should ingest however we decided in #6185. It should support having multiple transcriptions for a single mp4. Let's try "filename-English (Original Language).vtt" for a transcript thats label is "English (Original Language)"

**Comment by hackartisan** [comment]
How do we account for the language in this use case? complicated by the fact that it's a controlled vocabulary.

I guess I'll assume `filename-language-label.vtt`

what should happen if the language isn't valid?

**Comment by hackartisan** [comment]
Re: what should happen if the language is invalid: Is there an ISO code for "unknown"?
