### ISSUE TITLE
Paper Prototype attaching a Transcript to a Video

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6184]
## Use Case

As a Figgy staff member I should be able to ingest a video associated with a resource (ScannedResource or EphemeraFolder), mark it complete, add subtitles to it later, and it should render in DPUL, the Catalog, and Finding Aids so that researchers can view that video. This means I should be able to add subtitles later which will then make it viewable to the public. (It has to preserve, even if it doesn't have subtitles yet, and I have to be able to add subtitles later.)

## Scenario

I've uploaded a video and I want to upload a transcript into it.

## Acceptance Criteria

A paper prototype we agree upon which shows how to upload a new transcript into a resource with a video. It should also support uploading a second transcript to one that has one already. It should also support marking it as not having transcribable audio. 

## Likely Future Use Cases

We expect to want to be able to attach multiple transcripts, each with a different language. Maybe attach a label to the uploaded transcript?

## Options

Attach from the FileSet page?
"Attach Transcript" button from the File Manager, with a pop up to provide a label?

**Comment by sdellis** [comment]
How do we prevent people from marking "does not have transcribable audio" when it has transcribable audio? Can we verify with reasonable confidence? Are there any consequences for doing that?

**Comment by tpendragon** [comment]
> How do we prevent people from marking "does not have transcribable audio" when it has transcribable audio? Can we verify with reasonable confidence? Are there any consequences for doing that?

As long as they have to make the decision I think we can go by trust.

**Comment by sdellis** [comment]
Resource Show Page:
![resource-show](https://github.com/pulibrary/figgy/assets/609368/095ce00d-3a08-404e-9d6e-564929bf62af)

File Manager:
![filemanager](https://github.com/pulibrary/figgy/assets/609368/c7e3ebaf-7826-4f5d-a198-f1ee5c171791)

FileSet Show Page:
![fileset-show](https://github.com/pulibrary/figgy/assets/609368/c2fde580-a81d-408a-ad98-638ac5408b96)

FileSet Edit Page:
![fileset-edit](https://github.com/pulibrary/figgy/assets/609368/32ecfbf2-51d9-46f2-b8a5-eb1cb6a614cb)

Suplemental File Create/Upload Page:
![create-supplemental](https://github.com/pulibrary/figgy/assets/609368/5f330625-8fa4-406f-8048-2c0de0f9c79a)

Note: Annotations of above images with descriptions of UI changes are in progress!

**Comment by sdellis** [comment]
# Revised Wire Frames
Note: Fonts, icons, and colors in these wireframes are not consistent and may not be accurate. This is for layout and wording only. 

## Resource Show Page:
![Resource_Page](https://github.com/pulibrary/figgy/assets/609368/041c73ce-f390-472c-8235-b03aeb662338)

## Resource Show Page with Health Report Modal:
Coming soon ... 

## File Manager:
![FileManager](https://github.com/pulibrary/figgy/assets/609368/56644a38-46eb-424b-a89a-ed5ad117aa9f)

## FileSet Show Page:
![FileSetShow](https://github.com/pulibrary/figgy/assets/609368/396b0a11-cf0f-4aba-8ef6-87e1278d9e13)

## FileSet Show Page with Health Report Modal:
![FileSetShow-HealthReport](https://github.com/pulibrary/figgy/assets/609368/485c6e7c-83ce-43d2-aa0e-694e72b5d16e)

## FileSet Edit Page:
Coming soon... 

## Attach Caption Edit Page:
Coming soon...

**Comment by sdellis** [comment]
The FileManager Error should say "Attach Caption" instead of "Requires Captions | Upload". Whole error should be clickable.

**Comment by sdellis** [comment]
Note: ONLY Captions should have a "Delete" on the FileSet Show page.

**Comment by sdellis** [comment]
Keep the Attach form, retain and show the original filename, and add the appropriate tags to let users know that it's:

1. A Caption
2. In the original language
3. What language it's in
