### ISSUE TITLE
FileSets with video should have the option to be marked as not legally requiring captions

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6187]
## Use Case

As a collector I have a collection of silent films that I want to make public, but they are silent and thus would have no transcriptions. I should be able to make them viewable.

## Example

Pathé Baby Films

## Acceptance Criteria

Add a radio button to the FileSet edit page for "Legally requires captions?" - default to yes.

![FileSet-Edit-Page](https://github.com/pulibrary/figgy/assets/609368/ffea52ca-16d9-495c-9207-c1696166de74)
![FileSet-Edit-Page-with-Infoblurb](https://github.com/pulibrary/figgy/assets/609368/0a195980-9e80-4f1d-93c6-762025c9a4db)

**Comment by hackartisan** [comment]
@sdellis Can you please copy / paste the text of the modal into this issue?

**Comment by sdellis** [comment]
@hackartisan here you go:

> Princeton University Library has a legal obligation to provide adequate closed captioning for online educational content. Any resource that has videos containing important audio content will not be viewable until a caption is attached to each.
> 
> Videos captions must be created in the original language of the spoken audio and must be attached in the WebVTT format. Captions are transcriptions of important audio (including non-spoken audio) that are synced with the video through time codes. Subtitles, translations, and transcriptions do not satisfy our Accessibility requirements.
> 
> If your video is silent or contains audio content that is not essential to the content of the work, the video does not require a caption.

**Comment by Seanwarren77** [comment]
Could not find the right icon in lux, we will need to add something to finalize this. @sdellis  can you help with this?
