### ISSUE TITLE
Revise disk space alert for mounts

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6191]
With 10 production boxes that each have 5 isilon mount locations, we get 50 alerts in the datadog-alerts channel whenever the disk space threshold is reached.

Moreover, because the disk space threshold is a percent and the isilon is outrageously large, the alerts don't appear to necessitate any action.

We should figure out what alert we might actually need, and what action would be required in response to it. It seems likely that datadog is not the right place to monitor isilon capacy and we should remove these locations from the datadog alert altogether.

Example alert: https://app.datadoghq.com/monitors/4301126?q=device%3A%2F%2Flib-dps-server.princeton.edu%2Fmicroforms%2Chost%3Alib-proc7&source=monitor_notif&view=spans&from_ts=1706857226000&to_ts=1706858426000&eval_ts=1706858426000

**Comment by tpendragon** [comment]
CheckMK is going to replace all of these, so we're going to not do this. @acozine can you make sure that these alerts and this concern makes it to the monitoring group and that y'all will turn this off?
