### ISSUE TITLE
Add a Health Status report for transcripts for video files

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6192]
As a staff user I should get a notice in the health status if my resource should have a caption attached and does not.

## Acceptance Criteria

1.  When a resource has a Video FileSet and no caption, it should show there's something wrong in the health report.
2.  When a resource has a Video FileSet and that FileSet is set to not require captions, the health report should show healthy.
3.  When a resource has a Video FileSet and that FileSet has a caption (set to be in the original language of the video), the health report should show healthy.
4.  
![FileSetShow-HealthReport](https://github.com/pulibrary/figgy/assets/609368/485c6e7c-83ce-43d2-aa0e-694e72b5d16e)

**Comment by hackartisan** [comment]
I think this is blocked by #6182
