### ISSUE TITLE
Generate OCR

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#62]
Port OCR implementation from Plum, and queue workers to generate OCR for existing works.  The [Derrida collection](https://figgy.princeton.edu/catalog/7081b751-abb6-4f62-9c38-ff1fda0f9d30) should be processed first.

**Comment by rlskoeser** [comment]
I'm interested in OCR for CDH projects using PUL materials, but don't have an immediate need (and I'm aware that the OCR for the older Winthrop materials may not be very useful).

**Comment by tpendragon** [comment]
This got moved up to an immediate need because of an accessibility review of the Derrida site which said we need to provide OCR for those materials.

**Comment by tpendragon** [comment]
So this process is something like:

If I enable OCR via a property on the ScannedResource, pump each of its images through tesseract, generate H-OCR, place that H-OCR in the repository (not as a derivative right?), and then strip the HTML tags and embed it in the manifest.

Yes?

**Comment by escowles** [comment]
@tpendragon that looks good to me, including storing the hOCR in the repository so we could do things like upgrade it with transcription later on.

**Comment by rlskoeser** [comment]
Sounds fine to me.  I might be interested in getting more details from the H-OCR at some point, but I don't have an immediate need or use case for that.  Plain text should satisfy the immediate accessibility concern.

**Comment by sdellis** [comment]
@tpendragon when you say, "embed [the OCR] in the manifest" above, are you embedding it at the canvas level? 

@rlskoeser  how will end users with accessibility needs be able to read the OCR? Will it be part of a custom IIIF viewer (unforked UV doesn't display the OCR)? Also, if you have OCR of the text, but no transcriptions of the marginalia, will this OCR even be useful?

**Comment by rlskoeser** [comment]
@sdellis I'm not certain how useful/accessible the site will really be without images.  However, we're not currently using a IIIF viewer for this display, so we can simply add the OCR as alt text for the page image. The annotations have been transcribed and documented by the team, and include tags to indicate the type of marginalia, transcriptions of annotation text for verbal annotations, and anchor text (displayed for non-verbal annotations).

**Comment by tpendragon** [comment]
We're just generating the H-OCR now because we have a later use case for hit highlighting and it's useful info to have. It'll just be a plain-text download in the manifest.

**Comment by sdellis** [comment]
If you're getting the OCR at the canvas level, then alt-text seems like a good simple solution for the pages. 

However, I agree, OCR alone will not allow those with visual impairments to experience this work the way it was intended as it's not about reading the text, but rather about Derrida's annotations in relation to the text. It seems like capturing and conveying that relationship in a non-visual way would be an important part of making Derrida's Margins accessible.

**Comment by tpendragon** [comment]
Maybe we should be storing OCR as a property on the FileSet rather than in a file in the repository? It'd likely keep generating manifests performant, and then we wouldn't have to handle cleaning them up. Could better enable working on the OCR in the front-end in the future too.

**Comment by escowles** [comment]
👍 storing OCR as a property seems reasonable to me.
