### ISSUE TITLE
Failing health report: Nicaragua [microform] : North American Congress on Latin America (NACLA) archive of Latin Americana

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6218]
This resource has failures in derivative generation and fixity checks. https://figgy.princeton.edu/catalog/b1daaa9f-1563-4241-a634-fac125f5836e

Contact Kim McCauley as the stakeholder for this item if needed

**Comment by tpendragon** [comment]
This reel needs reingested: https://figgy.princeton.edu/catalog/636f08d8-376b-4d90-b43e-a6727270a387

**Comment by tpendragon** [comment]
I'm closing this, Kim's going to handle reingesting.
