### ISSUE TITLE
Research effort to change slug in DPUL exhibit https://dpul.princeton.edu/msi

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6240]
### Summary

Refer to : https://github.com/pulibrary/figgy/blob/main/docs/technical/changing_collection_slug.md

Requested slug: https://dpul.princeton.edu/specialized-digital-imaging

I am happy to rebuild it, if this is a heavy lift.  
KEL time estimate of work: will take up to, but not exceeding 2 hours. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Due next week, end of day Wednesday.
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Submitting materials to LSC for review, which includes this DPUL site.

**Comment by kelea99** [comment]
I wonder. there is a space to change the slug in DPUL...  have we ever tried changing the slug in figgy then changing the slug in dpul or vice versa? I can test that too...

**Comment by tpendragon** [comment]
Done.

In DPUL:

```ruby
e = Spotlight::Exhibit.where(slug: "msi").first
e.slug = "specialized-digital-imaging"
e.save
```

In Figgy:

Go change the slug on the collection in the UI: https://figgy.princeton.edu/catalog/3eb34ff2-ba8f-4e52-b11f-67791f71fe20
