### ISSUE TITLE
Helenica Posters ephemera items not ingesting

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6249]
### Summary

Please update Beth Haas once this issue is resolved.

Potentially a result of the jammy machine setup, ingest is not working after running the `lae:ingest_disk_files` task. At first it appeared that the new box simply needed to be added to known_hosts, but images haven't ingested on subsequent runs of the task.

The task is run on lib-proc4. Invocation is:
```
""ssh deploy@figgy-worker-prod2 "cd /opt/figgy/current; RAILS_ENV=production bundle exec rake lae:ingest_disk_files "'/mnt/diglibdata/pudl/lae_to_ingest/32101046816920'""
```

An example item that should be ingested after this run is barcode 32101118176260

### Impact 
This is an evergreen project and the ingest doesn't have a particular deadline, but this script is used for other ephemera loads and will become a work blocker moving forward.

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification

This load script is used for ephemera projects and blocks work if it's broken.

### Expected behaviour

After running the script, images are ingested to the ephemera resources

### Actual behaviour

No result.

**Comment by kelea99** [comment]
We are testing something. @roelmoon noticed the box visibility did not match the item/folder visibilities. I just changed the box visibility to match the folder visibilities and he is retesting the ingest.

**Comment by roelmoon** [comment]
Still not working, material didn't ingest after @kelea99 changed box visibility.

**Comment by kelea99** [comment]
Can you give me a path to the files, @roelmoon

**Comment by roelmoon** [comment]
@kelea99 Box 14 path is ~pudl/lae_to_ingest/32101046816920
