### ISSUE TITLE
Ukraine Ephemera Box #35 refusing to go into production (batch complete of folders). 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6258]
### Summary
From Anna Meerson: I'm currently experiencing difficulty marking box #35 as complete for Print Ephemera from Ukraine. When I change the status to "All in production," Figgy opens the box editing mode instead of applying the action. Could you please look into this issue? https://figgy.princeton.edu/catalog/parent/1e722b00-8876-4a94-9092-ece7007e9894/64afa3c5-eb11-4a21-9e93-f6bae0a6e818

Because the batch complete will not complete until all derivatives are generated, I did a selective search of items to check the health status (awesome visuals, @sdellis , super easy to notice reds).  I found one that failed cloud fixity:  https://figgy.princeton.edu/catalog/parent/64afa3c5-eb11-4a21-9e93-f6bae0a6e818/0b4eb9a3-bf3f-4600-a7c8-7435507db8ef

I think it would be useful to:

- Run report on Box 35 to see what the status of the derivatives are
- Fix the sadness
- test the "all in production" workflow for box 35 again
- think about ways users can see what has failed more easily in figgy (faceting?) or maybe give them agency to run a report on a .....oh! I wonder if we can include fixety information on the report that can already be run on all ephemera?

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

## Implementation Strategy

This is the behavior when a validation fails. We should figure out what validation is failing, and see if we can fix it. We'll create another ticket for the fact that some derivatives have failed somewhere in this box, and the cloud fixity is failing.

**Comment by tpendragon** [comment]
I think batch complete works when cloud fixity falls, just not when derivatives fails right?

**Comment by kelea99** [comment]
Does it work differently with ephemera? This is pushing everything into production at the box level.

**Comment by tpendragon** [comment]
https://figgy.princeton.edu/catalog/43c4f8f2-fe19-41d9-af8b-45fee571d1e4 is corrupt, so derivatives aren't generating, so we can't mark it complete.

We can either delete that file and mark them all complete anyways, or we could get that file fixed.

**Comment by tpendragon** [comment]
@kelea99 will follow up. Closing this ticket.
