### ISSUE TITLE
Develop a wireframe for a PDF loading page

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6280]
A user will see this after clicking "Download PDF" in the Universal Viewer or somewhere else. It should have some kind of loading bar - when it reaches the end it will automatically redirect to the PDF.

**Comment by hackartisan** [comment]
Here's a simple idea that uses bootstrap's striped progress bar, a stripped down header, the usual footer, and the resource title.

![Figgy #6280](https://github.com/pulibrary/figgy/assets/845363/6253858b-0e53-4673-bc0b-67796d79dcf6)

(The file's at https://docs.google.com/drawings/d/1qyqzNX44JqS7K6CMaHIToTW9GBzZ9majJMUxyPhpLkc/edit)

**Comment by hackartisan** [comment]
- Try it without headers and footers, and maybe a gray background
- Try it with the "you will be redirected" text.
- Try adding a iiif puzzle game.
- Maybe add some language to make it clear that you can close the tab and it will keep generating.

**Comment by tpendragon** [comment]
![Screen Shot 2024-04-01 at 1 13 39 PM](https://github.com/pulibrary/figgy/assets/2806645/49adb699-b3ba-4313-9a3a-77422ec445ed)

is the screenshot! https://github.com/pulibrary/figgy/commit/b37f161a3d7eb7eecf60cc50f64848093822717a has some of the styles I used to generate this.
