### ISSUE TITLE
Wireframe: Allow users to diagnose and fix files in child resources from the parent resource.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6297]
Right now it's impossible to tell which of the 100 folders in https://figgy.princeton.edu/catalog/parent/1e722b00-8876-4a94-9092-ece7007e9894/64afa3c5-eb11-4a21-9e93-f6bae0a6e818 has a failing status. That should be possible.

It should also be possible for Multi-Volume Works.

## First Step

Generate a wireframe for displaying "resources with a problem" in the health status view.

**Comment by tpendragon** [comment]
Generating a health report for all children for #6296 took over a minute, so we wouldn't be able to do this on all pages all the time unless we optimized that somehow.

**Comment by sdellis** [comment]
Here are draft wireframes for viewing problematic resources in the Health Status modal for an Ephemera or MVW parent resource. A button for expanding and collapsing the list of problematic resources is proposed. Each link in the list would take the user to the File Manager page for that child resource, which is the most direct path to see the filesets that need attention. In the case of a long list, which could potentially be hundreds of child resources, the list container element would be scrollable so as to not extend the modal too far down the page. 

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94fd1191eb57a452956460a75f6d8b0ff4f11f0a/figgy-issue-6297-wireframe-collapsed.png" alt="figgy-issue-6297-wireframe-collapsed.png" />

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9630aa09a33f71439412775b14ad2613ce8dd79/figgy-issue-6297-wireframe-expanded.png" alt="figgy-issue-6297-wireframe-expanded.png" />

**Comment by sdellis** [comment]
Suggestion from DLS Slack:
Since it can take a few seconds to generate a list of links to resources that need attention, we should add a "loader" gif/thingy so the user understands the list is being generated. The opening of the modal should trigger the load, but the user only sees it if the list has not completed generating/loading if they expand the button.

**Comment by sdellis** [comment]
## Wireframe State 1: Collapsed list of problematic resources

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3hmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0591fe28d47650dcddf181fef39e9dadcd2105bb/01_figgy-issue-6297-wireframe-COLLAPSED.png" alt="01_figgy-issue-6297-wireframe-COLLAPSED.png" />

## Wireframe State 2: Display spinning Loader as list of problematic resources is generating

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE5mQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc78ccaffff76dcce0bc4f1ab6c229d99fec2972/02_figgy-issue-6297-wireframe-LOADER.png" alt="02_figgy-issue-6297-wireframe-LOADER.png" />

## Wireframe State 3: Expanded list of problematic resources

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzlmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6947bd1791e8b52722ebe3925c85473c24107b75/03_figgy-issue-6297-wireframe-EXPANDED.png" alt="03_figgy-issue-6297-wireframe-EXPANDED.png" />

**Comment by tpendragon** [comment]
This report should:

1. Only show up for resources that have child resources (deep) (non-FileSets)
    * E.g if I have an Ephemera Project with a bad folder in a box, the Ephemera project's health report should have a link to the Folder, not the box, since the box's file manager will be empty.
2. Each link should send you to the file manager for that child resource
3. Each link should say how many are bad - e.g `XXI Bk, No. 117 (2416) - 7 Files Affected` 
4. The report should start to load when the health modal is opened.

**Comment by tpendragon** [comment]
Implementation ticket: https://github.com/pulibrary/figgy/issues/6341
