### ISSUE TITLE
When no PDF is available, end-users should not be redirected to a figgy show page

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6305]
The "no pdf available" message is currently presented as a flash on the show page, so if you've gotten there from another application it seems pretty confusing.

To replicate: go to https://catalog.princeton.edu/catalog/9924010593506421 and scroll down to the viewer. Click "download" and select "PDF", submit.

**Comment by hackartisan** [comment]
Here's another resource, with no download options: https://dpul.princeton.edu/ealtoc/catalog/bc4f6a8f-2d56-4c45-902c-b10274f76013 -- user can't get to the pdf endpoint.

Maybe we just need to make sure the pdf option isn't clickable when no pdf is available.

**Comment by tpendragon** [comment]
The resource doesn't have a download button unless you're an admin in Figgy.
