### ISSUE TITLE
Add "videos" to the scanned resources description on the home page

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6306]
It currently says "Books, Manuscripts, Scanned Documents, and CDs"

screenshot:
![Screenshot 2024-03-29 at 9 37 17 AM](https://github.com/pulibrary/figgy/assets/845363/ddb56d3f-af8c-4451-b36f-c1cf1af365a8)

## Success Criteria

Change to "Books, Manuscripts, Scanned Documents, Audio, and Video"

## First Step

Search the code base for "Books, Manuscripts"

**Comment by kelea99** [comment]
Ill also change documentation text in Confluence to include video.
