### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `ocr_content' for #<ScannedMap id=#<Valkyrie::ID:0x00007fecd871f508 @id="94cfed2f-9bfb-43a7-bf1a-f77be0f629af"> internal_resource="ScannedMap" created_at="2018-02-24T00:22:01.004Z" updated_at="2023-10-28T23:52:02.967Z" new_record=false optimistic_lock_token=[#<Valkyrie::Persistence::OptimisticLockToken:0x00007fecd871dbb8 @adapter_id=#<Valkyrie::ID:0x00007fecd871dc08 @id="746f06acf4d573bebd8c8a500b398589">, @token="1">] read_groups=["public"] read_users=[...

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6309]
## Backtrace

    line 594 of [PROJECT_ROOT]/app/services/manifest_builder.rb: ocr_content
    line 14 of [PROJECT_ROOT]/app/services/manifest_builder/canvas_rendering_builder.rb: apply
    line 8 of [PROJECT_ROOT]/app/services/manifest_builder/canvas_builder.rb: apply_record_properties

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/103971250)

**Comment by tpendragon** [comment]
Removed start_canvas from the object via the terminal. We have no idea how it got there.

**Comment by eliotjordan** [comment]
Showing up again.

https://figgy.princeton.edu/catalog/12880711-53c3-4129-9ca0-55bb6ce1ff00

**Comment by eliotjordan** [comment]
Fixed.
