### ISSUE TITLE
Could a user export the Vue state when getting an error in production?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#632]
This would be very useful for debugging

**Comment by sdellis** [comment]
They definitely could, but not with the Vue DevTools extension (would require the user to install anyway) as it's disabled outside development. I could either expose it to the window so someone could type `JSON.stringify(state)` in the console. Or if I can catch the error, we could present it to them to send along (or even better, log write it to the logs).

**Comment by hackmastera** [comment]
So far we've been able to debug without this type of data.
