### ISSUE TITLE
Report Needed: How many objects are linked to MMS IDs in Figgy?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6324]
### Summary
See https://github.com/pulibrary/bibdata/issues/2330 for reference
DACs needs a report run against figgy that includes:

- MMS ID
- Ark(s)
- Figgy identifier/hash
- Type of work
- Visibility
- State

### Goal 
Rectify the faceting in Orangelight to accurately reflect what online content is actually there, including all of figgy content (faceting and online content link in record itself)

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Users are not able to find anything that has been added to Figgy since 2021 via the faceting. Users are confused or miss the online content entirely, because it is not noted in the catalog record (and is only visible if the user scrolls down).

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
DACS is working on their quarterly sprint planning this week and working out a plan/roadmap to commence work this on sometime after all hands (Ideally). If they have this report in hand, they will be able to more accurately scope the future work.

**Comment by tpendragon** [comment]
Code to generate report:

```ruby
CSVReport.new(ChangeSetPersister.de
fault.query_service.custom_queries.all_mms_resources
, fields: [:id, :source_metadata_identifier, :identi
fier, :internal_resource, :change_set, :visibility,
:state]).write(path: Rails.root.join("tmp", "mms_id_
resources.csv")); nil
```

```sh
scp deploy@figgy-web-prod1:/opt/figgy/current/tmp/mms_id_resources.csv ~/Downloads/mms_id_resources.csv
```

Report is attached.
[mms_id_resources.csv](https://github.com/pulibrary/figgy/files/15223823/mms_id_resources.csv)

@kelea99 @maxkadel @kevinreiss Can you confirm this is what you needed so I can close this?
