### ISSUE TITLE
Upgrade Solr to Solr 9

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6342]
Work with Operations to experiment on adding a Solr 9 box to our existing cluster and upgrade them with zero downtime.

## Options

1. Add a new Solr 8 box to the cluster, make it a replica of everything, take it down, upgrade it to solr 9 with a playbook, put it back up, see if it works.
2. Add an empty Solr 9 box to the cluster, make it a replica of everything, see if it works.

## First Step

Find time with @acozine 
Get a virtual machine

**Comment by hackartisan** [comment]
On closer inspection of [the documentation](https://solr.apache.org/guide/solr/latest/indexing-guide/reindexing.html), this proposed strategy won't get us out of having to delete and reindex. Since that's what we were hoping to gain, it's not worth doing this work.
