### ISSUE TITLE
Images ingesting with a black bar across the tiff

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6407]
### Summary
See https://figgy.princeton.edu/concern/scanned_resources/93fa3696-98bb-47ff-bb3a-3e54ec7dea5f/file_manager

Report from Brianna Garden: "It seems like different files are being merged together into one image, like 70, 74, 76, etc. The files on my computer seem normal."

The directory used for the upload is `/mnt/hydra_sources/mudd/ingest_complete/MC001.04_c12061`

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification

This is for a patron digitization request

## Acceptance Criteria

- [ ] A resource that's created by ingesting these files has no black bars in them.

## Things to Test

If we reingest, do the black bars reappear?

Are there black bars in the source file? No.

Are there black bars in the file in the repository? Yes.

### Steps to reproduce behaviour

On figgy-staging, create a scanned resource using the component ID `MC001.04_c12061`. Go to its file manager and select "ingest from server", then navigate to the directory cited above.

If everything looks fine, advise Brianna to delete the resource and reingest it.

**Comment by hackartisan** [comment]
from @kelea99:

I think it would be helpful to learn (just seeing the ingest attributes for the images):
- Were these images taken in house at mudd or outsourced?
- If they were in house,  something is up with the settings, perhaps? those files are enormous and they shoudlnt be, from what I can see.
- If they were outsourced, it would be good to look at the contract and compare the deliverables to ensure they are doing what is expected, best practices wise

**Comment by eliotjordan** [comment]
- Ingested resource on figgy-staging and derivatives were processed normally.
- Deleted the old resource in Figgy prod. Re-ingested, and completed a new version:
https://figgy.princeton.edu/catalog/5e5246e7-101f-4fe2-b544-3b6f5350f642

@kelea99 Anything else to do here? Looks like this was a temporary problem with derivative processing.
