### ISSUE TITLE
Figgy Vue3 upgrade issues

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#6416]
I found some UI inconsistencies after upgrading Vue and Lux:

1. Upload buttons in File Manager are incorrectly spaced.
![Screenshot 2024-05-29 at 3 50 47 PM](https://github.com/pulibrary/figgy/assets/784196/50cf1108-93f9-4175-b959-a7039f67424b)

2. ~~Health check file list spinner no longer displays (is using component from previous version of Lux).~~

3. ~~Buttons on edit page "save work" panel are incorrectly spaced.~~

## First Step

Replicate, find the CSS.

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/issues/6417 might be another one.

**Comment by eliotjordan** [comment]
All issues above have been fixed.
