### ISSUE TITLE
Map bitcur-archives share to figgy as ingest point for users

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6421]
### Summary
With the help of Annalise and Philippe, Amy Vo and archivists have developed a new workflow for born digital processing work  They are needing to be able to access a new share from the isilon (bitcur-archives) as an ingest point within figgy.  Original information is below. Speaking with Philippe on 05/31/2024, this is not an asap request. Something in the next 3-6 weeks, however, would be nice.  
Original information:
> Annalise and Philippe had created a virtual machine (VM) from which the archivists could do their born-digital processing work from their own computers, rather than one of the two FRED processing stations. I have been working through some of the new workflows in the VM – the workflow for creating access copies in our finding aids involves uploading these copies of processed born-digital content to Figgy. Another new, and important part, of these new VM workflows is the use of the bitcur-archives drive, which we are now primarily using in our work, though we still use archives_bd (Isilon) for some of the work that we do with removable media. In Figgy, the current drive/server options from which we can choose (and to which I have access to) only include archives_bd and archives. Would it be possible to add bitcur-archives to the list of options in Figgy?

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Adding this share as an ingest point to figgy will allow Amy Vo and other users to make their process content available digitally in our applications. 
### Priority recommendation

- [ ] asap
- [x] within the next 3-6 weeks (discuss with DLS in standup 5/31/2024)
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

### Screenshots
![Screenshot 2024-05-29 at 7 00 43 PM (1)](https://github.com/pulibrary/figgy/assets/45043014/51235546-05ef-42c7-8cd7-c7da38cc5806)

## First Step

Talk to Philippe to get user/password for that share to add to princeton-ansible.

**Comment by tpendragon** [comment]
I emailed lsupport.
