### ISSUE TITLE
Failed migrations from Plum leave orphaned GenerateChecksumJobs

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#644]
When a migration fails, it has already queued GenerateChecksumJobs.  The transaction is rolled back, the FileSets are deleted, but the queued jobs remain behind, and fail because the FileSet doesn't exist.

**Comment by tpendragon** [comment]
@escowles It's GenerateChecksumJobs which are left behind, right?

**Comment by escowles** [comment]
@tpendragon Oh, yes, it's GenerateChecksumJobs (because the derivatives are linked)
