### ISSUE TITLE
Batch Add OCR to entire Industrial Relations Ephemera Project items

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6448]
### Summary
OCR was accidentaly not set at ingest and over 5,000 items are currently in the collection. may we batch add the language OCR to the lot of them? 

They are primarily English (see faceting):

 https://figgy.princeton.edu/?f%5Bephemera_project_ssim%5D%5B%5D=Industrial+Relations+Ephemera&q=
### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
This collections is going to be used in a workshop by Bryan Winston and Charissa Jeffersion at the end of the summer. Ideally within the next 3-4 weeks.

## Acceptance Criteria

- [ ] The ocr_language on everything in the Industrial Relations Ephemera Project is set to english.

## First Step

Write a script that loops over all of the EphemeraFolders inside that collection and sets ocr_language to "eng".

## Implementation Notes

It might be worth taking a little time to see if it would be hard to add bulk edit functionality for EphemeraProjects. If it doesn't seem reasonable, then just write a script to do it. The script that's run should be in this ticket when it's closed.

**Comment by eliotjordan** [comment]
Script used to update ocr_language:

```
def find(id)
  ChangeSetPersister.default.query_service.find_by(id: Valkyrie::ID.new(id))
end

project = find("a4ce64f7-f35e-447a-a2e4-5189ab34107f"); nil
boxes = project.decorate.boxes; nil

folders = []
boxes.each do |box|
  folders = folders + box.decorate.folders
end; nil

change_set_persister = ChangeSetPersister.default
folders.each do |folder|
  cs = ChangeSet.for(folder)
  cs.visibility = ["open"]
  ChangeSetPersister.default.save(change_set: cs)
rescue
  next
end
```

**Comment by tpendragon** [comment]
The script above saved decorators, which resulted in broken references to genres and things for all those objects.

We ran the following script to fix them:

```ruby
def find(id)
  ChangeSetPersister.default.query_service.find_by(id: Valkyrie::ID.new(id))
end

def convert_objects(objects)
  return if objects.nil?
  objects.map do |object|
    if object.is_a?(EphemeraTerm)
      object.id
    else
      object
    end
  end
end

project = find("a4ce64f7-f35e-447a-a2e4-5189ab34107f"); nil
boxes = Wayfinder.for(project).ephemera_boxes; nil

folders = []
boxes.each do |box|
  folders = folders + Wayfinder.for(box).ephemera_folders
end; nil

change_set_persister = ChangeSetPersister.default
folders.each do |folder|
  cs = ChangeSet.for(folder)
  cs.validate(
    genre: convert_objects(folder.genre),
    language: convert_objects(folder.language),
    geographic_origin: convert_objects(folder.geographic_origin),
    subject: convert_objects(folder.subject),
    geo_subject: convert_objects(folder.geo_subject)
  )
  ChangeSetPersister.default.save(change_set: cs)
rescue
  next
end
```
