### ISSUE TITLE
Move Box 25 in SAE DK  Ephemera Project to SAE Ephemera Project 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6464]
### Summary
Hi Kim, happy Friday:) I'm writing to ask if the devs could transfer [DK-SAE Box 25](https://figgy.princeton.edu/catalog/5ed9b9ea-ccdb-4717-8ba0-37e3d9ddbb1b) into [SAE](https://figgy.princeton.edu/catalog/f99af4de-fed4-4baa-82b1-6e857b230306) whenever they can fit it into their work. DK Agencies has completed the metadata, so once it's in SAE, I'll make it live. Huge thanks, and let me know if you'd prefer to receive these requests in a way other than Slack.
### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by hackartisan** [comment]
Here's how you do it
https://github.com/pulibrary/figgy/issues/5971

**Comment by hackartisan** [comment]
done

**Comment by kelea99** [comment]
Let @ellen-aa know. Thank you!!
