### ISSUE TITLE
Add CB-BY-Noncommercial-No derivatives statement option to figgy rights statements dropdown in edit form.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6476]
### Summary
@escowles  can you help with this?  For Urban Video Archive collaboration and requested by Fernando Acosta-Rodriguez

https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by escowles** [comment]
@kelea99 I'm seeing CC-BY-NC-ND in the rights menu now — is there something wrong with it, or something else needed?

![Screenshot 2024-08-20 at 12 26 06 PM](https://github.com/user-attachments/assets/eae8b362-f52d-4547-900a-eff77136bd0b)

**Comment by kelea99** [comment]
oooo nope! closing and thank you!
