### ISSUE TITLE
Create new or better way to batch ingest coins for numismatic records

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6480]
### Summary

Walking through the process  with Elana, the rake task being used to search and find the coins for the specific record being worked on is taking forever.  (see video).  once the coin directory is found, it may take yet more minutes to ingest to the record. (see video)

Short term: review task/code to try to speed up the search for coins to be ingested? 
ingest directly from server? No. the students are needing automatic for a variety of reasons as well

Long term: Batch ingest coin images, like we do for scanned resources or Ephemera?

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
This work is being slowed down to as much as 10 minutes per coin ingest for Elana, and the student workers who are also having this same experience. for the 16,600 coins in need of work and the pressure  on numismatics staff to finish things off quickly is making for a stressful situation. 
### Videos

ONE

https://github.com/user-attachments/assets/cda92880-f780-475e-b5bc-f804a1408656

TWO ( a few seconds later)

https://github.com/user-attachments/assets/1a450b4d-8521-453d-9021-b8a1b0687df5

**Comment by eliotjordan** [comment]
I'm not sure why the search is taking so long, but it is still possible to add images using "upload from server":

![Screenshot 2024-08-23 at 3 07 40 PM](https://github.com/user-attachments/assets/3729a403-efe2-460a-8a92-9c0bf95d96d8)

**Comment by kelea99** [comment]
@eliotjordan correct and we discussed that workflow option. According to Elana, it takes too long and the students get lost looking for the right directory and then the right coin.

**Comment by tpendragon** [comment]
The only ways to make this faster are to either:

1. Remove the old coin directories from the place this code is searching (numismatics share)
2. Define a directory that only has directories of coins to ingest, and we can change the code to not search deeply for directories.

**Comment by kelea99** [comment]
Troubleshoot: 

1. Elena has requested access to the X drive on the student computer so that she can start moving and deleting file folders, so that the numismatics directory can get in better order.
2. We are to map the auto search to ONLY the Numismatics => CoinImages directory.

**Comment by kelea99** [comment]
created ticket https://github.com/pulibrary/figgy/issues/6484 . @eliotjordan should I close this one?

**Comment by eliotjordan** [comment]
Closed in favor of #6484
