### ISSUE TITLE
Resource has a few bad tiffs and health check is good

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6483]
https://figgy.princeton.edu/catalog/9a2660bf-8ae4-4a54-8f1e-0f58255889b0

## Backtrace

    line 14 of [PROJECT_ROOT]/app/services/pdf_generator/canvas_downloader.rb: download
    line 26 of [PROJECT_ROOT]/app/services/pdf_generator.rb: block in render
    line 19 of [PROJECT_ROOT]/app/services/pdf_generator.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/106879537)

**Comment by eliotjordan** [comment]
@kelea99 Do you know wtharris (or whoever is responsible for this item)?

**Comment by kelea99** [comment]
yes! He is a photographer in @roelmoon 's group. Im on it

**Comment by kelea99** [comment]
@roelmoon reviewed and this is from a shoot 3 years ago. The pages need to be rephotographed. Hes coordinating with AnnaLee to get the item back up in the studio.

**Comment by tpendragon** [comment]
Checked, looks like this got reshot.
