### ISSUE TITLE
CDL usage report

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6487]
We'd like a report of CDL usage for the past year. Needed by Wednesday 9/11. Deliver to Esmé.

for reference: https://github.com/pulibrary/figgy/issues/6171

also potentially relevant: https://github.com/pulibrary/figgy/pull/6440

## Acceptance Criteria
month-by-month report of total CDL usage counts for the past year. no specific format required.

## first step
Look at the referenced PR and play around with it in a console on prod.

## Sudden priority justification
Needed for decision-making

**Comment by hackartisan** [comment]
## Report: Counts per month over the last year of CDL items charged
2023/9: 21
2023/10: 10
2023/11: 12
2023/12: 14
2024/1: 13
2024/2: 18
2024/3: 20
2024/4: 17
2024/5: 18
2024/6: 10
2024/7: 4
2024/8: 11
Total: 168

## code used:
```
> query_service = ChangeSetPersister.default.query_service
> lists = query_service.find_all_of_model(model: CDL::ResourceChargeList)
> with_items = lists.select { |l| l.charged_items.present? }
> range_start = Date.parse("2023/09/01"
> range_end = Date.parse("2024/08/31")
> items_in_range = with_items.map do |list|
*   list.charged_items.select { |i| i.expiration_time <= range_end && i.expiration_time >= range_start }
* end
> items_in_range.reject!(&:empty?).flatten!
> checkouts_by_month = items_in_range.group_by { |item| Date.parse("#{item.expiration_time.year}/#{item.expiration_time.mon}") }.transform_values { |l| l.size }
> checkouts_by_month = checkouts_by_month.sort_by { |key| key }.to_h
> checkouts_by_month.each do |key, val|
*   puts "#{key.year}/#{key.mon}: #{val}"
* end
* > puts "Total: #{checkouts_by_month.values.sum}"
Total: 168
```

**Comment by escowles** [comment]
Thanks @hackartisan! This is a great summary of the usage I can use as we decide how to move forward with CDL.
