### ISSUE TITLE
Investigate 4k MP4 video file ingest issues

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6489]
### Summary
Tested this in Figgy staging, both for Ephemera Project and for Scanned Resource ingest. The ingests themselves were successful (also local/cloud fixity check aok). However, the viewer is not showing anything.  

Reasoning for need:
Stakeholder has asked if 4K MP4 is possible for preservation purposes in Figgy (this is currently not an option for Princeton University Kaltura / Media Central submissions).  @roelmoon has also shared that there is 8k capacity for some cameras. We should think about this.  

[Figgy Staging Ephemera ingests (4K)
](https://figgy-staging.princeton.edu/catalog/f12456b9-342f-4681-80a3-da1b7854aaac)

[Figgy Staging Scanned Resource ingest (4K)](https://figgy-staging.princeton.edu/catalog/d679b65e-ef3d-4d7b-9213-1d3c63ae4a54)

Also ingested the 2K versions of these videos (both 4k and 2k were converted from original .MOV files). these ingested fine and view fine in Figgy:

[Figgy Ephemera Production (2K)](https://figgy.princeton.edu/catalog/0f912488-fa96-406f-9239-2d67fccddb02)

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

**Comment by tpendragon** [comment]
@kelea99 Can you look at these? We didn't change anything, and all the ones from above we can see are playing.

**Comment by hackartisan** [comment]
turns out they worked eventually!
