### ISSUE TITLE
Opening a Ephemera Project box in Figgy breaks figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6493]
### Summary
Reported by Adrianna Tarabolletti.  She is getting this error message everytime she opens any and all Ephemera Project boxes in Figgy. Error states (also see screenshot):

"DataTables warning: table id=members - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

### DLS info
This error was caught in Honeybadger today as well. Probably due to rails upgrade. 
Short term fix suggestion: roll back rails upgrade, if immediate fix needed. 

## First Step

Revert the Rails 7.1 Upgrade

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
It is stopping stopping her work. She will not be in on the Sept 11 but she will need it fixed by Thursday September 12.
### Priority recommendation

- [x] asap - by Thursday, 09/12/2024
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
Stopping her work for her job. 

### Expected behaviour

When I go to a Figgy ephemera box, I expect that box to open without an error code and see the folders within.

### Actual behaviour

When I go to a figgy ephemera box, I get a pop up error. I click ok and I see none of my folders. 

### Steps to reproduce behaviour
go to: https://figgy.princeton.edu/catalog/a4ce64f7-f35e-447a-a2e4-5189ab34107f

Click "view" on any ephemera box

Ta daaaa

### Screenshots
<img width="1512" alt="Screenshot 2024-09-10 at 4 19 04 PM" src="https://github.com/user-attachments/assets/45f978ed-0d2c-4cb1-8198-9ac6fb8e8721">

**Comment by tpendragon** [comment]
We figured out today this was because we needed to fix a small bug from when we migrated ocr_language for these items. They're processing now.

**Comment by tpendragon** [comment]
Fixed!
