### ISSUE TITLE
UTF8 is whiffing on urdu script for Pakistani FIlm Posters 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6502]
### Summary

Example:  بڈھا displays fine in github and in google. However, the letters are broken in Figgy. Assuming it is a font issue.  
https://figgy.princeton.edu/catalog/9ff6fb59-aa8f-4d91-b908-727cd443a818
Screenshot below for comparative

BUT it is fine when. you see the title on the item page, and the saved information. It does not work in the big search section. it works in the box section.

## Acceptance Criteria

- [ ] When entering  بڈھا as the title in the form, it displays the last two characters as joined when zoomed all the way in. The first two also.
- [ ] Make sure it also works in Firefox.

## First Step

Compare the font CSS between where it works (in the title header on the record page) and where it doesn't.

### Impact 

_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not stopping work, but slowing it for a graduate student who travels up from philadelphia to work on the corpus  only 2 times a week. 

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks - would this be learning friendly? 
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

### Screenshots
<img width="1512" alt="Screenshot 2024-09-13 at 2 40 22 PM" src="https://github.com/user-attachments/assets/0e3b01c4-d8bf-4b56-ad67-1b36f4aef3d1">

<img width="1512" alt="Screenshot 2024-09-13 at 2 46 33 PM" src="https://github.com/user-attachments/assets/a40edce2-11d3-4fe7-b9d5-e95e91c4efe0">

<img width="1512" alt="Screenshot 2024-09-13 at 2 46 23 PM" src="https://github.com/user-attachments/assets/d052894d-57bb-42f3-a546-f5b3f77fa5c4">

**Comment by tpendragon** [comment]
The big problem here is the connecting doesn't appear in the edit form, so it's hard to tell on entry if it's right.
