### ISSUE TITLE
Delete image ingests from Host Record

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6509]
### Summary

Reported by Brianna G.  We need images for this item: https://figgy.princeton.edu/concern/scanned_resources/0e0a7d7c-558a-4e57-8c61-f4e4c89a0086/file_manager
Removed from the host record. this is a MVW and should have constituent records with nothing ingested to the host. 

We have had several of these requests. it might be time to think about Figgy ways to keep ingests like this from happening in the future. 

## Acceptance Criteria

- [x] There's a rake task that deletes all file sets directly attached to a given resource, but none of its resource members.
- [x] That task is run on this item, and it no longer has anything in the file manager view.

## First Step

Write a test.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
Not stopping work, but difficult for users to understand or find the volumes attached. 

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
This is not stopping work, but it is make it incredibly difficult to navigate or understand for the patron.

**Comment by hackartisan** [comment]
We talked about whether figgy should disallow ingests of files onto records that already have child resources on them. however, we need that functionality to support MapSet / RasterMosaics

**Comment by eliotjordan** [comment]
Complete.

@kelea99

**Comment by kelea99** [comment]
I let Brianna know in slack.
