### ISSUE TITLE
Suppressed Bib Records

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#651]
@joycebcat, two items are failing to migrate from Plum because their bib records are missing/suppressed:

* https://plum.princeton.edu/concern/multi_volume_works/pcn69nn66t (pudl0104/3936937)
* https://plum.princeton.edu/concern/scanned_resources/pk356b3174 (pudl0127/4735456)

Can you check these records to see if we can un-suppress them to let us migrate them?

**Comment by joycebcat** [comment]
OK, the first is now unsuppressed.  The second (4735456) isn't an existing Voyager record.  The correct ID should be: 10279164.  This happened with a number of the Soviet records.  I suspect somebody has been deleting and creating new records instead of updating existing record.

**Comment by escowles** [comment]
Thanks @joycebcat — I was able to migrate those records to Figgy now that we can load their metadata from Voyager.
