### ISSUE TITLE
DPUL Success Dashboard is erroring

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6515]
## Description

When querying the DPUL Success Dashboard we're getting an error.

## Acceptance Criteria

Using https://figgy.princeton.edu/reports/dpul_success_dashboard works.

## First Step

Diagnose what's causing the below error. A good first step for diagnosing this error is to make the API call using Postman, curl, or some other HTTP request client to determine if the query itself is working. Perhaps there was a change to the API, or we hit a request limit or something. 

## Sudden Priority Justification

Without the success dashboard we can't tell if our work with DPUL-C is effective. However, as this is just visualizing a current state, the priority isn't super high.

## Backtrace

    line 70 of [PROJECT_ROOT]/app/services/dpul_success_dashboard_report_generator.rb: traffic
    line 37 of [PROJECT_ROOT]/app/services/dpul_success_dashboard_report_generator.rb: daily_metrics
    line 47 of [PROJECT_ROOT]/app/views/reports/dpul_success_dashboard.html.erb: _app_views_reports_dpul_success_dashboard_html_erb__1377258794076482274_26025880

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/111455438)

**Comment by sdellis** [comment]
Somehow the password for the PLAUSIBLE_API_KEY was missing from the vault on the server. Running `playbooks/figgy_production.yml` made it all work again.
