### ISSUE TITLE
Set default rights statement to "Copyright not evaluated" for individual ingest to the repository 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#6525]
### Summary
After conversations with matthew kopel, a best practice going forward is to set our default to "copyright not evaluated" for all ingests to the repository.

Models this effects:

- [ ] ScannedResource
- [ ] ScannedMap
- [ ] VectorResource
- [ ] RasterResource
- [ ] EphemeraFolder
- [ ] Issues
- [ ] Coins
- [ ] SimpleResource

You can search for ""property :rights_statement" and get all ChangeSets - change anything that's no_known_copyright to copyright_not_evaluated.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [x] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
This is a new adopted best practice for PUL that better reflects the ingest before copyright review.

**Comment by hackartisan** [comment]
As specified this ticket excludes controlled digital lending resources which default to "in copyright" -- seems right to me.

Question: does this stay the same? https://github.com/pulibrary/figgy/blob/764809a79d5741b03995c130c517bd305ed49581/app/change_set_persisters/change_set_persister/apply_visibility_by_date.rb#L50

**Comment by tpendragon** [comment]
Answer: Yes.
