### ISSUE TITLE
Ephemera Folder form should warn when folder number has already been used within parent

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#653]
As captured during a meeting held on 12/08/17, at least a warning should be issued when duplicated Folder barcodes or numbers are entered

**Comment by tpendragon** [comment]
There's a test for this here: https://github.com/pulibrary/figgy/blob/master/spec/features/ephemera_folder_spec.rb#L92

Weird that it's not working.

**Comment by escowles** [comment]
I believe the original issue was with "Save and Create Another" — when it wasn't providing a flash message, they clicked the button several times because nothing seemed to happen.  So maybe we should consider validating uniqueness of these fields?
