### ISSUE TITLE
Resources ingested without title, or with mmsid as title

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6559]
Report from @roelmoon:

During bulk ingest, 80+ items, a group of them whiffed, even though all seems ok on the catalog and staging ends. Some went in as title only, where the MMS ID is the title and others look like they went ok, but seems like the figgy ID is the title. Here are a couple of examples:
- https://figgy.princeton.edu/catalog/abdd3c23-b452-4310-97d8-6e590f11ac31
- https://figgy.princeton.edu/catalog/57acbe50-88d2-43dd-86f8-779c0ad16b3b

I suspect this is happening because of intermittent issues with the catalog, from which figgy fetches data during resource creation. I suspect that if the catalog doesn't respond when the MMSID is validating, figgy uses the id as the title. If the catalog does respond to validate the MMSID but then isn't able to provide the data when metadata sync is requested, you have the resource created correctly but with no title (or other data provided by the catalog).

What should happen when the catalog is intermittent / unavailable?

## Initial Acceptance Criteria

 - [ ] Research ways to make it so the catalog can go down and ingests can still be reliable. Post a proposal to this ticket and get buy-in, then we'll determine if we're going to implement that as an ASAP ticket.

## Sudden priority justification
- work cannot proceed in figgy during catalog downtime
- staff time spent repairing ingest issues

## Research

When the catalog is down, one of two things happens:

Either it was down when trying to see if the bulk ingest ID is a source metadata ID, and so it treats it as a title: https://github.com/pulibrary/figgy/blob/0afeda8a094d59185fe89bd87a2322ef1a9a6d89/app/services/local_ingester.rb#L57

Or it was down when trying to get metadata, in which case it doesn't import any metadata: https://github.com/pulibrary/figgy/blob/0afeda8a094d59185fe89bd87a2322ef1a9a6d89/app/change_set_persisters/change_set_persister/apply_remote_metadata.rb#L16
https://github.com/pulibrary/figgy/blob/0afeda8a094d59185fe89bd87a2322ef1a9a6d89/app/models/remote_record.rb#L100-L109

**Comment by tpendragon** [comment]
Three questions:

1. What should happen?
2. Do we need a communication strategy?
3. ASAP Ticket?
4. How much catalog downtime should we be able to handle?

**Comment by tpendragon** [comment]
> 2\. Run a cron that fetches resources that have a source metadata id but not imported metadata and enqueues refresh remote metadata jobs

Would suppressed bibs constantly retry?

**Comment by hackartisan** [comment]
We decided to loosen the validation on catalog resources, but not try to handle the metadata sync issue for now.
