### ISSUE TITLE
Usability questions for the Ephemera Folder forms

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#656]
Two users identified some difficulty in repeatedly scrolling between the bottom and the top of the edit forms for Ephemera Folders.  @escowles identified that there was quite some empty space and that the file upload button at the bottom of this form could be hidden.  @hackmastera noted that an affixed container for the visibility might also be an improvement worthy of exploration.

**Comment by hackmastera** [comment]
file upload button is gone. Otherwise this is a dup of #1544
