### ISSUE TITLE
Get a list of all resources created in the last week that either don't have a title or have a title that starts with "99"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#6560]
## Acceptance Criteria

 - [ ] There's a list of resource IDs with their depositors that don't have a title or have a title that starts with "99"
 - [ ] list includes: resource id, depositor, title, and source metadata identifier

## Reasoning

Because of https://github.com/pulibrary/figgy/issues/6559 we have some bulk ingested resources that failed to import metadata and will need to be reingested. This will help get us the scale of those items.

## First Step

Write a script

## Sudden Priority Justification

We need to message these folks in short order - the earlier it is, the easier it is for them to reingest or adjust their materials, we should get the names as fast as possible

**Comment by hackartisan** [comment]
Here's a script:

```
query_service = Valkyrie::MetadataAdapter.find(:indexing_persister).query_service

date_range = DateTime.new(2024, 12, 3)..DateTime.now

missing_imported = query_service.custom_queries.all_mms_resources(created_at: date_range)
resources = missing_imported.select { |r| r.imported_metadata.nil? }

mms_titles = query_service.custom_queries.mms_title_resources(created_at: date_range)

resources += mms_titles

resources.map!(&:decorate)
fields = %w[id depositor title source_metadata_identifier]
csv_report = CSVReport.new(resources, fields: fields.index_by(&:to_sym))
File.write(Rails.root.join("tmp", "mms_ingest_sync_problems.csv"), csv_report.to_csv)
```
