### ISSUE TITLE
Date or date ranges should be required for Ephemera Folders

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#657]
This may have been originally featured in [pulibrary/plum](https://github.com/pulibrary/plum)

**Comment by tpendragon** [comment]
Ask if we can just have a toggle for ranges - is there ever a time they need both?

**Comment by sdellis** [comment]
And if they need both, what is the intention?

**Comment by hackmastera** [comment]
Proposal: Date is visible on the form as a required field, with a toggle for "date range". That toggle would reveal an "end" field.

Get feedback from POs on this idea.
