### ISSUE TITLE
Use Hivemind or Overmind to simplify starting up dev environment?

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#663]
Right now, one has to kick off Puma, Sidekiq, and Webpacker. 

Using one of these would simplify it:
https://evilmartians.com/chronicles/introducing-overmind-and-hivemind

**Comment by hackmastera** [comment]
@sdellis does foreman seem to fill t his need?

**Comment by sdellis** [comment]
@hackmastera I think so. This would simplify it further, and provide better logging with the foreman approach, but it seems we have not needed it. Closing...

**Comment by tpendragon** [comment]
Overmind looks real cool, but also looks like something we can just try out individually.
