### ISSUE TITLE
Provide feedback while waiting for BrowseEverything uploader

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#667]
The user doesn't get any feedback until it finishes, and may reload the page (which might interrupt the upload)

**Comment by sdellis** [comment]
I will look into at least providing a way to view BrowseEverything's list of pending uploads. At least it tell you what you selected, although there is no realtime feedback and the page must be reloaded. 

We should also keep an eye on [Uppy](https://uppy.io/) as a BrowseEverything replacement. They don't currently have a Provider for a custom fileserver, but it may not be too hard to add using the [other Provider plugins as references](https://github.com/transloadit/uppy/tree/master/src/plugins). They are happy to accept PRs as well.
