### ISSUE TITLE
MultiVolumeWork volumes shouldn't have a source_metadata_identifier field

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#671]
If the parent ScannedResource has a source_metadata_identifier, then the child should not be allowed to enter one.

**Comment by tpendragon** [comment]
Sammelbands are an exception. I think we should close this.

**Comment by escowles** [comment]
I think we can have a source_metadata_identifier either at the top level or at the volume level, but not both.  In the cases where the top level resource already has it, it would be nice to hide it at the volume level (to make it clear that you need to enter a volume label).

**Comment by hackmastera** [comment]
close in favor of #1555
