### ISSUE TITLE
Accidentally selecting subtree in BrowseEverything

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#674]
Because of the small widget for expanding a directory, users are accidentally clicking on the directory name, accidentally selecting a (potentially huge) subtree.

**Comment by hackmastera** [comment]
Our users aren't using browse everything quite as much now that we have save & ingest. Closing due to low priority.

More generally, this UI issue has been added to https://github.com/samvera/browse-everything/issues/210#issuecomment-391381165
