### ISSUE TITLE
Very wide images don't display in UV until interacted with

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#679]
Very wide images (e.g., large scrolls) don't display until you zoom in.  For example: https://figgy.princeton.edu/catalog/b0574e09-20fc-428b-ba7e-5e93f618b955

**Comment by sdellis** [comment]
I'm getting an error in production when I try to view the example, but this is probably something that the UV folks should be aware of, particularly since they're looking at faster initial rendering in the next version.

**Comment by tpendragon** [comment]
We ran into this in Plum too, I think there's a ticket there with a link to a UV issue...

**Comment by tpendragon** [comment]
Weird, can't find the issue - I know we ran into it before though, and in talking to UV folks discovered it was an OSD issue. All from memory though.

**Comment by hackmastera** [comment]
Working now.

**Comment by hackmastera** [comment]
updated example link: https://figgy.princeton.edu/catalog/4bf28a48-c09c-4a6f-a6b6-c9b710358e7f
