### ISSUE TITLE
Visibility and rights statement based on copyright year

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#691]
For the Brittle Books project, they would like to be able to create a ScannedResource with a bib number, and have the visibility and rights statement set based on the date of the resource (1923 or ealier: open/public domain, 1924 or later: private/in copyright)

**Comment by tpendragon** [comment]
Questions:

1. Do we have example records with both side of this date range?
2. Is this only for brittle books? How are they identified? A member of a collection? I assume it isn't everything because we probably don't want to auto-mark everything we have from post-1924 as private.

**Comment by escowles** [comment]
Sample records:
* pre 1924 (public domain): 4609321 and 5241365
* 1924- (in copyright): 1605804 and 1234567

This was requested by a single project, and we don't want this for everything (because there are other ways we can have rights to display things).  @roelmoon and @joycebcat can correct me, but I think we would only want this for Brittle Books.  We can create a Brittle Books collection and have that trigger this behavior.  This would probably be a good way to trigger this: a form to create a member of a specific collection could be a good place to hang this logic.

**Comment by tpendragon** [comment]
Are they all going to be in the same collection?

If so, we can key this logic off whether or not an item is in that collection.
