### ISSUE TITLE
Vue File Manager should show volumes?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#705]
Especially important for Sammelbands, where it goes File -> Volume -> Volume -> File

**Comment by sdellis** [comment]
The use cases this needs to support will play into the design decisions. One decision is whether or not to "collapse" all volumes into a single item, and have a separate filemanager to make changes to the volume. 

Is the primary use case to reorder Sammelband members? In other words, to easily make the example above into Volume -> File -> File -> Volume? Or is it to relabel all filesets across the entire MVW in a single interface? 

I think it would be good to talk to someone who has the task of cataloging MVW's in their typical workflow. Kim and David work with MVW's, correct?

**Comment by tpendragon** [comment]
We've never promised the ability to relabel all filesets across the entire MVW in a single interface. Historically it's just been to re-order the covers in relation to new volumes added to a Sammelband, or to re-order volumes in a MVW.

I'm not sure who you'd ask - original use cases for this came from Joyce and @jpstroop

**Comment by sdellis** [comment]
I'm trying to create a sample MVW or Sammelband to develop with, but it's not intuitive. Do I need to create multiple works and then create a collection to group them?

**Comment by tpendragon** [comment]
When you make a scanned resource, the bottom right corner has "Attach Child", click that, fill out the form, and that'll make a volume.

**Comment by sdellis** [comment]
So, when am editing resources with the Vue Filemanager, I PATCH the changes to two different endpoints: 

1. `/concern/file_sets/{id}` for each relabeled fileset
2. `/concern/{pluralized_resource_type}/{id} for the resource

I assume we will still use #2 for each of the relabeled and rearranged volumes in MVW. But what do we use for the collection PATCH endpoint? And are these the fields I should be sending to the collection endpoint: `member_ids, thumbnail_id, viewing_direction, id`?

Finally, I just want to document here that Sammelbands won't be arrange-able by volume. They are essentially treated as a single-volume work, although there may be logical structure that makes them imitate MVWs.

As a side note, it looks like a user can edit the files for each volume by clicking "View" (but not "Edit") next to the work. Seems like a weird flow, but perhaps that's a separate issue.

**Comment by tpendragon** [comment]
The volume end point (please avoid collection as the word here - there's a Plum collection and a IIIF collection and they're not 1-1) would be `/concern/scanned_resources/{id}`. We might be able to store that as a seeAlso or something similar on the manifest. Although, it strikes me that we don't actually update anything for volumes in the current version - it's just there so it can be reordered, which is a property of the resource.

I don't think you have to send anything to the volume end point. It might be a nice improvement to allow them to edit the `title` of volumes though.

We need a way to make Sammelbands work at some point - it may be that we'll have to initialize the file manager with something other than the IIIF manifest. :(

**Comment by tpendragon** [comment]
Sammelbands work if you ingest them right the first time. The structure editor allows you to build structure -around- your volumes, but it doesn't let you re-order.

**Comment by tpendragon** [comment]
Remember we only have like, what, 11 of them? I liked how it works in the old file manager - create children like it's a MVW and then just upload the front/back covers if you need.

**Comment by sdellis** [comment]
The ideal workflow would be that one could select a number of FileSets and group them as Volumes using the filemanager, probably with an "expand/collapse" GUI to show or hide the FileSet thumbs within a volume. Then one could rearrange both FileSets and Volumes in the same pane.

**Comment by tpendragon** [comment]
I'm not sure I'd consider that my ideal workflow. The imaging studio's ideal workflow is they organize the volumes into folders and just hit "Save and Ingest," which would mean the grouping FileSets feature would never get used.

**Comment by sdellis** [comment]
As you said earlier, the studio's ideal workflow is great if the initial ingest is correct the first time (and there's no reason to abandon this for initial ingests). It becomes less than ideal when the initial ingest is not correct (missing image, image in wrong volume, out of order, etc), which is where my proposal comes in.  It would be nice to have a single UI for which to correct those kinds of problems -- yes there is a solution for most of those, but they are not ideal.  I also think that the "grouping Filesets" feature could be used to allow for structural/logical editing.

**Comment by sdellis** [comment]
At any rate, for now, I'm just mimicking the old filemanager to fulfill this issue. We should probably move the Sammelband support discussion into a separate issue.

**Comment by sdellis** [comment]
ViewingDirection is not an option for Collections (and thus, MVW) until IIIF Prezi 3.0. And it may require updates to the resource class on the back end. Front-end would be easy to add, but do we want to? Our gemified version of UV will currently ignore it.

**Comment by tpendragon** [comment]
Shouldn't require updates to the back end (since it's a ScannedResource either way.) Whatever's less work seems fine. I think RTL is mostly important for Sammelbands.
