### ISSUE TITLE
Don't index FileSets

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#720]
Would make re-indexing WAY faster.

Update  views to be used from the proper fileset route instead of the catalog route. Views there for regenerating derivatives would have to be moved. In some cases we may need to pull views from blacklight (or just rewrite them).

Update the indexing persister to not persist file sets to solr. This would be a custom MetadataAdapter inheriting from the solr metadata adapter: it would no-op for file sets and otherwise call super.

**Comment by escowles** [comment]
We need to index FileSets for IIIF search now.
