### ISSUE TITLE
Can't complete items which have a non-ark identifier.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#728]
Should we check to make sure something looks ark-y when we go to mint an ark?

**Comment by tpendragon** [comment]
This is an issue for EAL items that never made it into PUDL, like:

https://plum.princeton.edu/concern/multi_volume_works/pzw131p108

**Comment by escowles** [comment]
I think there are three issues here:
1. The records shouldn't have UUIDs and other non-ARK things in `identifier` (this is probably simple data cleanup)
2. We shouldn't try to update the metadata for things in `identifier` that aren't ARKs (checking to make sure they look like ARKs seems reasonable)
3. When we get an error from Ezid, we might want to do something better than "Something went wrong"

**Comment by tpendragon** [comment]
Cleaned up records.

2 should never happen again since we're not importing identifiers and you can't enter that data.

3 is probably true, but what do we say? Do we....add a validation error?

**Comment by hackmastera** [comment]
moving the part that's not done to #1563
