### ISSUE TITLE
Ephemera JSON-LD includes "plum.princeton.edu"

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#732]
it's the vocabulary id. example: https://figgy.princeton.edu/catalog/9bc36231-ec20-4176-ace5-26eb88bdbb89.jsonld

It should just be the jsonld link for the vocabulary (i.e. just the figgy uri)

**Comment by eliotjordan** [comment]
This should be fixed now. Close?

**Comment by escowles** [comment]
Yep, those are now Figgy URLs
