### ISSUE TITLE
UV should show the index tab by default

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#734]
Is there any way to make UV show the index tab by default, if it's present?  This was requested for the Table of Contents project, but it seems reasonable for all MVWs, where navigating between the volumes is not obvious until you can see the index tab.

**Comment by sdellis** [comment]
Yes, this is configurable: 
https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/config/en-GB.json#L64

**Comment by sdellis** [comment]
A little more on the specifics of how to do this... 

We would need to add the `data-config` attribute to the div we use to mount the UV when embedding, and point it to the correct config for MVW:
```
<div class="uv" data-config="/config.json" data-uri="http://example.org/iiif/b18035723/manifest"></div>
```

```
// config.json
    {
        "modules":
        {
            "contentLeftPanel":
            {
                "options":
                {
                    "defaultToTreeEnabled": true
                }
            }
        }
    }
```
