### ISSUE TITLE
File manager link to resource does not include MVW context

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#736]
When I am in the file manager for a MVW volume, the breadcrumbs do not contain a link for the MVW.  If I click the link for the volume show page, it does not have the MVW context, either.

**Comment by sdellis** [comment]
Is it possible for a volume to be the child of multiple parents, or is the relationship one to one?

**Comment by tpendragon** [comment]
Theoretically possible, but there's no UI to do it - or use case, atm.
