### ISSUE TITLE
Editing/Deleting a FileSet should take you to the show page for its parent Resource

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#746]
Currently, deleting a fileset takes the user all the way back to the home screen. 

You can get to a fileset from the order manager or the file manager, so the user should be taken back to the resource show page after the edit/delete is made.

**Comment by hackmastera** [comment]
Can't you delete a fileset from the fileset show page? Or do we no longer allow that route?

**Comment by tpendragon** [comment]
That's actually where the delete happens - the button in the file manager just redirects to the show page.

**Comment by hackmastera** [comment]
I see, but there's not a link to the show page anywhere else in the site? this makes sense then.

**Comment by tpendragon** [comment]
Might be fixed. Investigate.
