### ISSUE TITLE
LAE: viewer metadata drawer has field labels but no values

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#756]

**Comment by jrgriffiniii** [comment]
This is likely related to issues arising from indexing improperly serialized `EphemeraTerms`.  Please see the following for an example:
https://lae-staging.princeton.edu/catalog/4710f460-7bf6-4a5d-ba32-774ea92cdcf4.jsonld

**Comment by jrgriffiniii** [comment]
I believe that Documents within `lae` might simply need to be reindexed at this point (please see https://figgy.princeton.edu/concern/ephemera_folders/4710f460-7bf6-4a5d-ba32-774ea92cdcf4/manifest and https://lae-staging.princeton.edu/catalog/4710f460-7bf6-4a5d-ba32-774ea92cdcf4.jsonld)
