### ISSUE TITLE
Ephemera: do not require barcode, folder number, height or width for boxless items

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#759]
This is probably a question for a larger group thinking about all the ephemera projects:
* which fields should be required for initial record creation?
* are these the same for all projects?
* maybe a minimal required set for initial record creation, then (configurable?) validation step afterwards?

**Comment by escowles** [comment]
Decision: boxless items should not require barcode, folder number, height or width — other fields should remain required.

**Comment by hackmastera** [comment]
Assuming "item" means "ephemera folder"

**Comment by escowles** [comment]
@hackmastera Yes, "boxless items" should be "ephemera folders attached directly to ephemera projects"
