### ISSUE TITLE
Unable to delete EAL record

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#770]
Trying to delete this record causes a server error:

https://figgy.princeton.edu/catalog/cf534eb1-2840-45a4-ab78-e5976045911d

**Comment by tpendragon** [comment]
https://app.honeybadger.io/projects/53391/faults/36237376#notice-trace Probably a result of compacting structure again.

**Comment by escowles** [comment]
Maybe we should explicitly delete the blank created/updated keys, instead of using `compact`?

**Comment by tpendragon** [comment]
We just need some better tests in there I think. Compact should work.

**Comment by tpendragon** [comment]
In the meantime, maybe we revert that commit? Slower is better if it works.

**Comment by escowles** [comment]
Yeah, reverting the commit for now is probably the right thing to do.

**Comment by tpendragon** [comment]
Github says it can't auto-revert. :( I'll have to look at it in a bit.

**Comment by tpendragon** [comment]
https://github.com/pulibrary/figgy/pull/772
