### ISSUE TITLE
Move Characterize to after_save_commit

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#773]
`after_commit` runs on save and delete. @jrgriffiniii is there a reason we needed to `Characterize` on delete? https://github.com/pulibrary/figgy/blob/master/app/change_set_persisters/plum_change_set_persister.rb#L40

**Comment by jrgriffiniii** [comment]
I don't believe so - from what I recall there was an intention was to avoid invoking `after_commit` after deletion (and instead run only `after_delete_commit`).
