### ISSUE TITLE
Thumbnail not displaying for multi-volume work in search results

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#781]
When a MVW is retrieved in the search results, a thumbnail is not displaying for the item, e.g., 

https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=+%E7%89%A7%E6%84%9B%E5%A0%82%E7%B7%A8

**Comment by jrgriffiniii** [comment]
Attempting to reproduce this, I've found that there are cases where it is indeed displayed:
https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=+%E5%8F%A4%E4%BB%8A%E8%A9%A9%E9%9F%BB%E9%87%8B%E7%BE%A9+

**Comment by escowles** [comment]
@jrgriffiniii Yes, most of them are being displayed, but some MVWs are not.  Just listing MVWs, I see most of them have thumbnails displaying, but there are many that do not:

https://figgy.princeton.edu/?f%5Bhuman_readable_type_ssim%5D%5B%5D=Multi+Volume+Work&per_page=50&q=

**Comment by jrgriffiniii** [comment]
Understood, I believe that this relates somehow to the indexing of MVW's:
https://figgy.princeton.edu/catalog/a4e3a31a-e4f0-47ce-a4cb-2f1d604dcad4.json
 has the ID for the thumbnail indexed in `thumbnail_id_tesim` (and appears in https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=+%E5%8F%A4%E4%BB%8A%E8%A9%A9%E9%9F%BB%E9%87%8B%E7%BE%A9+) while https://figgy.princeton.edu/catalog/dc2e59fb-ff84-4d82-9af0-f2ffd8ebdf57.json does not feature that field at all (which is found in https://figgy.princeton.edu/catalog?utf8=%E2%9C%93&q=+%E7%89%A7%E6%84%9B%E5%A0%82%E7%B7%A8).
