### ISSUE TITLE
Embargoes

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#782]
We have a collection that needs to be embargoed for years.  We should be able to ingest them with an embargo instead of marking them private (or managing them outside of the repo until the embargo expires).

**Comment by tpendragon** [comment]
@escowles Which collection is it that needs embargo'd?

**Comment by escowles** [comment]
The ACLU (MC001) files have been digitized but have a 5 year embargo.  I think the embargo expiration should trigger a notification to the collection owner to review the materials and confirm they can be public.

**Comment by tpendragon** [comment]
@escowles Do we still have this use case? Should we just close this until it comes up for a collection we need to ingest?

**Comment by escowles** [comment]
We do still have this situation — I thought we had ingested all of the ACLU files as private because we didn't have an embargo, but I don't see most of them in Figgy right now. So we may have deleted them or never ingested them because of this.

But bulk ingest would let us make them public when the embargo expires, and there are other ways to keep track of when that is, so I think this can be iceboxed until we have a use case that requires automatic embargo expiration.
