### ISSUE TITLE
Metadata drawer is showing non-useful metadata

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#784]
It's displaying things like "depositor" and "created/updated at" which aren't useful to show in the metadata drawer.

Good place to start looking: https://github.com/pulibrary/figgy/blob/0d48fd38e14fbced210a2c2e7f75f152b7012ead/app/decorators/valkyrie/resource_decorator.rb#L85

**Comment by escowles** [comment]
Here is some feedback on which fields we should display from one of our Cicognara partners (Alexandra Buettner):

[manifest-metadata.docx](https://github.com/pulibrary/figgy/files/2185053/manifest-metadata.docx)
