### ISSUE TITLE
Add scanner information field to scanned maps

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#786]
Eliot can find default text. Should this be in the work metadata or on the file set? File set seems logical, but scanned map seems easiest.

**Comment by hackmastera** [comment]
we'll have new file metadata fields for a/v, too. any reason we shouldn't just add all this to the generic FileMetadata object?

**Comment by tpendragon** [comment]
What's "scanner information" and how is it discovered? Part of characterization that's in the file header?

**Comment by eliotjordan** [comment]
It's information about the machine used to scan the particular map and the software used to process the image. As far as I know, it isn't available in the header. Here's the boiler plate that Wangyal wants (at least until they get another scanner):

```
This map was scanned with an HD Ultra i4290s scanner and Nextimage 4.5.2 software at 400 DPI in 256 colors, and georeferenced using ArcGIS 10.2 software.
```

**Comment by escowles** [comment]
We could get most of that from the JHove output.

**Comment by tpendragon** [comment]
Oh, I dunno where I'd store that. FileMetadata I guess? It's weird.

**Comment by tpendragon** [comment]
If we look at it from a use case perspective rather than a data purity perspective, I guess it doesn't matter where we store it. Is there a case where a map will have two FileSets, each scanned differently? If not, probably easiest to just put it on SR.

**Comment by eliotjordan** [comment]
Yeah. This is a weird request, and was a blocker for getting this workflow into production before we got sidelined by other things last year. I'd guess that there is 99.999% chance that multiple maps are scanned at the same time on the same machine.

**Comment by eliotjordan** [comment]
Running `exiv2 -pv` on a map tiff returns:

```
0x00fe Image        NewSubfileType              Long        1  0
0x00ff Image        SubfileType                 Short       1  1
0x0100 Image        ImageWidth                  Short       1  2917
0x0101 Image        ImageLength                 Short       1  3558
0x0102 Image        BitsPerSample               Short       1  8
0x0103 Image        Compression                 Short       1  1
0x0106 Image        PhotometricInterpretation   Short       1  3
0x0107 Image        Thresholding                Short       1  1
0x010a Image        FillOrder                   Short       1  1
0x0111 Image        StripOffsets                Long        7  1818 1495322 2988826 4482330 5975834 7469338 8962842
0x0112 Image        Orientation                 Short       1  1
0x0115 Image        SamplesPerPixel             Short       1  1
0x0116 Image        RowsPerStrip                Long        1  512
0x0117 Image        StripByteCounts             Long        7  1493504 1493504 1493504 1493504 1493504 1493504 1417662
0x011a Image        XResolution                 Rational    1  400/1
0x011b Image        YResolution                 Rational    1  400/1
0x011c Image        PlanarConfiguration         Short       1  1
0x0128 Image        ResolutionUnit              Short       1  2
0x0140 Image        ColorMap                    Short     768  50688 52736...
```

Missing the scanner model and processing software version.

**Comment by escowles** [comment]
FWIW, this was standard practice at UCSD — every image in the DAMS had scanner hardware, scanning software, etc., etc. recorded using a local RDF vocab based on [MIX](http://www.loc.gov/standards/mix/)

**Comment by hackmastera** [comment]
it seems like file metadata to me, except for the way it's worded as a complete sentence.

**Comment by eliotjordan** [comment]
Here's a proposal.

Let's add `tiff:BitsPerSample`, `tiff:XResolution`, and `tiff:YResolution` to the default file metadata in the tika characterization service.

https://github.com/pulibrary/figgy/blob/master/app/characterization_services/tika_file_characterization_service.rb#L25-L29

And then ask the map lab to add `ScannerModel`, `ScanningSystemSoftware`, and/or `ProcessingSoftware` tags to their TIFFs. If those are found by tika, they can be added to the file metadata in the same way. This absolves us of having to keep track of what scanning equipment they're currently using.

**Comment by escowles** [comment]
@eliotjordan Though we're currently using https://github.com/pulibrary/figgy/blob/master/app/characterization_services/imagemagick_characterization_service.rb — so we'll need to make sure that we use the Tika characterization (either instead of ImageMagick or as a second pass) for these files.

**Comment by eliotjordan** [comment]
The `GeoCharacterizationService` uses Tika still (ImageMagick characterization is a bit newer I guess). I assume that it's alright to leave that as is.

**Comment by escowles** [comment]
Oh, my mistake @eliotjordan — improving the Tika characterization service to extract those additional fields sounds like a good way to go.
