### ISSUE TITLE
Bad File

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#800]
The TIFF in this FileSet is broken (maybe truncated — the top part displays and then it's cutoff): https://figgy.princeton.edu/catalog/af39f7bf-2a68-47fc-a30d-9a833f0a779f

Can we track down the original file to see if we can simply replace this file?

**Comment by tpendragon** [comment]
This file's bad on the PUDL share. Might need to re-scan unless it's somewhere else? @jpstroop @rmunoz?

**Comment by tpendragon** [comment]
Roel's going to get the book picked up and that page re-shot.

**Comment by tpendragon** [comment]
Roel fixed it.
