### ISSUE TITLE
CR2 files at end of item

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#802]
There are 8 CR2 files at the end of this item:

https://figgy.princeton.edu/catalog/d0b94043-3a44-44e1-9f20-ce1fad8b5715

* If these are duplicates of the TIFFs, delete them
* If they are different pages, then convert them to TIFFs and add them (or ask the studio to do so)

**Comment by tpendragon** [comment]
These are side-on shots of the book it looks like. Roel says his team can convert them to tiffs for us.

**Comment by tpendragon** [comment]
Fixed.
