### ISSUE TITLE
Identifier pulled in from bibdata jsonld is wrong

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#824]
This is an issue in bibdata that manifests in figgy. The `identifier` property in the JSON-LD returns the catalog url instead of the ARK url.

Example bib: 2086336

![screenshot 2018-02-16 11 01 34](https://user-images.githubusercontent.com/784196/36319681-49909e7c-1309-11e8-9e9f-8325477c11ad.png)

See: https://github.com/pulibrary/marc_liberation/issues/365

**Comment by jrgriffiniii** [comment]
This seems to be fully resolved from within my local development environment using https://github.com/pulibrary/marc_liberation/pull/366
![figgy_824_screenshot_0](https://user-images.githubusercontent.com/1443986/36389500-38c3815c-156d-11e8-812a-75d42186a5f6.png)
![figgy_824_screenshot_1](https://user-images.githubusercontent.com/1443986/36389507-3b1fd216-156d-11e8-94ff-1d53b8998cc0.png)

**Comment by eliotjordan** [comment]
Closed by https://github.com/pulibrary/marc_liberation/pull/366
