### ISSUE TITLE
Access control for digitized audio/video

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#832]
Are Figgy's access controls good enough for items where we need to limit access because of copyright?  We've talked about encrypting or storing some items offline, but mostly for cases like student records where there were liability and confidentiality concerns.

**Comment by tpendragon** [comment]
@escowles @hackmastera My understanding is that the answer for this is "yes". Confirm?

**Comment by escowles** [comment]
Yes, I haven't heard any of our users asking for more stringent access controls.

**Comment by hackmastera** [comment]
Yes, let's wait until we have a request/use case for finer distinctions
