### ISSUE TITLE
MapSets that failed to import from Plum

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#853]
- "pqn59ss173"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817404 not found or suppressed'
- "pdv142h163"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6819878 not found or suppressed'
- "pqv33vm08n"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6830998 not found or suppressed'

**Comment by tpendragon** [comment]
@eliotjordan Still busted?

**Comment by eliotjordan** [comment]
Yes. Still busted. I can remind the people that can fix these about it.

**Comment by escowles** [comment]
Any update on these @eliotjordan ?

**Comment by eliotjordan** [comment]
Still no movement. I'll try reminding the map lab again, and gather the images into a directory like https://github.com/pulibrary/figgy/issues/854 .

**Comment by tpendragon** [comment]
@eliotjordan Bi-yearly check-in: Still busted?

**Comment by eliotjordan** [comment]
I'm gonna close this. No one seems to care.
