### ISSUE TITLE
Scanned Maps that failed to import from Plum

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#854]
- "pdr271d11z"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6819953 not found or suppressed'
- "p5425nr70r"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817777 not found or suppressed'
- "pv118tz74x"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831007 not found or suppressed'
- "ph128qw75k"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817699 not found or suppressed'
- "p8k71r030h"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817707 not found or suppressed'
- "pxk81n1237"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817778 not found or suppressed'
- "psx61h3508"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831008 not found or suppressed'
- "p7h14d6098"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831406 not found or suppressed'
- "pwd378c10x"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817776 not found or suppressed'
- "pc247h838r"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817782 not found or suppressed'
- "ph128qw893"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6839764 not found or suppressed'
- "pw3765p28p"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817781 not found or suppressed'
- "pqz20w6524"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6843004 not found or suppressed'
- "pxk81n125v"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817773 not found or suppressed'
- "p0p098q97p"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817095 not found or suppressed'
- "ptt44s335x"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817406 not found or suppressed'
- "pw6636k82m"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831982 not found or suppressed'
- "pq237m697s"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831193 not found or suppressed'
- "ptm70q9577"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817706 not found or suppressed'
- "pzk51xx586"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6514376 not found or suppressed'
- "pbr86dk95d"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6820783 not found or suppressed'
- "png454099z"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817710 not found or suppressed'
- "p6q1852379"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6819491 not found or suppressed'
- "pvx023x783"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817709 not found or suppressed'
- "p6t055x478"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6840870 not found or suppressed'

- "p1z40p931n"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831002 not found or suppressed'
- "p0k227s29d"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817780 not found or suppressed'
- "p6h4437704"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6820794 not found or suppressed'
- "pm900rc48n"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817805 not found or suppressed'
- "p2801rz229"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817620 not found or suppressed'
- "pnc583304s"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817708 not found or suppressed'
- "pjs958x32w"
Errno::ENOENT: No such file or directory @ rb_file_s_link - (/mnt/diglibdata/hydra_binaries/p7/w6/2h/q0/p7w62hq04f/pn89d821d.tif, /opt/repository/files/69/d3/cd/69d3cdd616f84bcf890501711e362e6c/pn89d82...
- "pkp78jw57d"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6841706 not found or suppressed'
- "pnv937k400"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831194 not found or suppressed'
- "p8s45ss47m"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817797 not found or suppressed'
- "pdb78wt283"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831961 not found or suppressed'
- "pfj238j053"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831011 not found or suppressed'
- "pnk324x63f"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817398 not found or suppressed'
- "pb8518590d"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6816888 not found or suppressed'
- "p5d86rg23t"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817771 not found or suppressed'
- "pkd17g9544"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817770 not found or suppressed'
- "p2514r268b"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817774 not found or suppressed'
- "pv405vr525"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831014 not found or suppressed'
- "p4742cr928"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817403 not found or suppressed'
- "pjs958x828"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6840872 not found or suppressed'
- "pjm2175504"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831006 not found or suppressed'
- "pxk81n0750"
  - MultiJson::ParseError: 765: unexpected token at 'Record 9823520 not found or suppressed'
- "p7940bd397"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6840871 not found or suppressed'
- "pzc77w609j"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6865515 not found or suppressed'
- "pfj238h84r"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6514416 not found or suppressed'

- "pw3765p36b"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6865521 not found or suppressed'
- "pf1884346p"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6820781 not found or suppressed'
- "pr781zz963"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6839748 not found or suppressed'
- "p2r36xf495"
  - MultiJson::ParseError: 765: unexpected token at 'Record 8256685 not found or suppressed'
- "p70797q07c"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6842537 not found or suppressed'
- "p6m314556t"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6820770 not found or suppressed'
- "pwd378b77h"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6843252 not found or suppressed'
- "p4q77j7646"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6831947 not found or suppressed'
- "pfj238h92d"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817397 not found or suppressed'
- "ppv63jd66q"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6819881 not found or suppressed'
- "p4m90h980j"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817405 not found or suppressed'
- "prr174d114"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6819885 not found or suppressed'
- "p8k71r040s"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6821711 not found or suppressed'
- "psx61h349s"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6830597 not found or suppressed'
- "p0v83bf373"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817723 not found or suppressed'
- "pkw52mq26s"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6846388 not found or suppressed'
- "pzk51xx497"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6819514 not found or suppressed'
- "pbk12bs349"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817400 not found or suppressed'
- "ptt44s3395"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817399 not found or suppressed'
- "p0k227s30w"
  - MultiJson::ParseError: 765: unexpected token at 'Record 6817772 not found or suppressed'

**Comment by tpendragon** [comment]
@eliotjordan Still busted?

**Comment by eliotjordan** [comment]
A check of a sample of records tells me that they are still busted.

**Comment by escowles** [comment]
Any update on these @eliotjordan ?

**Comment by eliotjordan** [comment]
Yes these are still not ingested and the bib ids are incorrect. I can put together a folder of the images with their titles and ARKs for Berta.

**Comment by eliotjordan** [comment]
There is no movement on this ticket. So I'm going to close.
