### ISSUE TITLE
Add lossless JP2 recipe?

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#860]
Should we add the ability to select a lossless JP2 recipe, similar to how we allow different PDF quality settings?

@roelmoon says these changes to our existing recipe would be needed for lossless:
> For lossless JP2, change rate to:
>-rate -,2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171
>
> And add:
>Creversible=yes

**Comment by roelmoon** [comment]
There are a couple of engraving projects from Julie's collection in PUDL that had to be processed in lossless. Even with very mild compression the engraving details got crushed.

**Comment by tpendragon** [comment]
Related to #1540

**Comment by tpendragon** [comment]
Closed as dup of #1540
