### ISSUE TITLE
Route iiif/lookup/ark:/ should return a 403 status code for cases where resources exist but are access restricted

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#875]
Please attempt to access https://figgy.princeton.edu/iiif/lookup/ark:/88435/qb98mj372 as an unauthenticated and authenticated administrative user.

**Comment by tpendragon** [comment]
It's important that this returns 403 and not 404?

**Comment by jrgriffiniii** [comment]
The potential importance stems from a discussion regarding how best to resolve https://github.com/pulibrary/orangelight/issues/1201...one approach discussed was the usage of this route to either:
- Retrieve a IIIF Manifest for a resource being indexed in Orangelight
- Handle resources in Orangelight which have manifests but are access-restricted in Figgy
- Handle cases where the resources simply aren't in Figgy

How this relates to https://github.com/pulibrary/orangelight/issues/1201 is that, for cases where the resource doesn't exist in Figgy but has an ARK, the Orangelight Show template renders the ARK as a link (trivial).  For cases where the resource is in Figgy but is access-restricted, the ARK is not rendered on the template at all (users can't view images of this item, but they can view its catalog page here).

**Comment by escowles** [comment]
Closing in favor of https://github.com/pulibrary/orangelight/issues/1211
