### ISSUE TITLE
Set up a place to write bags to

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#912]
Child of #1876

Create the mechanism and configuration needed to Bag up an object and write it to preservation storage.

Document how the bucket is created and how to access it.

The key file for access should be added to ansible and set up as an environment variable appropriately.

**Comment by tpendragon** [comment]
Child of #1551

**Comment by tpendragon** [comment]
We haven't decided on a strategy for this yet, so we're closing this as premature.

**Comment by escowles** [comment]
I think this should be directly to cloud storage, if possible.
