### ISSUE TITLE
Don't retry on `Valkyrie::Persistence::ObjectNotFoundError`?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#918]
Seems like since we've figured out the transaction business that these jobs never succeed - it's usually because the relevant object has been deleted since the job was queued up.

**Comment by hackmastera** [comment]
I'm seeing these on object creation, coming from the characterization job. I wouldn't want to not retry on them.

**Comment by tpendragon** [comment]
We've fixed most of these to stop honeybadger errors. Closing this and we can just respond to honeybadger.
