### ISSUE TITLE
Vue-flash component blocks user clicks in Filemanager

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#920]
I figured out why the range input was not working, along with the inability to select thumbnails sometimes. I'm using a component called vue-flash for alert messaging and the wrapper for the flash stays invisible on the screen and prevents mouse clicks. I have an open ticket for this (see below), but I would not have to use this if I could trigger Rails flash messaging via a Javascript event. This would also be more consistent with our current user messaging approach. Rails folks, is this possible?

Outstanding ticket for vue-flash:
https://github.com/andyleach/vue-flash/issues/16

**Comment by tpendragon** [comment]
"Rails Flash Messages" are just a server-side session that gets sent and flushed on the next request. If you just want the flash area to get populated when you fire a javascript event, that seems like some pretty straight forward javascript.

**Comment by rlskoeser** [comment]
This is impacting CDH work on labeling Derrida materials - we need an option to view the thumbnails at a larger size to label them properly.
