### ISSUE TITLE
Add a documentation cop to PR process

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#921]
It would be great to get into the practice of including class-level and method-level docs. especially param / return types and see references to related code.

**Comment by tpendragon** [comment]
Does Rubocop have something like this? I know things like `inch-CI` exist, but they purposefully take a grading stance to things because it's hard to tell if you really -should- document a thing.

**Comment by tpendragon** [comment]
This is the documentation cop: https://rubocop.readthedocs.io/en/latest/cops_style/#styledocumentation
