### ISSUE TITLE
Unicode/UTF-8 characters are lost in manifest

### ISSUE THREAD

**Issue by sdellis** [pulibrary/figgy#928]
See:
https://figgy.princeton.edu/concern/scanned_resources/fb1f4cf0-9acb-4c3e-a32e-c2380b11b7ad/manifest

And:
https://catalog.princeton.edu/catalog/4843238#view

**Comment by escowles** [comment]
I'm not seeing any issues with Unicode characters (using Firefox with the JSON Lite extension (https://github.com/lauriro/json-lite).

**Comment by tpendragon** [comment]
They look broken to me.

**Comment by tpendragon** [comment]
Ugh this is really frustrating. So the problem is a font issue with Chrome on Mac OSX. I can't seem to get the UV iframe to load any fonts that support the cyrillic, except for Arial Unicode MS which is really, really, really hideous.

**Comment by tpendragon** [comment]
I give up. To get this to work we'll have to get Dejavu Sans as part of the theme in UV.

**Comment by tpendragon** [comment]
Only other info I could pull up: Apparently that's the ALA-LC Romanization of Cyrillic, so a bunch of cyrillic fonts don't support it.
