### ISSUE TITLE
PDF Images are getting squished when they should be landscape

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#938]
https://figgy.princeton.edu/downloads/f8bb91e3-b577-49f1-9e0c-79a209b6d53e/file/e06e1b6b-bc4e-460a-afae-7bee88ab6d65

**Comment by jrgriffiniii** [comment]
The original resource appears to no longer resolve, however the following appears to exhibit the referenced problems: https://figgy.princeton.edu/downloads/261328f1-8128-4d1b-8618-9f0e44074745/file/38ec7b28-59f0-4cea-9288-234305aa26df
