### ISSUE TITLE
Create static pages for service Privacy Policy and Terms of Service agreement

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#941]
These are encouraged for services which integrate with the Google Drive API (https://developers.google.com/drive/?hl=en_US)

Please see the following criteria for verifying a service integrated with Google API's:
- https://support.google.com/accounts/answer/7455163?p=app_notverified&visit_id=1-636573409598171649-2612818503&rd=1#notverified
- https://support.google.com/cloud/answer/7454865

**Comment by escowles** [comment]
This can probably be a short paragraph explaining that Figgy is a staff tool for PUL staff, and linking to Princeton's policies: https://itpolicy.princeton.edu/

**Comment by escowles** [comment]
Lower priority now that Google has authorized Figgy again, and no privacy policy is forthcoming from campus.

**Comment by tpendragon** [comment]
@escowles Is this still forthcoming or should we just close this?

**Comment by escowles** [comment]
Yes, I think we can just close this. There is a separate effort to post a takedown policy and form, and link to it from the viewer, so I think that will wind up addressing some of this anyway.
