### ISSUE TITLE
Include PUL logo in manifests

### ISSUE THREAD

**Issue by rlskoeser** [pulibrary/figgy#942]

**Comment by hackmastera** [comment]
Pretty sure someone said we did this in plum, so I will look there for hints.

**Comment by hackmastera** [comment]
@escowles do you want the cicognara logo option as well, keyed off the rights statement as is done in plum? https://github.com/pulibrary/plum/blob/master/app/services/manifest_builder/logo_builder.rb#L17

**Comment by hackmastera** [comment]
@escowles if so, let's create another issue since I just made a PR against this one.

**Comment by escowles** [comment]
@hackmastera I created #957 for the Cicognara logo, so I'm closing this one now that #953 is merged.
