### ISSUE TITLE
EAL ToC images look terrible at small resolution

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#943]
See https://figgy.princeton.edu/catalog/b51a47ce-b699-4b5e-8bff-57fb64255d34

The EAL ToC images were converted from PDFs containing black-and-white (not grayscale) images.  At full resolution the look OK, but at smaller resolution, they look like blank pages.

Investigate pre-processing the TIFFs, adjusting the Kakadu settings, etc. to see if we can improve the low-resolution images.

**Comment by escowles** [comment]
Source images converted to grayscale are in `//diglibdata/pudl/ealtoc` and the original source images are in `//diglibdata/pudl/ealtoc/raw`

**Comment by jrgriffiniii** [comment]
This issue was found to be problematic by another user on 04/15/19, I will also make an attempt to improve the quality of these.

**Comment by tventimi** [comment]
I should add that the case I reported

https://figgy.princeton.edu/catalog/368acc16-f95b-4741-8f7b-ed9edfaafadd

Is not a scan, but was directly generated from an Excel spreadsheet.

**Comment by jrgriffiniii** [comment]
Arbitrarily increasing the resolution for a small subset of the affected images on Cantaloupe seems promising, but the threshold must be inferred before a solution can be offered.

**Comment by jrgriffiniii** [comment]
Increasing the resolution of the images used for PDF document generation may be one solution to attempt, and does not seem to adversely affect the aspect ratio for pages in documents in the PDF.

**Comment by tpendragon** [comment]
We turned down the resolution quite some time ago to decrease the size of PDFs. Just something to keep in mind.

**Comment by jrgriffiniii** [comment]
After discussing this with escowles, it was proposed that different strategies for converting the derivatives for EAL ToC resources should be attempted, one being the generation of grayscale thumbnail derivatives and blurring of the original files during this process.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/figgy/compare/issues-943-jrgriffiniii-eal-toc-derivatives advances this by trying to implement an alternative `ImageDerivativeService` which chains derivative generation using Class methods as callbacks.

**Comment by tventimi** [comment]
The example given before

https://figgy.princeton.edu/catalog/368acc16-f95b-4741-8f7b-ed9edfaafadd

Looks a lot better, as do many other EAL TOCs when displayed at the initial resolution in UV.  Thanks for your work on this.
