### ISSUE TITLE
Existing derivatives are not removed when regenerating derivatives

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#979]
Need to create a RegenerateDerivativesJob to cleanup then generate new derivatives.

![screenshot 2018-03-29 11 50 14](https://user-images.githubusercontent.com/784196/38102019-91eb49ca-3347-11e8-8943-cca0b91d8327.png)
![screenshot 2018-03-29 11 50 25](https://user-images.githubusercontent.com/784196/38102020-91fe1154-3347-11e8-81ee-b19cb7ab9c3c.png)

**Comment by tpendragon** [comment]
Was fixed a while ago.
