### ISSUE TITLE
Don't include ActionDispatch::TestProcess globally

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#995]
Honeybadger says it's a bad idea, and it causes a warning when running tests.

https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/notice.rb#L521

**Comment by hackmastera** [comment]
we've messed with this before; maybe the notes here will be helpful to the next person who tries: https://github.com/pulibrary/figgy/issues/275

**Comment by tpendragon** [comment]
Fixed.
